### PR TITLE
Notebooks: Fix relative images not rendering on PC for Markdown Cells

### LINKED ISSUE #8090: Notebooks: Relative Images on PC Don't Render Properly
Relative Images on PC Don't Render Properly.

Relative Image

### PR DESCRIPTION
**Pull request by chlafreniere**
Reference to #8090.

### CODE REVIEW

File: src/sql/workbench/parts/notebook/browser/outputs/notebookMarkdown.ts [hunk 1]
```diff
@@ -203,7 +203,7 @@ export class NotebookMarkdownRenderer {
 			href = this.resolveUrl(base, href);
 		}
 		try {
-			href = encodeURI(href).replace(/%25/g, '%');
+			href = encodeURI(href).replace(/%25/g, '%').replace(/%5C/g, '\\');
```
Comment (corivera) [inline src/sql/workbench/parts/notebook/browser/outputs/notebookMarkdown.ts]: Might want to do the backslash replacement first, since the percent replacement might introduce a "%5C" sequence by accident.

Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/browser/outputs/notebookMarkdown.ts]: Nice suggestion, will do. Thanks.
