### PR TITLE
Set target platform for database project from the server metadata

### LINKED ISSUE #20363: Schema Compare failed: The source and target platform must be the same to use Schema Compare for Azure Synapse Dedicated SQL Pool
Azure Data Studio Version: 1.38.0 (user setup)
Commit: dff93c4736269ef2a7e8a225737a0d8354bf0246
Date: 2022-07-26T23:56:16.217Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. create connection to Azure Synapse SQL Pool
2. choose 'Create project from database'
3. commit
4. choose 'Update project from database' which produces the following error:

Schema Compare failed: The source and target platform must be the same to use Schema Compare for Azure Synapse Dedicated SQL Pool

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #20363.
Currently, all the database projects created from the databases are assigned DSP (target platform) as "Sql Server 2019". instead of its current version. The changes in PR reads the server metadata to determine its version and maps & assigns it appropriately to the target platform for the database project.
Steps to repro:
1. Connect to DW server with a user db.
2. Create project from this user db.
-- The project should now be created with appropriate target platform.

This PR doesn't handle the VSCode version of Projects.

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -1399,7 +1399,7 @@ export class ProjectsController {
 		if (utils.getAzdataApi()) {
 			let createProjectFromDatabaseDialog = this.getCreateProjectFromDatabaseDialog(profile as azdataType.IConnectionProfile);
 
-			createProjectFromDatabaseDialog.createProjectFromDatabaseCallback = async (model) => await this.createProjectFromDatabaseCallback(model);
+			createProjectFromDatabaseDialog.createProjectFromDatabaseCallback = async (model) => await this.createProjectFromDatabaseCallback(model, profile as azdataType.IConnectionProfile);
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/projectController.ts:1402]: in case the user changes the connection after opening the create project from db dialog, the connection profile (or connection id if that's all that's needed) should be passed into this callback when it's called by the dialog

File: extensions/sql-database-projects/src/common/constants.ts [hunk 2]
```diff
@@ -593,6 +593,15 @@ export const targetPlatformToVersion: Map<string, string> = new Map<string, stri
 	[SqlTargetPlatform.sqlDW, 'Dw']
 ]);
 
+export const serverVersionToTargetPlatform: Map<number, SqlTargetPlatform> = new Map<number, SqlTargetPlatform>([
```
Comment (kisantia) [inline extensions/sql-database-projects/src/common/constants.ts:596]: let's add "onPrem" to the name of the map so it's clear the Azure versions aren't here

File: extensions/sql-database-projects/src/common/utils.ts [hunk 3]
```diff
@@ -3,7 +3,7 @@
  *  Licensed under the Source EULA. See License.txt in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
 
-import type * as azdataType from 'azdata';
+import * as azdataType from 'azdata';
```
Comment (kisantia) [inline extensions/sql-database-projects/src/common/utils.ts:6]: removing the `type` from this import will break the sql-database-projects-vscode extension. Use `getAzdataApi()` to be able to call functions like `getServerInfo()`. 

Here's a PR with an explanation of what broke when I accidentally got rid of the `type` in the import a few months ago :) https://github.com/microsoft/azuredatastudio/pull/19292

File: extensions/sql-database-projects/src/common/utils.ts [hunk 4]
```diff
@@ -711,3 +711,24 @@ export async function fileContainsCreateTableStatement(fullPath: string, project
...
+ * @returns target platform for the database project
+ */
+export async function getTargetPlatformFromServerVersion(profile: azdataType.IConnectionProfile): Promise<SqlTargetPlatform | undefined> {
+	const serverInfo = await azdataType.connection.getServerInfo(profile.id);
+	const isCloud = serverInfo.isCloud;
+
+	let targetPlatform;
+	if (isCloud) {
+		const engineEdition = serverInfo.engineEditionId;
+		targetPlatform = engineEdition === azdataType.DatabaseEngineEdition.SqlDataWarehouse ? SqlTargetPlatform.sqlDW : (engineEdition === azdataType.DatabaseEngineEdition.SqlDatabase ? SqlTargetPlatform.sqlAzure : undefined);
```
Comment (kisantia) [inline extensions/sql-database-projects/src/common/utils.ts:727]: if it isn't DW, can we just assume it's sqlAzure and skip the check if the engineEditoin is SqlDatabase?

Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/common/utils.ts:727]: Projects support Sql Edge as well (https://github.com/microsoft/azuredatastudio/blob/5d30c5eb88d2386bf4d822fa95098ec8f47e3eca/extensions/sql-database-projects/src/sqldbproj.d.ts). So I thought setting it to SQL Azure wouldn't be completely correct, hence the extra check. But if you think it should safe to skip the additional check, I can do that to.

Comment (kisantia) [reply extensions/sql-database-projects/src/common/utils.ts:727]: I think it should be ok to set the target platform to sqlAzure if it's cloud and not DW. @Benjin any concerns with this? I don't think there are that many people creating projects from edge dbs, and the new edge project template creates projects with the target platform 150.

File: extensions/sql-database-projects/src/controllers/projectController.ts (hunk 1 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/controllers/projectController.ts]: Addressed.

File: extensions/sql-database-projects/src/common/utils.ts (hunk 3 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/common/utils.ts]: Makes sense. Updated it.

File: extensions/sql-database-projects/src/common/utils.ts (hunk 4 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/common/utils.ts]: Updated it for now, waiting on Benjin for confirmation.

**Review by kisantia — APPROVED** [review]

**Comment by SakshiS-harma** [comment]
Created https://github.com/microsoft/azuredatastudio/issues/20576 to track VS code version.
