### PR TITLE
Fixing async server tree error handling and removing timeout. 

### LINKED ISSUE #22737: Object Explorer timeout occurs when should not happen
Consider cases like:
- Expanding a connection node made with Serverless database 
  (takes ~50 seconds to expand since we retry and wait for DB to resume)
- Expand a node where Azure account token needs refresh (user is prompted to login)

These cases will always take more than 45 seconds (default OE timeout), and the second case should wait indefinitely on purpose to allow user to login into AAD account using MFA authentication.

These are common scenarios and OE timeout on parent tree node is causing unwanted disruptions.

@aasimkhan30 Do you think with Async Server tree changes this property is still required? Since we fixed the hang issue by triggering completion event, can we remove this setting?

### LINKED ISSUE #22798: 'Run Kinit' Prompt doesn't show anymore when expanding OE node
Haven't run kinit in a while, tried using integrated auth from my mac to connect to an on prem server, and the experience looks to have regressed.

Stable:

image

Latest insiders:
image

### LINKED ISSUE #22801: Failed to expand node error when expanding Databases Node (not 100% repro rate)
Not 100% repro, but moreso like 20-30%. It's happened multiple times on my machine (x86 Mac), latest insiders.

1. Connect to a server (default/master) via clicking the saved connection on OE
2. <Sometimes, dashboard shows up. Other times, it doesn't. Seems like the pattern is when it doesn't show up, the following occurs:
3. Attempt to expand databases node, wait 45 seconds:

image

ERR Failed to expand node: Error: Failed to expand node
    at p.expandOrRefreshTreeNode (vscode-file://vscode-app/Applications/Azure%20Data%20Studio%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1040:2017) [<root>]
    at async h.getChildren (vscode-file://vscode-app/Applications/Azure%20Data%20Studio%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1396:36511) [<root>]
    at async vscode-file://vscode-app/Applications/Azure%20Data%20Studio%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:797:21670 [<root>]

 ERR Object Explorer task didn't complete within 45 seconds.

WARN Cannot find node status for session: <redacted>

Didn't see much from STS log.

### LINKED ISSUE #22917: Async server tree node expansion timeout not canceled on error
Note: An easy way to repro this is with a local docker instance so you can quickly turn it on/off

1. Add a connection and set the "Connection Timeout" advanced property to something low, like 5 seconds
2. Make the connection so the properties are saved
3. Disconnect
4. Turn off the server
5. Try to connect by expanding the node
6. Wait 5 seconds for it to time out (this happens as expected, error is shown and node is collapsed)

Expected :

Nothing else happens

Actual : 

The following error appears in the console after 45sec (the server tree timeout period)

```
ERR Object Explorer expansion timed out for '': Error: Object Explorer expansion timed out for ''
    at nodeUpdateTimeout (vscode-file://vscode-app/c:/src/azuredatastudio/out/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.js:264:36) [<root>]
    at timer (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:3155:47) [<root>]
    at data.args.<computed> (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:3135:36) [<root>]
```

We should be cancelling this timeout if we get an error for a session .

### PR DESCRIPTION
**Pull request by aasimkhan30**
1. This removes the OE timeout from various async server tree performances. Fixes #22737 and #22801 
2. Previously, Async server tree used to show its own error dialog in case of connection issues, Now, I am avoiding that and let connection service handle and show error dialogs in case of connection issues. Attempts to fix #22798 and fix #22917 
3. Previously, in the case of expansion where there was only one expansion provider, the tree used to not return the error nodes message indicating the exact error that had occured. That's why the user only "failed to expand node" Fixes #22801

### CODE REVIEW

File: src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts [hunk 1]
```diff
@@ -52,12 +51,6 @@ const serverTreeConfig: IConfigurationNode = {
 			'type': 'boolean',
 			'default': true,
 			'description': localize('serverTree.useAsyncServerTree', "Use the new async server tree for the Servers view and Connection Dialog with support for new features such as dynamic node filtering. Requires a restart to take effect.")
-		},
-		'serverTree.nodeExpansionTimeout': {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts:56]: So we're going back to relying on the providers to complete (either successfully or not) in a reasonable amount of time then? And it'll be expected that if there's an issue with the provider and they never return then node expansion could potentially hang forever?

File: src/sql/workbench/services/objectExplorer/browser/asyncServerTreeDataSource.ts [hunk 2]
```diff
@@ -51,17 +51,14 @@ export class AsyncServerTreeDataSource implements IAsyncDataSource<ConnectionPro
...
-				}
+				return await this._objectExplorerService.resolveTreeNodeChildren(element.getSession()!, element);
 			}
 		} catch (err) {
 			if (element instanceof TreeNode) {
 				element.errorStateMessage = err.message ?? err;
 			}
-			if (err.message) {
+			// In case of connection profile, we won't show the error here and let the connection service handle it.
+			if (err.message && !(err instanceof ConnectionError)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/asyncServerTreeDataSource.ts:61]: err could be anything, not necessarily an Error object. I'd suggest using [getErrorMessage](https://github.com/Microsoft/azuredatastudio/blob/main/src/vs/base/common/errors.ts#L202) and then using that in all the places you want to get the error message in this catch.

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts [hunk 3]
```diff
@@ -601,7 +563,11 @@ export class ObjectExplorerService implements IObjectExplorerService {
 	}
 
 	private mergeResults(allProviders: azdata.ObjectExplorerProviderBase[], resultMap: Map<string, azdata.ObjectExplorerExpandInfo>, nodePath: string): azdata.ObjectExplorerExpandInfo | undefined {
-		let finalResult: azdata.ObjectExplorerExpandInfo | undefined = undefined;
+		let finalResult: azdata.ObjectExplorerExpandInfo | undefined = {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts:566]: This can't be undefined anymore from the looks of it

File: src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts [hunk 4]
```diff
@@ -184,52 +182,58 @@ export class TreeUpdateUtils {
...
-						onConnectSuccess: () => tree.removeTraits('loading', [connection]),
-						onDisconnect: () => { },
-						onConnectCanceled: rejectOrCancelCallback,
-					};
-				}
+		try {
+			if (!connectionManagementService.isProfileConnected(connection)) {
+				// don't try to reconnect if currently connecting
+				if (connectionManagementService.isProfileConnecting(connection)) {
+					return undefined;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts:190]: Do you want to return the connection here instead? It would be helpful to add comments about what this is returning so callers know what to expect.

**Review by kburtram — APPROVED** [review]
Looks like we're still working through some fundamental use cases with the new tree control.  Are we planning to use the old tree control for May release and then enable the new one in July once we've had sufficient stabilization time?

**Review by cssuh — APPROVED** [review]

File: src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts (hunk 1 above)
Comment (aasimkhan30) [reply src/sql/workbench/contrib/objectExplorer/common/serverGroup.contribution.ts:56]: Yes, for now. The timeout are unstable as they are not cleared sometimes causing intermittent issues. We still have fixed race conditions so it is not completely undoing the previous work.

File: src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts (hunk 4 above)
Comment (aasimkhan30) [reply src/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.ts:190]: I haven't changed this part of the code. Just enclose this within try catch

File: src/sql/workbench/services/objectExplorer/browser/asyncServerTreeDataSource.ts [hunk 5]
```diff
@@ -51,18 +52,16 @@ export class AsyncServerTreeDataSource implements IAsyncDataSource<ConnectionPro
...
 			} else if (element instanceof TreeNode) {
-				if (element.children) {
-					return element.children;
-				} else {
-					return await this._objectExplorerService.resolveTreeNodeChildren(element.getSession()!, element);
-				}
+				return await this._objectExplorerService.resolveTreeNodeChildren(element.getSession()!, element);
 			}
 		} catch (err) {
+			const errorMessage = getErrorMessage(err) ?? err;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/asyncServerTreeDataSource.ts:58]: This will always return a string so the null coalesce part is unnecessary.

```suggestion
			const errorMessage = getErrorMessage(err);
```

**Review by Charles-Gagnon — APPROVED** [review]
This is a lot of changes to be getting in at the last minute, so I definitely agree with Karl that we should probably hold off on enabling the async tree for stable until the July release. Make sure you're spending plenty of time (and asking others to help out) testing both trees though, there's a lot of intermixed logic here and I'm worried that some of these changes might cause issues in the old tree as well.

**Review by cheenamalhotra — APPROVED** [review]
