### PR TITLE
accessible radio card

### LINKED ISSUE #7933: A11y_Deploymentconfigurationtemplate_ScreenReader:Table mark up is missing under AKS-dev-test.
**GitHubTags**: #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG1.3.1;#WCAG4.2.3;#WCAG4.1.2;#WCAG4.2.1#DesktopApp;#Keyboard;#VoiceOver;#Mac;
**Environment Details:**Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 32df727
Date: 2019-10-08T19:18:43.743Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
**Repro Steps:**
1.Install /Launch the application Azure data studio.
2.Navigate to connections and click on more action button.
3.Select “Deploy SQL Server big data cluster” from more action drop down.
4.Click on “Deploy SQL Server big data cluster”.
5. "Select the deployment option" screen gets open.
6.check the I accept check box and click on select button.
7. Deployment template configuration screen gets open.
8. Start VoiceOver and navigate with the help of ctrl + option 
+ forward arrow up and down arrow and observe the announcement.
Actual:
Issue 1. Table mark up is missing for the "Aks -dev-test tab" and the remaining tab on the screen.
Issue 2. Table name should be announced by the NVDA.
Issue 3. Row and column reference should be announced by the NVDA.
Issue 4. column header should be marked as a column header .
Expected:
Issue 1.There should be table mark up "Aks -dev-test tab" and the reaming tab on the screen.
Issue 2. Table name should be announced by the NVDA.
Issue 3. Row and column reference should be announced by the NVDA.
Issue 4. column header should be marked as a column header .
User Impact:
In Aks -dev-test tab below content should be marked as table as user will unable to understand the relation with the correspondent data.
Screen reader User will
Attachment for Reference:
[A11y_Deployment configuration template_Screenreader.pptx](https://github.com/microsoft/azuredatastudio/files/3760489/A11y_Deployment.configuration.template_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #7936: A11y_AzureDataStudio_Selectthedeploymentoption_ScreenReader:Missing grouping for "Select the deployment option screen" Screen radio buttons.
**GitHubTags:** #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG3.3.2;#DesktopApp;#VoiceOver;#Mac
**Environment Details:**
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 32df727
Date: 2019-10-08T19:18:43.743Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS:  MacOS Mojave 10.14.6
**Repro Steps:**
1.Install /Launch the application Azure data studio.
2.Navigate to connections and click on more action button.
3.Select “Deploy SQL Server big data cluster” from more action drop down.
4.Click on “Deploy SQL Server big data cluster”.
5. "Select the deployment option" screen gets open.
6. Start Voice over and navigate with the help of up and down arrow and Observe the announcement.
**Actual**:
Missing grouping for the for the for "step 1 Select the deployment option screen"
**Expected:**
Groping should be marked for the three radio buttons available on the screen.
**User Impact:**
User will not able to directly relate with the three radio button which is present on the screen.
Attachment for Reference:
[7936_A11y_AzureDataStudio_Selectthedeploymentoption_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3760572/7936_A11y_AzureDataStudio_Selectthedeploymentoption_ScreenReader.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by alanrenmsft**
Problems solved by this PR:
1. screen readers do not know the grouping of our custom radio card, for custom radio elements, they need to be placed directly under the group div in order to be recognized by screen readers.
2. our current card doesn't support the standard radio group keyboard navigation. 
    tab: navigate away from the group
    left or up key: select the previous radio element. special case: first element -> last element
    right or down key: select the next radio element. special case: last element -> first element
3. No centralized place to manage the card selection/de-selection logic
4. the card description is not organized using tables

This PR fixes #7936  and fixes #7933

### CODE REVIEW

**Comment by alanrenmsft** [comment]
will have a follow up PR to deprecate the old card component

File: extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts [hunk 1]
```diff
@@ -51,99 +62,83 @@ export class DeploymentProfilePage extends WizardPageBase<DeployClusterWizard> {
...
-			this.loadCards().then(() => {
-				this._loadingComponent!.loading = false;
-			}, (error) => {
-				this.wizard.wizardObject.message = {
-					level: azdata.window.MessageLevel.Error,
-					text: localize('deployCluster.loadProfileFailed', "Failed to load the deployment profiles: {0}", error.message)
-				};
-				this._loadingComponent!.loading = false;
+			return view.initializeModel(form).then(() => {
+				return this.loadCards().then(() => {
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts]: Dangling promise here. It'd probably just be easiest to move the error handler code into the out later (if you do make sure you make the inner call async so a thrown error is handled appropriately)

File: extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts [hunk 2]
```diff
@@ -51,99 +62,83 @@ export class DeploymentProfilePage extends WizardPageBase<DeployClusterWizard> {
...
+				{
+					label: localize('deployCluster.dataPoolLabel', "Data"),
+					value: profile.dataReplicas.toString()
+				}, {
+					label: localize('deployCluster.hdfsLabel', "HDFS + Spark"),
+					value: profile.hdfsReplicas.toString()
+				}]
+		};
+		const storageDescription: azdata.RadioCardDescription = {
+			ariaLabel: localize('deployCluster.scaleDescription', "Scale description"),
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts]: >Scale [](start = 58, length = 5)

Storage description?

File: src/sql/azdata.proposed.d.ts [hunk 3]
```diff
@@ -113,4 +113,40 @@ declare module 'azdata' {
...
+		label: string;
+		descriptions?: RadioCardDescription[];
+		icon?: string | vscode.Uri | { light: string | vscode.Uri; dark: string | vscode.Uri };
+	}
+
+	export interface RadioCardDescription {
+		ariaLabel: string;
+		labelHeader: string;
+		valueHeader?: string;
+		contents: RadioCardLabelValuePair[];
```
Comment (Charles-Gagnon) [inline src/sql/azdata.proposed.d.ts]: nit: required properties above optional ones

File: src/sql/workbench/browser/modelComponents/iconUtils.ts [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+
+import { IdGenerator } from 'vs/base/common/idGenerator';
+import { removeCSSRulesContainingSelector, createCSSRule, asCSSUrl } from 'vs/base/browser/dom';
+import { URI } from 'vs/base/common/uri';
+
+const ids = new IdGenerator('model-view-component-icon-');
+
+export type IUserFriendlyIcon = string | URI | { light: string | URI; dark: string | URI };
+
+export function getIconClass(iconPath: IUserFriendlyIcon, className?: string): string {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/iconUtils.ts]: >getIconClass [](start = 16, length = 12)

This is also removing the existing CSS rules for the specified class so it's not just a getter suggest updating the name to something like "clearAndSetIconClassRules"

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+		}
+		return this.iconClasses[card.id];
+	}
+
+	public setProperties(properties: { [key: string]: any }) {
+		super.setProperties(properties);
+		if (this.selectedCardId) {
+			const filteredCards = this.cards.filter(c => { return c.id === this.selectedCardId; });
+			if (filteredCards.length === 1) {
+				this.selectCard(filteredCards[0]);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: Why this extra logic? It would make sense to me that you'd just select the first one if there were duplicates - in that case just using find seems appropriate.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+	public selectCard(card: azdata.RadioCard): void {
+		if (!this.enabled || this.selectedCard === card || this.cards.indexOf(card) === -1) {
+			return;
+		}
+		this.selectedCard = card;
+		this._changeRef.detectChanges();
+		const cardElement = this.getCardElement(this.selectedCard);
+		cardElement.nativeElement.focus();
+		this.selectedCardId = card.id;
+		this.fireEvent({
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: I'd suggest moving the logic for updating the selected card and its id into a single function - we never want to update those separately. Doing it in the selectedCardId setter for example.

**Comment by chlafreniere** [comment]
Tests 😄? Those utils seem mighty unit-testable to me especially 😃!

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts [hunk 7]
```diff
@@ -0,0 +1,179 @@
...
+import 'vs/css!./media/card';
+
+import {
+	Component, Inject, ChangeDetectorRef, forwardRef,
+	ElementRef, OnDestroy, Input, ViewChildren, QueryList
+} from '@angular/core';
+
+import { IComponent, IComponentDescriptor, IModelStore, ComponentEventType } from 'sql/workbench/browser/modelComponents/interfaces';
+import { ComponentBase } from 'sql/workbench/browser/modelComponents/componentBase';
+import * as azdata from 'azdata';
```
Comment (chlafreniere) [inline src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: organize usings

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts [hunk 8]
```diff
@@ -0,0 +1,179 @@
...
+
+	ngOnDestroy(): void {
+		Object.keys(this.iconClasses).forEach((key) => {
+			DOM.removeCSSRulesContainingSelector(this.iconClasses[key]);
+		});
+		this.baseDestroy();
+	}
+
+	onKeyDown(event: KeyboardEvent): void {
+		if (!this.enabled || this.cards.length === 0) {
```
Comment (chlafreniere) [inline src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: may want to check for this.cards as well

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts [hunk 9]
```diff
@@ -0,0 +1,179 @@
...
+		return this.getPropertyOrDefault<azdata.RadioCardGroupComponentProperties, string | undefined>((props) => props.selectedCardId, undefined);
+	}
+
+	public set selectedCardId(newValue: string | undefined) {
+		this.setPropertyFromUI<azdata.RadioCardGroupComponentProperties, string | undefined>((props, value) => props.selectedCardId = value, newValue);
+	}
+
+	public getIconClass(card: azdata.RadioCard): string {
+		if (!this.iconClasses[card.id]) {
+			this.iconClasses[card.id] = `cardIcon icon ${getIconClass(card.icon)}`;
```
Comment (chlafreniere) [inline src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: I'm a little confused around why something is being set in a method with the word 'get' in the name. Can you clarify?

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts [hunk 10]
```diff
@@ -0,0 +1,179 @@
...
+
+	public selectCard(card: azdata.RadioCard): void {
+		if (!this.enabled || this.selectedCard === card || this.cards.indexOf(card) === -1) {
+			return;
+		}
+		this.selectedCard = card;
+		this._changeRef.detectChanges();
+		const cardElement = this.getCardElement(this.selectedCard);
+		cardElement.nativeElement.focus();
+		this.selectedCardId = card.id;
```
Comment (chlafreniere) [inline src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: if we already have a this.selectedCard, do we need to keep track of its id in a different var as well? Seems rife for a sneaky bug

File: src/sql/workbench/browser/modelComponents/media/card.css [hunk 11]
```diff
@@ -122,7 +113,7 @@
 	border-radius: 50%;
 	background-color: white;
 	border-width: 1px;
-	border-color: rgb(0, 120, 215);
+	border-color: rgb(214, 214, 214);
```
Comment (chlafreniere) [inline src/sql/workbench/browser/modelComponents/media/card.css]: was this a contrast issue for accessibility purposes?

File: extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts [hunk 12]
```diff
@@ -61,10 +59,30 @@ export class ResourceTypePickerDialog extends DialogBase {
 		tab.registerContent((view: azdata.ModelView) => {
 			const tableWidth = 1126;
 			this._view = view;
-			this.resourceTypeService.getResourceTypes().sort((a: ResourceType, b: ResourceType) => {
+			const resourceTypes = this.resourceTypeService.getResourceTypes().sort((a: ResourceType, b: ResourceType) => {
 				return (a.displayIndex || Number.MAX_VALUE) - (b.displayIndex || Number.MAX_VALUE);
-			}).forEach(resourceType => this.addCard(resourceType));
-			this._cardsContainer = view.modelBuilder.flexContainer().withItems(this._resourceTypeCards, { flex: '0 0 auto', CSSStyles: { 'margin-bottom': '10px' } }).withLayout({ flexFlow: 'row' }).component();
+			});
+			this._cardGroup = view.modelBuilder.radioCardGroup().withProperties<azdata.RadioCardGroupComponentProperties>({
```
Comment (chlafreniere) [inline extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: Is the layout for the resource deployment dialog any different after these changes?

File: extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts [hunk 13]
```diff
@@ -15,28 +15,39 @@ const localize = nls.loadMessageBundle();
...
 	}
 
 	public initialize(): void {
 		this.pageObject.registerContent((view: azdata.ModelView) => {
-			this._view = view;
-			this._cardContainer = view.modelBuilder.flexContainer().withLayout({ flexFlow: 'row', flexWrap: 'wrap' }).component();
+			this._cardContainer = view.modelBuilder.radioCardGroup().withProperties<azdata.RadioCardGroupComponentProperties>({
+				cards: [],
+				cardWidth: '240px',
+				cardHeight: '340px',
```
Comment (chlafreniere) [inline extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts]: was the card height changed on purpose

Comment (alanrenmsft) [reply extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts]: yes, give it more space for the bottom margin

File: extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts (hunk 12 above)
Comment (alanrenmsft) [reply extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: it looks exactly the same

File: src/sql/workbench/browser/modelComponents/media/card.css (hunk 11 above)
Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/media/card.css]: the old color is blueish, it might confuse people since that is normally the focused border color. I am changing it to the same as the border color when the card is not being focused.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 10 above)
Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: hmm, the selectedCardId is for the extension to use and the this.selectedCard is the internal state of the card group component. I won't be able to simply do obj assign since for objects it is reference based comparison.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 9 above)
Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: lazy initialization of the icon css class.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 8 above)
Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: default value for this.cards is [], it should be safe to skip the null check for it.

File: src/sql/workbench/browser/modelComponents/media/card.css (hunk 11 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/media/card.css]: And you verified this passes accessibility requirements for contrast in both light and dark mode?

**Comment by alanrenmsft** [comment]
@Charles-Gagnon I didn't introduce new colors, all the colors have been tested. here are the screenshots, I should have included in my original PR :)
light theme - normal
Screen Shot 2019-12-02 at 11 15 31 AM
light theme - selected/focused
Screen Shot 2019-12-02 at 11 16 00 AM

dark theme - normal
Screen Shot 2019-12-02 at 11 16 23 AM

dark theme - selected/focused
Screen Shot 2019-12-02 at 11 16 31 AM

File: extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts (hunk 2 above)
Comment (alanrenmsft) [reply extensions/resource-deployment/src/ui/deployClusterWizard/pages/deploymentProfilePage.ts]: good catch.

**Comment by Benjin** [comment]
In the future, it'd be awesome if something that addresses four different issues were split up into different stacking PRs; that can be easier to understand the specific impact of each fix.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts [hunk 14]
```diff
@@ -0,0 +1,179 @@
...
+			this.iconClasses[card.id] = `cardIcon icon ${getIconClass(card.icon)}`;
+		}
+		return this.iconClasses[card.id];
+	}
+
+	public setProperties(properties: { [key: string]: any }) {
+		super.setProperties(properties);
+		if (this.selectedCardId) {
+			const filteredCards = this.cards.filter(c => { return c.id === this.selectedCardId; });
+			if (filteredCards.length === 1) {
```
Comment (Benjin) [inline src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: Do we want to log anything here if the `selectedCardId` isn't found (length === 0)?

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts [hunk 15]
```diff
@@ -0,0 +1,179 @@
...
+		}
+
+		let e = new StandardKeyboardEvent(event);
+		if (e.keyCode === KeyCode.Enter || e.keyCode === KeyCode.Space) {
+			if (this.focusedCard && !this.selectedCard) {
+				this.selectCard(this.focusedCard);
+			}
+			DOM.EventHelper.stop(e, true);
+		}
+		else if (e.keyCode === KeyCode.LeftArrow || e.keyCode === KeyCode.UpArrow) {
```
Comment (Benjin) [inline src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: this implies cards are only ever arranged along one dimension; are they never in an grid (where one might want left and up to have different behavior)?

Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: currently if we have too many cards to fit in one line it will wrap vertically. see screenshots below. Pressing down key cause the next card to be selected is a little bit unexpected but acceptable especially we want to keep it consistent when there is only one row.
Screen Shot 2019-12-03 at 9 35 36 AM

Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: Does pressing down arrow in a normal radio group move to the next one if they're all on a single line?

Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: yes, radio card group behaves exactly the same as plain radio buttons

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_radio

Screen Shot 2019-12-03 at 9 47 47 AM

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 14 above)
Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: i added a console.error for it, most likely this should be a dev time error.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 5 above)
Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: adding handler in case there are no or multiple cards matching the giving ID.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 7 above)
Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: found this extension does the job pretty good: vsc-organize-imports :)

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 14 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: Where? I'm not seeing that. 

And regardless - don't use console.log/err/etc directly. Use the ILogService instead if you just want to log something to the console.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 7 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: If we're going to start caring about this we should actually enforce it via a tslint/hygiene rule. Otherwise this is just going to be something where people have different opinions and it's never going to be consistent. 

(I personally don't really care about ordering them and don't see a huge amount of value in enforcing any sort of ordering. But if others care I'm fine going along with it as long as we have an automated check that validates the ordering)

Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: lets talk about it in today's meeting.

**Comment by alanrenmsft** [comment]
> For the future: it'd be awesome if something that addresses four different issues were split up into different PRs. That makes it easier to understand the specific impact of each fix, and makes it possible to approve/reject piecemeal.

definitely, that is what i usually do, this one is kind of special, we need a new component type to address all 4 issues.

File: src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts (hunk 6 above)
Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/radioCardGroup.component.ts]: I have removed the setter and moved that to the selectCard method to avoid calling one but the other.
