### PR TITLE
#3585: Canceled message when changing kernel

### LINKED ISSUE #3585: Cancelled msg - when kernel is changed
1. Run a cell with one of the Spark kernels
2. While execution is in progress, change the kernel
3. Cancelled message is displayed. We may need to display a user friendly message if it's an exception

image

### PR DESCRIPTION
**Pull request by rajmusuku**
This is to fix #3585. Improved the error handling by adding a message 'Query execution is canceled' when changing kernel, while execution is in progress. Please let me know the wording if something needs to be added.

### CODE REVIEW

File: src/sql/parts/notebook/models/cell.ts [hunk 1]
```diff
@@ -230,13 +230,15 @@ export class CellModel implements ICellModel {
...
 			if (error.message === 'Canceled') {
 				// swallow the error
+				message = localize('executionCanceled', 'Query execution is canceled');
+			}else{
+				message = notebookUtils.getErrorMessage(error);
 			}
-			let message = notebookUtils.getErrorMessage(error);
 			this.sendNotification(notificationService, Severity.Error, message);
 			// TODO track error state for the cell
-			throw error;
```
Comment (Charles-Gagnon) [inline src/sql/parts/notebook/models/cell.ts]: Don't you still want to throw the error if it wasn't 'Canceled'?

File: src/sql/parts/notebook/models/cell.ts [hunk 2]
```diff
@@ -230,13 +230,15 @@ export class CellModel implements ICellModel {
 				}
 			}
 		} catch (error) {
+			let message: string;
 			if (error.message === 'Canceled') {
 				// swallow the error
+				message = localize('executionCanceled', 'Query execution is canceled');
+			}else{
```
Comment (Charles-Gagnon) [inline src/sql/parts/notebook/models/cell.ts]: nit: fix spacing

File: src/sql/parts/notebook/models/cell.ts [hunk 3]
```diff
@@ -230,13 +230,15 @@ export class CellModel implements ICellModel {
 				}
 			}
 		} catch (error) {
+			let message: string;
 			if (error.message === 'Canceled') {
 				// swallow the error
+				message = localize('executionCanceled', 'Query execution is canceled');
```
Comment (Charles-Gagnon) [inline src/sql/parts/notebook/models/cell.ts]: How about 'Query execution was canceled'? Is canceled is a little weird grammar-wise.

File: src/sql/parts/notebook/models/cell.ts (hunk 1 above)
Comment (rajmusuku) [reply src/sql/parts/notebook/models/cell.ts]: No. 'throw error' used to be in catch block and so there is no way of throwing error message when it wasn't canceled

Comment (Charles-Gagnon) [reply src/sql/parts/notebook/models/cell.ts]: I'm not sure what you mean - it would look like this 
```
} catch (error) {
			let message: string;
			if (error.message === 'Canceled') {
				// swallow the error
				message = localize('executionCanceled', 'Query execution was canceled');
			} else {
				message = notebookUtils.getErrorMessage(error);
			}

                                this.sendNotification(notificationService, Severity.Error, message);
                        if(error.message === 'Canceled') {
                                 throw error;
                        }
```

Comment (rajmusuku) [reply src/sql/parts/notebook/models/cell.ts]: I don't think throwing error is needed in this case since we are notifying the error in the catch back itself. This runCell method is used in three different places and it's a simple action which doesn't have any dependency to pass it on. We don't seem to be handling error in all three parent methods.

Comment (Charles-Gagnon) [reply src/sql/parts/notebook/models/cell.ts]: Sounds good. Might want to move the "swallow error" comment out of the if though since we're swallowing all errors.

Does the error display in any other way? Like in the cell itself? The notification is nice but it might be good to have the grid actually display that an error occurred too.

Comment (rajmusuku) [reply src/sql/parts/notebook/models/cell.ts]: Error displays in all cases whenever there is an exception, however, we are customizing the error message only in case of canceled scenario. runCell method corresponds to each code component in notebook not in a Grid. We will need to handle it in a different way when we implement run all cells. Folks can correct me if it doesn't make sense.
