### PR TITLE
Fixing result grid plans not opening execution plan editor.

### LINKED ISSUE #20964: ShowPlan XML link doesn't open execution plan editor
- Azure Data Studio Version: `insiders`

Steps to Reproduce:

1. Open a SQL query with some statements and run Estimated Plan command
2. Click the Show Plan XML link

Expected: Show Plan document is opened

Actual: Document opens then closes.  Below exception is raised in application log.

```
Cannot read properties of undefined (reading 'hidden'): TypeError: Cannot read properties of undefined (reading 'hidden')
    at showColumn (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1206:20829)
    at Object.eval [as updateDirectives] (ng:///w/s.ngfactory.js:634:24)
    at Object.updateDirectives (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12625:72)
    at checkAndUpdateView (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12151:14)
    at callViewAction (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514:21)
```

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #20964
It seems it had nothing to do with the merge. When the new execution plan editor tab was opened, dispose was called and the editor input was disposed causing the new tab to close.

### CODE REVIEW

File: src/sql/workbench/contrib/query/browser/gridPanel.ts [hunk 1]
```diff
@@ -726,7 +726,7 @@ export abstract class GridTableBase<T> extends Disposable implements IView {
 						graphFileType: result.queryExecutionPlanFileExtension
 					};
 
-					const executionPlanInput = this._register(this.instantiationService.createInstance(ExecutionPlanInput, undefined, executionPlanGraphInfo));
+					const executionPlanInput = this.instantiationService.createInstance(ExecutionPlanInput, undefined, executionPlanGraphInfo);
```
Comment (kburtram) [inline src/sql/workbench/contrib/query/browser/gridPanel.ts:729]: do we still need to dispose the input somehow?  or it get's cleaned up by the editorService?

**Review by kburtram — APPROVED** [review]

File: src/sql/workbench/contrib/query/browser/gridPanel.ts (hunk 1 above)
Comment (aasimkhan30) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:729]: The inputs are disposed whenever the editor tab associated with it is closed. So, no cleanups are required on this end of the code.
