### PR TITLE
Patching issue where error would be thrown when backup file already exists for sqlproj

### LINKED ISSUE #22573: Updating .sqlproj for cross-plat fails when backup file already present
Updating this bug with info from the investigation (elaborated upon in [this comment](https://github.com/microsoft/azuredatastudio/issues/22573#issuecomment-1494746756).

Updating a .sqlproj file fails when a file already exists at the expected backup location (e.g. `MyProject.sqlproj` -> `MyProject.sqlproj_backup`).  This can be fixed properly in DacFx by appending an incrementing number to the extension (`MyProject.sqlproj_backup2`) or a work-around can be added in ADS by renaming an existing backup file if one already exists before calling down into DacFx.  I plan on doing both, DacFx for completeness and ADS for expediency.

[.sqlproj that I've been using to repro](https://gist.githubusercontent.com/Benjin/53ee533800f89c6d72401655a0c69955/raw/76dc7d3e8f2ca09bb8f2ef0dd3f536e619c4920e/LegacyDatabaseProject.sqlproj)

### PR DESCRIPTION
**Pull request by Benjin**
Fixes #22573 by renaming existing backup file with an incrementing counter

### CODE REVIEW

File: extensions/sql-database-projects/src/models/project.ts [hunk 1]
```diff
@@ -439,6 +440,18 @@ export class Project implements ISqlProject {
...
+		// due to bug in DacFx.Projects, if a backup file already exists this will fail
+		// workaround is to rename the existing backup
+
+		if (await utils.exists(this.projectFilePath + '_backup')) {
+			let counter = 2;
+			while (await utils.exists(this.projectFilePath + '_backup' + counter)) {
+				counter++;
+			}
+
+			await fs.rename(this.projectFilePath + '_backup', this.projectFilePath + '_backup' + counter);
```
Comment (SakshiS-harma) [inline extensions/sql-database-projects/src/models/project.ts:452]: Is it possible that the backup file has a Write hold, and the code won't be able to rename it?

Comment (Benjin) [reply extensions/sql-database-projects/src/models/project.ts:452]: Yes, but the the calling code will display that error (once #22612 goes in).

This is just a work-around until the proper fix can be implemented in DacFx.Projects, but I think pushing a Projects update (and therefore STS) is more than we should do for this during Ask mode.

**Review by SakshiS-harma — APPROVED** [review]
