### PR TITLE
Import Flat File Wizard - hangs at table schema

### LINKED ISSUE #9748: Import Flat File Wizard - hangs at table schema
Azure Data Studio Version: 1.16.1
Steps to Reproduce:

Download Azure Data Studio 1.16.1 Mac
Install the SQL Server Import 0.14.0

Launch Flat file import wizard. When selecting anything other than master Table Schema area just hangs and I cannot use this tool. 
image

Does anyone know how to fix this?

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #9748

### CODE REVIEW

**Comment by aaomidi** [comment]
This looks good to me, but i'd wait for someone with more knowledge behind SQL to approve this.

File: extensions/import/src/wizard/pages/fileConfigPage.ts [hunk 1]
```diff
@@ -269,8 +269,18 @@ export class FileConfigPage extends ImportPage {
 		let connectionUri = await azdata.connection.getUriForConnection(this.model.server.connectionId);
 		let queryProvider = azdata.dataprotocol.getProvider<azdata.QueryProvider>(this.model.server.providerName, azdata.DataProviderType.QueryProvider);
 
-		const escapedQuotedDb = this.databaseDropdown.value ? `[${(<azdata.CategoryValue>this.databaseDropdown.value).name.replace(/]/g, ']]')}].` : '';
-		const query = `SELECT name FROM ${escapedQuotedDb}sys.schemas`;
+		let currentServer = await azdata.connection.getServerInfo(this.model.server.connectionId);
+
+		let query: string;
+
+		// Azure SQL server doesn't support use statements.
```
Comment (Charles-Gagnon) [inline extensions/import/src/wizard/pages/fileConfigPage.ts:276]: So first off - this isn't a use statement so the comment doesn't really make sense here. 

Second - Azure DOES support db-qualified names as long as you're connected to the DB you're trying to query. So what that implies is that if the user uses a connection to a user-DB and then selects a different DB from the dropdown the query fails (as expected).

What we really should be doing is establishing a new connection to that specific database. Because otherwise we'll get the wrong list of schemas because the connection is always going to be to the original DB.

Comment (aasimkhan30) [reply extensions/import/src/wizard/pages/fileConfigPage.ts:276]: I have used the change database API to resolve this issue. Please check the updated code

**Comment by aasimkhan30** [comment]
Also, added a fix for #9361

File: extensions/import/src/wizard/pages/fileConfigPage.ts [hunk 2]
```diff
@@ -146,13 +149,24 @@ export class FileConfigPage extends ImportPage {
 			return false;
 		}
 
-		let values = await this.getDatabaseValues();
+		let serverDefaultDatabase = this.model.server.options.database;
```
Comment (Charles-Gagnon) [inline extensions/import/src/wizard/pages/fileConfigPage.ts:152]: And to make sure - this is going to default to the database the user launched the import dialog from?

File: extensions/import/src/wizard/pages/fileConfigPage.ts [hunk 3]
```diff
@@ -266,11 +280,15 @@ export class FileConfigPage extends ImportPage {
...
+
 		let connectionUri = await azdata.connection.getUriForConnection(this.model.server.connectionId);
+		let connection = await azdata.connection.getConnection(connectionUri);
+		connection.databaseName = this.model.database;
+
 		let queryProvider = azdata.dataprotocol.getProvider<azdata.QueryProvider>(this.model.server.providerName, azdata.DataProviderType.QueryProvider);
 
 		const escapedQuotedDb = this.databaseDropdown.value ? `[${(<azdata.CategoryValue>this.databaseDropdown.value).name.replace(/]/g, ']]')}].` : '';
-		const query = `SELECT name FROM ${escapedQuotedDb}sys.schemas`;
+		let query = `SELECT name FROM ${escapedQuotedDb}sys.schemas`;
```
Comment (Charles-Gagnon) [inline extensions/import/src/wizard/pages/fileConfigPage.ts:291]: Just leave this as const. It's good practice to default vars to const and if only if you need to modify them change to let.

File: extensions/import/src/wizard/pages/fileConfigPage.ts [hunk 4]
```diff
@@ -266,11 +280,15 @@ export class FileConfigPage extends ImportPage {
...
 	private async populateSchemaDropdown(): Promise<boolean> {
 		this.schemaLoader.loading = true;
+
 		let connectionUri = await azdata.connection.getUriForConnection(this.model.server.connectionId);
+		let connection = await azdata.connection.getConnection(connectionUri);
+		connection.databaseName = this.model.database;
+
 		let queryProvider = azdata.dataprotocol.getProvider<azdata.QueryProvider>(this.model.server.providerName, azdata.DataProviderType.QueryProvider);
 
 		const escapedQuotedDb = this.databaseDropdown.value ? `[${(<azdata.CategoryValue>this.databaseDropdown.value).name.replace(/]/g, ']]')}].` : '';
```
Comment (Charles-Gagnon) [inline extensions/import/src/wizard/pages/fileConfigPage.ts:290]: At this point since we're connecting to the database I don't see the point in using the 3 part name here anyways so I'd suggest just getting rid of it and querying sys.schemas directly.

File: extensions/import/src/wizard/pages/fileConfigPage.ts (hunk 2 above)
Comment (aasimkhan30) [reply extensions/import/src/wizard/pages/fileConfigPage.ts:152]: Yes, I'm initially defaulting to the database found in the connection.
