### PR TITLE
emit better errors for azure access failure

### LINKED ISSUE #11499: Azure fields in Deployment dialog will fail if account is stale
If the account chosen is stale (needs to be re-authenticated) then the queries to get the subscriptions/RGs will fail without any indication what the issue is. 

This happens at https://github.com/microsoft/azuredatastudio/blob/main/extensions/resource-deployment/src/ui/modelViewUtils.ts#L906 and https://github.com/microsoft/azuredatastudio/blob/main/extensions/resource-deployment/src/ui/modelViewUtils.ts#L981.

We should be checking if isStale is true and if it is then refreshing the account before attempting to fetch the resources.

### PR DESCRIPTION
**Pull request by ranasaria**
Improves error message shown to the user when there is a failure to fetch the subscription/resource group. Here is what the improved messages look like:
image

The improved messages are emitted when the account is chosen is no longer available or is no longer signed in. Here are the sample messages for each case:

1. The selected account 'Arvind Ranasaria - arvran@microsoft.com (iIBqJnswLig1ZXx3fBnlL0fBT9XNVk1EDi2eVXTMazs)' is no longer available. Please click the 'Sign in' button to add it again or select a different account.
2. The access token for selected account 'Arvind Ranasaria - arvran@microsoft.com (acc41c7a-3409-4ece-bd95-39ad3e31dd05)' is no longer valid. Please click the 'Sign in' button and refresh the account or select a different account.

This PR fixes #11499.

### CODE REVIEW

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 1]
```diff
@@ -756,7 +756,18 @@ async function createRadioOptions(context: FieldContext, getRadioButtonInfo?: ((
...
 }
 
+const enum AccountStatus {
+	notFound = 0,
+	isStale,
+	isNotStale,
+}
 
+async function getAccountStatus(account: azdata.Account): Promise<AccountStatus> {
+	const refreshedAccount = (await azdata.accounts.getAllAccounts()).filter(ac => ac.key.accountId === account.key.accountId).shift();
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:766]: Just use .find instead of filter

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 2]
```diff
@@ -942,14 +957,31 @@ async function handleSelectedAccountChanged(
...
+	return `${subscription.name} (${subscription.id})`;
+}
+
+async function showAzureAccessError(selectedAccount: azdata.Account, error: any, unexpectedErrorMessage: string) {
+	switch (await getAccountStatus(selectedAccount)) {
+		case AccountStatus.notFound:
+			vscode.window.showErrorMessage(localize('azure.accounts.accountNotFoundError', "The selected account '{0}' is no longer available. Kindly add it back by signing in.\n Error Details: {1}.", getAccountDisplayString(selectedAccount), getErrorMessage(error)));
+			break;
+		case AccountStatus.isStale:
+			vscode.window.showErrorMessage(localize('azure.accounts.accountStaleError', "The access token for selected account '{0}' is no longer valid. Kindly sign in again to refresh your credentials.\n Error Details: {1}.", getAccountDisplayString(selectedAccount), getErrorMessage(error)));
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:981]: `Please click the sign in button and refresh the account or select a different account`

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 3]
```diff
@@ -942,14 +957,31 @@ async function handleSelectedAccountChanged(
...
+}
+
+function getSubscriptionDisplayString(subscription: azureResource.AzureResourceSubscription) {
+	return `${subscription.name} (${subscription.id})`;
+}
+
+async function showAzureAccessError(selectedAccount: azdata.Account, error: any, unexpectedErrorMessage: string) {
+	switch (await getAccountStatus(selectedAccount)) {
+		case AccountStatus.notFound:
+			vscode.window.showErrorMessage(localize('azure.accounts.accountNotFoundError', "The selected account '{0}' is no longer available. Kindly add it back by signing in.\n Error Details: {1}.", getAccountDisplayString(selectedAccount), getErrorMessage(error)));
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:978]: `is no longer available. Click sign in to add it again.`

File: extensions/resource-deployment/src/ui/modelViewUtils.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts]: done

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts]: done

File: extensions/resource-deployment/src/ui/modelViewUtils.ts (hunk 2 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts]: done

File: extensions/resource-deployment/src/ui/modelViewUtils.ts (hunk 3 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts]: done.

**Comment by ranasaria** [comment]
> Why is the error message duplicated three times? That doesn't seem very readable to me.
> 
> And I don't see the string updates that I suggested you make.

Where is the message duplicated three times?

Here are the latest strings for the new error messages. If there is still anything missing let me know.

 "The selected account '{0}' is no longer available. Kindly add it back by signing in.\n Error Details: {1}.", 
 "The access token for selected account '{0}' is no longer valid. Kindly sign in again to refresh your credentials.\n Error Details: {1}."

**Comment by Charles-Gagnon** [comment]
This screenshot you posted has the same message 3 times....

(The selected account....)

image

**Comment by ranasaria** [comment]
> This screenshot you posted has the same message 3 times....
> 
> (The selected account....)
> 
> image

Ah got it. I did not like that myself and was the main thing that I wanted a second opinion on. Will fix.

File: extensions/resource-deployment/src/ui/modelViewUtils.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts]: done

**Comment by Charles-Gagnon** [comment]
@ranasaria Could you include a screenshot of what the error message looks like now?

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 4]
```diff
@@ -828,6 +840,10 @@ async function processAzureAccountField(context: AzureAccountFieldContext): Prom
 	}, 0);
 }
 
+function getAccountDisplayString(account: azdata.Account) {
+	return `${account.displayInfo.displayName} (${account.displayInfo.userId})`;
```
Comment (alanrenmsft) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:844]: make sure to test the live account as well, I think only showing the email address is enough.

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts:844]: We should generally show the ID as well - email address isn't necessarily unique

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts:844]: This is not introduced by this change. For the accounts that I have tested with account.displayInfo.userId and account.key.accountId are the same value, so including both does not make sense. Also, it would seem that we should only include fields account.displayInfo object in what is displayed to the user. Since userId is the same as accountId, we are already displaying to user what Charles has suggested. We can do any improvements as necessary in the future. 

@alanrenmsft  - if you have concerns about the correctness of this code for live account then kindly open an issue and I will get that prioritized, investigated, and tackled. The changes here do not affect the correctness or incorrectness of the live accounts, so I would like to get this fix in and tackle that separately.

**Comment by ranasaria** [comment]
> This screenshot you posted has the same message 3 times....
> 
> (The selected account....)
> 
> image

Fixed.
