### PR TITLE
Expand/collapse all node options

### LINKED ISSUE #10954: Hitting error after adding a required await
After adding await for reveal method, project focus started throwing following error.

image

### LINKED ISSUE #10979: Expand/collapse all nodes options
- Azure Data Studio Version:

Steps to Reproduce:

1. For bigger database projects having all nodes expanded might be bit overwhelmening to work with.

possible improvements
1. Adding a button/toggle in the viewlet for expand all collapse all
2 At first open the DB with notes collapsed (lets check what SSDT does)
Longer term..
3. if we could remember state what is open collapsed is greater long term

### PR DESCRIPTION
**Pull request by anjalia**
- Adds button in the Database Projects viewlet to collapse all nodes. Does not preserve the state of what was open when collapsing.
- When a project is opened, opens with only one level expanded. (Previously, all levels of the project were initially expanded.)
- Includes bug fix for using await with reveal method

This PR fixes #10979 and fixes #10954

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts [hunk 1]
```diff
@@ -39,6 +39,13 @@ export class SqlDatabaseProjectTreeViewProvider implements vscode.TreeDataProvid
 		return element.children;
 	}
 
+	public getParent(element: BaseProjectTreeItem): BaseProjectTreeItem {
+		if (!element.parent) {
+			throw new Error('Cannot access parent of provided tree item');
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:44]: localize error message in constants.ts

File: extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts [hunk 2]
```diff
@@ -71,7 +78,13 @@ export class SqlDatabaseProjectTreeViewProvider implements vscode.TreeDataProvid
 		const projNode = this.roots.find(x => x instanceof ProjectRootTreeItem ? (<ProjectRootTreeItem>x).project === project : false);
 
 		if (projNode) {
-			this.treeView?.reveal(projNode, { focus: true, expand: true });
+			await this.treeView?.reveal(projNode, { focus: true, expand: true });
+		}
+	}
+
+	public async expandAllNodes(): Promise<void> {
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:85]: it's a little confusing that this is called "Expand All" but it's only expanding the first level and not all the folders. What's the Visual Studio behavior for this?

Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:85]: is there a way to make this so that only the selected project gets expanded instead of all the open projects?

File: extensions/sql-database-projects/package.json [hunk 3]
```diff
@@ -133,6 +133,12 @@
         "command": "sqlDatabaseProjects.openContainingFolder",
         "title": "%sqlDatabaseProjects.openContainingFolder%",
         "category": "%sqlDatabaseProjects.displayName%"
+      },
+      {
+        "command": "sqlDatabaseProjects.expandAllNodes",
+        "title": "%sqlDatabaseProjects.expandAllNodes%",
+        "category": "%sqlDatabaseProjects.displayName%",
+        "icon": "$(expand-all)"
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/package.json:141]: Not necessarily in this PR but we will have a colapse all too right? 
once we do we will need to change icons to toggle based on state OR we can have both at all times but one enabled one disabled...

Comment (anjalia) [reply extensions/sql-database-projects/package.json:141]: There is actually a collapse all included in this PR; it is included as an option when the tree view is created (in extensions/sql-database-projects/src/controllers/mainController.ts).  This results in two buttons in the viewlet at all times. 

I know it's a little strange to have collapse all created via an option vs expand all created manually. Did this because expand all cannot be created as an option, and couldn't find APIs to create collapse all manually. Any recommendations on this?

File: extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts (hunk 2 above)
Comment (anjalia) [reply extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:85]: ah makes sense... Visual Studio does not actually have an expand all option for file explorer, only collapse all. Same with Notebooks and Explorer in ADS

Comment (anjalia) [reply extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:85]: yes, is that the desired behavior of "Expand All" / should the action be renamed in that case?

Comment (udeeshagautam) [reply extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:86]: hmm.. good point. I think it would be okay to track per project expand collapse as seperate item though - right?

Comment (udeeshagautam) [reply extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:86]: hmm... I thought VS has both... am I perceiving this wrong
image

Comment (kisantia) [reply extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:86]: the "Show All Files" button shows the generated files and stuff not part of the project, not expanding the folders

Comment (Benjin) [reply extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:86]: yup, would be fine to add them separately.  Just gotta keep that in mind when designing this portion so adding the next step is relatively easy!

Comment (anjalia) [reply extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:86]: New issue opened to track per project expand/collapse: #11795

File: extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts [hunk 4]
```diff
@@ -8,6 +8,7 @@ import * as vscode from 'vscode';
 import { BaseProjectTreeItem, SpacerTreeItem } from '../models/tree/baseTreeItem';
 import { ProjectRootTreeItem } from '../models/tree/projectTreeItem';
 import { Project } from '../models/project';
+import * as constants from '../common/constants';
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/databaseProjectTreeViewProvider.ts:11]: nit: move this up with the other import *
