### PR TITLE
Fixed a bug with deleting models from list in import model wizard

### LINKED ISSUE #12789: ML- Removing models from Import model wizard breaks the operation
- Azure Data Studio Version:

Steps to Reproduce:

1. Open Import model wizard
2. choose a model to import (file or AML)
3. In the next page remove the model you chose 

Expected: When the list only has one item, either don't let user to delete that or disable Next button so user is forced to go back and select another model to import

Actual: Removing the only row in the list causes UI to break down and wizard still lets user to continue with the import

Screen Shot 2020-10-07 at 9 52 21 AM

### PR DESCRIPTION
**Pull request by llali**
This PR fixes #12789
Screen Shot 2020-10-07 at 1 35 38 PM

### CODE REVIEW

File: extensions/machine-learning/src/common/constants.ts [hunk 1]
```diff
@@ -213,6 +213,7 @@ export const invalidModelImportTargetError = localize('models.invalidModelImport
 export const columnDataTypeMismatchWarning = localize('models.columnDataTypeMismatchWarning', "The data type of the source table column does not match the required input field’s type.");
 export const outputColumnDataTypeNotSupportedWarning = localize('models.outputColumnDataTypeNotSupportedWarning', "The data type of output column does not match the output field’s type.");
 export const modelNameRequiredError = localize('models.modelNameRequiredError', "Model name is required.");
+export const modelsRequiredError = localize('models.modelsRequiredError', "Please select at least one model to import.");
```
Comment (llali) [inline extensions/machine-learning/src/common/constants.ts:216]: @MsSQLGirl , I added this new error message and wanted to see if it looks ok to you

**Review by udeeshagautam — APPROVED** [review]
