### PR TITLE
Fix/open book error

### LINKED ISSUE #11369: Opening notebook using bookTreeView command
- Azure Data Studio Version: 1.20.0

Steps to Reproduce:

1. Use the `bookTreeView.openBook` command to open a notebook in the side viewlet bar
2. Receive an error showing that no TOC is found so the notebook cannot be opened

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #11369 

OpenBook should not be used to open a folder of notebooks. So the error in the above issue is a valid error. 
But to address the missing way to open a folder with notebooks, updated the OpenNotebookFolder to accept a folder path to open (which if absent, prompts user to select a folder).

### CODE REVIEW

File: extensions/notebook/src/extension.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ type ChooseCellType = { label: string, id: CellType };
 export async function activate(extensionContext: vscode.ExtensionContext): Promise<IExtensionApi> {
 	const appContext = new AppContext(extensionContext);
 	const createBookPath: string = path.posix.join(extensionContext.extensionPath, 'resources', 'notebooks', 'JupyterBooksCreate.ipynb');
-	extensionContext.subscriptions.push(vscode.commands.registerCommand('bookTreeView.openBook', (bookPath: string, openAsUntitled: boolean, urlToOpen?: string) => openAsUntitled ? providedBookTreeViewProvider.openBook(bookPath, urlToOpen, true) : bookTreeViewProvider.openBook(bookPath, urlToOpen, true)));
+	extensionContext.subscriptions.push(vscode.commands.registerCommand('bookTreeView.openBook', (bookPath: string, openAsUntitled: boolean, urlToOpen?: string, isNotebook?: boolean) => openAsUntitled ? providedBookTreeViewProvider.openBook(bookPath, urlToOpen, true, isNotebook) : bookTreeViewProvider.openBook(bookPath, urlToOpen, true, isNotebook)));
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/extension.ts:26]: Why wouldn't we call bookTreeView.openNotebook instead if it's a notebook? It isn't a terrible idea to have a single command be able to handle both - but if we do then we should just get rid of the other and have everything go through the one command IMO.

File: extensions/notebook/src/book/bookTreeView.ts [hunk 2]
```diff
@@ -383,7 +391,7 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 		}
 	}
 
-	public async openNotebookFolder(): Promise<void> {
+	public async openNotebookFolder(urlToOpen?: string, showPreview?: boolean): Promise<void> {
```
Comment (corivera) [inline extensions/notebook/src/book/bookTreeView.ts:394]: Are there any issues with loading multiple notebooks at once when using these options?

File: extensions/notebook/src/extension.ts (hunk 1 above)
Comment (MaddyDev) [reply extensions/notebook/src/extension.ts:26]: yeah, I agree. OpenBook is not supposed to be used for opening notebook(s). But we're reusing openBook for opening items in a folder, hence the parameter. Added it for clarity.

Comment (barbaravaldez) [reply extensions/notebook/src/extension.ts:26]: So, is the issue that the OpenNotebookFolder command only opens Books?

File: extensions/notebook/src/book/bookTreeView.ts (hunk 2 above)
Comment (MaddyDev) [reply extensions/notebook/src/book/bookTreeView.ts]: I haven't seen any issues loading multiple notebooks but the highlight isn't working as expected. I'll create a separate issue to track it.

File: extensions/notebook/src/book/bookTreeView.ts [hunk 3]
```diff
@@ -190,17 +190,37 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
...
-			const sectionToOpen = bookRoot.findChildSection(urlToOpen);
-			const urlPath = sectionToOpen ? sectionToOpen.url : bookRoot.tableOfContents.sections[0].url;
-			const sectionToOpenMarkdown: string = path.join(this.currentBook.bookPath, Content, urlPath.concat('.md'));
-			// The Notebook editor expects a posix path for the resource (it will still resolve to the correct fsPath based on OS)
-			const sectionToOpenNotebook: string = path.posix.join(this.currentBook.bookPath, Content, urlPath.concat('.ipynb'));
-			if (await fs.pathExists(sectionToOpenMarkdown)) {
-				this.openMarkdown(sectionToOpenMarkdown);
+			let urlPath: string;
+			if (this.currentBook.isNotebook) {
+				urlPath = urlToOpen && this.currentBook.bookPath === urlToOpen ? this.currentBook.bookPath : undefined;
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts:195]: When would this be true? Is this for the case of opening a regular folder of Notebooks? Why wouldn't you default to the "first" Notebook in the folder then - similar to what we do with Books? I guess I'm not exactly sure when this is called so maybe it makes sense not to open a file immediately.

Comment (MaddyDev) [reply extensions/notebook/src/book/bookTreeView.ts:195]: So we call this from OpenBook for every notebook. In case of a Book , it has items and we open the first one when no urlToOpen is given. In case of folder with notebooks, this get's called for every notebook with urlToOpen and if we default like books, we end up opening every notebook in the folder. Hence opening only the passed urlToOpen (if there is one or none at all).

File: extensions/notebook/src/book/bookTreeView.ts [hunk 4]
```diff
@@ -190,17 +190,37 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
...
+					const sectionToOpen = bookRoot.findChildSection(urlToOpen);
+					urlPath = sectionToOpen?.url;
+				} else {
+					urlPath = this.currentBook.bookItems[0].tableOfContents.sections[0].url;
+				}
 			}
-			else if (await fs.pathExists(sectionToOpenNotebook)) {
-				await this.openNotebook(sectionToOpenNotebook);
+			if (urlPath) {
+				if (this.currentBook.isNotebook) {
```
[the remark this answers is not in the document]
Comment (MaddyDev) [reply extensions/notebook/src/book/bookTreeView.ts:206]: You're right it could be a markdown/ipynb file within a Book/NotebookFolder. If it's within a notebook folder, url has the exact path of the file but if it's part of a book, it's the url from toc file which doesn't include the file type so the extra logic.
