### PR TITLE
fix the endless loop scenario that breaks tree scroll

### LINKED ISSUE #17875: Book tree view scroll not working after opening notebook
- Azure Data Studio Version:
Version: 1.34.0-rc1
Commit: d5a3370b655a53b3f431ac7008ab84ba311d991b
Date: 2021-12-08T20:14:15.444Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 21.1.0

Steps to Reproduce:
1. Open ADS Livesite repo in the Explorer Viewlet
2. `Cmd + p` to open file picker and open the **ASCDiagnostics_SQL** notebook 
3. Go to the Notebooks Viewlet
4. Try scrolling in the Book Tree View

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #17875 

When a notebook is opened through command pallet and it's not present in the book tree view, findAndExpandParentNode goes into an endless loop checking for the same book node that has no children. Fixed it by tracking the expanded nodes and breaking out if we see the same node.

### CODE REVIEW

**Review by lucyzhang929 — APPROVED** [review]

**Review by barbaravaldez — APPROVED** [review]

File: extensions/notebook/src/book/bookTreeView.ts [hunk 1]
```diff
@@ -478,7 +479,7 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 				// since bookItems will not have them yet, check the sections->file property
 				bookItemToExpand = parentBook.bookItems.find(b => b.sections?.find(n => notebookFolders[notebookFolders.length - depthOfNotebookInBook - 1].indexOf(n.file.substring(n.file.lastIndexOf('/') + 1)) > -1));
 				// book isn't found even in the same level, break out and return.
-				if (!bookItemToExpand) {
+				if (!bookItemToExpand || expandedBookItems.includes(bookItemToExpand)) {
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts:482]: Do you have to keep track of all the book items you've found? Or would it just be enough to instead just break out if we get to a node that doesn't have children and we haven't found the book yet?

**Review by Charles-Gagnon — COMMENTED** [review]
Please add tests

File: extensions/notebook/src/book/bookTreeView.ts (hunk 1 above)
Comment (MaddyDev) [reply extensions/notebook/src/book/bookTreeView.ts:482]: I think it would be better to keep looking since we can have weird book structures when it comes to livesite.

**Comment by MaddyDev** [comment]
> Please add tests

Will do in a separate PR. Thanks.

File: extensions/notebook/src/book/bookTreeView.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply extensions/notebook/src/book/bookTreeView.ts:482]: But this isn't going to "keep looking", right? It just traverses down the path checking the folders along the way until it finds the item - so if it ever gets to the point where there aren't any children then there's nothing more for us to check (which is where it would get into the endless loop).



If you wanted to fix it so that it checks all other paths then that'd be a separate enhancement.

Comment (MaddyDev) [reply extensions/notebook/src/book/bookTreeView.ts:482]: What I meant by keep looking is I don't want to break out if we get to a node that doesn't have children (keep the iteration going until the depth condition is satisfied)

Comment (Charles-Gagnon) [reply extensions/notebook/src/book/bookTreeView.ts:482]: Can you verify that's what actually happens? Looking at the code it seems like the state doesn't change - on 486 it increments the depth so that on 501 when it decrements it it'll actually stay in the same place. So it'll just go and repeat what it just tried.

The idea being that if there were children that were loaded it'll now check them to see if any of them were the one we're looking for. But if there's no children then isn't that where we got into the endless loop in the first place?

Comment (MaddyDev) [reply extensions/notebook/src/book/bookTreeView.ts:482]: I double checked and I added that increment step for multiple child nodes in the same level. But am not checking it it's the same child node that it's trying to expand, so added the expanded nodes to check that and not increment it if it's already expanded node.

**Review by Charles-Gagnon — APPROVED** [review]
