### PR TITLE
Fix the Attempt to use a destroyed view Errors

### LINKED ISSUE #4074: Notebooks: Attempt to use a destroyed view Errors
From time to time, running the same cell multiple times results in an error like the following:

  ERR ViewDestroyedError: Attempt to use a destroyed view: detectChanges: Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges

Please root cause and fix. This clogs up the developer console.

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #4074.

Looks like we had the same problem in ComponentBase, so solving it in the same way here.

### CODE REVIEW

File: src/sql/parts/notebook/cellViews/outputArea.component.ts [hunk 1]
```diff
@@ -34,7 +34,9 @@ export class OutputAreaComponent extends AngularDisposable implements OnInit {
 		this.updateTheme(this.themeService.getColorTheme());
 		if (this.cellModel) {
 			this._register(this.cellModel.onOutputsChanged(() => {
-				this._changeRef.detectChanges();
+				if (!(this._changeRef['destroyed'])) {
```
Comment (rajmusuku) [inline src/sql/parts/notebook/cellViews/outputArea.component.ts]: Should we add the same condition on all the cells wherever detect change happens?

Comment (chlafreniere) [reply src/sql/parts/notebook/cellViews/outputArea.component.ts]: We could, but this is the only place that I've seen where this error can occur, since we're reusing the output component. I'm a little worried about the code component and checking this condition thousands of times unnecessarily.
