### PR TITLE
Fixing the checked variable in radio buttons

### LINKED ISSUE #13907: Buttons in radio button group do not update the checked variable when unchecked
- Azure Data Studio Version:

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #13907

### CODE REVIEW

File: src/sql/base/browser/ui/radioButton/radioButton.ts [hunk 1]
```diff
@@ -33,7 +35,18 @@ export class RadioButton extends Widget {
...
 		this.enabled = opts.enabled || true;
 		this.checked = opts.checked || false;
-		this.onclick(this.inputElement, () => this._onClicked.fire());
+		this.onclick(this.inputElement, () => {
+			this._onClicked.fire();
+			let buttonGroup = document.getElementsByName(this.name);
+			buttonGroup.forEach((button) => {
+				let event = document.createEvent('HTMLEvents');
+				event.initEvent('change', true, true);
+				button.dispatchEvent(event);
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/radioButton/radioButton.ts:44]: We should avoid sending the event if the checked state hasn't actually changed

File: src/sql/base/browser/ui/radioButton/radioButton.ts [hunk 2]
```diff
@@ -33,7 +35,18 @@ export class RadioButton extends Widget {
 		this.label = opts.label;
 		this.enabled = opts.enabled || true;
 		this.checked = opts.checked || false;
-		this.onclick(this.inputElement, () => this._onClicked.fire());
+		this.onclick(this.inputElement, () => {
+			this._onClicked.fire();
+			let buttonGroup = document.getElementsByName(this.name);
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/radioButton/radioButton.ts:40]: What's the behavior if name is empty/undefined? We should only do this if we actually have a name

File: src/sql/base/browser/ui/radioButton/radioButton.ts [hunk 3]
```diff
@@ -33,7 +35,18 @@ export class RadioButton extends Widget {
...
+			buttonGroup.forEach((button) => {
+				let event = document.createEvent('HTMLEvents');
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/radioButton/radioButton.ts:42]: Any reason you're creating an event here versus just firing the emitters manually? None of our other code seems to use this manual event creation and I don't know if there's any weird issues that might pop up because of this.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/sql/base/browser/ui/radioButton/radioButton.ts (hunk 1 above)
Comment (aasimkhan30) [reply src/sql/base/browser/ui/radioButton/radioButton.ts:44]: Won't the state be change for all the buttons with the same "name" attribute?

File: src/sql/base/browser/ui/radioButton/radioButton.ts (hunk 3 above)
Comment (aasimkhan30) [reply src/sql/base/browser/ui/radioButton/radioButton.ts:42]: I am going the HTMLEvents route because I do not have reference to other buttons. 
How can I get reference to an emitter that belong to other radio buttons?

File: src/sql/base/browser/ui/radioButton/radioButton.ts [hunk 4]
```diff
@@ -18,6 +18,8 @@ export class RadioButton extends Widget {
 	private inputElement: HTMLInputElement;
 	private _onClicked = new Emitter<void>();
 	public readonly onClicked: Event<void> = this._onClicked.event;
+	private _onChanged = new Emitter<boolean>();
```
Comment (alanrenmsft) [inline src/sql/base/browser/ui/radioButton/radioButton.ts:21]: I started to question the purpose of onClicked event, do we still need that?

Comment (aasimkhan30) [reply src/sql/base/browser/ui/radioButton/radioButton.ts:21]: I can remove that but it might break existing functionality.

File: src/sql/base/browser/ui/radioButton/radioButton.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/radioButton/radioButton.ts]: Only two - the previously checked one and the newly checked on.

File: src/sql/base/browser/ui/radioButton/radioButton.ts (hunk 4 above)
Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/radioButton/radioButton.ts:21]: onClick implies an event that's fired whenever the element is actually clicked by the user - where as onChanged would be whenever the value is changed.

The primary difference I could see is that onClicked would only be fired for the one that was actually clicked - but onChanged would be fired for both it and the previously selected one that had its value changed.

Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/radioButton/radioButton.ts:21]: So while I think there's a clear difference it's not clear to me when we'd actually care about the onClick scenario I gave. I'm kind of fine either way but I think having an onChanged event as well is clearer as to when it's actually fired.

File: src/sql/base/browser/ui/radioButton/radioButton.ts (hunk 3 above)
Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/radioButton/radioButton.ts]: Yeah that's a good point. Hmmm. I had put some thought into this a while back but never came up with a solution I liked so dropped it. 

Since I can't really think of a better solution then sending the event seems reasonable enough for now. Make sure that we only handle this if the value is actually changed when doing stuff like updating the ext host though.

Also something to think about - but the groupings can be scoped. I don't know all the rules that govern that but for example if you have two separate forms on a page with radio buttons that all have the same name property they'll still each only be grouped with the other buttons in the form. Since we don't use forms AFAIK I'm hoping this isn't an issue (and generally people have been using unique names) but something to be aware of regardless.

Comment (aasimkhan30) [reply src/sql/base/browser/ui/radioButton/radioButton.ts]: Yeah, that is one of the reasons I do not like the part 'getElementsByName'. This might generate an event for all elements that have the same 'name' attribute. Maybe I can introduce a custom attribute for radio buttons and set it to name and try to get elements by that custom attribute.  What do you think about that solution?

File: src/sql/workbench/api/common/extHostModelView.ts [hunk 5]
```diff
@@ -1271,6 +1271,7 @@ class RadioButtonWrapper extends ComponentWrapper implements azdata.RadioButtonC
 		super(proxy, handle, ModelComponentTypes.RadioButton, id);
 		this.properties = {};
 		this._emitterMap.set(ComponentEventType.onDidClick, new Emitter<any>());
+		this._emitterMap.set(ComponentEventType.onDidChange, new Emitter<any>());
```
Comment (Charles-Gagnon) [inline src/sql/workbench/api/common/extHostModelView.ts:1274]: `new Emitter<boolean>`

File: extensions/machine-learning/src/test/views/utils.ts [hunk 6]
```diff
@@ -16,6 +16,7 @@ export interface ViewTestContext {
 
 export function createViewContext(): ViewTestContext {
 	let onClick: vscode.EventEmitter<any> = new vscode.EventEmitter<any>();
+	let onChange: vscode.EventEmitter<any> = new vscode.EventEmitter<any>();
```
Comment (Charles-Gagnon) [inline extensions/machine-learning/src/test/views/utils.ts:19]: boolean for the types, not any

Comment (Charles-Gagnon) [reply extensions/machine-learning/src/test/views/utils.ts:19]: (make sure to update all the other instances of this too)

File: src/sql/base/browser/ui/radioButton/radioButton.ts [hunk 7]
```diff
@@ -33,7 +36,23 @@ export class RadioButton extends Widget {
...
+					let event = document.createEvent('HTMLEvents');
+					event.initEvent('change', true, true);
+					button.dispatchEvent(event);
+				});
+			}
+		});
+		this.inputElement.addEventListener('change', () => {
+			if (this.inputElement.checked !== this._internalCheckedStateTracker) {
+				this.checked = this.inputElement.checked;
+				this._onChanged.fire(this.checked);
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/radioButton/radioButton.ts:53]: This should probably go in the checked setter  so it's correctly fired when something sets that directly. (I'd also move the internal state logic there too)

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/sql/base/browser/ui/radioButton/radioButton.ts (hunk 7 above)
Comment (aasimkhan30) [reply src/sql/base/browser/ui/radioButton/radioButton.ts:53]: Should I fire the event even when some external code updates the 'checked' variable?
I was trying to avoid that scenario

File: src/sql/base/browser/ui/radioButton/radioButton.ts [hunk 8]
```diff
@@ -18,7 +18,10 @@ export class RadioButton extends Widget {
 	private inputElement: HTMLInputElement;
 	private _onClicked = new Emitter<void>();
 	public readonly onClicked: Event<void> = this._onClicked.event;
+	private _onChanged = new Emitter<boolean>();
+	public readonly onChange: Event<boolean> = this._onChanged.event;
 	private _label: HTMLSpanElement;
+	private _internalCheckedStateTracker: boolean;
```
Comment (alanrenmsft) [inline src/sql/base/browser/ui/radioButton/radioButton.ts:24]: lets have the default value set as well. it should be false, right?

File: src/sql/base/browser/ui/radioButton/radioButton.ts [hunk 9]
```diff
@@ -33,7 +36,23 @@ export class RadioButton extends Widget {
 		this.label = opts.label;
 		this.enabled = opts.enabled || true;
 		this.checked = opts.checked || false;
-		this.onclick(this.inputElement, () => this._onClicked.fire());
+		this.onclick(this.inputElement, () => {
+			this._onClicked.fire();
+			if (this.name) {
+				let buttonGroup = document.getElementsByName(this.name);
```
Comment (alanrenmsft) [inline src/sql/base/browser/ui/radioButton/radioButton.ts:42]: const instead of let, same should apply to the variable below.

File: extensions/machine-learning/src/test/views/utils.ts (hunk 6 above)
Comment (aasimkhan30) [reply extensions/machine-learning/src/test/views/utils.ts:19]: In future, if the same onChange is used for other components it will have a different type. Therefore, I left it as any.

File: src/sql/base/browser/ui/radioButton/radioButton.ts (hunk 3 above)
Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/radioButton/radioButton.ts]: Something to consider if we run into this issue - but for now I think this should be good enough. I don't see this being a common enough scenario to warrant extra custom logic like that.

File: extensions/machine-learning/src/test/views/utils.ts (hunk 6 above)
Comment (Charles-Gagnon) [reply extensions/machine-learning/src/test/views/utils.ts:19]: Not sure what you mean - each component should implement its own version of onChanged and thus can set the value to whatever is appropriate for that component. And anyways it's better to do the right thing now and then if someone does do something like that in the future it can be addressed now (likely by just making another emitter of the appropriate type)

File: src/sql/base/browser/ui/radioButton/radioButton.ts (hunk 7 above)
Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/radioButton/radioButton.ts:53]: Why wouldn't you? onChanged should be fired any time the selected state is changed - that's the whole point of this code.

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 You have a compile error currently FYI

```
[18:41:19] Error: /home/runner/work/azuredatastudio/azuredatastudio/extensions/arc/src/test/ui/components/radioOptionsGroup.test.ts(42,4): Conversion of type 'RadioButtonComponent | undefined' to type 'StubRadioButton' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'RadioButtonComponent' is missing the following properties from type 'StubRadioButton': click, _onDidClickEmitter
  ```

File: src/sql/base/browser/ui/radioButton/radioButton.ts [hunk 10]
```diff
@@ -33,7 +36,22 @@ export class RadioButton extends Widget {
...
+				buttonGroup.forEach((button) => {
+					const event = document.createEvent('HTMLEvents');
+					event.initEvent('change', true, true);
+					button.dispatchEvent(event);
+				});
+			}
+		});
+		this.inputElement.addEventListener('change', () => {
+			if (this.inputElement.checked !== this._internalCheckedStateTracker) {
+				this.checked = this.inputElement.checked;
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/radioButton/radioButton.ts:52]: I would suggest putting this check in the checked setter instead so that we only fire the event when the value actually changes. Then this event handler would just be simply 
`this.inputElement.addEventListener('change', () => this.checked = this.inputElement.checked);`

File: extensions/arc/package.json [hunk 11]
```diff
@@ -1076,7 +1076,7 @@
     "@types/sinon": "^9.0.4",
     "@types/uuid": "^8.3.0",
     "@types/yamljs": "^0.2.31",
-    "azdata-test": "^1.0.0",
+    "azdata-test": "^1.1.0",
```
Comment (Charles-Gagnon) [inline extensions/arc/package.json:1079]: Can you go through and update all the other extensions as well? Should try to keep these in sync generally.

File: extensions/machine-learning/src/test/views/utils.ts (hunk 6 above)
Comment (Charles-Gagnon) [reply extensions/machine-learning/src/test/views/utils.ts:19]: @aasimkhan30 ping - it's a bit of a nit but we really should be getting in the habit of avoiding using any

**Review by Charles-Gagnon — APPROVED** [review]
Couple of things but generally looks good. 

Let's get @alanrenmsft to sign off on this as well, want to hear his opinion on the new event being added to the component.

File: src/sql/azdata.proposed.d.ts [hunk 12]
```diff
@@ -274,6 +274,13 @@ declare module 'azdata' {
 		showLinkIcon?: boolean;
 	}
 
+	export interface RadioButtonComponent {
+		/**
+		 * An event called when the value of radio button changes
+		 */
+		onChanged: vscode.Event<boolean>;
```
Comment (alanrenmsft) [inline src/sql/azdata.proposed.d.ts:281]: lets follow the naming convention of vscode event -> onDidChangeCheckedState

**Review by alanrenmsft — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
please fix the compilation error
