### PR TITLE
Fix #6606: Data-tier Application extract file location resets when changing database 

### LINKED ISSUE #6606: Data-tier Application extract file location resets when changing database
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Use Data-tier Application Wizard Extract option
2. In Step 2 click "..." and choose a new folder to extract the dacpac to
3. Change Source Database field

Expected: The File Location file name changes to reflect new database, but the folder specified in step 2 is retained.

Actual: The File Location is reset to the original directory losing the value provided in step 2

image

### PR DESCRIPTION
**Pull request by kisantia**
Use previous file path if there was one for the dacpac/bacpac file location when the database changes in the DacFx wizard. Fixes #6606 .

### CODE REVIEW

File: extensions/dacpac/src/wizard/api/dacFxConfigPage.ts [hunk 1]
```diff
@@ -164,8 +164,12 @@ export abstract class DacFxConfigPage extends BasePage {
 	}
 
 	protected getRootPath(): string {
-		// return rootpath of opened folder in file explorer if one is open, otherwise default to user home directory
-		return vscode.workspace.rootPath ? vscode.workspace.rootPath : os.homedir();
+		// use previous file location if there was one
+		if (this.fileTextBox.value && path.dirname(this.fileTextBox.value)) {
```
Comment (udeeshagautam) [inline extensions/dacpac/src/wizard/api/dacFxConfigPage.ts]: do we need to check this directory's existence in case its deleted or something?

Comment (kisantia) [reply extensions/dacpac/src/wizard/api/dacFxConfigPage.ts]: I think it's ok to let DacFx handle if the directory doesn't exist. The extract fails with this error:
image
