### PR TITLE
save password checkbox fix

### LINKED ISSUE #17594: Remember Password is not selected on saved connections causing password to be forgotten
- Azure Data Studio Version: 1.33.0
- OS Version: Windows 11

Steps to Reproduce:

1. Open up Azure.
2. Open a new tab.
3. Click "Connect" along the top bar
4. Select a saved connection from my list
5. The "Remember password" box is always unticked now

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #17594 

turns out the issue was introduced by my previous [change](https://github.com/microsoft/azuredatastudio/pull/16777/files#diff-6cbed09935af5348af95a7fe0c504191ac5e2ee347e0325d5d89d6237dd90698L459) when I was refactoring the code, the save password checkbox should only be unchecked when the auth type is not SqlLogin.

### CODE REVIEW

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 1]
```diff
@@ -454,13 +454,16 @@ export class ConnectionWidget extends lifecycle.Disposable {
...
 		this._passwordInputBox.hideMessage();
-		this._rememberPasswordCheckBox.checked = false;
 		this._azureAccountDropdown.hideMessage();
 		this._azureTenantDropdown.hideMessage();
 		this._tableContainer.classList.add('hide-username');
 		this._tableContainer.classList.add('hide-password');
 		this._tableContainer.classList.add('hide-azure-accounts');
 
+		if (currentAuthType !== AuthenticationType.SqlLogin) {
+			this._rememberPasswordCheckBox.checked = false;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:464]: The checkbox is hidden anyways, why does it matter whether it's checked? Are we saving the value of the checkbox regardless of whether it's actually applicable or not? If so that seems like the better place to fix that - only save the value if the auth type actually supports a password.

**Comment by Charles-Gagnon** [comment]
Also please make sure to add a test case to this in the test plan

File: src/sql/workbench/services/connection/browser/connectionWidget.ts (hunk 1 above)
Comment (alanrenmsft) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:464]: the purpose of this code is to reset it to default value (unchecked) when auth type changes, and next time sqllogin is selected it will be unchecked, I personally don't have a preference. my first reaction was simply remove the line, but I think it also makes sense to keep it.

regarding to your comment about 'better fix'. I am afraid that was not the problem, the problem is the checkbox that was supposed to be checked was unexpected unchecked by the line I removed.

**Comment by alanrenmsft** [comment]
> Also please make sure to add a test case to this in the test plan

yes, I just did that.

File: src/sql/workbench/services/connection/browser/connectionWidget.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:464]: I guess my main issue is that what if a new auth type is added later that isn't sql login but uses the checkbox. Then we'd have the same issue for that one. Maybe never an issue but if we can avoid it now why not do so?

Can you explain why we need to reset it anyways? I would expect that when an auth type that uses it is selected that the checkbox will be updated to the saved value at that time so wouldn't this be unnecessary?

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/services/connection/browser/connectionWidget.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts]: This works too 😁

**Review by cssuh — APPROVED** [review]
