### PR TITLE
Fix connection profile prompt for Create Function with SQL Binding

### LINKED ISSUE #19106: SQL bindings should have progress notification while making a test connection
1. Run the "Create Azure Function with SQL Binding" command
2. When prompted to choose a connection from the list, select an invalid connection (to easily simulate this just disconnect your network then select it, or manually enter in an invalid hostname)

The quickpick will disappear and then there's no indication that anything is happening. We should be displaying the progress bar on the quickpick while it's connecting to indicate that work is being done in the background while it waits to time out.

### LINKED ISSUE #19107: SQL Bindings - If connection fails then the user is exited from the flow
1. Run the "Create Azure Function with SQL Binding" command
1. When prompted to choose a connection from the list, select an invalid connection (to easily simulate this just disconnect your network then select it, or manually enter in an invalid hostname)

After the connection fails the flow is exited. Instead we should bring them back to the "choose a connection prompt" so they can choose a valid connection if they desire.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #19107 and fixes #19106.

After the user chooses a connection from the connection profile list we will show this progress notification:
image

If we are unable to connect then it will go back to the prompt for choosing a connection. We will also go back to the connection profile picker if the user exits from the database prompt or objectName. 

#19108 - this issue seems to be on vscode-mssql side for promptForConnection since I correctly pass in ignoreFocusOut parameter as true but it does not respect it.

### CODE REVIEW

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 1]
```diff
@@ -46,37 +46,54 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+				quickPickStep = 'getConnectionInfo';
+				try {
+					await vscode.window.withProgress(
+						{
+							location: vscode.ProgressLocation.Notification,
+							title: constants.connectionProgressTitle,
+							cancellable: false
+						}, async (_progress, _token) => {
+							// list databases based on connection profile selected
+							if (!connectionInfo) {
```
Comment (lucyzhang929) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:64]: Aren't you already checking for connectionInfo above?

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 2]
```diff
@@ -46,37 +46,54 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+								// User cancelled
+								return;
+							}
+							connectionURI = await vscodeMssqlApi.connect(connectionInfo);
+						}
+					);
+				} catch (e) {
+					// User cancelled
```
Comment (lucyzhang929) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:72]: This is a connection error right? Not user cancelled

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 3]
```diff
@@ -46,37 +46,54 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+				connectionInfo = await vscodeMssqlApi.promptForConnection(true);
+				if (!connectionInfo) {
+					// User cancelled
+					return;
+				}
+				quickPickStep = 'getConnectionInfo';
+				try {
+					await vscode.window.withProgress(
+						{
+							location: vscode.ProgressLocation.Notification,
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:59]: What would be even better IMO would be to have the quickpick prompt to select a connection also have the option to test a connection - which could then have the progress notification on the quickpick itself. 

Having the user have to jump around where their attention is during the flow isn't great

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 4]
```diff
@@ -46,37 +46,54 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+							}
+							connectionURI = await vscodeMssqlApi.connect(connectionInfo);
+						}
+					);
+				} catch (e) {
+					// User cancelled
+					continue;
+				}
+				// list databases based on connection profile selected
+				listDatabases = await vscodeMssqlApi.listDatabases(connectionURI);
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:76]: What about the offline scenario? We still want to allow users to manually enter in the DB if they want so we should add an option for them to do so.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 3 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:59]: This is what we are doing however in this flow. Our focus is the connected scenario. 

The flow seems reasonable to me: 
1. User chooses a connection profile 
2. Progress report shown while connecting
3. Error shown (mssql connection error) if unable to connect
4. User is shown connection profile list again

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 4 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:76]: We can track the offline scenario in a separate follow-up issue. But that is currently not the focus. We plan to add more with the table prompts so I would see this coming in when we address that.

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 1 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:64]: If I don't include this it shows me this error within the withProgress: 
image

Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:64]: Probably because it's in a lambda function. We know it's going to exist here though so you can just do `vscodeMssqlApi.connect(connectionInfo!)`

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 3 above)
Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:59]: I don't understand how your comment relates to mine. The flow would stay the same - I'm suggesting that the progress notification be done on the quickpick itself. 

See [QuickInput.busy](https://github.com/microsoft/azuredatastudio/blob/2bc6a0cd012de69504061a876070cfa43533fedc/src/vs/vscode.d.ts#L9926)

(This would of course need to be done in the vscode mssql extension though)

Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:129]: So instead I should pass in busy (optional) parameter to promptForConnection and then use that to create the progress notification on the vscode-mssql side?

Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:129]: After looking a bit at the QuickInput.busy and how promptForConnection is setup we call `promptItemChoice` here - https://github.com/microsoft/vscode-mssql/blob/main/src/views/connectionUI.ts#L90
This takes in options of type `vscode.QuickPickOptions` and `busy` is not one of the properties on the list.

Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:129]: Yes, you'll have to modify it to create our own QuickPick and then you'll have full control over it so can set properties like busy. 

Given the amount of refactoring that would require though I guess we can do that later. But please make an issue to track doing that.

Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:129]: Created Issue here: https://github.com/microsoft/vscode-mssql/issues/17325

File: extensions/sql-bindings/src/common/constants.ts [hunk 5]
```diff
@@ -87,3 +87,4 @@ export const userPasswordLater = localize('userPasswordLater', 'In order to user
 export const openFile = localize('openFile', "Open File");
 export const closeButton = localize('closeButton', "Close");
 export function addSqlBinding(functionName: string): string { return localize('addSqlBinding', 'Adding SQL Binding to function "{0}"...'), functionName; }
+export const connectionProgressTitle = localize('connectionProgressTitle', "Connecting to SQL Server Connection...");
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/constants.ts:90]: Maybe something like `Testing SQL Server connection...`

(connecting to a connection doesn't make sense. And connection usually shouldn't be capitalized)

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 6]
```diff
@@ -26,6 +26,8 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
 	let connectionInfo: IConnectionInfo | undefined;
 	let isCreateNewProject: boolean = false;
 	let newFunctionFileObject: azureFunctionsUtils.IFileFunctionObject | undefined;
+	let connectionURI: string = '';
+	let listDatabases: string[] | undefined;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:30]: Why is this up here? You should only need it for the quickpick so just declare it down on line 142

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 7]
```diff
@@ -26,6 +26,8 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
 	let connectionInfo: IConnectionInfo | undefined;
 	let isCreateNewProject: boolean = false;
 	let newFunctionFileObject: azureFunctionsUtils.IFileFunctionObject | undefined;
+	let connectionURI: string = '';
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:29]: You only need this for verifying the connection so just declare it down right before the withProgress call

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 8]
```diff
@@ -115,6 +116,50 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+					// User cancelled
+					continue;
+				}
+				connectionInfo.database = selectedDatabase;
+
+				// prompt user for object name to create function from
+				objectName = await azureFunctionsUtils.promptForObjectName(selectedBinding);
+				if (!objectName) {
+					// user cancelled
+					continue;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:159]: Shouldn't we return here? Why would we want to loop back and ask them for the connection again if they cancel out of this?

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 9]
```diff
@@ -115,6 +116,50 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+							location: vscode.ProgressLocation.Notification,
+							title: constants.connectionProgressTitle,
+							cancellable: false
+						}, async (_progress, _token) => {
+							// list databases based on connection profile selected
+							connectionURI = await vscodeMssqlApi.connect(connectionInfo!);
+						}
+					);
+				} catch (e) {
+					// connection error occurred
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:138]: connect will show an error message if the connection fails right? Please add a comment explaining that so there isn't confusion about why we don't display anything here

And please update this comment to explain why we continue instead of returning here if an error occurs.

**Review by lucyzhang929 — APPROVED** [review]

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 10]
```diff
@@ -115,6 +114,52 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+				let listDatabases = await vscodeMssqlApi.listDatabases(connectionURI);
+				const selectedDatabase = (await vscode.window.showQuickPick(listDatabases, {
+					canPickMany: false,
+					title: constants.selectDatabase,
+					ignoreFocusOut: true
+				}));
+
+				if (!selectedDatabase) {
+					// User cancelled
+					continue;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:151]: You're still doing the continue  here - is that intentional? If so please add a comment explaining why we want to continue in this case.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 10 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:151]: Yeah, I would imagine if the user cancels the database prompt we can have them show the connection profile prompt once more for them to either choose another connection where their database was in instead for example.

**Review by Charles-Gagnon — APPROVED** [review]
