### PR TITLE
Convert values to string when selecting in selectbox

### LINKED ISSUE #24078: Boolean connection option property no longer works as before
- Azure Data Studio Version: 1.45.0
- OS Version: Win11

Steps to Reproduce:
1. Click on new connection button
2. Select Browse to browse your Azure resources
3.  Select a regular Cosmos DB for Mongo API account (not a Cosmos DB vcore mongo)
4. The information in Connection Details will be automatically filled: "Cluster Server" is set as "True", but it should be set as "False".
image

Root cause:
It appears that [this change](https://github.com/microsoft/azuredatastudio/pull/22512/files) no longer works. It sets the `isServer` as `false` boolean, but the "Connection Details" UI will still display as "True".
If I modify the code to set `isServer` to a string `"false"` or `"true"` and perform checks against a string (e.g. `if (isServer === "true")`) it will work as expected.

For reference:
* the property is defined [here](https://github.com/Azure/azure-cosmosdb-ads-extension/blob/642bb3e4b87f025f1672b35b65104ce595584615/package.json#L300).
* In the extension, it is used [here](https://github.com/Azure/azure-cosmosdb-ads-extension/blob/642bb3e4b87f025f1672b35b65104ce595584615/src/Dashboards/homeDashboard.ts#L35) and [here](https://github.com/Azure/azure-cosmosdb-ads-extension/blob/642bb3e4b87f025f1672b35b65104ce595584615/src/Dashboards/homeDashboard.ts#L44)

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes #24078

cc @languy

### CODE REVIEW

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 1]
```diff
@@ -932,7 +932,7 @@ export class ConnectionWidget extends lifecycle.Disposable {
 					let value = this.getModelValue(connectionInfo.options[this._customOptions[i].name]);
 					if (value !== '') {
 						if (widget instanceof SelectBox) {
-							widget.selectWithOptionName(value);
+							widget.selectWithOptionName(value?.toString());
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:935]: If the type of option is a boolean what about using a checkbox instead?

Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:935]: I'll let you make the call here - although I don't think this is the correct fix. The issue is because getModelValue expects a string currently - but the value passed in is defined as an any (it strikes again!)

So the better fix IMO would be to change that to take in any and then call toString() there instead so it's always guaranteed to return a string. (and while you're at it, make sure we aren't assuming anything about the connectionInfo.options type anywhere else here...)

Comment (cheenamalhotra) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:935]: It's a good feedback to consider as a design improvement, but it seems this is as per design specs as of now.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:935]: (let's hope no one ever tries to use an object as a custom option value...)

Comment (cheenamalhotra) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:935]: I try to avoid using `any` but it seems it's best option to avoid future problems in this case. Will do that instead.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:935]: In this case we don't have a choice since the value coming in through connectionInfo is any unfortunately. So we have to be prepared to handle anything.

File: src/sql/base/browser/ui/selectBox/selectBox.ts [hunk 2]
```diff
@@ -150,10 +150,10 @@ export class SelectBox extends vsSelectBox implements AdsWidget {
 		this._dialogOptions = options;
 	}
 
-	public selectWithOptionName(optionName?: string, selectFirstByDefault: boolean = true, forceSelectionEvent: boolean = false): void {
+	public selectWithOptionName(optionName?: any, selectFirstByDefault: boolean = true, forceSelectionEvent: boolean = false): void {
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/selectBox/selectBox.ts:153]: Sorry if I was unclear, but I don't think this is the correct approach either. Select boxes only really make sense with strings so leaving it like this is fine. 

I was suggesting that you fix up `getModelValue` to actually always return a string instead. Right now it says it returns a string, but that's just because we don't have strict type checking on - it's actually returning the original object value (booleans in this case).

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 3]
```diff
@@ -879,7 +879,7 @@ export class ConnectionWidget extends lifecycle.Disposable {
 	}
 
 	private getModelValue(value: string): string {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:881]:
```suggestion
	private getModelValue(value: any): string {
```

**Review by Charles-Gagnon — APPROVED** [review]
