### PR TITLE
Fix Issue when Saving Wrong Kernel

### LINKED ISSUE #7280: Notebook saves wrong kernel when saving immediately after kernel is changed
Repro steps:
1. Open a new, untitled notebook.
2. Change kernel from SQL to Python 3.
3. After kernel dropdown updates, save the notebook.
4. When the notebook reopens after the save, the kernel in the dropdown is SQL instead of the expected Python 3.

Note that this bug doesn't show up if you add an empty cell after the kernel change. This cell doesn't even need to be run, just added.

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #7280

The problem was that we were firing the notebook model's kernelChangeEvent too early, before the model updated `_savedKernelInfo`. In addition, we were also not previously waiting for configureKernel() or an updated languageInfo before sending the event, which wasn't good news either.

Here was the previous behavior:
- notebookModel: `kernelChanged()` event fired (from clientSession kernelChange completed)
- notebookEditorModel: listens on `model.kernelChange()`
- notebookTextFileModel asks notebookModel for its `toJson()`
- notebookModel serializes kernel info from  `this._savedKernelInfo` (which is now outdated)
- notebookModel sees that the `await this._activeClientSession.changeKernel()` has returned
- notebookModel calls `updateKernelInfo()`, updating `this._savedKernelInfo`

So, we now no

### CODE REVIEW

File: src/sql/workbench/parts/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -490,16 +489,9 @@ export class NotebookModel extends Disposable implements INotebookModel {
 		}
 	}
 
-	// When changing kernel, update the active session and register the kernel change event
-	// So KernelDropDown could get the event fired when added listerner on Model.KernelChange
+	// When changing kernel, update the active session
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/notebook/browser/models/notebookModel.ts]: Use proper jsdoc styling for this

File: src/sql/workbench/parts/notebook/browser/models/notebookModel.ts [hunk 2]
```diff
@@ -670,6 +662,10 @@ export class NotebookModel extends Disposable implements INotebookModel {
 		if (kernel.info) {
 			this.updateLanguageInfo(kernel.info.language_info);
 		}
+		this._kernelChangedEmitter.fire({
+			newValue: kernel,
+			oldValue: undefined
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/notebook/browser/models/notebookModel.ts]: You don't want to get the existing kernel value and pass that as the oldValue?

Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/browser/models/notebookModel.ts]: Actually, no. It's part of the APIs but we don't use it.

Comment (Charles-Gagnon) [reply src/sql/workbench/parts/notebook/browser/models/notebookModel.ts]: I'd suggest leaving a comment explaining that then, since if I came across this I would think it's a bug at first glance.
