### PR TITLE
Fixing unsupported providers behavior on Async Server Tree (#23758)

### LINKED ISSUE #23604: Null ref when expanding "Unsupported connection" node
1. Create a connection for a non-MSSQL provider (such as PGSQL)
2. Uninstall the connection and reload ADS
3. Try to expand the node

The prompt asking to install the extension appears as expected, but the console has this error :

`TypeError: Cannot read properties of undefined (reading 'onReady')
    at wa.sendConnectRequest (connectionManagementService.ts:1372:53)`

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #23604 
Original PR #23758

### CODE REVIEW

**Review by cheenamalhotra — APPROVED** [review]

File: src/sql/workbench/services/connection/browser/connectionManagementService.ts [hunk 1]
```diff
@@ -1368,16 +1368,22 @@ export class ConnectionManagementService extends Disposable implements IConnecti
 		});
 
 		await this._extensionService.activateByEvent(`onConnect:${connection.providerName}`);
-
+		if (this._providers.get(connection.providerName) === undefined) {
+			await this.handleUnsupportedProvider(connection.providerName);
+			throw new Error(nls.localize('connection.providerNotFound', "Connection provider '{0}' not found", connection.providerName));
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionManagementService.ts:1373]: Missed the original PR, but why are you throwing? Shouldn't the extension be installed after calling handleUnsupportedProvider? So you should be able to continue this logic instead of making the user click it again.

Comment (aasimkhan30) [reply src/sql/workbench/services/connection/browser/connectionManagementService.ts:1373]: Installing the provider refreshes the tree and replaces the node. I don't think we can still use the same expansion call to complete the expansion request.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionManagementService.ts:1373]: Hrm, that's unfortunate. But I doubt that's an easy fix so we'll leave that as a future enhancement if needed (but given that it's essentially a one-time thing it's probably fine as is)

I would suggest adding a comment in main to this code saying that though so it's clear why we don't/can't (don't need to port it here)

**Review by kisantia — APPROVED** [review]
