### PR TITLE
use URI to equal

### LINKED ISSUE #8768: Query results not shown when starting ADS with named files already open
Issue Type: <b>Bug</b>

This appears to be a regression issue with ADS with the latest update as it was working before. When a query is run you can see the query status in the status bar but the Results tab never populates. 

Steps:
1. Open ADS.
1. Create a new tab and put in a simple query. Run the query to ensure it works. Save the query to a file. 
1. Create a new tab and put the same query into that window. DO NOT save the query (leave it as Untitled).
1. Run the query to ensure it returns something.
1. Leaving the current script file open, close ADS.
1. Open ADS.
1. The script windows should open back up.
1. Run the Untitled script. It will prompt for a connection to the server and you can see the query results.
1. Run the named script. It will run and you'll see the stats in the status bar but the query results are not shown.

Expected Results:
When restoring opened script windows all the windows should be able to show their query results irrelevant of whether they are new windows, previously opened in other sessions and whether they are saved or not.
[Recording.zip](https://github.com/microsoft/azuredatastudio/files/3995297/Recording.zip)

Azure Data Studio version: azuredatastudio 1.14.0 (27468f75a5c969736ff663140d46f927d3ac749b, 2019-12-18T20:21:08.840Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### PR DESCRIPTION
**Pull request by anthonydresser**
This PR fixes #8768

### CODE REVIEW

File: src/sql/workbench/contrib/query/browser/queryResultsView.ts [hunk 1]
```diff
@@ -317,8 +318,8 @@ export class QueryResultsView extends Disposable {
 			this.setQueryRunner(info.queryRunner);
 		} else {
 			let disposable = this.queryModelService.onRunQueryStart(c => {
-				if (c === input.uri) {
-					let info = this.queryModelService._getQueryInfo(input.uri);
+				if (URI.parse(c).toString() === URI.parse(input.uri).toString()) {
```
Comment (kburtram) [inline src/sql/workbench/contrib/query/browser/queryResultsView.ts]: no concerns with undefined values here?

**Comment by kburtram** [comment]
@anthonydresser I'll merge and port to release/1.14 so we can get a hotfix staged.  I left a comment on the PR to consider.
