### PR TITLE
Fixed an issue when azure account is expired or not valid

### LINKED ISSUE #13228: ML - Azure loading subscription doesn't work when it's first time login to azure
- Azure Data Studio Version:

Steps to Reproduce:

1. open ML import model wizard
2. select Azure 
3. make sure you haven't login to azure before. login for the first time
4. select subscription

Expected: subscriptions should be loaded
Actual: the drop down is empty. closing the wizard and reopening fixes the problem

### PR DESCRIPTION
**Pull request by llali**
This PR fixes #13228

### CODE REVIEW

File: extensions/machine-learning/src/views/models/modelBrowsePage.ts [hunk 1]
```diff
@@ -80,24 +80,24 @@ export class ModelBrowsePage extends ModelViewBase implements IPageView, IDataCo
...
 					this.registeredModelsComponent.removeComponents(this._formBuilder);
-					this.localModelsComponent.addComponents(this._formBuilder);
 					await this.localModelsComponent.refresh();
+					this.localModelsComponent.addComponents(this._formBuilder);
 				}
 
 			} else if (this.modelSourceType === ModelSourceType.Azure) {
 				if (this.localModelsComponent && this.azureModelsComponent && this.registeredModelsComponent) {
 					this.localModelsComponent.removeComponents(this._formBuilder);
+					await this.azureModelsComponent.refresh();
```
Comment (udeeshagautam) [inline extensions/machine-learning/src/views/models/modelBrowsePage.ts:90]: can you elaborate more on these ordering changes please?

**Review by udeeshagautam — APPROVED** [review]

**Review by kburtram — APPROVED** [review]
Looks fine to me.  But it's not super-clear from the change why the refresh before the addComponents fixes the issue.

File: extensions/machine-learning/src/views/models/modelBrowsePage.ts (hunk 1 above)
Comment (llali) [reply extensions/machine-learning/src/views/models/modelBrowsePage.ts:90]: refresh loads the data  and add components creates the UI. so if the data is loaded after UI is loaded, we might show the UI for when there's no user
