### PR TITLE
Tab trap for modal (closes #5930)

### LINKED ISSUE #5930: [Accessibility]A11y__AzureDataStudio_CreateDatabaseMasterKey _Keyboard: Keyboard focus get trapped on the page after tab key is pressed on "Cancel" button and only moves when Shift tab key is used.
[Check out Keros!](
https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Environment Details:**
Application name: Azure Data Studio
Version: 1.8.0-insider (user setup)
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Additional Details:**
Tool Name: Keyboard
MAS Reference: MAS2.1.2

**Repro Steps:**
1.Launch the Azure Data Studio application.
2.Navigate to "Enable SQL server2019 preview->select table from the database->Create External Table screen should open->click on next button.
3. Observed that Keyboard focus get trapped on the page after tab key is pressed on "Cancel" button.

**Actual:**
Keyboard focus get trapped on the page after tab key is pressed on "Cancel" button and only moves when Shift tab key is used.

**Expected:**
Keyboard focus should not get trapped on the page after tab key is pressed on "Cancel" button and focus should move on the other control.

**User Impact:**
Keyboard only user will find the difficulties to navigate after "Cancel" button using tab key.

**Recommendation:**
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference:**
**MAS2.1.2**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={ebdc3fe1-09a9-4aa2-a29b-e97764774e6c}

**Attachment for Reference:**

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #6031: [Accessibility]A11y__AzureDataStudio_CreateExternalTable _Keyboard: Keyboard focus get trapped on the page after tab key is pressed on "Cancel" button and only moves when Shift tab key is used.
[Check out Keros! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Environment Details:**
Application name: Azure Data Studio
Version: 1.8.0-insider (user setup)
Commit: 2ca39b5
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Additional Details:**
MAC Version: 10.14.5
Tool name: Keyboard
MAS Number: MAS2.4.7

**Steps to Reproduce:** 
1. Install the app Azure Data Studio
2. Enable   SQL server2019 preview->select table from the database.
3. Navigate till "Cancel" button using tab.
4. Press tab again on "Cancel " button and observed that there is a keyboard trap.

**Actual:**
Keyboard focus get trapped on the page after tab key is pressed on "Cancel" button and only moves when Shift tab key is used.
**Similar issue observed in following pages:**
**1.CSVSelectDestinationDatbse:** Connect to database->navigate to the Data services folder->HDFS Folder-> navigate to CSV files folder->Right click on the files->Select option Create external table from CSV files
**2.MapDataSrcObjects:** Enable SQL server2019 preview->select table from the database->Create External Table screen should open->Next button->Create Database Master Key screen should open->click on next button->fill all the required details->click on next button.

**Expected:**
Keyboard focus should not get trapped on the page after tab key is pressed on "Cancel" button and focus should move on the other control.

**User Impact:**
Keyboard only user will find the difficulties to navigate after "Cancel" button using tab key.

**Recommendation:
Please refer the following snippet link for fixes:**
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference:
MAS2.1.2 :**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={ebdc3fe1-09a9-4aa2-a29b-e97764774e6c}

**Attachment for Reference:**

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by qifahs**
This PR fixes #5930. The modal dialog in ADS has the logic for trapping the tab. However it was not comparing against the right first and last tabbable elements. As a result the tab order could bleed into elements in the background in ADS, outside of the modal dialog. This fix includes the following:
- Find first and last tabbable element on the _bodyContainer, which includes all items in the dialog. This gets the code back in the state it was in August.
- Determine the first and last element on every tab press. The contents of the dialog can change. Just remembering the elements in the beginning does not help.
- Separate the logic for setting the focus on the most logical element in a wizard. This executes once for the dialog. And does not conflict with the tab trapping logic for modal dialogs.

Also fixes #6031 .

### CODE REVIEW

File: src/sql/workbench/browser/modal/modal.ts [hunk 1]
```diff
@@ -316,29 +317,30 @@ export abstract class Modal extends Disposable implements IThemable {
...
+	public setFocusableElements() {
+		// Try to find focusable element in dialog pane rather than overall container. _modalBodySection contains items in the pane for a wizard.
+		// This ensures that we are setting the focus on a useful element in the form when possible.
+		let focusableElements = this._modalBodySection ?
+		this._modalBodySection.querySelectorAll('a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), [tabindex="0"]') :
+		this._bodyContainer.querySelectorAll('a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), [tabindex="0"]');
+
+		this._focusedElementBeforeOpen = <HTMLElement>document.activeElement;
+
+		if (focusableElements[0]) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modal/modal.ts]: Just to be safe should check focusableElements.length > 0. (I wouldn't' expect that to ever happen though since we have the buttons - and I'm not sure what we would do in that case if we did indeed have no focusable elements. Probably just capture the tab events and stop them propagating but not do anything else?)

File: src/sql/workbench/browser/modal/modal.ts [hunk 2]
```diff
@@ -316,29 +317,30 @@ export abstract class Modal extends Disposable implements IThemable {
...
 
 	/**
-	 * Focuses the modal
-	 * Default behavior: focus the first focusable element
+	 * Set focusable elements in the modal dialog
 	 */
-	protected focus() {
-		if (this._firstFocusableElement) {
-			this._firstFocusableElement.focus();
+	public setFocusableElements() {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modal/modal.ts]: This name could probably be updated now since it's really just initializing the first focused element on open. Maybe something like `setInitialFocusedElement()`

File: src/sql/workbench/browser/modal/modal.ts [hunk 3]
```diff
@@ -316,29 +317,30 @@ export abstract class Modal extends Disposable implements IThemable {
...
 	 */
-	public setFocusableElements() {
-		// try to find focusable element in dialog pane rather than overall container
-		this._focusableElements = this._modalBodySection ?
-			this._modalBodySection.querySelectorAll('a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), [tabindex="0"]') :
-			this._bodyContainer.querySelectorAll('a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), [tabindex="0"]');
-		if (this._focusableElements && this._focusableElements.length > 0) {
-			this._firstFocusableElement = <HTMLElement>this._focusableElements[0];
-			this._lastFocusableElement = <HTMLElement>this._focusableElements[this._focusableElements.length - 1];
+	public setFirstLastTabbableElement() {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modal/modal.ts]: And just to check - this works correctly with the wizard dialogs that have multiple pages?

**Comment by qifahs** [comment]
> This will be great to have, thanks! It looks like this will also fix #6031 - could you verify and then if so associate that with this PR so it gets closed?

I checked this and it does fix #6031. I have included this in the description.

File: src/sql/workbench/browser/modal/modal.ts (hunk 1 above)
Comment (qifahs) [reply src/sql/workbench/browser/modal/modal.ts]: Good point. I'll add that check.

File: src/sql/workbench/browser/modal/modal.ts (hunk 2 above)
Comment (qifahs) [reply src/sql/workbench/browser/modal/modal.ts]: That is a better name now. I'll update it.

File: src/sql/workbench/browser/modal/modal.ts (hunk 3 above)
Comment (qifahs) [reply src/sql/workbench/browser/modal/modal.ts]: Yes it does.
