### PR TITLE
Fix for null shift-tab/focus

### LINKED ISSUE #8889: New row NULL values are not restored after Shift-TAB
- Azure Data Studio Version: `master`, regression from 1.14.1

Steps to Reproduce:

1. Edit Data on a table
2. Use TAB to move through the columns in the new row
3. Use Shift-TAB to navigate backwards through and out of new row

Expected: New row initially contains all NULL values.  NULLS are replaced with blank text box when there is focus on a cell.  When the focus leaves the cell the NULL value is replaced in the cell.  After using shift-tab to leave the new row the entire row should contain NULLs and appear the same as it initially did.

Actual: NULL values are replaced with blank cells after focus leaves the cell.

*Compares master to 1.14.1 after tabbing through and back out of new row*
image

### PR DESCRIPTION
**Pull request by smartguest**
Here are the primary changes listed:

On Line 378 in editdatagridpanel.ts: changed the formatter in the columnDefinitions to use a custom formatter in the class, instead of one in tables.

On Line 171 and 739: NULL is used to indicate a null row as the loading of cell values is handled primarily by slick.grid api which only recognizes NULL, and not undefined, as empty (not counting empty strings)

slick.grid api is called first when a cell is clicked and loads the value in before it can be processed by the main code. The code cannot determine whether a cell has been changed or not because of this.

This PR fixes #8889

### CODE REVIEW

File: src/sql/workbench/contrib/editData/browser/editData.component.ts [hunk 1]
```diff
@@ -172,10 +172,15 @@ export class EditDataComponent extends GridParentComponent implements OnInit, On
...
 			// replace the line breaks with space since the edit text control cannot
 			// render line breaks and strips them, updating the value.
-			if (Services.DBCellValue.isDBCellValue(value) && !value.isNull) {
+			/* tslint:disable:no-null-keyword */
+			let valueMissing = value === undefined || value === null || (Services.DBCellValue.isDBCellValue(value) && value.isNull);
+			if (!valueMissing && Services.DBCellValue.isDBCellValue(value)) {
 				returnVal = this.spacefyLinebreaks(value.displayValue);
 			} else if (typeof value === 'string') {
 				returnVal = this.spacefyLinebreaks(value);
+			} else if (valueMissing) {
```
Comment (MaddyDev) [inline src/sql/workbench/contrib/editData/browser/editData.component.ts]: if you check this first you can avoid having it checked twice.

File: src/sql/workbench/contrib/editData/browser/editData.component.ts [hunk 2]
```diff
@@ -725,4 +730,38 @@ export class EditDataComponent extends GridParentComponent implements OnInit, On
 		}
 
 	}
+
+	/*Formatter for Column*/
+	private getColumnFormatter(row, cell, value, columnDef, dataContext) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editData.component.ts]: Please add types for the params and return value
