### PR TITLE
Fix markdown cell toolbar focus not being visible

### LINKED ISSUE #10653: A11y_AzureDataStudioStayHealthy_Notebook_Markdown Toolbar_Keyboard: Keyboard focus is not visible on Toolbar Buttons.
“[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#MAS2.4.7;#DesktopApp;#SQL Azure Data Studio;#FTP;#Keyboard;#Benchmark;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider (system setup)
Commit: 8288360
Date: 2020-05-29T05:54:49.731Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Additional Details:**
MAS References: MAS2.4.7

**Repro Steps:**

1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Navigate to File --> New Notebook.
4. Navigate upto + Cell button in notebook, hit enter & select markdown cell.
5.Navigate using keyboard tab key and check whether the keyboard focus is visible or not on cell Toolbar Buttons.

**Actual:**
Keyboard focus is not visible on cell toolbar buttons.

**Expected:**
Keyboard focus should be visible on cell toolbar buttons.

**User Impact:**
User will get confuse as the focus is not clearly visible on interactive controls.

**Attachment link for Reference:**

[10653_A11y_AzureDataStudioStayHealthy_Notebook_Markdown Toolbar_Keyboard.zip](https://github.com/microsoft/azuredatastudio/files/4707532/10653_A11y_AzureDataStudioStayHealthy_Notebook_Markdown.Toolbar_Keyboard.zip)

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #10653 Markdown Cell Toolbar Keyboard Focus.

I utilized the masked-icon styles to use :before pseudo element similar to that of the notebook toolbar and cell toolbar. I made edits to reduce the CSS mask sizes in order to reduce code as well. 

Below are screenshots for the different themes illustrating the focus. 

Light Theme:
image

Dark Theme:
image

High Contrast Theme:
image

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 1]
```diff
@@ -51,16 +51,16 @@ export class MarkdownToolbarComponent {
...
-		let linkButton = this._instantiationService.createInstance(TransformMarkdownAction, 'notebook.linkText', '', 'insert-link', this.buttonLink, this.cellModel, MarkdownButtonType.LINK);
-		let listButton = this._instantiationService.createInstance(TransformMarkdownAction, 'notebook.listText', '', 'list', this.buttonList, this.cellModel, MarkdownButtonType.UNORDERED_LIST);
-		let orderedListButton = this._instantiationService.createInstance(TransformMarkdownAction, 'notebook.orderedText', '', 'ordered-list', this.buttonOrderedList, this.cellModel, MarkdownButtonType.ORDERED_LIST);
-		let imageButton = this._instantiationService.createInstance(TransformMarkdownAction, 'notebook.imageText', '', 'insert-image', this.buttonImage, this.cellModel, MarkdownButtonType.IMAGE);
-		let togglePreviewAction = this._instantiationService.createInstance(TogglePreviewAction, 'notebook.togglePreview', true, this.cellModel.showPreview);
+		let boldButton = this._instantiationService.createInstance(TransformMarkdownAction, 'notebook.boldText', '', 'bold masked-icon', this.buttonBold, this.cellModel, MarkdownButtonType.BOLD);
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:54]: nit: some of thI see a mix of 1 or 2 space keys, it doesn't matter, but better to be just 1 space key.

Comment (VasuBhog) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:54]: Fixed 👍

**Comment by Charles-Gagnon** [comment]
@VasuBhog Please make sure when you open PRs that it has a useful title - these typically end up as the commit message in main and so it's nice not to have a bunch of extra stuff like your alias in when viewing those messages.
