### PR TITLE
Make Create Azure Function with SQL Binding more efficient and simple

### LINKED ISSUE #18929: "Create Azure Function with SQL Binding" in empty workspace interrupts flow after project is created
1. Close all workspaces/folders
1. Right click on table and select "Create Azure Function with SQL binding"
1. Choose "Create new project"

Go through flow to create new project. After the project is created and the user chooses to add it to the current workspace then VS Code restarts (expected behavior). But this means that the "add SQL binding" flow is interrupted.

Ideally we should persist the state that the user wanted to add the binding, and after the restart then continue the flow where it was left off.

### LINKED ISSUE #19123: Looking for host file times out when creating new function project
1. Open VS Code with a non-empty workspace (open up some random folder, but specifically one that doesn't have a function project in it)
1. Run "Create Azure Function with SQL Binding" 
2. Go through prompts to create a new project,
3. When prompted to choose project location choose a folder NOT in the workspace
4. Then at the end choose to "Add project to workspace"

After everything is done and completed you will see this error in the console : 

`Timed out waiting for Azure Function project to be created. This may not necessarily be an error, for example if the user canceled out of the create flow.`

I believe this is because we're currently watching for the host.json file to be created. But the file watcher only watches the workspace, and the function project isn't added to the workspace until AFTER the host.json file is created so we never get that event.

2 options I see : 

1. Have the watcher promise also hook into workspace changes and look through them to see if a host.json file exists in of them
2. Add the folder the user selected for the project to the workspace from the start. We need to be careful here though since adding a folder to an empty workspace will reload the extension host

### LINKED ISSUE #19191: Create Azure function with SQL Binding when AzureFunctionCoreTools v3 is not installed
SQL Bindings 0.0.1

Steps to Reproduce:

1. Uninstall azure function core tools v3 (can run `npm ls -g azure-functions-core-tools@3` and `brew ls azure-functions-core-tools@3` to see if it is installed.

2. Run Create Azure Function with SQL Binding 
3. Follow prompts

Issue with createFunction API since we pick a specific target framework:
Screen Shot 2022-04-22 at 12 54 49 PM

The issue is that the project version defaults to the latest GA version which would be v4 and therefore the target frameworks used for v4 would be .Net 6.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR simplifies our process to Create Azure Function with SQL Binding. 

Three Scenarios were covered: 
1. User has an azure function project in a folder (multiple or single)
2. User has an empty workspace (no folder open) or User has no workspace/folder open

Flow is found [here](https://www.figma.com/file/3f9jwshitDGh79bFNkiFHV/Create-Azure-Function-with-SQL-Binding-Design?node-id=0%3A1)

Issues fixed:
- Include Password Prompt for when the user does Scenario 2 fixes https://github.com/microsoft/azuredatastudio/issues/19122
- Fixes #19191 : 
  Screen Shot 2022-04-22 at 12 54 49 PM
- Fixes #18929
- Fixes #19123 

General Flow of Logic:
- Find Azure Function Project
- Prompt For Binding Type
- Based on entry point (command palette vs command via table) show prompts 
- Prompt for Azure Function Name
- Prompt For Connection String Setting Name and Password for Connection String (Scenario 1 - adds connection string to local.settings.json) 
- Create Function API call (ask for namespace)
- Prompt to Include Password for connection string and adds to local.settings.json

### CODE REVIEW

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 1]
```diff
@@ -20,33 +20,108 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+					projectFile = '';
+					let workspaceFolder = vscode.workspace.rootPath;
+					if (!workspaceFolder) {
+						// user does not have a workspace open and therefore will have to pick a folder to create the project in
+						const browseProjectLocation = await vscode.window.showQuickPick(
+							[constants.browseEllipsisWithIcon],
+							{ title: constants.selectAzureFunctionProjFolder, ignoreFocusOut: true });
+						if (!browseProjectLocation) {
+							// User cancelled
+							return undefined;
```
Comment (barbaravaldez) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:73]: No need to return undefined here. Just return

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 2]
```diff
@@ -20,33 +20,108 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+						.withAdditionalProperties(propertyBag).send();
+					return;
+				} else if (projectCreate === constants.createProject) {
+					telemetryStep = 'helpCreateAzureFunctionProject';
+					TelemetryReporter.createActionEvent(TelemetryViews.CreateAzureFunctionWithSqlBinding, TelemetryActions.helpCreateAzureFunctionProject)
+						.withAdditionalProperties(propertyBag).send();
+
+					isCreateNewProject = true;
+					// set projectFile to empty string so we know that the user is creating a new azure function project
+					projectFile = '';
```
Comment (barbaravaldez) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:64]: Do we need to reset the value to empty here? It seems we already have the isCreateNewProject boolean to know if the user is creating a new azure function project.

**Review by barbaravaldez — CHANGES_REQUESTED** [review]

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 3]
```diff
@@ -198,12 +198,12 @@ export async function getSettingsFile(projectFile: string): Promise<string | und
 
 /**
  * Retrieves the new function file once the file is created and the watcher disposable
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:200]: complete this

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 4]
```diff
@@ -244,10 +244,10 @@ export async function addNugetReferenceToProjectFile(selectedProjectFile: string
  * Adds the Sql Connection String to the local.settings.json
  * @param connectionString of the SQL Server connection that was chosen by the user
  */
-export async function addConnectionStringToConfig(connectionString: string, projectFile: string): Promise<void> {
+export async function addConnectionStringToConfig(connectionString: string, projectFile: string, settingName: string = constants.sqlConnectionStringSetting): Promise<void> {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:247]: update xml doc

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 5]
```diff
@@ -511,10 +510,10 @@ export async function promptAndUpdateConnectionStringSetting(projectUri: vscode.
 /**
  * Prompts the user to include password in the connection string and updates the connection string based on user input
  * @param connectionInfo connection info from the connection profile user selected
- * @param localSettingsPath path to the local.settings.json file
+ * @param localSettingsPath path to the local.settings.json file (undefined when creating a new azure function project)
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:513]: The way this is worded makes me think that the parameter is required - it would just be undefined. In this case I would suggest just phrasing it that this field is optional instead

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 6]
```diff
@@ -558,8 +557,8 @@ export async function promptConnectionStringPasswordAndUpdateConnectionString(co
 		if (includePassword !== constants.yesString && !userPassword && connectionInfo?.authenticationType === 'SqlLogin') {
 			// if user does not want to include password or user does not enter password, show warning message that they will have to enter it manually later in local.settings.json
 			void vscode.window.showWarningMessage(constants.userPasswordLater, constants.openFile, constants.closeButton).then(async (result) => {
-				if (result === constants.openFile) {
-					// open local.settings.json file
+				if (result === constants.openFile && localSettingsPath) {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:560]: We shouldn't even be prompting if we don't have a file to open

File: extensions/sql-bindings/src/common/utils.ts [hunk 7]
```diff
@@ -140,11 +140,16 @@ export function timeoutPromise(errorMessage: string, ms: number = 10000): Promis
...
- * @param folderPath selected project folder path
  * @param fileName base filename to use
+ * @param folderPath selected project folder path
  * @returns a promise with the unique file name, or undefined
  */
-export async function getUniqueFileName(folderPath: string, fileName: string): Promise<string | undefined> {
+export async function getUniqueFileName(fileName: string, folderPath?: string,): Promise<string | undefined> {
+	if (!folderPath) {
+		// user is creating a brand new azure function project
+		return;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/utils.ts:150]: `return undefined`

File: extensions/sql-bindings/src/common/utils.ts [hunk 8]
```diff
@@ -140,11 +140,16 @@ export function timeoutPromise(errorMessage: string, ms: number = 10000): Promis
  * Gets a unique file name
  * Increment the file name by adding 1 to function name if the file already exists
  * Undefined if the filename suffix count becomes greater than 1024
- * @param folderPath selected project folder path
  * @param fileName base filename to use
+ * @param folderPath selected project folder path
  * @returns a promise with the unique file name, or undefined
  */
-export async function getUniqueFileName(folderPath: string, fileName: string): Promise<string | undefined> {
+export async function getUniqueFileName(fileName: string, folderPath?: string,): Promise<string | undefined> {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/utils.ts:147]: Extra ,

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 9]
```diff
@@ -20,33 +20,108 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+					let workspaceFolder = vscode.workspace.rootPath;
+					if (!workspaceFolder) {
+						// user does not have a workspace open and therefore will have to pick a folder to create the project in
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:67]: We should always be prompting the user where they want to save the project regardless of whether they have a workspace folder open. What's the purpose of this check?

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 10]
```diff
@@ -71,234 +147,135 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
-			} else {
-				newNode = newNode.parentNode;
+		} else {
+			// if user selects table in tree view we use connection info from Object Explorer node
+			telemetryStep = 'launchFromTable';
+			connectionInfo = node.connectionInfo;
+			// set the database containing the selected table so it can be used
+			// for the initial catalog property of the connection string
+			let newNode: ITreeNodeInfo = node;
+			while (newNode) {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:163]: This logic to get the database name should go in a separate helper function - it's generic enough (and this function is massive enough as it is)

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 11]
```diff
@@ -24,8 +24,8 @@ export interface ILocalSettingsJson {
 }
 
 export interface IFileFunctionObject {
-	filePromise: Promise<string>;
-	watcherDisposable: vscode.Disposable;
+	filePromise: Promise<string> | undefined;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:27]: Why would these ever need to be undefined?

Comment (VasuBhog) [reply extensions/sql-bindings/src/common/azureFunctionsUtils.ts:27]: Need to have this undefined since in the `finally block` we dispose of it and that would happen if the user exits out of selecting a folder. This would make the `newFunctionFileObject` undefined.

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts (hunk 3 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/common/azureFunctionsUtils.ts:200]: What do you mean by this?

Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/common/azureFunctionsUtils.ts:200]: `and the watcher disposable`

the sentence seems incomplete. Or maybe just written wrong (`new function file and watcher disposable once`...?). It doesn't make any sense as it is.

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts (hunk 11 above)
Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/common/azureFunctionsUtils.ts:27]: Then just make the whole object undefined - not the specific properties within it. I don't see any reason why either of these would ever be undefined - they're created at the same time and once they're done being used the entire object can just be deleted.

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts (hunk 3 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/common/azureFunctionsUtils.ts]: Let me know if the updated string ` New azure function file watcher and watcher disposable to be used to watch for changes to the azure function project
` is better.

**Comment by VasuBhog** [comment]
Follow up  PR will cover this issue #19203

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 12]
```diff
@@ -56,249 +123,144 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+					newNode = newNode.parentNode;
+				}
 			}
+
+			objectName = utils.generateQuotedFullName(node.metadata.schema, node.metadata.name);
 		}
-		// Ask binding type for promptObjectName
-		quickPickStep = 'getBindingType';
-		let selectedBinding = await azureFunctionsUtils.promptForBindingType();
+		telemetryStep = CreateAzureFunctionStep.getConnectionString;
```
Comment (barbaravaldez) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:159]: why do we need telemetryStep? It seems that you are reassigning it's value without sending it as telemetry

Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:159]: So currently I have this so that if an error occurs at any point or if the user cancels a certain step within the flow then in the finally block we would send where they left off from.

**Review by barbaravaldez — APPROVED** [review]

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 13]
```diff
@@ -219,27 +219,23 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
 			.withAdditionalProperties(propertyBag)
 			.withConnectionInfo(connectionInfo).send();
 
+		// check for the new function file to be created and dispose of the file system watcher
+		const timeoutForFunctionFile = utils.timeoutPromise(constants.timeoutAzureFunctionFileError);
+		let functionFilePath = await Promise.race([newFunctionFileObject.filePromise, timeoutForFunctionFile]);
+
 		// prompt user for include password for connection string
-		if (isCreateNewProject) {
+		if (isCreateNewProject && functionFilePath) {
```
Comment (VasuBhog) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:227]: Need to make sure the azure function project is created prior to adding the connection string to the local.settings.json for the folder the user selected (and added to the workspace).

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 14]
```diff
@@ -575,3 +575,21 @@ export async function promptConnectionStringPasswordAndUpdateConnectionString(co
 		return undefined;
 	}
 }
+
+export async function getDatabase(connectionInfo: IConnectionInfo): Promise<string | undefined> {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:579]: `promptSelectDatabase` - it's not clear what "get" means in this case

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 15]
```diff
@@ -20,285 +20,251 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
-			selectedBindingType = selectedBinding;
-			propertyBag.bindingType = selectedBindingType;
-			TelemetryReporter.createActionEvent(TelemetryViews.CreateAzureFunctionWithSqlBinding, TelemetryActions.startCreateAzureFunctionWithSqlBinding)
+	let isCreateNewProject: boolean = false;
+	let newFunctionFileObject: azureFunctionsUtils.IFileFunctionObject | undefined;
+
+	try {
+		const azureFunctionApi = await azureFunctionsUtils.getAzureFunctionsExtensionApi();
+		if (!azureFunctionApi) {
+			propertyBag.exitReason = exitReason;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:33]: This should probably be "error" at this point

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 16]
```diff
@@ -20,285 +20,251 @@ export async function createAzureFunction(node?: ITreeNodeInfo): Promise<void> {
...
+		telemetryStep = CreateAzureFunctionStep.getAzureFunctionProject;
+		if (!projectFile) {
+			while (true) {
+				// show warning message that user needs an azure function project to create a function
+				let projectCreate = await vscode.window.showErrorMessage(constants.azureFunctionsProjectMustBeOpened,
+					constants.createProject, constants.learnMore);
+				if (projectCreate === constants.learnMore) {
+					telemetryStep = CreateAzureFunctionStep.learnMore;
+					void vscode.commands.executeCommand('vscode.open', vscode.Uri.parse(constants.sqlBindingsDoc));
+					TelemetryReporter.createActionEvent(TelemetryViews.CreateAzureFunctionWithSqlBinding, telemetryStep)
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:55]: Do you need to send this event? Couldn't you just use the exit event and check for step == learnMore?

**Review by Charles-Gagnon — APPROVED** [review]
I didn't spend a ton of time going through all the logic - way too many changes to be able to fully review this. Make sure you're spending lots of time testing this yourself and setting up bug bashes as needed.

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 16 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:55]: Yeah, that's right. We could also use the final block to see if it exited with the step learnMore.
