### PR TITLE
Fix/open relative on dev

### LINKED ISSUE #8147: Can't open relative notebook links on dev build
```
Unable to read file (Error: File not found (d:\src\azuredatastudio.build\builtInExtensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\common\sop007-get-key-version-information.ipynb))
```

Looks like we're not concatenating the path correctly. It should be `d:\src\azuredatastudio\.build` Oddly this only seems to be on dev builds though - I'm not seeing this on the release branch nor insiders builds. 

It's in the actual link on the page too - so something is going on when opening the notebook.

image

This is what it looks like in the Notebook 

```
    "-   [SOP007 - Version information (azdata, bdc,\n",
    "    kubernetes)](../common/sop007-get-key-version-information.ipynb)\n",
```

### PR DESCRIPTION
**Pull request by MaddyDev**
When formatting the links on the markdown, we're calling removeMarkdownEscapes which removes the any matching the following regex: /\\([\\`*_{}[\]()#+\-.!])/
So if the path is below: (it's getting rid of the \\. before build in the path)
$localdrive\git\azuredatastudio\\.build\builtInExtensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\common\sop007-get-key-version-information.ipynb

This PR fixes #8147

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts [hunk 1]
```diff
@@ -111,7 +111,11 @@ export class NotebookMarkdownRenderer {
 				text = removeMarkdownEscapes(text);
 			}
 			title = removeMarkdownEscapes(title);
-			href = removeMarkdownEscapes(href);
+			// only remove escaped characters if it's a hyperlink, filepath usually can start with .{}_
+			// and the below function escapes them if it encounters in the path.
+			if (!path.isAbsolute(href)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: This is still going to break if you have a relative link to a folder with a . in it though, right? Do we ever even escape these links? It would seem like the correct thing to do here is ensure that the markdown links are properly escaped before this is called.

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: relative links are resolved before coming to this check.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: Then what's the point of the isAbsolute check? What paths can make it here that aren't absolute and need to be unescaped?

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts [hunk 2]
```diff
@@ -59,7 +59,7 @@ export class NotebookMarkdownRenderer {
 		let signalInnerHTML: () => void;
 		const withInnerHTML = new Promise(c => signalInnerHTML = c);
 
-		let notebookFolder = path.dirname(this._notebookURI.fsPath) + '/';
+		let notebookFolder = this._notebookURI ? path.dirname(this._notebookURI.fsPath) + '/' : '';
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: Is always using a / appropriate here? vs os-specific one

File: src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+		assert.strictEqual(result.innerHTML, `<p><img src="someimageurl" alt="image" title="caption" width="100" height="200"></p>`);
+	});
+
+	test('link from local file path', () => {
+		let result: HTMLElement = notebookMarkdownRenderer.renderMarkdown({ value: `[Link to File Path](someFileurl)`, isTrusted: true });
+		assert.strictEqual(result.innerHTML, `<p><a href="someFileurl" data-href="someFileurl" title="someFileurl">Link to File Path</a></p>`);
+	});
+
+	test('link from relative path', () => {
+		let result: HTMLElement = notebookMarkdownRenderer.renderMarkdown({ value: `[Link to relative path](/test/.build/someimageurl)`, isTrusted: true });
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts]: This isn't relative on mac - is that working as intended there? Wasn't the issue with \ on windows anyways - is the path then converted correctly during the implementation of this and so this would fail without your fix?

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts [hunk 4]
```diff
@@ -203,7 +207,7 @@ export class NotebookMarkdownRenderer {
 			href = this.resolveUrl(base, href);
 		}
 		try {
-			href = encodeURI(href).replace(/%5C/g, '\\').replace(/%25/g, '%');
+			href = encodeURI(href).replace(/%5C/g, '\\').replace(/%25/g, '%').replace(/%7C/g, '|');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: The | unescape needs to happen first, otherwise unescaping the % could result in things mistakenly being unescaped into a |.

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 1 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: http links

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 2 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: I haven't added that code here but since am touching the code I can update it to os-specific one. @chlafreniere do you know if we had this for a specific reason?

File: src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts (hunk 3 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts]: I think I need to re-think and write this test, since it's not actually getting the relative link here as well. I haven't tested this on Mac. Let me test and update it here.

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 4 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: so this is the correct way ?-> encodeURI(href).replace(/%5C/g, '\\').replace(/%7C/g, '|').replace(/%25/g, '%');

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: Yes, that should be fine.

File: src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts (hunk 3 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/test/browser/notebookMarkdown.test.ts]: @Charles-Gagnon  I've run the same on mac and the tests passed.

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts [hunk 5]
```diff
@@ -59,7 +59,7 @@ export class NotebookMarkdownRenderer {
 		let signalInnerHTML: () => void;
 		const withInnerHTML = new Promise(c => signalInnerHTML = c);
 
-		let notebookFolder = path.dirname(this._notebookURI.fsPath) + '/';
+		let notebookFolder = this._notebookURI ? path.dirname(this._notebookURI.fsPath) + path.sep : '';
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: let's do path.join() here

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 2 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: No reason that I'm aware of.

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 1 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: In path.test.ts we can also see that 'http://foo.com/bar' is a relative path

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 5 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: path.join(path.dirname(this._notebookURI.fsPath), path.sep) ?

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 1 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: now that's confusing, they even have an absolute path like z:/foo/bar.txt in relative path.

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 5 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: looks right, yup!

File: src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts (hunk 1 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/outputs/notebookMarkdown.ts]: I believe that's for `path.posix.isAbsolute`, which will return a relative path.

**Comment by Charles-Gagnon** [comment]
@MaddyDev Looks like you need to format notebookMarkdown.ts

**Comment by MaddyDev** [comment]
> Make sure you fix the format error and verify checks pass before merging in

Sure. Thanks!
