### PR TITLE
Make 'Script to notebook' consistent with 'Deploy' when user cancels during password re-acquisition for controller

### LINKED ISSUE #13555: Cancelling out of Password reacquisition dialog for controller leaves MIAA wizard broken
If the user cancels out of the dialog trying to reacquire a password for a controller at the end of the MIAA create dialog, then the 'Script to notebook' and 'Deploy' buttons stay disabled. The user should be allowed to re-invoke these buttons in this scenario.

**Steps to Reproduce:**
> 1. Have an arc controller added that does not have the password stored.
> 2. Go through the workflow to add a new SQL instance to this controller. Once you hit the 'Generate Script' button, a dialog pops up requesting the user to enter the password for the data controller. Cancel this dialog.
> 3. The opened dialog closes and the user context goes back to the last screen of the MIAA deployment wizard.

**Actual:**
The last screen of the MIAA deploy wizard after we canceled out of the controller password acquisition dialog has the 'Script to notebook' and 'Deploy' buttons disabled. Kindly note that all fields on the page have valid values and the page is in a fully 'validated' state.
image

**Expected:**
The dialog opened should not allow the user to modify the URL, name, and username fields in the dialog.

**Azure Data Studio Version:**
```
Version: 1.25.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

### PR DESCRIPTION
**Pull request by ranasaria**
This change ensures that ARC wizards' close if the user chooses to cancel instead of providing the controller password after a 'Script to notebook' action. This makes the 'Script to notebook' behavior consistent with the 'Deploy' button behavior.

This PR fixes #13555

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Please use more descriptive titles than `fix for issue <#>`. PR titles should ideally be a brief description of the change being made so it's easy to tell what a change is about when going back through commit history.

File: extensions/arc/src/extension.ts [hunk 1]
```diff
@@ -38,9 +38,11 @@ export async function activate(context: vscode.ExtensionContext): Promise<arc.IE
 		}
 		const dialog = new ConnectToControllerDialog(treeDataProvider);
 		dialog.showDialog();
-		const model = await dialog.waitForClose();
-		if (model) {
+		try {
+			const model = await dialog.waitForClose();
 			await treeDataProvider.addOrUpdateController(model.controllerModel, model.password);
+		} catch (err) {
+			console.log(`Error connecting to Controller dashboard ${err}`);
```
Comment (Charles-Gagnon) [inline extensions/arc/src/extension.ts:45]: This message isn't accurate - we're not "connecting to a controller dashboard" - but rather the controller itself. The dashboard has nothing to do with this.

File: extensions/arc/src/extension.ts [hunk 2]
```diff
@@ -59,9 +61,11 @@ export async function activate(context: vscode.ExtensionContext): Promise<arc.IE
 	vscode.commands.registerCommand('arc.editConnection', async (treeNode: ControllerTreeNode) => {
 		const dialog = new ConnectToControllerDialog(treeDataProvider);
 		dialog.showDialog(treeNode.model.info, await treeDataProvider.getPassword(treeNode.model.info));
-		const model = await dialog.waitForClose();
-		if (model) {
+		try {
+			const model = await dialog.waitForClose();
 			await treeDataProvider.addOrUpdateController(model.controllerModel, model.password, true);
+		} catch (err) {
+			console.log(`Error connecting to Controller dashboard ${err}`);
```
Comment (Charles-Gagnon) [inline extensions/arc/src/extension.ts:68]: Same here - this logic has nothing to do with the dashboard. It's just updating the connection information.

File: extensions/arc/src/test/models/controllerModel.test.ts [hunk 3]
```diff
@@ -36,8 +36,9 @@ describe('ControllerModel', function (): void {
 		});
 
 		it('Rejected with expected error when user cancels', async function (): Promise<void> {
+			const cancellationError = new UserCancelledError();
 			// Returning an undefined model here indicates that the dialog closed without clicking "Ok" - usually through the user clicking "Cancel"
```
Comment (Charles-Gagnon) [inline extensions/arc/src/test/models/controllerModel.test.ts:40]: Update comment

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts [hunk 4]
```diff
@@ -58,16 +59,27 @@ export class NotebookWizardModel extends ResourceTypeModel {
...
+			try {
+				notebook = await this.prepareNotebookAndEnvironment();
+			} catch (e) {
+				const isUserCancelled = (e: any) => e instanceof Error && 'type' in e && (<ErrorWithType>e).type === ErrorType.userCancelled;
+				// user cancellation is a normal scenario, we just bail out of the wizard without actually opening the notebook, so rethrow for any other case
+				if (!isUserCancelled(e)) {
+					throw e;
+				}
+			}
+			if (notebook!) { // open the notebook if it was successfully prepared
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts:77]: The ! shouldn't be necessary here

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts [hunk 5]
```diff
@@ -58,16 +59,27 @@ export class NotebookWizardModel extends ResourceTypeModel {
...
 		const lastPage = this.wizard.lastPage! as NotebookWizardPage;
 		if (lastPage.validatePage()) {
-			const notebook = await this.prepareNotebookAndEnvironment();
-			await this.openNotebook(notebook);
-			return true;
+			let notebook: Notebook;
+			try {
+				notebook = await this.prepareNotebookAndEnvironment();
+			} catch (e) {
+				const isUserCancelled = (e: any) => e instanceof Error && 'type' in e && (<ErrorWithType>e).type === ErrorType.userCancelled;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts:71]: Just use this logic directly - if you're not re-using the function no reason to add the extra overhead to create the function object here.

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 6]
```diff
@@ -110,10 +111,10 @@ abstract class ControllerDialogBase extends InitializingComponent {
 	public abstract async validate(): Promise<boolean>;
 
 	private handleCancel(): void {
-		this.completionPromise.resolve(undefined);
+		this.completionPromise.reject(new UserCancelledError(loc.userCancelledError));
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:114]: I guess this is fine - but is there any particular reason that you chose to throw an error instead of just continuing to return undefined? A couple thoughts about that : 

1. The VS Code APIs tend to just returned undefined when the dialog/popup is cancelled (such as quick pick items) so doing something different here is a bit confusing
1. A user cancelling generally isn't really an error so doesn't seem like something we should have throw
1. We only returned undefined if it's cancelled so it's not like there's other cases we're needing to take care of

**Review by Charles-Gagnon — APPROVED** [review]
Some comments I'd like to see addressed but overall looks fine

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts (hunk 5 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts:71]: makes the code more readable. The negated condition is harder to read otherwise

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts (hunk 6 above)
Comment (ranasaria) [reply extensions/arc/src/ui/dialogs/connectControllerDialog.ts:114]: I was not aware of vscode apis returning undefined for cancel. In general, do not like the use of sentinel values for communicating state. I think the treatment of 'cancellation' as success or failure is where the difference in approach is.

I will revert to the old behavior.

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts (hunk 5 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts:71]: I could make isUserCancelled a variable instead of function perhaps.

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts (hunk 6 above)
Comment (ranasaria) [reply extensions/arc/src/ui/dialogs/connectControllerDialog.ts:114]: reveted

File: extensions/arc/src/test/models/controllerModel.test.ts (hunk 3 above)
Comment (ranasaria) [reply extensions/arc/src/test/models/controllerModel.test.ts:40]: reverted to old behavior

File: extensions/arc/src/extension.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/arc/src/extension.ts:45]: changed back to old code.

File: extensions/arc/src/extension.ts (hunk 2 above)
Comment (ranasaria) [reply extensions/arc/src/extension.ts:68]: changed back to old code.

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts (hunk 5 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts:71]: Done. Changed isUserCancelled to a constant

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts (hunk 4 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizardModel.ts:77]: cleanded up.
