### PR TITLE
Bring back old editor resolving logic to fix saving in notebooks.

### LINKED ISSUE #21075: Notebook name not updated after saving it
Saving a new notebook does not update the name of the notebook in the editor.

Version: 1.40.0-insider
Commit: 9d921e4efc2a00c5c9c8f440c32fa2f6c9277737
Date: 2022-11-02T05:55:55.526Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Darwin x64 21.6.0

https://user-images.githubusercontent.com/34872381/199549464-71620f6d-abfb-48d5-a391-30f9aa95e16d.mov

### PR DESCRIPTION
**Pull request by corivera**
VS Code changed some of their EditorInput saving behavior a while back, which we picked up in the latest merge. AbstractTextResourceInput now returns an IUntypedEditor result, which just contains the editor URI. It used to handle resolving the new editor, but that's now supposed to be handled by downstream sources. I brought back that old editor resolving logic in our notebook save methods to fix problems we've been having with saved untitled notebooks notebooks not closing and reopening properly. Here's the original VS Code commit for reference about the code I brought back in: https://github.com/microsoft/vscode/commit/0e04328299ad24b0d7ff83bc9c763fa1ac5312bc#diff-9065af890ec775428cb4361fbd0b4eeb8131ea56f2e64a161440275e9fd98bdeL69

This PR fixes #21075

### CODE REVIEW

**Review by kburtram — APPROVED** [review]

**Review by chlafreniere — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts [hunk 1]
```diff
@@ -335,18 +338,40 @@ export abstract class NotebookInput extends EditorInput implements INotebookInpu
...
-		await this.setTrustForNewEditor(input);
+		let untypedInput = await this.textInput.saveAs(group, options);
+		let editorInput = await this.createEditorInput(untypedInput, group, true);
+		await this.setTrustForNewEditor(editorInput);
 		const langAssociation = languageAssociationRegistry.getAssociationForLanguage(NotebookLanguage.Ipynb);
-		return langAssociation.convertInput(input);
+		return langAssociation.convertInput(editorInput);
+	}
+
+	private async createEditorInput(untypedEditor: IUntypedEditorInput, group: GroupIdentifier, saveAs: boolean): Promise<EditorInput | undefined> {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts:357]:
```suggestion
	private async createEditorInput(untypedEditor: IUntypedEditorInput | undefined, group: GroupIdentifier, saveAs: boolean): Promise<EditorInput | undefined> {
```

File: src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts [hunk 2]
```diff
@@ -335,18 +338,40 @@ export abstract class NotebookInput extends EditorInput implements INotebookInpu
...
+		// If this save operation results in a new editor, either
+		// because it was saved to disk (e.g. from untitled) or
+		// through an explicit "Save As", make sure to replace it.
+		if (!untypedEditor) {
+			return undefined; // if we have an undefined input, then the save was cancelled, so do nothing here
+		}
+
+		let target = (<any>untypedEditor).resource;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts:365]: We should be avoiding using any wherever we can - it's too easy for stuff like this to silently cause runtime breaks. What editor type are you expecting here?

**Review by Charles-Gagnon — APPROVED** [review]
