### PR TITLE
Notebooks: Persist Chart Data when Re-Executing Cell

### LINKED ISSUE #14393: Notebok Visual Settings to be retained on subsequent execution
- Azure Data Studio Version: 1.2.6

**Steps to Reproduce:**

1. Run a query in a code cell and configure a chart
1. Re-run the cell 

The chart settings are not retained and the output defaults to table

**Fix Required:**

The cell should remember the chart configuration and render the chart accordingly without defaulting to table

### PR DESCRIPTION
**Pull request by chlafreniere**
https://user-images.githubusercontent.com/40371649/109739703-de439980-7b7e-11eb-8fea-d60cbe6b9d49.mp4

Fixes #14393. Saves chart state when the query is the same as it was on the previous execution. This seemed like a reasonable tradeoff, as if you were to completely rewrite your code cell, your previous chart data in the previous query may not make any sense.

Added tests for cellModel.

### CODE REVIEW

File: src/sql/workbench/services/notebook/browser/models/cell.ts [hunk 1]
```diff
@@ -1023,4 +1047,33 @@ export class CellModel extends Disposable implements ICellModel {
...
+	private cacheChartStateIfExists(): void {
+		this.clearPreviousChartState();
+		// If a cell's source was changed, don't cache chart state
+		if (!this._preventNextChartCache) {
+			this._outputs?.forEach(o => {
+				if (dataResourceDataExists(o)) {
+					if (o.metadata?.azdata_chartOptions) {
+						this._previousChartState.push(o.metadata.azdata_chartOptions);
+					} else {
+						this._previousChartState.push(null);
```
Comment (barbaravaldez) [inline src/sql/workbench/services/notebook/browser/models/cell.ts:1064]: Is there a reason why we use null instead of undefined?

**Review by lucyzhang929 — APPROVED** [review]

File: src/sql/workbench/services/notebook/browser/models/cell.ts (hunk 1 above)
Comment (chlafreniere) [reply src/sql/workbench/services/notebook/browser/models/cell.ts:1064]: `null` explicitly says that there is no value, whereas `undefined` may refer to a variable that just hasn't been given a value yet.

If this breaks convention, happy to change it; it just was natural for me to put `null` in here.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/notebook/browser/models/cell.ts:1064]: We should generally not be using null in our own code. Nothing else in our code base uses that convention so having null is confusing and could potentially have adverse side effects (since we sometimes check specifically for undefined)

File: src/sql/workbench/services/notebook/browser/models/cell.ts [hunk 2]
```diff
@@ -1023,4 +1047,33 @@ export class CellModel extends Disposable implements ICellModel {
...
+		this._preventNextChartCache = false;
+	}
+
+	private clearPreviousChartState(): void {
+		this._previousChartState = [];
+	}
+}
+
+function dataResourceDataExists(metadata: nb.ICellOutput): boolean {
+	return metadata['data'] && metadata['data']['application/vnd.dataresource+json'];
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/cell.ts:1078]: Can just do `return metadata['data']?.['application/vnd.dataresource+json'];`

File: src/sql/workbench/services/notebook/browser/models/cell.ts [hunk 3]
```diff
@@ -80,7 +80,10 @@ export class CellModel extends Disposable implements ICellModel {
 	private _isParameter: boolean;
 	private _onParameterStateChanged = new Emitter<boolean>();
 	private _isInjectedParameter: boolean;
+	private _previousChartState: any[] = [];
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/cell.ts:83]: Can't have a better type than any?

File: src/sql/workbench/services/notebook/browser/models/cell.ts [hunk 4]
```diff
@@ -80,7 +80,10 @@ export class CellModel extends Disposable implements ICellModel {
...
+	private _outputCounter = 0;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/cell.ts:84]: Some comments for these properties would be nice...hard to tell how the `_outputCounter` fits in to everything just by the name...

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts [hunk 5]
```diff
@@ -139,6 +139,9 @@ export class GridOutputComponent extends AngularDisposable implements IMimeCompo
 
 	updateResult(resultSet: ResultSetSummary, rows: ICellValue[][]): void {
 		this._table.updateResultSet(resultSet, rows);
+		if (this._table.chartDisplayed) {
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts]: > I wonder if this makes more sense to put in table.updateResultSet...is there a scenario where you'd want to update a result set but not update a table?

Not that I'm aware of. Will move there.

>And why only update it when the chart is displayed here? I would expect updateChartData to handle doing that check if anything (does having hidden stale chart data matter for anything?)

Seems reasonable. I looked into this, and being able to put this check into `updateChartData()`. We're constantly on a quest to decrease cell execution time, and when the chart action is invoked, `updateChartData()` gets called anyway. Double checked that a notebook saved with a chart isn't broken by this.

https://github.com/microsoft/azuredatastudio/blob/10f16b7d59c6976b5c1bbdbb9eff0c7323f36079/src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts#L549
