### PR TITLE
Fix a couple a11y issues with manage access

### LINKED ISSUE #7794: A11y_AzureDataStudio_ManageAccessForFile_Keyboard : Keyboard focus is not  landing on the form as soon as we click on manage access.
GitHub Tags:#A11y_ADS_OctTestPass;#A11yMAS; #A11yTCS;#SQL 
AzureDataStudio;#MAS2.4.3;#DesktopApp;#Mac;#Keyboard;

**Environment Details: **

Application Name: Azure Data Studio

Version: 1.12.0-insider (user setup)

Commit:6582debd7388b1be512fc3a9b956d3e54f6115e7

Date: 2019-10-03T08:56:27.454Z

VS Code: 1.38.0

Electron: 4.2.10

Chrome: 69.0.3497.128

Node.js: 10.11.0

V8: 6.9.427.31-electron.0

OS: MacOS Mojave 10.14.6

 

**Additional Details:**

Tool Name :Voice Over
**Steps to Reproduce:**

1. Install and Launch the application the azure data studio application.

2.Connet to the servers with the required credentials.

3.Navigate to the control panel and click on the “Jupyter books” icon. 

 4.Navigate till HDFS folder and right click on it and click on manage access.

5. Navigate with the help of keyboard "tab"

7.Observe the focus on the screen.

 

**Actual:**
Keyboard focus is not landing on the form as soon as we click on manage access.
This issue is through out the application.

 

**Expected:** 
Keyboard focus is should landing on the form as soon as we click on manage access.
 

**User Impact:**
Key board user will be confused if the focus remains out of the screen.
 

**Attachment for Reference:*

[7794_A11y_AzureDataStudio_ManageAccessForFile_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3760964/7794_A11y_AzureDataStudio_ManageAccessForFile_ScreenReader.pptx)

### LINKED ISSUE #7799: A11y_AzureDataStudio_ManageAccessForFile_AI4D:Name property does not exist for check box.
GitHubTags: #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG4.1.2;#WCAG4.2.1;#WCAG1.3.1;#DesktopApp;#Win32;#AI4D;

**Environment Details:**

Application Name: Azure Data Studio

Version: 1.12.0-insider (user setup)

Commit:6582debd7388b1be512fc3a9b956d3e54f6115e7

Date: 2019-10-03T08:56:27.454Z

VS Code: 1.38.0

Electron: 4.2.10

Chrome: 69.0.3497.128

Node.js: 10.11.0

V8: 6.9.427.31-electron.0

OS: Windows_NT x64 10.0.18362

 

**Additional Details:**

Tool Name : AI4D

 

**Steps to Reproduce:**

1. Install and Launch the application the azure data studio application.

2.Connet to the servers with the required credentials.

3.Navigate to the control panel and click on the “Jupyter books” icon. 

 4.Navigate till HDFS folder and right click on it and click on manage access.

5. Hover on the check box with the help of AI4D 

**Actual:**
Name property does not exist for all the check box on the screen.

 

**Expected:** 
Name property should exist for Check box.
 

**User Impact:**
Screen reader user will not able to coonect with the check box as  there is no name for the check box.

**Attachment for Reference:**
[7799A11y_AzureDataStudio_ManageAccessForFile_AI4D.pptx](https://github.com/microsoft/azuredatastudio/files/3750170/7799A11y_AzureDataStudio_ManageAccessForFile_AI4D.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7799
Fixes #7794

### CODE REVIEW

File: extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts [hunk 1]
```diff
@@ -280,21 +281,21 @@ export class ManageAccessDialog {
 		rowContainer.addItem(nameCell);
 
 		// Access - Read
-		const accessReadComponents = createCheckbox(builder, entry.getPermission(AclEntryScope.access).read, true, permissionsReadColumnWidth, permissionsRowHeight);
+		const accessReadComponents = createCheckbox(builder, entry.getPermission(AclEntryScope.access).read, true, permissionsReadColumnWidth, permissionsRowHeight, `${loc.accessHeader} ${loc.readHeader}`);
```
Comment (alanrenmsft) [inline extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts]: we shouldn't do string concatenation for localizable strings.

Comment (Charles-Gagnon) [reply extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts]: So for this the reasoning I went with is that this isn't a single sentence - it's two separate words that are used to describe what the box is about. I was also thinking of putting a - inbetween them but wasn't trying to avoid adding more clutter.

In the end I'm fine following the normal way of making a separate string but I felt like this case was special enough to warrant breaking that. 

Thoughts?

Comment (Benjin) [reply extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts]: If it's a simple concat like this where it doesn't chance sentence structure, isn't it okay?  The concern is typically when values are getting inserted mid-sentence.
