### PR TITLE
Fix error deleting HDFS mount

### LINKED ISSUE #8320: Delete mount gives error
Issue Type: <b>Bug</b>

When trying to delete a mount, it gives an error message. However, when I delete from CLI, it works fine.

"Error deleting mount - Cannot read property '_authPromise' of undefined"

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-01T23:25:46.501Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
datavirtualization|Mic|1.0.0
azdata-sanddance|msr|1.3.9
scala|sca|0.3.8

</details>

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #8320

### CODE REVIEW

File: extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts [hunk 1]
```diff
@@ -275,9 +275,9 @@ export class ClusterController {
 			mountPath);
 	}
 
-	private async deleteMountImpl(mountPath: string): Promise<MountResponse> {
-		let auth = await this._authPromise;
-		const api = new DefaultApiWrapper(this._username, this._password, this._url, auth);
+	private async deleteMountImpl(self: ClusterController, mountPath: string): Promise<MountResponse> {
```
Comment (alanrenmsft) [inline extensions/big-data-cluster/src/bigDataCluster/controller/clusterControllerApi.ts]: to avoid this you can also do ()=>{ this.deleteMountImpl(...)} when you call it.
