### PR TITLE
[Port] Fix HDFS node for Integrated auth (#12906)

### LINKED ISSUE #12905: Expanding the HDFS folder for BDC leads to an error
Issue Type: <b>Bug</b>

I connected to a BDC deployment on mssql.tdeupgrade.aris.local,31433 using Windows authentication. I expanded the HDFS folder in the Object explorer and I got this error "Error: Missing required inputs for CLuster controller API (URL, username, password)

image

Azure Data Studio version: azuredatastudio-insiders 1.24.0-insider (10d3a6b2bae26d9a95bc44df4843c9e62224e404, 2020-10-13T05:30:59.632Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (10.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #12905 - the casing was different so the check wasn't being done properly.

### CODE REVIEW

File: extensions/mssql/src/sqlClusterLookUp.ts [hunk 1]
```diff
@@ -149,7 +149,7 @@ async function createSqlClusterConnInfo(sqlConnInfo: azdata.IConnectionProfile |
 
 async function getClusterController(controllerEndpoint: string, connInfo: ConnectionParam): Promise<bdc.IClusterController | undefined> {
 	const bdcApi = <bdc.IExtension>await vscode.extensions.getExtension(bdc.constants.extensionName).activate();
-	let authType: bdc.AuthType = connInfo.options[constants.authenticationTypePropName] === AuthType.Integrated ? 'integrated' : 'basic';
+	let authType: bdc.AuthType = connInfo.options[constants.authenticationTypePropName].toLowerCase() === AuthType.Integrated ? 'integrated' : 'basic';
```
Comment (kburtram) [inline extensions/mssql/src/sqlClusterLookUp.ts:152]: no need to null check options before using the item in the array?

**Review by kburtram — APPROVED** [review]

File: extensions/mssql/src/sqlClusterLookUp.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply extensions/mssql/src/sqlClusterLookUp.ts:152]: As a safety thing I guess it couldn't hurt - but things would have to be pretty horribly broken in core for this to not be there and if it isn't we probably shouldn't be assuming the auth type.
