### PR TITLE
Fix links on WYSIWYG

### LINKED ISSUE #12899: WYSIWYG Notebook - Updating a cell with relative path causes removal of the paths
- Azure Data Studio Version:
Version: 1.23.0-rc1 (user setup)
Commit: 05615c796db46a766f62ffd90b4d78553b75e2d9
Date: 2020-10-12T18:54:16.767Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open an existing notebook with a relative path. See attached file (last cell).
2. Click edit on the text cell with a relative path. 
3. Switch to markdown **Split view** mode. You'll see the actual relative path value.
4. Switch back to **Rich Text** mode. Type in a new text in a new line.
5. Exit out of edit mode in the text cell. 
You'll now see that the relative paths are removed. i.e. no hover on links.
When you edit, you'll also see that the link has been removed both on the **Rich Text** and the **Split view** modes.

File for testing:
[KUS001 - Check Kqlmagic installation.txt](https://github.com/microsoft/azuredatastudio/files/5372639/KUS001.-.Check.Kqlmagic.installation.txt)
EditCausesBadRelativePath

The workaround is for users to always remember to use **Split View** or **Markdown** mode. But because the default mode is Rich Text view, this will significantly impact users with files where text cells have relative paths.

### PR DESCRIPTION
**Pull request by barbaravaldez**
This PR fixes #12899
On windows,  the href attribute from the html element is removed in untrusted notebooks.
When we convert the text to markdown the href attribute is empty that's why the links disappeared when switching between rich text view to split view.
The other thing that I fixed here is that markdown does not identify a path as a link if it contains whitespaces. When switching from markdown to WYSIWYG, we parse the href link so it removes all the encoding, so I replace all the whitespaces to %20 to keep the link working when switching from Split View to Rich Text View.

### CODE REVIEW

**Comment by MsSQLGirl** [comment]
@qifahs and @rajeshka - can you please help review this PR? this is needed for Livesite..

**Review by VasuBhog — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 1]
```diff
@@ -484,11 +485,17 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 		this.turndownService.addRule('a', {
 			filter: 'a',
 			replacement: (content, node) => {
-				if (node?.href) {
-					let relativePath = this.findPathRelativeToContent(node.href);
-					if (relativePath) {
-						return `[${node.innerText}](${relativePath})`;
-					}
+				//if notebook is untrusted then the link is save on the title
+				let path: URI;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:489]: `const path = node.href ? URI.parse(node.href) : URI.file(node.title);`

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 2]
```diff
@@ -504,13 +511,18 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
...
+	private findPathRelativeToContent(absolutePathURI: URI): string {
 		let notebookFolder = this.notebookUri ? path.join(path.dirname(this.notebookUri.fsPath), path.sep) : '';
 		if (notebookFolder) {
-			let absolutePathURI = URI.parse(elementContent);
 			if (absolutePathURI?.scheme === 'file') {
 				let relativePath = path.relative(notebookFolder, absolutePathURI.fsPath);
-				return relativePath ? relativePath : '';
+				//if path contains whitespaces then it's not identified as a link
+				relativePath = relativePath.replace(/\s/g, '%20');
+				if (relativePath.startsWith(path.join('.', path.sep))) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:521]: path.relative can start with `../` as well - are you purposely not checking for that?

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 3]
```diff
@@ -484,11 +485,17 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
...
-					let relativePath = this.findPathRelativeToContent(node.href);
-					if (relativePath) {
-						return `[${node.innerText}](${relativePath})`;
-					}
+				//if notebook is untrusted then the link is save on the title
+				let path: URI;
+				if (node.href) {
+					path = URI.parse(node.href);
+				} else {
+					path = URI.file(node.title);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:493]: Why are you using URI.file here?

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 4]
```diff
@@ -504,13 +511,18 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 		this._model.updateActiveCell(this.cellModel);
 	}
 
-	private findPathRelativeToContent(elementContent: string): string {
+	private findPathRelativeToContent(absolutePathURI: URI): string {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:514]: It would be great to add tests for this logic. It might be easiest to move this.notebookUri to be a param instead and then just make this a file level function

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts (hunk 3 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:493]: If I use URI.parse, then it doesn't create the the path correctly.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:493]: Why? Shouldn't they be the same value - just stored in different attributes?

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts]: So, it can be either an absolute path or a hyperlink.

**Review by lucyzhang929 — APPROVED** [review]

**Review by VasuBhog — APPROVED** [review]
Tested this locally and it fixes the issue that is linked. Along with retaining the link on WYSIWYG mode.

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 5]
```diff
@@ -484,11 +486,13 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
...
 			filter: 'a',
 			replacement: (content, node) => {
-				if (node?.href) {
-					let relativePath = this.findPathRelativeToContent(node.href);
-					if (relativePath) {
-						return `[${node.innerText}](${relativePath})`;
-					}
+				//On Windows, if notebook is not trusted then the href attr is removed.
+				// href contains either a hyperlink or an absolute path. (See resolveUrls method in notebookMarkdown.ts)
+				const notebookLink = node.href ? URI.parse(node.href) : (path.isAbsolute(node.title) ? URI.file(node.title) : undefined);
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:491]: the check for absolute is not needed. I'll remove it

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 6]
```diff
@@ -484,11 +486,13 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
...
+				const notebookFolder = this.notebookUri ? path.join(path.dirname(this.notebookUri.fsPath), path.sep) : '';
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:492]: I'm not sure about this one. I just moved the notebookFolder logic to this method, so the findPathRelativeToContent was easier to test.

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 7]
```diff
@@ -503,18 +507,24 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
...
 
-	private findPathRelativeToContent(elementContent: string): string {
-		let notebookFolder = this.notebookUri ? path.join(path.dirname(this.notebookUri.fsPath), path.sep) : '';
-		if (notebookFolder) {
-			let absolutePathURI = URI.parse(elementContent);
-			if (absolutePathURI?.scheme === 'file') {
-				let relativePath = path.relative(notebookFolder, absolutePathURI.fsPath);
-				return relativePath ? relativePath : '';
+export function findPathRelativeToContent(notebookFolder: string, contentPath: URI): string {
+	if (notebookFolder) {
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:513]: NotebookFolder would be either the directory name or an empty string

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 8]
```diff
@@ -503,18 +507,24 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
...
+			if (relativePath.startsWith(path.join('..', path.sep) || path.join('.', path.sep))) {
+				return relativePath;
+			} else {
+				// if the relative path does not contain ./ at the beginning, we need to add it so it's recognized as a link
+				return `.${path.join(path.sep, relativePath)}`;
 			}
 		}
-		return '';
 	}
+	// return empty for hyperlinks
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:526]: ooh that's right!  I'm not sure if it's a valid scenario, but I'll remove the comment to avoid any confusion

**Review by Charles-Gagnon — APPROVED** [review]
