### PR TITLE
Fixed the generate script logic for notebook wizards.

### LINKED ISSUE #13318: Generate Script button is always enabled for SQL MI and Postgres wizard
Repro:
1. Run ADS from the latest development code in the Main branch.
2. New Deployment ... -> Azure Sql managed Instance - Azure Arc -> Select
3. Check the terms of use -> Next
Actual: 'Script to notebook' is enabled (very often but sometimes it is not, which itself is weird) and it is possible to end the wizard even when all required fields have not been entered.
Expected: 'Script to notebook' is enabled only after the required fields are entered and they are valid.

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #13318 
Invalid state:
image
Valid state: 
image
Always enabled for summary page:
image

### CODE REVIEW

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts [hunk 1]
```diff
@@ -96,7 +96,12 @@ export class NotebookWizardPage extends ResourceTypePage {
 			this.wizard.wizardObject.generateScriptButton.hidden = true;
 		}
 
+		// by default the generate button is disabled and will wait for the page validation to be enabled.
```
Comment (ranasaria) [inline extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts:99]: All these matter only on last page because on all other pages generateScript button is hidden so you can move this logic within the pageInfo.isLastPage check above.

**Review by ranasaria — APPROVED** [review]
Looks good overall. So minor changes suggested would be good to take care of before merge.

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts [hunk 2]
```diff
@@ -96,7 +96,12 @@ export class NotebookWizardPage extends ResourceTypePage {
...
+		this.wizard.wizardObject.generateScriptButton.enabled = false;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts:100]: Did you verify that this works correctly when you first enter a page that had empty required fields? My observation was that we were running the validations as soon as the pages were created (when the wizard was first opened) and then only again if anything on the page changed - which if true would mean this would only be set to true once someone made changes on a non-summary page.

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts [hunk 3]
```diff
@@ -96,7 +96,12 @@ export class NotebookWizardPage extends ResourceTypePage {
...
+
 		if (this.pageInfo.isSummaryPage) {
+			//generate button is always enabled for summary page as there are no in page validations.
+			this.wizard.wizardObject.generateScriptButton.enabled = true;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts:104]: But the summary page shouldn't have any validation errors because of this and so why is this needed to be special? This seems to indicate to me that something isn't being done correctly here.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/resource-deployment/src/ui/resourceTypeWizard.ts [hunk 4]
```diff
@@ -147,10 +147,12 @@ export class ResourceTypeWizard {
 		pages.unshift(new ToolsAndEulaPage(this));
 		this.wizardObject!.pages = pages.map(p => p.pageObject);
 		this.pages = pages;
-		this.pages.forEach((page) => {
+		this.pages.forEach((page, idx) => {
 			page.pageObject.onValidityChanged((isValid: boolean) => {
-				// generateScriptButton is enabled only when the page is valid.
-				this.wizardObject.generateScriptButton.enabled = isValid;
+				if (idx === pages.length - 1) {
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/resourceTypeWizard.ts:152]: This is assuming that the last page is the only one showing the generate scripts - which may not necessarily be true in the future.

Why isn't each page just setting the button status when it's navigated to based on the current state of its validation?

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/resourceTypeWizard.ts:152]: The enabled state of generateScriptButton should just be tied to the validity of the page. The hidden state is used to toggle whether generateScript button is visible or not. Only for NotebookWizards currently, we want the generateScript button to be visible on the last change. In the future, each pageInfo object in the JSON could expose a flag to display generateScriptButton on that page.

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts [hunk 5]
```diff
@@ -100,6 +100,8 @@ export class NotebookWizardPage extends ResourceTypePage {
 			await setModelValues(this._model.inputComponents, this.wizard.model);
 		}
 
+		this.wizard.wizardObject.generateScriptButton.enabled = this.pageObject.valid;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts:103]: I'd suggest moving this up to the `if (pageInfo.isLastPage) {` block - in the else for that we hide this button anyways and it'd be nice to keep all the button logic in one place.

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts (hunk 5 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizardPage.ts:103]: @Charles-Gagnon - as I mentioned earlier, hidden or not is a function of being on the last page or not while enablement is a function of page validity irrespective of the page we are on. So, the current code captures these semantics well. @aasimkhan30 - Kindly add a comment in the code that clearly spell out the above semantics so we maintain it going forward.

**Review by ranasaria — APPROVED** [review]
Looks good. Kindly add comments to spell out the hiding/enablement semantics fo generateScript button so that it is easy to maintain this going forward.
