### PR TITLE
Fix for issue where bulk-adding scripts could perform a rescan after each script

### LINKED ISSUE #22663: Bulk-adding objects to SQL project rescans after each item
Request from migration team for oracle migraiton GA.  Should be a simple fix

### PR DESCRIPTION
**Pull request by Benjin**
Fixes #22663

### CODE REVIEW

**Comment by kisantia** [comment]
also please update the extension version to 1.0.1 in the package.json

File: extensions/sql-database-projects/src/models/project.ts [hunk 1]
```diff
@@ -117,6 +117,10 @@ export class Project implements ISqlProject {
 		return this._sqlProjStyle;
 	}
 
+	public get sqlProjStyleName(): string {
```
Comment (Benjin) [inline extensions/sql-database-projects/src/models/project.ts:120]: I don't love this, but given the confusion around typing file references for the migration extension earlier, I didn't want to add an mssql-vscode or mssql dependency now.  I'd like for this to be able to be replaced by the enum with the reintroduction of vscode support.

**Review by kisantia — APPROVED** [review]

**Review by SakshiS-harma — APPROVED** [review]
