### PR TITLE
Fix sql projects not using OutputPath in sqlproj for publishing

### LINKED ISSUE #19918: Publish always tries to find dacpac in .\bin\debug\
Issue Type: <b>Bug</b>

right-click and publish a database. It will build but fail to deploy it if the <OutputPath> tag is anything other than .\bin\debug\

In Azure Data Studio it fails without error messages.
In VS Code is where you see the precise issue with the wrong path for the dacpac for deployment 

Extension version: 0.17.1
Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #19918. The sql database projects extension would always look for the dacpac at the default location of .\bin\Debug when publishing, but there's an OutputPath property that can be specified in a .sqlproj, so the dacpac will be created at that location if it's provided.

### CODE REVIEW

**Review by zijchen — COMMENTED** [review]
If user sets `<Configuration>Release</Configuration>`, it would build to `./bin/Release`. Do we also have logic to handle that?

**Comment by kisantia** [comment]
> If user sets `<Configuration>Release</Configuration>`, it would build to `./bin/Release`. Do we also have logic to handle that?

Nope - good catch, I'll add it! 

I tried specifying `<Configuration>Release</Configuration>` in an SDK style project, but the dacpac still got built in `./bin/Debug`. For the legacy style project, it got built in `./bin/Release` as expected when this was added. Is this a bug for SDK-style projects?

File: extensions/sql-database-projects/src/models/project.ts [hunk 1]
```diff
@@ -155,6 +160,15 @@ export class Project implements ISqlProject {
 			this.projFileXmlDoc!.documentElement.getElementsByTagName(constants.PropertyGroup)[0]?.appendChild(newProjectGuidNode);
 			await this.serializeToProjFile(this.projFileXmlDoc);
 		}
+
+		// get output path
+		try {
+			const outputPath = this.projFileXmlDoc!.documentElement.getElementsByTagName(constants.OutputPath)[0].childNodes[0].nodeValue!;
+			this._outputPath = path.join(utils.getPlatformSafeFileEntryPath(this.projectFolderPath), utils.getPlatformSafeFileEntryPath(outputPath));
+		} catch (e) {
+			// If output path isn't specified in .sqlproj, set it to the default output path .\bin\Debug\
```
Comment (llali) [inline extensions/sql-database-projects/src/models/project.ts:169]: can we check the path fist and set to default instead of catching an exception?

**Review by llali — APPROVED** [review]

File: extensions/sql-database-projects/src/common/constants.ts [hunk 2]
```diff
@@ -493,6 +494,8 @@ export const RoundTripSqlDbNotPresentCondition = '\'$(NetCoreBuild)\' != \'true\
 export const DacpacRootPath = '$(DacPacRootPath)';
 export const ProjJsonToClean = '$(BaseIntermediateOutputPath)\\project.assets.json';
 
+export const defaultOutputPath = '.\\bin\\Debug\\';
```
Comment (Benjin) [inline extensions/sql-database-projects/src/common/constants.ts:497]: should this be a non-const that's constructed with `path.join()` to make sure the slashes work on all plats?

**Review by Benjin — APPROVED** [review]

File: extensions/sql-database-projects/src/models/project.ts (hunk 1 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/models/project.ts:170]: updated to be an if else checking if any OutputPath nodes were found

File: extensions/sql-database-projects/src/common/constants.ts (hunk 2 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/common/constants.ts]: Updated to use `path.join()`. It was getting converted with `utils.getPlatformSafeFileEntryPath()` in project.ts, so it was working on mac, but good to update it in case it's used somewhere else in the future so it doesn't get missed.

**Comment by kisantia** [comment]
> Changes here look good. I think you can address the configuration issue in a separate PR if you like. I'm not sure how common of a scenario that is anyway.

opened #20027 to track adding support for this later
