### PR TITLE
Fix endpoint links to not overflow text

### LINKED ISSUE #7307: BDC Dashboard : Long Service Endpoint URLs aren't displayed correctly
MicrosoftTeams-image

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7307

After (note - dummy values used, these aren't the actual URLs we get back from the controller) : 

image

image

### CODE REVIEW

File: extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts [hunk 1]
```diff
@@ -244,11 +244,11 @@ function createServiceEndpointRow(modelBuilder: azdata.ModelBuilder, container:
 		const endpointCell = modelBuilder.hyperlink()
 			.withProperties({ label: endpoint.endpoint, url: endpoint.endpoint, CSSStyles: { 'height': '15px' } })
 			.component();
-		endPointRow.addItem(endpointCell, { CSSStyles: { 'width': `${serviceEndpointRowEndpointCellWidth}px`, 'min-width': `${serviceEndpointRowEndpointCellWidth}px`, 'overflow': 'hidden', ...cssStyles.hyperlink } });
+		endPointRow.addItem(endpointCell, { CSSStyles: { 'width': `${serviceEndpointRowEndpointCellWidth}px`, 'min-width': `${serviceEndpointRowEndpointCellWidth}px`, 'overflow': 'hidden', 'text-overflow': 'ellipsis', ...cssStyles.hyperlink } });
```
Comment (chlafreniere) [inline extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts]: something to think about: can we move these properties into .css files?

Comment (Charles-Gagnon) [reply extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts]: Yeah that's on my backlog of features to add - since as far as I'm aware there isn't a way for an extension to contribute style sheets at this time.

File: extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts [hunk 2]
```diff
@@ -263,13 +263,13 @@ function createServiceEndpointRow(modelBuilder: azdata.ModelBuilder, container:
 				azdata.connection.openConnectionDialog(undefined, connProfile);
 			}
 		});
-		endPointRow.addItem(endpointCell, { CSSStyles: { 'width': `${serviceEndpointRowEndpointCellWidth}px`, 'min-width': `${serviceEndpointRowEndpointCellWidth}px`, 'overflow': 'hidden' } });
+		endPointRow.addItem(endpointCell, { CSSStyles: { 'width': `${serviceEndpointRowEndpointCellWidth}px`, 'min-width': `${serviceEndpointRowEndpointCellWidth}px` } });
 	}
 	else {
 		const endpointCell = modelBuilder.text()
-			.withProperties({ value: endpoint.endpoint, CSSStyles: { ...cssStyles.text } })
+			.withProperties({ value: endpoint.endpoint, CSSStyles: { 'overflow': 'hidden', 'text-overflow': 'ellipsis', ...cssStyles.text } })
```
Comment (qifahs) [inline extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardOverviewPage.ts]: Whenever we truncate and show ellipsis, it would be good to show tooltip on hover, which shows the entire string (or atleast most of it).

**Comment by Charles-Gagnon** [comment]
@qifahs I added the tooltips - here's what it looks like (although I need to sync up with @alanrenmsft since he was also adding tooltips to the text component but was doing it very differently)

screen

**Comment by Charles-Gagnon** [comment]
@alanrenmsft I merged in your changes. Could you look and make things seem OK from your end? I tested your deployment dialog and things seemed to work fine.

File: extensions/mssql/src/dashboard/serviceEndpoints.ts [hunk 3]
```diff
@@ -60,16 +60,28 @@ export function registerServiceEndpoints(context: vscode.ExtensionContext): void
...
 				if (hyperlinkedEndpoints.findIndex(e => e === endpointInfo.serviceName) >= 0) {
-					const linkCell = view.modelBuilder.hyperlink().withProperties<azdata.HyperlinkComponentProperties>({ label: endpointInfo.endpoint, url: endpointInfo.endpoint }).component();
-					endPointRow.addItem(linkCell, { CSSStyles: { 'width': '62%', 'color': '#0078d4', 'text-decoration': 'underline', 'padding-top': '10px' } });
+					const linkCell = view.modelBuilder.hyperlink()
+						.withProperties<azdata.HyperlinkComponentProperties>({
+							label: endpointInfo.endpoint,
+							title: endpointInfo.endpoint,
+							url: endpointInfo.endpoint
+						}).component();
+					endPointRow.addItem(linkCell, { CSSStyles: { 'width': '62%', 'color': '#0078d4', 'text-decoration': 'underline', 'padding-top': '10px', 'overflow': 'hidden', 'text-overflow': 'ellipsis' } });
```
Comment (alanrenmsft) [inline extensions/mssql/src/dashboard/serviceEndpoints.ts]: is this color good for both light and dark themes?

Comment (alanrenmsft) [reply extensions/mssql/src/dashboard/serviceEndpoints.ts]: it seems this color will not pass the contrast ratio requirement for accessibility, I would do the styling in the component code, so that other features can benefit from it. It will be nice if we could find a color that works for both theme, otherwise, you have the ability of having theme-aware css in core.

Comment (Charles-Gagnon) [reply extensions/mssql/src/dashboard/serviceEndpoints.ts]: No, but that's something I'm going to be addressing in later updates when we get our accessibility review finished.

Comment (alanrenmsft) [reply extensions/mssql/src/dashboard/serviceEndpoints.ts]: sounds good
