### PR TITLE
Fix search results display

### LINKED ISSUE #14259: Search results are confusing when pinned Notebook's book is opened in Book Tree View
Having the book of a pinned notebook opened in the Books View will divide the results in two nodes (the directory of the pinned notebook and the book's root)
Screen Shot 2021-02-11 at 10 38 47 AM

- Azure Data Studio Version:
Version: 1.26.0-rc1
Commit: 06bace1fcf7ec79b3f2df8588400f56b54476125
Date: 2021-02-08T08:33:58.217Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:
1.Open a book and pin a notebook from the same book.
2. Search for a term that appears in multiple sections of the book as well the newly pinned notebook.
3. The search results will be divided in two nodes.

### PR DESCRIPTION
**Pull request by barbaravaldez**
Previously, we used to identify the root of a tree item with the resourceUri but since we were sending always the root of the book instead of the actual path of a notebook it would cause the following issue: https://github.com/microsoft/azuredatastudio/issues/13688.

In order to fix how the results were display, I keep track of the opened books in the Provided Book Tree View and the actual Book Tree View. For this reason, I iterate over the Pinned Books View last.
The `folder.includePattern` is `undefined` for the new version of Jupyter Books, it's `content/**` for the legacy version of Books and it is the name of a` file + extension `for individual notebooks (either pinned or standalone notebooks in the Books View).
I added this check to identify which queries were books and check if the tree item (saved notebook or pinned notebook) belongs to a book that has been added to the query before. If they haven't been added, then I proceed to add it to the query.

This PR addresses  #14259

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts [hunk 1]
```diff
@@ -260,40 +259,46 @@ export class NotebookExplorerViewPaneContainer extends ViewPaneContainer {
...
-									let baseName = path.join('**', path.basename(pathToNotebook));
+									const rootFolder = URI.file(path.dirname(root.resourceUri.path));
+									const baseName = path.join('**', path.basename(root.resourceUri.path)).replace(/\\/g, '/');
+									let isOpenedInBooksView = false;
 									pattern[baseName] = true;
-									let folderToSearch = { folder: rootFolder, includePattern: pattern };
-									query.folderQueries.push(folderToSearch);
-									filesToIncludeFiltered = filesToIncludeFiltered + rootFolder + ',';
+									query.folderQueries.forEach((folder) => {
+										//check for books
```
Comment (VasuBhog) [inline src/sql/workbench/contrib/notebook/browser/notebookExplorer/notebookExplorerViewlet.ts:290]: Small nit, usually has space after // and then the comment. 
This and the "//verify..."

**Review by VasuBhog — APPROVED** [review]

**Review by MaddyDev — APPROVED** [review]
