### PR TITLE
Fix task flicker

### LINKED ISSUE #5490: Flickering in task details in Task View
Azure Data Studio Version:
Daily Insiders build

Steps to Reproduce:

1. Add a number of tasks in the tasks view so that task view needs scrolling to see all issues (that the key to see this issue).
2. Scroll up down and you see a flickering as below in task related information (it is intermittent but relatively higher repro rate)

tasks

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes #5490

### CODE REVIEW

File: src/sql/workbench/parts/tasks/browser/tasksRenderer.ts [hunk 1]
```diff
@@ -36,15 +39,15 @@ export class TaskHistoryRenderer implements IRenderer {
...
 		return TaskHistoryRenderer.TASKOBJECT_HEIGHT;
 	}
 
 	/**
 	 * Returns a template ID for a given element.
 	 */
-	public getTemplateId(tree: ITree, element: any): string {
-		return TaskHistoryRenderer.TASKOBJECT_TEMPLATE_ID;
+	public getTemplateId(tree: ITree, element: TaskNode): string {
+		return element.id;
```
Comment (anthonydresser) [inline src/sql/workbench/parts/tasks/browser/tasksRenderer.ts]: This is unfortunately an inefficiency, but is required based on what we are trying to accomplish and how vscode's tree works.

File: src/sql/workbench/parts/tasks/browser/tasksRenderer.ts [hunk 2]
```diff
@@ -108,15 +112,15 @@ export class TaskHistoryRenderer implements IRenderer {
...
 
-			this.timer(element, templateData);
-			let self = this;
-			setInterval(function () {
-				self.timer(element, templateData);
-			}, 1000);
+			this.timer(element, templateData.time);
+
+			const timer = new IntervalTimer();
+			timer.cancelAndSet(() => this.timer(element, templateData.time), 500);
```
Comment (kburtram) [inline src/sql/workbench/parts/tasks/browser/tasksRenderer.ts]: it looks like the timer is now `500` instead of `1000`.  Any reason for this (I would expect increasing update frequency to increase flicker)?

Comment (anthonydresser) [reply src/sql/workbench/parts/tasks/browser/tasksRenderer.ts]: The change was arbitrary. I just rewrote this section and set it to w/e looked good to me but I can revert to 1000
