### PR TITLE
Fix for PG parameters table disappearing when trying to reset a value

### LINKED ISSUE #15250: Postgres trying to reset parameter to default causes table to disappear.
When trying to reset single parameter on table, the table disappears. Can reappear after refreshing entire model but is a new issue. 

- Azure Data Studio Version:1.29.0-insider (user setup)
-arc extension: https://sqltools.blob.core.windows.net/arc/arc-0.9.3.vsix 

resetind

Steps to Reproduce:

1. Manage postgres instance
2. Connect to server group to show parameter values
3. Press reset button found last column of table to reset a parameter value.

### PR DESCRIPTION
**Pull request by nasc17**
This PR is meant to address the issue of the parameters table disappearing after trying to reset a value. 

1.  Instead of repopulating the table every refresh, only values that have been changed get updated within the components
2. Took out calling refresh postgres model after every azdata call since the parameter updates does not depend on the show command
3. Add promise to make sure calling engine settings only happens once at a time. 

This PR fixes #15250

### CODE REVIEW

File: extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts [hunk 1]
```diff
@@ -607,14 +612,31 @@ export abstract class PostgresParametersPage extends DashboardPage {
 		});
 	}
 
+	private refreshParametersTable(): void {
+		this.engineSettings.map(parameter => {
+			let param = this._parameters.find(p => p.parameterName === parameter.parameterName);
```
Comment (bergeron) [inline extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:617]: Should probably null check `param` in case it wasn't found in `_parameters` and is undefined.

File: extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts [hunk 2]
```diff
@@ -607,14 +612,31 @@ export abstract class PostgresParametersPage extends DashboardPage {
 		});
 	}
 
+	private refreshParametersTable(): void {
```
Comment (bergeron) [inline extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:615]: I'd add a comment somewhere that this only updates existing values, and won't add new parameters to the table if they don't already exist.

**Review by bergeron — APPROVED** [review]

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
Did you find out what the specific issue was? Do you think there's some problem in core that might be causing this with what you had before?

Also you currently have a failing test it looks like.

**Comment by nasc17** [comment]
> Did you find out what the specific issue was? Do you think there's some problem in core that might be causing this with what you had before?
> 
> Also you currently have a failing test it looks like.

I was not able to see where the problem was coming from. When the debugger was attached the page would function as expected with no issues. I decided to just look into how I could clean up the refreshing process.

File: extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts [hunk 3]
```diff
@@ -612,20 +608,24 @@ export abstract class PostgresParametersPage extends DashboardPage {
 		});
 	}
 
-	private refreshParametersTable(): void {
+	private refreshParametersTableValues(): void {
+		//Checks if exisiting parameter values needs to be updated.
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:612]: Would suggest putting this as an XML doc comment

**Review by Charles-Gagnon — APPROVED** [review]
