### PR TITLE
fix error message steal focus issue

### LINKED ISSUE #22777: User dialog validation logic steals focus while trying to correct warnings
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open Create User dialog
2. Change to Contained user with SQL Login auth
3. Click Script button with empty passwords
4. Try to fix the passwords by typing two new values in text boxes

Expected: The warning can be corrected.

Actual: After each character is typed into password text box focus is stolen and moved to the warning on dialog.  This makes it very difficult to correct the errors.

image

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #22777

introduced in https://github.com/microsoft/azuredatastudio/pull/22743.
the fix is to only reset the focus if the message area was previously not visible.

### CODE REVIEW

File: src/sql/workbench/browser/modal/modal.ts [hunk 1]
```diff
@@ -612,8 +612,11 @@ export abstract class Modal extends Disposable implements IThemable {
 	protected set messagesElementVisible(visible: boolean) {
 		if (visible) {
 			if (this._useDefaultMessageBoxLocation) {
-				DOM.prepend(this._modalContent!, this._messageElement!);
-				this.setInitialFocusedElement();
+				// only do the append when the messageElement doesn't have parent element.
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modal/modal.ts:615]: It would be better to explain WHY we only want to do it then (the code itself already tells us that it's doing this)

**Review by kburtram — APPROVED** [review]
