### PR TITLE
Fix #3778 intellisense is delayed

### LINKED ISSUE #3778: Intellisense delayed
gif

- Azure Data Studio Version: 1.3.9

Steps to Reproduce:

1. Download latest version of Azure Data Studio (1.3.9)
2. Connect to localhost SQL Server 2017
3. Open New Query Window
4. Type S
5. Intellisense has a clear delay

I have tried a fresh install and restarting computer, and refreshing intellisense cache. Computer is 16gb and 4 cores.

### PR DESCRIPTION
**Pull request by kevcunnane**
- Jupyter completion item support was awaiting info before responding. Fix is to check if this is even a notebook cell first, then only await stuff if that's true

### CODE REVIEW

File: extensions/notebook/src/intellisense/completionItemProvider.ts [hunk 1]
```diff
@@ -11,22 +11,30 @@ import * as vscode from 'vscode';
 import { charCountToJsCountDiff, jsIndexToCharIndex } from './text';
 import { JupyterNotebookProvider } from '../jupyter/jupyterNotebookProvider';
 import { JupyterSessionManager } from '../jupyter/jupyterSessionManager';
-import { Deferred } from '../common/promise';
 
-const timeoutMilliseconds = 4000;
+const timeoutMilliseconds = 3000;
```
Comment (rajmusuku) [inline extensions/notebook/src/intellisense/completionItemProvider.ts]: Any specific reason form 4 to 3 seconds ?

File: extensions/notebook/src/intellisense/completionItemProvider.ts [hunk 2]
```diff
@@ -197,4 +194,5 @@ export interface INewIntellisenseInfo {
 	editorUri: string;
 	cell: nb.NotebookCell;
 	notebook: nb.NotebookDocument;
+	kernel?: nb.IKernel;
```
Comment (rajmusuku) [inline extensions/notebook/src/intellisense/completionItemProvider.ts]: Do we need this to be nullable ?

Comment (kevcunnane) [reply extensions/notebook/src/intellisense/completionItemProvider.ts]: Yes, because I define the overall info object without it and set it later

File: extensions/notebook/src/intellisense/completionItemProvider.ts (hunk 1 above)
Comment (kevcunnane) [reply extensions/notebook/src/intellisense/completionItemProvider.ts]: turns out 4 seconds is an eternity so bringing it down to improve perf in case where kernel intellisense times out. Should think about 2 seconds or less, but for remote calls this can be slow.
