### PR TITLE
layout the child component

### LINKED ISSUE #16693: LoadingComponent content is collapsed after loading
- Azure Data Studio Version: 1.32.0-insider (user setup)
- Commit: 309e558727225bde9e577f8f566e68f8b657ae45
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Modify `/samples/sqlservice/src/controller/mainController.ts` on line 152 replace `formWrapper.loading = false;` with `setTimeout(() => { formWrapper.loading = false; }, 5000);`, which essentially delays the loading completion and therefore rendering of the children components to after the model initialization is done.
2. Build the `sqlservice` sample extension and install it in ADS
3. In ADS run the `sqlservice.openDialog` command from command palette and navigate to the third tab `Test tab 3`
4. Wait for the loading to finish (~5 seconds)

**Expected result:**

image

**Actual result:**

image
(you can see tiny vertical scroll bar on the right, which is the height of the tree control)

*Disclaimer:* I don't know if it's just the tree control that acts this way or all of them. Technically it is wrapped in a form, so I'd assume form should provide some consistency as to how it is rendered with or without loading component around it.

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #16693

when doing layout for the loading component we also need to invoke the layout method for the child component to make sure it is sized properly.

### CODE REVIEW

File: src/sql/workbench/browser/modelComponents/loadingComponent.component.ts [hunk 1]
```diff
@@ -67,10 +67,18 @@ export default class LoadingComponent extends ComponentBase<azdata.LoadingCompon
...
+			const childComponent = this.modelStore.getComponent(this._component.id);
+			childComponent?.layout();
+		}
+	}
+
 	public override setProperties(properties: { [key: string]: any; }): void {
 		const wasLoading = this.loading;
 		super.setProperties(properties);
-		if (wasLoading && !this.loading) {
+		if (wasLoading !== this.loading) {
```
Comment (alanrenmsft) [inline src/sql/workbench/browser/modelComponents/loadingComponent.component.ts:81]: this was introduced in https://github.com/microsoft/azuredatastudio/pull/9088/files#diff-8effc957b1a67811f03a7c6e348c947d2ae372eb933d92a0a41ff9bc9054803fR69, and while working on this issue, I realized we have an issue here, it will only announce the loading completed event and miss the loading event. so fixing it to check for changes of the loading state.

**Review by Charles-Gagnon — APPROVED** [review]
