### PR TITLE
Fix #6771: Dacfx wizard summary page has wrong page number

### LINKED ISSUE #6771: DacFx: Summary labeled as Step 4 instead of Step 3 when deploying to a new database
Issue Type: <b>Bug</b>

When deploying a dacpac to a new database, the numbered progress bar on the left indicates that the Summary is Step 3, but it is labeled at the top as Step 4. See screenshot below.

image

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.17763

Steps to Reproduce:
1. Open Dacfx wizard and select Deploy Dacpac
2. Select a dacpac file and set the Target Database to a New Database
3. Click 'Next'
4. Summary is labeled as Step 4 when it should be Step 3

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by kisantia**
Fixes #6771. The summary page had the wrong page number for deploy to new database. This fixes that by removing both the summary and deploy plan pages, then adding the summary page back so that it will have the correct page number.

image

### CODE REVIEW

File: extensions/dacpac/src/wizard/pages/deployConfigPage.ts [hunk 1]
```diff
@@ -135,8 +136,11 @@ export class DeployConfigPage extends DacFxConfigPage {
 			this.model.database = this.databaseTextBox.value;
 			this.instance.setDoneButton(Operation.deploy);
 
-			// remove deploy plan page
+			// remove deploy plan page and readd summary page so that it has the correct page number
+			this.instance.wizard.removePage(DeployOperationPath.summary);
```
Comment (udeeshagautam) [inline extensions/dacpac/src/wizard/pages/deployConfigPage.ts]: noticed that in upgradeRadioButton.onDidClick we are adding only the deployplan page... do we add only the very next page? Iso... may be we should check if summary page is added or not before removing?

Comment (kisantia) [reply extensions/dacpac/src/wizard/pages/deployConfigPage.ts]: ah good catch! That summary page also has to be removed and re-added there to have the correct page number

File: extensions/dacpac/src/wizard/pages/deployConfigPage.ts [hunk 2]
```diff
@@ -123,9 +124,12 @@ export class DeployConfigPage extends DacFxConfigPage {
 			this.formBuilder.addFormItem(this.databaseDropdownComponent, { horizontal: true, componentWidth: 400 });
 			this.model.database = (<azdata.CategoryValue>this.databaseDropdown.value).name;
 
-			// add deploy plan page
+			// add deploy plan page and remove and re-add summary page so that it has the correct page number
+			this.instance.wizard.removePage(DeployNewOperationPath.summary);
 			let deployPlanPage = this.instance.pages.get('deployPlan');
+			let summaryPage = this.instance.pages.get('summary');
```
Comment (alanrenmsft) [inline extensions/dacpac/src/wizard/pages/deployConfigPage.ts]: can we create an enum for the pages?
