### PR TITLE
Fixing URI openings for execution plans 

### LINKED ISSUE #20902: Opening ADS from URL with a sqlplan file does not render graphical query plan
- Azure Data Studio Version: 1.39.1
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. With ADS installed on a machine, enter the following URL in a browser location bar: `azuredatastudio://file/path\to\file\untitled-1.sqlplan` and hit Enter. Here, `untitled-1.sqlplan` contains query plan XML retrieved from Query Store.
2. After a couple of prompts, ADS will open and display the XML contents of the file, instead of rendering graphical query plan.
3. Opening the same file directly in ADS via File->Open File renders it correctly as a graphical query plan.

Does this issue occur when all extensions are disabled?: Unclear. Unable to launch ADS from URL with extensions disabled.

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #20902 

This PR registers execution plan editor early in the workbench lifecycle. That will  make it available for the URI based file to use when ADS starts.

### CODE REVIEW

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 1]
```diff
@@ -27,19 +28,37 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
+	private async ensureCapabilitiesRegistered(providerId?: string): Promise<void> {
+		let providers: string[] = [];
+		// Wait until the capabilities service has registered some providers.
+		await new Promise<void>(resolve => {
+			let retryCount = 0;
+			const intervalId = setInterval(() => {
+				while (retryCount < 5) {
+					providers = Object.keys(this._capabilitiesService.providers);
+					if (providers) {
+						if (providerId && providers[providerId]) {
```
Comment (lewis-sanchez) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:44]: You can probably simplify this to: `if ((providerId && providers[providerId]) || providers)`

Comment (lewis-sanchez) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts:44]: Actually you can do that in the if that checks providers and remove a level of conditional nesting.

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 2]
```diff
@@ -27,19 +28,37 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests.
+	 * @param providerId Optional provider id to wait for.
+	 */
+	private async ensureCapabilitiesRegistered(providerId?: string): Promise<void> {
+		let providers: string[] = [];
+		// Wait until the capabilities service has registered some providers.
+		await new Promise<void>(resolve => {
+			let retryCount = 0;
+			const intervalId = setInterval(() => {
```
[the remark this answers is not in the document]
Comment (aasimkhan30) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts:40]: There was a race condition because sometimes the providers were registered before this file was able to resgiter onCapabilitiesRegistered handler. This code fixes that.

[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts:40]: Then couldn't you just check to see if the provider is registered already and resolve immediately, otherwise set up the promise so it waits for it to resolve?

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts (hunk 1 above)
Comment (aasimkhan30) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts]: that's not correct as it will resolve for condition when providerID is not found in providers but providers is not undefined.

Comment (aasimkhan30) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts]: I have cleaned up the condition now.

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (alanrenmsft) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts:47]: I agree with Charles, this can be simplified. also looks like you are simply returning after retrying for 5 times, are we not supposed to reject the promise with some error message?

[the remark this answers is not in the document]
Comment (aasimkhan30) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts:47]: Those errors are already handled later @alanrenmsft

[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts:46]: Why are you retrying anyways? We get notified when a provider is registered. It'd be better to just have a single timeout in case it never gets registered.

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 3]
```diff
@@ -27,19 +28,43 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
-			});
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests.
+	 * @param providerId Optional provider id to wait for.
+	 */
+	private async ensureCapabilitiesRegistered(providerId?: string): Promise<void> {
+		let providers: string[] = Object.keys(this._capabilitiesService.providers);
+
+		// If the provider is already registered, return.
+		if (providerId && providers?.includes(providerId) || (!providerId && providers?.length > 0)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:39]: Is a falsy providerId even valid? Are there cases where we're passing in an empty string or something?

Comment (aasimkhan30) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts]: There are 2 cases for using execution plans.
1. Getting execution plan when we run queries. In this case we already have the provider id.
1. When we a open a file that is registered to be handled by execution plan editor. In this case, we do not know which provider within the execution plan service will be able to handle that file.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts]: But surely the service can figure that out? Otherwise how do you know which provider to send it to?

Comment (aasimkhan30) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts]: The service can figure out only after the providers are registered. As during registration, they will provide the file types they support.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts]: So shouldn't it be : 

1. Check if a provider is registered that can handle it
2. If not then set up promise with event on capabilities registered to watch for provider being registered
3. For every provider registered see if it can handle the EP. If it can then complete the promise, if not then ignore
4. After certain timeout (15-30sec?) reject with "No provider registered" error

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 4]
```diff
@@ -27,9 +27,14 @@ export class ExecutionPlanService implements IExecutionPlanService {
 		this._providerRegisterEvent = this._onProviderRegister.event;
 	}
 
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests.
+	 */
 	private async ensureCapabilitiesRegistered(): Promise<void> {
+
+		// Wait until the capabilities service has registered some providers.
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:35]: But what if the provider that can handle the EP isn't registered yet?

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts (hunk 3 above)
Comment (aasimkhan30) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts]: I agree. I had changed the code because I misunderstood how capabilities providers worked and the if statement I was using in the code was wrong. The provider keys will never be null. Instead it will be an empty array. Now I waiting for the right provider to be registered.

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 5]
```diff
@@ -27,19 +27,46 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
-		let providers = Object.keys(this._capabilitiesService.providers);
-		if (!providers) {
-			await new Promise<void>(resolve => {
-				this._capabilitiesService.onCapabilitiesRegistered(e => {
-					resolve();
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests.
+	 */
+	private async ensureCapabilitiesRegistered(providerId?: string): Promise<void> {
+		if (!providerId) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:34]: So this case still confuses me - are we just going to blindly pick the first provider that's registered and hope that it can handle it? Shouldn't we still be looking for a provider that's able to handle the file with the extension of the plan?

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 6]
```diff
@@ -27,19 +27,46 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
-	private async ensureCapabilitiesRegistered(): Promise<void> {
-		let providers = Object.keys(this._capabilitiesService.providers);
-		if (!providers) {
-			await new Promise<void>(resolve => {
-				this._capabilitiesService.onCapabilitiesRegistered(e => {
-					resolve();
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests.
+	 */
+	private async ensureCapabilitiesRegistered(providerId?: string): Promise<void> {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:33]: This shouldn't be optional - you're always passing in a providerId (or if you aren't then you need to fix up the parameter in getExecutionPlanProvider)

```suggestion
	private async ensureCapabilitiesRegistered(providerId: string): Promise<void> {
```

**Comment by aasimkhan30** [comment]
I have separated the functions and rectified the logic:

If a file format is present, I will check if any registered provider can manage it. If not, I will wait for 30 seconds to check if a future registered provider can handle it.
If we already have the provider ID, I will verify if any registered provider matches that ID. If not, I will wait for 30 seconds to see if a future registered provider will have the ID.

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 7]
```diff
@@ -27,19 +27,49 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
 	}
 
-	private async ensureCapabilitiesRegistered(): Promise<void> {
-		let providers = Object.keys(this._capabilitiesService.providers);
-		if (!providers) {
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests for the given file format.
+	 * @param fileFormat Execution plan file format
+	 */
+	public async ensureFileFormatHandlerRegistered(fileFormat: string) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:34]:
```suggestion
	public async ensureFileFormatHandlerRegistered(fileFormat: string): Promise<void> {
```

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 8]
```diff
@@ -27,19 +27,49 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
+				setTimeout(() => {
+					throw new Error(localize('executionPlanService.ensureCapabilitiesRegistered', "Provider with id {0} is not registered.", providerId));
+				}, 30000);
 			});
 		}
 	}
 
 	private async getExecutionPlanProvider(providerId: string): Promise<azdata.executionPlan.ExecutionPlanProvider> {
-		await this.ensureCapabilitiesRegistered();
+		await this.ensureCapabilitiesRegistered(providerId);
```
[the remark this answers is not in the document]
Comment (aasimkhan30) [reply src/sql/workbench/services/executionPlan/common/executionPlanService.ts:72]: The errors are handled and an infobox gets shown.
Example error thrown from the method.
image

**Review by alanrenmsft — APPROVED** [review]

**Review by lewis-sanchez — APPROVED** [review]

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 9]
```diff
@@ -27,25 +27,49 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
+	 * @param fileExtension Execution plan file format
+	 */
+	public async ensureFileExtensionHandlerRegistered(fileExtension: string) {
+		for (let provider in Object.keys(this._capabilitiesService.providers)) {
+			if (this._capabilitiesService.providers[provider].connection.supportedExecutionPlanFileExtensions?.includes(fileExtension)) {
+				return;
+			}
+		}
+		await (new Promise<void>((resolve, reject) => {
+			this._capabilitiesService.onCapabilitiesRegistered(e => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:41]: You should be cleaning this up by saving the disposable and then disposing it before you resolve/reject

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 10]
```diff
@@ -27,25 +27,49 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
-			await new Promise<void>(resolve => {
-				this._capabilitiesService.onCapabilitiesRegistered(e => {
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests for the given file format.
+	 * @param fileExtension Execution plan file format
+	 */
+	public async ensureFileExtensionHandlerRegistered(fileExtension: string) {
+		for (let provider in Object.keys(this._capabilitiesService.providers)) {
+			if (this._capabilitiesService.providers[provider].connection.supportedExecutionPlanFileExtensions?.includes(fileExtension)) {
+				return;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:37]:
```suggestion
				// We already have a provider registered that can handle this file extension so we're done
				return;
```

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 11]
```diff
@@ -27,25 +27,49 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
-		if (!provider || !provider.connection?.isExecutionPlanProvider) {
-			return undefined;
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests.
+	 */
+	private async ensureCapabilitiesRegistered(providerId: string): Promise<void> {
+		// Wait until the provider with the given id is registered.
+		if (!this._capabilitiesService.providers[providerId]) {
+			await (new Promise<void>((resolve, reject) => {
+				this._capabilitiesService.onCapabilitiesRegistered(e => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:59]: Same here, save the disposable and dispose it before resolve/reject.

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 12]
```diff
@@ -27,25 +27,49 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
+					if (e.id === providerId) {
+						resolve();
+					}
+				});
+				setTimeout(() => {
+					reject(new Error(localize('executionPlanService.ensureCapabilitiesRegistered', "Provider with id {0} was not registered after 30 seconds.", providerId)));
+				}, 30000);
+			}).catch(e => { throw e; }));
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:67]: Shouldn't need the catch/rethrow

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 13]
```diff
@@ -27,25 +27,49 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
-		let providers = Object.keys(this._capabilitiesService.providers);
-		if (!providers) {
-			await new Promise<void>(resolve => {
-				this._capabilitiesService.onCapabilitiesRegistered(e => {
+	/**
+	 * This ensures that the capabilities service has registered the providers to handle execution plan requests for the given file format.
+	 * @param fileExtension Execution plan file format
+	 */
+	public async ensureFileExtensionHandlerRegistered(fileExtension: string) {
+		for (let provider in Object.keys(this._capabilitiesService.providers)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:35]: nit: It would be good to clarify this as `providerId` - it's not the actual provider itself. (same below in _runAction)

**Review by Charles-Gagnon — APPROVED** [review]
