### PR TITLE
Fix #6477 controller login + fix dashboard layout

### LINKED ISSUE #6477: Big data cluster connection dialog broken
The SQL Server big data cluster controller was broken by an API change. We need to fix by adding in cluster name option and using new controller API.

### PR DESCRIPTION
**Pull request by kevcunnane**
- Service endpoints should be on own column, cut off smaller screen
- Controller login not working due to 404 error
This is due to a breaking API change
We have requested fixes to help mitigate need for cluster name,
but for now have a default value for this

Finally, modified code so it's easier to update swagger API
and also added instructions on how to update in future

**Dialog UI**
image

**Dashboard UI**
image

### CODE REVIEW

File: extensions/big-data-cluster/src/extension.ts [hunk 1]
```diff
@@ -83,3 +89,21 @@ function deleteControllerInternal(treeDataProvider: ControllerTreeDataProvider,
 		treeDataProvider.saveControllers();
 	}
 }
+
+
+
+/**
+ * Throttles actions to avoid bug where on clicking in tree, action gets called twice
```
Comment (kevcunnane) [inline extensions/big-data-cluster/src/extension.ts]: This is handling a recent bug since the last vscode merge. If we don't do this, we'll get a dialog shown behind the current one

**Comment by geleems** [comment]
Is `url` + `username` combination still enough information to specify a certain node when search and delete? Should we update the combination to `cluster name` + `url` + `username` to indicate a certain node? Other than this, all looks good to me.

**Comment by kevcunnane** [comment]
#6482, #6481, #6480 opened to address issues Gene raised & cover testing & UI improvements. Will address separately due to time constraints
