### PR TITLE
Fix #3439 Trusted doesn't get saved in Notebooks

### LINKED ISSUE #3439: Trusted doesn't get saved in Notebooks save functionality
image

Steps to Reproduce:

1. Open a notebook and add some content
2. Make it trusted and hit save button
3. Content is saved but still 'Not Trusted' is shown by default

### PR DESCRIPTION
**Pull request by kevcunnane**
The main fix is to add a memento to store trust information. This is only needed for saved files - untitled files are always trusted as the user created them.
On clicking trusted or saving a file, the trusted state is cached. In the future, we will also handle code execution here too by sending notification on snapshot state.
I found issue #5506 during testing - existing issue where we should track trusted state changing on run. In the case all cells are ran, the whole notebook should become trusted.

Finally, I did a decent amount of refactoring to move more logic to the model - removing unnecessary calls from components which duplicated model behavior, moving trust notification to the model or at least the notebook service completely.
This should aid in testability, so I'll look at some tests.

### CODE REVIEW

File: src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts [hunk 1]
```diff
@@ -399,7 +399,6 @@ export class MainThreadNotebookDocumentsAndEditors extends Disposable implements
 		const fileInput = isUntitled ? this._untitledEditorService.createOrGet(uri, notebookModeId, options.initialContent) :
 			this._editorService.createInput({ resource: uri, language: notebookModeId });
 		let input = this._instantiationService.createInstance(NotebookInput, path.basename(uri.fsPath), uri, fileInput);
-		input.isTrusted = isUntitled;
```
Comment (kevcunnane) [inline src/sql/workbench/api/node/mainThreadNotebookDocumentsAndEditors.ts]: isTrusted logic is all moved to the notebookserviceimpl.

File: src/sql/workbench/common/customInputConverter.ts [hunk 2]
```diff
@@ -57,11 +57,7 @@ export function convertEditorInput(input: EditorInput, options: IQueryEditorOpti
 		//Notebook
 		uri = getNotebookEditorUri(input, instantiationService);
 		if (uri) {
-			let fileName: string = 'untitled';
-			if (input) {
```
Comment (kevcunnane) [inline src/sql/workbench/common/customInputConverter.ts]: We're already inside an if(input) check so no need to do this conditional check. It has no value.

File: src/sql/workbench/parts/notebook/notebook.component.ts [hunk 3]
```diff
@@ -188,19 +188,6 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 		this._model.addCell(cellType);
 	}
 
-	// Updates Notebook model's trust details
-	public updateModelTrustDetails(isTrusted: boolean) {
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/notebook.component.ts]: Moved logic and notification to the model.
- Note that removing the `updateModel` call below and having logic to filter trusted state updates vs. other updates a) saves a text model serialization on trusted state changing, and b) does not force input to be dirty when trust is enabled. These are both good things

File: src/sql/workbench/services/notebook/common/notebookService.ts [hunk 4]
```diff
@@ -68,6 +68,25 @@ export interface INotebookService {
...
 
 	renameNotebookEditor(oldUri: URI, newUri: URI, currentEditor: INotebookEditor): void;
+
+	/**
+	 * Checks if a notebook has previously been marked as trusted, and that
+	 * the notebook has not changed on disk since that time. If the notebook
+	 * is currently dirty in the app, the previous trusted state will be used even
+	 * if it's altered on disk since the version in our UI is based on previously trusted
+	 * content.
+	 * @param notebookUri the URI identifying a notebook
```
Comment (chlafreniere) [inline src/sql/workbench/services/notebook/common/notebookService.ts]: I guess my main question is this... What's the behavior if you save a notebook, trust it, then with another notebook, save it as the same URI? It would then be trusted, right?

This may be a corner case, just wanted to call it out 😄

File: src/sql/workbench/services/notebook/common/notebookServiceImpl.ts [hunk 5]
```diff
@@ -484,4 +514,83 @@ export class NotebookService extends Disposable implements INotebookService {
...
+		if (!cacheInfo) {
+			// This notebook was never trusted
+			return false;
+		}
+		// This was trusted. If it's not dirty (e.g. if we're not working on our cached copy)
+		// then should verify it's not been modified on disk since that invalidates trust relationship
+		if (!isDirty) {
+			// Check mtime against mtime on disk
+			let actualMtime: number = await this.getModifiedTimeForFile(notebookUri);
+			if (actualMtime > cacheInfo.mtime) {
```
Comment (chlafreniere) [inline src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: Ah nice, this answers a question I previously had.

Comment (kevcunnane) [reply src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: What was the question?

**Comment by kevcunnane** [comment]
Added some tests at the model level. Created #5517 for notebook service tests as there's no framework yet for that part.
