### PR TITLE
Aasim/fix/sqldbtypos

### LINKED ISSUE #12955: Typos in SQL Database deployment flow
- Azure Data Studio Version: Insiders build

Steps to Reproduce:

1. Open Connection viewlet
2. Click "..." in Connection view
3. Click "New deployment"
4. Select "Azure SQL" tile

Issues in Azure SQL Database flow:

- Tile titled "SQL Database on Azure Server" should be titled "Azure SQL Database" and description should be "Create a SQL database, database server, or elastic pool in Azure."
- Button in bottom right should say "Select" when "Single database" is selected to match experience for other similar selections
- Sentence casing should be used:
      - Dropdown options should be sentence cased, i.e. "Single database", "Elastic pool", "Database server"
      - Wizard step 1 - title should be sentence cased - "Azure SQL Database - Azure account settings"
      - Wizard step 1 - "Azure Account" should be "Azure account"; "Sign In" should be "Sign in"
- Wizard step 2 - Firewall rule should be optional
- Wizard step 2 - Add a description somewhere (bottom of page?) saying "Create a firewall rule for your local client IP in order to connect to your database through Azure Data Studio after creation is completed."

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #12955 
When option is disabled
image
When option is enabled
image
Help text
image

### CODE REVIEW

File: extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/databaseSettingsPage.ts [hunk 1]
```diff
@@ -128,6 +135,31 @@ export class DatabaseSettingsPage extends BasePage {
...
+		}).component();
+
+		this._firewallToggleDropdown.onValueChanged((value) => {
+			let dropDownValue = (this._firewallToggleDropdown.value as azdata.CategoryValue).name;
+			let displayValue: 'block' | 'none' = dropDownValue === 'True' ? 'block' : 'none';
+			this.wizard.changeRowDisplay(this._firewallRuleNameTextRow, displayValue);
+			this.wizard.changeRowDisplay(this._endIpAddressTextRow, displayValue);
+			this.wizard.changeRowDisplay(this._startIpAddressTextRow, displayValue);
+			this.wizard.changeComponentDisplay(this._IpInfoText, displayValue);
+			this.wizard.model.newFirewallRule = dropDownValue;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/databaseSettingsPage.ts:159]: I'd suggest converting this to a boolean here instead - easier to work with for the stuff that uses the model value

File: extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/databaseSettingsPage.ts [hunk 2]
```diff
@@ -128,6 +135,31 @@ export class DatabaseSettingsPage extends BasePage {
 		this._endIpAddressTextRow = this.wizard.createFormRowComponent(view, constants.EndIpAddressLabel, '', this._endIpAddressTextbox, true);
 	}
 
+	private createFirewallToggle(view: azdata.ModelView) {
+		this._firewallToggleDropdown = view.modelBuilder.dropDown().withProps({
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/deployAzureSQLDBWizard/pages/databaseSettingsPage.ts:139]: Did you talk with the designers about using a dropdown for this? Seems like a checkbox would be cleaner.

**Review by Charles-Gagnon — APPROVED** [review]
Looks fine, but a few comments to consider

**Review by alanrenmsft — APPROVED** [review]
