### PR TITLE
Notebooks: Support for In-Proc Markdown Renderer

### LINKED ISSUE #5640: Relative paths on Notebooks
Issue Type: <b>Bug</b>

Currently we're not able to link notebooks to one another using relative paths.

Azure Data Studio version: azuredatastudio 1.7.0-insider (fcb2b53bf8af46d2cae855ce776e0eb29f1455b9, 2019-05-15T21:06:28.219Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (3.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### LINKED ISSUE #5826: Images not rendering in markdown cells in notebooks
- Azure Data Studio Version: 1.7.0

Steps to Reproduce:

1. This used to work, but now it is not as of 1.7.0
image
2. If I ctrl+click on the /images/wwi.png the file opens in a new tab
image
3. Yet it does not render within the notebook.

I could be doing something wrong? But I can't find anything in the docs about it either.

Thank you!
Anna

### PR DESCRIPTION
**Pull request by chlafreniere**
Building on the work that @kevcunnane started, add an option to use an in-proc markdown renderer (off by default in stable, on by default everywhere else). After we have sufficient confidence that this works for a greater group of people, we can turn this on by default, and finally remove the old code path.

VS Code leverages the 'marked' javascript library so that markdown rendering doesn't have to go over to the extension host; for startup scenarios, this can result in an order of magnitude difference in markdown cell render time.

We're now separating out content reading/rendering from the rest of the model load; there were a few changes that had to happen as a result of this, including passing in the 'standardKernels' when they become available, instead of through the constructor. VS Code had overwritten some of the calls from 'marked', so I leveraged what they wrote, adapted it to the notebook scenarios (using the notebook's location as a possible 'baseUrl', passing through the trusted state, etc.).

Fixes #5826.
Fixes #5640.

### CODE REVIEW

File: src/sql/workbench/parts/notebook/notebook.component.ts [hunk 1]
```diff
@@ -311,6 +314,7 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 	private async awaitNonDefaultProvider(): Promise<void> {
 		// Wait on registration for now. Long-term would be good to cache and refresh
 		await this.notebookService.registrationComplete;
+		this.model.standardKernels = this._notebookParams.input.standardKernels;
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/notebook.component.ts]: Nice solution here.

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts [hunk 2]
```diff
@@ -0,0 +1,240 @@
...
+
+export class NotebookMarkdownRenderer {
+	private _notebookURI: URI;
+	private _baseUrls: string[] = [];
+
+	constructor() {
+	}
+
+	render(markdown: IMarkdownString): IMarkdownRenderResult {
+		let disposables: IDisposable[] = [];
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Do we intent to use this disposable in the future?

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts [hunk 3]
```diff
@@ -0,0 +1,240 @@
...
+	 * be clickable.
+	 */
+	renderMarkdown(markdown: IMarkdownString, options: RenderOptions = {}): HTMLElement {
+		const element = this.createElement(options);
+
+		// signal to code-block render that the element has been created
+		let signalInnerHTML: () => void;
+		const withInnerHTML = new Promise(c => signalInnerHTML = c);
+
+		let notebookFolder = path.join(path.dirname(this._notebookURI.fsPath), path.sep);
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: On Mac the separator is `/` but on Windows `\`. My understanding is that in Markdown all links should use URI format (e.g. `./my/relative/file.txt`). I can see supporting `\` on Windows, but we at least need to support `/`. I'd suggest we do that by re-converting the directory to a URI and getting the path from that?

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts [hunk 4]
```diff
@@ -0,0 +1,240 @@
...
+		if (!this._baseUrls.includes(notebookFolder)) {
+			this._baseUrls.push(notebookFolder);
+		}
+		const renderer = new marked.Renderer({ baseUrl: notebookFolder });
+		renderer.image = (href: string, title: string, text: string) => {
+			href = this.cleanUrl(!markdown.isTrusted, notebookFolder, href);
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Minor: all these are large enough they warrant their own method/function for simplicity. I know VSCode doesn't do that, but can we?

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts [hunk 5]
```diff
@@ -0,0 +1,240 @@
...
+import { IDisposable, dispose } from 'vs/base/common/lifecycle';
+import { RenderOptions } from 'vs/base/browser/htmlContentRenderer';
+import { IMarkdownString, removeMarkdownEscapes } from 'vs/base/common/htmlContent';
+import { IMarkdownRenderResult } from 'vs/editor/contrib/markdown/markdownRenderer';
+import marked = require('vs/base/common/marked/marked');
+import { defaultGenerator } from 'vs/base/common/idGenerator';
+import { revive } from 'vs/base/common/marshalling';
+import * as fs from 'fs';
+
+export class NotebookMarkdownRenderer {
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Can you leave a comment referencing which class we're basing this on? Periodically we might want to compare & see if we need to / should update anything.

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts [hunk 6]
```diff
@@ -0,0 +1,240 @@
...
+			if (href === text) { // raw link case
+				text = removeMarkdownEscapes(text);
+			}
+			title = removeMarkdownEscapes(title);
+			href = removeMarkdownEscapes(href);
+			if (
+				!href
+				|| !markdown.isTrusted
+				|| href.match(/^data:|javascript:/i)
+				|| href.match(/^command:(\/\/\/)?_workbench\.downloadResource/i)
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Is this removing support for command syntax? What specifically are these 2 lines blocking? I just want to make sure the feature where, when trusted, we can execute commands is still present. Thanks!

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts [hunk 7]
```diff
@@ -0,0 +1,240 @@
...
+					}).catch(err => {
+						// ignore
+					});
+				});
+
+				if (options.codeBlockRenderCallback) {
+					promise.then(options.codeBlockRenderCallback);
+				}
+
+				return `<div class="code" data-code="${id}">${escape(code)}</div>`;
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Do we need to update CSS for this or is it already correct looking? Can we verify this, just in case it's different from existing markdown. Thanks!

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts [hunk 8]
```diff
@@ -0,0 +1,240 @@
...
+
+		element.innerHTML = marked.parse(markdown.value, markedOptions);
+		signalInnerHTML!();
+
+		return element;
+	}
+
+	// This following methods have been adapted from marked.js
+	// Copyright (c) 2011-2014, Christopher Jeffrey (https://github.com/chjj/)
+	cleanUrl(sanitize, base, href) {
```
Comment (kevcunnane) [inline src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Minor: can we add in typings here? I know the method comes from elsewhere, but still nice.

File: src/sql/workbench/parts/notebook/models/notebookModel.ts [hunk 9]
```diff
@@ -294,7 +296,7 @@ export class NotebookModel extends Disposable implements INotebookModel {
 			// if cells already exist, create them with language info (if it is saved)
 			this._cells = [];
 			if (contents) {
-				this._defaultLanguageInfo = this.getDefaultLanguageInfo(contents);
+				this._defaultLanguageInfo = contents && contents.metadata && contents.metadata.language_info;
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/models/notebookModel.ts]: Correct.

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 5 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Ah I put a comment in renderMarkdown but not before the class declaration. I'll make sure there's a comment at the top too.

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 6 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: I tested commands and they work just fine when trusted. I think this just prevents workbench.downloadResource (which I'm assuming was done out of security concerns).

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 7 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: I have a number of test notebooks and couldn't see any weirdness from this.

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 8 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: How do I do that?

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 6 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: The second line is blocking pure javascript. Since we don't have a renderer any preference over whether we should get rid of this block here?

File: src/sql/workbench/parts/notebook/cellViews/textCell.component.ts [hunk 10]
```diff
@@ -152,16 +170,34 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 				this._content = this.cellModel.source;
 			}
 
-			this._commandService.executeCommand<string>('notebook.showPreview', this.cellModel.notebookModel.notebookUri, this._content).then((htmlcontent) => {
-				htmlcontent = this.convertVscodeResourceToFileInSubDirectories(htmlcontent);
-				htmlcontent = this.sanitizeContent(htmlcontent);
+			if (this.useInProcMarkdown) {
+				let uri = Object.create(null);
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/cellViews/textCell.component.ts]: The markdown renderer allows special handling for uri's if they're already known. Since we don't know them at this point, that's why we're creating an object with no properties here.

export interface IMarkdownString {
	value: string;
	isTrusted?: boolean;
	uris?: { [href: string]: UriComponents };
}

File: src/sql/workbench/parts/notebook/cellViews/textCell.component.ts [hunk 11]
```diff
@@ -152,16 +170,34 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
...
-			});
+				DOM.clearNode(outputElement);
+				DOM.append(outputElement, this.markdownResult.element);
+			} else {
+				this._commandService.executeCommand<string>('notebook.showPreview', this.cellModel.notebookModel.notebookUri, this._content).then((htmlcontent) => {
+					htmlcontent = this.convertVscodeResourceToFileInSubDirectories(htmlcontent);
+					htmlcontent = this.sanitizeContent(htmlcontent);
+					let outputElement = <HTMLElement>this.output.nativeElement;
+					outputElement.innerHTML = htmlcontent;
+					this.setLoading(false);
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/cellViews/textCell.component.ts]: The spinner goes away eventually. Let me clean up this logic.

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 2 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Unsure. I can clean this up some more.

File: src/sql/workbench/parts/notebook/notebook.component.ts [hunk 12]
```diff
@@ -268,35 +264,42 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 	}
 
 	private async loadModel(): Promise<void> {
+		let start = performance.now();
+		this.setLoading(false);
+		// Once contents loaded, wait on provider information to be available before loading kernel and other information
 		await this.awaitNonDefaultProvider();
+		await this.notebookParams.input.getProviderInfo();
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/notebook.component.ts]: Don't need this anymore after I did some more refactoring. Let me remove it.

File: src/sql/workbench/parts/notebook/notebook.component.ts (hunk 1 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/notebook.component.ts]: 😄

File: src/sql/workbench/parts/notebook/notebook.component.ts [hunk 13]
```diff
@@ -268,35 +264,42 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 	}
 
 	private async loadModel(): Promise<void> {
+		let start = performance.now();
+		this.setLoading(false);
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/notebook.component.ts]: Good catch.

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 3 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: This isn't in markdown though. This is the root directory that we're passing into the markdown renderer, which will spit out links in the correct format. If I'm understanding you correctly, I think this is ok?

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 8 above)
Comment (kevcunnane) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: I meant types as in `href: Element` or `href: HtmlElement`?

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 3 above)
Comment (kevcunnane) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: As long as this works on Windows and mac, it's OK. I'm just trying to make sure that we don't get weirdly formed links like `C:\my\folder/relative/link/forward.txt`

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 6 above)
Comment (kevcunnane) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: This is fine to keep as-is

File: src/sql/workbench/parts/notebook/cellViews/textCell.component.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (kevcunnane) [reply src/sql/workbench/parts/notebook/cellViews/textCell.component.ts]: OK, I think we could inline this or since it's optional just not fill in?

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 3 above)
Comment (kevcunnane) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: I won't block on this given your explanation. Let's just test / verify this.

File: src/sql/workbench/parts/notebook/cellViews/textCell.component.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/cellViews/textCell.component.ts]: Ack won't fill it in.

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 8 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Done, thanks

File: src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts (hunk 3 above)
Comment (chlafreniere) [reply src/sql/workbench/parts/notebook/outputs/notebookMarkdown.ts]: Ok I reworked this a tiny bit based on your feedback and from testing.

Here's what now works on Windows:
tux1.0
tux2.0 
tux3.0
tux4.0

And on Mac
tux
tux2.0
tux3.0
tux4.0
