### PR TITLE
Notebooks: Ensure Python Environment Variables are Removed Before First Python Command

### LINKED ISSUE #12995: Notebook failed to initialize due to conflicting PYTHONHOME environment variable.
- Azure Data Studio Version:
Version: 1.23.0
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. set PYTHONHOME to c:\python37. Assuming you have python37 installed at c:\python37
2. install ML extension.
3. start ADS

ML extension will failed to start because it depends on notebook. Notebook failed to start because of the below error.
Note that I did not have any notebook opne in ADS. This is also a fresh install of ADS and ML extension.

image

```
[2020-10-19 14:53:26.265] [exthost] [info] extension host started
[2020-10-19 14:53:26.272] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.azurecore {"startup":true,"extensionId":{"value":"Microsoft.azurecore","_lower":"microsoft.azurecore"},"activationEvent":"*"}
[2020-10-19 14:53:26.272] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/azurecore/dist/extension
[2020-10-19 14:53:26.403] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-10-19 14:53:26.403] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/git/dist/main
[2020-10-19 14:53:26.528] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-10-19 14:53:26.528] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-10-19 14:53:26.561] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.notebook {"startup":true,"extensionId":{"value":"Microsoft.notebook","_lower":"microsoft.notebook"},"activationEvent":"*"}
[2020-10-19 14:53:26.561] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/notebook/dist/extension
[2020-10-19 14:53:26.937] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-10-19 14:53:26.937] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/search-result/dist/extension.js
[2020-10-19 14:53:26.954] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.datavirtualization {"startup":true,"extensionId":{"value":"Microsoft.datavirtualization","_lower":"microsoft.datavirtualization"},"activationEvent":"*"}
[2020-10-19 14:53:26.954] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jarupatj/.azuredatastudio/extensions/microsoft.datavirtualization-1.10.0/out/src/extension
[2020-10-19 14:53:29.387] [exthost] [error] Activating extension Microsoft.notebook failed due to an error:
[2020-10-19 14:53:29.387] [exthost] [error] Error: Command failed: "C:\Users\jarupatj\azuredatastudio-python\0.0.1\python.exe" -c "import site;print(site.USER_SITE)"
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Python37\lib\_bootlocale.py", line 12, in getpreferredencoding
    if sys.flags.utf8_mode:
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
 
    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2020-10-19 14:53:29.387] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-10-19 14:53:29.388] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/github/dist/extension.js
[2020-10-19 14:53:29.430] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.mssql {"startup":true,"extensionId":{"value":"Microsoft.mssql","_lower":"microsoft.mssql"},"activationEvent":"*"}
[2020-10-19 14:53:29.430] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/mssql/dist/main
[2020-10-19 14:53:32.665] [exthost] [info] eager extensions activated
[2020-10-19 14:53:41.131] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2020-10-19 14:53:41.131] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2020-10-19 14:53:41.137] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-10-19 14:53:41.138] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
```

You will see the failure that it can't find utf8_mode because utf8_mode only available on python 3.7 and later
https://github.com/pyinstaller/pyinstaller/issues/3866

```
[2020-10-19 14:53:29.387] [exthost] [error] Error: Command failed: "C:\Users\jarupatj\azuredatastudio-python\0.0.1\python.exe" -c "import site;print(site.USER_SITE)"
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Python37\lib\_bootlocale.py", line 12, in getpreferredencoding
    if sys.flags.utf8_mode:
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
```

Looking closely, python that ADS uses are python36. However, since we have python37 as default by setting PYTHONHOME, this cause conflict.

```
C:\Users\jarupatj\azuredatastudio-python\0.0.1>python.exe
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #12995.

The call to get the python user directory actually executes a Python command:

```
let cmd = `"${pythonExecutable}" -c "import site;print(site.${sitePath})"`;
```

Because of this, existing environment variables can affect how this command gets run (and which version of Python is targeted). Removing the Python-related things environment variables before calling this fixes the issue. Verified this internally with someone running into this problem.

### CODE REVIEW

File: extensions/notebook/src/jupyter/jupyterServerInstallation.ts [hunk 1]
```diff
@@ -320,6 +320,11 @@ export class JupyterServerInstallation implements IJupyterServerInstallation {
 			}
 		}
 
+		// Delete existing Python variables in ADS to prevent conflict with other installs
+		delete process.env['PYTHONPATH'];
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: If we're going to be doing this to the ADS process shouldn't this be something we do at startup? Because otherwise you may be having stuff running along using the env vars happily but then all of a sudden have them removed and break other things once you actually open a notebook.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by lucyzhang929 — APPROVED** [review]

File: extensions/notebook/src/jupyter/jupyterServerInstallation.ts (hunk 1 above)
Comment (corivera) [inline extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: Might as well move these deletes to the top of the method. That would prevent any command ordering edge cases if we modify this method later on.

**Review by corivera — APPROVED** [review]

**Review by VasuBhog — APPROVED** [review]

File: extensions/notebook/src/jupyter/jupyterServerInstallation.ts (hunk 1 above)
Comment (chlafreniere) [reply extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: While this may be the case, there are other scenarios that leverage Python that could be broken by making a change globally at startup (ML extension as an example), so I'm hesitant to make a global change like that, since that could impact a number of scenarios outside of notebooks . I'd prefer to keep our existing behavior at the moment until we need to change this to unblock those folks who are hitting this particular bug.

Comment (Charles-Gagnon) [reply extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: But isn't this still going to be a breaking issue for those if that's the case? It'll just happen later instead of at startup.

It seems like we should be starting up the Jupyter instance with those env vars removed instead of modifying the ADS process itself.

Comment (chlafreniere) [reply extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: Only if users open a notebook before leveraging those other scenarios. I agree that it's not perfect for sure.

It's really 2 things:
- Jupyter should be started without these env vars
- There are other Python calls that exist without Jupyter being in the picture (pip/conda install, python user folder, etc). 

The 2nd one is a bit trickier so trying to figure out how we can prevent impacts in other scenarios there. Remove env vars, run whatever command, then set those vars back to their previous values?

Comment (corivera) [reply extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: Would using a virtual environment fix those issues?

Comment (Charles-Gagnon) [reply extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: And for the commands - we're almost always spawning a child process for those so can modify the environment used for that directly.

Comment (chlafreniere) [reply extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: @corivera potentially yes. If we wanted to go down that route in the future, there are a few teams that we would want to talk to. Have heard some stories about trickiness there too 😄

Comment (chlafreniere) [reply extensions/notebook/src/jupyter/jupyterServerInstallation.ts:324]: https://github.com/microsoft/azuredatastudio/issues/13144

I've added a priority tag there. Merging in this fix for existing behavior is high pri, so we'll go with this for now instead of blocking for a more ideal fix. I'll need to setup a repro environment myself, but after looking through the code, this looks doable; the trick will be ensuring that we catch all of the places where we interact with `child-process`
