### PR TITLE
Don't open schema compare if project build fails

### LINKED ISSUE #12715: When launching Schema Compare from project but build fails, it still opens schema compare UI and populates with dacpac path

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #12715. Previously, schema compare would open if there was a dacpac in the project's bin folder. buildProject() returns the undefined if the build failed and the dacpac path if successful, so we can use that instead of creating the dacpac path again.

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -272,17 +272,11 @@ export class ProjectsController {
...
 			// build project
-			await this.buildProject(treeNode);
-
-			// start schema compare with the dacpac produced from build
-			const project = this.getProjectFromContext(treeNode);
-			const dacpacPath = path.join(project.projectFolderPath, 'bin', 'Debug', `${project.projectFileName}.dacpac`);
+			const dacpacPath = await this.buildProject(treeNode);
 
 			// check that dacpac exists
 			if (await utils.exists(dacpacPath)) {
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/controllers/projectController.ts:278]: we should still give the message that dacpac wasnt created and SC cant start... right?

**Review by udeeshagautam — APPROVED** [review]

File: extensions/sql-database-projects/src/controllers/projectController.ts (hunk 1 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/controllers/projectController.ts:278]: updated the error message to be because the build failed(a dacpac from a previous successful build could still exist)
