### PR TITLE
Show error when trying to add file/folder that already exists to project

### LINKED ISSUE #11103: No error when trying to add file or folder with name that already exists
Steps to Reproduce:

1. Create a project with a table called Table1.sql
2. Add table with the same name

Expected: There should be an error that a file with the same name already exists on disk at that location. 

Actual: The entry gets added to the sqlproj and the old file is overwritten

Same problem for creating a folder with the same name

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #11103. This makes it so that an error shows if the user tries to add a file or folder that already exists. Previously, another entry would get added to the sqlproj and the old file would get overwritten. This also checks for the reserved folders in a project, which are currently: Data Sources, Database References, and Properties. These aren't physical folders, but they're in the project tree.

### CODE REVIEW

File: extensions/sql-database-projects/src/models/project.ts [hunk 1]
```diff
@@ -589,3 +589,5 @@ export enum SystemDatabase {
 	master,
 	msdb
 }
+
+export const reservedProjectFolders = ['Properties', 'Data Sources', 'Database References'];
```
Comment (Benjin) [inline extensions/sql-database-projects/src/models/project.ts:593]: Actually, Properties should either be a physical folder that gets created on disk (how SSDT works), or not created at all (even in virtual form, since I've never seen the Properties folder get used for anything in SSDT, and there's no harm in deleting it from the project in SSDT).

It's be awesome if you added either of those changes to this PR :)

Comment (kisantia) [reply extensions/sql-database-projects/src/models/project.ts:593]: Oh weird I haven't seen Properties be a physical folder that gets created by SSDT with the other folders in the project. Where does the folder get added? 

It's probably ok to not show the folder in ADS since editing the properties in the UI isn't supported, but I'm hesitant to get rid of it altogether because then it removes this launch point to editing the properties in SSDT: 
image

Comment (udeeshagautam) [reply extensions/sql-database-projects/src/models/project.ts:593]: Yep, we can also in long run have project dashboard open from properties may be... so lets not remove completely anyways. We can stop showing in ADS tree - but I dont now its required since its not hurting any scenario.

Question on reserved folder - can one add afile in reserved folder?

File: extensions/sql-database-projects/src/test/projectController.test.ts [hunk 2]
```diff
@@ -110,6 +111,75 @@ describe('ProjectsController: project controller operations', function (): void
...
+
+			await verifyFolderNotAdded(folderName, projController, project, projectRoot);
+
+			// reserved folder names
+			for (let i in reservedProjectFolders) {
+				await verifyFolderNotAdded(reservedProjectFolders[i], projController, project, projectRoot);
+			}
+		});
+
+		it('Should be able to add folder with reserved name as long as not at project root', async function (): Promise<void> {
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/test/projectController.test.ts:152]: can we add a check that root level adding fails also

File: extensions/sql-database-projects/src/test/projectController.test.ts [hunk 3]
```diff
@@ -110,6 +111,75 @@ describe('ProjectsController: project controller operations', function (): void
...
+			should(project.files.length).equal(1, 'There should only be the properties folder');
+			await projController.addFolderPrompt(projectRoot);
+			should(project.files.length).equal(2, 'Folder should be successfully added');
+			projController.refreshProjectsTree();
+
+			await verifyFolderNotAdded(folderName, projController, project, projectRoot);
+
+			// reserved folder names
+			for (let i in reservedProjectFolders) {
+				await verifyFolderNotAdded(reservedProjectFolders[i], projController, project, projectRoot);
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/test/projectController.test.ts:148]: good one

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 4]
```diff
@@ -325,16 +342,26 @@ export class ProjectsController {
...
+			}
 
-		this.refreshProjectsTree();
+			const newEntry = await project.addScriptItem(relativeFilePath, newFileText);
+
+			this.apiWrapper.executeCommand('vscode.open', newEntry.fsUri);
+
+			this.refreshProjectsTree();
+		} catch (err) {
+			this.apiWrapper.showErrorMessage(utils.getErrorMessage(err));
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/controllers/projectController.ts:363]: should the showErrorMessage ones be awaited? the vscode api is thenable...

@aaomidi  any suggestion here?

File: extensions/sql-database-projects/src/models/project.ts (hunk 1 above)
Comment (Benjin) [reply extensions/sql-database-projects/src/models/project.ts:593]: @kisantia Looks like I got my wires crossed between csproj and sqlproj again; .net framework projects create a physical properties folder.  Virtual folder it is!

File: extensions/sql-database-projects/src/controllers/projectController.ts (hunk 4 above)
Comment (aaomidi) [reply extensions/sql-database-projects/src/controllers/projectController.ts:363]: No they shouldn't. The await only resolves once the dialog is closed. The promise is kinda being used as an event.

File: extensions/sql-database-projects/src/models/project.ts (hunk 1 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/models/project.ts:593]: @udeeshagautam no files can't be added to these reserved folders. The database references folder isn't a physical folder (the refs are from the sqlproj) and the data sources are read from a file single datasources.json file in the project folder.
