### PR TITLE
Kenvh/noazurecms

### LINKED ISSUE #8471: Data is null for Sql Server Central Management Servers extension
On Central Management Servers extension.
Added the Azure server and it shows up under the Central Management Servers.
Click on the server and get this error:

Data is Null. This method or property cannot be called on Null values.

### PR DESCRIPTION
**Pull request by kenvanhyning**
Added check for "isCloud" to disallow setting an Azure SQL DB server as a CMS server.  

This PR fixes #8471

### CODE REVIEW

File: src/sql/workbench/services/connection/browser/connectionManagementService.ts [hunk 1]
```diff
@@ -991,6 +991,7 @@ export class ConnectionManagementService extends Disposable implements IConnecti
 						this._connectionStatusManager.deleteConnection(uri);
 						resolve({ connected: connectResult, errorMessage: errorMessage, errorCode: errorCode, callStack: callStack, connectionProfile: connection });
 					} else {
+						connection.options.isCloud = connectionMngInfo.serverInfo.isCloud;
```
Comment (anthonydresser) [inline src/sql/workbench/services/connection/browser/connectionManagementService.ts]: Might make more sense to utilize command 'when' statements and use the context mssql extension is already setting for isCloud

Comment (kenvanhyning) [reply src/sql/workbench/services/connection/browser/connectionManagementService.ts]: Can you point me to an example to learn from for this?  This isn't to decide to show menus or not, but rather if a successfully connected to server should be added to the CMS registration list.  The other check was already there was duplicate name.  Maybe there is a better place I could do this check all together?

Comment (kenvanhyning) [reply src/sql/workbench/services/connection/browser/connectionManagementService.ts]: Checked with Karl and when has more to do with what commands are valid for a given connection context.  This is a validation check for adding an item to a viewlet so keeping it this way for now.

Comment (kburtram) [reply src/sql/workbench/services/connection/browser/connectionManagementService.ts]: I think this code path is for validation of dialog box input.  I'm not sure how we can use the when clause for this task.  Wouldn't we need a new concept like "Validation" or "Server" or something to attach the when to, since there isn't an applicable command in this case.
