### PR TITLE
fix declarative table issue

### LINKED ISSUE #10637: controller storage class settings is required but not enforced
BDC wizard's service settings page
Screen Shot 2020-05-15 at 4 44 13 PM

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #10637 

the events (validity changed event for this specific issue) of the components added to the declarative table are not being wired properly, this is done by adding them to the container.

**before**
Screen Shot 2020-06-09 at 3 38 36 PM
**after** the next button is disabled now
Screen Shot 2020-06-09 at 3 37 57 PM

### CODE REVIEW

File: src/sql/workbench/browser/modelComponents/declarativeTable.component.ts [hunk 1]
```diff
@@ -205,6 +199,16 @@ export default class DeclarativeTableComponent extends ComponentBase implements
 
 	public setProperties(properties: { [key: string]: any; }): void {
 		super.setProperties(properties);
+		if (properties.data) {
+			this.clearContainer();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/declarativeTable.component.ts:203]: So every time we change a property we're going to clear and refresh the grid? Did you test to see if this is visible? I'm worried that we'll get some flickering and/or lose context (such as focus state) by doing this.

**Comment by aaomidi** [comment]
Btw to validate stuff isn't being recreated over and over place a print statement on the constructor of checkbox and see how many times thats getting constructed.

That was the main symptom of inefficiency I noticed.

**Comment by aaomidi** [comment]
So I think this broke the header level checkboxes.
