### PR TITLE
Ensure Active File is Highlighted in Books Viewlet

### LINKED ISSUE #9248: Jupyter Book - Active (opened) file should be highlighted in the Jupyter Book Viewlet
This scenario happens usually when there are multiple notebooks in Jupyter book. The issue impact increases when there are many linked notebooks (files) and / or the hierarchy is deep. 

- Azure Data Studio Version:
Version: 1.15.1 (user setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open a notebook (that has a link to another notebook) from Jupyter Book viewlet. 
2. Click on the link to open another notebook. 
3. The (2nd) notebook now is not highlighted in Jupyter Book viewlet.

Another way of reproducing is:
1. Search for a notebook and open it from one of the results. 
2. View the Jupyter Book viewlet, the opened notebook is not highlighted in the viewlet.

### PR DESCRIPTION
**Pull request by chlafreniere**
This resolves #9248. I am also focusing on notebooks here; we can expand to markdown as well in the future.

When opening a notebook that is in an opened book, we'll now see the notebook item selected + focused when the viewlet is already opened. In addition, when another viewlet is opened and we navigate back to the books viewlet, if the active document is a notebook, we will see that item selected as well.

We also didn't have an azdata API that we could hook into for active notebook editor changes. Since we were already tracking this in the extHostNotebookDocumentsAndEditors, it was trivial to expose here.

BooksViewletSelection

### CODE REVIEW

File: extensions/notebook/src/extension.ts [hunk 1]
```diff
@@ -109,6 +109,8 @@ export async function activate(extensionContext: vscode.ExtensionContext): Promi
 		await vscode.commands.executeCommand('vscode.open', vscode.Uri.parse(urlToOpen));
 	}));
 
+	extensionContext.subscriptions.push(vscode.commands.registerCommand('notebook.command.revealInBooksViewlet', (uri: vscode.Uri, shouldReveal: boolean) => bookTreeViewProvider.revealActiveDocumentInViewlet(uri, shouldReveal)));
```
Comment (MaddyDev) [inline extensions/notebook/src/extension.ts]: So we don't need this for untitled view-let?

File: extensions/notebook/src/book/bookTreeView.ts [hunk 2]
```diff
@@ -89,6 +89,15 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 		if (!this.currentBook) {
 			this.currentBook = book;
 		}
+		this._bookViewer = vscode.window.createTreeView(this.viewId, { showCollapseAll: true, treeDataProvider: this });
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts]: This should be using the apiWrapper to do this

File: src/sql/azdata.d.ts [hunk 3]
```diff
@@ -4224,6 +4224,11 @@ declare module 'azdata' {
 		 */
 		export const onDidOpenNotebookDocument: vscode.Event<NotebookDocument>;
 
+		/**
+		 * An event that is emitted when the active Notebook editor is changed.
+		 */
+		export const onDidChangeActiveNotebookEditor: vscode.Event<NotebookEditor>;
```
Comment (Charles-Gagnon) [inline src/sql/azdata.d.ts]: Add this to azdata.proposed.d.ts

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 4]
```diff
@@ -438,6 +440,9 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 
 		if (this.contextKeyService.getContextKeyValue('bookOpened') && this._navProvider) {
 			this._navProvider.getNavigation(this._notebookParams.notebookUri).then(result => {
+				if (result && result.hasNavigation) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts]: >hasNavigation [](start = 25, length = 13)

Why are you tying this to hasNavigation? I'm guessing here you just want to only execute the command if the notebook is part of a book? I'd think that check would be unnecessary though - you can just always execute the command and then if the notebook isn't part of a book it wouldn't do anything (there wouldn't be a corresponding tree item to reveal)

File: extensions/notebook/src/book/bookTreeView.ts [hunk 5]
```diff
@@ -89,6 +89,15 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
...
+		this._bookViewer.onDidChangeVisibility(e => {
+			if (e.visible) {
+				this.revealActiveDocumentInViewlet();
+			}
+		});
+		azdata.nb.onDidChangeActiveNotebookEditor(e => {
+			this.revealActiveDocumentInViewlet(e.document.uri, false);
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts]: Just checking - this handles the case where you move to a different editor by unselecting the tree item in the viewlet right?

Comment (chlafreniere) [reply extensions/notebook/src/book/bookTreeView.ts]: Yeah, that works.

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts (hunk 4 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts]: Yeah. hasNavigation implies that it's part of a book. Lemme play with this.

Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts]: Looks good I can remove this condition.

File: extensions/notebook/src/extension.ts (hunk 1 above)
Comment (chlafreniere) [reply extensions/notebook/src/extension.ts]: I chatted about this and thought about this some more, and we actually don't. Given the latest mockups it doesn't include the untitled viewlet either, so let's leave this alone for now.

Comment (MaddyDev) [reply extensions/notebook/src/extension.ts]: Do I need change the way we're opening the TSG books then? Because currently they open in the untitled view-let, probably will fail with the current changes.
