### PR TITLE
do nothing if the focus is already in dialog

### LINKED ISSUE #9293: A11y_SQLAzureDataStudio_NewDeployment_SQLServerBigDataCluster_Keyboard: When selected any option from Deployment target combo box, focus moves to ‘I accept…License terms’ Checkbox.
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#DesktopWeb;#MacOS;#MAS2.4.3;# Benchmark;#A11y_SQLAzureDataStudioBenchmark;#A11ySev2;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.15.0-insider
Commit: 3a8b74a
Date: 2020-02-11T05:49:41.181Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
Mac OS:10.15.3

Additional Details:
Mac OS:10.15.3
MAS reference: MAS2.4.3

**Repro Steps:**

1. Launch Azure Data Studio.
2. Select the Connections icon (if not already selected) from left bar.
3. Click on the ellipses '...' and select "New Deployment".
4. Select "SQL Server Big Data Cluster" card under deployment options.
5. Navigate to Deployment Target combo box using tab key and select any option.

**Actual:**
When selected any option from Deployment target combo box using Space key, focus moves to ‘I accept…License terms’ Checkbox

**Expected:**
When selected any option from Deployment Target combo box, focus should remain at Deployment Combo box.

**User Impact:**
Keyboard only users will face difficulty to trace the current focus.

**Attachment link reference:**
[9293_A11y_SQLAzureDataStudio_NewDeployment_SQLServerBigDataCluster_Keyboard.zip](https://github.com/microsoft/azuredatastudio/files/4274824/9293_A11y_SQLAzureDataStudio_NewDeployment_SQLServerBigDataCluster_Keyboard.zip)

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #9293

finally figured out why the focus is moving away, setting the dialog.message will change the focus 😆 
the fix is to keep the focus if the it is already inside the dialog.

### CODE REVIEW

File: src/sql/workbench/browser/modal/modal.ts [hunk 1]
```diff
@@ -498,9 +498,11 @@ export abstract class Modal extends Disposable implements IThemable {
 				DOM.prepend(this._modalContent, (this._messageElement));
 			}
 		} else {
-			// Set the focus manually otherwise it'll escape the dialog to something behind it
-			this.setInitialFocusedElement();
 			DOM.removeNode(this._messageElement);
+			// Set the focus to first focus element if the focus is not within the dialog
+			if (!DOM.isAncestor(this._bodyContainer.ownerDocument.activeElement, this._bodyContainer)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modal/modal.ts]: You should be able to just use document.activeElement. Any reason you're using ownerDocument instead?

Comment (alanrenmsft) [reply src/sql/workbench/browser/modal/modal.ts]: document.activeElement works too. changed it in latest commit.

**Comment by alanrenmsft** [comment]
> Are we handling the case where focus is within the messages dialog and it gets closed correctly? i.e. tab to the close button and click enter and then shift+tab - in my testing that seemed to escape outside the dialog.

Yes, I have tested scenario:
1. Move the keyboard focus to the 'Close' button in the message area.
1. Press enter to close the message box.
=> The focus will be moved to the first focusable element in the dialog
1. Press Shift+Tab
=>the focus will go to the cancel button of the dialog
