### PR TITLE
[Azure Arc] Update MIAA model to include encryption properties

### LINKED ISSUE #21703: Unable to manage Arc SQL MI database from Azure Data Studio(ADS)
_Originally reported question: [Unable to manage Arc SQL MI...](https://learn.microsoft.com/en-us/answers/questions/1161292/unable-to-manage-arc-sql-mi-database-from-azure-da)_

"I was able to connect to Azure Arc SQL MI from Azure Data Studio(ADS). But, unable to manage databases as 'Connect to Server' is failing with below errors related to certificates. I learnt that this error goes away, if Encrypt can be changed to No or TrustServerCertificate can be changed to Yes in the connection string. But I didn’t find any option to change connection string in ADS. Please let me know how and where to change connection string in ADS.

image

`Error: Instance x.x.x.x,1433. A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)"`

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes #21703

This PR adds support to manage encryption options to be able to connect with SQL Managed Instance in Azure Arc extension, if server certificates are not installed. As of now, there's no workaround if TLS certificate is not available in client environment.

With changes:
AzureArcEncryptionNew

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Please add screenshots of the new UI elements being modified/added

**Comment by Charles-Gagnon** [comment]
Also could you file an issue in this repo so it can be tracked and linked to? (responding to the original issue would be great)

**Comment by cheenamalhotra** [comment]
> Please add screenshots of the new UI elements being modified/added

Added GIF to description

File: extensions/arc/src/ui/dialogs/connectSqlDialog.ts [hunk 1]
```diff
@@ -47,13 +58,22 @@ export abstract class ConnectToSqlDialog extends InitializingComponent {
...
 					value: connectionProfile?.password
-				})
-				.component();
+				}).component();
 			this.rememberPwCheckBox = this.modelBuilder.checkBox()
 				.withProps({
 					label: loc.rememberPassword,
 					checked: connectionProfile?.savePassword
 				}).component();
+			this.encryptSelectBox = this.modelBuilder.dropDown()
```
Comment (cheenamalhotra) [inline extensions/arc/src/ui/dialogs/connectSqlDialog.ts:67]: I'm working on including tooltip (info) icon and property description text

File: extensions/arc/src/localizedConstants.ts [hunk 2]
```diff
@@ -142,12 +142,19 @@ export const controllerPassword = localize('arc.controllerPassword', "Controller
...
+export const enableTrustServerCert = localize('arc.enableTrustServerCert', "Enable Trust Server Certificate");
+export const msgPromptSSLCertificateValidationFailed = localize('arc.msgPromptSSLCertificateValidationFailed', 'Encryption was enabled on this connection, review your SSL and certificate configuration for the target SQL Server, or set \'Trust server certificate\' to \'true\' in the settings file. Note: A self-signed certificate offers only limited protection and is not a recommended practice for production environments. Do you want to enable \'Trust server certificate\' on this connection and retry?');
 export const connect = localize('arc.connect', "Connect");
+export const readMore = localize('arc.readMore', "Read more");
 export const cancel = localize('arc.cancel', "Cancel");
 export const apply = localize('arc.apply', "Apply");
 export const ok = localize('arc.ok', "Ok");
 export const on = localize('arc.on', "On");
 export const off = localize('arc.off', "Off");
+export const booleantrue = localize('arc.booleantrue', "True");
```
Comment (Charles-Gagnon) [inline extensions/arc/src/localizedConstants.ts:156]: `booleanTrue` and `booleanFalse` (although personally I'd just do `true` and `false`...)

File: extensions/arc/src/ui/tree/controllerTreeNode.ts [hunk 3]
```diff
@@ -111,9 +111,14 @@ export class ControllerTreeNode extends TreeNode {
 						break;
 					case ResourceType.sqlManagedInstances:
 						// Fill in the username too if we already have it
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/tree/controllerTreeNode.ts:113]:
```suggestion
						// Fill in the username and connection properties too if we already have them
```

File: extensions/arc/src/ui/dialogs/connectSqlDialog.ts [hunk 4]
```diff
@@ -122,11 +157,37 @@ export abstract class ConnectToSqlDialog extends InitializingComponent {
...
+				});
+			} else {
+				vscode.window.showErrorMessage(this.connectionFailedMessage(result.errorMessage));
+				return false;
+			}
 		}
 	}
 
+	private async showInstructionTextAsWarning(profile: azdata.IConnectionProfile, reconnectAction: IReconnectAction): Promise<boolean> {
+		const selection = await vscode.window.showWarningMessage(
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectSqlDialog.ts:173]: So currently this shows just the explanation text when it fails as a warning. It seems to me : 

1. That it should be an error (the connection failed after all)
2. It should tell the user that the connection failed (and the error message) so it's clear what happened in addition to the current explanation of why

File: extensions/arc/src/ui/dialogs/connectSqlDialog.ts [hunk 5]
```diff
@@ -122,11 +157,37 @@ export abstract class ConnectToSqlDialog extends InitializingComponent {
 			return true;
 		}
 		else {
-			vscode.window.showErrorMessage(this.connectionFailedMessage(result.errorMessage));
-			return false;
+			// Show error with instructions for MSSQL Provider Encryption error code -2146893019 thrown by SqlClient when certificate validation fails.
+			if (result.errorCode === -2146893019) {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectSqlDialog.ts:161]: Isn't this something we should be handling on the provider side? Or at least provide some options to allow the provider to auto-fix stuff like this?

It's unfortunate that any extension which calls connect has to reimplement this same logic...a bunch of our extensions create connections this way.

File: extensions/arc/src/ui/dialogs/connectSqlDialog.ts [hunk 6]
```diff
@@ -122,11 +157,37 @@ export abstract class ConnectToSqlDialog extends InitializingComponent {
...
+				loc.readMore,
+				loc.cancel
+			]);
+		if (selection === loc.enableTrustServerCert) {
+			profile.options.encrypt = true;
+			profile.options.trustServerCertificate = true;
+			return await reconnectAction(profile);
+		} else if (selection === loc.readMore) {
+			vscode.env.openExternal(vscode.Uri.parse(constants.encryptReadMoreLink));
+			return await this.showInstructionTextAsWarning(profile, reconnectAction);
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectSqlDialog.ts:187]: Could just use a loop for this instead - that way we aren't adding extra stack frames every time the user clicks read more.

File: extensions/arc/src/localizedConstants.ts (hunk 2 above)
Comment (cheenamalhotra) [reply extensions/arc/src/localizedConstants.ts:156]: true/false are reserved keywords so variables can't be named - I hit that so I renamed :)

Comment (Charles-Gagnon) [reply extensions/arc/src/localizedConstants.ts:156]: Oh heh, yeah that makes sense 😁

File: extensions/arc/src/ui/dialogs/connectSqlDialog.ts (hunk 5 above)
Comment (cheenamalhotra) [reply extensions/arc/src/ui/dialogs/connectSqlDialog.ts:161]: I don't think this is provider responsibility.

There were 2 issues being addressed here:
1. Including Encryption properties in connection dialog:
It is extension's responsibility to include any property that is required for any server configuration, such that there is no server configuration that cannot be connected to. If these properties existed in the extension, user would have been unblocked by setting desired values themselves. This is the same problem as #21646 for CMS extension. If extensions are not mapping these properties, provider doesn't know.

2. Optional Error handling
What we're doing with the custom error dialog is just an experience improvement, by catching error and modifying properties for connection on behalf of the user when they click on 'Enable Trust Server Certificate'. It's an optional assistance, by catching error code. In general, error handling capabilities are being added to provider (with https://github.com/microsoft/azuredatastudio/pull/21627), but it is totally up-to provider to decide whether it wants to aid in handling a particular error, or let customers manually look into their setup. Irrespectively, end users shouldn't be blocked in making connections due to (1).

Comment (Charles-Gagnon) [reply extensions/arc/src/ui/dialogs/connectSqlDialog.ts:161]: 1. That makes sense for situations like this where a custom connection experience is done - so yes I agree that that's expected here to some extent
2. But the issue I have is that currently the whole handling of the SSL error and successive prompting-and-reconnecting thing seems like something the provider should have since it already knows what SSL errors are and what they usually mean. So it seems reasonable and useful for the provider to be able to be able to handle this so we don't have to duplicate this code in every extension that wants to make a connection itself. 

Building that into the error handling Alex is adding seems like a possible way to solve this - have you considered making that change after the feature work there is complete to move the SSL error updating into that instead? That would be a good test of the feature as well to see how useful/easy it is to make these types of changes and use them in a variety of situations.

Comment (cheenamalhotra) [reply extensions/arc/src/ui/dialogs/connectSqlDialog.ts:161]: Yes, it's planned to be addressed. 

Extensions would also have to be updated eventually to let provider handle error code before showing error dialog, as this extension does currently. But that should be one time change, and the flow would be:

Current: Extension receives error > extension handles error by showing error dialog.
Future: Extension receives error > provider API: handleError(errorInfo) > provider handles error or returns to let extension take default action.

Comment (Charles-Gagnon) [reply extensions/arc/src/ui/dialogs/connectSqlDialog.ts:161]: Sounds great!

**Comment by Charles-Gagnon** [comment]
Can you update the gif with the latest changes? Want to see how the dual-toast notifications look, generally we want to avoid spamming too many notifications at once (especially if they're for the same thing)

**Comment by cheenamalhotra** [comment]
> Can you update the gif with the latest changes? Want to see how the dual-toast notifications look, generally we want to avoid spamming too many notifications at once (especially if they're for the same thing)

Updated

File: extensions/arc/src/ui/dialogs/connectSqlDialog.ts [hunk 7]
```diff
@@ -123,10 +164,39 @@ export abstract class ConnectToSqlDialog extends InitializingComponent {
...
+					loc.readMore,
+					loc.cancel
+				]);
+			if (selection === loc.enableTrustServerCert) {
+				profile.options.encrypt = true;
+				profile.options.trustServerCertificate = true;
+				return await reconnectAction(profile);
+			} else if (selection === loc.readMore) {
+				vscode.env.openExternal(vscode.Uri.parse(constants.encryptReadMoreLink));
+				continue;
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectSqlDialog.ts:194]:
```suggestion
				// Show the dialog again so the user can still pick yes or no after they've read the docs
				continue;
```

**Review by Charles-Gagnon — APPROVED** [review]

**Review by candiceye — APPROVED** [review]
