### PR TITLE
Show notification if there are projects that haven't been added to the workspace

### LINKED ISSUE #13674: Adding a folder to a workspace/opening that workspace doesn't open sqlproj files under that folder
Steps to Reproduce:

1. Open a workspace.
2. Add a folder that has sqlproj file in it. 

Actual: no projects are opened, though folder opens up under Explorer.
image

Expectation: projects under the folder should open in Projects workspace.

image

Also, opening this workspace from with "Open existing" workspace doesn't open the projects under that workspace.
image

image

image

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #13674. Users could be confused if there are projects in their workspace folders, but they aren't showing up in the projects viewlet. This is because projects are only opened if they are in the dataworkspace.projects section of the workspace file like this: 
```
{
	"folders": [
		{
			"path": "test2"
		},
		{
			"name": "DatabaseProjectKeep_WideWorldImporters",
			"path": "../DatabaseProjectKeep_WideWorldImporters"
		}
	],"settings": {
		"dataworkspace.projects": [
			"test2/test2.sqlproj",
			"../DatabaseProjectKeep_WideWorldImporters/DatabaseProjectKeep_WideWorldImporters.sqlproj"
		]
}
```

This PR adds an info toast notification shows if there are projects in the workspace folders that haven't been added to the workspace. There is a button to launch the open existing dialog from this notification.
openExistingDialog

If users don't want to see this notification, then there is a setting to not show this notification, which will also skip doing the check.
doNotShowAgain

### CODE REVIEW

File: extensions/data-workspace/src/main.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@ import { IconPathHelper } from './common/iconHelper';
 export function activate(context: vscode.ExtensionContext): Promise<IExtension> {
 	const workspaceService = new WorkspaceService(context);
 	workspaceService.loadTempProjects();
+	workspaceService.checkForProjectsNotAddedToWorkspace();
```
Comment (alanrenmsft) [inline extensions/data-workspace/src/main.ts:19]: hmm, can you also try add a workspace folder, I am not sure whether that will cause a reload, if not, we have to have another event hook to do this check.

File: extensions/data-workspace/src/services/workspaceService.ts [hunk 2]
```diff
@@ -158,6 +159,55 @@ export class WorkspaceService implements IWorkspaceService {
...
+							if (!projectsInWorkspace.find(p => p.fsPath === projFile)) {
+								containsNotAddedProject = true;
+								break;
+							}
+						}
+
+						if (containsNotAddedProject) {
+							const result = await vscode.window.showInformationMessage(constants.WorkspaceContainsNotAddedProjects, constants.LaunchOpenExisitingDialog, constants.DoNotShowAgain);
+							if (result === constants.LaunchOpenExisitingDialog) {
+								//open settings
```
Comment (alanrenmsft) [inline extensions/data-workspace/src/services/workspaceService.ts:197]: If I don't leave a space after // I will get an error message when I commit. maybe not enabled for this extension?

File: extensions/data-workspace/src/main.ts (hunk 1 above)
Comment (kisantia) [reply extensions/data-workspace/src/main.ts:19]: good catch! Added an event hook to do the check for projects not in the workspace when the workspace folders change

File: extensions/data-workspace/src/services/workspaceService.ts (hunk 2 above)
Comment (kisantia) [reply extensions/data-workspace/src/services/workspaceService.ts]: do you remember which setting that is?

File: extensions/data-workspace/src/services/workspaceService.ts [hunk 3]
```diff
@@ -158,6 +159,55 @@ export class WorkspaceService implements IWorkspaceService {
...
+
+			// look for any projects that haven't been added to the workspace
+			const projectsInWorkspace = this.getProjectsInWorkspace();
+			const workspaceFolders = vscode.workspace.workspaceFolders;
+
+			if (workspaceFolders) {
+				for (const extType of supportedProjectExtensions) {
+					for (const folder of workspaceFolders) {
+						// find all project files with extType in the folder
+						const escapedPath = glob.escapePath(folder.uri.fsPath.replace(/\\/g, '/'));
```
Comment (alanrenmsft) [inline extensions/data-workspace/src/services/workspaceService.ts:181]: have you tested this on Windows? not sure how can it handle path like after escaping: c:/documents/

File: extensions/data-workspace/src/services/workspaceService.ts [hunk 4]
```diff
@@ -158,6 +159,55 @@ export class WorkspaceService implements IWorkspaceService {
...
+						const projFilter = path.posix.join(escapedPath, '**', `*.${extType}`);
```
Comment (alanrenmsft) [inline extensions/data-workspace/src/services/workspaceService.ts:182]: posix? why not use path.join?

File: extensions/data-workspace/src/services/workspaceService.ts (hunk 3 above)
Comment (kisantia) [reply extensions/data-workspace/src/services/workspaceService.ts:181]: yup this works on Windows. The path needs to use forward slashes for glob to work. I'll add a comment.

File: extensions/data-workspace/src/services/workspaceService.ts (hunk 4 above)
Comment (kisantia) [reply extensions/data-workspace/src/services/workspaceService.ts:182]: need to use posix for Windows since the path needs to use forward slashes for glob.

File: extensions/data-workspace/package.nls.json [hunk 5]
```diff
@@ -10,5 +10,6 @@
 	"projects-view-no-workspace-content": "No workspace open, create new or open existing to get started.\n[Create new](command:projects.new)\n[Open existing](command:projects.openExisting)\nTo learn more about SQL Database projects [read our docs](https://aka.ms/azuredatastudio-sqlprojects).",
 	"projects-view-no-project-content": "No projects found in current workspace.\n[Create new](command:projects.new)\n[Open existing](command:projects.openExisting)\nTo learn more about SQL Database projects [read our docs](https://aka.ms/azuredatastudio-sqlprojects).\n",
 	"open-existing-command": "Open existing",
-	"projects.defaultProjectSaveLocation": "Full path to folder where new projects are saved by default."
+	"projects.defaultProjectSaveLocation": "Full path to folder where new projects are saved by default.",
+	"projects.showNotAddedProjectsInWorkspacePrompt": "Always show information message when the current workspace folders contain a project that have not been added to the workspace's projects."
```
Comment (alanrenmsft) [inline extensions/data-workspace/package.nls.json:14]: ... when the current workspace folders contain **projects** that have... instead of **a project**?

File: extensions/data-workspace/src/services/workspaceService.ts [hunk 6]
```diff
@@ -158,6 +159,56 @@ export class WorkspaceService implements IWorkspaceService {
...
+						let containsNotAddedProject = false;
+						for (const projFile of results) {
+							// if any of the found projects aren't already in the workspace's projects, we can stop checking and show the info message
+							if (!projectsInWorkspace.find(p => p.fsPath === projFile)) {
+								containsNotAddedProject = true;
+								break;
+							}
+						}
+
+						if (containsNotAddedProject) {
```
Comment (alanrenmsft) [inline extensions/data-workspace/src/services/workspaceService.ts:195]: did you put this in the wrong place, if this is added here, user will be prompted multiple times.

Comment (alanrenmsft) [reply extensions/data-workspace/src/services/workspaceService.ts:195]: this should be done only once, right?

Comment (kisantia) [reply extensions/data-workspace/src/services/workspaceService.ts:195]: there's a return at the end of this if block so the notification only shows once since the function gets exited already. I put this here so that the function will get finished as soon as possible because the other workspace folders don't need to be checked if a not added project was already found.

**Review by alanrenmsft — APPROVED** [review]

File: extensions/data-workspace/src/services/workspaceService.ts [hunk 7]
```diff
@@ -158,6 +159,56 @@ export class WorkspaceService implements IWorkspaceService {
...
+			const projectsInWorkspace = this.getProjectsInWorkspace();
+			const workspaceFolders = vscode.workspace.workspaceFolders;
+
+			if (workspaceFolders) {
+				for (const extType of supportedProjectExtensions) {
+					// find all project files with extType in each workspace folder
+					for (const folder of workspaceFolders) {
+						// path needs to use forward slashes for glob to work
+						const escapedPath = glob.escapePath(folder.uri.fsPath.replace(/\\/g, '/'));
+						const projFilter = path.posix.join(escapedPath, '**', `*.${extType}`);
```
Comment (SakshiS-harma) [inline extensions/data-workspace/src/services/workspaceService.ts:183]: Can this be modified in such a way that the join would work on a list of supported project extensions instead of one at a time? Just looking of ways to see if we can minimize the triple for-loop execution.

File: extensions/data-workspace/yarn.lock [hunk 8]
```diff
@@ -189,6 +189,27 @@
   dependencies:
     vscode-extension-telemetry "^0.1.6"
 
+"@nodelib/fs.scandir@2.1.4":
```
Comment (SakshiS-harma) [inline extensions/data-workspace/yarn.lock:192]: What do these changes in this file mean?

**Comment by SakshiS-harma** [comment]
Can we add a few tests for the big for-loop section that got added in this change?

File: extensions/data-workspace/yarn.lock (hunk 8 above)
Comment (kisantia) [reply extensions/data-workspace/yarn.lock:192]: these are the dependences of the fast-glob package I added as a dependency for this extension. This file gets updated when you run yarn

File: extensions/data-workspace/src/services/workspaceService.ts [hunk 9]
```diff
@@ -158,6 +159,61 @@ export class WorkspaceService implements IWorkspaceService {
...
+	async checkForProjectsNotAddedToWorkspace(): Promise<void> {
+		const config = vscode.workspace.getConfiguration(constants.projectsConfigurationKey);
+
+		// only check if the user hasn't selected not to show this prompt again
+		if (config[constants.showNotAddedProjectsMessageKey]) {
+			// look for any projects that haven't been added to the workspace
+			const projectsInWorkspace = this.getProjectsInWorkspace();
+			const workspaceFolders = vscode.workspace.workspaceFolders;
+
+			if (workspaceFolders) {
```
Comment (Benjin) [inline extensions/data-workspace/src/services/workspaceService.ts:174]: I think it's generally better to have early escapes rather than indenting the bulk of logic so everything's more readable (logic doesn't wrap as quickly, you don't have to scroll far to the bottom just to find there's no "else")

```
// only check if the user hasn't selected not to show this prompt again
if (!config[constants.showNotAddedProjectsMessageKey]) {
    return;
}

[...]

if (!workspaceFolders) {
    return;
}

[...]
```

**Review by Benjin — APPROVED** [review]

File: extensions/data-workspace/yarn.lock (hunk 8 above)
Comment (SakshiS-harma) [reply extensions/data-workspace/yarn.lock:192]: Sounds good. Thanks!

**Review by SakshiS-harma — APPROVED** [review]

**Review by udeeshagautam — APPROVED** [review]
