### PR TITLE
Set current connection as the selected connection in schema compare dialog

### LINKED ISSUE #21210: Newly added connection doesn't get auto-populated in schema compare dialog
Steps to Reproduce:

1. Open schema compare dialog from within a server/server>database
2. Click ... to open schema compare dialog.
3. Add a new connection using + sign beside the server information.

Expected: New connection gets added to the server dropdown in schema compare dialog and auto populates as the Server information.
Actual: New connection auto populate as the Server information.

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #21210.
Currently while creating a list of servers in the schema compare dialog (for database comparison), the code will either pick the newly added connection or the one with which schema compare extension was started from, to set as the selected server- whichever came later. It should rather follow the hierarchy of picking the newly added connection first, if it doesn't exist then pick the one where SC context was launched from. This PR made the change to select newly added connection first; if not, then select contextual server from the SC was launched.

Before the changes:
scConnectIssue

After the changes:
scIssueFix

Tested other scenarios as well (adding/selecting other servers in the server list).

### CODE REVIEW

File: extensions/schema-compare/src/dialogs/schemaCompareDialog.ts [hunk 1]
```diff
@@ -874,13 +874,13 @@ export class SchemaCompareDialog {
 				finalName = c.options.connectionName;
 			}
 
-			// use previously selected server or current connection if there is one
-			if (endpointInfo && !isNullOrUndefined(endpointInfo.serverName) && !isNullOrUndefined(endpointInfo.serverDisplayName)
-				&& c.options.server.toLowerCase() === endpointInfo.serverName.toLowerCase()
-				&& finalName.toLowerCase() === endpointInfo.serverDisplayName.toLowerCase()) {
+			// use current connection else use previously selected server if there is one
+			if (c.connectionId === this.connectionId) {
```
Comment (kisantia) [inline extensions/schema-compare/src/dialogs/schemaCompareDialog.ts:878]: what does `this.connectionId` refer to in this dialog? Would it help to have separate variables for source and target connectionIds?

Comment (SakshiS-harma) [reply extensions/schema-compare/src/dialogs/schemaCompareDialog.ts:878]: this.connectionId is the current active connection. This is used only when schema compare isn't started from a server or db context. There is target and source endpoint info, so don't need a separate connection id for both. This is majorly used when a new connection is added, and helps to keep track of the sequence/list of the active connections available to SC.

Comment (kisantia) [reply extensions/schema-compare/src/dialogs/schemaCompareDialog.ts:878]: ah ok got it. Can you add a comment about it being the current active connection where `connectionId ` is declared so it's more clear?

**Review by kisantia — APPROVED** [review]

**Review by Benjin — APPROVED** [review]

File: extensions/schema-compare/src/dialogs/schemaCompareDialog.ts [hunk 2]
```diff
@@ -874,13 +874,13 @@ export class SchemaCompareDialog {
...
 				idx = count;
-			}
-			else if (c.connectionId === this.connectionId) {
+			} else if (endpointInfo && !isNullOrUndefined(endpointInfo.serverName) && !isNullOrUndefined(endpointInfo.serverDisplayName)
```
Comment (kburtram) [inline extensions/schema-compare/src/dialogs/schemaCompareDialog.ts:880]: nit: it looks like both the `if` and `else` blocks have the same code.  I think you could combine into a single condition with an `||` operator.

**Review by kburtram — APPROVED** [review]
LGTM
