### PR TITLE
Fix schema compare include/exclude behavior

### LINKED ISSUE #7157: Schema Compare exclude doesn't always exclude the object
If an object is depended on by another object, the change will still be included even if it's unchecked as long as the dependency change is included. 

Current ADS behavior: Even though the two tables are unchecked, they are included in the generated script because the view depends on them
image

In these cases, SSDT doesn't allow an object to be unchecked if there is an included dependency 
image

### PR DESCRIPTION
**Pull request by kisantia**
Fixes #7157. Previously, the schema compare differences table wasn't updating the inclusion state of other differences that were affected by the checking/unchecking of a different row. This fixes that by updating the checkboxes of affected dependencies and also resetting the checkbox state if the include/exclude request failed.

includeExcludeFix

### CODE REVIEW

File: extensions/mssql/src/mssql.d.ts [hunk 1]
```diff
@@ -290,7 +296,7 @@ export interface ISchemaCompareService {
 	schemaCompareGenerateScript(operationId: string, targetServerName: string, targetDatabaseName: string, taskExecutionMode: azdata.TaskExecutionMode): Thenable<azdata.ResultStatus>;
 	schemaComparePublishChanges(operationId: string, targetServerName: string, targetDatabaseName: string, taskExecutionMode: azdata.TaskExecutionMode): Thenable<azdata.ResultStatus>;
 	schemaCompareGetDefaultOptions(): Thenable<SchemaCompareOptionsResult>;
-	schemaCompareIncludeExcludeNode(operationId: string, diffEntry: DiffEntry, IncludeRequest: boolean, taskExecutionMode: azdata.TaskExecutionMode): Thenable<azdata.ResultStatus>;
+	schemaCompareIncludeExcludeNode(operationId: string, diffEntry: DiffEntry, IncludeRequest: boolean, taskExecutionMode: azdata.TaskExecutionMode): Thenable<SchemaCompareIncludExcludeResult>;
```
Comment (udeeshagautam) [inline extensions/mssql/src/mssql.d.ts]: nite : spelling SchemaCompareInclud**e**ExcludeResult

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 2]
```diff
@@ -386,16 +387,63 @@ export class SchemaCompareMainWindow {
...
+							};
+							this.saveExcludeState(dependencyCheckBoxState);
+						}
+					});
+				} else {
+					// failed because of dependencies
+					if (result.blockingDependencies) {
+						// show the first dependent that caused this to fail in the warning message
+						const firstDependentName = this.createName(result.blockingDependencies[0].sourceValue ? result.blockingDependencies[0].sourceValue : result.blockingDependencies[0].targetValue);
+						vscode.window.showWarningMessage(checkboxState.checked ? cannotIncludeMessage + firstDependentName : cannotExcludeMessage + firstDependentName);
```
Comment (udeeshagautam) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts]: Can we use paratermets in loc string to be consistent... also am not sure how "+" would work in all languages if the ordering insentence changes...
localize('schemaCompare.cannotExcludeMessage', "Cannot exclude. Included dependents exist such as {0}", firstDependentName);

Comment (udeeshagautam) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts]: Just to make a note: please make sure we validate again table + index case to make sure in no operation that shows up as blocking dependency

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 3]
```diff
@@ -386,16 +387,63 @@ export class SchemaCompareMainWindow {
...
-				await service.schemaCompareIncludeExcludeNode(this.comparisonResult.operationId, diff, checkboxState.checked, azdata.TaskExecutionMode.execute);
-				this.saveExcludeState(checkboxState);
+				const result = await service.schemaCompareIncludeExcludeNode(this.comparisonResult.operationId, diff, checkboxState.checked, azdata.TaskExecutionMode.execute);
+				if (result.success) {
+					this.saveExcludeState(checkboxState);
+
+					// depencies could have been included or excluded as a result, so save their exclude states
+					result.affectedDependencies.forEach(difference => {
+						// find the row of the difference and set it's checkbox
+						const row = this.findDifferenceRow(difference);
```
Comment (udeeshagautam) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts]: hmm... is it possible to keep a Map <DiffEntry_string, row> where we create the diff entry string with say source_name_target_change_type? Is that possible or has some issues?

I think that will be faster - can take more memory but since it would be just string, not that much I assume.

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 4]
```diff
@@ -386,16 +387,63 @@ export class SchemaCompareMainWindow {
...
+						if (row !== -1) {
+							this.differencesTable.checked = { row: row, columnName: 'Include', checked: difference.included };
+							const dependencyCheckBoxState: azdata.ICheckboxCellActionEventArgs = {
+								checked: difference.included,
+								row: row,
+								column: 2,
+								columnName: undefined
+							};
+							this.saveExcludeState(dependencyCheckBoxState);
```
Comment (udeeshagautam) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts]: good catch on saved state!! :)

File: src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts [hunk 5]
```diff
@@ -189,7 +189,21 @@ export class CheckboxSelectColumn<T extends Slick.SlickData> implements Slick.Pl
...
 		//Ensure that the focus stays correct
-		this._grid.getActiveCellNode().focus();
+		if(this._grid.getActiveCellNode()) {
+			this._grid.getActiveCellNode().focus();
+		}
+	}
+
+	// This call is to handle reactive changes in check box UI
+	// This DOES NOT fire UI change Events
+	reactiveCheckboxCheck(row: number, value: boolean) {
```
Comment (udeeshagautam) [inline src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts]: Not changing name? :) :)

File: src/sql/workbench/browser/modelComponents/table.component.ts [hunk 6]
```diff
@@ -255,10 +256,21 @@ export default class TableComponent extends ComponentBase implements IComponent,
 			this._table.focus();
 		}
 
+		if (this.checked !== undefined) {
+			this.check(this.checked);
```
Comment (udeeshagautam) [inline src/sql/workbench/browser/modelComponents/table.component.ts]: @chlafreniere asked initially if it will be better to have table.checked = list<checkboxInfos> so save multiple calls. I'll do that in the branch in sometime you want to take that.

File: src/sql/workbench/browser/modelComponents/table.component.ts [hunk 7]
```diff
@@ -255,10 +256,21 @@ export default class TableComponent extends ComponentBase implements IComponent,
...
+		}
+
 		this.layoutTable();
 		this.validate();
 	}
 
+	private check(checkInfo: azdata.CheckBoxInfo): void {
+		if (isNullOrUndefined(checkInfo.columnName) || isNullOrUndefined(checkInfo.row)) {
```
Comment (udeeshagautam) [inline src/sql/workbench/browser/modelComponents/table.component.ts]: my bad here but can you please check for row > -1 as well please

Comment (udeeshagautam) [inline src/sql/workbench/browser/modelComponents/table.component.ts]: not sure how I dleted my comment :| ...please add (  || checkInfo.row < 0 || checkInfo.row > this.data.length) also

File: src/sql/workbench/browser/modelComponents/table.component.ts (hunk 6 above)
Comment (udeeshagautam) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: pushed this to other branch

File: extensions/schema-compare/src/schemaCompareMainWindow.ts (hunk 2 above)
Comment (kisantia) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts]: Fixed :)

File: src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts (hunk 5 above)
Comment (kisantia) [reply src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts]: It's fine with me unless someone has a better name for it haha

File: src/sql/workbench/browser/modelComponents/table.component.ts (hunk 6 above)
Comment (kisantia) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: Took the changes from the other branch

File: src/sql/workbench/browser/modelComponents/table.component.ts (hunk 7 above)
Comment (kisantia) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: Got this in the commit from the other branch

File: extensions/schema-compare/src/schemaCompareMainWindow.ts (hunk 3 above)
Comment (kisantia) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts]: Makes sense. Added a map where the key is sourcename_target_name_updateAction_objectType

File: extensions/schema-compare/src/schemaCompareMainWindow.ts (hunk 2 above)
Comment (kisantia) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts]: Yes validated that indexes don't block including/excluding a table after the update to SqlToolsService

File: src/sql/azdata.d.ts [hunk 8]
```diff
@@ -3086,9 +3086,16 @@ declare module 'azdata' {
 		ariaColumnCount?: number;
 		ariaRole?: string;
 		focused?: boolean;
+		checked?: CheckBoxInfo[];
```
Comment (alanrenmsft) [inline src/sql/azdata.d.ts]: IIUC, you want to do partial data update. I'd recommend not to do this as this is very specific to checkbox. I think we should introduce a method updateCells(cellInfos:<row, column, value>[]). for now you only need to implement the checkbox related logic.

File: src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts [hunk 9]
```diff
@@ -189,7 +189,21 @@ export class CheckboxSelectColumn<T extends Slick.SlickData> implements Slick.Pl
...
+		value ? this._selectedCheckBoxLookup[row] = true : delete this._selectedCheckBoxLookup[row];
+
+		// update row to call formatter
+		this._grid.updateRow(row);
+
+		// ensure that grid reflects the change
+		this._grid.scrollRowIntoView(row);
```
Comment (alanrenmsft) [inline src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts]: have you tested the scenario where you have too many rows to fit within one screen and the affected rows are scattered on different places. I believe in that case, you will see the table to be refreshed multiple times and eventually focus goes back to the original place.

File: src/sql/azdata.d.ts (hunk 8 above)
Comment (kisantia) [reply src/sql/azdata.d.ts]: I thought there wasn't a way for an extension to call a method of a component. I can change this property to a more generic one for all TableCells, but is that what you meant?

File: src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts (hunk 9 above)
Comment (kisantia) [reply src/sql/base/browser/ui/table/plugins/checkboxSelectColumn.plugin.ts]: Yes. The table doesn't get refreshed multiple times. This example affects 3 rows, but the table doesn't show as refreshing multiple times.
includeExcludeBigTable

**Comment by alanrenmsft** [comment]
since we are very close to the final code freeze and the feature is only used by schema compare, I am ok with merge as is and open an issue to track the refactor work after the nov release.
