### PR TITLE
fix query result grid shortcut keys

### LINKED ISSUE #3341: Add Shortcut for Copying Results with Headers
- Azure Data Studio Version: 0.32.9

Copying with Headers is available via the context menu, but it'd be beneficial to also have access to it through a keyboard shortcut.  In SQL Server Management Studio, the shortcut is ctrl+shift+c.

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #3341

There were some keybindings for grid commands but has stopped working after the numerous refactorings over the years, especially now that we also have query result grid in notebook, I redesigned the keybindings for grid commands that works for both query editor and notebook.

The `Select all` command is not customizable because it is implemented directly in SlickGrid, I can fix it in future if I see feature request for it.

Before:
image

image

After:
image

image

### CODE REVIEW

File: src/sql/workbench/services/componentContext/browser/componentContextService.ts [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+		return {
+			componentContextKeyService: service,
+			dispose: () => {
+				this._components.delete(id);
+				service.dispose();
+			}
+		};
+	}
+
+	private getActiveComponent<T>(type: ComponentType, elementGetter: (component: T) => HTMLElement): T | undefined {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/componentContext/browser/componentContextService.ts:98]: doc comment here explaining this please

**Review by Charles-Gagnon — APPROVED** [review]
