### PR TITLE
ML- Fixed the issue with adding and removing flex container

### LINKED ISSUE #13468: show more/less links on Machine Learning dashboard stop working after multiple clicks
works on latest stable release, but not on insider builds
image

### PR DESCRIPTION
**Pull request by llali**
This PR fixes #13468

### CODE REVIEW

**Review by halerankin — APPROVED** [review]

File: extensions/machine-learning/src/views/widgets/dashboardWidget.ts [hunk 1]
```diff
@@ -237,12 +238,10 @@ export class DashboardWidget {
...
 					light: this.asAbsolutePath('images/light/showLess.svg'),
 				};
-				parentPanel.addItem(morePanel, {
-					CSSStyles: morePanelStyle
-				});
+				morePanel.updateCssStyles(Object.assign({}, morePanelStyle, { 'visibility': 'visible' }));
 			} else {
 				showMoreComponent.label = constants.showMoreTitle;
-				parentPanel.removeItem(morePanel);
+				morePanel.updateCssStyles(Object.assign({}, morePanelStyle, { 'visibility': 'hidden' }));
```
Comment (alanrenmsft) [inline extensions/machine-learning/src/views/widgets/dashboardWidget.ts:244]: I do see an accessibility issue, you also have to set the aria-hidden to true/false otherwise screen reader is still able to reach these elements.
