### PR TITLE
Notebook UI - Fixes navigation offset

### LINKED ISSUE #10062: Navigation offset is not working
Azure Data Studio Version: Release 1.17

Navigation to sections is not working properly. The offset calculation is not accurate and sections are not visible when scrolling.

Steps to Reproduce:

Use the following file to reproduce the issue.
[sample.zip](https://github.com/microsoft/azuredatastudio/files/4495320/sample.zip)

1.  Open notebook on ADS
2.  Click on the multiple links to verify if scroll goes to the right section.

### PR DESCRIPTION
**Pull request by halerankin**
Replaced scrollTop with getBoundingClientRect().top. Created an offset that accounts for the combined height of the tab bar and action bar at top.

This PR addresses #10062

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 1]
```diff
@@ -664,10 +664,14 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
...
 	navigateToSection(id: string): void {
 		id = id.toLowerCase();
+		let elBody: HTMLElement = document.body;
+		let tabBar = elBody.querySelector('.title.tabs') as HTMLElement;
+		let actionBar = elBody.querySelector('.editor-toolbar.actionbar-container') as HTMLElement;
 		let section = find(this.getSectionElements(), s => s.relativeUri && s.relativeUri.toLowerCase() === id);
 		if (section) {
 			// Scroll this section to the top of the header instead of just bringing header into view.
-			let scrollTop = section.headerEl.offsetTop;
+			let chromeHeight: number = tabBar.scrollHeight + actionBar.scrollHeight + 10;
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:673]: to prevent some potential undefined exceptions, let's make sure that the tabBar and actionBar objects exist before accessing the scrollHeight properties.

Comment (halerankin) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts]: Fixed.
