### PR TITLE
Stop watching for sqlproj updates after the file is closed

### LINKED ISSUE #12241: Reload project popup shows after sqlproj is closed
Steps to Reproduce:

1. Right click on an opened project and select "Edit .sqlproj File"
2. close the opened editor with the .sqlproj opened
3. Add or delete a file or database reference (something that would update the .sqlproj)

Expected: nothing happens, the project tree should be updated as expected
Actual: project tree is updated, but then a popup shows asking if you want to reload the project. This message should only show when the .sqlproj is edited when it gets opened. It shouldn't show up after the file is closed

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #12241

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -450,6 +452,15 @@ export class ProjectsController {
 					this.reloadProject(projectFileUri);
 				}
 			});
+
+			// stop watching for changes to the sqlproj after it's closed
+			const closeSqlproj = vscode.workspace.onDidCloseTextDocument((d) => {
```
Comment (SakshiS-harma) [inline extensions/sql-database-projects/src/controllers/projectController.ts:457]: What happens if the sqlproj file is still open, but the project has been closed and removed from the explorer viewlet?

Comment (kisantia) [reply extensions/sql-database-projects/src/controllers/projectController.ts:463]: fixed to remove watcher when project is closed

**Review by Benjin — APPROVED** [review]

**Review by SakshiS-harma — APPROVED** [review]
