### PR TITLE
Fix importing new project from server dashboard

### LINKED ISSUE #11765: Import Db project shows in Server Dashboard toolbar and fails when using
- Azure Data Studio Version:

Steps to Reproduce:

1. Open the server dashboard - it shows menu item new db project
2. click it - it doesnt not ask for which DB to use and directly  prompts to create a project named "DatabaseProjetnull"
3. go through the flow with or without changing the name : fails to create project

NOTE that one from database dashboard and command pallet works fine - specifically server dashboardone fails

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #11765. This was caused by a closing curly bracket on the wrong line, probably from a merge conflict in this refactoring PR #11184. Also fixes another bug introduced from that PR which caused the databases to be listed even if the connection from the connection dialog already specified the db.

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -689,19 +689,19 @@ export class ProjectsController {
 			if (connection.options['database']) {
 				database = connection.options['database'];
 			}
+		}
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/controllers/projectController.ts:692]: this one? nice catch!!
