### PR TITLE
Notebooks: Fix for dispose method of undefined when running empty python cell

### LINKED ISSUE #4842: Notebooks: Run Empty Cell, Get Cannot read property 'dispose' of undefined Error
Choose Python 3 as the kernel.
Attempt to run an empty cell.
Following error message will appear:
image

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #4842, which is a regression.

### CODE REVIEW

File: src/sql/parts/notebook/models/cell.ts [hunk 1]
```diff
@@ -490,7 +490,9 @@ export class CellModel implements ICellModel {
 
 	// Dispose and set current future to undefined
 	private disposeFuture() {
-		this._future.dispose();
+		if (this._future) {
+			this._future.dispose();
+		}
 		this._future = undefined;
```
Comment (corivera) [inline src/sql/parts/notebook/models/cell.ts]: Technically could move this assignment into the if statement.
