### PR TITLE
Fix #3736 Notebook: cannot connect to SQL big data cluster due to empty config.json file

### LINKED ISSUE #3736: Notebook: cannot connect to SQL big data cluster due to empty config.json file
This affects the January release.
Steps to Reproduce:

1. Delete the `%home%/.sparkmagic` folder if it exists
2. Open Azure Data Studio, New Notebook, PySpark3, and select a connection
3. Run `print (1)`
Expected: works and creates a session
Actual: Fails due to SSL error

Root cause is that the Notebook code to create a config.json with `ignore_ssl_errors=True` was not ported over. We need to fix ASAP as this blocks usage against SQL Server big data cluster endpoints.

### PR DESCRIPTION
**Pull request by kevcunnane**
- Writing the config file in the core for now, will look to move to the extension in Feb release

### CODE REVIEW

File: src/sql/parts/notebook/models/sparkMagicContexts.ts [hunk 1]
```diff
@@ -107,31 +143,28 @@ export class SparkMagicContexts {
...
 		return {
-				otherConnections: activeConnections,
-				defaultConnection: defaultConnection
+			otherConnections: activeConnections,
+			defaultConnection: defaultConnection
 		};
 	}
 
-	public static async configureContext(options: INotebookModelOptions): Promise<object> {
+	public static async configureContext(): Promise<object> {
```
Comment (kevcunnane) [inline src/sql/parts/notebook/models/sparkMagicContexts.ts]: This is the key change

File: src/sql/parts/notebook/models/sparkMagicContexts.ts [hunk 2]
```diff
@@ -76,13 +112,13 @@ export class SparkMagicContexts {
...
 		let activeConnections: IConnectionProfile[] = await connectionService.getActiveConnections();
 		// If no connections exist, only show 'n/a'
-        if (activeConnections && activeConnections.length > 0) {
-            // Remove all non-Spark connections
-            activeConnections = activeConnections.filter(conn => conn.providerName === notebookConstants.hadoopKnoxProviderName);
-        }
-        if (activeConnections.length === 0) {
-            return SparkMagicContexts.DefaultContext;
-        }
+		if (activeConnections && activeConnections.length > 0) {
```
Comment (kevcunnane) [inline src/sql/parts/notebook/models/sparkMagicContexts.ts]: I ran formatter when copying in the JSON, seems to have altered these sections. Apologies for the confusion.
