### PR TITLE
Fix duplicate db references being allowed

### LINKED ISSUE #12794: duplicate database references shouldn't be allowed
image

Happens when a project already with database references is loaded, then an already existing db reference tries to get added. The same reference isn't found on Mac because the slashes are in a different direction when read from the sqlproj

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #12794. Fixes two things: 
1. Wasn't checking if project reference already exists before adding
2. On mac, duplicate references weren't being caught if a project already with a db reference was loaded because the uri read from the sqlproj had Window's slashes. Fix is to make sure slashes are all consistent when doing the comparison

### CODE REVIEW

File: extensions/sql-database-projects/src/models/project.ts [hunk 1]
```diff
@@ -621,7 +627,7 @@ export class Project {
 	}
 
 	private databaseReferenceExists(entry: IDatabaseReferenceProjectEntry): boolean {
-		const found = this.databaseReferences.find(reference => reference.fsUri.fsPath === entry.fsUri.fsPath) !== undefined;
+		const found = this.databaseReferences.find(reference => reference.pathForSqlProj() === entry.pathForSqlProj()) !== undefined;
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/models/project.ts:630]: While savng the ref to file or such this wont have any impact/change right?

**Review by udeeshagautam — APPROVED** [review]
Not for this PR sice its time sensitive but we should add a test for this one right?

**Comment by kisantia** [comment]
opened #12809 to track adding more tests for this. There's already a test for duplicate refs, but it doesn't test after reloading a project and is only testing a dacpac without slashes in the filepath ('test.dacpac')
