### PR TITLE
limit the data size for chart rendering

### LINKED ISSUE #14335: ADS crashes when chart button is clicked in the results pane
Issue Type: <b>Bug</b>

1. Execute any query that returns tabular data
2. Click on the Chart button/icon to the right of the results pane
3. ADS pops up a a little window on bottom right saying it recommends installing some visualization extension and freezes. The buttons in the dialog box ("Install All" and "Show Recommendations") do not respond to mouse clicks. ADS becomes unresponsive to all user interaction. After a while another dialog pops up with options for "Reopen", "Keep Waiting" and "Close". (I do not see any recommended data visualization extensions in the extension list either.)

It has had this behavior out of the box. Installation and removal of any extensions have had no affect on this behavior.

Azure Data Studio version: azuredatastudio 1.25.3 (b277eafb8f5328ea26c6edfddd1999292ac27937, 2021-02-09T23:10:35.151Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz (4 x 3096)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|4.42GB (1.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.2.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.8.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.5.0
sql-database-projects|Mic|0.5.1
whoisactive|Mic|0.1.4
vscodeintellicode|Vis|1.2.1

</details>

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #14335 

Right now we are not limiting the size of the data we pass to chartjs to render charts, as described in the issue, this will cause the app to freeze or crash.

I experimented myself locally and I found 300 is a reasonable number that the charts works with no obvious lag.
I've made it configurable so that users can adjust this number based on their local environment, also provided an option to suppress this notification. 

image

### CODE REVIEW

File: src/sql/workbench/contrib/charts/browser/chartView.ts [hunk 1]
```diff
@@ -2,33 +2,36 @@
  *  Copyright (c) Microsoft Corporation. All rights reserved.
  *  Licensed under the Source EULA. See License.txt in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
-
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/charts/browser/chartView.ts:5]: I reorganized the imports

File: src/sql/workbench/contrib/charts/browser/chartView.ts [hunk 2]
```diff
@@ -228,15 +234,33 @@ export class ChartView extends Disposable implements IPanelView {
...
 			let batch = this._queryRunner.batchSets[this._currentData.batchId];
 			if (batch) {
 				let summary = batch.resultSetSummaries[this._currentData.resultId];
 				if (summary) {
-					this._queryRunner.getQueryRows(0, summary.rowCount, this._currentData.batchId, this._currentData.resultId).then(d => {
+					const maxRowCount = this._configurationService.getValue<IChartsConfiguration>('charts').maxRowCount;
+					const storageKey = 'charts/ignoreMaxRowCountExceededNotification';
+
+					if (summary.rowCount > maxRowCount) {
+						this._adsTelemetryService.sendTelemetryEvent('charts.maxRowCountExceeded');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/charts/browser/chartView.ts:249]: Do we have an event for every time someone charts something too? MIght be good to see what % of the time this happens

(what I'd suggest is that we either add/modify an event that is sent every time someone shows the graph and include a boolean property `maxRowCountExceeded` to make that easier to figure out)

Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/charts/browser/chartView.ts:249]: Try not to use `sendTelemetryEvent`. You should generally be using the common schema that I defined (see OneNote for details) aka send/create Action/View/Error

So for this along with what I suggested above I would create an action event `showQueryResultsGraph` or something (make sure to put that in TelemetryKeys.ts) and then include the `maxRowCountExceeded` property on it using `withProperties`

File: src/sql/workbench/contrib/charts/browser/charts.contribution.ts [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+
+const chartsConfiguration: IConfigurationNode = {
+	id: 'charts',
+	type: 'object',
+	title: nls.localize('chartsConfigurationTitle', "Charts"),
+	properties: {
+		'charts.maxRowCount': {
+			type: 'number',
+			default: 300,
+			description: nls.localize('charts.maxRowCountDescription', "Maximum allowed rows for charts to render, this is introduced to prevent the application hang. If exceeded, ADS will only take the first N rows for chart rendering.")
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/charts/browser/charts.contribution.ts:20]: Would suggest not using phrases like `prevent the application hang` - instead maybe something like `The maximum number of rows for Query Results charts to display. Warning: increasing this may impact performance.`

File: src/sql/workbench/contrib/charts/browser/charts.contribution.ts [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+import { Extensions, IConfigurationRegistry, IConfigurationNode } from 'vs/platform/configuration/common/configurationRegistry';
+import { Registry } from 'vs/platform/registry/common/platform';
+import * as nls from 'vs/nls';
+
+const configurationRegistry = Registry.as<IConfigurationRegistry>(Extensions.Configuration);
+
+const chartsConfiguration: IConfigurationNode = {
+	id: 'charts',
+	type: 'object',
+	title: nls.localize('chartsConfigurationTitle', "Charts"),
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/charts/browser/charts.contribution.ts:15]: I wonder if this should be put under query editor settings along with other stuff like default chart type.

Although now that notebooks renders charts too I wonder if we should just split these into their own section `Query Results Charts` or something...

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/sql/workbench/contrib/charts/browser/charts.contribution.ts [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+ *--------------------------------------------------------------------------------------------*/
+
+import { Extensions, IConfigurationRegistry, IConfigurationNode } from 'vs/platform/configuration/common/configurationRegistry';
+import { Registry } from 'vs/platform/registry/common/platform';
+import * as nls from 'vs/nls';
+
+const configurationRegistry = Registry.as<IConfigurationRegistry>(Extensions.Configuration);
+
+const chartsConfiguration: IConfigurationNode = {
+	id: 'charts',
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/charts/browser/charts.contribution.ts:13]: builtinCharts? Same with loc ids

File: src/sql/workbench/contrib/charts/browser/utils.ts [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+import * as nls from 'vs/nls';
+import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
+import { INotificationService, Severity } from 'vs/platform/notification/common/notification';
+import { IStorageService, StorageScope, StorageTarget } from 'vs/platform/storage/common/storage';
+
+/**
+ * Gets the max allowed row count for chart rendering.
+ */
+export function getChartMaxRowCount(configurationService: IConfigurationService): number {
+	return configurationService.getValue<IChartsConfiguration>('charts').maxRowCount;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/charts/browser/utils.ts:16]: Would suggest making a const for this ID so we don't accidently update it and forget to change this

File: src/sql/workbench/contrib/preferences/browser/sqlSettingsLayout.ts [hunk 7]
```diff
@@ -36,6 +36,11 @@ let sqlTocItems: ITOCEntry<string>[] = [{
 			id: 'data/profiler',
 			label: localize('profiler', "Profiler"),
 			settings: ['profiler.*']
+		},
+		{
+			id: 'data/charts',
+			label: localize('charts', "Charts"),
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/preferences/browser/sqlSettingsLayout.ts:42]: Built-In Charts?

**Review by Charles-Gagnon — APPROVED** [review]
