### PR TITLE
Open external for files from results serialize

### LINKED ISSUE #8218: Excel files open in editor instead of excel after exporting result set
- Azure Data Studio Version: 1.13.0

Steps to Reproduce:
Export result set to excel (via the "Save As Excel"-Button on the right). In the notification that shows after the file has been saved click "Open file".
I get a new tab in Azure Data Studio and the message "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?".
Clicking on the text link to open the file anyways shows the file as text in the editor instead of opening excel.

### PR DESCRIPTION
**Pull request by anthonydresser**
This is a behavior change but this is reverting to behavior before ~3 months ago.

fixes #8218

### CODE REVIEW

File: src/sql/workbench/common/workspaceActions.ts [hunk 1]
```diff
@@ -27,6 +27,6 @@ export class OpenFileInFolderAction extends Action {
 	}
 
 	run() {
-		return this.openerService.open(URI.file(this.path));
+		return this.openerService.open(URI.file(this.path), { openExternal: true });
```
Comment (kburtram) [inline src/sql/workbench/common/workspaceActions.ts]: I think previously (~a few months ago), CSV\XML\JSON would open in VS Code and XLSX would open externally.  Perhaps this was because vscode was the default file handler for these extensions?  In any case, I think we auto-open those files in any case, so the prompt was redundant for non-XLSX in all my testing.  

Do you know if this changes the CSV\XML\JSON behavior compared to a few months ago?  It likes like it will restore the XLSX behavior.

Comment (anthonydresser) [reply src/sql/workbench/common/workspaceActions.ts]: this will restore the behavior is was before a few months ago (when they introduced the openerservice), basically it always tried to open it externally and let the os decide who to open it with.

**Comment by asjones987** [comment]
Should this have been fixed in the December 2019 release that just came out? I figured it wold but does not look like it.

**Comment by anthonydresser** [comment]
@asjones987 no this didn't make it into our december release, this is in insiders and will be in our next release.
