### PR TITLE
make group container header accessible

### LINKED ISSUE #7601: A11y_AzureDataStudio_ServiceSettings_Keyboard:Expand/collapse button is not accessible by the keyboard.
"[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHubTags:** #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG2.1.1;#DesktopApp;#Keyboard; #Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 32df727
Date: 2019-10-08T19:18:43.743Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Repro Steps:**

1.	Install /Launch the application Azure data studio.
2.	Navigate to connections and click on more action button.
3.	Select “Deploy SQL Server big data cluster” from more action drop down.
4.	Click on “Deploy SQL Server big data cluster”.
5.	Check the check box I accept in the “select the deployment option” screen and click on
        select button.
6.	Select any block and click on next button and again click on next button.
7.	Enter password and confirm password and click on next button.
8.	Navigate on the "service setting" screen using tab navigation.
9.    Check expand/collapse button is actionable by the keyboard or not.

**Actual:**
Expand/collapse button is not accessible by the keyboard.

**Expected:**
Keyboard focus should go on expand/collapse button and accessible by the keyboard.

**Same issue observed for the below scenario:**
**1.Summary:**
1.	Install /Launch the application Azure data studio.
2.	Navigate to connections and click on more action button.
3.	Select “Deploy SQL Server big data cluster” from more action drop down.
4.	Click on “Deploy SQL Server big data cluster”.
5.	Check the check box I accept in the “select the deployment option” screen and click on select button.
6.	Select any block and click on next button and again click on next button.
7.	Enter password and confirm password and click on next button and again click on next button.
8.	Verify that all the elements of " Summary" are accessible and MAS Compliant.

**User Impact:**
Keyboard only user get difficulty to access the control.

**Attachment for Reference**
[7601_A11y_AzureDataStudio_ServiceSettings_Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3711281/7601_A11y_AzureDataStudio_ServiceSettings_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by alanrenmsft**
added proper tabIndex, role, and aria-expanded attributes for the group container header.

setting value to null will clear the attribute when not needed, but for tabindex I had to use -1 to make it not keyboard focusable.

also added keyboard handler

enter/space will toggle the collapsed state
left: collapse the container
right: expand the container

This PR fixes #7601

### CODE REVIEW

File: src/sql/workbench/browser/modelComponents/groupContainer.component.ts [hunk 1]
```diff
@@ -14,11 +14,14 @@ import { GroupLayout, GroupContainerProperties } from 'azdata';
...
 import { endsWith } from 'vs/base/common/strings';
+import { StandardKeyboardEvent } from 'vs/base/browser/keyboardEvent';
+import { KeyCode } from 'vs/base/common/keyCodes';
+import * as DOM from 'vs/base/browser/dom';
 
 @Component({
 	selector: 'modelview-groupContainer',
 	template: `
-		<div *ngIf="hasHeader()" [class]="getHeaderClass()" (click)="changeState()">
+		<div *ngIf="hasHeader()" [class]="getHeaderClass()" (click)="changeState()" [tabindex]="isCollapsible()? 0 : -1" [attr.role]="isCollapsible() ? 'button' : null" [attr.aria-expanded]="isCollapsible() ? !collapsed : null">
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/groupContainer.component.ts]: I assume you verified null works as expected here? For Element.setAttribute it warns that null would be converted to the string null which wouldn't be what we want : https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

(I don't know what angular is using for setting the value though). Regardless I've always just used an empty string instead for clearing a value - that's a closer representation of what we actually want to happen anyways so I generally prefer that.

Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/groupContainer.component.ts]: yes, tested. here are the screenshots.

collapsable:
Screen Shot 2019-11-24 at 12 17 57 PM

Screen Shot 2019-11-24 at 12 17 42 PM

non-collapsable:

Screen Shot 2019-11-24 at 12 19 56 PM
Screen Shot 2019-11-24 at 12 20 03 PM
