### PR TITLE
set focus to default cards when loaded

### LINKED ISSUE #7673: A11y_AzureDataStudio_Selectthedeploymentoption_ScreenReader:NVDA does not announce the tittle of the screen as soon as it is landed on the screen.
**GitHubTags:** #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG1.3.1;#DesktopApp;#Win32;#NVDA;
**Environment Details:**
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 32df727
Date: 2019-10-08T19:18:43.743Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
**Repro Steps:**
1.Install /Launch the application Azure data studio.
2.Navigate to connections and click on more action button.
3.Select “Deploy SQL Server big data cluster” from more action drop down.
4.Click on “Deploy SQL Server big data cluster”.
5. "Select the deployment option" screen gets open.
6. Start NVDA and navigate with the help of up and down arrow and observe the announcement.
**Actual:**
NVDA does not announce the tittle of the screen as soon as it is landed on the screen.
**Expected:**
NVDA should announce the new screen name as soon as it is landed on the new screen.
**User Impact:**
Screen reader User will not understand weather they have landed on new screen or not. 

**Attachment for Reference:**
[7673_A11y_AzureDataStudio_Selectthedeploymentoption_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3717400/7673_A11y_AzureDataStudio_Selectthedeploymentoption_ScreenReader.pptx)
Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by alanrenmsft**
set focus to the proper card after loading so that the dialog/wizard will be announced properly

This PR fixes #7673

### CODE REVIEW

File: src/sql/workbench/browser/modelComponents/card.component.ts [hunk 1]
```diff
@@ -53,6 +54,12 @@ export default class CardComponent extends ComponentWithIconBase implements ICom
 		this.baseDestroy();
 	}
 
+	focus() {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/card.component.ts]: void return type
