### PR TITLE
Hide refresh context menu action on disconnected connections

### LINKED ISSUE #1866: Refresh action should work on disconnected connection or not be shown
- SQL Operations Studio Version:

Steps to Reproduce:
- Open Ops Studio
- Right-click on a connection and choose "Refresh"

Expected:
- As connection wasn't in a connected state, it should be connected & expanded
- Alternatively, this action shouldn't be shown for disconnected DBs
Actual:
- It's a no-op with no clear user output.

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #1866

The refresh action doesn't do anything when a connection profile is disconnected and it also doesn't show any indicator that it didn't do anything. By hiding the action we can make it clear that the action only refreshes connected profiles and not disconnected profiles.

Disconnected profiles don't show the refresh context menu action:
image

Connected profiles show the refresh context menu action:
image

### CODE REVIEW

File: src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts [hunk 1]
```diff
@@ -126,14 +126,15 @@ export class ServerTreeActionProvider {
...
+		const isProfileConnected = this._connectionManagementService.isProfileConnected(context.profile);
+		if (isProfileConnected) {
 			actions.push(this._instantiationService.createInstance(DisconnectConnectionAction, DisconnectConnectionAction.ID, DisconnectConnectionAction.LABEL, context.profile));
 		}
 		actions.push(this._instantiationService.createInstance(EditConnectionAction, EditConnectionAction.ID, EditConnectionAction.LABEL, context.profile));
 		actions.push(this._instantiationService.createInstance(DeleteConnectionAction, DeleteConnectionAction.ID, DeleteConnectionAction.DELETE_CONNECTION_LABEL, context.profile));
 
 		// Contribute refresh action for scriptable objects via contribution
-		if (!this.isScriptableObject(context)) {
+		if (isProfileConnected && !this.isScriptableObject(context)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/serverTreeActionProvider.ts:137]: I'm very confused by the use of "isScriptableObject" to determine whether something can be refreshed, so that might be something to look at in case there's something not quite correct there.

**Review by Charles-Gagnon — APPROVED** [review]
