### PR TITLE
Fixed tooltip not hiding when scrolling through graph control.

### LINKED ISSUE #18283: Tooltip still shows when the user has scrolled away from Execution Plan
Steps to repro:

1. Hover on a node.
2. Scroll using mouse wheel.
3. Tooltip is still shown on screen. Ideally, it should be hidden.

image

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #18283

### CODE REVIEW

**Review by lewis-sanchez — APPROVED** [review]

File: src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts [hunk 1]
```diff
@@ -391,9 +391,14 @@ export class QueryPlan2 implements ISashLayoutProvider {
 			 * use the scroll bars.
 			 */
 			diagramContainer.addEventListener('wheel', e => {
+				this._parent.scrollTop += e.deltaY;
+				//Hiding all tooltips when we scroll.
+				const element = document.getElementsByClassName('mxTooltip');
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:396]: can we make the class name more specific for query plan graph?

**Review by alanrenmsft — APPROVED** [review]
