### PR TITLE
Bdc wizard pages now track all components in wizard.InputCompnentsInfo

### LINKED ISSUE #13020: Cluster Settings Page is broken on BDC wizard.
Start a BDC wizard based deployment and navigate to the clusters settings page. The page fails to load and this exception is seen on the console:

[98041:1021/130655.985068:INFO:CONSOLE(44)] "TypeError: Cannot read property 'component' of undefined
	at processPasswordField (/Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:474:83)
	at processField (/Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:291:13)
	at processFields (/Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:221:15)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.createSection (/Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:186:9)
	at async /Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/deployClusterWizard/pages/clusterSettingsPage.js:204:40", source: file:///Users/arvranmac/git/ads/out/vs/workbench/api/browser/mainThreadExtensionService.js (44)

This seems to have come broken with recent changes in processPasswordField. However, the bug is not with the new code but that the changes exposed a pre-existing bug in setup of the cluster settings page.

### PR DESCRIPTION
**Pull request by ranasaria**
**The issue:** 
The following lines: https://github.com/microsoft/azuredatastudio/blob/bug/12082/extensions/resource-deployment/src/ui/modelViewUtils.ts#L569-#L570
were trying to get the textField that was just created for the password field from the context.inputComponents collection. 
The clusterSettingsPage (and all other pages of BDC) maintain two inputComponents collections: one for the whole wizard and one for each page. When a page exits, the page code copies over all the inputComponents of the page over to this collection for the wizard.

The clusterSettingsPage sets the wizard's inputComponents collection into the context when the section context is created, however, in the callback of onNewInputComponentCreated, it only updates the inputComponents collection for that page, so the code at line 570(
https://github.com/microsoft/azuredatastudio/blob/bug/12082/extensions/resource-deployment/src/ui/modelViewUtils.ts#L569-#L570)
does not find the passwordInput in the inputComponents collection, because it got added to the page's inputComponents Collection and got looked up from the wizard's inputComponents collection.

**The fix:**
The fix for the bug is just to return the input from the processTextField and use it in processPasswordField.

However, the oddity of handling of the inputComponents collections in the BDC pages is a ticking bomb, so I am also changing so that onNewInputComponentCreated API in those pages, we update both the page's inputComponents collection as well the wizard's inputComponents collection.

This PR fixes #13020

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
It's generally useful to include a short description of what was broken and how you fixed it for more complex fixes like this where it's not obvious what the problem was immediately

File: extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts [hunk 1]
```diff
@@ -234,7 +235,8 @@ export class ClusterSettingsPage extends WizardPageBase<DeployClusterWizard> {
 					self.wizard.registerDisposable(disposable);
 				},
 				onNewInputComponentCreated: (name: string, inputComponentInfo: InputComponentInfo): void => {
-					this.inputComponents[name] = { component: inputComponentInfo.component };
+					this.inputComponents[name] = inputComponentInfo;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts:238]: Hm, are you sure this is working? Passing in functions like this generally is going to have the wrong "this" context - hence capturing it in self.

**Review by Charles-Gagnon — COMMENTED** [review]
Fix the hygiene error too

File: extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts:238]: I will move the function out so that it is not tied to the 'this' context at all. There is no need for it to be an instance method.

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts]: done.

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/deployClusterWizard/pages/clusterSettingsPage.ts]: Yeah that's true - I always get those mixed up. Lambda functions shouldn't require using self

**Comment by Charles-Gagnon** [comment]
I still don't know exactly what the issue is and how this is fixing it - could you please explain?

**Comment by ranasaria** [comment]
> I still don't know exactly what the issue is and how this is fixing it - could you please explain?

Put in a detailed explanation in the description of this PR. My bad that i thought that the issue was self-evident from the call stack in the bug and my code changes.

File: extensions/resource-deployment/src/ui/deployClusterWizard/pages/azureSettingsPage.ts [hunk 2]
```diff
@@ -133,7 +133,8 @@ export class AzureSettingsPage extends WizardPageBase<DeployClusterWizard> {
 					self.wizard.registerDisposable(disposable);
 				},
 				onNewInputComponentCreated: (name: string, inputComponentInfo: InputComponentInfo): void => {
-					this.inputComponents[name] = { component: inputComponentInfo.component };
+					self.inputComponents[name] = inputComponentInfo;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/deployClusterWizard/pages/azureSettingsPage.ts:136]: So why do we even need the inputComponents array anymore if it's just going to be kept up to date with wizard.inputComponents? Seems like we only need the one

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/deployClusterWizard/pages/azureSettingsPage.ts:136]: Maybe, but I do not want to expand the scope of those changes here for a quick bug fix. Using the page's inputComponents, the model values get updated at end of each page which gets potentially used in other pages. We will have to track those usages down. I can eliminate the page-specific inputComponents and update the model values at the end of each page using the inputComponents from the wizard. That will eliminate the 2nd copy without much risk with the only down side being that we are populating model values after 2nd page we are re-populating the already populated values from 1st page.


As I said before we can definitely do a lot of cleanup in the BDC code. An alternative would be to do the absolutely minimal fix of just making the change to modelviewutils.

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/resource-deployment/src/ui/deployClusterWizard/pages/azureSettingsPage.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/deployClusterWizard/pages/azureSettingsPage.ts:136]: Sounds good. I agree going through and cleaning this up would be nice but that can be done later if needed.

**Comment by Charles-Gagnon** [comment]
@ranasaria Merged this in since it's blocking an investigation I need to do
