### PR TITLE
fixes the contrast ratio for hoverable list items in the welcome page new button dropdown

### LINKED ISSUE #10644: A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_Usability: The data in the drop down are not visible when the theme are applied.
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev4;#A11yTCS;#A11yUsable;#Benchmark;#DesktopApp;#SQL Azure Data Studio;#FTP;#STP;#HighContrast;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Pre-Requisite:** : enable theme  solarized light

**Repro Steps:**
1 .Launch Azure Data Studio Insiders application.
2 . If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3 .Tab to Preview button and press enter.
4 .Apply the theme quite light and solarized light

**Actual:**
Issue1:
The items under dropdown new are not visible when navigated to each of them.

Issue2:
When color theme high contrast is applied the drop-down new is not recognizable as a drop down. 

**Expected:**
Issue1:
The items under dropdown should be  visible when navigated to each of them.

Issue2:
When color theme high contrast is applied the drop-down should be  recognizable as a drop down

**User Impact:**
Keyboard and low vision users will face difficulty in viewing the data.

**Attachment link for Reference:**
Screenshot (150)
Screenshot (151)

### PR DESCRIPTION
**Pull request by v-bbrady**
This PR fixes the issue of the dropdown not be recognizable as a dropdown as well as some focusing color issues on the welcome page.

This PR fixes  #10644

### CODE REVIEW

**Comment by alanrenmsft** [comment]
why is this PR closed?

**Comment by Charles-Gagnon** [comment]
@v-bbrady Could you also make sure that when you open PRs the title is more descriptive and succinct? Those will typically end up being the commit messages into master so having a bunch of messages that all start with `bbrady/` and contain unneeded information like the issue # being fixed is just distracting. You can use the description box to fill in more detailed information as needed.

File: src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts [hunk 1]
```diff
@@ -1037,26 +1042,27 @@ registerThemingParticipant((theme, collector) => {
 		collector.addRule(`.monaco-workbench .part.editor > .content .welcomePageContainer .ads-homepage .icon-arrow-down:before { color: ${buttonForegroundColor};}`);
 		collector.addRule(`.monaco-workbench .part.editor > .content .welcomePageContainer .ads-homepage .extension-pack-body { color: ${buttonForegroundColor};}`);
 		collector.addRule(`.monaco-workbench .part.editor > .content .welcomePageContainer .ads-homepage .extension-pack-header { color: ${buttonForegroundColor};}`);
+		collector.addRule(`.monaco-workbench .part.editor > .content .welcomePageContainer .ads-homepage .dropdown-content a:hover, .monaco-workbench .part.editor > .content .welcomePageContainer .ads-homepage .dropdown-content a:hover { color: ${buttonForegroundColor};}`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts:1045]: Why are you using buttonForegroundColor for the link hover color? Don't we have a link hover color already?

File: src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts [hunk 2]
```diff
@@ -1037,26 +1042,27 @@ registerThemingParticipant((theme, collector) => {
...
 	}
 	const buttonSecondaryColor = theme.getColor(buttonSecondary);
 	if (buttonSecondaryColor) {
-		collector.addRule(`.monaco-workbench .part.editor > .content .welcomePageContainer .btn-secondary { color: ${buttonSecondaryColor} !important;}`);
+		collector.addRule(`.monaco-workbench .part.editor > .content .welcomePageContainer .btn-secondary { color: ${buttonSecondaryColor} !important}`);
 	}
 	const buttonSecondaryHover = theme.getColor(buttonSecondaryHoverColor);
 	if (buttonSecondaryColor) {
-		collector.addRule(`.monaco-workbench .part.editor > .content .welcomePageContainer .btn-secondary:hover { color: ${buttonSecondaryHover}; border: 1px solid ${buttonSecondaryHover};}`);
+		collector.addRule(`.monaco-workbench .part.editor > .content .welcomePageContainer .btn-secondary:hover:not(.disabled) { color: ${buttonSecondaryHover}; border: 1px solid ${buttonSecondaryHover}}`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts:1065]: Why are you using buttonSecondaryHover for the border color here?

Comment (v-bbrady) [reply src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts:1065]: I was using this because it is hover state and the border on hover is the same color as the "color". I have divided them into two different registered colors now for clarity. @Charles-Gagnon

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/welcome/page/browser/welcomePage.ts]: Thanks, yeah that's definitely preferable as I mentioned since we don't want someone to change a color (these are all configurable by the user) and have it change the color unexpectedly.
