### PR TITLE
Fix loading and clickable div screen reader issues

### LINKED ISSUE #7662: A11y_AzureDataStudio_BigDataClusterOverviewPage _ScreenReader : NVDA is unnecessarily announcing clickable for every read only data.
"[Check out Accessibility Insights!](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier."
​
GitHubTags:#A11y_ADS_OctTestPass;#A11yMAS;#A11yTCS;#MAS1.3.1;DesktopApp;#NVDA;#SQL AzureDataStudio;#Win32

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 6582debd7388b1be512fc3a9b956d3e54f6115e7
Date: 2019-10-03T08:56:27.454Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
NVDA Version: 2019.2

**Additional Details:**
Tool Name : NVDA

**Steps to Reproduce:**
1. Install and Launch the application the azure data studio application.
2. Open the “Connections” viewlet (CTRL + SHIFT + D)
3. Navigate to the “SQL Server Big Data Clusters” section and expand it
4. Navigate to the "Add SQL Server big data cluster controller…" node and click on it.
5. Fill in the connection information for the BDC Controller Endpoint
6. Click “Add”
7. Navigate to the controller node in the “SQL Server Big Data Clusters” view and right click on it, then select “Manage” to open the dashboard
8. "Big Data Cluster Overview page " should open.
9. Start NVDA.
10. Navigate till "Cluster Properties" using basic navigation that is using arrow.
11. Observe the announcement by screen reader .

**Actual:**
Screen reader  is unnecessarily announcing clickable for every read only data.
It is announcing like "Clickable Cluster properties".
**Similar issue is also observed with following screens:
1)Control tab**
1. Install and Launch the application the azure data studio application.
2. Open the “Connections” viewlet (CTRL + SHIFT + D)
3. Navigate to the “SQL Server Big Data Clusters” section and expand it
4. Navigate to the "Add SQL Server big data cluster controller…" node and click on it.
5. Fill in the connection information for the BDC Controller Endpoint
6. Click “Add”
7. Navigate to the controller node in the “SQL Server Big Data Clusters” view and right click on it, then select “Manage” to open the dashboard->click on the "control tab " in the left nav bar-> navigate to the "Metricsdc" tab.

**2)Jupyter books**
1. Install and Launch the application the azure data studio application.
2.Connet to the servers with the required credentials.
3.Navigate to the control panel and click on the "jupyter books" icon.
4.Press CRTL+SHIFT+P and search "jupyter books: SQL Server 2019 Guide" 

 
**Expected:**
Screen reader should not announce clickable for the text as it is read only data.

**User Impact:**
Screen reader user will get incorrect information regarding the content present on the screen.

**Attachment for Reference:**
[7662_A11y_AzureDataStudio_BigDataClusterOverviewPage _ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3716321/7662_A11y_AzureDataStudio_BigDataClusterOverviewPage._ScreenReader.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7662

1. "Loading Completed" was always being announced when walking the tree in text mode. Changed to using the general aria status helper function instead - this way it isn't in the DOM so the screen reader won't announce it unnecessarily

2. Clickable was always being announced because we were always hooking up a click handler for divs. I changed it so the click handler is hooked up dynamically now and is removed if clickable is set to false so this no longer announces

Output after loading is completed :
```
menu
menu item
controller:  [IP/user] level 1
Loading health status completed 
```
Output now when walking tree after loading is completed :
```
tab
App
Cluster Properties
Cluster State :
Ready
Health Status :
Healthy
Cluster Overview
Last Updated : 2/7/2020 9:48:09 AM
```

and output when things are still loading :

```
Cluster Properties
Cluster State :
graphic
Loading
Health Status :
graphic
Loading
```

### CODE REVIEW

File: src/sql/workbench/browser/modelComponents/divContainer.component.ts [hunk 1]
```diff
@@ -131,7 +140,7 @@ export default class DivContainer extends ContainerBase<azdata.DivItemLayout> im
 	}
 
 	public get clickable(): boolean {
-		return this.getPropertyOrDefault<azdata.DivContainerProperties, boolean>((props) => props.clickable, false);
+		return this.getPropertyOrDefault<azdata.DivContainerProperties, boolean>((props) => props.clickable, true);
```
Comment (alanrenmsft) [inline src/sql/workbench/browser/modelComponents/divContainer.component.ts]: why do we have to change the default value here?

Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/divContainer.component.ts]: Oops, I was testing changing that. Thanks.

File: src/sql/workbench/browser/modelComponents/loadingComponent.component.ts [hunk 2]
```diff
@@ -13,13 +13,11 @@ import * as azdata from 'azdata';
 import { ComponentBase } from 'sql/workbench/browser/modelComponents/componentBase';
 import { localize } from 'vs/nls';
 import { IComponent, IComponentDescriptor, IModelStore } from 'sql/platform/dashboard/browser/interfaces';
+import { status } from 'vs/base/browser/ui/aria/aria';
 
 @Component({
 	selector: 'modelview-loadingComponent',
 	template: `
-		<div role="status" aria-live="polite" class="modelview-loading-component-status-message">
```
Comment (alanrenmsft) [inline src/sql/workbench/browser/modelComponents/loadingComponent.component.ts]: glad that you fixed this, i also realized this problem but didn't get a chance to look into it. looked into the vscode status implementation and it looks good.

Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/loadingComponent.component.ts]: Note that this isn't perfect. If multiple things send off a status message at the same time then it'll usually only announce one of them. There isn't really a good way to solve this though that I can think of since there's no way to detect if something has actually been announced. Might be something we have to come up with a solution for later if we start needing multiple messages to be announced in a row.
