### PR TITLE
Change logic to not show results until there are results to show

### LINKED ISSUE #6126: Query Results tab is shown blank while script is executing
- Azure Data Studio Version: `master`
 
Steps to Reproduce:

1. Run a SQL script that takes a while to complete and that doesn't generate a resultset.  For example, the Northwinds install script from https://raw.githubusercontent.com/microsoft/sql-server-samples/master/samples/databases/northwind-pubs/instnwnd.sql

Expected: Results tab is never shown and the Messages tab is shown while script is executing.  The Results tab should only show up when there are results.

Actual: Results tab is show blank and Messages are logged in the background.

Screen Shot 2019-06-21 at 11 17 17 AM

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes #6126

### CODE REVIEW

**Comment by kburtram** [comment]
I left a comment on #6126 regarding an undesirable side-effect of this change.

**Comment by kburtram** [comment]
@anthonydresser do you have any ideas of how to update this PR to address the issue with long running queries?

File: src/sql/workbench/parts/query/browser/queryResultsView.ts [hunk 1]
```diff
@@ -212,26 +213,24 @@ export class QueryResultsView extends Disposable {
 
 	private setQueryRunner(runner: QueryRunner) {
 		const activeTab = this._input.state.activeTab;
-		if (runner.hasCompleted && !this.hasResults(runner)) {
-			this.hideResults();
-		} else {
+		if (this.hasResults(runner)) {
 			this.showResults();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/query/browser/queryResultsView.ts]: So this change here is making it so new query tabs won't show their results until ran a second time. This is because by the time this is called we're already past the onQueryStart event being fired so the below handler never gets called which means we never call showResults to un-hide the results tab

File: src/sql/workbench/parts/query/browser/queryResultsView.ts [hunk 2]
```diff
@@ -366,11 +365,13 @@ export class QueryResultsView extends Disposable {
 		}
 	}
 
-	public showResults() {
+	public showResults(show: boolean = true) {
 		if (!this._panelView.contains(this.resultsTab)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/query/browser/queryResultsView.ts]: You never use this with false so this seems like an unnecessary change (for now)

**Comment by anthonydresser** [comment]
@kburtram can you review again
