### PR TITLE
Fix Schema compare recompare after options reset not using correct options 

### LINKED ISSUE #6538: Schema compare recompare options reset doesn't use correct options
Clicking 'Yes' to recompare after resetting options uses the old options, not the reset options.

image

### PR DESCRIPTION
**Pull request by kisantia**
Recomparing from the notification after resetting options wasn't using the correct options because the compare was being started before the options were set to the new values. Fixes #6538.

### CODE REVIEW

File: extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts [hunk 1]
```diff
@@ -448,6 +448,7 @@ export class SchemaCompareOptionsDialog {
 		if (this.optionsChanged) {
 			vscode.window.showWarningMessage(SchemaCompareOptionsDialog.OptionsChangedMessage, SchemaCompareOptionsDialog.YesButtonText, SchemaCompareOptionsDialog.NoButtonText).then((result) => {
 				if (result === SchemaCompareOptionsDialog.YesButtonText) {
+					this.schemaComparison.setDeploymentOptions(this.deploymentOptions);
```
Comment (udeeshagautam) [inline extensions/schema-compare/src/dialogs/schemaCompareOptionsDialog.ts]: good catch!!

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 2]
```diff
@@ -915,7 +918,7 @@ export class SchemaCompareMainWindow {
 			}
 
 			this.updateSourceAndTarget();
-			this.deploymentOptions = result.deploymentOptions;
```
Comment (udeeshagautam) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts]: was this causing issue too? that seems similar in effect..

Comment (kisantia) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts]: no but I thought it would be best to use this function wherever the deployment options get set
