### PR TITLE
change order of tasks

### LINKED ISSUE #8627: Dashboard Tasks incorrectly ordered
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open a Dashboard to the Server page

Expected: New Query & New Notebook tasks on top row of tasks widget

image

### PR DESCRIPTION
**Pull request by alanrenmsft**
I am looking into the area recently and saw this issue, I didn't dig too much into the change history, it makes sense to have new query and new notebook appear first.

This PR fixes #8627 

with the changes:
Screen Shot 2019-12-16 at 12 10 28 PM

### CODE REVIEW

File: src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts [hunk 1]
```diff
@@ -2,10 +2,9 @@
  *  Copyright (c) Microsoft Corporation. All rights reserved.
  *  Licensed under the Source EULA. See License.txt in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
-
+import { generateDashboardTabSchema, generateDashboardWidgetSchema } from 'sql/workbench/contrib/dashboard/browser/pages/dashboardPageContribution';
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts]: order the imports alphabetically.
