### PR TITLE
fix informational/error messages when tools not installed/not discovered/not installable

### LINKED ISSUE #8638: Change error message for docker tool not available
On the Deployment screen, when a user selects SQL Server Container image and docker tool is not detected, the error message is:

Some required tools are not installed or do not meet the minimum version requirement.
'docker' was not discovered and automated installation is not supported. Kindly install it manually or if installed make sure it is started and discoverable. Once done please restart Azure Data Studio. See [https://docs.docker.com/install] .
You will need to restart Azure Data Studio if the tools are installed by yourself after Azure Data Studio is launched to pick up the updated PATH environment variable. You may find additional details in 'Deployments' output channel

I suggest we modify the text as below:

'docker' was not discovered and automated installation is not supported at the moment. Install docker manually or ensure it is started and discoverable. Once done please restart Azure Data Studio. See [https://docs.docker.com/install] .
You will need to restart Azure Data Studio if the tools are installed after Azure Data Studio is launched to pick up the updated PATH environment variable. You may find additional details in 'Deployments' output channel.

### PR DESCRIPTION
**Pull request by ranasaria**
This change fixes information/warning/error messages. Here is a sample snapshot of the error messages displayed after fixes:
image

This PR fixes #8638.

### CODE REVIEW

File: extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts [hunk 1]
```diff
@@ -221,40 +221,45 @@ export class ResourceTypePickerDialog extends DialogBase {
 				if (this.toolRefreshTimestamp !== currentRefreshTimestamp) {
 					return;
 				}
-				let installationNeeded = false;
 				let minVersionCheckFailed = false;
-				const messages: string[] = [];
+				let toolsToAutoInstall: ITool[] = [];
```
Comment (alanrenmsft) [inline extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: both array can be const.

File: extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts [hunk 2]
```diff
@@ -221,40 +221,45 @@ export class ResourceTypePickerDialog extends DialogBase {
...
 					this._toDispose.push(tool.onDidUpdateData((t: ITool) => {
 						this.updateToolsDisplayTableData(t);
 					}));
-					if (tool.isNotInstalled && !tool.autoInstallSupported) {
-						messages.push(localize('deploymentDialog.ToolInformation', "'{0}' was not discovered and automated installation is not supported. Kindly install it manually or if installed make sure it is started and discoverable. Once done please restart Azure Data Studio. See [{1}] .", tool.displayName, tool.homePage));
+					if (tool.isNotInstalled) {
+						if (tool.autoInstallSupported) {
+							toolsToAutoInstall.push(tool);
+						} else {
+							messages.push(localize('deploymentDialog.ToolInformation', "'{0}' was not discovered and automated installation is not supported at the moment. Install '{0}' manually or ensure it is started and discoverable. Once done please restart Azure Data Studio. See [{1}] .", tool.displayName, tool.homePage));
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: Run this string by a PM. I don't think "at the moment" is the best here. Something like "not currently supported" is better since moment implies that it may be available if they try again.

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: See https://github.com/microsoft/azuredatastudio/issues/8638. Dinaker specifically requested this verbiage. I will still double-check with him.

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: Added Dinaker to chime in.

**Comment by dnethi** [comment]
I am good with “.. not currently supported”  in place of “at the moment” ..


Thanks,
Dinakar

**Comment by anthonydresser** [comment]
why is your change set so large? you should merge from master.

**Comment by ranasaria** [comment]
> Building up on what @anthonydresser said, this will break the current state of master - it's changing a TON of files.

Fixed botched merge from the master. Please take a look again.

**Comment by ranasaria** [comment]
> please share a screenshot.

Done

**Comment by ranasaria** [comment]
> why is your change set so large? you should merge from master.

Fixed.
