### PR TITLE
Fix schema compare diff script formatting

### LINKED ISSUE #5419: Fix schema compare formatting of scripts in diff
Need to add 'GO's after statements.

Blank lines showing as a difference:
image

Blank line before script. Doesn't happen for all types. Looks like it's part of the script returned from the backend, so the excess whitespace needs to be trimmed.
image

Sometimes there isn't a new line between different lines of the script. Again due to the inconsistency of what's being returned from the backend.
image

### PR DESCRIPTION
**Pull request by kisantia**
Fix #5419. This fixes the formatting problems below. Adding 'GO' after statements and blank lines at the beginning were fixed in SqlToolsService and are in version 1.5.0-alpha.93.

**Blank lines no longer showing as difference:**
old:
image
fixed:
image

**No more blank lines at the beginning of some scripts:**
old:
image
fixed:
image

**Each statement now starts on its own line:**
old:
image
fixed:
image

### CODE REVIEW

**Comment by udeeshagautam** [comment]
how come I thought this was checked in.

**Comment by kisantia** [comment]
@udeeshagautam the SqlToolsService changes were checked it. I closed the previous ADS PR since I moved some the changes to SqlToolsService.

File: extensions/schema-compare/src/schemaCompareResult.ts [hunk 1]
```diff
@@ -264,15 +264,29 @@ export class SchemaCompareResult {
...
+		let script = this.getAggregatedScript(diffEntry, getSourceScript);
+		return script;
+	}
+
 	private getAggregatedScript(diffEntry: azdata.DiffEntry, getSourceScript: boolean): string {
 		let script = '';
 		if (diffEntry !== null) {
-			script += getSourceScript ? diffEntry.sourceScript : diffEntry.targetScript;
+			let diffEntryScript = getSourceScript ? diffEntry.sourceScript : diffEntry.targetScript;
+			if (diffEntryScript) {
```
Comment (udeeshagautam) [inline extensions/schema-compare/src/schemaCompareResult.ts]: just for my understanding:

suppose a child script is just ' '  will this part all \n to that? because then when it goes to parent it might end up having multiple lines. am I missing something?

Comment (kisantia) [reply extensions/schema-compare/src/schemaCompareResult.ts]: Empty strings evaluate to false, so it doesn't go inside the if in that case. The scripts are trimmed in SqlToolsService so scripts that might be all whitespace would be empty strings at this point.
