### PR TITLE
First draft of outputProcessor tests

### LINKED ISSUE #11355: extract method in output processor does not hand sentinel JSONObject inputs correctly
- Azure Data Studio Version:
main. 

Steps to Reproduce:

1. Call extract method in src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts with value of 'value' parameter undefined. The following error is thrown:
**_SyntaxError: Unexpected token u in JSON at position 0_**

### PR DESCRIPTION
**Pull request by ranasaria**
This PR adds unit tests for OutputProcessor.ts

This PR also fixes #11355 and removes a couple of redundant checks in conditionals.

Testing: 
1.  Ran all unit test
2. Measured code coverage of the new tests.

Coverage:
[Code coverage report for workbench_contrib_notebook_browser_models_outputProcessor.ts.pdf](https://github.com/microsoft/azuredatastudio/files/4928535/Code.coverage.report.for.workbench_contrib_notebook_browser_models_outputProcessor.ts.pdf)

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts [hunk 1]
```diff
@@ -41,10 +41,10 @@ export function getData(output: nb.ICellOutput): JSONObject {
 	} else if (nbformat.isError(output)) {
 		let traceback = output.traceback ? output.traceback.join('\n') : undefined;
 		bundle['application/vnd.jupyter.stderr'] = undefined;
-		if (traceback && traceback !== '') {
```
Comment (ranasaria) [inline src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts:44]: redundant check

File: src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts [hunk 2]
```diff
@@ -41,10 +41,10 @@ export function getData(output: nb.ICellOutput): JSONObject {
...
+		if (traceback) {
 			bundle['application/vnd.jupyter.stderr'] = traceback;
 		} else if (output.evalue) {
-			bundle['application/vnd.jupyter.stderr'] = output.ename && output.ename !== '' ? `${output.ename}: ${output.evalue}` : `${output.evalue}`;
```
Comment (ranasaria) [inline src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts:47]: redundant check

File: src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts [hunk 3]
```diff
@@ -78,7 +78,7 @@ export function getBundleOptions(options: IOutputModelOptions): MimeModel.IOptio
  */
 export function extract(value: JSONObject, key: string): {} {
 	let item = value[key];
-	if (isPrimitive(item)) {
```
Comment (ranasaria) [inline src/sql/workbench/contrib/notebook/browser/models/outputProcessor.ts:81]: bug fix. value of undefined and null note being handled correctly. It is not possible to do JSON.parese on undefined.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+
+
+suite('OutputProcessor functions', function (): void {
+	suite('getData', async function (): Promise<void> {
+		for (const outputType of ['execute_result', 'display_data', 'update_display_data', 'stream', 'error'] as nbformat.OutputType[]) {
+			const text = getRandomString(1, 10);
+			const output: nb.ICellOutput = {
+				output_type: outputType
+			};
+			if (nbformat.isError(output)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:22]: Instead of having one huge block with tons of nested ifs it would be great if you could just simply split this up into multiple tests. For example I don't see why the error and stream have to be a part of this loop - they don't share any code paths.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+											'application/vnd.jupyter.stderr': `${output.ename}: ${output.evalue}`
+										};
+									} else {
+										expectedData = {
+											'application/vnd.jupyter.stderr': `${output.evalue}`
+										};
+									}
+
+								}
+								assert.deepEqual(result, <JSONObject>expectedData, `getData should return the expectedData:'${JSON.stringify(expectedData)}' object`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:51]: Well, I really hope if anyone has to debug failures in this test they have a deep knowledge of how this all works. Because there's absolutely no indication of why these are the expected values. Getting some comments in here explaining what's going on would be great.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+							});
+						}
+					}
+				}
+			} else if (nbformat.isStream(output)) {
+				for (const name of ['stderr', 'stdout'] as nbformat.StreamType[]) {
+					test(`test for outputType:${outputType} and name:${name}`, async () => {
+						output.text = text;
+						output.name = name;
+						const expectedData =
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:61]: Another example of being way overly verbose. If you're going to use loops why not just embed the expected values into the loop params?
```
for (const item of [ 
   'stderr', { 'application/vnd.jupyter.stderr': text},
   'stdout', { 'application/vnd.jupyter.stdout', text}
]) {
...
```
That seems much cleaner to me and clearly shows what the expected values are in the code for each type.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 7]
```diff
@@ -0,0 +1,136 @@
...
+					metadata: op.getMetadata(output),
+					trusted: trusted
+				};
+				assert.deepEqual(result, expected, `getBundleOptions did not return the expected object:'${JSON.stringify(expected)}'`);
+			});
+		}
+	});
+});
+
+function getRandom<T>(...list: T[]): T {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:134]: This should probably be in some general utils module.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 8]
```diff
@@ -0,0 +1,136 @@
+/*---------------------------------------------------------------------------------------------
+ *  Copyright (c) Microsoft Corporation. All rights reserved.
+ *  Licensed under the Source EULA. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+
+// import * as TypeMoq from 'typemoq';
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:6]: remove

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 9]
```diff
@@ -0,0 +1,136 @@
...
+
+suite('OutputProcessor functions', function (): void {
+	suite('getData', async function (): Promise<void> {
+		for (const outputType of ['execute_result', 'display_data', 'update_display_data', 'stream', 'error'] as nbformat.OutputType[]) {
+			const text = getRandomString(1, 10);
+			const output: nb.ICellOutput = {
+				output_type: outputType
+			};
+			if (nbformat.isError(output)) {
+				for (const traceback of [undefined, [], [getRandomString(1, 10), getRandomString(1, 10)]]) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:23]: Not testing empty strings for these?

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 5 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:51]: will do

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 4 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:22]: will do.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 9 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:23]: Thanks, I will add a case for that.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 8 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:6]: done

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 5 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:51]: added comments

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 4 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:22]: split up into several blocks. One for reach types of tests. Thanks for the suggestion.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 8 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:6]: done

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 7 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:158]: removed. Used a pre-existing one that I found. Thanks for the suggestion.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 6 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts]: This was a good suggestion but I ended up doing a different refactor where I felt it was not needed (but could still be done).

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 9 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts]: done

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 10]
```diff
@@ -0,0 +1,166 @@
...
+	suite('getData', async function (): Promise<void> {
+		// data tests
+		for (const outputType of ['execute_result', 'display_data', 'update_display_data'] as nbformat.OutputType[]) {
+			const output = <nbformat.IExecuteResult>{
+				output_type: outputType,
+				data: <op.IMimeBundle>{
+					result: text  // free form fields of the IMimeBundle. This is just an arbitrarily cooked-up hardcoded example for the test.
+				}
+			};
+			test(`test for outputType:${output.output_type}`, async () => {
```
Comment (aaomidi) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:41]: I dont think this needs to be async

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 11]
```diff
@@ -0,0 +1,166 @@
...
+				verifyGetDataForDataOutput(output);
+			});
+		}
+
+		// error tests
+		for (const traceback of [undefined, [undefined], [], [''], [getRandomString(0, 10), getRandomString(0, 10)]]) {
```
Comment (aaomidi) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:47]: Arguably your test shouldn't have a random test case - the getRandomString() could cause some tests to pass and some tests to fail.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:47]: Fuzz tests can be useful, but yeah I agree for these it'd be better to keep most tests deterministic and then optionally we can add fuzz tests if that seems useful.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 10 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:41]: Ack. Will remove redundant 'async' qualifiers.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 11 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:47]: 'could' is the key word. The claim with these tests is that they should not fail for any of the values. If they do it needs to be investigated. This is symbolizing any payload given to the input should get returns as its. I disagree with hardcode value in these test scenarios even though they could ostensibly lead to more deterministic test.

Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:47]: Just because I have chosen a random string does not make it a fuzz test. I do very much think that a random payload is a correct thing.

Comment (aaomidi) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:47]: Yeah I suppose it's fine. My concern is that this could fail on someone else's PR and they're going to have to waste time realizing the test failure isn't even related to their work.

I agree with the concept of fuzzy testing but I've usually seen it in cases where the unit test is going to run a few thousand iterations of itself to catch issues.

Fuzzy testing when running one test per build seems like it'd just create noise and not get the attention of the correct person to look into any potential failure.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:47]: I agree with Amir. These tests should focus on testing a set of known values to verify behavior. If you want to make a special fuzz test that's fine (and useful) but it should be separate and clearly indicated that it's using random values so someone looking at failures can understand why a particular value was "expected".

Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:47]: I will change to a known string for know. So should testing with random inputs be separate run?

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 10 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:41]: removed

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 11 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:47]: fixed.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts]: I think just having a test that specifically runs through some number of random strings is fine - just make sure the title clearly indicates it as such. That'll at least prevent people from ratholing too hard on why the test is failing in most cases. 

What Amir said about the test failing for other people randomly is a slight concern - but since we don't currently have a good system set up for grouping up "types" of tests I don't think it's worth trying to come up with that now. If these start to be an issue for some reason then we can re-evaluate but I don't expect them to actually fail, and if they do fixing it should be simple I would imagine.

Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts]: Looking over the product code the fields in questions are just passed back as output in a different shape of any object and there is no processing done on the contents of the string field in question. So for these apps at least I do not see ROI in writing separate tests for running with multiple random invites. Even the execution times for those tests would seem an unnecessary expense. I would vote on skip authoring of separate tests with random inputs.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 12]
```diff
@@ -0,0 +1,164 @@
...
+				} else {
+					assert.deepEqual(result, {}, `getMetadata should return an empty object when output_type is not IDisplayData or IExecuteResult`);
+				}
+			});
+		}
+	});
+
+	suite('getBundleOptions', function (): void {
+		for (const trusted of [true, false]) {
+			const outputType = getRandomElement(['execute_result', 'display_data']) as nbformat.OutputType;
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:93]: Hmm let's not introduce an element of chance here. If we'd like to test all scenarios, then let's not randomly pick an element and have this be deterministic.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts [hunk 13]
```diff
@@ -0,0 +1,164 @@
...
+					result: text  // free form fields of the IMimeBundle. This is just an arbitrarily cooked-up hardcoded example for the test.
+				}
+			};
+			test(`test for outputType:${output.output_type}`, () => {
+				verifyGetDataForDataOutput(output);
+			});
+		}
+
+		// error tests
+		for (const traceback of [undefined, [undefined], [], [''], ['tb1:!@#$%^&*()_+~`:;,.-_=', 'tb2:!@#$%^&*()_+~`:;,.-_=']]) {
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:45]: let's put a comment here that the string represents arbitrary text

Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:45]: did in line in the text of the string.

File: src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts (hunk 12 above)
Comment (ranasaria) [reply src/sql/workbench/contrib/notebook/test/browser/outputProcessor.test.ts:93]: fixed
