### PR TITLE
Fixed the stray validation error message in Resource Deployment wizard

### LINKED ISSUE #13679: Resource Deployment shows missing tools after auto-installing
1. Start with kubectl/azdata installed but not az
1. Start BDC deployment
1. It'll prompt to auto-install az, let it do so
1. After it's done this warning message is shown : 

image

But as you can see from the table it apparently was able to find those tools just fine.

### LINKED ISSUE #13719: Next button on ToolsAndEulaPage gives persistent spurious error
**Steps to Reproduce:**

1. Start with a state where az.cmd is not installed
2. Kickoff BDC deployment wizard
3. The tools and eula page warns that az.cmd is not installed.
4. Click 'Install Tools' button to install az.cmd. Click 'Next' once the installation is done.

**Actual:** An unexpected error 'Some tools are still not installed' shows up. This error persists if the user dismisses the error and clicks 'Next'. The wizard is rendered to be unusable.
image

**Expected:** The wizard proceeds to the next page.

**Workaround:** Cancel out of the wizard and launch it again. All tools are discovered and the wizard proceeds to 2nd page.

**Azure Data Studio Version**:
```
Version: 1.25.0-rc1
Commit: 2d50d2c5d1ed5f426c46e06cee436dce8debc6c9
Date: 2020-12-03T02:46:44.284Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #13679 and fixes #13719 

I have already extensively tested this change locally and I found 1 bug: Table 'withValidation' does not work. @Charles-Gagnon  what can be a potential fix for this issue?  

@ranasaria and @Charles-Gagnon, 
Please run this branch locally to see if it has fixed all the other edge cases. If not then please report the issues to this PR.

Initial State when a tool is not installed: (@Charles-Gagnon, @ranasaria   shouldn't this be an error message?)
image

If you click next without installing the tool:
image

If you click install button:
image

Once the tool installed: 
image

When you click the next button: 
image

### CODE REVIEW

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts [hunk 1]
```diff
@@ -109,6 +122,13 @@ export class ToolsAndEulaPage extends ResourceTypePage {
 				columns: [toolColumn, descriptionColumn, installStatusColumn, versionColumn, minVersionColumn, installedPathColumn],
 				width: tableWidth,
 				ariaLabel: loc.requiredToolsText
+			}).withValidation((component) => {
```
Comment (aasimkhan30) [inline extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:125]: @Charles-Gagnon, this validation does not work. The function works and returns the value as expected but the next button does not get disabled it the function returns false. 

Also, the function is called every time there is change to the table data.

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts [hunk 2]
```diff
@@ -58,14 +57,28 @@ export class ToolsAndEulaPage extends ResourceTypePage {
 				return false; // we return false so that the workflow does not proceed and user gets to either click acceptEulaAndSelect again or cancel
 			}
 
-			if (!this._isDoneButtonEnabled) {
-				this.wizard.wizardObject.message = {
-					text: localize('deploymentDialog.FailedToolsInstallation', "Some tools were still not discovered. Please make sure that they are installed, running and discoverable"),
-					level: azdata.window.MessageLevel.Error
-				};
-				return false;
+			for (let i = 0; i < this._tools.length; i++) {
```
Comment (aasimkhan30) [inline extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:60]: @Charles-Gagnon , I can potentially move this to the 'with validation' method if it works correctly.

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts (hunk 1 above)
Comment (aasimkhan30) [reply extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:125]: @Charles-Gagnon @ranasaria, the overall code works without this method. If I cannot get this working then I will remove it from the PR and just fix the issue at hand

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:125]: As long as you're not regressing behavior and the next button is disabled correctly when there's still tools to be installed then removing it is fine. It's possible there's a bug with the table validation since that isn't something we validate often.

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts [hunk 3]
```diff
@@ -302,7 +323,7 @@ export class ToolsAndEulaPage extends ResourceTypePage {
 					// Update the informational message
 					this.wizard.wizardObject.message = {
 						level: azdata.window.MessageLevel.Information,
-						text: localize('deploymentDialog.InstallingTool', "Required tool '{0}' [ {1} ] is being installed now.", tool.displayName, tool.homePage)
+						text: loc.getToolInstallingMessage(tool)
 					};
 					await this._tools[i].install();
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:328]: It doesn't necessarily have to be part of this PR - but it would be great to have the "Installing" status using the "withProgress" function from VS Code in a notification (toast) - see https://github.com/microsoft/azuredatastudio/blob/main/extensions%2Farc%2Fsrc%2Fui%2Fdashboards%2Fmiaa%2FmiaaComputeAndStoragePage.ts#L125 for an example

Right now it's not really easy to see that it's doing something and if we're allowing the user to cancel out of this dialog it would still be good to have the notification running so they know the tool is still being installed.

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by ranasaria** [comment]
From Description:
`Initial State when a tool is not installed: (@Charles-Gagnon, @ranasaria shouldn't this be an error message?)`

Issues that can be resolved using automation provided in the current ui are considered 'warnings'.

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts [hunk 4]
```diff
@@ -58,14 +57,28 @@ export class ToolsAndEulaPage extends ResourceTypePage {
...
 
-			if (!this._isDoneButtonEnabled) {
-				this.wizard.wizardObject.message = {
-					text: localize('deploymentDialog.FailedToolsInstallation', "Some tools were still not discovered. Please make sure that they are installed, running and discoverable"),
-					level: azdata.window.MessageLevel.Error
-				};
-				return false;
+			for (let i = 0; i < this._tools.length; i++) {
+				switch (this._tools[i].status) {
+					case ToolStatus.Installing:
```
Comment (ranasaria) [inline extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:62]: I do not see when it can happen that we are still 'installing' a tool and we need to do exit page validation.

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:125]: Since this is not working, remove it. You can file a new bug into our backlog for this api not working.

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts [hunk 5]
```diff
@@ -364,8 +387,6 @@ export class ToolsAndEulaPage extends ResourceTypePage {
 	private setUiControlsEnabled(enable: boolean): void {
 		this._agreementContainer.enabled = enable;
 		this._optionsContainer.enabled = enable;
-		this.wizard.wizardObject.cancelButton.enabled = enable;
```
Comment (ranasaria) [inline extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:367]: are we allowing cancel button to be clickable when the tool is being installed? If so, we should revert this change as   
we do not have a way of cancelling already started tool installation. Install once started has to be allowed to proceed to completion.

**Review by ranasaria — CHANGES_REQUESTED** [review]
Kindly review the questions I have raised and/or do the changes requested.

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts [hunk 6]
```diff
@@ -503,7 +524,6 @@ export class ToolsAndEulaPage extends ResourceTypePage {
 	}
 
 	private enableDoneButton(enable: boolean) {
-		this._isDoneButtonEnabled = enable;
```
Comment (ranasaria) [inline extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:506]: I assume this is removed because we are not ever on last page so this is irrelevant, is that right?

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts (hunk 4 above)
Comment (aasimkhan30) [reply extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:62]: This is because the next button is not getting disabled after you click the agreement checkbox.

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:62]: Put in some comments about the status changes

**Review by ranasaria — APPROVED** [review]
