### PR TITLE
Read server options from publish profile

### LINKED ISSUE #21927: Publish profile load fails for windows authentication
Steps to Reproduce:

1. Open Publish UI for a sql project.
2. Load publish profile with Windows auth.
3. Load fails with following error:
image

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #21927.
Prior changes did not read Encrypt and Trust Server Certificate value, hence doesn't load the connection properly and throws an error. The changes here reads it and uses these values to create a connection profile with proper options.

### CODE REVIEW

**Comment by SakshiS-harma** [comment]
Created https://github.com/microsoft/azuredatastudio/issues/21961 to have an API that supports all the options (instead of just reading a few of them).

File: extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts [hunk 1]
```diff
@@ -100,7 +112,11 @@ export class SqlConnectionDataSource extends DataSource {
 			providerName: 'MSSQL',
 			saveProfile: true,
 			id: this.name + '-dataSource',
-			options: []
+			options: {
+				'encrypt': this.encrypt,
```
Comment (kburtram) [inline extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts:116]: it might be possible to iterate through the connection string and build this dictionary in a more generic way, allowing you to send all options without special-casing these three.  Though I tend to agree sending the connection string to the connection API and having that code there is probably a better design.

**Review by kburtram — APPROVED** [review]

File: extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts (hunk 1 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts:116]: So the dictionary is getting created for the whole connection string here: https://github.com/microsoft/azuredatastudio/blob/f45069e4a99fce0e25a5fb773e1a555940fd0a4c/extensions/sql-database-projects/src/models/dataSources/sqlConnectionStringSource.ts#L83
But agreed it is not generic and while creating the connectionProfile object is when it actually misses the options. Hopefully with the new API it should work/generate connectionProfile as expected.

**Review by kisantia — APPROVED** [review]
If a connection string in a profile doesn't have these options set, can the behavior be updated so that the connection dialog opens with the fields pre populated with the connection string properties, rather than just showing an error that the connection failed? Then the user can try to update their connection through the connection dialog that pops up instead of having to update the connection string in the profile, then load it again.
