### PR TITLE
Reset IV/Key if MSAL cache file decryption fails

### LINKED ISSUE #22716: Cannot Log Into Azure Data Studio
Issue Type: <b>Bug</b>

I have tried authenticating to this app for a number of attempts. I have deleted and reinstalled this application at least 4 times, and did so after restarting my machine to get my credentials to the SQL server authenticated. I cannot access the database, and my credentials WILL NOT update. This happens EVERY TIME Azure Data Studio updates. Any assistance would be greatly appreciated.

Attached file:
[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/11226299/1-Azure.Accounts.log)

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (21.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.4

</details>

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes #22716 that may occur if IV/KEY is corrupted due to any reason.
The best action here is to reset IV/KEY combination to allow resetting cache.

Fix verified with log:

```log
[Verbose]: Initialized Azure account extension storage. - []
[Verbose]: FileEncryptionHelper: Fired encryption keys updated event. - []
[Verbose]: Initializing stored accounts [] - []
[Information]: [Fri, 14 Apr 2023 17:21:04 GMT] : @azure/msal-node@1.16.0 : Info - getTokenCache called - []
[Verbose]: [Fri, 14 Apr 2023 17:21:04 GMT] : @azure/msal-node@1.16.0 : Trace - getAllAccounts called - []
[Error]: FileEncryptionHelper: Error occurred when decrypting data, IV/KEY will be reset: Error: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH - []
[Information]: FileEncryptionHelper: Successfully saved encryption key accessTokenCache-iv for MSAL persistent cache encryption in system credential store. - []
[Information]: FileEncryptionHelper: Successfully saved encryption key accessTokenCache-key for MSAL persistent cache encryption in system credential store. - []
[Verbose]: FileEncryptionHelper: Fired encryption keys updated event. - []
[Error]: MsalCachePlugin: Failed to read from cache file: Error: Decryption failed with error: Error: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH - []
[Verbose]: MsalCachePlugin: Error occurred when trying to read cache file, file will be deleted: Decryption failed with error: Error: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH - []
[Verbose]: [Fri, 14 Apr 2023 17:21:05 GMT] : @azure/msal-node@1.16.0 : Trace - Retrieving all cache keys - []
[Verbose]: [Fri, 14 Apr 2023 17:21:05 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store - []
[Information]: [Fri, 14 Apr 2023 17:21:05 GMT] : @azure/msal-node@1.16.0 : Info - getTokenCache called - []
[Verbose]: [Fri, 14 Apr 2023 17:21:05 GMT] : @azure/msal-node@1.16.0 : Trace - getAllAccounts called - []
[Verbose]: MsalCachePlugin: Cache file not found on disk: ENOENT - []
```

Account can now be added/refreshed successfully, as cache file will be created when content is to be written.

### CODE REVIEW

File: extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts [hunk 1]
```diff
@@ -64,8 +64,9 @@ export class MsalCachePluginProvider {
 				}
 				else {
 					Logger.error(`MsalCachePlugin: Failed to read from cache file: ${e}`);
-					Logger.verbose(`MsalCachePlugin: Error occurred when trying to read cache file, file contents will be cleared: ${e.message}`);
-					await fsPromises.writeFile(this._msalFilePath, '', { encoding: 'utf8' });
+					Logger.verbose(`MsalCachePlugin: Error occurred when trying to read cache file, file will be deleted: ${e.message}`);
+					await fsPromises.unlink(this._msalFilePath);
+					// await fsPromises.writeFile(this._msalFilePath, '', { encoding: 'utf8' });
```
Comment (kburtram) [inline extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts:69]: should we remove this commented out code or add some text why it is being retained?

**Review by kburtram — APPROVED** [review]

File: extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts (hunk 1 above)
Comment (cheenamalhotra) [reply extensions/azurecore/src/account-provider/utils/msalCachePlugin.ts:69]: Oh yes, I accidentally missed it.
