### PR TITLE
Fix "Query Canceled by User" when querying encrypted fields Bug

### LINKED ISSUE #12611: "Query Canceled by User" when querying encrypted fields
Issue Type: <b>Bug</b>

When querying encrypted fields, query cancels itself, and "Query Canceled by User" message is returned.
- Using Azure Key Vault
- SSMS is working
- Azure account is connected
- "Always Encrypted" is Enabled
- Secure Enclave is not being used

**Steps to Reproduce:**
1. Clean install of Azure Data Studio 1.22.0 (Also attempted with clean install of 1.19.0)
1. Enable "Always Encrypted"
1. Execute query with any encrypted field selected

**Expected Results**
Results are returned for selected encrypted fields

**Actual Results**
Query is canceled by system before results are returned. Following system message is returned:
>Started executing query at Line 1
>(X rows affected)
>Query was canceled by user
>Total execution time: X

No errors are returned in any logs

Azure Data Studio version: azuredatastudio 1.22
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (3.39GB free)|
|Process Argv|-psn_0_208947|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### PR DESCRIPTION
**Pull request by Xtrimmer**
Some time back when the `azdata.accounts.getAccountSecurityToken()` method was introduced, [some changes](https://github.com/microsoft/azuredatastudio/commit/587abd43c2d92d83af1214399172fe8734597915#diff-e519fbe7133b0f3ebdab4872678a1ad87ce1a8736ee4e2988ae0637a2a318c2b) were made to make use of this new method. Within one of the AE workflows, the `tenant` object was passed to this method instead of the `tenant.id` string value, which caused an exception and led to this bug.

image

This PR aims to correct this mistake, fix the bug and Closes #12611.

### CODE REVIEW

File: extensions/mssql/src/features.ts [hunk 1]
```diff
@@ -76,7 +76,7 @@ export class AccountFeature implements StaticFeature {
 			window.showErrorMessage(unauthorizedMessage);
 			return undefined;
 		}
-		const securityToken = await azdata.accounts.getAccountSecurityToken(account, tenant, azdata.AzureResource.AzureKeyVault);
+		const securityToken = await azdata.accounts.getAccountSecurityToken(account, tenant.id, azdata.AzureResource.AzureKeyVault);
```
Comment (Benjin) [inline extensions/mssql/src/features.ts:79]: I'm surprised this wasn't prevented by parameter typing.  I expected that the compiler would catch this.

**Review by Benjin — APPROVED** [review]

**Review by kburtram — APPROVED** [review]
LGTM.  @cssuh could you please review this fix and confirm there aren't related issues introduced by the refactor mentioned in the PR discussion.  Thanks!

File: extensions/mssql/src/features.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply extensions/mssql/src/features.ts:79]: Tenant is an any type so that's why it wasn't caught. 

This is currently because the account type is a generic azdata.Account which doesn't have the concept of tenants (those are a specific implementation for Azure accounts). 

That being said we should most definitely also be fixing this to have proper typing for Azure accounts - stuff like this is why I keep pushing people to never use any unless you absolutely need to and then to create types whenever you can if you have specific implementations.

**Review by abist — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
Looks good as a fix - I'm going to look into improving the typings here so this doesn't happen again.

(There's also some confusion I have on why this is basically doing similar stuff to what azurecore is already doing re: security tokens so I might try to clean that up as well...)

**Comment by Charles-Gagnon** [comment]
Merging this in so we can bring it up for port request to release branch
