### PR TITLE
Fix for Markdown File in Jupyter Books Viewlet not Opening After 2x

### LINKED ISSUE #8006: Markdown Files in Jupyter Book Viewlet Fail to Open After Opening Twice Previously
The problem is here:

```
private runThrottledAction(resource: string, action: () => void) {
		const isResourceChange = resource !== this._resource;
		if (isResourceChange) {
			clearTimeout(this._throttleTimer);
			this._throttleTimer = undefined;
		}

		this._resource = resource;

		// Schedule update if none is pending
		if (!this._throttleTimer) {
			if (isResourceChange) {
				action();
			} else {
				this._throttleTimer = setTimeout(() => action(), 300);
			}
		}
	}
```

@kevcunnane can you help advise here? The lowdown is the following:

The first time, `isResourceChange` is true, so `this._throttleTimer` is set to undefined. `action()` is run directly.

The second time, `isResourceChange` is false, but `this._throttleTimer` is still undefined. `action()` is called with a timeout of 300 ms.

The third (and subsequent) time, `isResourceChange` is still false, and `!this._throttleTimer` will return false, as it is no longer undefined. `action()` will never be called.

### PR DESCRIPTION
**Pull request by chlafreniere**
Potentially fixes #8006 but need help thinking through the scenarios.

I can open/close the same markdown file as many times as I want, though, so that's... Progress?

### CODE REVIEW

File: extensions/notebook/src/book/bookTreeView.ts [hunk 1]
```diff
@@ -214,11 +213,19 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
...
-				this._throttleTimer = setTimeout(() => action(), 300);
+				this._throttleTimer = setTimeout(() => {
+					action();
+					this.clearAndResetThrottleTimer();
+				}, 300);
 			}
 		}
 	}
 
+	private clearAndResetThrottleTimer() {
```
Comment (kevcunnane) [inline extensions/notebook/src/book/bookTreeView.ts]: `: void` return type
