### PR TITLE
Fix refreshing nodes in Azure view

### LINKED ISSUE #9184: Refreshing table list doesn't do anything
Issue Type: <b>Bug</b>

Repro:
- Set up Azure account set up with ADS and some Server/Database/Tables to look at the available tables
- Run some queries on that server to drop several tables
- Press refresh on the table-list-header (right mouse button + refresh)
- Doesn't seem to refresh - dropped tables are still there

Same for created tables or similar stuff. 

Azure Data Studio version: azuredatastudio 1.15.0 (e57eb999fc5f1e000477da8fe0b8679ff0bfd57b, 2020-02-12T20:48:43.389Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.2
datavirtualization|Mic|1.3.0

</details>

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #9184

I'm not sure if this ever worked - I went back a couple releases and it was broken there.

In the end this is due to the refresh for asyncDataTree just calling getChildren on the provider when doing a refresh. Since the provider doesn't have any refresh functionality it expects that this will return the current set of children. But we weren't doing that - instead just returning the known set of children nodes and so any changes made after the initial load wouldn't be picked up.

### CODE REVIEW

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts [hunk 1]
```diff
@@ -145,6 +146,28 @@ export class OEShimService extends Disposable implements IOEShimService {
...
+			let sessionId = await this.getOrCreateSession(viewId, node);
+			let requestHandle = this.nodeHandleMap.get(generateNodeMapKey(viewId, node)) || node.handle;
+			let treeNode = new TreeNode(undefined, undefined, undefined, requestHandle, undefined, undefined, undefined, undefined, undefined, undefined);
+			treeNode.connection = new ConnectionProfile(this.capabilities, node.payload);
+			return this.oe.refreshTreeNode({
+				success: undefined,
+				sessionId,
+				rootNode: undefined,
+				errorMessage: undefined
+			}, treeNode).then(e => e.map(n => this.treeNodeToITreeItem(viewId, n, node)));
```
Comment (aaomidi) [inline src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts]: Any reason not to do await here?

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts [hunk 2]
```diff
@@ -145,6 +146,28 @@ export class OEShimService extends Disposable implements IOEShimService {
...
+		} else {
+			return Promise.resolve([]);
```
Comment (aaomidi) [inline src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts]: return [] should also work

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts]: This was just copy-pasted with a minor change so I didn't look over it, I'll refactor to be cleaner though.

File: src/sql/workbench/browser/parts/views/customView.ts [hunk 3]
```diff
@@ -700,7 +700,7 @@ class TreeDataSource implements IAsyncDataSource<ITreeItem, ITreeItem> {
 
 	getChildren(node: ITreeItem): Promise<any[]> {
 		if (node.childProvider) {
-			return this.withProgress(this.objectExplorerService.getChildren(node, this.id)).catch(e => {
+			return this.withProgress(this.objectExplorerService.refreshNode(node, this.id)).catch(e => {
```
Comment (anthonydresser) [inline src/sql/workbench/browser/parts/views/customView.ts]: I would rather hide these details in the oeshim service. Rather than a caller having to explicitly know to call refreshNode vs getchildren, the oeshim services should just do the refresh node as part of the getchildren call if it needs to refresh the node (it already knows about the node).

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts [hunk 4]
```diff
@@ -26,6 +26,7 @@ export const IOEShimService = createDecorator<IOEShimService>(SERVICE_ID);
 export interface IOEShimService {
 	_serviceBrand: undefined;
 	getChildren(node: ITreeItem, viewId: string): Promise<ITreeItem[]>;
+	refreshNode(node: ITreeItem, viewId: string): Promise<ITreeItem[]>;
```
Comment (anthonydresser) [inline src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts]: I wouldn't have a separate function here, this should all just be wrapped up in getchildren.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts]: I'm fine with that - just wasn't sure what the contract was for this service. If you think it's fine I can make that change since that seems to be the assumption that the trees generally have anyways.

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts [hunk 5]
```diff
@@ -130,19 +130,19 @@ export class OEShimService extends Disposable implements IOEShimService {
...
 		if (node.payload) {
-			let sessionId = await this.getOrCreateSession(viewId, node);
-			let requestHandle = this.nodeHandleMap.get(generateNodeMapKey(viewId, node)) || node.handle;
-			let treeNode = new TreeNode(undefined, undefined, undefined, requestHandle, undefined, undefined, undefined, undefined, undefined, undefined);
+			const sessionId = await this.getOrCreateSession(viewId, node);
+			const requestHandle = this.nodeHandleMap.get(generateNodeMapKey(viewId, node)) || node.handle;
+			const treeNode = new TreeNode(undefined, undefined, undefined, requestHandle, undefined, undefined, undefined, undefined, undefined, undefined);
 			treeNode.connection = new ConnectionProfile(this.capabilities, node.payload);
-			return this.oe.resolveTreeNodeChildren({
+			const childrenNodes = await this.oe.refreshTreeNode({
```
Comment (anthonydresser) [inline src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts]: I'm assuming this still works even if its the first time the node is being asked for children?

Comment (Charles-Gagnon) [reply src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts]: Correct. They actually call the same method (refreshOrExpandTreeNode) - but resolveTreeNodeChildren only does a refresh if there's an error message.

https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts#L577

Comment (anthonydresser) [reply src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts]: interesting...
