### PR TITLE
Fix clickable being announced for all modelview text

### LINKED ISSUE #7670: A11y_AzureDataStudio_BigDataClusterOverviewPage_AI4D: Incorrect control type is given for "40.117.212.184,31433" button.
"[Check out Accessibility Insights!](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier."
​
GitHubTags:#A11y_AzureDataStudio;#A11yMAS;#A11yTCS;#WCAG1.3.1;#WCAG4.1.2;DesktopApp;#NVDA;#JAWS;#SQL Azure Data Studio;#AI4D;#Win32

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 6582debd7388b1be512fc3a9b956d3e54f6115e7
Date: 2019-10-03T08:56:27.454Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
NVDA Version: 2019.2
JAWS Version:2019.1907.42 ILM

**Additional Details:**
Tool Name : AI4D

**Steps to Reproduce:**
1. Install and Launch the application the azure data studio application.
2. Open the “Connections” viewlet (CTRL + SHIFT + D)
3. Navigate to the “SQL Server Big Data Clusters” section and expand it
4. Navigate to the "Add SQL Server big data cluster controller…" node and click on it.
5. Fill in the connection information for the BDC Controller Endpoint
6. Click “Add”
7. Navigate to the controller node in the “SQL Server Big Data Clusters” view and right click on it, then select “Manage” to open the dashboard
8. "Big Data Cluster Overview page " should open.
9. Open AI4D.
10. Check the control type given for "40.117.212.184,31433" button.

**Actual:**
Incorrect control type is given for "40.117.212.184,31433" button.

**Similar issue is also observed with JAWS .**
 
**Expected:**
Correct control type should be provided for "40.117.212.184,31433" button.
It should be button .

**User Impact:**
If proper control type is not provided then screen reader users will get confused with the control.

**Attachment for Reference:**
7670_A11y_AzureDataStudio_BigDataClusterOverviewPage_AI4D

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #7802: A11y_AzureDataStudio_ManageAccessForFile_ScreenReader:NVDA announcing the non interactive label as clickble.
GitHubTags: #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG1.3.1;#DesktopApp;#Win32;#NVDA;

**Environment Details: **

Application Name: Azure Data Studio

Version: 1.12.0-insider (user setup)

Commit:6582debd7388b1be512fc3a9b956d3e54f6115e7

Date: 2019-10-03T08:56:27.454Z

VS Code: 1.38.0

Electron: 4.2.10

Chrome: 69.0.3497.128

Node.js: 10.11.0

V8: 6.9.427.31-electron.0

OS: Windows_NT x64 10.0.18362

 

**Additional Details:**

Tool Name : NVDA 2019.2
**Steps to Reproduce:**

1. Install and Launch the application the azure data studio application.

2.Connet to the servers with the required credentials.

3.Navigate to the control panel and click on the “Jupyter books” icon. 

 4.Navigate till HDFS folder and right click on it and click on manage access.

5. Start NVDA and observe the announcement.

**Actual:**
NVDA is announcing the non interactive element as clickable. For example  label and headings.  

 

**Expected:** 
NVDA should announce all non interactive in simple text format not clickable.  
 

**User Impact:**
Screen Reader user will misunderstand if the content is also interactive. 

**Attachment for Reference:**
[7802_A11y_AzureDataStudio_ManageAccessForFile_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3762502/7802_A11y_AzureDataStudio_ManageAccessForFile_ScreenReader.pptx)
Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7802
Fixes #7670

The click handler on the text was causing NVDA to announce it as being clickable. It makes more sense to have clickable text to just be an actual link and then allow callers to pass in an empty URL if they want to handle the click themselves. 

Also fixes #8384 - making them hyperlinks adds them into the list of tabbable elements.

### CODE REVIEW

File: src/sql/azdata.d.ts [hunk 1]
```diff
@@ -3281,16 +3281,17 @@ declare module 'azdata' {
 	}
 
 	export interface TextComponent extends Component, TextComponentProperties {
-		/**
-		 * An event called when the text is clicked
-		 */
-		onDidClick: vscode.Event<any>;
```
Comment (kevcunnane) [inline src/sql/azdata.d.ts]: Can you check this with Alan Ren? Any change that removes a public API should be verified. Did this _never_ work? 

I am concerned here about risk to break existing extensions - please at a minimum check Github and verify nothing is changed. I would strongly suggest holding on this removal, communicating via Github issue / verification with larger team and any partners like SQL Prompt that this isn't used, then and only then remove in an individual PR.

Comment (alanrenmsft) [reply src/sql/azdata.d.ts]: this was introduced on Aug 27, It is very unlikely other folks are using this. but to be safe I like Kevin's idea and we can make it the process of updating/removing public APIs.

Comment (Charles-Gagnon) [reply src/sql/azdata.d.ts]: It did work - I added it myself. I only added it for the BDC dashboard itself so it's highly unlikely anyone else is using it. The only reason I'm changing it is because it's not the right approach from an accessibility standpoint. 

The reason this breaks accessibility is because "clickable" is announced whenever an item has an onclick handler attached to it. And by hooking up the onclick in the angular component we were thus making EVERY text item "clickable" (even if nothing was being done).

A hyperlink is inherently a "clickable text" object so using that instead is the much better approach.

Comment (Charles-Gagnon) [reply src/sql/azdata.d.ts]: We need to have a discussion about this - by leaving the existing click handler in on the text element we're not fixing the accessibility issue. How are we planning on handling updates to existing definitions (such as adding new properties/methods to classes)? That's going to be tricky to do "correctly" through the proposed API...

Comment (Benjin) [reply src/sql/azdata.d.ts]: Is there a way to annotate a property as deprecated so that anything building against it gets flagged?  Would be a good first step as we look to remove it.

Comment (Charles-Gagnon) [reply src/sql/azdata.d.ts]: VS Code just uses the @deprecated tag

https://github.com/microsoft/azuredatastudio/blob/master/src/vs/vscode.d.ts#L1167

Give how few extensions are out there that aren't ours it's probably best to just manually check those to see if they're using the deprecated functions and if so reach out to the author directly. Figuring out some way to alert users of deprecated APIs would be a good idea long term though.

**Comment by Charles-Gagnon** [comment]
@kevcunnane - We discussed this today and the general thought is that since this is so new we're fine in this case to just remove it (I'm still going to go through existing extensions to verify none of them are using it)

Are you ok with this? Going forward the process should be to add new stuff to the proposed API - which is what should have been done here - and so I've moved the new event for the hyperlink control into the proposed API.
