### PR TITLE
Handle undefined error when opening connection dialog

### LINKED ISSUE #21642: Console error when opening Connection dialog without any Azure connections
RC1

1. Remove all registered Azure accounts
2. Open connection dialog
3. If AzureMFA isn't selected select it, then close and reopen connection dialog
4. See error in console `  ERR Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'key')`

### PR DESCRIPTION
**Pull request by cssuh**
Current behavior:
1. Remove all registered Azure accounts
2. Open connection dialog
3. If AzureMFA isn't selected select it, then close and reopen connection dialog
4. See error in console   ERR Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'key')

New Behavior:
- No error message displayed 

This PR fixes #21642

### CODE REVIEW

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 1]
```diff
@@ -957,7 +961,9 @@ export class ConnectionWidget extends lifecycle.Disposable {
 						this.onAzureTenantSelected(0);
 					}
 					else {
-						this._logService.error(`fillInConnectionInputs : Could not find any tenants for account ${accountName}`);
+						if (accountName) {
```
Comment (cheenamalhotra) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:964]: Nit: Combine these into `else if`

**Review by cheenamalhotra — APPROVED** [review]

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 2]
```diff
@@ -936,7 +936,11 @@ export class ConnectionWidget extends lifecycle.Disposable {
 						// If account was not filled in from received configuration, select the first account.
 						this._azureAccountDropdown.select(0);
 						account = this._azureAccountList[0];
-						accountName = account.key.accountId;
+						if (this._azureAccountList.length > 0) {
+							accountName = account.key.accountId;
+						} else {
+							this._logService.info('No accounts available');
+						}
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:943]: Info seems a bit high of a logging level for this. And do we really care about logging it anyways? Not having any accounts isn't really an error situation so as long as we're handling it gracefully that's fine IMO

```suggestion
						accountName = account?.key.accountId;
```

Comment (cssuh) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:943]: Yeah I'll put it in verbose, but in general I think having more logs is better

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 3]
```diff
@@ -936,7 +936,11 @@ export class ConnectionWidget extends lifecycle.Disposable {
 						// If account was not filled in from received configuration, select the first account.
 						this._azureAccountDropdown.select(0);
 						account = this._azureAccountList[0];
-						accountName = account.key.accountId;
+						if (this._azureAccountList.length > 0) {
+							accountName = account.key.accountId;
+						} else {
+							this._logService.debug('No accounts available');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:942]: If you're going to keep this you should indicate where it's coming from (this applies to all debug logging) - a generic message like this could easily be coming from anywhere.

**Review by Charles-Gagnon — APPROVED** [review]
