### PR TITLE
Surfacing extension install errors

### LINKED ISSUE #19369: Fix vsix installation error for extensions that require newer version of  Azure Data Studio
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Install Database Migration Assessment extension in ADS with version less than 1.35.0.
2. Error message shown is not correct

**Error shown on UI:**

image

**Actual Error:**

image

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #19369
1. Surfacing error when user tries to install vsix files that requires a higher version of ADS.
image

2. Surfacing error when user tries to install extension through gallery that requires a higher version of ads.
Now:
image
Before:
image

### CODE REVIEW

File: src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts [hunk 1]
```diff
@@ -1042,7 +1042,9 @@ export class ExtensionsWorkbenchService extends Disposable implements IExtension
 		// The check is added here because we want to fail fast instead of downloading the VSIX and then fail.
 		if (gallery.properties.engine && (!isEngineValid(gallery.properties.engine, this.productService.vscodeVersion, this.productService.date)
 			|| (gallery.properties.azDataEngine && !isEngineValid(gallery.properties.azDataEngine, this.productService.version, this.productService.date)))) {
-			return Promise.reject(new Error(nls.localize('incompatible2', "Unable to install version '{2}' of extension '{0}' as it is not compatible with Azure Data Studio '{1}'.", extension.gallery!.identifier.id, this.productService.version, gallery.version)));
+			const error = new Error(nls.localize('incompatible2', "Unable to install version '{2}' of extension '{0}' as it is not compatible with Azure Data Studio '{1}'.", extension.gallery!.identifier.id, this.productService.version, gallery.version));
```
Comment (Charles-Gagnon) [inline src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts:1045]: Let's be as specific as possible - so include what version of azdataEngine or vscodeVersion is required and what one the install currently has. That'll help users understand what exactly the problem is.

File: src/vs/workbench/contrib/extensions/browser/extensionsActions.ts [hunk 2]
```diff
@@ -299,7 +299,7 @@ export abstract class AbstractInstallAction extends ExtensionAction {
 			// {{SQL CARBON EDIT}}
 			// Prompt the user that the current ADS version is not compatible with the extension,
 			// return here as in this scenario it doesn't make sense for the user to download manually.
-			if (error && error.code === INSTALL_ERROR_INCOMPATIBLE) {
+			if (error && error.name === INSTALL_ERROR_INCOMPATIBLE) {
```
Comment (Charles-Gagnon) [inline src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:302]: Why are you changing it from code to name?

File: src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts [hunk 3]
```diff
@@ -760,7 +760,9 @@ class ExtensionsContributions extends Disposable implements IWorkbenchContributi
 						openLabel: mnemonicButtonLabel(localize({ key: 'installButton', comment: ['&& denotes a mnemonic'] }, "&&Install"))
 					});
 					if (vsixPaths) {
-						await commandService.executeCommand(INSTALL_EXTENSION_FROM_VSIX_COMMAND_ID, vsixPaths);
+						await commandService.executeCommand(INSTALL_EXTENSION_FROM_VSIX_COMMAND_ID, vsixPaths).catch(e => {
```
Comment (Charles-Gagnon) [inline src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts:763]: You can remove the await if you're catching the error here

File: src/vs/workbench/contrib/extensions/browser/extensionsActions.ts (hunk 2 above)
Comment (aasimkhan30) [reply src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:302]: Error does not have any code property to it. 
I can see that it only has name

Comment (Charles-Gagnon) [reply src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:302]: Huh, interesting.

Anyways, it'd be better to make a new superclass error IncompatibleEngineError or something that extends error and check typeof the error object in that case

File: src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts [hunk 4]
```diff
@@ -1042,7 +1042,8 @@ export class ExtensionsWorkbenchService extends Disposable implements IExtension
 		// The check is added here because we want to fail fast instead of downloading the VSIX and then fail.
 		if (gallery.properties.engine && (!isEngineValid(gallery.properties.engine, this.productService.vscodeVersion, this.productService.date)
 			|| (gallery.properties.azDataEngine && !isEngineValid(gallery.properties.azDataEngine, this.productService.version, this.productService.date)))) {
-			return Promise.reject(new Error(nls.localize('incompatible2', "Unable to install version '{2}' of extension '{0}' as it is not compatible with Azure Data Studio '{1}'.", extension.gallery!.identifier.id, this.productService.version, gallery.version)));
+			const error = new ExtensionManagementError(nls.localize('incompatible2', "Unable to install version '{2}' of extension '{0}' as it is not compatible with Azure Data Studio '{1}'. Update to Azure Data Studio {3} to install the extension.", extension.gallery!.identifier.id, this.productService.version, gallery.version, gallery.properties.azDataEngine), INSTALL_ERROR_INCOMPATIBLE);
```
Comment (Charles-Gagnon) [inline src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts:1045]: Oh and when changing VS strings we need to add them to https://github.com/Microsoft/azuredatastudio/blob/ffdefd3b52ec5b2acb6620c0707f99bc0f32faa0/src/sql/base/common/locConstants.ts otherwise they'll get clobbered by the VS langpack strings

Comment (Charles-Gagnon) [reply src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts:1045]: Although actually - if this isn't a string that VS code has themselves we don't need to do that. So check that first and if they don't then this is fine

Comment (aasimkhan30) [reply src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts:1045]: I don't think this is a vscode string as 'Azure Data Studio' in it. Vscode has its own extension installation errors

**Comment by aasimkhan30** [comment]
image
New error message

File: src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts (hunk 4 above)
Comment (Charles-Gagnon) [reply src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts:1045]: Good point 😄

File: src/sql/base/common/locConstants.ts [hunk 5]
```diff
@@ -34,7 +34,7 @@ export function extensionsActionsInstallExtensionCompletedAndReloadRequired(exte
 export function extensionsActionsReinstallActionSuccessReload(extension: string): string { return localize('ReinstallAction.successReload', "Please reload Azure Data Studio to complete reinstalling the extension {0}.", extension); }
 export const extensionsViewletRecommendedExtensions = localize('recommendedExtensions', "Marketplace");
 export const extensionsViewsScenarioTypeUndefined = localize('scenarioTypeUndefined', 'The scenario type for extension recommendations must be provided.');
-export function extensionsWorkbenchServiceIncompatible(extension: string, version: string) { return localize('incompatible', "Unable to install extension '{0}' as it is not compatible with Azure Data Studio '{1}'.", extension, version); }
+export function extensionsWorkbenchServiceIncompatible(extension: string, version: string, requiredVersion: string) { return localize('incompatible', "Unable to install extension '{0}' as it is not compatible with Azure Data Studio '{1}'. Update to Azure Data Studio {3} to install the extension.", extension, version, requiredVersion); }
```
Comment (Charles-Gagnon) [inline src/sql/base/common/locConstants.ts:37]: You skip 2

**Comment by aasimkhan30** [comment]
image
New error message

**Comment by aasimkhan30** [comment]
image

File: src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts [hunk 6]
```diff
@@ -1098,9 +1099,9 @@ export class ExtensionsWorkbenchService extends Disposable implements IExtension
 		}
 
 		return this.galleryService.getCompatibleExtension(extension.gallery.identifier, version)
-			.then(gallery => {
+			.then(async (gallery) => {
 				if (!gallery) {
-					return Promise.reject(new Error(locConstants.extensionsWorkbenchServiceIncompatible(extension.gallery!.identifier.id, version))); // {{SQL CARBON EDIT}} Change vscode to ads
+					return Promise.reject(new Error(locConstants.extensionsWorkbenchServiceIncompatible(extension.gallery!.identifier.id, extension.gallery.version, version, (await extension.getManifest(undefined)).engines.azdata))); // {{SQL CARBON EDIT}} Change vscode to ads
```
Comment (Charles-Gagnon) [inline src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts:1104]: If this is async you should throw instead

Comment (Charles-Gagnon) [inline src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts:1104]: Not going to use ExtensionManagementError?

File: src/vs/platform/extensionManagement/node/extensionManagementService.ts [hunk 7]
```diff
@@ -114,7 +115,7 @@ export class ExtensionManagementService extends AbstractExtensionManagementServi
 			throw new Error(nls.localize('incompatible', "Unable to install extension '{0}' as it is not compatible with the current VS Code engine version '{1}'.", id, product.vscodeVersion));
 		}
 		if (manifest.engines?.azdata && !isEngineValid(manifest.engines.azdata, product.version, product.date)) {
-			throw new Error(nls.localize('incompatibleAzdata', "Unable to install extension '{0}' as it is not compatible with Azure Data Studio '{1}'.", id, product.version));
+			throw new Error(extensionsWorkbenchServiceIncompatible(id, manifest.version, product.version, manifest.engines.azdata));
```
Comment (Charles-Gagnon) [inline src/vs/platform/extensionManagement/node/extensionManagementService.ts:118]: ExtensionManagementError?

**Review by Charles-Gagnon — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]
