### PR TITLE
Handle delayed Notebook provider registration

### LINKED ISSUE #3197: Notebooks: builtin provider always used on reopen with notebook file visible
Open a notebook file in the editor, and close Azure Data Studio.
Reopen and  you'll note that the built-in editor will always be used. This is a bug but it's not immediately clear how best to solve it - seems like we need to detect registration of a file type when that file is already open and somehow refresh?

### LINKED ISSUE #3414: Can't refresh kernel after connect to big data cluster
image

Steps to Reproduce:

1. Run ADS
2. Open a notebook before ADS service starts
3. Select "Add new connection" from "Attach to" and connect to a big data cluster
4. Kernel is "No Kernel"
Expected: Kernel displays all kernels available for big data cluster

### PR DESCRIPTION
**Pull request by kevcunnane**
- Fixes #3197 Notebooks: builtin provider always used on reopen with notebook file visible
- Fixes #3414 Can't refresh kernel after connect to big data cluster

There are 3 parts to this fix:
- If no notebook provider other than the default is installed, we warn users and prompt to install the SQL2019 extension
- We wait on the extension host registration to complete before determining which provider to use
- We know that the extension registration of the provider instance will be after package.json is read, so if we wait after registration for 10 seconds to give this a chance to happen before returning a provider to the front end

### CODE REVIEW

File: src/sql/services/notebook/notebookServiceImpl.ts [hunk 1]
```diff
@@ -18,42 +18,138 @@ import { RenderMimeRegistry } from 'sql/parts/notebook/outputs/registry';
...
+export interface NotebookProviderProperties {
+	provider: string;
+	fileExtensions: string[];
+}
+
+interface NotebookProviderCache {
+	[id: string]: NotebookProviderProperties;
+}
+
+interface NotebookProvidersMemento {
```
Comment (kevcunnane) [inline src/sql/services/notebook/notebookServiceImpl.ts]: This memento is based on capabilities service. I'm using this since it should be a short hop over to fully caching the results instead of having to wait on provider registration in the future

File: src/sql/parts/common/customInputConverter.ts [hunk 2]
```diff
@@ -59,20 +57,23 @@ export function convertEditorInput(input: EditorInput, options: IQueryEditorOpti
...
+				//TODO: We need to pass in notebook data either through notebook input or notebook service
+				let fileName: string = 'untitled';
+				let providerId: string = DEFAULT_NOTEBOOK_PROVIDER;
+				if (input) {
+					fileName = input.getName();
+					providerId = getProviderForFileName(fileName, notebookService);
+				}
+				let notebookInputModel = new NotebookInputModel(uri, undefined, false, undefined);
+				notebookInputModel.providerId = providerId;
+				//TO DO: Second parameter has to be the content.
```
Comment (chlafreniere) [inline src/sql/parts/common/customInputConverter.ts]: Can you clarify this? the 2nd parameter that I see below is fileName

File: src/sql/services/notebook/notebookRegistry.ts [hunk 3]
```diff
@@ -54,42 +55,28 @@ let notebookContrib: IJSONSchema = {
...
-		}
-	}
-
-	private addFileProvider(fileType: string, provider: NotebookProviderDescription) {
-		this.fileToProviders.set(fileType.toUpperCase(), provider);
-	}
-
-	getSupportedFileExtensions(): string[] {
-		return Array.from(this.fileToProviders.keys());
+		this._onNewProvider.fire( { id: provider.provider, properties: provider });
```
Comment (chlafreniere) [inline src/sql/services/notebook/notebookRegistry.ts]: This is super confusing. We don't need to fix this now, but crap... Just looking at this, I have no idea what the difference is between 'provider.provider' and 'provider'.

File: src/sql/parts/common/customInputConverter.ts (hunk 2 above)
Comment (kevcunnane) [reply src/sql/parts/common/customInputConverter.ts]: Great question. I just copied this code (see it's in the red section too). I think we can just remove the comments

File: src/sql/services/notebook/notebookRegistry.ts (hunk 3 above)
Comment (kevcunnane) [reply src/sql/services/notebook/notebookRegistry.ts]: Yeah... agreed. Will see if I can fix
