### PR TITLE
Replace URL and use vscode.URI on local paths

### LINKED ISSUE #11602: Remote Book Version Picker Doesn't Work on Mac
- Azure Data Studio Version:
Version: 1.21.0-insider
Commit: 4f58f53e57011abe6f7c2782d4b87e08507545e7
Date: 2020-07-31T05:50:30.617Z (18 hrs ago)
VS Code: 1.48.0
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Click on more option on the Notebooks Viewlet section.
2. Add Remote Jupyter Book
3. Select a book from tiger toolbox repo 
4. Click Add

Error message:
Invalid URL: /Users/{user}

### PR DESCRIPTION
**Pull request by barbaravaldez**
This PR fixes #11602
Using Node.js url for reading local paths on macOS and Linux was causing issues. 
This PR replaces the Url module and uses vscode uri for reading local paths which is cross platform compatible.

### CODE REVIEW

File: extensions/notebook/src/book/remoteBook.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import * as utils from '../common/utils';
 import { IAsset } from './remoteBookController';
 
 export abstract class RemoteBook {
-	protected _localPath: URL;
+	protected _localPath: vscode.Uri;
 
 	constructor(public remotePath: URL, public outputChannel: vscode.OutputChannel, protected _asset?: IAsset) {
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/remoteBook.ts:13]: You're still using URL here - shouldn't this be updated to Uri as well?

Comment (barbaravaldez) [reply extensions/notebook/src/book/remoteBook.ts:13]: The issue only happens with local paths, but I think you are right. Maybe we should replace completely the other module if we are using vscode uri, instead

File: extensions/notebook/src/book/githubRemoteBook.ts [hunk 2]
```diff
@@ -62,34 +62,32 @@ export class GitHubRemoteBook extends RemoteBook {
 	}
 	public async createDirectory(): Promise<void> {
 		let fileName = this._asset.book.concat('-').concat(this._asset.version).concat('-').concat(this._asset.language);
-		this._localPath = new URL(path.join(this._localPath.href, fileName));
+		this._localPath = vscode.Uri.parse(path.join(this._localPath.fsPath, fileName));
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/githubRemoteBook.ts:65]: `vscode.Uri.file` for local file paths
