### PR TITLE
remove "New File..." from File menu

### LINKED ISSUE #20993: File -> New File (shown twice)
Version: 1.40.0-insider (Universal)
Commit: d5cf088ba7b794859438fd2c1902249fd1e6a947
Date: 2022-10-26T05:49:36.314Z (14 hrs ago)
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.6.0

Steps to Reproduce:
Screen Shot 2022-10-26 at 1 24 21 PM

Expected:
Should only have one `New File` option.

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by caohai**
This PR fixes #20993

VSCode added a new `New File...` entry to the `File` menu. This PR removes this entry as ADS has its own `New File` entry

Before this PR:
image

After this PR:
image

For comparison, ADS 1.39.1:
image

### CODE REVIEW

File: src/vs/workbench/contrib/welcomeViews/common/newFile.contribution.ts [hunk 1]
```diff
@@ -32,11 +32,13 @@ registerAction2(class extends Action2 {
 				primary: KeyMod.Alt + KeyMod.CtrlCmd + KeyMod.WinCtrl + KeyCode.KeyN,
 				weight: KeybindingWeight.WorkbenchContrib,
 			},
-			menu: {
-				id: MenuId.MenubarFileMenu,
-				group: '1_new',
-				order: 2
-			}
+			// {{SQL CARBON EDIT}} - Start
```
Comment (Charles-Gagnon) [inline src/vs/workbench/contrib/welcomeViews/common/newFile.contribution.ts:35]: SQL CARBON EDITs should always have text explaining why we're making a change - in this case `We have our own New File item` should be enough

But did you look to see if we can just use theirs and get rid of ours? If they have an item to make a new blank file already I don't see the reason to keep ours around.

Comment (caohai) [reply src/vs/workbench/contrib/welcomeViews/common/newFile.contribution.ts]: Updated.

Yes I took a look at theirs and it's not very straightforward to just use this and clean up `New File` and `New Query`. Given that I don't have time to look deep into this now, I'll just comment out this part.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by VasuBhog — APPROVED** [review]

**Review by kburtram — APPROVED** [review]
