### PR TITLE
Sign out of GitHub Copilot

### LINKED ISSUE #24478: Add ability to logout of GitHub account from Copilot extension
Currently, there is no easy way to log out of your GitHub account from the Copilot extension within ADS (in the event that you logged in with the wrong account).  If we could add this functionality to log out from the Accounts dialog, that would be great.

Example user issue: https://learn.microsoft.com/en-us/answers/questions/1348464/how-to-sign-out-my-github-account-on-azure-data-st

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR closes #24478

The PR adds functionality to sign out of GitHub Copilot in Azure Data Studio.

The accounts section in ADS will show any active GitHub Copilot sessions that can be signed out of:
image

Clicking on the 'X' will then sign the user out and GitHub Copilot will then show a dialog informing the user to log in to the GitHub Copilot extension:
image

### CODE REVIEW

File: src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts [hunk 1]
```diff
@@ -129,7 +129,13 @@ export class AccountListRenderer extends AccountPickerListRenderer {
 			// templateData.actions.push(new ApplyFilterAction(ApplyFilterAction.ID, ApplyFilterAction.LABEL), actionOptions);
 		}
 
-		const removeAction = this._instantiationService.createInstance(RemoveAccountAction, account);
-		templateData.actions.push(removeAction, actionOptions);
+		if (account.key.providerId === 'github') {
+			const signOutOfGithubCopilot = this._instantiationService.createInstance(GitHubCopilotSignOutAction, account);
+			templateData.actions.push(signOutOfGithubCopilot, actionOptions);
```
[the remark this answers is not in the document]
Comment (lewis-sanchez) [reply src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts:134]: Yeah, it does: 
image

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 2]
```diff
@@ -193,9 +195,39 @@ export class AccountDialog extends Modal {
 				for (const addedProvider of addedProviders) {
 					this.addProvider(addedProvider);
```
Comment (kisantia) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:196]: is there a way for the github provider to get added here, rather than separately in the `then()` below?

Comment (lewis-sanchez) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts:196]: In the body of the loop or below it? I'm not entirely sure. I wasn't able to locate an account object, so I had to go and find sessions for Copilot. I could move the call to `addGitHubCopilotProvider` below this loop to get rid of the second `then`.

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 3]
```diff
@@ -193,9 +195,39 @@ export class AccountDialog extends Modal {
...
 				}
+			})
+			.then(async () => {
+				await this.addGitHubCopilotProvider();
 			});
 	}
 
+	private async addGitHubCopilotProvider(): Promise<void> {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:204]: It would be great to make this generic for all auth providers - the account dialog shouldn't really know anything about specific implementations. What you have here is basically already doing that - but you could finish the job by removing the `providerId === 'github'` check and then using the ID directly along with the session.account.label for the displayName

(of course having two separate "account" services is also not very ideal, but that'd be a bigger refactor. Something to think about @cheenamalhotra @kisantia though as a way to standardize more of our stuff with VS Code)

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 4]
```diff
@@ -193,9 +195,39 @@ export class AccountDialog extends Modal {
...
+		const providers = this._authenticationService.getProviderIds();
+		for (const providerId of providers) {
+			if (providerId === 'github') {
+				const copilotAccounts: azdata.Account[] = [];
+
+				const allSessions = await this._authenticationService.getSessions(providerId);
+				for (const session of allSessions) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:211]: nit - using map here would be clearer

`const copilotAccounts = allSessions.map(s => ...)`

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 5]
```diff
@@ -193,9 +195,39 @@ export class AccountDialog extends Modal {
 				for (const addedProvider of addedProviders) {
 					this.addProvider(addedProvider);
 				}
+			})
+			.then(async () => {
+				await this.addGitHubCopilotProvider();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:200]: You add these on startup, but I don't see anything hooking into updating when a new login is made. Is that being handled so that users don't have to reload the window to get their Copilot account to show up?

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 6]
```diff
@@ -193,9 +195,39 @@ export class AccountDialog extends Modal {
...
+		const providers = this._authenticationService.getProviderIds();
+		for (const providerId of providers) {
+			if (providerId === 'github') {
+				const copilotAccounts: azdata.Account[] = [];
+
+				const allSessions = await this._authenticationService.getSessions(providerId);
+				for (const session of allSessions) {
+					copilotAccounts.push({
+						key: { providerId: 'github', accountId: session.account.id } as azdata.AccountKey,
+						displayInfo: { contextualDisplayName: 'GitHub Copilot', displayName: session.account.label, userId: session.account.label, accountType: 'work_school' } as azdata.AccountDisplayInfo,
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:214]: Can we leave out the accountType? Or even use a value such as the ID instead so it has something? `work_school` doesn't seem accurate here - that's pretty specific to AAD

File: src/sql/platform/accounts/common/accountActions.ts [hunk 7]
```diff
@@ -150,3 +151,28 @@ export class RefreshAccountAction extends Action {
...
+	constructor(
+		private _account: azdata.Account,
+		@IAuthenticationService private readonly authenticationService: IAuthenticationService
+	) {
+		super(GitHubCopilotSignOutAction.ID, GitHubCopilotSignOutAction.LABEL, 'remove-account-action codicon remove');
+	}
+
+	public override async run(): Promise<void> {
+		const providers = this.authenticationService.getProviderIds();
+		for (const providerId of providers) {
```
Comment (Charles-Gagnon) [inline src/sql/platform/accounts/common/accountActions.ts:172]: You know that this is the Github provider, so do you need to loop through all them?

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts (hunk 6 above)
Comment (lewis-sanchez) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts:214]: We can omit it, but it doesn't show this icon in the accounts pane: 
image

Also the Copilot session doesn't include any properties about what account type it is. Just includes the name, provider ID, a couple guid's, and that's it. It's very minimal.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts:214]: Yeah, that's fine (accountType is really just an artifact for Azure accounts anyways)

I'd suggest doing that and then having the view default to the above icon if no accountType is specified. That'll make it a lot easier to use for other types of accounts we want to add later.

File: src/sql/platform/accounts/common/accountActions.ts (hunk 7 above)
Comment (lewis-sanchez) [reply src/sql/platform/accounts/common/accountActions.ts:172]: I wasn't sure if that was guaranteed and didn't want to assume, seeing as to how VS Code also iterated through the providers when they added sign out for Copilot: https://github.com/microsoft/vscode/blob/fbfabc523dd0e0a7ede47ea5e2b2d210e11ded9a/src/vs/workbench/browser/parts/globalCompositeBar.ts#L385

Comment (Charles-Gagnon) [reply src/sql/platform/accounts/common/accountActions.ts:172]: That's a very different implementation. Here you're specifically creating an action for just Github copilot. The code you linked is for creating actions for ALL providers/accounts (that support it)

https://github.com/microsoft/vscode/blob/fbfabc523dd0e0a7ede47ea5e2b2d210e11ded9a/src/vs/workbench/browser/parts/globalCompositeBar.ts#L415

In the future we may want to do something similar so that we don't have to keep creating one-off actions, but for now what you have is fine I think.

File: src/sql/platform/accounts/common/accountActions.ts [hunk 8]
```diff
@@ -150,3 +151,26 @@ export class RefreshAccountAction extends Action {
...
+		@IAuthenticationService private readonly authenticationService: IAuthenticationService
+	) {
+		super(GitHubCopilotSignOutAction.ID, GitHubCopilotSignOutAction.LABEL, 'remove-account-action codicon remove');
+	}
+
+	public override async run(): Promise<void> {
+		const providerId = this._account.key.providerId;
+		const allSessions = await this.authenticationService.getSessions(providerId);
+		const sessionsForAccount = allSessions.filter(s => s.account.label === this._account.displayInfo.userId);
+		await this.authenticationService.removeAccountSessions(providerId, this._account.displayInfo.userId, sessionsForAccount);
```
Comment (cheenamalhotra) [inline src/sql/platform/accounts/common/accountActions.ts:174]: Successfully signed out popup doesn't go away and requires user interaction, please make sure it goes away in 5-10 seconds.

Comment (cheenamalhotra) [inline src/sql/platform/accounts/common/accountActions.ts:174]: How does user sign in to Copilot again?

image
image

**Review by cheenamalhotra — CHANGES_REQUESTED** [review]

File: src/sql/platform/accounts/common/accountViewModel.ts [hunk 9]
```diff
@@ -48,23 +53,61 @@ export class AccountViewModel {
...
+				};
+			} catch (err) {
+				this._logService.warn(`Error getting accounts for provider ${providerMetadata.id} : ${err}`);
+				return undefined;
+			}
+		}));
+		return accounts;
+	}
+
+	private async getAccountForSessions(): Promise<AccountProviderAddedEventParams[]> {
```
Comment (cheenamalhotra) [inline src/sql/platform/accounts/common/accountViewModel.ts:87]: Signing into Copilot doesn't show newly added account in account list, requires ADS to be refreshed.

image

File: src/sql/platform/accounts/common/accountViewModel.ts [hunk 10]
```diff
@@ -48,23 +53,61 @@ export class AccountViewModel {
...
+			}
+
 			return coalesce(accounts);
 		} catch (err) {
 			this._logService.warn(`Error getting account provider metadata : ${err}`);
 			return [];
 		}
 	}
+
+	private async getAccountsForProviders(): Promise<AccountProviderAddedEventParams[]> {
```
[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/platform/accounts/common/accountViewModel.ts:69]: Or maybe just return an empty array? Not much point in returning undefined I think unless we want to differentiate when an error occurred vs there just weren't any accounts....in which case letting the error bubble up is probably a better thing to do.

File: src/sql/platform/accounts/common/accountViewModel.ts (hunk 9 above)
Comment (lewis-sanchez) [reply src/sql/platform/accounts/common/accountViewModel.ts:87]: The account list isn't refreshing. I chained logic used by remove account to remove the github account after signing out, but it didn't work. Most likely because the github account is being hydrated by the session information retrieved from the authentication service and not the account management service, so it's not in the map or list holding the rest of the accounts.

File: src/sql/platform/accounts/common/accountViewModel.ts [hunk 11]
```diff
@@ -48,23 +53,61 @@ export class AccountViewModel {
...
+					key: { providerId: providerId, accountId: session.account.id } as azdata.AccountKey,
+					displayInfo: { contextualDisplayName: providerId, displayName: session.account.label, userId: session.account.label } as azdata.AccountDisplayInfo,
+					isStale: false,
+				}) as azdata.Account;
+			});
+
+			const sessionAccount: AccountProviderAddedEventParams = {
+				addedProvider: {
+					id: providerId,
+					displayName: providerId
```
[the remark this answers is not in the document]
Comment (lewis-sanchez) [reply src/sql/platform/accounts/common/accountViewModel.ts:104]: They wanted it to be generic without having something like `if (providerId === 'github')`

[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/platform/accounts/common/accountViewModel.ts:104]: The session account has a label associated with it - could you just use that? Or is that the username?

If it's the later then for now I think it's fine to have a check here `if github then label = 'Github' else label = id` so at least we handle non-Github accounts more generically. Clearly making this fully generic is going to take a bit more effort, so workarounds like that seem acceptable to me.

File: src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts [hunk 12]
```diff
@@ -129,7 +129,13 @@ export class AccountListRenderer extends AccountPickerListRenderer {
 			// templateData.actions.push(new ApplyFilterAction(ApplyFilterAction.ID, ApplyFilterAction.LABEL), actionOptions);
 		}
 
-		const removeAction = this._instantiationService.createInstance(RemoveAccountAction, account);
-		templateData.actions.push(removeAction, actionOptions);
+		if (account.key.providerId === 'github') {
```
[the remark this answers is not in the document]
Comment (lewis-sanchez) [reply src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts:132]: That comes from the accountType property on the `az.Account` type. The current options are "work_school" and "personal". I'll add an option for github, but I can't infer the account type from the session since it doesn't specify if the session is for a corporate or personal subscription of Copilot.

I was previously defaulting to "work_school", but Charles had pointed out how that didn't make sense and I agree with him.

File: src/sql/platform/accounts/common/accountViewModel.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/platform/accounts/common/accountViewModel.ts:104]: Actually, there's an `authenticationService.getLabel` function too - that one is probably what you'd want to use here.

File: src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts:132]: This is what I was suggesting to update the code to use a default icon if the accountType isn't recognized. And then you can add something for Cheena's suggestion which will use the Github icon when the account is a Github account.

File: src/sql/platform/accounts/common/accountViewModel.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (cheenamalhotra) [reply src/sql/platform/accounts/common/accountViewModel.ts:104]: I agree, push it into the service and make service work for GitHub accounts.

File: src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (lewis-sanchez) [reply src/sql/workbench/services/accountManagement/browser/accountListRenderer.ts:132]: Added github icon for github accounts: 
image

File: src/sql/platform/accounts/common/accountViewModel.ts [hunk 13]
```diff
@@ -48,23 +53,64 @@ export class AccountViewModel {
...
+		return accounts ?? [];
+	}
+
+	private async getAccountForSessions(): Promise<AccountProviderAddedEventParams[]> {
+		const sessionAccounts: AccountProviderAddedEventParams[] = [];
+		const providerIds = this._authenticationService.getProviderIds();
+
+		for (const providerId of providerIds) {
+			const displayName = this._authenticationService.getLabel(providerId);
+			const accountType = providerId === 'github' ? 'github' : 'microsoft'; // TODO: Find a better default account icon.
```
Comment (lewis-sanchez) [inline src/sql/platform/accounts/common/accountViewModel.ts:93]: 'microsoft' account type logo is a generic outline of a person: 
image

File: src/sql/platform/accounts/common/accountActions.ts [hunk 14]
```diff
@@ -150,3 +151,31 @@ export class RefreshAccountAction extends Action {
...
+ * Action to sign out of GitHub Copilot account
+ */
+export class GitHubCopilotSignOutAction extends Action {
+	public static ID = 'account.github.copilot.sign.out';
+	public static LABEL = localize('githubCopilotSignOut', "Sign out of GitHub Copilot");
+	public account?: azdata.Account;
+
+	constructor(
+		private _account: azdata.Account,
+		@IAccountManagementService private _accountManagementService: IAccountManagementService,
```
Comment (Charles-Gagnon) [inline src/sql/platform/accounts/common/accountActions.ts:165]: nit: If we're going to use readonly we should be consistent within a file

```suggestion
		@IAccountManagementService private readonly _accountManagementService: IAccountManagementService,
```

File: src/sql/platform/accounts/common/accountActions.ts [hunk 15]
```diff
@@ -150,3 +151,31 @@ export class RefreshAccountAction extends Action {
...
 	}
 }
+
+/**
+ * Action to sign out of GitHub Copilot account
+ */
+export class GitHubCopilotSignOutAction extends Action {
+	public static ID = 'account.github.copilot.sign.out';
+	public static LABEL = localize('githubCopilotSignOut', "Sign out of GitHub Copilot");
+	public account?: azdata.Account;
```
Comment (Charles-Gagnon) [inline src/sql/platform/accounts/common/accountActions.ts:161]: This doesn't seem to be used anymore. If it is make sure it's being set correctly - and that the type matches what the value can actually be.

File: src/sql/platform/accounts/common/accountViewModel.ts [hunk 16]
```diff
@@ -24,7 +25,11 @@ export class AccountViewModel {
...
 	public get updateAccountListEvent(): Event<UpdateAccountListEventParams> { return this._updateAccountListEmitter.event; }
 
-	constructor(@IAccountManagementService private _accountManagementService: IAccountManagementService, @ILogService private _logService: ILogService) {
+	constructor(
+		@IAccountManagementService private _accountManagementService: IAccountManagementService,
+		@ILogService private _logService: ILogService,
+		@IAuthenticationService private readonly _authenticationService: IAuthenticationService
+	) {
 		// Create our event emitters
 		this._addProviderEmitter = new Emitter<AccountProviderAddedEventParams>();
```
[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/platform/accounts/common/accountViewModel.ts:34]: Good catch, although I'd suggest going through and fixing those as a follow up PR to avoid cluttering up this PR even more

File: src/sql/platform/accounts/common/accountViewModel.ts [hunk 17]
```diff
@@ -24,7 +25,11 @@ export class AccountViewModel {
 	private _updateAccountListEmitter: Emitter<UpdateAccountListEventParams>;
 	public get updateAccountListEvent(): Event<UpdateAccountListEventParams> { return this._updateAccountListEmitter.event; }
 
-	constructor(@IAccountManagementService private _accountManagementService: IAccountManagementService, @ILogService private _logService: ILogService) {
+	constructor(
+		@IAccountManagementService private _accountManagementService: IAccountManagementService,
+		@ILogService private _logService: ILogService,
+		@IAuthenticationService private readonly _authenticationService: IAuthenticationService
```
Comment (Charles-Gagnon) [inline src/sql/platform/accounts/common/accountViewModel.ts:31]: nit: Use of readonly should be consistent within a file
```suggestion
		@IAccountManagementService private readonly _accountManagementService: IAccountManagementService,
		@ILogService private readonly _logService: ILogService,
		@IAuthenticationService private readonly _authenticationService: IAuthenticationService
```

File: src/sql/platform/accounts/common/accountViewModel.ts [hunk 18]
```diff
@@ -48,23 +53,64 @@ export class AccountViewModel {
...
-						addedProvider: providerMetadata,
-						initialAccounts: accounts
-					};
-				} catch (err) {
-					this._logService.warn(`Error getting accounts for provider ${providerMetadata.id} : ${err}`);
-					return undefined;
-				}
-			}));
+			let accounts = await this.getAccountsForProviders();
+			if (this._authenticationService) {
```
Comment (Charles-Gagnon) [inline src/sql/platform/accounts/common/accountViewModel.ts:57]: We should always have an authService (otherwise something is horribly wrong), so I would suggest just removing this check. If tests are failing because you're passing in null then you should be creating a mock service and passing that in instead.

File: src/sql/platform/accounts/common/accountViewModel.ts [hunk 19]
```diff
@@ -48,23 +53,64 @@ export class AccountViewModel {
...
+			try {
+				const accounts = await this._accountManagementService.getAccountsForProvider(providerMetadata.id);
+
+				return <AccountProviderAddedEventParams>{
+					addedProvider: providerMetadata,
+					initialAccounts: accounts
+				};
+			} catch (err) {
+				this._logService.warn(`Error getting accounts for provider ${providerMetadata.id} : ${err}`);
+				return undefined;
```
Comment (Charles-Gagnon) [inline src/sql/platform/accounts/common/accountViewModel.ts:81]: The return type isn't accurate with this - it should be `Promise<(AccountProviderAddedEventParams | undefined)[]>`

That being said, coalescing the results before returning wouldn't be a bad idea just to simplify this a bit

File: src/sql/workbench/services/accountManagement/browser/accountManagementService.ts [hunk 20]
```diff
@@ -63,7 +64,8 @@ export class AccountManagementService implements IAccountManagementService {
 		@ILogService private readonly _logService: ILogService,
 		@INotificationService private readonly _notificationService: INotificationService,
 		@IAdsTelemetryService private _telemetryService: IAdsTelemetryService,
-		@IQuickInputService private _quickInputService: IQuickInputService
+		@IQuickInputService private _quickInputService: IQuickInputService,
+		@IAuthenticationService private readonly _authenticationService: IAuthenticationService
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountManagementService.ts:68]: nit: Update services to all use readonly

File: src/sql/workbench/services/accountManagement/browser/accountManagementService.ts [hunk 21]
```diff
@@ -399,6 +401,27 @@ export class AccountManagementService implements IAccountManagementService {
 		});
 	}
 
+	/**
+	 * Updates the account list for a provider.
+	 * @param provider Provider to update the account list for
+	 */
+	public async updateAccountList(account: azdata.Account): Promise<void> {
+		const sessions = await this._authenticationService.getSessions(account.key.providerId);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountManagementService.ts:409]: You should make it explicitly clear in the doc and/or name for this function that it only handles auth sessions - not accountManagement sessions.

File: src/vs/workbench/api/browser/mainThreadAuthentication.ts [hunk 22]
```diff
@@ -96,7 +96,7 @@ export class MainThreadAuthenticationProvider extends Disposable implements IAut
 		quickPick.show();
 	}
 
-	async removeAccountSessions(accountName: string, sessions: AuthenticationSession[]): Promise<void> {
+	async removeAccountSessions(accountName: string, sessions: AuthenticationSession[], updateAccontList: () => Promise<void> | undefined): Promise<void> { // {{SQL CARBON EDIT}} - Added updateAccountList to update account list after signout or account removal.
```
Comment (Charles-Gagnon) [inline src/vs/workbench/api/browser/mainThreadAuthentication.ts:99]: spelling - `updateAccountList`

File: src/vs/workbench/api/browser/mainThreadAuthentication.ts [hunk 23]
```diff
@@ -112,6 +112,12 @@ export class MainThreadAuthenticationProvider extends Disposable implements IAut
 			await Promise.all(removeSessionPromises);
 			removeAccountUsage(this.storageService, this.id, accountName);
 			this.storageService.remove(`${this.id}-${accountName}`, StorageScope.APPLICATION);
+
+			// {{SQL CARBON EDIT}} - BEGIN - Invoking updateAccountList delegate if a callback definition is defined.
+			if (updateAccontList) {
+				await updateAccontList();
```
Comment (Charles-Gagnon) [inline src/vs/workbench/api/browser/mainThreadAuthentication.ts:118]: Why do we need this callback? Couldn't the caller just await on this function and then call whatever they want to after (such as refreshing the account list)?

File: src/vs/workbench/services/authentication/browser/authenticationService.ts [hunk 24]
```diff
@@ -781,10 +781,10 @@ export class AuthenticationService extends Disposable implements IAuthentication
 		}
 	}
 
-	async removeAccountSessions(id: string, accountName: string, sessions: AuthenticationSession[]): Promise<void> {
+	async removeAccountSessions(id: string, accountName: string, sessions: AuthenticationSession[], updateAccountList: () => Promise<void> | undefined = undefined): Promise<void> { // {{SQL CARBON EDIT}} - Added updateAccountList delegate to update accounts pane after session sign out
 		const authProvider = this._authenticationProviders.get(id);
 		if (authProvider) {
-			return authProvider.removeAccountSessions(accountName, sessions);
+			return authProvider.removeAccountSessions(accountName, sessions, updateAccountList); // {{SQL CARBON EDIT}} - Added updateAccountList delegate to update accounts pane after session sign out
```
Comment (Charles-Gagnon) [inline src/vs/workbench/services/authentication/browser/authenticationService.ts:787]: The auth service has a `onDidChangeSessions` event - could you just use that instead (have the account list hook into that event and update itself on changes) to avoid having to modify VS Code stuff?

**Review by Charles-Gagnon — COMMENTED** [review]
Some tests would be fantastic as well - at least some focused on ensuring that the view model is updated correctly when accounts/sessions are added/removed.

File: src/sql/platform/accounts/common/accountActions.ts (hunk 8 above)
Comment (kisantia) [reply src/sql/platform/accounts/common/accountActions.ts:178]: maybe ADS should be restarted to complete the sign out process to make sure the copilot extension sign in notification is triggered?

**Review by kisantia — APPROVED** [review]
