### PR TITLE
Fix deploy upgrade existing not choosing the correct database

### LINKED ISSUE #14634: Dacpac upgrade existing doesn't remember the correct database
If you right click on a db that isn't the first one on the list, the database in the summary page of the deploy - upgrade existing flow is the first database in the list, not the one that was right clicked. 

Looks like this was a bug already in 1.7.0, before https://github.com/microsoft/azuredatastudio/pull/14285. Might have been exposed by the modelview improvements made in November that caused more events to be fired.

Got missed when another place with the same problem was fixed in https://github.com/microsoft/azuredatastudio/pull/10595

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #14634. The database dropdowns got changed from CategoryValues to strings in https://github.com/microsoft/azuredatastudio/pull/8909 and this missed getting updated. The model.database was getting set to undefined here since databaseDropdownValue.name was undefined, so it defaulted to the first value in the database dropdown.

### CODE REVIEW

**Review by udeeshagautam — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]

File: extensions/dacpac/src/wizard/pages/deployConfigPage.ts [hunk 1]
```diff
@@ -142,12 +142,12 @@ export class DeployConfigPage extends DacFxConfigPage {
 
 		//Handle database changes
 		this.databaseDropdown.onValueChanged(() => {
-			const databaseDropdownValue = this.databaseDropdown.value as azdata.CategoryValue;
+			const databaseDropdownValue = this.databaseDropdown.value;
```
Comment (Benjin) [inline extensions/dacpac/src/wizard/pages/deployConfigPage.ts:145]: can this var be specified as a string instead of casting it later? that'd ensure compile-time correctness

**Review by Benjin — APPROVED** [review]
