### PR TITLE
Handle empty values to determine xml cells

### LINKED ISSUE #24929: Query Results Unexpectedly Interpreted as XML When Blank String ('') Present
Type: <b>Bug</b>

When a blank string is present in the column of a SQL query result set, the other values in the column unexpectedly appear to be interpreted as XML, so that clicking on values opens a new XML file window containing the value.

## Repro Example

```sql
DROP TABLE IF EXISTS #BugReportDemo

-- Create demo table
CREATE TABLE #BugReportDemo (
    ID INT PRIMARY KEY,
    Name VARCHAR(50),
    Age VARCHAR(50),
    Salary DECIMAL(10, 2)
);

-- Insert sample data
INSERT INTO #BugReportDemo (ID, Name, Age, Salary) VALUES (1, 'John Doe', 25, 50000.00);
INSERT INTO #BugReportDemo (ID, Name, Age, Salary) VALUES (2, '', 42, 60000.50);
INSERT INTO #BugReportDemo (ID, Name, Age, Salary) VALUES (3, 'Bob Johnson', 25, 45000.75);
INSERT INTO #BugReportDemo (ID, Name, Age, Salary) VALUES (4, 'Test User', 84, 70000.25);
INSERT INTO #BugReportDemo (ID, Name, Age, Salary) VALUES (5, 'Charlie Brown', 35, 80000.00);

SELECT 
    *
FROM 
    #BugReportDemo

```
image
image

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (3.99GB free)|
|Process Argv|C:\\Users\\ebeery\\Swagelok\\MKT_Swagelok_Marketing_Team - MKT_OPS_Customer_Data_Channel_DDouglas\\MKT_OPS_Customer_Data_Team_Projects\\2021_Data_Validation\\Validation Notebooks\\POS Daily Validation.ipynb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
machine-learning|Mic|0.12.0
net-6-runtime|Mic|1.1.0
powershell|ms-|2022.12.1
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.21.0
sql-database-projects|Mic|1.4.1
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353
azdata-sanddance|msr|4.0.1
sql-prompt|Red|0.2.12

</details>

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes #24929

### CODE REVIEW

File: src/sql/workbench/contrib/query/browser/gridPanel.ts [hunk 1]
```diff
@@ -1173,7 +1173,7 @@ function isJsonCell(value: ICellValue): boolean {
 
 function isXmlCell(value: ICellValue): boolean {
 	let isXML = false;
-	if (value && !value.isNull) {
+	if (value && !value.isNull && value.displayValue.trim() !== '') {
 		parseXMLString(value.displayValue, (err, _) => {
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/query/browser/gridPanel.ts:1177]: should the parseXMLString function treat spaces as valid xml?

Comment (cheenamalhotra) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:1177]: I don't think so, only valid xml contents should be allowed, that have open/close tags which `parseXMLString` can validate.

**Review by kisantia — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]

File: src/sql/workbench/contrib/query/browser/gridPanel.ts (hunk 1 above)
Comment (cheenamalhotra) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:1177]: Since `parseXMLString` is xml2js API, we can't modify it's logic, but we see it treated empty string as s valid XML, which depends if you accept empty values as valid types, but in our case it shouldn't have been the case..
