### PR TITLE
handle query gallery with tags

### LINKED ISSUE #14618: Should not suggest extensions based on .JS file extension
- Azure Data Studio Version: `1.27 RC`

Steps to Reproduce:

1. Open a .JS file

Expected: No extension recommendation prompts

Actual: Prompted to install extensions for .JS files (which we don't have any in marketplace).  When clicking the search button, the search results are incorrectly filtered and show unrelated extension results.

*Prompt*
image

*Search results*
image

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR will fix #14618

file based extension recommendation uses the ext: {extension} to query the extension gallery (you can do the same in extensions view),
image

when the request is received, ADS will ignore the tag filter and return all the extensions.

the fix is to return empty array when we receive a request with tag filtering since our extension metadata doesn't include any tag information.

I have queued a build to verify the fix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=96183&view=results

### CODE REVIEW

File: src/vs/platform/extensionManagement/common/extensionGalleryService.ts [hunk 1]
```diff
@@ -608,6 +608,11 @@ export class ExtensionGalleryService implements IExtensionGalleryService {
 					});
 				}
 			}
+			// ADS doesn't not support extension tags, we need to return empty array to avoid breaking some scenarios. e.g. file extension based recommendations.
```
Comment (kisantia) [inline src/vs/platform/extensionManagement/common/extensionGalleryService.ts:611]: nit: ADS doesn't support

Comment (kisantia) [inline src/vs/platform/extensionManagement/common/extensionGalleryService.ts:611]: does this not need {{SQL CARBON EDIT}} because it's there for the whole function?

**Review by kisantia — APPROVED** [review]

**Comment by alanrenmsft** [comment]
> LGTM. Do we need to do something to avoid the notification prompt? I don't think we want that displaying for every file extension type.

@kburtram with this PR, the prompts will also be muted because there is no extensions matching the ext: fileType query.

File: src/vs/platform/extensionManagement/common/extensionGalleryService.ts (hunk 1 above)
Comment (alanrenmsft) [reply src/vs/platform/extensionManagement/common/extensionGalleryService.ts:611]: this is already inside the {{SQL CARBON EDIT}}

**Review by Charles-Gagnon — APPROVED** [review]
