### PR TITLE
fix the extra large icon issue

### LINKED ISSUE #13521: extra large icons on toolbars and some other buttons
today's insider build.

image

image

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #13521

introduced by https://github.com/microsoft/azuredatastudio/pull/13514

for toolbar, we would like a consistent sizing for all buttons, overwriting the sizing in toolbar container's CSS.
for normal buttons, I am providing a proper default size.

before:

image

image

after:

image

image

### CODE REVIEW

File: src/sql/base/browser/dom.ts [hunk 1]
```diff
@@ -22,21 +21,22 @@ export function convertSize(size: number | string | undefined, defaultValue?: st
 		return defaultValue;
 	}
 	let convertedSize: string = size ? size.toString() : defaultValue;
-	if (!endsWith(convertedSize.toLowerCase(), 'px') && !endsWith(convertedSize.toLowerCase(), '%')) {
+	convertedSize = convertedSize.toLowerCase();
```
Comment (alanrenmsft) [inline src/sql/base/browser/dom.ts:24]: not related to the issue, I was looking at the implementation here and saw the obsolete functions being used here. so I replaced the obsolete endsWith function with String.endsWith function

**Review by kburtram — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
For additional context - Alan and I discussed this and while using important! is not ideal we don't really have a good way to enforce the size for the toolbar items since the toolbar is just a container and those don't have direct control over the child component properties so they can be updated on their own at any time.

What might be interesting is to allow containers to tell their child components to use the parent value for certain things instead of whatever is set on the component. This is actually something that could be relevant to https://github.com/microsoft/azuredatastudio/pull/13524 as well for having containers control the enabled status of their children.
