### PR TITLE
Use a different config name for connection sorting

### LINKED ISSUE #15272: Settings error with connections.sortBy configuration
```
workbench.desktop.main.js:1256 Conflict in default settings: Ignoring datasource.connections.sortBy as datasource.connections is []
```

Pretty sure this is because the configuration stuff parses out .'s as being object properties, so by saying a configuration has the name `datasource.connections.sortBy` we're looking for the `sortBy` property in the `datasource.connections` configuration (which we already use as an array of connections so then fails)

We need to use a different name for this to avoid that.

### PR DESCRIPTION
**Pull request by caohai**
This PR fixes #15272 by using a different config name for connection sorting. The original implementation was in #15229 .

### CODE REVIEW

**Comment by caohai** [comment]
I updated the loc id for the two enum options as well just to be consistent and avoid any confusion.

**Review by Charles-Gagnon — COMMENTED** [review]
Let's go with `datasource.connectionsSortOrder` instead to match what the other sorting settings in VS Code are 

image

**Comment by caohai** [comment]
> Let's go with `datasource.connectionsSortOrder` instead to match what the other sorting settings in VS Code are
> 
> image

Done. I also updated enum variable name and setting description just to be consistent.

File: src/sql/platform/connection/common/connectionConfig.ts [hunk 1]
```diff
@@ -16,9 +16,9 @@ import { deepClone } from 'vs/base/common/objects';
 
 export const GROUPS_CONFIG_KEY = 'datasource.connectionGroups';
 export const CONNECTIONS_CONFIG_KEY = 'datasource.connections';
-export const CONNECTIONS_SORT_BY_CONFIG_KEY = 'datasource.connections.sortBy';
+export const CONNECTIONS_SORT_BY_CONFIG_KEY = 'datasource.connectionsSortOrder';
```
Comment (alanrenmsft) [inline src/sql/platform/connection/common/connectionConfig.ts:19]: if the name is sortOrder, I would expect the values being 'Ascending', 'Descending'. Is there something wrong with SortBy?

Comment (Charles-Gagnon) [reply src/sql/platform/connection/common/connectionConfig.ts:19]: I'm just going off what VS Code has already. Better to be consistent in this case I think

image

**Review by Charles-Gagnon — APPROVED** [review]
