### PR TITLE
Fix for adventureworks formatting issue

### LINKED ISSUE #9040: Column values incorrectly displayed when adding a new row with Edit Data
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Edit Data on a table 
2. Add a new row
3. Tab to skip providing values for some columns

Expected: The skipped columns have a default value or say NULL when not in focus
Actual:  A bunch of columns say TBD and the `<` and `>` characters are improperly escaped

image

### PR DESCRIPTION
**Pull request by smartguest**
The column formatter adds additional formatting that is unnecessary for its purpose, so they have been removed.

This PR fixes #9040

### CODE REVIEW

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 1]
```diff
@@ -1066,7 +1066,7 @@ export class EditDataGridPanel extends GridParentComponent {
 			cellClasses += ' missing-value';
 		}
 		else if (Services.DBCellValue.isDBCellValue(value)) {
-			valueToDisplay = (value.displayValue + '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
+			valueToDisplay = (value.displayValue + '');
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: this is unnecessary now because it's being handled somewhere else?

Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: It isn't handled here, are there any instances that might require escaping characters?

Comment (kburtram) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: @smartguest thanks.  In general it is good to root cause the exact reason by the application behavior.  i.e., if this is no longer needed we should understand why not and how character escaping is being handled now.  This helps understand if there are potential side-effects from a change.
