### PR TITLE
Error out for unsupported dotnet versions for sql db projects

### LINKED ISSUE #15053: Show better error for unsupported (lower) versions of Dotnet installed for SqlDB Project
- Azure Data Studio Version:

Steps to Reproduce:

1. Currently we give the right set of errors if no dotnet is installed

"The .NET Core SDK cannnot be located. Project build will not work. Please install .NET Core SDK version 3.1 or update the .Net Core SDK location in settings if already installed."

2. BUT if dotnet is present but the version is such that it might not be supported the error is only limited to whatever error  dotnet build is giving. We should have a more clear error for the same.

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #15053. It adds an extra check to determine the installed dotnet core version and verify if it is supported or not.

### CODE REVIEW

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 1]
```diff
@@ -96,13 +110,45 @@ export class NetCoreTool {
 		return undefined;
 	}
 
+	private get isNetCoreVersionSupported(): boolean | undefined {
+		try {
+			let spawnSync = require('child_process').spawnSync;
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:115]: Requires should go at the top of the file and use the import syntax `import * as child_process from 'child_process'`

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 2]
```diff
@@ -96,13 +110,45 @@ export class NetCoreTool {
...
+			let child;
+
+			child = spawnSync('dotnet --version', [], {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:118]: You should avoid using sync functions for potentially long-running operations (basically any external operations). Would suggest using the async versions and having this function be async itself.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 3]
```diff
@@ -96,13 +110,45 @@ export class NetCoreTool {
 		return undefined;
 	}
 
+	private get isNetCoreVersionSupported(): boolean | undefined {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:113]: Add comments explaining what "supported" means.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 4]
```diff
@@ -96,13 +110,45 @@ export class NetCoreTool {
...
+			let child;
+
+			child = spawnSync('dotnet --version', [], {
+				encoding: 'utf-8',
+				shell: true
+			});
+
+			let versions = String(child.stdout).split('.', 2);
+
+			if (Number(versions[0]) < 3) {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:125]: Please either add a comment explaining these values or use consts with clear names

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 5]
```diff
@@ -36,16 +40,27 @@ export class NetCoreTool {
 
 	private static _outputChannel: vscode.OutputChannel = vscode.window.createOutputChannel(projectsOutputChannel);
 
+	private netCoreInstallationPresent: boolean | undefined;
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:43]: Why do you need another property when you already have `netCoreInstallationPresent`?

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 6]
```diff
@@ -96,13 +110,45 @@ export class NetCoreTool {
...
+				return true;
+			} else {	// major version = 3
+				if (Number(versions[1]) >= 1) {
+					return true;
+				} else {
+					return false;
+				}
+			}
+		} catch (err) {
+			return undefined;
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:137]: Would suggest logging to console or output channel so you can debug failures

**Comment by kisantia** [comment]
looks like the extensionsGallery.json got added to this PR on accident. Please undo those changes

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 5 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts:43]: I used the new one to store the value, so that the new code that looks at "isNetCoreInstallationPresent" property- doesn't have to go through the whole processing again. Is there a better way to do it?

Comment (Charles-Gagnon) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts:43]: Are you ok with this one not necessarily being accurate? How often is findOrInstallNetCore called? It just seems like the small overhead of checking whether a file exists is worth not having to try and keep the state in sync here - but if you expect to query this property a whole bunch then it might be worth it.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 7]
```diff
@@ -18,9 +18,13 @@ export const NetCoreInstallLocationKey: string = 'netCoreSDKLocation';
 export const NetCoreDoNotAskAgainKey: string = 'netCoreDoNotAsk';
 export const NextCoreNonWindowsDefaultPath = '/usr/local/share';
 export const NetCoreInstallationConfirmation: string = localize('sqlDatabaseProjects.NetCoreInstallationConfirmation', "The .NET Core SDK cannot be located. Project build will not work. Please install .NET Core SDK version 3.1 or update the .Net Core SDK location in settings if already installed.");
+export const NetCoreSupportedVersionInstallationConfirmation: string = localize('sqlDatabaseProjects.NetCoreSupportedVersionInstallationConfirmation', "The .NET Core SDK that was found isn't a supported version. Project build will not work. Please install .NET Core SDK version 3.1 or update the .Net Core SDK supported version location in settings if already installed.");
```
Comment (kisantia) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:21]: can the currently installed .Net Core SDK version be added to this message?

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 8]
```diff
@@ -36,16 +40,27 @@ export class NetCoreTool {
 
 	private static _outputChannel: vscode.OutputChannel = vscode.window.createOutputChannel(projectsOutputChannel);
 
+	private netCoreInstallationPresent: boolean | undefined;
+
+	private osPlatform: string = os.platform();
+
 	public async findOrInstallNetCore(): Promise<boolean> {
```
Comment (Benjin) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:47]: With this new state (found but insufficient version), I'm wondering if this logic should be refactored slightly to either return an enum as a result (something like `{notFound, foundGood, foundOldVersion}`) so that we don't have to keep track of extra state outside the scope of this function and what it returns.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 2 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: Fixed it to use async version of spawn.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 5 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: Got rid of the newly added property.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 7 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: Added it in the message.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 8 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts:44]: I did introduce a new enum, not exactly here, but does a similar job that you explained here.

File: extensions/sql-database-projects/src/common/constants.ts [hunk 9]
```diff
@@ -251,6 +251,15 @@ export const externalStreamingJobFriendlyName = localize('externalStreamingJobFr
 export const preDeployScriptFriendlyName = localize('preDeployScriptFriendlyName', "Script.PreDeployment");
 export const postDeployScriptFriendlyName = localize('postDeployScriptFriendlyName', "Script.PostDeployment");
 
+// Build
+
+export const NetCoreInstallationConfirmation: string = localize('sqlDatabaseProjects.NetCoreInstallationConfirmation', "The .NET Core SDK cannot be located. Project build will not work. Please install .NET Core SDK version 3.1 or update the .Net Core SDK location in settings if already installed.");
```
Comment (kisantia) [inline extensions/sql-database-projects/src/common/constants.ts:256]: nit: update the last .Net to be .NET like the previous 2 (also in the string below)

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 10]
```diff
@@ -35,17 +37,27 @@ export interface DotNetCommandOptions {
 export class NetCoreTool {
 
 	private static _outputChannel: vscode.OutputChannel = vscode.window.createOutputChannel(projectsOutputChannel);
+	private osPlatform: string = os.platform();
+	private netCoreSdkInstalledVersion: string | undefined;
+	private netCoreError: netCoreFindError = netCoreFindError.noError;
 
 	public async findOrInstallNetCore(): Promise<boolean> {
```
Comment (kisantia) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:44]: add doc comments to explain what the return value of true and false mean

**Review by kisantia — APPROVED** [review]

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 11]
```diff
@@ -96,13 +111,63 @@ export class NetCoreTool {
...
+			console.log(err);
+			return undefined;
+		}
+	}
+
+	private onExit(childProcess: child_process.ChildProcess): Promise<boolean | undefined> {
+		return new Promise((resolve, reject) => {
+			childProcess.on('exit', () => {
+				let isSupported: boolean = false;
+				if (semver.gte(this.netCoreSdkInstalledVersion!, '3.1.0')) {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:149]: You should avoid having magic numbers like this - it makes it difficult to update/find later on. Would suggest using a single const value and then making any comments which reference this specific version instead just say something like "min required version"

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 12]
```diff
@@ -96,13 +111,63 @@ export class NetCoreTool {
...
+					isSupported = true;
+				}
+				resolve(isSupported);
+			});
+			childProcess.on('error', () => {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:154]: Not going to reject with the actual error? Would be useful for debugging purposes

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 13]
```diff
@@ -35,17 +37,27 @@ export interface DotNetCommandOptions {
 export class NetCoreTool {
 
 	private static _outputChannel: vscode.OutputChannel = vscode.window.createOutputChannel(projectsOutputChannel);
+	private osPlatform: string = os.platform();
+	private netCoreSdkInstalledVersion: string | undefined;
+	private netCoreError: netCoreFindError = netCoreFindError.noError;
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:42]: `netCoreError` doensn't really seem accurate here. Something like `netcoreInstallState` would be better I think

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 14]
```diff
@@ -35,17 +37,27 @@ export interface DotNetCommandOptions {
...
 
 	public async findOrInstallNetCore(): Promise<boolean> {
-		if (!this.isNetCoreInstallationPresent && vscode.workspace.getConfiguration(DBProjectConfigurationKey)[NetCoreDoNotAskAgainKey] !== true) {
+		this.netCoreError = netCoreFindError.noError;
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:45]: There's a potential for a race condition here if something in the background tries to run some command while we're still searching for it. Would probably be better to just set this after the if check when we know that it's been found.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 15]
```diff
@@ -70,9 +86,8 @@ export class NetCoreTool {
 	}
 
 	private get defaultLocalInstallLocationByDistribution(): string | undefined {
-		const osPlatform: string = os.platform();
-		return (osPlatform === 'win32') ? this.defaultWindowsLocation :
-			(osPlatform === 'darwin' || osPlatform === 'linux') ? this.defaultnonWindowsLocation :
+		return (this.osPlatform === winPlatform) ? this.defaultWindowsLocation :
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:89]: A switch statement would be cleaner here

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 16]
```diff
@@ -163,3 +228,9 @@ export class NetCoreTool {
 			});
 	}
 }
+
+export const enum netCoreFindError {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:232]: Generally stuff like this would go at the top of the file

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 17]
```diff
@@ -35,17 +37,27 @@ export interface DotNetCommandOptions {
...
 	private static _outputChannel: vscode.OutputChannel = vscode.window.createOutputChannel(projectsOutputChannel);
+	private osPlatform: string = os.platform();
+	private netCoreSdkInstalledVersion: string | undefined;
+	private netCoreError: netCoreFindError = netCoreFindError.noError;
 
 	public async findOrInstallNetCore(): Promise<boolean> {
-		if (!this.isNetCoreInstallationPresent && vscode.workspace.getConfiguration(DBProjectConfigurationKey)[NetCoreDoNotAskAgainKey] !== true) {
+		this.netCoreError = netCoreFindError.noError;
+		if ((!this.isNetCoreInstallationPresent || !await this.isNetCoreVersionSupported()) &&
+			vscode.workspace.getConfiguration(DBProjectConfigurationKey)[NetCoreDoNotAskAgainKey] !== true) {
```
[the remark this answers is not in the document]
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: It should. Fixed it. Thanks for catching that.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 12 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: Added console.log to throw the original error.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 13 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: Updated this.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 14 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: Makes sense. Updated it.

**Comment by SakshiS-harma** [comment]
Created another issue for default installation location changer for Linux (a few tests were failing and I want to check in by today).
https://github.com/microsoft/azuredatastudio/issues/16598

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 18]
```diff
@@ -96,13 +125,64 @@ export class NetCoreTool {
 		return undefined;
 	}
 
+	/**
+	 * This function checks if the installed dotnet version is 3.1 or greater.
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:129]: Don't hardcode the values here - just refer to the min version var

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 19]
```diff
@@ -96,13 +125,64 @@ export class NetCoreTool {
...
+			console.log(err);
+			return undefined;
+		}
+	}
+
+	private onExit(childProcess: child_process.ChildProcess): Promise<boolean | undefined> {
+		return new Promise((resolve, reject) => {
+			childProcess.on('exit', () => {
+				let isSupported: boolean = false;
+				if (semver.gte(this.netCoreSdkInstalledVersion!, minSupportedNetCoreVersion)) {		// Net core version greater than or equal to 3.1 are supported for Build
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:163]: update comment to just refer to var

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 20]
```diff
@@ -96,13 +125,64 @@ export class NetCoreTool {
...
+					isSupported = true;
+				}
+				resolve(isSupported);
+			});
+			childProcess.on('error', (err) => {
+				console.log(err);
+				reject(undefined);
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:170]: You should generally be rejecting with an error, it'd be unexpected to have a rejection throw undefined

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 19 above)
Comment (Charles-Gagnon) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts:163]: Would suggest wrapping this in a try catch in case you get back an invalid string and the comparison fails (it'd be stuck here forever then)

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 21]
```diff
@@ -96,13 +125,64 @@ export class NetCoreTool {
...
+		try {
+			const spawn = child_process.spawn;
+			let child: child_process.ChildProcessWithoutNullStreams;
+			let isSupported: boolean | undefined = undefined;
+
+			child = spawn('dotnet --version', [], {
+				shell: true
+			});
+
+			child.stdout.on('data', (data) => {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:144]: I don't think we should be assuming that when we get a data event it's going to be the entire string we need. 

https://nodejs.org/api/stream.html#stream_class_stream_readable

Generally you should be batching up the data and then when you get the stream exit event take that buffer and turn it into a string then. 

See https://github.com/microsoft/azuredatastudio/blob/main/extensions/azdata/src/common/childProcess.ts#L51 for an example

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 22]
```diff
@@ -96,13 +125,64 @@ export class NetCoreTool {
...
+				this.netCoreInstallState = netCoreInstallState.netCoreVersionNotSupported;
+			}
+			return isSupported;
+		} catch (err) {
+			console.log(err);
+			return undefined;
+		}
+	}
+
+	private onExit(childProcess: child_process.ChildProcess): Promise<boolean | undefined> {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:159]: This isn't really clear what it's doing or what the return value means. Would suggest updating the name and/or adding documentation to make this clear.

Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: Removed this separate method and merged it in the parent method.

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 19 above)
Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: After merging onExit method in the parent method, there wouldn't be a need to add an extra try-catch , there is one already- so removed that.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by Benjin — APPROVED** [review]
