### PR TITLE
SQL Migration extension - accessibility bug - fixes filter enter and focus

### LINKED ISSUE #15855: A11y_AzureDataStudioSQLMigration_MigratetoAzureSQL_MigrationAssessment_Keyboard:Typing in search form field and pressing enter key closes the migration assessment screen and no search results are displayed.
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AZUREDATASTUDIOSQLMigration_June2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG4.2.2;#AINotInScope;#Keyboard

### Environment Details:
Application Name: SQL Azure Data Studio
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure SQL Migration.
2. Connect to any sql server.
3. Tab till Azure SQL migration Tab and press enter.
4. Tab till Migrate to azure sql and press enter.
5. Add azure account and tab till next button and press enter.
6. Select SQL server on azure virtual machine radio button and tab till view/select button and press enter.
7. Tab till Search form field.

### Actual:
Typing in search form field and pressing enter key closes the migration assessment screen and no search results are displayed.

### Expected:
When pressing enter key the results should be displayed or if there are no matching results a status message should be displayed as no results found.

### User Impact:
Keyboard only users will not be able to search anything in the screen.

### PR DESCRIPTION
**Pull request by brian-harris**
This PR fixes #15855 

* set focus to first control when Assessment results dialog is opened
* implement database filter in assessment results dialog
* block enter key in assessment results filter textbox from closing dialog
* set focus to first control when Migration status dialog is opened
* block enter key in migration status search from closing dialog

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
FYI @brian-harris to auto-close multiple issues you have to put a keyword before each issue link, e.g. `fixes #1234 and fixes #1235`

File: extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts [hunk 1]
```diff
@@ -46,7 +46,8 @@ export class AssessmentResultsDialog {
 					}).component();
 					flex.addItem(await this._tree.createRootContainer(view), { flex: '1 1 auto' });
 
-					view.initializeModel(flex);
+					await view.initializeModel(flex);
+					await this._tree.focusComponent.focus();
```
Comment (Charles-Gagnon) [inline extensions/sql-migration/src/dialog/assessmentResults/assessmentResultsDialog.ts:50]: The modal dialogs are supposed to pick the first tabbable element on a page when they're shown - @aasimkhan30 could you work with Brian to figure out if there's a bug with the base implementation of that logic? Ideally we shouldn't need every person creating a dialog to manually set the focus unless they want to focus something besides the first tabbable element on a page

https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/browser/modal/modal.ts#L384

File: extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts [hunk 2]
```diff
@@ -201,9 +203,30 @@ export class SqlDatabaseTree {
...
+					const cell: any = row[1]?.value;
+					const cellText: string = cell?.items[1]?.value?.toLowerCase();
+					const searchText: string = value.toLowerCase();
+					if (cellText?.includes(searchText)) {
+						filter.push(index);
+					}
+				});
+			}
+
+			this._databaseTable.setFilter(
```
Comment (Charles-Gagnon) [inline extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts:225]: I'd suggest adding a debounce for this so you aren't sending too many of these if the user is typing really fast

File: extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts [hunk 3]
```diff
@@ -215,6 +219,25 @@ export class SqlDatabaseTree {
 		return searchContainer;
 	}
 
+	@debounce(500)
+	private _filterTableList(value: string): void {
+		if (this._databaseTableValues && value && value.length > 0) {
```
Comment (Charles-Gagnon) [inline extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts:224]: FYI you can use null-coalescing to shorten checks like this `if (this._databaseTableValues && value?.length > 0)`

File: extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts [hunk 4]
```diff
@@ -215,6 +219,25 @@ export class SqlDatabaseTree {
...
+			const filter: number[] = [];
+			this._databaseTableValues.forEach((row, index) => {
+				const cell: any = row[1]?.value;
```
Comment (Charles-Gagnon) [inline extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts:227]: I believe this should be DeclarativeTableCellValue. Try to avoid using any whenever you can so we can take advantage of the type-safety that Typescript brings.

File: extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts [hunk 5]
```diff
@@ -72,7 +72,7 @@ export class MigrationStatusDialog {
 			this._view.onClosed(e => {
 				clearInterval(this._autoRefreshHandle);
 			});
-			return view.initializeModel(form);
+			return await view.initializeModel(form);
```
Comment (Charles-Gagnon) [inline extensions/sql-migration/src/dialog/migrationStatus/migrationStatusDialog.ts:75]: Were you seeing a bug here or something? You can just return the promise directly here as it was doing before (and no need to make it async). Making it async and awaiting here is just adding extra overhead (since the async will result in it being wrapped in a promise again) and doesn't change how this functions.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]
