### PR TITLE
fix for parameterized notebook closure.

### LINKED ISSUE #14127: Unable to close notebook without saving
Issue Type: <b>Bug</b>

I seem to be unable to exit a notebook without saving changes, whether or not I have made the changes myself or (in the gif) using an external process like my parameterization test notebook.

Azure Data Studio - Unable to Close without Saving

Azure Data Studio version: azuredatastudio-insiders 1.26.0-insider (8651db1e7edfe83452c01c6aeb4cfe6d20baabfa, 2021-01-28T07:00:09.975Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (0.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
sales-by-salesperson|Adv|0.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
adslivesite|Mic|0.0.36
agent|Mic|0.47.0
arc|Mic|0.7.1
asde-deployment|Mic|0.4.0
azdata|Mic|0.5.1
azuredatastudio-mysql|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.6.0
datavirtualization|Mic|1.12.0
import|Mic|1.2.0
kusto|Mic|0.4.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.8.0
sql-database-projects|Mic|0.5.1
azdata-sanddance|msr|3.1.0
azuredatabot|vas|0.0.2

</details>

### PR DESCRIPTION
**Pull request by MaddyDev**
Issue: When a parameterized notebook is loaded, it updates the contents of the notebook which triggers the notebook content changed event and updates the version. When trying to close the notebook without saving it calls revert which calls load notebook and which again triggers the content update and leaving it in dirty state always.

Fix:
Do not consider changes during load time as dirty.

This PR addresses #14127

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts [hunk 1]
```diff
@@ -245,6 +248,7 @@ export abstract class NotebookInput extends EditorInput {
 
 	public revert(group: GroupIdentifier, options?: IRevertOptions): Promise<void> {
 		return this._textInput.revert(group, options);
+		// return this._textInput.revert(group, { soft: true });
```
Comment (barbaravaldez) [inline src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts:251]: nit: remove the commented line

**Review by barbaravaldez — APPROVED** [review]

**Review by VasuBhog — APPROVED** [review]
Tested this and works as expected on both Mac and Windows!

**Review by Charles-Gagnon — COMMENTED** [review]
Is it possible for someone to type anything into a notebook before loadContents is finished executing? We should still be marking those changes as making the Notebook dirty if so.

Did you look into adding an additional parameter to onCellChange to indicate whether a particular change should mark the Notebook as dirty? That might be a safer way.

**Comment by Charles-Gagnon** [comment]
It also looks like this broke the Notebook unit tests

**Comment by MaddyDev** [comment]
> Is it possible for someone to type anything into a notebook before loadContents is finished executing? We should still be marking those changes as making the Notebook dirty if so.
> 
> Did you look into adding an additional parameter to onCellChange to indicate whether a particular change should mark the Notebook as dirty? That might be a safer way.

Notebook UI doesn't show any contents until the loadContents is complete. 
As for the second question, any change should mark the notebook dirty, this is only to handle the corner case when notebook contents are updated during load in a parameterized notebook.
