### PR TITLE
- Adding mouse in and out styling to clickbale divs

### LINKED ISSUE #15734: A11y_AzureDataStudioSQLMigration_AzureSQLMigration_Keyboard:There is no visible indication of focus on the Data migration in progress tab.
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AZUREDATASTUDIOSQLMigration_June2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG2.4.7;#AINotInScope;#focusvisible;#keyboard

### Environment Details:
Application Name: SQL Azure Data Studio
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure SQL Migration.
2. Connect to any sql server.
3. Tab till Azure SQL migration Tab and press enter.
4. Tab till Data migration in progress tab item and check if there is a visible indication of focus present on the link.

### Actual:
There is no visible indication of focus on the Data migration in progress tab.
This issue is observed with Migration completed tab.

### Expected:
There should be a visible indication of focus provided for the data migration progress tab.

### User Impact:
Users using keyboard to navigate will not know where the focus is situated.

### PR DESCRIPTION
**Pull request by aasimkhan30**
-Moving dashboard card styling to outer div container from inner form container

This PR fixes #15734 

Fixing focus outline
Before:
image
After:
image

Before:
image
Fixing hover background
image

Focus and hover on different themes:
Dark:
image
Light:
image
HC:
image

### CODE REVIEW

File: extensions/sql-migration/src/dashboard/sqlServerDashboard.ts [hunk 1]
```diff
@@ -488,7 +491,13 @@ export class DashboardWidget {
 		const compositeButton = this._view.modelBuilder.divContainer().withItems([flex]).withProps({
 			ariaRole: 'button',
 			ariaLabel: 'show status',
```
Comment (Charles-Gagnon) [inline extensions/sql-migration/src/dashboard/sqlServerDashboard.ts:493]: This should be localized (check the other buttons and such on this page too)

File: src/sql/workbench/browser/modelComponents/divContainer.component.ts [hunk 2]
```diff
@@ -18,14 +18,21 @@ import { KeyCode } from 'vs/base/common/keyCodes';
...
+import * as colorRegistry from 'vs/platform/theme/common/colorRegistry';
 
 class DivItem {
 	constructor(public descriptor: IComponentDescriptor, public config: azdata.DivItemLayout) { }
 }
 
 @Component({
 	template: `
-		<div #divContainer *ngIf="items" class="divContainer" [ngStyle]="CSSStyles" [style.height]="height" [style.width]="width" [style.display]="display" (keyup)="onKey($event)" [attr.role]="ariaRole" [attr.aria-selected]="ariaSelected">
+		<style>
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/divContainer.component.ts:30]: styles should go in a corresponding stylesheet, not in the template

File: src/sql/workbench/browser/modelComponents/divContainer.component.ts [hunk 3]
```diff
@@ -169,4 +184,18 @@ export default class DivContainer extends ContainerBase<azdata.DivItemLayout, az
 			this.cancelClick = undefined;
 		}
 	}
+
+	public onMouseOver(): void {
+		// not forcing the mouse in styling on non-clickable divs
+		if (this.clickable) {
+			this.divContainer.nativeElement.style.backgroundColor = this._colorTheme.getColor(colorRegistry.editorHoverBackground).toString();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/divContainer.component.ts:191]: I would suggest using a CSS rule with the hover selector instead of manually hooking up the mouseover/mouseout events : 

https://www.w3schools.com/cssref/sel_hover.asp

And then just have a hoverBackground color property that's either the editorHoverBackground color or the default background color

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/sql-migration/src/constants/strings.ts [hunk 4]
```diff
@@ -290,6 +290,7 @@ export const SUCCESSFULLY_MIGRATED_TO_AZURE_SQL = localize('sql.migration.succes
 export const MIGRATION_NOT_STARTED = localize('sql.migration.migration.not.started', "Migration not started");
 export const CHOOSE_TO_MIGRATE_TO_AZURE_SQL = localize('sql.migration.choose.to.migrate.to.azure.sql', "Choose to migrate to Azure SQL");
 export const COMING_SOON = localize('sql.migration.coming.soon', "Coming soon");
+export const SHOW_STATUS = localize('sql.migration.show.status', "show status");
 export function MIGRATION_INPROGRESS_WARNING(count: number) {
```
Comment (brian-harris) [inline extensions/sql-migration/src/constants/strings.ts:294]: Should the text be 'Show status' using sentence casing?

File: extensions/sql-migration/src/dashboard/sqlServerDashboard.ts [hunk 5]
```diff
@@ -286,7 +286,7 @@ export class DashboardWidget {
 			const failedMigrations = filterMigrations(migrations, AdsMigrationStatus.FAILED);
 			const failedCount = failedMigrations.length;
 			if (failedCount > 0) {
-				this._failedMigrationButton.container.display = 'inline';
+				this._failedMigrationButton.container.display = '';
 				this._failedMigrationButton.count.value = failedMigrations.length.toString();
```
Comment (brian-harris) [inline extensions/sql-migration/src/dashboard/sqlServerDashboard.ts:290]: nit, it would use failedCount instead

File: src/sql/workbench/browser/modelComponents/divContainer.component.ts [hunk 6]
```diff
@@ -18,20 +18,25 @@ import { KeyCode } from 'vs/base/common/keyCodes';
...
+		<div #divContainer *ngIf="items" class="divContainer" [ngStyle]="CSSStyles" [style.height]="height" [style.width]="width" [style.display]="display" (keyup)="onKey($event)" [attr.role]="ariaRole" [attr.aria-selected]="ariaSelected" (mouseover)="onMouseOver()" (mouseout)="onMouseOut()">
 			<div *ngFor="let item of items" [style.order]="getItemOrder(item)" [ngStyle]="getItemStyles(item)">
 				<model-component-wrapper [descriptor]="item.descriptor" [modelStore]="modelStore">
 				</model-component-wrapper>
 			</div>
 		</div>
-	`
+	`,
+	styles: [
+		`.divContainer: focus { outline-offset: 2px }`
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/divContainer.component.ts:38]: Hm, I guess this works but it'd be nice to just use https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/browser/modelComponents/media/divContainer.css for general rules to align with how we styles for every other component in ADS.

**Review by brian-harris — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
This looks great, thanks for adding this!
