### PR TITLE
Postgres Parameters edit calls missing try catch block

### LINKED ISSUE #14803: Postgres Server Parameters Page does not show expectation
When running edit command from server parameters page, exit code was not caught. Pop up notification states instance has been updated which is inaccurate. 

uncaughtexception

### PR DESCRIPTION
**Pull request by nasc17**
Added Try catch block to edit functions in dashboard. Able to catch unexpected code error and show error message notification. 
resetbugfic

This PR fixes #14803

### CODE REVIEW

File: extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts [hunk 1]
```diff
@@ -36,33 +36,42 @@ export class PostgresWorkerNodeParametersPage extends PostgresParametersPage {
...
+		try {
+			await this._azdataApi.azdata.arc.postgres.server.edit(
+				this._postgresModel.info.name,
+				{ engineSettings: parameterName + '=' },
+				this._postgresModel.engineVersion,
+				this._postgresModel.controllerModel.azdataAdditionalEnvVars,
+				session);
+		} catch (error) {
+			throw error;
+		}
```
Comment (bergeron) [inline extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts:74]: Hmm does this need to catch the error just to rethrow it?  I wouldn't expect it to behave differently than just letting it throw.

File: extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts [hunk 2]
```diff
@@ -147,21 +147,20 @@ export abstract class PostgresParametersPage extends DashboardPage {
...
 									engineSettings.push(`${key}="${value}"`);
 								});
-								const session = await this._postgresModel.controllerModel.acquireAzdataSession();
-								try {
-									this.saveParameterEdits(engineSettings.toString(), session);
-								} finally {
-									session.dispose();
-								}
+								session = await this._postgresModel.controllerModel.acquireAzdataSession();
+								await this.saveParameterEdits(engineSettings.toString(), session);
```
Comment (bergeron) [inline extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:156]: Good find, I expect the cause of the uncaught exceptions is that these calls weren't awaited.

Comment (Charles-Gagnon) [reply extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:156]: Yeah, that'd be the issue. WIthout the awaits the thread continues on and so the catch does nothing

File: extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts [hunk 3]
```diff
@@ -147,21 +147,20 @@ export abstract class PostgresParametersPage extends DashboardPage {
...
 								this.parameterUpdates!.forEach((value, key) => {
 									engineSettings.push(`${key}="${value}"`);
 								});
-								const session = await this._postgresModel.controllerModel.acquireAzdataSession();
-								try {
-									this.saveParameterEdits(engineSettings.toString(), session);
-								} finally {
-									session.dispose();
-								}
+								session = await this._postgresModel.controllerModel.acquireAzdataSession();
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:155]: You shouldn't need to change the session like this - a try/finally without a catch will still throw

File: extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts [hunk 4]
```diff
@@ -221,9 +220,10 @@ export abstract class PostgresParametersPage extends DashboardPage {
 							cancellable: false
 						},
 						async (_progress, _token): Promise<void> => {
-							const session = await this._postgresModel.controllerModel.acquireAzdataSession();
+							let session: azdataExt.AzdataSession | undefined = undefined;
 							try {
-								this.resetAllParameters(session);
+								session = await this._postgresModel.controllerModel.acquireAzdataSession();
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:225]: Same here - you shouldn't need to move the session up. Just awaiting the resetAllParameters call should be enough.

File: extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts [hunk 5]
```diff
@@ -516,11 +515,14 @@ export abstract class PostgresParametersPage extends DashboardPage {
...
 						},
 						async (_progress, _token): Promise<void> => {
-							const session = await this._postgresModel.controllerModel.acquireAzdataSession();
+							let session: azdataExt.AzdataSession | undefined = undefined;
 							try {
-								this.resetParameter(engineSetting.parameterName!, session);
+								session = await this._postgresModel.controllerModel.acquireAzdataSession();
+								await this.resetParameter(engineSetting.parameterName!, session);
+							} catch (err) {
+								throw err;
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:523]: This is unnecessary - if you don't have a catch it'll still throw (but first do the finally)

File: extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts [hunk 6]
```diff
@@ -36,33 +36,42 @@ export class PostgresWorkerNodeParametersPage extends PostgresParametersPage {
...
-			session);
-
+		try {
+			await this._azdataApi.azdata.arc.postgres.server.edit(
+				this._postgresModel.info.name,
+				{ engineSettings: engineSettings },
+				this._postgresModel.engineVersion,
+				this._postgresModel.controllerModel.azdataAdditionalEnvVars,
+				session);
+		} catch (error) {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresWorkerNodeParametersPage.ts:46]: Remove the try/catch - it's not doing anything since if the awaited call throws it'll cause this function to throw as well

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts [hunk 7]
```diff
@@ -147,21 +147,19 @@ export abstract class PostgresParametersPage extends DashboardPage {
 							cancellable: false
 						},
 						async (_progress, _token): Promise<void> => {
+							const session = await this._postgresModel.controllerModel.acquireAzdataSession();
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresParameters.ts:150]: This should actually be in its own outer try/catch - we want the save button to be re-enabled here if an error occurs during login as well

(same for all the other similar calls below)

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

**Review by bergeron — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
