### PR TITLE
Better error messages from connection failures in MSAL

### LINKED ISSUE #21660: Improve error reporting from Azure Core extension
When an error occurs in Azure Core extension while acquiring access token, error message is not captured in UI when connecting to an Azure resource. The only alternative for end user is to capture and identity what went wrong from Azure logs, which is inconvenient.

We should consider passing error message instead of access token when error happens so it can be populated to the error dialog.

### PR DESCRIPTION
**Pull request by cssuh**
Building upon #22003, this PR introduces better error messages displayed to the user when failures happen due to a connection attempt.  The MSAL-specific error message is displayed to the user rather than a generic message.  This PR plus #22003 fixes #21660.

Also fix a small typo in an error message I noticed.

Old behavior:
Screenshot 2023-02-28 at 11 32 53 AM

New behavior:
Screenshot 2023-02-28 at 11 07 47 AM

### CODE REVIEW

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 1]
```diff
@@ -364,10 +364,19 @@ export abstract class AzureAuth implements vscode.Disposable {
...
 			} else if (e.name === 'ClientAuthError') {
-				Logger.error(e.message);
+				Logger.error('[ClientAuthError] Failed to silently acquire token');
+				return {
+					name: e.name,
+					errorCode: e.errorCode,
+					errorMessage: e.errorMessage || e.message
+				}
+			} else {
+				return {
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:374]: Did you purposely not want to log anything in this case?

Given that these are both returning the same thing consider combining them into one and then doing an if check inside if you need.

File: src/sql/azdata.proposed.d.ts [hunk 2]
```diff
@@ -444,6 +444,23 @@ declare module 'azdata' {
 		errorMessage?: string;
 	}
 
+	export interface MsalError {
```
Comment (Charles-Gagnon) [inline src/sql/azdata.proposed.d.ts:447]: Shouldn't you be adding this as a return type for Prompt and otheras well?

Although this seems like a much more generic error, consider naming it something like `ProviderError` so that any provider can use it to return more detailed error info.

Comment (cssuh) [reply src/sql/azdata.proposed.d.ts]: prompt needs to be a PromptFailedResult because that one has the canceled field present, where else did you mean for me to add this as a return type?

File: src/sql/azdata.proposed.d.ts [hunk 3]
```diff
@@ -444,6 +444,23 @@ declare module 'azdata' {
 		errorMessage?: string;
 	}
 
+	export interface ProviderError {
```
Comment (Charles-Gagnon) [inline src/sql/azdata.proposed.d.ts:447]: So now that prompt can return this as well you should be updating the return type to include this - although having two separate types of "errors" is definitely a bit weird...(this and PromptFailedResult).

Looking at PromptFailedResult, why aren't you just using that anyways? The only new thing you're adding here is `name` so is there a reason you're not just adding this to the PromptFailedResult?

File: src/sql/azdata.proposed.d.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/azdata.proposed.d.ts]: Let's continue in the other thread so it's inline with the diff

File: src/sql/azdata.proposed.d.ts (hunk 3 above)
Comment (cssuh) [reply src/sql/azdata.proposed.d.ts:447]: I wanted a more generic error, but think I can just change the name of PromptFailedResult

File: src/sql/azdata.d.ts [hunk 4]
```diff
@@ -2515,7 +2515,7 @@ declare module 'azdata' {
 	 * AccountProvider.refresh or AccountProvider.prompt are rejected with this error, the error
 	 * will not be reported to the user.
 	 */
-	export interface PromptFailedResult {
+	export interface ProviderError {
```
Comment (Charles-Gagnon) [inline src/sql/azdata.d.ts:2518]: We really shouldn't ever be updating stuff in azdata.d.ts unless it's really necessary - doing this will cause anyone that might be using this to have compilation failures when updating the typings.

I'd also say that the `canceled` property here makes this something more specific than just generic "ProviderError".

My suggestion here would be to undo the changes in this file, and then in azdata.proposed add this 

`export interface PromptFailedResult extends ProviderError { }` 

in addition to the addition of the new ProviderError interface you added. This way we can still use that error for generic provider errors (even if they know nothing about a "canceled" state) while keeping the existing typings intact.

File: src/sql/azdata.proposed.d.ts [hunk 5]
```diff
@@ -432,7 +432,12 @@ declare module 'azdata' {
 		azurePortalEndpoint?: string;
 	}
 
-	export interface PromptFailedResult {
+	export interface ProviderError {
+		/**
+		 * Error name used for non-user cancelled errors
```
Comment (Charles-Gagnon) [inline src/sql/azdata.proposed.d.ts:437]: Update these params - they should be generic for any provider.

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 6]
```diff
@@ -363,11 +363,17 @@ export abstract class AzureAuth implements vscode.Disposable {
 					displayName: ''
 				};
 				return this.handleInteractionRequiredMsal(tenant, resource);
-			} else if (e.name === 'ClientAuthError') {
-				Logger.error(e.message);
+			} else {
+				if (e.name === 'ClientAuthError') {
+					Logger.error('[ClientAuthError] Failed to silently acquire token');
```
Comment (cheenamalhotra) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:368]: Is it useful to log this? You're already logging exception in catch above.

File: src/sql/azdata.d.ts (hunk 4 above)
Comment (cssuh) [reply src/sql/azdata.d.ts:2518]: Do you mean to say `export interface ProviderError extends PromptFailedResult`? since I would be changing the one in azdata.d.ts back to PromptFailedResult

Comment (cssuh) [reply src/sql/azdata.d.ts]: oh I see I misunderstood, that makes sense.

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 7]
```diff
@@ -322,7 +322,7 @@ export abstract class AzureAuth implements vscode.Disposable {
 	 * @param azureResource
 	 * @returns The authentication result, including the access token
 	 */
-	public async getTokenMsal(accountId: string, azureResource: azdata.AzureResource, tenantId: string): Promise<AuthenticationResult | null> {
+	public async getTokenMsal(accountId: string, azureResource: azdata.AzureResource, tenantId: string): Promise<AuthenticationResult | azdata.ProviderError | null> {
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:325]: This should still be returning PromptFailedResult since it has the canceled property.

File: src/sql/azdata.d.ts [hunk 8]
```diff
@@ -2579,15 +2579,15 @@ declare module 'azdata' {
 		 * Prompts the user to enter account information.
 		 * Returns an error if the user canceled the operation.
 		 */
-		prompt(): Thenable<Account | PromptFailedResult>;
+		prompt(): Thenable<Account | ProviderError>;
```
Comment (Charles-Gagnon) [inline src/sql/azdata.d.ts:2582]: Shouldn't all these stay as PromptFailedResult? That will include the new ProviderError properties you added - and these will all have the canceled property on them so ProviderError isn't correct.

File: src/sql/azdata.proposed.d.ts [hunk 9]
```diff
@@ -432,18 +432,31 @@ declare module 'azdata' {
 		azurePortalEndpoint?: string;
 	}
 
-	export interface PromptFailedResult {
+	export interface PromptFailedResult extends ProviderError {
 		/**
-		 * Error code used for non-user cancelled sign in errors
+		 * Type guard for differentiating user cancelled sign in errors from other errors
+		 */
+		canceled: boolean;
```
Comment (Charles-Gagnon) [inline src/sql/azdata.proposed.d.ts:439]: Remove this, it's already defined in azdata.d.ts. This here is just adding in the additional ProviderError properties.

File: src/sql/workbench/services/accountManagement/test/browser/accountManagementService.test.ts [hunk 10]
```diff
@@ -573,13 +573,13 @@ function getFailingMockAccountProvider(cancel: boolean): TypeMoq.Mock<azdata.Acc
 	mockProvider.setup(x => x.prompt())
 		.returns(() => {
 			return cancel
-				? Promise.resolve(<azdata.PromptFailedResult>{ canceled: true }).then()
+				? Promise.resolve(<azdata.ProviderError>{ canceled: true }).then()
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/test/browser/accountManagementService.test.ts:576]: Given that you're adding in the canceled property then these should still be PromptFailedResult, right?

But also you shouldn't need the casting I would think - the type it's expecting should be a ProviderError already so it should be ok with it based on the properties of the object being returned.

**Review by Charles-Gagnon — APPROVED** [review]
