### PR TITLE
fix holding down key scrolling issue

### LINKED ISSUE #18270: Notebooks: Holding Down Arrow Keys Scrolls Notebook Instead of Selecting Cells
[Latest insiders, notebook keyboard navigation bug bash]

- Create a notebook with enough cells such that there is a vertical scrollbar.
- Select a cell, then press escape (so that a user should be able to navigate between cells via the keyboard).
- Now, hold down the up/down arrow.

Expected: different cells get selected sequentially
Actual: notebook itself is scrolled

### PR DESCRIPTION
**Pull request by barbaravaldez**
This PR is for #18270

https://user-images.githubusercontent.com/34872381/154353446-613d4a7f-2406-4ede-9578-b7eb4de2bd3a.mov

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 1]
```diff
@@ -136,6 +136,9 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 		this._register(DOM.addDisposableListener(window, DOM.EventType.KEY_DOWN, (e: KeyboardEvent) => {
 			let event = new StandardKeyboardEvent(e);
 			if (this.isActive() && this.model.activeCell) {
+				if (e.repeat) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:139]: So now if you hold it down it'll scroll but not move through the cells? Because there were two ways that this could have been fixed : 

1. Holding down scrolls but doesn't move selection (what you have)
2. Holding down changes selected cell but doesn't move (except to bring new cell into view)

And it's not clear to me which one is better - but I was leaning towards the second since that seems useful so you don't have to click a whole bunch if you have a ton of cells.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:139]: @chlafreniere @dzsquared Any thoughts here?

Comment (lucyzhang929) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:139]: When I tested holding down changes the selected cell by one and doesn't scroll.

Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:139]: Just want to make sure that I'm parsing the difference here, but my expectation would be that holding the arrow keys does the same thing as tapping the arrow key many times.

i.e. if tapping the down arrow selects the next cell, I would expect that holding the down arrow for some period of time will select the next cell n times.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:139]: Yeah ok I'm not sure this is the correct fix then. I'm not seeing where the event propagation is being stopped, that'd be where I'd start for this

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 2]
```diff
@@ -136,6 +136,9 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 		this._register(DOM.addDisposableListener(window, DOM.EventType.KEY_DOWN, (e: KeyboardEvent) => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:136]: You should have the listener on the notebook component itself - this shouldn't need to be hooked up at the window level (and then you should be able to get rid of the isActive check too)

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:136]: Looked into this myself, we unfortunately need this for the time being.

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 3]
```diff
@@ -141,9 +141,12 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 		// events we care about are fired when the document focus is on something else - typically the root window.
 		this._register(DOM.addDisposableListener(window, DOM.EventType.KEY_DOWN, (e: KeyboardEvent) => {
 			// Make sure that the current active element is an ancestor - this is to prevent us from handling events when the focus is
-			// on some other dialog or part of the app. 
+			// on some other dialog or part of the app.
 			if (DOM.isAncestor(this.container.nativeElement, document.activeElement) && this.isActive() && this.model.activeCell) {
 				const event = new StandardKeyboardEvent(e);
+				if (e.repeat) {
+					e.stopImmediatePropagation();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:148]: Is there a reason you're not stopping propagation for any of the events we handle? Because this is now going to block any keyboard events from being propagated up if they're held down which probably isn't what we want. 

I think it would just be simplest to keep track of whether we handled the event (boolean that's set in each of the if checks) and if so then stop propagation.

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 4]
```diff
@@ -292,7 +295,7 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 	private scrollToActiveCell(): void {
 		// Get active cell from active notebook editor
 		const activeCellElement = document.querySelector(`.editor-group-container.active .notebook-cell.active`);
-		activeCellElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
+		activeCellElement.scrollIntoView({ behavior: 'auto', block: 'nearest' });
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:298]: What's this change for?

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:298]: The smooth effect takes longer get to the cell. That's why it looks like we are leaving behind the cell when we hold down the key.  Since we are selecting the next cell, we can scroll in one 'jump'. 

I'm going to remove the parameters though because that's the default behavior of scrollIntoView.

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 5]
```diff
@@ -290,11 +301,18 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 		}
 	}
 
+	@debounce(50)
 	private scrollToActiveCell(): void {
 		// Get active cell from active notebook editor
-		const activeCellElement = document.querySelector(`.editor-group-container.active .notebook-cell.active`);
-		activeCellElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
+		const activeCellElement = this.container.nativeElement.querySelector(`.editor-group-container.active .notebook-cell.active`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:305]: While you're here - this shouldn't be necessary to run again. Just pass in the active cell since we already got it in the event handler above.

**Review by Charles-Gagnon — APPROVED** [review]
Not sure we need the extra logic in scrollToActiveCell, revert that unless you find a reason we need it.

Check out the other comment I left below too

But otherwise this should fix the issue now so pre-emptively approving

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts (hunk 5 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:304]: We need to get the active cell again because the active cell that we got in the event handler is the past cell (before selecting the next cell)

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 6]
```diff
@@ -145,39 +146,47 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 			// For Escape - the focused element is the div.notebook-preview or textarea.inputarea of the cell, so we need to make sure that it is a descendant of the current active cell
 			//  on the current active editor.
 			const activeCellElement = this.container.nativeElement.querySelector(`.editor-group-container.active .notebook-cell.active`);
+			let handled = false;
```
Comment (VasuBhog) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:149]: might be good to leave a comment on what this represents or rename it to something like `handledKeyEvent`

**Review by Charles-Gagnon — APPROVED** [review]
One comment to look at, but tested this out and it seems to work as expected now!

**Review by VasuBhog — APPROVED** [review]
Tested this on code cells, text cells, and alternating code/text cells. Looks good!

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 7]
```diff
@@ -291,10 +305,16 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 	}
 
 	private scrollToActiveCell(): void {
-		// Get active cell from active notebook editor
-		const activeCellElement = document.querySelector(`.editor-group-container.active .notebook-cell.active`);
-		activeCellElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
+		const activeCellElement = this.container.nativeElement.querySelector(`.editor-group-container.active .notebook-cell.active`);
+		let containerTop = this.container.nativeElement.scrollTop;
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:309]: let me check

[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:309]: yup, it works as expected. I'll remove the checks.
