### PR TITLE
Don't allow tabbing into table

### LINKED ISSUE #6729: A11y_AzureDataStudio(Schema,Dacpac,Backup)_DeployDacpac_DeployDacpacSummaryScreen_ScreenReader: Tab key navigation is available in the table cells while Jaws is on and is an illogical order.
[“Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS; #A11yTCS; #A11y_ADS_Schema_Dacpac_Backup; #Azure Data Studio; #DesktopApp; #Win10; #MAS1.3.2; #Jaws; #NVDA;

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.10.0-insider (user setup)
Commit: e8ccc65
Electron: 4.2.7
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
Jaws Version: 2019.1907.31 ILM
Nvda version: 2019.1.1

**Additional Details:**
Tools Name: Jaws, NVDA
MAS References: MAS1.3.2

**Repro Steps:**
1.Launch Azure Data Studio application.
2.Connect to server with windows credentials.
3.Navigate to Extensions from left menu.
4.Search & install Dacpac extension.
5.Navigate to Connections from left menu.
6.Expand the server connected in step 2.
7.Right click an on prem database and select Data-tier application wizard from Context menu.
8.Select first radio button.
9.Navigate till next button & hit enter.
10.Provide all the details for Deploy Dacpac & hit next.
11.Navigate till Next button & hit enter.
12.Start screen reader as Jaws.
13.Navigate to the header row using arrow key.

**Actual:**
On navigating to the header row using arrow key, the next tab key navigation is available in the cells of the table.

**Same issue is observed in nvda configuration.**
**Same issue is observed in voiceover configuration.**

**Same issue is observed in the following pages:**
1.Extract Dacpac Summary Screen
Follow the exact same steps mentioned above but select the second radio button.
2.Import Bacpac Summary Screen
Follow the exact same steps mentioned above but select the third radio button.
3.Export Bacpac Summary Screen
Follow the exact same steps mentioned above but select the 4th radio button and click on next button. Again click on the next button

**Expected:**
The tab key navigation should not be present for the cells of the table since they are not actionable. The navigation to the cells should be done by arrow keys only. The tab key navigation should be from step3 on the left side to the next tab on the previous button.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: (https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx)

**User Impact:**
The screen reader user will take the wrong understating of the cells if navigation is done using tab key , they will perceive it as an actionable control.

**MAS Reference:**
MAS 1.3.2- 
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={1ee227a7-e3c5-47b8-ab18-48ca8595077b}](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={1ee227a7-e3c5-47b8-ab18-48ca8595077b})

**Attachment for Reference:**
[#6729A11y_AzureDataStudio(Schema,Dacpac,Backup)_DeployDacpac_DeployDacpacSummaryScreen_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3496916/6729A11y_AzureDataStudio.Schema.Dacpac.Backup._DeployDacpac_DeployDacpacSummaryScreen_ScreenReader.pptx)

### PR DESCRIPTION
**Pull request by kisantia**
Fixes #6729. For accessibility, tabbing to a table shouldn't be allowed if the table cells aren't actionable. Previously, if arrow keys were used to navigate into the table, pressing tab for the first time would go to the next cell, then the following tab would exit the table. This fixes that so the first tab will leave the table.

tableNoTab

### CODE REVIEW

File: src/sql/workbench/browser/modelComponents/table.component.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ import { slickGridDataItemColumnValueWithNoData, textFormatter } from 'sql/base/
 @Component({
 	selector: 'modelview-table',
 	template: `
-		<div #table style="height:100%;" [style.font-size]="fontSize" [style.width]="width"></div>
+		<div #table style="height:100%;" [style.font-size]="fontSize" [style.width]="width" tabindex="-1"></div>
```
Comment (udeeshagautam) [inline src/sql/workbench/browser/modelComponents/table.component.ts]: wouldn't this change this for any table? for example schema compare result table - we don't want tab there too? :(

Comment (kisantia) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: This isn't affecting the schema compare result table because of the checkbox focus thing in #6821, so tabbing into the table still works there.

Comment (kisantia) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: I think all other tables would need this too because the cells aren't actionable. The DeclarativeTable has actionable cells, but that isn't impacted by this since it's a different component.

Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: schema compare is using this together with checkbox plugin, right? I am not sure i understand your previous comments, could you please explain how will this not affect schema compare?

Comment (kisantia) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: When tabbing into the schema compare table, the focus goes to the first checkbox in the first row of the table. The behavior of tabbing into the schema compare table doesn't change with this change.
schemaCompareTab

Comment (udeeshagautam) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: We can merge this and as per recent conversation looks like as per Acessibility team tabbing should not work inside any table, only row keys.

Comment (kburtram) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: @kisantia does this change any behavior in other places we use this component, like Dashboard, Query Editor or Profiler?  The user's will still be able to use the keyboard to focus into these tables and navigate around?

**Comment by kburtram** [comment]
@anthonydresser do you see any issues with this change impacting tables in the various places we use this?

**Comment by anthonydresser** [comment]
This change is limited to the model view components, so it won't affect any other tables in the product.

File: src/sql/workbench/browser/modelComponents/table.component.ts (hunk 1 above)
Comment (kisantia) [reply src/sql/workbench/browser/modelComponents/table.component.ts]: Yes users can still use the keyboard to navigate to and around tables
