### PR TITLE
Don't allow adding duplicate database references to sql project

### LINKED ISSUE #10977: Same database reference can be added more than once
Steps to Reproduce:
Note: also occurs for normal database references, not just system database references
1. Add system database reference to master
2. Try to add another system database reference to master

Expected:
Shouldn't be allowed to add same reference twice

Actual: 
There are now two references to master
Screen Shot 2020-06-17 at 2 01 24 PM

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #10977. Now a db reference can't be added if there's already a reference to that dacpac in the project.
dbRefExists

### CODE REVIEW

File: extensions/sql-database-projects/src/models/project.ts [hunk 1]
```diff
@@ -323,6 +328,23 @@ export class Project {
 		}
 	}
 
+	private databaseReferenceExists(entry: DatabaseReferenceProjectEntry): boolean {
+		const isSystemDatabaseProjectEntry = (<SystemDatabaseReferenceProjectEntry>entry).ssdtUri;
+		const entryFsPath = isSystemDatabaseProjectEntry ? entry.fsUri.fsPath.substring(1) : entry.fsUri.fsPath;
+
+		for (let r = 0; r < this.projFileXmlDoc.documentElement.getElementsByTagName(constants.ArtifactReference).length; r++) {
```
Comment (Benjin) [inline extensions/sql-database-projects/src/models/project.ts:335]: Why not check against `this.databaseReferences.find(something)` instead of the xml?

Comment (kisantia) [reply extensions/sql-database-projects/src/models/project.ts:335]: SSDT allows adding a reference with the same dacpac name but different filepath. this.databaseReferences only has the name of the dacpacs right now.

Comment (Charles-Gagnon) [reply extensions/sql-database-projects/src/models/project.ts:335]: You should at least turn this into a `.this.projFileXmlDoc.documentElement.getElementsByTagName(constants.ArtifactReference).find(ele => ...)`

Right now you're calling `getElementsByTagName` once at the beginning and then 2 times for every element found - using find will reduce that to one call at the beginning.

File: extensions/sql-database-projects/src/test/project.test.ts [hunk 2]
```diff
@@ -177,6 +177,29 @@ describe('Project: sqlproj content operations', function (): void {
...
+		await project.readProjFile();
+
+		should(project.databaseReferences.length).equal(0);
+		await project.addSystemDatabaseReference(SystemDatabase.master);
+		should(project.databaseReferences.length).equal(1);
+		should(project.databaseReferences[0]).equal(constants.master);
+
+		// try to add reference to master again
+		await testUtils.shouldThrowSpecificError(async () => await project.addSystemDatabaseReference(SystemDatabase.master), constants.databaseReferenceAlreadyExists);
+		should(project.databaseReferences.length).equal(1);
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/test/project.test.ts:193]: With this many should checks make sure you add a message for each one so if it fails you know which one did. Right now it would just fail with a generic `expected : 1 actual : #` which isn't terribly useful.

File: extensions/sql-database-projects/src/models/project.ts (hunk 1 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/models/project.ts]: there isn't find() on NodeList, but I changed it to just call getElementsByTagName once at the beginning

Comment (Benjin) [reply extensions/sql-database-projects/src/models/project.ts]: Is there a reason it makes more sense to check the XML over adding the filepath info to `this.databaseReferences`?  I feel like we should keep talking to the XML should be kept to the serialization/deserialization methods as much as possible since that logic is more fragile and probably going to move out of this class.

Comment (kisantia) [reply extensions/sql-database-projects/src/models/project.ts]: Sure makes sense. I changed this.databaseReferences to be DatabaseReferenceProjectEntry[] instead of string[] and removed the XML checking from addDatabaseReferenceExists()

File: extensions/sql-database-projects/src/models/project.ts [hunk 3]
```diff
@@ -498,6 +489,10 @@ class DatabaseReferenceProjectEntry extends ProjectEntry {
 	constructor(uri: Uri, public databaseLocation: DatabaseReferenceLocation, public name?: string) {
 		super(uri, '', EntryType.DatabaseReference);
 	}
+
+	public databaseName(): string {
```
Comment (Benjin) [inline extensions/sql-database-projects/src/models/project.ts:493]: public get() databaseName to be ever so slightly cleaner, maybe

File: extensions/sql-database-projects/src/models/project.ts [hunk 4]
```diff
@@ -73,14 +73,17 @@ export class Project {
...
+			if (references[r].getAttribute(constants.Condition) !== constants.NotNetCoreCondition) {
+				const filepath = references[r].getAttribute(constants.Include);
 				if (!filepath) {
 					throw new Error(constants.invalidDatabaseReference);
 				}
 
-				this.databaseReferences.push(path.parse(filepath).name);
+				let nameNodes = references[r].getElementsByTagName(constants.DatabaseVariableLiteralValue);
+				let name = nameNodes.length === 1 ? nameNodes[0].childNodes[0].nodeValue : undefined;
+				this.databaseReferences.push(new DatabaseReferenceProjectEntry(Uri.parse(filepath), name ? DatabaseReferenceLocation.differentDatabaseSameServer : DatabaseReferenceLocation.sameDatabase, name));
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/models/project.ts:86]: FYI, there might be some conflict wth the PR for adding safe plaform path here...

File: extensions/sql-database-projects/src/models/project.ts [hunk 5]
```diff
@@ -73,14 +73,17 @@ export class Project {
...
+		const references = this.projFileXmlDoc.documentElement.getElementsByTagName(constants.ArtifactReference);
+		for (let r = 0; r < references.length; r++) {
+			if (references[r].getAttribute(constants.Condition) !== constants.NotNetCoreCondition) {
+				const filepath = references[r].getAttribute(constants.Include);
 				if (!filepath) {
 					throw new Error(constants.invalidDatabaseReference);
 				}
 
-				this.databaseReferences.push(path.parse(filepath).name);
+				let nameNodes = references[r].getElementsByTagName(constants.DatabaseVariableLiteralValue);
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/models/project.ts:84]: also just tried changing this in SSDT - looks like it could be any alias. In SSDT it doesnt seem to impact the tree

Comment (kisantia) [reply extensions/sql-database-projects/src/models/project.ts:84]: Yup the tree displays the dacpac file name and checking if the reference already exists is done by comparing the file paths. This is just keeping track of the DatabaseVariableLiteralValue in case it's needed to write back to the sqlproj later.

File: extensions/sql-database-projects/src/models/project.ts (hunk 4 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/models/project.ts:86]: Sure I'll wait for your other PR to get merged so I can get the update for safe platform path change :)

Comment (udeeshagautam) [reply extensions/sql-database-projects/src/models/project.ts:86]: done. plz let me know if you face any issues.
