### PR TITLE
Fix Notebook Kusto Kernel Consistency 

### LINKED ISSUE #12255: Notebook Kernel is not consistent for Kusto
- Azure Data Studio Version: 1.22.0-insider

Steps to Reproduce:

1. Have Kusto Connection in object explorer
2. Select new notebook on Kusto Cluster
3. Notice the Kernel is set to Kusto
4. Select new notebook on the same Kusto Cluster (or different Kusto Cluster)
5. Notice the kernel is set to SQL
6. Repeat steps 4 and 5 and notice the same result

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes an issue when opening a new notebook multiple times from the same Kusto connection.

### CODE REVIEW

**Review by JustinMDotNet — APPROVED** [review]
Looks good

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -653,9 +653,12 @@ export class NotebookModel extends Disposable implements INotebookModel {
 			let standardKernels = find(this._standardKernels, kernel => this._defaultKernel && kernel.displayName === this._defaultKernel.display_name);
 			let connectionProviderIds = standardKernels ? standardKernels.connectionProviderIds : undefined;
 			let providerFeatures = this._capabilitiesService.getCapabilities(profile.providerName);
-			if (connectionProviderIds.length > 0 && this._currentKernelAlias) {
+			if (connectionProviderIds.length > 0) {
```
Comment (chlafreniere) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:656]: `connectionProviderIds?.length`

It's possible for it to be undefined 2 lines above

**Review by chlafreniere — APPROVED** [review]
