### PR TITLE
Fix Issue when OE connection Disconnects on Notebook Close

### LINKED ISSUE #4383: Closing notebook shouldn't close OE connection
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect server from OE
2. Open notebook and select that connection
3. Close nb, the OE node is disconnected.

Expected:

OE node should be in connected state. NB should only close the connections created from Add new connection.

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #4383.

I spent a decent amount of time thinking about this problem, and came up with the following solution due to the following reasons:

- We only currently connect using the ConnectionManagementService in SQL (for the purposes of IntelliSense) for all of the notebooks code, and for the Add new connection scenario in the Attach To
- Any new connections from notebooks (besides Attach To [is there a way to include a purpose to simplify this code even more?]) should include the 'notebook' tag when generating the connection URI (we already do this today)
- I don't want to create new connections when they aren't strictly necessary, and would much prefer pruning them instead of creating new ones

Therefore, when we're closing the notebook, we should only be disconnecting from connections that were created in the notebook, and those that were created in Attach To (since those won't be reused).

### CODE REVIEW

File: src/sql/parts/notebook/models/notebookModel.ts [hunk 1]
```diff
@@ -840,6 +848,24 @@ export class NotebookModel extends Disposable implements INotebookModel {
 		return [];
 	}
 
+	// Check for and disconnect from any new connections opened while in the notebook
+	// Note: notebooks should always connect with the connection URI in the following format,
+	// so that connections can be tracked accordingly throughout ADS:
+	// let connectionUri = Utils.generateUri(connection, 'notebook');
+	private async disconnectNotebookConnection(conn: ConnectionProfile): Promise<void> {
+		if (this.notebookOptions.connectionService.getConnectionUri(conn).includes(uriPrefixes.notebook)) {
```
Comment (kevcunnane) [inline src/sql/parts/notebook/models/notebookModel.ts]: What if getConnectionUri returns undefined? is that possible?

**Comment by chlafreniere** [comment]
Totally agree on the tests; this is a great case to ensure that these various methods get called with the correct connections when thee notebook is closed.

File: src/sql/parts/notebook/models/notebookModel.ts (hunk 1 above)
Comment (chlafreniere) [reply src/sql/parts/notebook/models/notebookModel.ts]: Not possible from what I could see:

return this._connectionStatusManager.getOriginalOwnerUri(Utils.generateUri(connectionProfile));
