### PR TITLE
Fix About Dialog post merge for Azure Data Studio

### LINKED ISSUE #24709: Post Merge > Electron Build ID is undefined in ADS About info
Copied from ADS Ad-Hoc build:

Version: 1.47.0-insider (user setup)
Commit: 79981365c9cb66a525eca0f04a5bc1c6c9c87419
Date: 2023-10-17T19:18:50.073Z
Electron: 25.8.1
ElectronBuildId: **undefined**
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Expected as-in VS Code about info:

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
**_ElectronBuildId: 24154031_**
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR closes #24709

This PR removes the electron build ID since it's appearing as undefined.

image

VS Code doesn't use public Electron builds and use their own private builds, so the build ID could be coming in through a mixin that ADS doesn't have access to, which is why it's appearing as undefined.

### CODE REVIEW

File: src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts [hunk 1]
```diff
@@ -77,19 +77,35 @@ export class NativeDialogHandler extends AbstractDialogHandler {
...
-				process.versions['microsoft-build'],
+				process.versions['microsoft-build'], // {{SQL CARBON EDIT}} Removing Electron Build ID from detail string
 				process.versions['chrome'],
 				process.versions['node'],
 				process.versions['v8'],
 				`${osProps.type} ${osProps.arch} ${osProps.release}${isLinuxSnap ? ' snap' : ''}`,
 				this.productService.vscodeVersion  // {{SQL CARBON EDIT}} - add vscode version
 			);
+			*/
+			return localize({ key: 'aboutDetail', comment: ['Electron, Chromium, Node.js and V8 are product names that need no translation'] },
```
Comment (Charles-Gagnon) [inline src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts:96]: Any changed strings in the vs layer need to go in https://github.com/microsoft/azuredatastudio/blob/main/src/sql/base/common/locConstants.ts, otherwise they get overwritten by the localized strings coming from VS

File: src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts [hunk 2]
```diff
@@ -77,19 +78,34 @@ export class NativeDialogHandler extends AbstractDialogHandler {
...
+			// {{SQL CARBON EDIT}} - BEGIN - Removing Electron Build ID from detail string
+			/*
 			return localize({ key: 'aboutDetail', comment: ['Electron, Chromium, Node.js and V8 are product names that need no translation'] },
 				"Version: {0}\nCommit: {1}\nDate: {2}\nElectron: {3}\nElectronBuildId: {4}\nChromium: {5}\nNode.js: {6}\nV8: {7}\nOS: {8}",
 				version,
 				this.productService.commit || 'Unknown',
 				this.productService.date ? `${this.productService.date}${useAgo ? ' (' + fromNow(new Date(this.productService.date), true) + ')' : ''}` : 'Unknown',
 				process.versions['electron'],
-				process.versions['microsoft-build'],
+				process.versions['microsoft-build'], // {{SQL CARBON EDIT}} Removing Electron Build ID from detail string
```
Comment (Charles-Gagnon) [inline src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts:89]: nit: can remove this one - you already say that above

**Review by Charles-Gagnon — APPROVED** [review]

**Review by cheenamalhotra — APPROVED** [review]
