### PR TITLE
Fix WYSIWYG text + image paste

### LINKED ISSUE #13454: WYSIWYG doesnt convert image link when pasting text and image together
- Azure Data Studio Version: 1.24.0
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:35:27.682Z (6 days ago)
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Copy and paste text and pictures from [quickstart-sql-server](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/quickstart-sql-server.md) to Rich Text View.
2. After exiting the cell we then see the image disappear. We can open the cell back up and see that the HTML of the image does not convert properly.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #13454.

It fixes when a user copied both Text and images, and we now convert the image link properly (similar to how we did it in the October release of ADS).

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts [hunk 1]
```diff
@@ -137,14 +138,22 @@ export class HTMLMarkdownConverter {
 		this.turndownService.addRule('p', {
 			filter: 'p',
 			replacement: function (content, node) {
+				let isAnchorElement: boolean = false;
 				node.childNodes.forEach(c => {
 					if (c.nodeType === Node.TEXT_NODE) {
 						c.nodeValue = escapeAngleBrackets(c.textContent);
 					} else if (c.nodeType === Node.ELEMENT_NODE) {
 						c.innerText = escapeAngleBrackets(c.textContent);
+						if (c.nodeName === 'A') {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:147]: This is always going to be capitalized?

**Review by Charles-Gagnon — APPROVED** [review]
Some tests would be nice

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts (hunk 1 above)
Comment (VasuBhog) [reply src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:147]: Yes, as far as the turndown GitHub documentation I looked at all node names that are capitalized.

**Review by lucyzhang929 — APPROVED** [review]

**Review by barbaravaldez — APPROVED** [review]
