### PR TITLE
fix prompt for auth/device auth method

### LINKED ISSUE #21269: Enabling both Azure Auth modes (Code Grant and Device Code) don't prompt for selection
- Azure Data Studio Version: 1.40.0
- OS Version: Windows 11

**Steps to Reproduce:**

1. Enable both settings: "Azure: Auth: Code Grant" and "Azure: Auth: Device Code"
2. Reload Window and attempt to Sign in to Azure

**Expected:**
Should prompt for selection of Auth mode.

**Actual:**
Uses Code Auth by default and requires Code Auth to be disabled in order to make Device Code auth work.

**Regression:**
Yes

### PR DESCRIPTION
**Pull request by cssuh**
The prompt to select auth / device code does not appear anymore, this PR fixes that.

Old behavior (doesn't prompt for auth/device code when both options are selected in settings):
Screen_Recording_2022-11-18_at_12_33_22_PM_AdobeExpress

New behavior (prompts for auth/device code now):
Screen_Recording_2022-11-18_at_12_25_14_PM_AdobeExpress
This PR fixes #21269

### CODE REVIEW

File: extensions/azurecore/src/account-provider/azureAccountProvider.ts [hunk 1]
```diff
@@ -63,7 +63,8 @@ export class AzureAccountProvider implements azdata.AccountProvider, vscode.Disp
 
 		if (codeGrantMethod === true && !this.forceDeviceCode) {
 			this.authMappings.set(AzureAuthType.AuthCodeGrant, new AzureAuthCodeGrant(metadata, tokenCache, context, uriEventHandler));
-		} else if (deviceCodeMethod === true || this.forceDeviceCode) {
+		}
+		if (deviceCodeMethod === true || this.forceDeviceCode) {
 			this.authMappings.set(AzureAuthType.DeviceCode, new AzureDeviceCode(metadata, tokenCache, context, uriEventHandler));
 		} else {
 			console.error('No authentication methods selected');
```
Comment (cheenamalhotra) [inline extensions/azurecore/src/account-provider/azureAccountProvider.ts:70]: Could you also fix this to log when there are no auth mappings. This else condition doesn't seem right.

**Review by cheenamalhotra — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
