### PR TITLE
fix project listed twice when using multi root workspaces

### LINKED ISSUE #22517: Projects listed twice in Database Projects when using Multi Root Workspaces
- SqlPackage or DacFx Version: 1.18.0
- .NET Framework (Windows-only) or .NET Core: 6
- Environment (local platform and source/target platforms): Win 11 x64

**Steps to Reproduce:**

1. Create a vs code-workspace file to make your project multi root workspaces in VSCode.
2. Setup a packages folder for a mono repo with each package being it's own vs code workspace
3. Create a "database" package which is also a root workspace
4. Create a database project in the database package with mssql vs code extension
5. Open the code-workspace
6. Go to database projects in action pane
7. You will see the database is listed twice in database projects, if you add an item to 1 it shows up in the other, it's rendering the same project in the tree twice.

My hunch is because their is a root workspace pointing at ./ and also a workspace pointing at ./packages/Database, the extension sees it twice (in two workspaces) so renders it twice and is also why it's the same one each time.   

I suggest adding a way for us to tell the extension to ignore specific workspaces.

**Did this occur in prior versions?  If not - which version(s) did it work in?**

(DacFx/SqlPackage/SSMS/Azure Data Studio)

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #22517.

Example of a workspace where two of the workspace folders include the same project:
image

before:
image

fixed:
image

### CODE REVIEW

File: extensions/data-workspace/src/services/workspaceService.ts [hunk 1]
```diff
@@ -168,7 +168,13 @@ export class WorkspaceService implements IWorkspaceService {
 
 		try {
 			const projectPromises = vscode.workspace.workspaceFolders?.map(f => this.getAllProjectsInFolder(f.uri)) ?? [];
-			this.openedProjects = (await Promise.all(projectPromises)).reduce((prev, curr) => prev.concat(curr), []);
+			const allProjects = (await Promise.all(projectPromises)).reduce((prev, curr) => prev.concat(curr), []);
+
+			// convert to set to make sure all the fsPaths are unique so projects aren't listed multiple times if they are included by multiple workspace folders.
```
Comment (SakshiS-harma) [inline extensions/data-workspace/src/services/workspaceService.ts:173]: Nit: "S" instead of "s" in set, for better understanding :).

**Review by SakshiS-harma — APPROVED** [review]

**Review by Benjin — APPROVED** [review]
