### PR TITLE
Correctly route notebook serialization requests to SQL Tools Service.

### LINKED ISSUE #20432: Notebook: Save As CSV delimeter settings not working
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. In the settings queryEditor.results.saveAsCsv.delimiter put any character (for instance |)  
2.  Execute a query in the Notebook
3. Click the icon to export as CSV
4. Open the exported file. The separator you choosed is not applied. Same version before this was working fine

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by corivera**
When trying to convert query results into different file types, we were always picking the first registered serialization provider, which meant the request would get routed to the Kusto service rather than the SQL Tools one. This change routes that request to the right service, while also adding a new providerID field in case we want to use this serialization service for other file types in the future.

This PR fixes #20432

### CODE REVIEW

**Review by chlafreniere — APPROVED** [review]

**Comment by corivera** [comment]
Looks like Kusto results still need to go through the Kusto service, so I'll add some provider handling for that.

**Comment by Charles-Gagnon** [comment]
Was just about to ask that. We should be using the provider from the Notebook (or editor) instead of hardcoding to MSSQL

File: src/sql/platform/serialization/common/serializationService.ts [hunk 1]
```diff
@@ -115,7 +116,13 @@ export class SerializationService implements ISerializationService {
 		}
 		try {
 			// Create a new session with the provider and send initial data
-			let provider = this.providers[0].provider;
+			let provider = this.providers.find(provider => provider.providerId === serializationRequest.serializationProviderId).provider;
```
Comment (Charles-Gagnon) [inline src/sql/platform/serialization/common/serializationService.ts:119]: `this.providers.find(...)?.provider`

File: src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts [hunk 2]
```diff
@@ -488,9 +488,19 @@ export class DataResourceDataProvider implements IGridDataProvider {
 		// interface than the query execution service's saveResults handlers. Here, we take the
 		// format-specific request params (eg, includeHeaders for CSV) and merge the format-agnostic
 		// request params for the serialization request (eg, saveFormat, filePath).
+		let providerId: string;
+		switch (this.cellModel.notebookModel.currentKernelAlias) {
+			case 'Kusto':
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:493]: This is pretty hacky and not friendly to new providers being added later. The NotebookModel already has a ton of stuff using providers - why not use those?

Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:493]: These serialization providers have different IDs than the ones we use for notebook providers. For example, a SQL notebook uses the "MSSQL" serialization provider. We only use this service for notebook query results, so beyond Kusto and SQL it isn't used. Query Editor has its own RPC calls for exporting query results.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:493]: Do we really not have a way for Notebook providers to be mapped to connection/serialization providers? That seems like something we'd need so we can properly route these serialization requests without having to update this hardcoded list every time a new provider was added...

Maybe this is something the Notebook provider can optionally provide - what serialization provider it should use (defaulting to MSSQL if none provided)

Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:493]: Also Kusto and LogAnalytics are aliases of the SQL kernel, so they'd have the same provider

Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:493]: Even if we have each provider specify a serializer, we still run into problems because Kusto and LogAnalytics are aliases for the SQL kernel and have the same provider

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:493]: Hrm, yeah definitely a pretty big mess. Well this at least improves the current experience so I guess it's fine to get in but if we end up having to come back here and special case more stuff we should definitely take some time to try and do this properly.

File: src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts [hunk 3]
```diff
@@ -487,8 +488,19 @@ export class DataResourceDataProvider implements IGridDataProvider {
...
+			case 'LogAnalytics':
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:494]: You should be using common constants for these - I see a number of places where the provide IDs are hardcoded in so I'd suggest at least combining those to all use the same values to more easily be able to track down the different known aliases and providers. (having separate constants for provider IDs and aliases seems like a good idea giving the casing difference).

File: src/sql/platform/serialization/common/serializationService.ts [hunk 4]
```diff
@@ -17,6 +17,7 @@ const saveAsNotSupported = localize('saveAsNotSupported', "Saving results into d
 const defaultBatchSize = 500;
 
 export interface SerializeDataParams {
+	serializationProviderId: string;
```
Comment (Charles-Gagnon) [inline src/sql/platform/serialization/common/serializationService.ts:20]: Add a comment explaining where this ID comes from and some examples.

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts (hunk 2 above)
Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:493]: Actually, it looks like these serializer IDs correspond to the connection providers, rather than the notebook ones. I'll use those instead.

File: src/sql/platform/serialization/common/serializationService.ts [hunk 5]
```diff
@@ -17,6 +17,7 @@ const saveAsNotSupported = localize('saveAsNotSupported', "Saving results into d
 const defaultBatchSize = 500;
 
 export interface SerializeDataParams {
+	serializationProviderId: string; // The serializer to use for this request. Typically this is the ID of the connection provider used to run the query.
```
Comment (Charles-Gagnon) [inline src/sql/platform/serialization/common/serializationService.ts:20]: This should be a JS doc comment

File: src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts [hunk 6]
```diff
@@ -487,8 +488,11 @@ export class DataResourceDataProvider implements IGridDataProvider {
 		// interface than the query execution service's saveResults handlers. Here, we take the
 		// format-specific request params (eg, includeHeaders for CSV) and merge the format-agnostic
 		// request params for the serialization request (eg, saveFormat, filePath).
+		let connProviders = this.cellModel.notebookModel.getApplicableConnectionProviderIds(this.cellModel.notebookModel.selectedKernelDisplayName);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:491]: What if there's more than one provider? Wouldn't we have the same issue as we do currently in that case? Maybe we should at least log a warning.

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts (hunk 6 above)
Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:491]: Doesn't look like we ever register more than one provider per kernel, so it might be something we can simplify

Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:491]: Let me look around and see if there's a "current" connection provider in the notebookModel somewhere.
