### PR TITLE
Fix screenreader not reading tabular structure in dacpac deploy page

### LINKED ISSUE #9260: A11y_SQLAzureDataStudio_DeployDacpac_ReviewDeployPlan_ScreenReader: The control type and name for the table is not announced..
[“Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11y_SQLAzureDataStudioBenchmark;#A11yMAS;#A11ySev2;#A11yTCS;#SQL Azure Data Studio;#Benchmark;#DesktopApp;#Win32;#MAS1.3.1;#JAWS;#NVDA;#MAS4.2.3;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.16.0-insider
OS: Windows_NT x64 10.0.18363

**Additional Details:**
Tool: Accessibility insights for desktop.
MAS References:MAS1.3.1, MAS4.2.3;

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Dacpac extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Data-tier application wizard from Context menu.
8. Select first radio button.
9. Navigate till next button & hit enter.
10. Provide all the details for Deploy Dacpac & hit next.
11. Launch screen reader NVDA.

**Actual:**
Issue1:
On navigating to the table using arrow keys there is no table name and control announced.

Issue2:
Screen reader does not read the data inside the table in a tabular structure there is no column row value and header cell associations.

**Expected:**
Issue1:
On navigating to the table using arrow keys  the table name and control should be announced.

Issue2:
The screen reader should read the data inside the table in a tabular structure with proper column row value and header cell associations.

**User Impact:**
Screen reader users will not receive the information in a tabular structure.

**Attachment link for Reference :**
[A11y_SQLAzureDataStudio_DeployDacpac_ReviewDeployPlan9260.zip](https://github.com/microsoft/azuredatastudio/files/4322638/A11y_SQLAzureDataStudio_DeployDacpac_ReviewDeployPlan9260.zip)

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #9260. The table wasn't being recognized as a table by screenreaders because the role was alert. This was previously added to solve #6826, but that only asked for the loading status to be announced and it still is after this change.

### CODE REVIEW

File: extensions/dacpac/src/wizard/pages/deployPlanPage.ts [hunk 1]
```diff
@@ -98,8 +98,7 @@ export class DeployPlanPage extends DacFxConfigPage {
 			data: this.getColumnData(result),
 			columns: this.getTableColumns(result.dataLossAlerts.size > 0),
 			width: 875,
-			height: 300,
-			ariaRole: 'alert'
```
Comment (udeeshagautam) [inline extensions/dacpac/src/wizard/pages/deployPlanPage.ts]: after we remove this - will the loading still be announced as fixed for previous bug?

Comment (kisantia) [reply extensions/dacpac/src/wizard/pages/deployPlanPage.ts]: yup. The loader still has ariaRole="alert" so it announces when loading is finished
