### PR TITLE
Fix for Notebook Cell Height Not Resizing

### LINKED ISSUE #7246: Notebooks: Cells Not Resizing Automatically
This is a regression. Need to understand where this came from.

image

Cell height isn't getting resized properly when content changes.

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #7246.

Caused by https://github.com/microsoft/azuredatastudio/commit/ea0f9e6ce95b45def2b694efcd8ffe909bc43d20#diff-0308fd66e25b4760ce1a2b0a35757513

`this._lineHeight = editorWidget.getConfiguration().lineHeight;`

was changed to

`this._lineHeight = editorWidget.getRawOptions().lineHeight;`

which returns a lineHeight of 0, as getRawOptions() doesn't include any defaults apparently.

Also added a default just in case.

### CODE REVIEW

File: src/sql/workbench/browser/modelComponents/queryTextEditor.ts [hunk 1]
```diff
@@ -150,7 +150,7 @@ export class QueryTextEditor extends BaseTextEditor {
 		let shouldAddHorizontalScrollbarHeight = false;
 		if (!this._editorWorkspaceConfig || configChanged) {
 			this._editorWorkspaceConfig = this.workspaceConfigurationService.getValue('editor');
-			this._lineHeight = editorWidget.getRawOptions().lineHeight;
+			this._lineHeight = editorWidget.getOption(EditorOption.lineHeight) || 18;
```
Comment (corivera) [inline src/sql/workbench/browser/modelComponents/queryTextEditor.ts]: Should 18 here be a constant somewhere?
