### PR TITLE
Fix issue with SQL Database Projects unable to connect due to default encryption

### LINKED ISSUE #20977: publish to container creates container but fails to publish - problem connecting with azdata.connection.connect
Issue Type: <b>Bug</b>

	[ Build ]
    > "/usr/local/share/dotnet/dotnet"  build "/Volumes/Storage/CodeRepos/sample-sandbox/delete-bugbash/DatabaseProjectreactions/DatabaseProjectreactions.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="/Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory"
    stdout: Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
    stdout: Copyright (C) Microsoft Corporation. All rights reserved.
    stdout: 
    stdout: 
    stdout:   Determining projects to restore...
    stdout: 
    stdout:   All projects are up-to-date for restore.
    stdout: 
    stdout:   Creating a model to represent the project...
    stdout: 
    stdout:   Loading project references...
    stdout: 
    stdout:   Loading project files...
    stdout: 
    stdout:   Building the project model and resolving object interdependencies...
    stdout: 
    stdout:   Validating the project model...
    stdout: 
    stdout:   Writing model to /Volumes/Storage/CodeRepos/sample-sandbox/delete-bugbash/DatabaseProjectreactions/obj/Debug/Model.xml...
    stdout: 
    stdout:   DatabaseProjectreactions -> /Volumes/Storage/CodeRepos/sample-sandbox/delete-bugbash/DatabaseProjectreactions/bin/Debug/DatabaseProjectreactions.dll
    stdout: 
    stdout:   DatabaseProjectreactions -> /Volumes/Storage/CodeRepos/sample-sandbox/delete-bugbash/DatabaseProjectreactions/bin/Debug/DatabaseProjectreactions.dacpac
    stdout: 
    stdout: 
    stdout: 
    stdout: Build succeeded.
    stdout:     0 Warning(s)
    stdout:     0 Error(s)
    stdout: 
    stdout: 
    stdout: Time Elapsed 00:00:01.69
    stdout: 
    >>> "/usr/local/share/dotnet/dotnet"  build "/Volumes/Storage/CodeRepos/sample-sandbox/delete-bugbash/DatabaseProjectreactions/DatabaseProjectreactions.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="/Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory"    … exited with code: 0
    > docker version --format {{.Server.APIVersion}}
    stdout: 1.41
    stdout: 
    >>> docker version --format {{.Server.APIVersion}}    … exited with code: 0
Docker Image:
mcr.microsoft.com/azure-sql-edge
License Agreement:
https://aka.ms/mcr/osslegalnotice
Cleaning existing deployments...
    > docker ps -q -a --filter label=source=sqldbproject-databaseprojectreactions
    >>> docker ps -q -a --filter label=source=sqldbproject-databaseprojectreactions    … exited with code: 0
Creating deployment settings ...
Running the docker container ...
    > docker pull mcr.microsoft.com/azure-sql-edge
    stdout: Using default tag: latest
    stdout: 
    stdout: latest: Pulling from azure-sql-edge
    stdout: 
    stdout: Digest: sha256:dfce05471e259d330e00bc9e66904254d75b714b35edc81495b4faee4a2dba96
    stdout: Status: Image is up to date for mcr.microsoft.com/azure-sql-edge:latest
    stdout: 
    stdout: mcr.microsoft.com/azure-sql-edge:latest
    stdout: 
    >>> docker pull mcr.microsoft.com/azure-sql-edge    … exited with code: 0
    > docker run -p 1433:1433 -e "MSSQL_SA_PASSWORD=***" -e "ACCEPT_EULA=Y" -e "MSSQL_PID=Developer" --label source=sqldbproject-databaseprojectreactions -d --name sqldbproject-databaseprojectreactions-d8622ee6-b797-4a7c-99f5-9e76bd2c9691 mcr.microsoft.com/azure-sql-edge 
    stdout: 56fa02a4ba62737571047c540c2a7aa7d28076b6b436d1ad4cc522fcd97b33e5
    stdout: 
    >>> docker run -p 1433:1433 -e "MSSQL_SA_PASSWORD=***" -e "ACCEPT_EULA=Y" -e "MSSQL_PID=Developer" --label source=sqldbproject-databaseprojectreactions -d --name sqldbproject-databaseprojectreactions-d8622ee6-b797-4a7c-99f5-9e76bd2c9691 mcr.microsoft.com/azure-sql-edge     … exited with code: 0
    > docker ps -q -a --filter label=source=sqldbproject-databaseprojectreactions -q
    stdout: 56fa02a4ba62
    stdout: 
    >>> docker ps -q -a --filter label=source=sqldbproject-databaseprojectreactions -q    … exited with code: 0
Docker container created. Id: 56fa02a4ba62

Waiting for 2 seconds before another attempt for operation 'Validating the docker container'
Running operation 'Validating the docker container' Attempt 0 of 10
    > docker ps -q -a --filter label=source=sqldbproject-databaseprojectreactions -q
    stdout: 56fa02a4ba62
    stdout: 
    >>> docker ps -q -a --filter label=source=sqldbproject-databaseprojectreactions -q    … exited with code: 0
Operation 'Validating the docker container' completed successfully. Result: 56fa02a4ba62

Docker created id: '56fa02a4ba62
'
Waiting for 10 seconds before another attempt for operation 'Connecting to SQL Server'
Running operation 'Connecting to SQL Server' Attempt 0 of 3
Operation 'Connecting to SQL Server' failed. Re-trying... Current Result: {1}. Error: 'Connection failed error: 'A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)''
Waiting for 10 seconds before another attempt for operation 'Connecting to SQL Server'
Running operation 'Connecting to SQL Server' Attempt 1 of 3
Operation 'Connecting to SQL Server' failed. Re-trying... Current Result: {1}. Error: 'Connection failed error: 'A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)''
Waiting for 10 seconds before another attempt for operation 'Connecting to SQL Server'
Running operation 'Connecting to SQL Server' Attempt 2 of 3
Operation 'Connecting to SQL Server' failed. Re-trying... Current Result: {1}. Error: 'Connection failed error: 'A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)''

Extension version: 0.19.0
Azure Data Studio version: azuredatastudio-insiders 1.40.0-insider (d5cf088ba7b794859438fd2c1902249fd1e6a947, 2022-10-26T05:48:43.511Z)
OS version: Darwin arm64 22.1.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by cheenamalhotra**
This PR fixes #20977. 

Options were not being populated for Advanced properties as well as encrypt is now a 'string' type in backend. Addressing both changes fixes the issue and completes the deployment:

image

### CODE REVIEW

File: extensions/sql-database-projects/src/models/connections/connectionService.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ export class ConnectionService {
 				saveProfile: false,
 				id: '',
 				connectionName: profile.profileName,
-				options: [],
+				options: { 'encrypt': 'false' },
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/models/connections/connectionService.ts:45]: Why is encrypt a string? That's very unintuitive - we should at least support both string and boolean if we're going to support string at all.

Comment (kisantia) [inline extensions/sql-database-projects/src/models/connections/connectionService.ts:45]: just wondering, is it only encrypt that the value needs to be string or all options? Unless the value needs to be a string for all options that get set like this, it's not intuitive that you need to use `'false'` rather than `false`

**Review by kisantia — APPROVED** [review]
thanks for the quick fix, Cheena!

**Review by alanrenmsft — APPROVED** [review]

**Review by alanrenmsft — CHANGES_REQUESTED** [review]
actually, should we use the encrypt value from the original profile and only set it to false if it is not set?

File: extensions/sql-database-projects/src/models/connections/connectionService.ts (hunk 1 above)
Comment (cheenamalhotra) [reply extensions/sql-database-projects/src/models/connections/connectionService.ts:45]: It's a string as the values are now 'Mandatory', 'Optional', 'Strict', however we can keep the same support for backwards compat, adding it here: https://github.com/microsoft/sqltoolsservice/pull/1737

**Comment by cheenamalhotra** [comment]
> actually, should we use the encrypt value from the original profile and only set it to false if it is not set?

ISqlConnectionProperties doesn't have 'encrypt' property supported as of now, @kisantia would that be something you want to support in there (defaulting to ADS' new default for Encrypt and also accepting TrustServerCertificate?

**Comment by kisantia** [comment]
> > actually, should we use the encrypt value from the original profile and only set it to false if it is not set?
> 
> ISqlConnectionProperties doesn't have 'encrypt' property supported as of now, @kisantia would that be something you want to support in there (defaulting to ADS' new default for Encrypt (true) and also accepting TrustServerCertificate?

In this case, publish is always happening to a newly created docker container, so there isn't an original profile's encrypt value to use.

**Comment by cheenamalhotra** [comment]
> > > actually, should we use the encrypt value from the original profile and only set it to false if it is not set?
> > 
> > 
> > ISqlConnectionProperties doesn't have 'encrypt' property supported as of now, @kisantia would that be something you want to support in there (defaulting to ADS' new default for Encrypt (true) and also accepting TrustServerCertificate?
> 
> In this case, publish is always happening to a newly created docker container, so there isn't an original profile's encrypt value to use.

I've added a TODO comment for future reference, if profile could provide these params.

**Review by alanrenmsft — APPROVED** [review]
