### PR TITLE
Fix delete and exclude for pre and post deploy scripts

### LINKED ISSUE #12141: Can't delete publish profile from sql project
image

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #12141. Also fixes delete/exclude for publish.xml files because those are "none" entries in the sqlproj

### CODE REVIEW

**Review by udeeshagautam — APPROVED** [review]

File: extensions/sql-database-projects/src/models/project.ts [hunk 1]
```diff
@@ -263,11 +263,11 @@ export class Project {
 		switch (itemType) {
 			case templates.preDeployScript:
 				xmlTag = constants.PreDeploy;
-				this.preDeployScripts.push(fileEntry);
+				this.preDeployScripts.length === 0 ? this.preDeployScripts.push(fileEntry) : this.noneDeployScripts.push(fileEntry);
 				break;
 			case templates.postDeployScript:
 				xmlTag = constants.PostDeploy;
-				this.postDeployScripts.push(fileEntry);
+				this.postDeployScripts.length === 0 ? this.postDeployScripts.push(fileEntry) : this.noneDeployScripts.push(fileEntry);
```
Comment (SakshiS-harma) [inline extensions/sql-database-projects/src/models/project.ts:270]: Thanks for catching this. 
I realized noneDeployScripts was getting populated properly while opening a project; but not while adding a new script.

**Review by SakshiS-harma — APPROVED** [review]
