### PR TITLE
Fix for user using command palette 

### LINKED ISSUE #18926: "Create Azure Function with SQL Binding" fails if no connection is selected
1. Open VS Code and without connecting to a server run the "MS SQL: Create Azure Function with SQL Binding" command

This error appears 

```
Command 'MS SQL: Create Azure Function with SQL binding' resulted in an error (Cannot read properties of undefined (reading 'connectionInfo'))
```

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #18926.
This will be an initial fix so that users can at least have choices to learn more or select a SQL Server connection to select from in order to use `Create Azure Function with SQL Binding`. 

image

If the user chooses - `SQL Server Connections` the SQL Server Extension pane will open showing their connections.
Learn more sends them to aka.ms/sqlbindings

Future feature: 
- prompt user for connection, database and then table/view when they use this command from the command palette

### CODE REVIEW

**Comment by VasuBhog** [comment]
@dzsquared can you look over the error message/buttons we prompt to the user and see if we should change any wording.

File: extensions/sql-bindings/src/extension.ts [hunk 1]
```diff
@@ -17,7 +18,19 @@ export async function activate(context: vscode.ExtensionContext): Promise<IExten
 	context.subscriptions.push(vscode.commands.registerCommand('sqlBindings.addSqlBinding', async (uri: vscode.Uri | undefined) => { return launchAddSqlBindingQuickpick(uri); }));
 	// Generate Azure Function command
 	context.subscriptions.push(vscode.commands.registerCommand('sqlBindings.createAzureFunction', async (node: ITreeNodeInfo) => {
-		let connectionInfo = node.connectionInfo;
+		if (!node) {
+			let openServerPane = await vscode.window.showErrorMessage(constants.chooseAConnection,
+				constants.openPane, constants.learnMore);
+			if (openServerPane === constants.openPane) {
+				// open SQL Server connections pane
+				await vscode.commands.executeCommand('objectExplorer.focus');
```
[the remark this answers is not in the document]
Comment (VasuBhog) [reply extensions/sql-bindings/src/extension.ts:26]: I am a bit confused about what you mean here? Using the promptForConnection to list connections and then connect to the selected connection and open the objectExplorer for the user to see?

In VS Code this would open up the pane.

[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/extension.ts:26]: Yes, using promptForConnection is what I meant (and then continuing on with the connection info that it returns back)

I though this was for ADS at first - so then my question is "what about ADS"? The plan is to publish this there as well, right?

[the remark this answers is not in the document]
Comment (VasuBhog) [reply extensions/sql-bindings/src/extension.ts:26]: Not sure what you mean by continuing with the connection info. We would need the schema and table to pass into the `createAzureFunction` below. That is why I stated in the description it would be a future feature where we would have to prompt for databases (using API) and then tables/views (which have not been created).

The plan is to publish there as well, however, all the use cases as far as I know are for VS Code.

[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/extension.ts:26]: Gotcha, missed/forgot about the part where you need to prompt for the table/view. We could just have them type it in manually too - we already do this in other places. And given that we still need to prompt for a connection regardless that seems like a good thing to get in now if we can.

What do you mean the "use cases"? The commands can be ran in both VS Code and ADS so should function in both (or be disabled if they aren't applicable). Have you tested this in ADS at all?

[the remark this answers is not in the document]
Comment (VasuBhog) [reply extensions/sql-bindings/src/extension.ts:26]: I'll go ahead and do that now. 

In terms of use cases, we targeted VS code development. Would there be a way to remove the command from ADS specifically?

File: extensions/sql-bindings/src/common/constants.ts [hunk 2]
```diff
@@ -32,6 +32,8 @@ export const timeoutProjectError = localize('timeoutProjectError', 'Timed out wa
 export const errorNewAzureFunction = localize('errorNewAzureFunction', 'Error creating new Azure Function: {0}');
 export const azureFunctionsExtensionNotInstalled = localize('azureFunctionsExtensionNotInstalled', 'Azure Functions extension must be installed in order to use this feature.');
 export const azureFunctionsProjectMustBeOpened = localize('azureFunctionsProjectMustBeOpened', 'A C# Azure Functions project must be present in order to create a new Azure Function for this table.');
+export const chooseAConnection = localize('chooseAConnection', 'A SQL Server table must be selected to use this feature.');
```
Comment (dzsquared) [inline extensions/sql-bindings/src/common/constants.ts:35]: "A SQL table must be selected to use this feature."

(we support more than SQL Server so keeping it generic is good)

File: extensions/sql-bindings/src/extension.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/extension.ts:26]: `"when": "!azdataAvailable"`

[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/extension.ts:26]: When are you planning on adding ADS support? That shouldn't be too hard to do and it would be good to keep the feature set at parity when possible.

File: extensions/sql-bindings/src/common/constants.ts (hunk 2 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/common/constants.ts]: Since I decided to add prompts I removed this since we can get all the required information to start the createAzureFunction.

File: extensions/sql-bindings/package.json [hunk 3]
```diff
@@ -41,7 +41,7 @@
         "command": "sqlBindings.createAzureFunction",
         "title": "%sqlBindings.createAzureFunction%",
         "category": "MS SQL",
-        "when": "view == objectExplorer && viewItem == Table"
+        "when": "view == objectExplorer && viewItem == Table && !azdataAvailable"
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/package.json:44]: Is this when even valid here? I don't see "when" being a valid clause for "commands" contributions 

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/actions/common/menusExtensionPoint.ts#L527

Are you seeing this correctly hidden in ADS or something?

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/sql-bindings/src/extension.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (VasuBhog) [reply extensions/sql-bindings/src/extension.ts]: I want to focus on vscode support first. Once all these PRs are in I can see if I can put this as a priority.

File: extensions/sql-bindings/src/extension.ts [hunk 4]
```diff
@@ -16,22 +17,74 @@ export async function activate(context: vscode.ExtensionContext): Promise<IExten
...
+				if (newNode.nodeType === 'Database') {
+					connectionInfo.database = newNode.metadata.name;
+					break;
+				} else {
+					newNode = newNode.parentNode;
+				}
+			}
+			objectName = generateQuotedFullName(node.metadata.schema, node.metadata.name);
+		}
+		if (!connectionInfo) {
```
[the remark this answers is not in the document]
Comment (VasuBhog) [reply extensions/sql-bindings/src/extension.ts:77]: Yes, since `Argument of type 'IConnectionInfo | undefined' is not assignable to parameter of type 'IConnectionInfo'.
  Type 'undefined' is not assignable to type 'IConnectionInfo'.`.  I thought this as well, but it still complains if I remove this.

File: extensions/sql-bindings/src/common/utils.ts [hunk 5]
```diff
@@ -162,6 +162,18 @@ export function escapeClosingBrackets(str: string): string {
 	return str.replace(']', ']]');
 }
 
+export function checkBrackets(objectName: string): string {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/utils.ts:165]: This is doing more than just "checking" brackets. Make sure your function names clearly indicate what the function is actually doing (and use doc comments for further details if needed)

File: extensions/sql-bindings/src/common/utils.ts [hunk 6]
```diff
@@ -162,6 +162,18 @@ export function escapeClosingBrackets(str: string): string {
...
+	if (objectName.includes('.')) {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/utils.ts:166]: Object names can have . in them too so this check isn't enough. (e.g. a table named `My.Table` is valid).

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 7]
```diff
@@ -12,15 +12,109 @@ import * as constants from '../common/constants';
...
+
+			// prompt user for object name to create function from
+			objectName = await azureFunctionsUtils.promptForObjectName(selectedBinding.type);
+
+		} catch (e) {
+			void vscode.window.showErrorMessage(utils.getErrorMessage(e));
+			propertyBag.quickPickStep = quickPickStep;
+			exitReason = 'error';
+			TelemetryReporter.createErrorEvent(TelemetryViews.CreateAzureFunctionWithSqlBinding, TelemetryActions.exitCreateAzureFunctionQuickpick, undefined, utils.getErrorType(e))
+				.withAdditionalProperties(propertyBag).send();
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:81]: Shouldn't we be returning here?

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 8]
```diff
@@ -12,15 +12,109 @@ import * as constants from '../common/constants';
...
+			return;
+		}
+		selectedBindingType = selectedBinding.type;
+		propertyBag.bindingType = selectedBinding.type;
+		TelemetryReporter.createActionEvent(TelemetryViews.CreateAzureFunctionWithSqlBinding, TelemetryActions.startCreateAzureFunctionWithSqlBinding)
+			.withAdditionalProperties(propertyBag).withConnectionInfo(connectionInfo).send();
+
+		objectName = utils.generateQuotedFullName(node.metadata.schema, node.metadata.name);
+	}
+	if (!objectName || !connectionInfo || !selectedBindingType) {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:112]: I would generally suggest instead that you do these checks right after prompting for each of these. As mentioned above it's better practice to exit as early as possible in those scenarios.

File: extensions/sql-bindings/src/common/utils.ts [hunk 9]
```diff
@@ -162,6 +162,28 @@ export function escapeClosingBrackets(str: string): string {
 	return str.replace(']', ']]');
 }
 
+/**
+ * Gets a unique object name by removing all special characters
+ * @param objectName can include brackets/periods and user entered special characters
+ * @returns the object name without any special characters
+ */
+export function getUniqueObjectName(objectName: string): string {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/utils.ts:170]: There's nothing about this that's making it "unique". I would instead call this `sanitizeObjectName`

File: extensions/sql-bindings/src/common/utils.ts [hunk 10]
```diff
@@ -162,6 +162,28 @@ export function escapeClosingBrackets(str: string): string {
...
+	return objectName.replace(/[^a-zA-Z0-9 ]/g, '');
+}
+
+/**
+ * Check to see if the input from user entered is valid
+ * @param input from user input
+ * @returns false if the input is empty or has special characters, true if the input is valid
+ */
+export function checkInput(input: string): boolean {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/utils.ts:179]: This is a pretty generic name for the function, I'd suggest something clearer like `hasOnlyAlphanumericCharacters`.

But also I think it would be better to have this return `string | undefined` and then return the error message associated with the specific error. So have two errors, one for if it's empty and another if it has non-alphanumeric characters. Then a better name would be `validateFunctionName` I think

Comment (VasuBhog) [reply extensions/sql-bindings/src/common/utils.ts]: With new fix user will see this:
- Special Characters
Screen Shot 2022-04-07 at 7 38 08 PM

- Empty
Screen Shot 2022-04-07 at 7 38 12 PM

**Review by Charles-Gagnon — APPROVED** [review]
