### PR TITLE
Fix for table resizing

### LINKED ISSUE #9061: Edit Data grid doesn't properly resize when showing\hiding SQL Pane
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open Edit Data on a table with lots of rows and columns (~100+ rows and ~10+ columns) so that the grid requires horizontal and vertical scrollbars
2. Open the SQL Pane window and update the `TOP` clause to be something like `TOP 10`
3. Collapse and reexpand the SQL pane

Note: this is just one example variant of the repro

Expected: The grid is resized so that scrollbars are positioned correctly and there is no extraneous whitespace

Actual: Resizing is inconsistent and not correct.  The two screenshots below show a couple examples.

**Example 1**
image

**Example 2**
image

### PR DESCRIPTION
**Pull request by smartguest**
EditData now calls the table's resize function. (originally it fired events that called the same function in angular-slickgrid, which broke when angular was removed) 

OnScroll was unsubscribed as it caused an infinite loop.

Also incorporated fixes for crashing when either the bottom or top sashes are dragged and covering the table.

This PR fixes #9061

### CODE REVIEW

File: src/sql/workbench/contrib/editData/browser/gridParentComponent.ts [hunk 1]
```diff
@@ -499,15 +501,19 @@ export abstract class GridParentComponent extends Disposable {
...
 	protected abstract tryHandleKeyEvent(e: StandardKeyboardEvent): boolean;
 
-	resizeGrids(): void {
+	resizeGrid(): void {
 		const self = this;
 		setTimeout(() => {
-			for (let grid of self.renderedDataSets) {
-				grid.resized.fire();
-			}
+			setTimeout(() => self.onResize(), 100);
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/gridParentComponent.ts]: is there a need to have `setTimeout` call recursively call `setTimeout` vs. calling `onResize()` directly?

File: src/sql/workbench/contrib/editData/browser/gridParentComponent.ts [hunk 2]
```diff
@@ -63,6 +63,8 @@ export abstract class GridParentComponent extends Disposable {
 	private queryEditorVisible: IContextKey<boolean>;
 
 	// All datasets
+	//main dataset to work on.
+	protected dataSet: IGridDataSet;
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/gridParentComponent.ts]: it's not clear to me why this variable is being moved to this class?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 3]
```diff
@@ -1034,27 +1030,15 @@ export class EditDataGridPanel extends GridParentComponent {
...
 		// so, grid must be there already
 
-		if (this.dataSet.dataRows && this.dataSet.dataRows.getLength() > 0) {
+		if (this.placeHolderDataSets[0].dataRows && this.placeHolderDataSets[0].dataRows.getLength() > 0) {
 			this.table.grid.scrollRowToTop(0);
 		}
 
-		if (this.dataSet.resized) {
-			// Re-rendering the grid is expensive. Throttle so we only do so every 100ms.
-			this.dataSet.resized.throttleTime(100)
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: I don't see any `throttleTime` equivalent in the changed code (unless I'm missing something).  Is the throttling no longer needed to avoid excessive re-rendering?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 4]
```diff
@@ -810,6 +808,7 @@ export class EditDataGridPanel extends GridParentComponent {
 				for (let i = 0; i < dataSet.columnDefinitions.length; i++) {
 					this.columnNameToIndex[this.dataSet.columnDefinitions[i].name] = i;
 				}
+				this.onResize();
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: the grid seems to be created the correct size as far as I can tell.  why is this call needed here?

File: src/sql/workbench/contrib/editData/browser/editDataEditor.ts [hunk 5]
```diff
@@ -290,12 +292,28 @@ export class EditDataEditor extends BaseEditor {
...
 		}
 
 		this._sash.show();
 	}
 
+	/**
+	 * Checks if the current position of the sash doesn't cover the first row of the table.
+	 * If large enough, do layout. Else if too small, hide result editor to prevent crashing.
+	 */
+	private _positionCheck(position: number) {
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editDataEditor.ts]: please don't add a `_` prefix to function names.  this isn't the code convention we're following in this codebase generally.  You can add `_` to private variable names if that is the convention being used in that file.  That varies from file-to-file in this codebase.

File: src/sql/workbench/contrib/editData/browser/editDataEditor.ts [hunk 6]
```diff
@@ -45,7 +45,9 @@ export class EditDataEditor extends BaseEditor {
 	public static ID: string = 'workbench.editor.editDataEditor';
 
 	// The minimum width/height of the editors hosted in the QueryEditor
-	private readonly _minEditorSize: number = 55;
+	private readonly _minEditorSize: number = 60;
+	// Minimum position for the sash to ensure editor is at minimum height.
+	private readonly _minPositionSize: number = 40;
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editDataEditor.ts]: how did you determine this value?  does it work correctly when using customized font and grid size settings?  or in different zoom levels, etc.?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 7]
```diff
@@ -426,9 +424,9 @@ export class EditDataGridPanel extends GridParentComponent {
 			clearTimeout(self.refreshGridTimeoutHandle);
 			this.refreshGridTimeoutHandle = setTimeout(() => {
 
-				if (self.dataSet && self.placeHolderDataSets[0].resized) {
+				if (self.dataSet) {
 					self.placeHolderDataSets[0].dataRows = self.dataSet.dataRows;
-					self.placeHolderDataSets[0].resized.fire();
+					setTimeout(() => this.onResize(), 100);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: Is this supposed to replace the throttle? That isn't what's going to happen here - it'll just delay the call by 100ms but if this function is called multiple times in a row then each of those will queue up and fire separately. 

(There's some extra consideration here for how we're handling the refresh grid batching/throttling, but in general I don't see why the timeout here is doing anything useful. Especially if it's supposed to replace the throttle call.)

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 3 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: Throttling is no longer needed to avoid re-rendering as its only rerendered when its needed

File: src/sql/workbench/contrib/editData/browser/editDataEditor.ts (hunk 6 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataEditor.ts]: It was determined after running numerous tests, that it was the minimum size that is required for the grid to show the first row, without anything overlapping it, if the first row was covered over in any way, it would cause a crash.

File: src/sql/workbench/contrib/editData/browser/editDataEditor.ts [hunk 8]
```diff
@@ -290,12 +292,28 @@ export class EditDataEditor extends BaseEditor {
...
 
 		this._sash.show();
 	}
 
+	/**
+	 * Checks if the current position of the sash doesn't cover the first row of the table.
+	 * If large enough, do layout. Else if too small, hide result editor to prevent crashing.
+	 */
+	private _positionCheck(position: number) {
+		if (position < this._minPositionSize) {
```
[the remark this answers is not in the document]
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataEditor.ts]: It is relative to the sash's actual position in the editor.

File: src/sql/workbench/contrib/editData/browser/editDataEditor.ts [hunk 9]
```diff
@@ -290,12 +292,28 @@ export class EditDataEditor extends BaseEditor {
...
-			this._register(this._sash.onPositionChange(position => this._doLayout()));
+			this._register(this._sash.onPositionChange(position => this._positionCheck(position)));
 		}
 
 		this._sash.show();
 	}
 
+	/**
+	 * Checks if the current position of the sash doesn't cover the first row of the table.
+	 * If large enough, do layout. Else if too small, hide result editor to prevent crashing.
```
[the remark this answers is not in the document]
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataEditor.ts]: What happens is that, if the first row of the grid is overlapped in any way, it will crash unexpectedly (with the sash dragged over it), so it will have to be hidden to prevent it from crashing.

**Comment by smartguest** [comment]
After evaluating the code, I found out that the reason the crash is happening was that the isCellOnScreen method wasn't written properly and fired even when the last visible cell was covered, causing an infinite loop to occur, it has been removed, and the toggle panel check has been removed to account for this.

File: src/sql/workbench/contrib/editData/browser/gridParentComponent.ts (hunk 1 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/gridParentComponent.ts]: going to call it directly

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 10]
```diff
@@ -429,9 +429,9 @@ export class EditDataGridPanel extends GridParentComponent {
 			clearTimeout(self.refreshGridTimeoutHandle);
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: this method is intermixing `self` and `this` seemingly interchangeably.  This can lead to subtle difference based on how the method is invoked.  Could you please update such that we only use one or other consistently within a various execution scope?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 11]
```diff
@@ -425,22 +425,24 @@ export class EditDataGridPanel extends GridParentComponent {
...
-					self.detectChange();
-					self.oldDataRows = self.placeHolderDataSets[0].dataRows;
+				if (this.oldDataRows !== this.placeHolderDataSets[0].dataRows) {
+					this.detectChange();
+					this.oldDataRows = this.placeHolderDataSets[0].dataRows;
 				}
 
-				if (self.firstRender) {
+				if (this.firstRender) {
+					let self = this;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: You're still mixing self and this  here - if you're updating these to use this then these should also do that

File: src/sql/workbench/contrib/editData/browser/gridParentComponent.ts [hunk 12]
```diff
@@ -501,10 +501,14 @@ export abstract class GridParentComponent extends Disposable {
 	resizeGrids(): void {
 		const self = this;
 		setTimeout(() => {
-			for (let grid of self.renderedDataSets) {
-				grid.resized.fire();
-			}
-		});
+			self.onResize();
+		}, 100);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/gridParentComponent.ts]: Why do you have this delay here?

File: src/sql/workbench/contrib/editData/browser/gridParentComponent.ts [hunk 13]
```diff
@@ -501,10 +501,14 @@ export abstract class GridParentComponent extends Disposable {
...
+	}
+
+	protected onResize() {
+		if (this.table) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/gridParentComponent.ts]: This can be simplified to `this.table?.resizeCanvas();`

File: src/sql/workbench/contrib/editData/browser/gridParentComponent.ts [hunk 14]
```diff
@@ -501,10 +501,14 @@ export abstract class GridParentComponent extends Disposable {
 	resizeGrids(): void {
 		const self = this;
 		setTimeout(() => {
-			for (let grid of self.renderedDataSets) {
-				grid.resized.fire();
-			}
-		});
+			self.onResize();
```
Comment (aaomidi) [inline src/sql/workbench/contrib/editData/browser/gridParentComponent.ts]: Shouldn't need self here either 

Arrow lambdas preserve this.

Explanation: 
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-this-alias.md

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 11 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: I'm getting an outer value error when I attempt to use this inside the setActive function, I will have to move it out then
