### PR TITLE
Focus projects view when New Project is created

### LINKED ISSUE #10976: Creating SQL is not visible in UI to show project created successfully
- Azure Data Studio Version:

Steps to Reproduce:

1. Open connection viewlet
2. Create a new project
Expected: The view let for project should has the focus or some message should show up
Actua: I didn't see anything in the UI so didn't know if project created successfully.  Then I noticed the project viewlet is added but the UI focus was still on connection viewlet

### PR DESCRIPTION
**Pull request by Benjin**
Fixes #10976; already focuses for projects when imported or opened

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/mainController.ts [hunk 1]
```diff
@@ -137,8 +137,11 @@ export default class MainController implements Disposable {
 			// TODO: what if the selected folder is outside the workspace?
 
 			const newProjFolderUri = (selectionResult as Uri[])[0];
-			const newProjFilePath = await this.projectsController.createNewProject(newProjName as string, newProjFolderUri as Uri);
-			return this.projectsController.openProject(Uri.file(newProjFilePath));
+			const newProjFilePath = await this.projectsController.createNewProject(<string>newProjName, newProjFolderUri);
+			const proj = await this.projectsController.openProject(Uri.file(newProjFilePath));
+			await this.projectsController.focusProject(proj);
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/mainController.ts:142]: would it be easier if `this.projectsController.openProject()` already focused the project being opened so `this.projectsController.focusProject()` doesn't need to be called separately for open, import, and new project?

Comment (Benjin) [reply extensions/sql-database-projects/src/controllers/mainController.ts:142]: Good call.

**Comment by udeeshagautam** [comment]
Please try to rerun Pr vlidation
