### PR TITLE
fix adding nested items not being created in the correct location in the project

### LINKED ISSUE #17963: Creating items follow there own placement, instead of SSDT
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a project in SSDT
2. Import database in project
3. This (by default) creates a schema/object folder structure (dbo/tables/tablename.sql)
4. Opening the project with VSCode/Azure Data Studio and right click tables folder (node) new item -> table

This creates a tables folder in the root of the project, instead in the tables folder that already exists

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #17963. This was already fixed in main in #17826, but to minimize the changes, this PR only has the 2 line fix and test change. This looks related to this previous test issue that #11026 that wasn't investigated before because it was only failing in tests.

This wasn't a problem before because this line of code wasn't being hit in most cases. By default when created in VS or ADS, sqlprojs have the folders listed first before the files and the project loading logic would go through the ItemGroups in order so the folders would be loaded first. If the order is changed to have files first, then folders, this would also be a problem in the previous extension versions. The test was previously failing because the folder was added after the files.

This got exposed in recent changes because the order that the sqlproj is read changed so that files are loaded first, then folders(https://github.com/microsoft/azuredatastudio/pull/17637). The change in order is because files and folders don't need to listed in the sqlproj for SDK style projects. There's a default glob to include sql files in the same folder as the sqlproj. Empty folders aren't included, so the files need to be loaded first so that only the folders containing project files and folders explicitly listed in the sqlproj are shown in the project tree.

Also fixes https://github.com/microsoft/azuredatastudio/issues/17984, which was introduced now that the code in ProjectTreeItem.ts is getting hit.

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -660,7 +660,10 @@ export class ProjectsController {
 		if (root && fileOrFolder) {
 			// use relative path and not tree paths for files and folder
 			const allFileEntries = project.files.concat(project.preDeployScripts).concat(project.postDeployScripts).concat(project.noneDeployScripts);
-			return allFileEntries.find(x => utils.getPlatformSafeFileEntryPath(x.relativePath) === utils.getPlatformSafeFileEntryPath(utils.trimUri(root.fileSystemUri, fileOrFolder.fileSystemUri)));
+
+			// trim trailing slash since folders with and without a trailing slash are allowed in a sqlproj
+			const trimmedUri = utils.trimChars(utils.getPlatformSafeFileEntryPath(utils.trimUri(root.fileSystemUri, fileOrFolder.fileSystemUri)), '/');
+			return allFileEntries.find(x => utils.trimChars(utils.getPlatformSafeFileEntryPath(x.relativePath), '/') === trimmedUri);
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/projectController.ts:666]: had to also port this over from #17826 now that the code in projectTreeItem.ts is getting hit

**Review by chlafreniere — APPROVED** [review]
