### PR TITLE
controller dropdown field to SQL MIAA and Postgres deployment.

### LINKED ISSUE #11599: Need to check for azdata login context before attempting azdata-based actions
- Azure Data Studio Version:

Steps to Reproduce:

1.Try to deploy a SQL or PG instance via the ADS deployment wizard.  If the user doesnt login via azdata login prior to running the wizard it will fail.

Version: 1.19.0-insider (user setup)
Commit: 187667f4f1f52ee5e5a4b74e9a183574d6f46273
Date: 2020-06-10T05:36:56.219Z
VS Code: 1.46.0
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Name: Azure Arc deployment extension for Azure Data Studio (preview)
Id: microsoft.arcdeployment
Description: Provides an experience to deploy Azure SQL DB managed instances and Azure Database for PostgreSQL Hyperscale server groups on Azure Arc from Azure Data Studio. This extension is only applicable to customers in the Azure Arc data services private preview.
Version: 0.3.1
Publisher: Microsoft

From: Pradeep
Sent: Thursday, June 11, 2020 6:02 PM

Hi Team,

As we are aware many of the azdata commands expect the login context to be set with the controller, Is it possible to include login functionality into SQL/PGSQL deployment wizard in ADS.

At present the deployment experience is failing with the following error. How long the azdata stores the login context to a specific controller , when it will expire , does it have a renewal functionality.

Please let me know if you want me to file a request for the same to triage this.

For sure it’s possible for customer to execute login command from console and re-run the notebook but providing a single window experience to have a successful deployment would be great.

 
Creating a PostgreSQL server group on Azure Arc

ERROR: You must be authenticated to run this command. First run the azdata login --help for more information on how to login.

An exception has occurred, use %tb to see the full traceback.

SystemExit: exit code: 1

C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\lib\site-packages\IPython\core\interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.

### PR DESCRIPTION
**Pull request by ranasaria**
This PR adds a controller dropdown field to SQL MIAA and Postgres deployment in ARC. 
It adds a feature to allow options fieldType to 'source' the option values presented to the user using a code block that can execute arbitrary code to populate the options. This feature is used for the controller dropdown mentioned above.
Changes are done to the sample-resource-deployment extension to show how the feature is expected to be used.

Testing: End to end testing done
Fixes: #11599

### CODE REVIEW

File: extensions/resource-deployment/src/interfaces.ts [hunk 1]
```diff
@@ -171,9 +172,17 @@ export type ComponentCSSStyles = {
 	[key: string]: string;
 };
 
+export interface IOptionsSource {
+	readonly type: OptionsSourceType,
+	readonly variableNames: { [index: string]: string; },
+	getOptions(): Promise<string[]>,
```
Comment (alanrenmsft) [inline extensions/resource-deployment/src/interfaces.ts:178]: it could also be azdata.categoryvalue[], right?

Comment (ranasaria) [reply extensions/resource-deployment/src/interfaces.ts]: fixed

File: extensions/arc/src/extension.ts [hunk 2]
```diff
@@ -57,15 +58,23 @@ export async function activate(context: vscode.ExtensionContext): Promise<arc.IE
 	await checkArcDeploymentExtension();
 
 	return {
-		getRegisteredDataControllers: async () => {
-			return (await treeDataProvider.getChildren())
-				.filter(node => node instanceof ControllerTreeNode)
-				.map(node => (node as ControllerTreeNode).model.info);
-
+		getRegisteredDataControllers: async () => (await treeDataProvider.getChildren())
```
Comment (aaomidi) [inline extensions/arc/src/extension.ts:61]: This really feels like it should be implemented at a class level rather than an anonymous set of functions as a return statement.

File: extensions/arc/src/typings/arc.d.ts [hunk 3]
```diff
@@ -33,10 +33,12 @@ declare module 'arc' {
 		username: string,
 		rememberPassword: boolean,
 		resources: ResourceInfo[]
+
 	};
 
 	export interface IExtension {
-		getRegisteredDataControllers(): Promise<ControllerInfo[]>;
+		getRegisteredDataControllers(): Promise<{ label: string, info: ControllerInfo }[]>;
```
Comment (aaomidi) [inline extensions/arc/src/typings/arc.d.ts:40]: I'd export this type to some alias since you use it elsewhere too

File: extensions/arc/package.nls.json [hunk 4]
```diff
@@ -76,6 +76,9 @@
 	"resource.type.picker.display.name": "Resource Type",
 	"sql.managed.instance.display.name": "Azure SQL managed instance - Azure Arc",
 	"postgres.server.group.display.name": "PostgreSQL server groups - Azure Arc",
+
+	"arc.controller": "Arc Controller to deploy to",
```
Comment (alanrenmsft) [inline extensions/arc/package.nls.json:80]: Target arc controller?

File: extensions/arc/src/extension.ts (hunk 2 above)
Comment (alanrenmsft) [reply extensions/arc/src/extension.ts:61]: for the extension i am working on, even though there is only one method at this time, I still moved it to a separate class. cleaner and easier to test 😆

File: extensions/resource-deployment/src/helpers/optionSources.ts [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+
+import { apiService } from '../services/apiService';
+import * as arc from 'arc';
+import { throwUnless } from '../utils';
+import * as loc from '../localizedConstants';
+import { IOptionsSource } from '../interfaces';
+import { CategoryValue } from 'azdata';
+
+
+export type OptionsSourceType = 'ArcControllersOptionsSource';
```
Comment (alanrenmsft) [inline extensions/resource-deployment/src/helpers/optionSources.ts:14]: the name of the type is too generic for its actual value

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
please fix the build errors.

**Comment by chlafreniere** [comment]
@ranasaria there are hygiene check failures. do you bypass these when pushing? I'm confused.

File: extensions/arc/src/extension.ts (hunk 2 above)
Comment (ranasaria) [reply extensions/arc/src/extension.ts:61]: I agree but I will do this later in a different PR because there are a bunch of these in the azdata extension also. I also want to know Charles' views on this

File: extensions/arc/src/typings/arc.d.ts (hunk 3 above)
Comment (ranasaria) [reply extensions/arc/src/typings/arc.d.ts:40]: I wanted by no suitable name came to my mind. I will think more :)

File: extensions/resource-deployment/src/helpers/optionSources.ts (hunk 5 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/helpers/optionSources.ts:14]: Why this is an OptionsSource to get arc controllers

**Comment by ranasaria** [comment]
> @ranasaria there are hygiene check failures. do you bypass these when pushing? I'm confused.

No, I do not bypass hygiene checks, but I use a vscode git extension to push changes. For some reason, the hygiene check obviously got skipped this time. I will look into it. I had trouble with extension in the past also.

File: extensions/arc/package.nls.json (hunk 4 above)
Comment (ranasaria) [reply extensions/arc/package.nls.json:80]: changed

File: extensions/arc/src/extension.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply extensions/arc/src/extension.ts:61]: Sure, seems reasonable to me. But yeah we can do that in a separate PR I think.

File: extensions/arc/notebooks/arcDeployment/deploy.sql.existing.arc.ipynb [hunk 6]
```diff
@@ -50,7 +50,7 @@
         {
             "cell_type": "code",
             "source": [
-                "import sys,os,json,subprocess\n",
+                "import sys,os,json,subprocess,pprint\n",
```
Comment (ranasaria) [inline extensions/arc/notebooks/arcDeployment/deploy.sql.existing.arc.ipynb:53]: remove pprint

Comment (ranasaria) [reply extensions/arc/notebooks/arcDeployment/deploy.sql.existing.arc.ipynb]: done

File: extensions/azdata/src/localizedConstants.ts [hunk 7]
```diff
@@ -23,7 +23,7 @@ export const decline = localize('azdata.decline', "Decline");
 export const doNotAskAgain = localize('azdata.doNotAskAgain', "Don't Ask Again");
 export const askLater = localize('azdata.askLater', "Ask Later");
 export const downloadingTo = (name: string, location: string): string => localize('azdata.downloadingTo', "Downloading {0} to {1}", name, location);
-export const executingCommand = (command: string, args: string[]): string => localize('azdata.executingCommand', "Executing command \"{0} {1}\"", command, args?.join(' '));
+export const executingCommand = (command: string, args: string[]): string => localize('azdata.executingCommand', "Executing command: '{0} {1}'", command, args?.join(' '));
```
Comment (ranasaria) [inline extensions/azdata/src/localizedConstants.ts:26]: for azdata, the command is already a double-quoted fully qualified path. So using "" to wrap the full azdata execution command line was making it harder to read.

File: extensions/azdata/src/azdata.ts [hunk 8]
```diff
@@ -136,7 +136,7 @@ export class AzdataTool implements IAzdataTool {
 					// to get the correct stderr out. The actual value we get is something like
 					// ERROR: { stderr: '...' }
 					// so we also need to trim off the start that isn't a valid JSON blob
-					err.stderr = JSON.parse(err.stderr.substring(err.stderr.indexOf('{'))).stderr;
+					err.stderr = JSON.parse(err.stderr.substring(err.stderr.indexOf('{'), err.stderr.indexOf('}') + 1)).stderr;
```
Comment (ranasaria) [inline extensions/azdata/src/azdata.ts:139]: when --debug is turned out there are some execution time details that are appended to the error json so taking substring up to ending '}' brace of this error.

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 9]
```diff
@@ -149,3 +175,51 @@ export class ConnectToControllerDialog extends InitializingComponent {
...
+		if (!this.passwordInputBox.value) {
+			return false;
+		}
+		const azdataApi = <azdataExt.IExtension>vscode.extensions.getExtension(azdataExt.extension.name)?.exports;
+		try {
+			await azdataApi.azdata.login(this.urlInputBox.value!, this.usernameInputBox.value!, this.passwordInputBox.value);
+		} catch (e) {
+			if (getErrorMessage(e).match(/Wrong username or password/i)) {
+				this.dialog.message = {
+					text: loc.invalidPassword,
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:195]: Why aren't you just printing the error message directly? azdata should be providing us with a useful error message I'd hope...

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 10]
```diff
@@ -149,3 +175,51 @@ export class ConnectToControllerDialog extends InitializingComponent {
...
+					level: azdata.window.MessageLevel.Error
+				};
+				return false;
+			} else {
+				this.dialog.message = {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:200]: This message string mentions "taking corrective actions". But I don't understand what that would mean here - how is the user supposed to know what to do to "fix" it when the login fails? 

In general with my comment above I don't see why we're trying to do our own logic here instead of just displaying the error message from the login directly.

File: extensions/resource-deployment/src/helpers/optionSources.ts [hunk 11]
```diff
@@ -0,0 +1,108 @@
...
+		const sourceConstructor = OptionsSources.get(optionsSourceType);
+		throwUnless(sourceConstructor !== undefined, loc.noOptionsSourceDefined(optionsSourceType));
+		const obj = new sourceConstructor();
+		obj._type = optionsSourceType;
+		obj._variableNames = variableNames;
+		return obj;
+	}
+}
+
+export class ArcControllersOptionsSource extends OptionsSource {
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/helpers/optionSources.ts:43]: So you're still making it so that the resource-deployment extension has to know about every single consumer and implement some of the logic itself? I mean at this point you might as well just have it call the azdata extension directly instead of using arc....

If we're going to do this feature it should really be more generic and something that the extensions contribute - where they can register option providers with the resource-deployment extension that are used to populate the fields. An option provider would be super generic and all the logic would be done on the contributing extension side.

File: extensions/resource-deployment/src/localizedConstants.ts [hunk 12]
```diff
@@ -13,12 +15,22 @@ export const resourceGroup = localize('azure.account.resourceGroup', "Resource G
...
 export const NewResourceGroupAriaLabel = localize('azure.resourceGroup.NewResourceGroupAriaLabel', "New resource group name");
 export const realm = localize('deployCluster.Realm', "Realm");
-
-
+export const unexpectedOptionsSourceType = (type: OptionsSourceType) => localize('optionsSourceType.Invalid', "Invalid options source type:{0}", type);
+export const unknownFieldTypeError = (type: FieldType) => localize('UnknownFieldTypeError', "Unknown field type: \"{0}\"", type);
+export const variableValueFetchForUnsupportedVariable = (variableName: string) => localize('getVariableValue.unknownVariableName', "Attempt to get variable value for unknown variable:{0}", variableName);
+export const isPasswordFetchForUnsupportedVariable = (variableName: string) => localize('getIsPassword.unknownVariableName', "Attempt to get isPassword for unknown variable:{0}", variableName);
+export const noControllersConnected = localize('noControllersConnected', "No ARC controllers are currently connected. Please run the command: 'Connect to Existing Azure Arc Controller' and then try again");
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/localizedConstants.ts:29]: Don't know where `ARC` came from but you should be using the actual product name if this is displayed to users

File: extensions/resource-deployment/src/services/apiService.ts [hunk 13]
```diff
@@ -25,6 +28,16 @@ class ApiService implements IApiService {
 		}
 		return this.azurecoreApi;
 	}
+
+	public async getArcApi(): Promise<arc.IExtension> {
+		if (!this.arcApi) {
+			this.arcApi = <arc.IExtension>(await vscode.extensions.getExtension(arc.extension.name)?.activate());
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/services/apiService.ts:34]: Don't do this - just use the exports instead (When I implemented the azurecore version of this I didn't know enough about the area - but doing activate here is pretty much unnecessary since if it isn't activated there's no way we'd be able to do anything anyways so requiring the async call is just annoying to deal with)

File: extensions/resource-deployment/src/ui/deploymentInputDialog.ts [hunk 14]
```diff
@@ -110,7 +110,7 @@ export class DeploymentInputDialog extends DialogBase {
 				});
 			}
 		} else {
-			vscode.commands.executeCommand(this.dialogInfo.command, model);
+			await vscode.commands.executeCommand(this.dialogInfo.command, model);
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/deploymentInputDialog.ts:113]: Next time it'd be good to split fixes like these up into a separate PR so it's easier to review both parts.

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 15]
```diff
@@ -3,31 +3,34 @@
...
 const localize = nls.loadMessageBundle();
 
 export type Validator = () => { valid: boolean, message: string };
 export type InputValueTransformer = (inputValue: string) => string;
+export type InputValueTransformerAsync = (inputValue: string) => Promise<string>;
 export type InputComponent = azdata.TextComponent | azdata.InputBoxComponent | azdata.DropDownComponent | azdata.CheckBoxComponent | RadioGroupLoadingComponentBuilder;
 export type InputComponentInfo = {
 	component: InputComponent;
 	inputValueTransformer?: InputValueTransformer;
+	inputValueTransformerAsync?: InputValueTransformerAsync;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:33]: Just make the inputValueTransformer return `string | Promise<string>` and then check if it's a string and await it if not.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
This isn't really the implementation I had in mind. We might have to live with this for now but it'd be nice to at least see how much work it'd be to do the contribution stuff more generically so the resource-deployment extension doesn't have even more hard dependencies on extensions than it needs to.

File: extensions/arc/src/extension.ts (hunk 2 above)
Comment (ranasaria) [reply extensions/arc/src/extension.ts:61]: Filed #12283 to track this future work.

**Review by ranasaria — COMMENTED** [review]
Completed self-review and addressed pending pr comments.

File: extensions/resource-deployment/src/helpers/cacheManager.ts [hunk 16]
```diff
@@ -0,0 +1,83 @@
...
+	id: number,
+	pendingOperation: Deferred<void>
+}
+
+/**
+ * An implementation of Cache Manager which ensures that only one call to populate cache miss is pending at a given time.
+ * All remaining calls for retrieval are awaited until the one in progress finishes and then all awaited calls are resolved with the value
+ * from the cache.
+ */
+export class CacheManager<K, T> {
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/helpers/cacheManager.ts:27]: So why is this whole cache thing necessary? The way I see it we should just be fetching the valid options once upon opening the dialog and then using those to populate the dropdown. I don't really see the value in caching those options then - it just adds complexity for very little gain.

File: extensions/resource-deployment/src/services/apiService.ts [hunk 17]
```diff
@@ -5,26 +5,39 @@
...
 			if (!this.azurecoreApi) {
 				throw new Error('Unable to retrieve azurecore API');
 			}
 		}
 		return this.azurecoreApi;
 	}
+
+	public async getArcApi(): Promise<arc.IExtension> {
+		if (!this.arcApi) {
+			this.arcApi = <arc.IExtension>(await vscode.extensions.getExtension(arc.extension.name)?.exports);
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/services/apiService.ts:34]: The await is unnecessary here now.

And really I'd suggest just getting rid of this whole function. Calling getExtension is only a small hit and will then guarantee nothing weird happens with a stale api object.

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts (hunk 10 above)
Comment (Charles-Gagnon) [reply extensions/arc/src/ui/dialogs/connectControllerDialog.ts:200]: Yeah I'd prefer to keep it simple - and "take corrective actions" is way too formal anyways. So just removing it seems easiest.

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 18]
```diff
@@ -5,37 +5,73 @@
...
+			});
+		}
+		return components;
 	}
 
 	public showDialog(controllerInfo?: ControllerInfo, password?: string): azdata.window.Dialog {
+		return this._showDialog(controllerInfo, password);
+	}
+
+	protected _showDialog(controllerInfo: ControllerInfo | undefined, password: string | undefined, isPwReacquisition: boolean = false): azdata.window.Dialog {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:71]: _ should only be used for private members. The pattern vs code uses is something like `doShowDialog` for protected functions which seems generic enough

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 19]
```diff
@@ -5,37 +5,73 @@
...
 
-	private _id!: string;
 
-	constructor(private _treeDataProvider: AzureArcTreeDataProvider) {
+	constructor(protected _treeDataProvider: AzureArcTreeDataProvider, title: string = loc.connectToController) {
 		super();
+		this.dialog = azdata.window.createModelViewDialog(title);
+	}
+
+	private getComponents(isPwReacquisition: boolean): (azdata.FormComponent<azdata.Component> & { layout?: azdata.FormItemLayout | undefined; })[] {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:38]: For what it's worth I don't like how this is just increasing the complexity of the base class and adding a bunch of extra code for very little benefit. I personally would have just created a new dialog class that was very similar looking to this one - they share the basic stuff in common but there's enough custom logic and overrides here that it's just more confusing and harder to follow both sides now.

I guess it's ok to leave like this but please try to take stuff like that into account in the future.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
I'd like to get rid of the cache manager stuff if we can

File: extensions/resource-deployment/src/helpers/cacheManager.ts (hunk 16 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/helpers/cacheManager.ts:27]: it prevents multiple popups from being presented to the user for providing controller password when multiple calls to get the password value are received. The way the notebook wizard works when the summary page gets generated, we do get multiple calls for this password request. This cache manager serializes them and returns the same value that is fetched from the user once. Without it, a lot of code will need to be redone.

File: extensions/resource-deployment/src/services/apiService.ts (hunk 17 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/services/apiService.ts:34]: keeping the functions as a shortcut to the longish getExtension ... exports invocation but simplifying it a lot.

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts (hunk 19 above)
Comment (ranasaria) [reply extensions/arc/src/ui/dialogs/connectControllerDialog.ts:38]: Agreed. I do not like how this turned out code-wise. I will clean it up in a future PR. #12294

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts (hunk 18 above)
Comment (ranasaria) [reply extensions/arc/src/ui/dialogs/connectControllerDialog.ts:71]: removed the method altogether

File: extensions/resource-deployment/src/helpers/cacheManager.ts (hunk 16 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/helpers/cacheManager.ts:27]: > So why is this whole cache thing necessary? The way I see it we should just be fetching the valid options once upon opening the dialog and then using those to populate the dropdown. I don't really see the value in caching those options then - it just adds complexity for very little gain.

This would mean that if there are 5 controllers connected to by the user with none of them having a password saved, we would prompt the user for a password for each before opening the MIAA dialog. This is the behavior I am trying to avoid.

**Comment by ranasaria** [comment]
> I'd like to get rid of the cache manager stuff if we can

I did not want to add this in the first place :(

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 20]
```diff
@@ -5,101 +5,142 @@
...
+				value: password
+			}).component();
+	}
 
-	private _id!: string;
+	protected _completionPromise = new Deferred<ConnectToControllerDialogModel | undefined>();
+	protected _id!: string;
 
-	constructor(private _treeDataProvider: AzureArcTreeDataProvider) {
+	constructor(protected _treeDataProvider: AzureArcTreeDataProvider, title: string) {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:78]: Remove _ from protected vars (here and the couple above)

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 21]
```diff
@@ -5,101 +5,142 @@
...
+	protected initializeFields(controllerInfo: ControllerInfo | undefined, password: string | undefined) {
+		super.initializeFields(controllerInfo, password);
+		this.rememberPwCheckBox = this.modelBuilder.checkBox()
+			.withProperties<azdata.CheckBoxProperties>({
+				label: loc.rememberPassword,
+				checked: controllerInfo?.rememberPassword
+			}).component();
+	}
+
+	constructor(protected _treeDataProvider: AzureArcTreeDataProvider) {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:142]: Protected vars shouldn't have _

Comment (Charles-Gagnon) [reply extensions/arc/src/ui/dialogs/connectControllerDialog.ts:142]: And anyways - you already have the treeDataProvider defined in the base class so you can just remove the protected modifier here and pass it to the super constructor. (still remove the _)

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 22]
```diff
@@ -134,18 +175,67 @@ export class ConnectToControllerDialog extends InitializingComponent {
...
 
-	private handleCancel(): void {
-		this._completionPromise.resolve(undefined);
+	constructor(protected _treeDataProvider: AzureArcTreeDataProvider) {
+		super(_treeDataProvider, loc.passwordToController);
 	}
 
-	public waitForClose(): Promise<ConnectToControllerDialogModel | undefined> {
-		return this._completionPromise.promise;
+	protected fieldToFocusOn = () => this.passwordInputBox;
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:194]: Please don't use anonymous functions at the class level - they're generally just harder to read (especially when mixed in with normally defined function syntax)

File: extensions/resource-deployment/src/helpers/cacheManager.ts (hunk 16 above)
Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/helpers/cacheManager.ts:27]: Why would we need to fetch the password multiple times? The way I was thinking it'd work is that when the user selects the controller we get the password value then and validate it - if it's empty/wrong then we ask them to re-enter it at that point (and don't let them continue until they do and it passes validation).

Doing this shouldn't require any sort of cache/synchronizer since we only run that logic once when the data controller is picked.

File: extensions/resource-deployment/src/services/arcService.ts [hunk 23]
```diff
@@ -1,17 +0,0 @@
-/*---------------------------------------------------------------------------------------------
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/services/arcService.ts:1]: Just delete this file

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
So I still don't understand why this cache manager thing is necessary. I want to look over it myself and so what I think we can do here is have you fix the other small issues I brought up and then merge it in - then I'll go over it and see if there's anything I can do to make this better.

File: extensions/resource-deployment/src/services/arcService.ts (hunk 23 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/services/arcService.ts:1]: hmmm. In my enlistment, I do not see this file.

File: extensions/resource-deployment/src/helpers/cacheManager.ts (hunk 16 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/helpers/cacheManager.ts:27]: OK writing a handler for the dropdown picker to do the evaluation of subfields of the controller and saving those.

Comment (ranasaria) [reply extensions/resource-deployment/src/helpers/cacheManager.ts:27]: Charles and I had an offline conversation, picking the sub-values on dropdown picker value change (values of password, username, the endpoint for the picked-up controller in our use case) can have its own user experience issues. The plan is to go with the current implementation and revisit this later.

File: extensions/arc/src/ui/dialogs/connectControllerDialog.ts [hunk 24]
```diff
@@ -5,101 +5,144 @@
...
-	private usernameInputBox!: azdata.InputBoxComponent;
-	private passwordInputBox!: azdata.InputBoxComponent;
-	private rememberPwCheckBox!: azdata.CheckBoxComponent;
+	protected urlInputBox!: azdata.InputBoxComponent;
+	protected nameInputBox!: azdata.InputBoxComponent;
+	protected usernameInputBox!: azdata.InputBoxComponent;
+	protected passwordInputBox!: azdata.InputBoxComponent;
 
-	private _completionPromise = new Deferred<ConnectToControllerDialogModel | undefined>();
+	protected getComponents(): (azdata.FormComponent<azdata.Component> & { layout?: azdata.FormItemLayout | undefined; })[] {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dialogs/connectControllerDialog.ts:28]: I've left this comment in a few other places - but generally if a function is named "getX" that doesn't take any parameters then my immediate thought it "why isn't it just a property getter". Especially when it is just directly returning a value and not really doing any logic.

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/azdata/src/azdata.ts (hunk 8 above)
Comment (aaomidi) [inline extensions/azdata/src/azdata.ts:139]: I'm confused about this, what does the original JSON value look like? If its 
```
{ stderr: '...' }
```

then thats valid JSON?

Comment (Charles-Gagnon) [reply extensions/azdata/src/azdata.ts:139]: Nope, it's like :

```
ERROR: { stderr: '...' }
```

(apparently there's some other stuff that comes at the end too which is what Arvind was fixing)

Comment (Charles-Gagnon) [reply extensions/azdata/src/azdata.ts:139]: This is just a string that has a JSON blob embedded in it.
