### PR TITLE
Fix null ref error in query history

### LINKED ISSUE #8284: When running Edit Data on a database
Steps to reproduce:

1. Run edit data on a table in the database.

2. You get an error in the console saying that it "Cannot read property 'startLine' of undefined"

The issue appears to be caused in queryHistoryServiceImpl.ts where there is no null check for e.queryInfo.selection[0]; when registering the onQueryEvent function before actions are done on it. It is suggested to add one before executing line 52-72.

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #8284

If a query is ran without a specific selection the selection array is empty - in that case just get the entire text.

Opened #8303 as a related issue (we probably shouldn't be collecting queries from internal implementations of features)

### CODE REVIEW

File: src/sql/platform/queryHistory/common/queryHistoryServiceImpl.ts [hunk 1]
```diff
@@ -52,11 +52,14 @@ export class QueryHistoryService extends Disposable implements IQueryHistoryServ
 				const uri: URI = URI.parse(e.uri);
 				// VS Range is 1 based so offset values by 1. The endLine we get back from SqlToolsService is incremented
 				// by 1 from the original input range sent in as well so take that into account and don't modify
-				const text: string = _modelService.getModel(uri).getValueInRange(new Range(
-					e.queryInfo.selection[0].startLine + 1,
-					e.queryInfo.selection[0].startColumn + 1,
-					e.queryInfo.selection[0].endLine,
-					e.queryInfo.selection[0].endColumn + 1));
+				const text: string = e.queryInfo.selection.length > 0 ?
```
Comment (udeeshagautam) [inline src/sql/platform/queryHistory/common/queryHistoryServiceImpl.ts]: just to double confirm e.queryInfo.selection can not be undefined or should be check that as well?

Comment (smartguest) [reply src/sql/platform/queryHistory/common/queryHistoryServiceImpl.ts]: It should be checked just to be safe, unless its shown that it is always available physically.

Comment (Charles-Gagnon) [reply src/sql/platform/queryHistory/common/queryHistoryServiceImpl.ts]: Correct, the selection is non-optional (which is enforced by the strict null checking Anthony has been adding).

Comment (Charles-Gagnon) [reply src/sql/platform/queryHistory/common/queryHistoryServiceImpl.ts]: Double checked this and the strict null checking isn't enabled for the queryModelService yet (which is where the events come from) so I'll add the check just to be safe.
