### PR TITLE
Fix http request format

### LINKED ISSUE #22606: ADS - recent changes to RestClient are failing Post and Put calls w/ "Content-Length" undefined
- Azure Data Studio Version:  (build and debug latest code from main as of 4/3/2023)
- OS Version: Windows 11

Steps to Reproduce:
1. Launch ads
2. run SQL-Migration extension migration wizard
3. select any database, and SQL DB target to ensure ValidateIR is a required step in database configuration
4. run ValidateIR and notice the following console error:
image

Does this issue occur when all extensions are disabled?: n/a

### LINKED ISSUE #22631: Some azure REST calls not returning correct information
When updating from axios to the https module some of the response fields weren't properly updated, which means that they won't return the correct values.

example showing the returned fields not matching:

image

This should only apply to the calls that were switched from axios to the https module and weren't updated in the original PR, which there's two I see:

createResourceGroup
getStorageAccountAccessKey

These are both used by the sql-migration extension, as well as other features in ADS (such as backup).

### PR DESCRIPTION
**Pull request by cssuh**
Update the PUT requests, with help from @brian-harris 

Fixes #22606
Fixes #22631

### CODE REVIEW

File: extensions/azurecore/src/account-provider/auths/httpClient.ts [hunk 1]
```diff
@@ -151,7 +152,7 @@ const networkRequestViaProxy = <T>(
 	// compose a request string for the socket
 	let postRequestStringContent: string = '';
 	if (httpMethod === HttpMethod.POST || httpMethod === HttpMethod.PUT) {
-		const body = options?.body || '';
+		const body = JSON.stringify(options?.body || '');
```
Comment (brian-harris) [inline extensions/azurecore/src/account-provider/auths/httpClient.ts:155]: be sure to encode this line as well

File: extensions/azurecore/src/account-provider/auths/httpClient.ts [hunk 2]
```diff
@@ -284,7 +285,7 @@ const networkRequestViaHttps = <T>(
 ): Promise<NetworkResponse<T>> => {
 	const isPostRequest = httpMethod === HttpMethod.POST;
 	const isPutRequest = httpMethod === HttpMethod.PUT;
-	const body: string = options?.body || '';
+	const body = (new TextEncoder()).encode(JSON.stringify(options?.body || ''));
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/httpClient.ts:288]: Why do we have to encode the body content? It looks like it accepts a utf8 string by default so is there something else that makes it so we need to encode it first?

https://nodejs.org/api/http.html#requestwritechunk-encoding-callback

Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/httpClient.ts:288]: So body was an object here instead of a string? Does the msal-common library have the wrong typings or something? It would be good to figure that out and update it if so to avoid other similar problems.

File: extensions/azurecore/src/account-provider/auths/httpClient.ts [hunk 3]
```diff
@@ -151,7 +152,7 @@ const networkRequestViaProxy = <T>(
 	// compose a request string for the socket
 	let postRequestStringContent: string = '';
 	if (httpMethod === HttpMethod.POST || httpMethod === HttpMethod.PUT) {
-		const body = options?.body || '';
+		const body = (new TextEncoder()).encode(JSON.stringify(options?.body || ''));
 		postRequestStringContent =
 			'Content-Type: application/x-www-form-urlencoded\r\n' +
```
Comment (cheenamalhotra) [inline extensions/azurecore/src/account-provider/auths/httpClient.ts:157]: I see this is `x-www-form-urlencoded`, whereas for PUT/POST request you're passing headers as 'application/json': https://github.com/microsoft/azuredatastudio/blob/058856008b0bee1dea5227f9d2d1cda7b85bf6e3/extensions/azurecore/src/azureResource/utils.ts#L394

Shouldn't they be same?

File: extensions/azurecore/src/account-provider/auths/httpClient.ts (hunk 2 above)
Comment (cssuh) [reply extensions/azurecore/src/account-provider/auths/httpClient.ts:288]: without encoding the body content, this table name caused an error to be thrown:

MicrosoftTeams-image

 and encoding fixed that error

Comment (cssuh) [reply extensions/azurecore/src/account-provider/auths/httpClient.ts:288]: ok, I will open an issue on the msal-common library and discuss with the team there.

File: extensions/azurecore/src/account-provider/auths/httpClient.ts (hunk 3 above)
Comment (cssuh) [reply extensions/azurecore/src/account-provider/auths/httpClient.ts:157]: will investigate this

File: extensions/azurecore/src/account-provider/auths/httpClient.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/httpClient.ts:288]: Looked into this and part of the problem is that we define the request body as any here : 

https://github.com/microsoft/azuredatastudio/blob/efd489ecde310661669a2e204486426e4017bf78/extensions/azurecore/src/azureResource/utils.ts#L351-L352

So let's hold off on filing an issue with them since they properly type the body as a string - it's just that using `any` disables the type checking from marking that as an error. I'm looking into an eslint rule to help prevent this in the future.

**Comment by raymondtruong** [comment]
FYI, I'm seeing an issue with calling `getBlobs` in azurecore - even though that's a get it seems it uses a post behind the scenes to get the storage account keys, but even with your change here I'm still seeing errors:

image

cc @cssuh @Charles-Gagnon @cheenamalhotra @brian-harris

**Comment by Charles-Gagnon** [comment]
@raymondtruong Could you copy the entire contents of the message? Seems to be a different error.

**Comment by raymondtruong** [comment]
> @raymondtruong Could you copy the entire contents of the message? Seems to be a different error.

sure thing, here's the error that gets populated after calling `getBlobs`:

```
RestError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:ae992142-101e-0070-2eea-679c5e000000
Time:2023-04-05T18:14:08.8937409Z
    at handleErrorResponse (c:\\Users\\ratruong\\source\\repos\\azuredatastudio2\\extensions\\azurecore\
ode_modules\\@azure\\core-http\\dist\\index.js:3174:19)
    at c:\\Users\\ratruong\\source\\repos\\azuredatastudio2\\extensions\\azurecore\
ode_modules\\@azure\\core-http\\dist\\index.js:3110:49
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StorageRetryPolicy.attemptSendRequest (c:\\Users\\ratruong\\source\\repos\\azuredatastudio2\\extensions\\azurecore\
ode_modules\\@azure\\storage-blob\\dist\\index.js:14673:24)
    at async StorageClientContext.sendOperationRequest (c:\\Users\\ratruong\\source\\repos\\azuredatastudio2\\extensions\\azurecore\
ode_modules\\@azure\\core-http\\dist\\index.js:4893:31)
    at async ContainerClient.listBlobFlatSegment (c:\\Users\\ratruong\\source\\repos\\azuredatastudio2\\extensions\\azurecore\
ode_modules\\@azure\\storage-blob\\dist\\index.js:23381:30)"
```

**Comment by cheenamalhotra** [comment]
@raymondtruong can you also paste the request here that you're able to see in debug session?

**Comment by raymondtruong** [comment]
> @raymondtruong can you also paste the request here that you're able to see in debug session?

@cheenamalhotra yep, I'll ping you guys offline if that's okay - full request and response is pretty large and I don't know what might be included so I'd rather not paste it here

**Comment by cssuh** [comment]
the latest commit should fix the issues @raymondtruong was seeing.

**Review by raymondtruong — APPROVED** [review]
thanks @cssuh, I merged your branch into mine and verified getBlobs is working as intended now

File: extensions/azurecore/src/account-provider/auths/httpClient.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/httpClient.ts:288]: It's odd because I would think UTF-8 would be able to handle characters like that, so might be worth looking more into. 

But for now could you at least put a comment on all the places you use TextEncoder about why you're doing that so future people looking at this have context on why this is needed?

**Review by Charles-Gagnon — APPROVED** [review]

**Review by brian-harris — APPROVED** [review]

File: extensions/azurecore/src/account-provider/auths/httpClient.ts (hunk 3 above)
Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/httpClient.ts:158]: This Content-Type definitely doesn't seem correct, that content type is supposed to be used specifically for form data and the body is supposed to be in the form `key=value&key2=value2...` (like the query string)

https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1

Did you copy this from somewhere or was there a specific reason you chose it? If you don't have a reason for using it I definitely think you should update it (after checking it still works of course) to avoid any potential issues coming up later on.
