### PR TITLE
Move files locations

### LINKED ISSUE #9011: Azure signed-in landing page shows a blank page
- Azure Data Studio Version: 1.15.0

Steps to Reproduce:

1. Sign in to Azure account

Expected: Azure Data Studio branded landing page

Actual:

image

### PR DESCRIPTION
**Pull request by aaomidi**
This PR fixes #9011

### CODE REVIEW

File: extensions/azurecore/src/account-provider/azureAccountProvider2.ts [hunk 1]
```diff
@@ -189,6 +189,8 @@ export class AzureAccountProvider implements azdata.AccountProvider {
 		nonce: string,
 		authUrl: string) {
 
+		const mediaPath = path.join(__dirname, '..', '..', 'media');
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/azureAccountProvider2.ts]: Any reason you're not using vscode.ExtensionContext.extensionPath instead? Would be a safer way of knowing you're at the root level. 

Because right now isn't this still going to break for webpacked builds? __dirname for that will be `resources\app\extensions\azurecore\dist` so it'll resolve to `resources\app\extensions\media\` which isn't right.

Comment (aaomidi) [reply extensions/azurecore/src/account-provider/azureAccountProvider2.ts]: Because I didn't know that was a method :D
