### PR TITLE
Fix debounce issue when book toc is updated

### LINKED ISSUE #9249: Changes (after git sync/pull) should take effect immediately from git to Notebook and Jupyter Book viewlet
- Azure Data Studio Version:
Version: 1.15.1 (user setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. In Azure Data Studio, do a git pull from recently changed Jupyter book, to refresh your local copy with the master / remote branch.  
2. Go to Jupyter Book viewlet.

Issues: 
a. Jupyter Book viewlet is not updated immediately
b. Jupyter Book doesn't show which files have been touched / new. (OneNote can show files that are touched / updated nicely).

### PR DESCRIPTION
**Pull request by barbaravaldez**
Move the reInitializeContents logic to bookModel due to debounce method not taking into account the parameters. Every time we pulled changes and there were multiple books it only registered the changes from the last call.

Also I moved the unwatch/watch toc methods to the bookModel since it makes more sense for them to be called from the book's object.

This PR fixes the third scenario of #9249

### CODE REVIEW

File: extensions/notebook/src/book/bookModel.ts [hunk 1]
```diff
@@ -32,10 +32,29 @@ export class BookModel {
 		public readonly openAsUntitled: boolean,
 		public readonly isNotebook: boolean,
 		private _extensionContext: vscode.ExtensionContext,
+		private _bookTreeViewEvent: vscode.EventEmitter<BookTreeItem | undefined>,
```
Comment (corivera) [inline extensions/notebook/src/book/bookModel.ts:35]: Could this variable name be made more specific? This name makes it a bit vague as to what this event is actually for. If it's always going to be _onDidChangeTreeData, then would renaming it to that work?

File: extensions/notebook/src/book/bookModel.ts [hunk 2]
```diff
@@ -32,10 +32,29 @@ export class BookModel {
...
+	public watchTOC(): void {
+		fs.watchFile(this.tableOfContentsPath, async (curr, prev) => {
+			if (curr.mtime > prev.mtime) {
+				await this.reInitializeContents();
+			}
+		});
+	}
+
+	@debounce(1500)
+	public async reInitializeContents(): Promise<void> {
```
Comment (corivera) [inline extensions/notebook/src/book/bookModel.ts:53]: nit: reinitialize is a single word, so initialize shouldn't be capitalized here

**Review by corivera — APPROVED** [review]

File: extensions/notebook/src/book/bookModel.ts [hunk 3]
```diff
@@ -32,10 +32,29 @@ export class BookModel {
...
+		await this.initializeContents();
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookModel.ts:54]: Do you also want to handle concurrent executions? If this is called multiple times outside of the debounce window then it'll call initialize contents multiple times which could have weird side effects depending on which one finished first.

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@barbaravaldez It appears you have a test failure now

File: extensions/notebook/src/book/bookModel.ts (hunk 3 above)
Comment (corivera) [reply extensions/notebook/src/book/bookModel.ts:54]: Don't previous pending calls get cancelled when using a debounce?

Comment (Charles-Gagnon) [reply extensions/notebook/src/book/bookModel.ts:54]: I'm saying ones outside the debounce window.

- Call comes in - debounce timer starts.
- Wait 1.5 seconds
- initializeContents() is called (timer expired) and begins to run
- reInitializeContents is called again - timer starts again
- Wait 1.5 seconds
- initializeContents() is called again

We now have initializeContents running twice separately. If the call takes >1.5seconds to complete this is a scenario that I could easily see happening.

Comment (barbaravaldez) [reply extensions/notebook/src/book/bookModel.ts:54]: mm I didn't consider that, do you think it'll be better to add the debounce decorator directly to the initalizeContents method, instead?

Comment (Charles-Gagnon) [reply extensions/notebook/src/book/bookModel.ts:54]: That doesn't really solve the problem. And in general this isn't something that can be solved with debouncing.

You'd need to add some sort of gating to ensure that only one refresh is running at a time and/or additional calls are queued up for execution instead of executing right away. We can chat offline if you aren't sure where to start for that.
