### PR TITLE
Fix connectionSettingName for create azure function with sql binding

### LINKED ISSUE #18930: "Create Azure Function with SQL binding" doesn't prompt user about connection string setting
1. Open existing function project
2. Right click on a table and create a new binding

The user is walked through adding the binding but is never prompted to select the connection string setting to use or whether to save the password in the settings file.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR addresses #18930.

This ensures that we prompt the user for the connection string setting name for when the user uses `Create Azure Function with SQL Binding`. 

Flow:
1. Prompts for the binding type
image

2. If the user does not have azure function project in folder (else if the azure function project in the folder then skip to **step 4**):
Screen Shot 2022-04-11 at 5 23 58 PM
User chooses `Create Azure Function Project`

3. Prompted for Template (if creating a new azure function project):
image
able to create a project with any template or skip it for now and then continues flow

4. Prompt for Azure Function Name
image

5. Prompt user to select existing connection string setting or creates new
image

6. If user clicks create new setting name:
image

7. user asked to include password for connection string
image

if yes to above - we finish creating project and adding connection string to local.settings.json (got to step 9)
8. if no - user shown to enter password:
image
- if user enters valid password then we add it to the connection string 
- if escape we show warning:
   image

9. Prompt for namespace
image

Finish Creating Azure Function with SQL binding

### CODE REVIEW

**Comment by VasuBhog** [comment]
Add SQL Binding Flow:

1. Prompt to select azure function to add SQL Binding to:
image

2. Prompt for Binding type:
image

3. Prompt for table or view to query
image

4. Prompt user to select existing connection string setting or creates new
image

5. If user clicks create new setting name:
image

6. Prompt user for connection string method
image

- if `select a connection profile` (then step 7):
image

- if `enter connection string` (then step 9):
image

7. user asked to include password for connection string
image

- if yes to the above (go to step 9)
8. - if no - user is shown to enter a password:
image
- if the user enters a valid password then we add it to the connection string 
- if escape we show a warning:
   image

9. Add a connection string to local.settings.json and then finish adding SQL binding to selected azure function.

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 1]
```diff
@@ -545,3 +504,70 @@ export async function promptAndUpdateConnectionStringSetting(projectUri: vscode.
 	}
 	return connectionStringSettingName;
 }
+
+/**
+ * Prompts the user to include password in the connection string and updates the connection string based on user input
+ * @param connectionInfo
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:510]: Fill these out

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 2]
```diff
@@ -545,3 +504,70 @@ export async function promptAndUpdateConnectionStringSetting(projectUri: vscode.
...
+			});
+		}
+
+		return connectionString;
+
+	} catch (e) {
+		// failed to get connection string for selected connection and will go back to prompt for connection string methods
+		console.warn(e);
+		void vscode.window.showErrorMessage(constants.failedToGetConnectionString);
+		return;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:571]: `return undefined`

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/sql-bindings/package.json [hunk 3]
```diff
@@ -51,7 +51,7 @@
         },
         {
           "command": "sqlBindings.createAzureFunction",
-          "when": "view == objectExplorer && viewItem == Table && !azdataAvailable",
+          "when": "!azdataAvailable",
```
Comment (VasuBhog) [inline extensions/sql-bindings/package.json:54]: This will show in the command palette as an option for the user to use only in vscode currently.

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+import { assert } from 'console';
+
+let rootFolderPath: string;
+let localSettingsPath: string;
+let projectFilePath: string;
+
+describe('Tests to verify Azure Functions Utils functions', function (): void {
+	beforeEach(async () => {
+		rootFolderPath = path.join(os.tmpdir(), `AzureFunctionTest_${uuid.v4()}`);
+		await fs.mkdirSync(rootFolderPath);
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:25]: Unit tests should generally not be making actual files. Use sinon to stub these out instead and return fake results.

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+import * as os from 'os';
+import * as uuid from 'uuid';
+import * as fs from 'fs';
+import * as rimraf from 'rimraf';
+import * as should from 'should';
+import * as sinon from 'sinon';
+import { promisify } from 'util';
+import * as constants from '../../common/constants';
+import * as azureFunctionsUtils from '../../common/azureFunctionsUtils';
+import { assert } from 'console';
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:16]: Don't use this assert. Use should instead.

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 6]
```diff
@@ -75,8 +74,7 @@ export async function setLocalAppSetting(projectFolder: string, key: string, val
 	}
 
 	settings.Values[key] = value;
-	void fs.promises.writeFile(localSettingsPath, JSON.stringify(settings, undefined, 2));
-
+	fs.writeFileSync(localSettingsPath, JSON.stringify(settings, undefined, 2));
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:77]: You should avoid sync functions since they block execution, use async ones and await instead.

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+let projectFilePath: string = 'test/projectFilePath.csproj';
+
+describe('Tests to verify Azure Functions Utils functions', function (): void {
+
+	it('Should get local.settings.json', async () => {
+		sinon.stub(fs, 'existsSync').withArgs(localSettingsPath).returns(true);
+		sinon.stub(fs, 'readFileSync').withArgs(localSettingsPath).returns(
+			`{"IsEncrypted": false,
+			"Values": {"test1": "test1", "test2": "test2", "test3":"test3"}}`
+		).toString();
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:24]: What's the toString for?

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+		const getLocalSettingsSpy = sinon.spy(azureFunctionsUtils, 'getLocalSettingsJson');
+		sinon.stub(JSON, 'parse').withArgs(sinon.match.any).throws(new Error(errorMsg));
+		try {
+			await getLocalSettingsSpy(localSettingsPath);
+		} catch {
+			should(getLocalSettingsSpy.threw());
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:42]: You should do this outside the catch - otherwise if it doesn't throw this test will still pass

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 9]
```diff
@@ -0,0 +1,103 @@
...
+		let errorMsg = 'Error parsing local.settings.json';
+		sinon.stub(fs, 'existsSync').withArgs(localSettingsPath).returns(true);
+		sinon.stub(fs, 'readFileSync').withArgs(localSettingsPath).returns(
+			`{"IsEncrypted": false,
+			"Values": {"test1": "test1", "test2": "test2", "test3":"test3"}}`
+		).toString();
+		const getLocalSettingsSpy = sinon.spy(azureFunctionsUtils, 'getLocalSettingsJson');
+		sinon.stub(JSON, 'parse').withArgs(sinon.match.any).throws(new Error(errorMsg));
+		try {
+			await getLocalSettingsSpy(localSettingsPath);
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:40]: If all you're doing is checking that `getLocalSettingsJson` threw then you can just use `should(() => function()).throwError()`

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 10]
```diff
@@ -0,0 +1,103 @@
...
+		sinon.stub(fs, 'readFileSync').withArgs(localSettingsPath).returns(
+			`{"IsEncrypted": false,
+			"Values": {"test1": "test1", "test2": "test2", "test3":"test3"}}`
+		).toString();
+		let settings = await azureFunctionsUtils.getLocalSettingsJson(localSettingsPath);
+		should(settings.IsEncrypted).equals(false);
+		should(Object.keys(settings.Values!).length).equals(3);
+	});
+
+	it('Should show error message if local.settings.json throws', async () => {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:30]: What does it mean for local.settings.json to "throw"? And I don't see anything about checking an it showed an error message.

Make sure the names are describing what is actually happening - in this case `getLocalSettingsJson should throw when an invalid settings.json is read` seems much clearer

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 11]
```diff
@@ -0,0 +1,103 @@
...
+		sinon.stub(fs, 'existsSync').withArgs(localSettingsPath).returns(true);
+		sinon.stub(fs, 'readFileSync').withArgs(localSettingsPath).returns(
+			`{"IsEncrypted": false,
+			"Values": {"test1": "test1", "test2": "test2", "test3":"test3"}}`
+		).toString();
+
+		let warningMsg = constants.settingAlreadyExists('test1');
+		let settings = await azureFunctionsUtils.getLocalSettingsJson(localSettingsPath);
+		// originally should have 3 settings
+		should(Object.keys(settings.Values!).length).equals(3);
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:71]: Same here, this isn't necessary to test in these tests

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 12]
```diff
@@ -0,0 +1,103 @@
...
+
+		const spy = sinon.stub(vscode.window, 'showWarningMessage').resolves(await Promise.resolve({ title: constants.settingAlreadyExists('test1') }));
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:73]: The `await Promise.resolve` should be unnecessary, you're already using the resolves function...

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts (hunk 8 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:42]: I had this outside in my first commit with tests and found that it said Assertion Failed after throwing the error. Now it does not when it is in the catch.

Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:42]: Well that doesn't sound right. The assertion (threw()) shouldn't be failing. I don't think you need this spy as noted above so may not matter, but if you end up still using it you should look into why it's saying the assertion is failing.

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 13]
```diff
@@ -0,0 +1,103 @@
...
+			`{"IsEncrypted": false,
+			"Values": {"test1": "test1", "test2": "test2", "test3":"test3"}}`
+		).toString();
+		const connectionString = 'testConnectionString';
+		let settings = await azureFunctionsUtils.getLocalSettingsJson(localSettingsPath);
+		should(Object.keys(settings.Values!).length).equals(3);
+
+		let writeFileStub = sinon.stub(fs.promises, 'writeFile');
+		await azureFunctionsUtils.addConnectionStringToConfig(connectionString, projectFilePath);
+		should(writeFileStub.calledWithExactly(localSettingsPath, '{\n  "IsEncrypted": false,\n  "Values": {\n    "test1": "test1",\n    "test2": "test2",\n    "test3": "test3",\n    "SqlConnectionString": "testConnectionString"\n  }\n}')).equals(true);
```
[the remark this answers is not in the document]
Comment (VasuBhog) [reply extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:73]: Used EOL from os to handle platform dependent newline

[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:73]: I see you did that above, but not here. Is there a reason for that?

File: extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts [hunk 14]
```diff
@@ -0,0 +1,79 @@
...
+		sinon.stub(fs, 'readFileSync').withArgs(localSettingsPath).returns(
+			`{"IsEncrypted": false,
+			"Values": {"test1": "test1", "test2": "test2", "test3":"test3"}}`
+		);
+
+		let warningMsg = constants.settingAlreadyExists('test1');
+		const spy = sinon.stub(vscode.window, 'showWarningMessage').resolves({ title: constants.settingAlreadyExists('test1') });
+
+		await azureFunctionsUtils.setLocalAppSetting(path.dirname(localSettingsPath), 'test1', 'newValue');
+		should(spy.calledOnce).be.true('showErrorMessage should have been called exactly once');
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/test/common/azureFunctionsUtils.test.ts:54]: showWarningMessage

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 15]
```diff
@@ -426,104 +427,65 @@ export async function promptAndUpdateConnectionStringSetting(projectUri: vscode.
...
-							if (includePassword !== constants.yesString && !userPassword && connectionInfo?.authenticationType === 'SqlLogin') {
-								// if user does not want to include password or user does not enter password, show warning message that they will have to enter it manually later in local.settings.json
-								void vscode.window.showWarningMessage(constants.userPasswordLater, constants.openFile, constants.closeButton).then(async (result) => {
-									if (result === constants.openFile) {
-										// open local.settings.json file
-										void vscode.commands.executeCommand(constants.vscodeOpenCommand, vscode.Uri.file(localSettingsPath));
-									}
-								});
+							// get the connection string including prompts for password if needed
+							connectionString = await promptConnectionStringPasswordAndUpdateConnectionString(connectionInfo, localSettingsPath) as string;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:469]: You shouldn't need to cast this as a string anymore

**Review by chlafreniere — APPROVED** [review]
