### PR TITLE
Fix connection when changing kernel from Kusto to SQL (#12881)

### LINKED ISSUE #12862: Kusto Notebook does not clear connection info when switching to SQL kernel
- Azure Data Studio Version:Version: 1.23.0-rc1
Commit: 7429407029af2e08d17a8928825815cffad94f17
Date: 2020-10-09T00:40:51.445Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Open a new Kusto Notebook from Kusto Cluster
2. Switch Kernel from Kusto to SQL - **Does not clear connection**

kusto-nb-issue

**Expected:** When the user switches to SQL from Kusto notebook, it clears the connection in the Attach To dropdown.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #12862
PR from Main: #12881
(Discussed in Shiproom Channel)

It fixes Kusto to SQL kernel change by removing the connection based on the appropriate kernel.

### CODE REVIEW

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -846,6 +846,15 @@ export class NotebookModel extends Disposable implements INotebookModel {
 			if (newConnection) {
 				if (newConnection.serverCapabilities?.notebookKernelAlias) {
 					this._currentKernelAlias = newConnection.serverCapabilities.notebookKernelAlias;
+					// Removes SQL kernel to Kernel Alias Connection Provider map
```
Comment (kburtram) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:849]: would be useful for the comment to explain why this is being done, rather than just mentioning what is being done.

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 2]
```diff
@@ -973,7 +982,13 @@ export class NotebookModel extends Disposable implements INotebookModel {
 	private async loadActiveContexts(kernelChangedArgs: nb.IKernelChangedArgs): Promise<void> {
 		if (kernelChangedArgs && kernelChangedArgs.newValue && kernelChangedArgs.newValue.name) {
 			let kernelDisplayName = this.getDisplayNameFromSpecName(kernelChangedArgs.newValue);
-			let context = NotebookContexts.getContextForKernel(this._activeConnection, this.getApplicableConnectionProviderIds(kernelDisplayName));
+			if (this.context?.serverCapabilities?.notebookKernelAlias && this.selectedKernelDisplayName === this.context?.serverCapabilities?.notebookKernelAlias) {
+				kernelDisplayName = this.context.serverCapabilities?.notebookKernelAlias;
+			}
+			let context;
```
Comment (kburtram) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:988]: we should try to provide types when declaring variables.  If it really needs to be `any` then it should be explicitly declared that way.

**Review by kburtram — COMMENTED** [review]
I don't know the code area that well.  But I'm fine with the port if the change is desired for 1.23.

**Review by kburtram — APPROVED** [review]
