### PR TITLE
show notebook as trusted when it belongs to a trusted book

### LINKED ISSUE #15081: Some notebooks will remain untrusted when trusting books
Not a regression from 1.27

Click shield icon besides a book name and a message saying "Jupyter Book is now trusted in the workspace" will be shown but some notebooks will remain untrusted.
- Azure Data Studio Version:
Version: 1.28.0-rc1 (user setup)
Commit: 1c91f7971e8d4563dca47ab113953b4ad8d59b64
Date: 2021-04-09T00:19:50.442Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #15081

### CODE REVIEW

File: src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts [hunk 1]
```diff
@@ -560,11 +562,18 @@ export class NotebookService extends Disposable implements INotebookService {
...
 		}
+		const trustedBooksConfigKey = 'notebook.trustedBooks';
 
 		let cacheInfo = this.trustedNotebooksMemento.trustedNotebooksCache[notebookUri.toString()];
 		if (!cacheInfo) {
-			// This notebook was never trusted
-			return false;
+			// Check if the notebook belongs to a book that's trusted.
+			let trustedBookDirectories: string[] = this._configurationService?.getValue(trustedBooksConfigKey) ?? [];
+			if (trustedBookDirectories.find(b => notebookUri.fsPath.indexOf(b) > -1)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:571]: Just because a Notebook is in a directory doesn't necessarily mean it's a part of that book, right? At least we need to make a decision about whether we assume that's always going to be the case - it doesn't seem unreasonable to make this assumption but we need to make sure we're all in agreement this is the direction we want to go.

File: src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts [hunk 2]
```diff
@@ -560,11 +562,18 @@ export class NotebookService extends Disposable implements INotebookService {
...
+				return true;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:572]: I'd suggest leaving a comment saying that you're specifically ignoring the logic that checks the dirty status and why that isn't applicable here

File: src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts [hunk 3]
```diff
@@ -560,11 +562,18 @@ export class NotebookService extends Disposable implements INotebookService {
...
 			return true;
 		}
+		const trustedBooksConfigKey = 'notebook.trustedBooks';
 
 		let cacheInfo = this.trustedNotebooksMemento.trustedNotebooksCache[notebookUri.toString()];
 		if (!cacheInfo) {
-			// This notebook was never trusted
-			return false;
+			// Check if the notebook belongs to a book that's trusted.
+			let trustedBookDirectories: string[] = this._configurationService?.getValue(trustedBooksConfigKey) ?? [];
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:570]: You should update the doc comment in the interface definition as well

File: src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts (hunk 1 above)
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:571]: How are we handling untrusting a notebook that's in a trusted book? Should we even allow that?

**Review by Charles-Gagnon — APPROVED** [review]
In general something to think about - it's not great that we're continuing to split up the logic like this. Book trust is handled by the extension but Notebook trust is handled by core? And then we have logic like this where it's explicitly setting the document to trusted when opening a notebook in some cases? https://github.com/microsoft/azuredatastudio/blob/main/extensions/notebook/src/book/bookTreeView.ts#L384

Fixing the issue is fine here but while you're looking at this it would be great to try and think of how to make this cleaner, simpler and more robust such that changes on one side don't end up breaking the other.

**Review by barbaravaldez — APPROVED** [review]

File: src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts [hunk 4]
```diff
@@ -560,11 +562,21 @@ export class NotebookService extends Disposable implements INotebookService {
...
 		}
+		const trustedBooksConfigKey = 'notebook.trustedBooks';
 
 		let cacheInfo = this.trustedNotebooksMemento.trustedNotebooksCache[notebookUri.toString()];
 		if (!cacheInfo) {
-			// This notebook was never trusted
-			return false;
+			// Check if the notebook belongs to a book that's trusted
+			// and is not part of untrusted queue.
+			let trustedBookDirectories: string[] = !this._unTrustedCacheQueue.find(n => n === notebookUri) ? this._configurationService?.getValue(trustedBooksConfigKey) ?? [] : [];
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:571]: Why do we even have an "untrusted cache queue" (and why is it a "queue"? It's just a list...not a queue). Shouldn't anything that's not trusted therefore be untrusted?

Comment (MaddyDev) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:571]: Not sure! @joberume can you explain?

File: src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts (hunk 1 above)
Comment (MaddyDev) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:572]: Probably when a book that's trusted is not trusted, it goes into the untrustedQueue list. @joberume is the expert here. Can you correct me if am wrong?

Comment (joberume) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:572]: From the book tree view, that's the presumption: https://github.com/microsoft/azuredatastudio/blob/9aa4a03ecf4328e53aef78c62a5d64feaae6e0a9/extensions/notebook/src/book/bookTrustManager.ts#L29

File: src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts (hunk 4 above)
Comment (joberume) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:571]: Introduction of untrusted queue is here: https://github.com/microsoft/azuredatastudio/commit/73b9849dd59714b08631defda762df556113de9c

From reading the code, it looks like it removes the notebook from the trustedCacheQueue.

Comment (chlafreniere) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:571]: If we removed the ability to untrust a notebook, I certainly wouldn't complain; nobody ever signed off on the initial PR.

Oh wait, did I say that out loud 😄?

Comment (MaddyDev) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:571]: @joberume oops my bad, I assumed the trust notebook code is entirely done by you. Should have checked the code! Thanks for chiming in anyway. :)
