### PR TITLE
Aligns how Import and New project flows work

### LINKED ISSUE #11107: Import New Database Project - Unable to save in root directory
- Azure Data Studio Version:
Version: 1.20.0-insider (user setup)
Commit: 710d0462d8d81373aa2bc0f36f88955c902cb173
Date: 2020-06-25T05:31:00.820Z
VS Code: 1.46.0
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Right click on SQL Server 2019 database and choose Import New Database Project.
2. Use default name.
3. Choose SchemaObjectType.
4. Save on an empty drive.
image

An error like this would appear
image

### PR DESCRIPTION
**Pull request by Benjin**
Fixes #11107
Includes slight refactor of Import flow to simplify logic

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -767,52 +743,36 @@ export class ProjectsController {
...
-				canSelectMany: false,
-				openLabel: constants.selectString,
-				defaultUri: this.apiWrapper.workspaceFolders() ? (this.apiWrapper.workspaceFolders() as WorkspaceFolder[])[0].uri : undefined
-			});
-			if (selectionResult) {
-				projUri = (selectionResult as Uri[])[0];
-			}
-		} else {
-			// Get filename
-			selectionResult = await this.apiWrapper.showSaveDialog(
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/projectController.ts:787]: just want to make sure - does import still work if the extract target is file? Previously, the file name was required if the extract target was file, but it looks like that was removed from getFolderLocation().

Comment (Benjin) [reply extensions/sql-database-projects/src/controllers/projectController.ts:796]: Info in other reply

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 2]
```diff
@@ -633,108 +633,88 @@ export class ProjectsController {
...
-					database = connection.options['database'];
-				} else {
-					const databaseList = await this.apiWrapper.listDatabases(connectionId);
-					database = (await this.apiWrapper.showQuickPick(databaseList.map(dbName => { return { label: dbName }; })))?.label;
+			const newProjFilePath = await this.createNewProject(model.projName, Uri.file(newProjFolderUri), true);
 
-					if (!database) {
-						throw new Error(constants.databaseSelectionRequired);
-					}
-				}
```
Comment (Benjin) [inline extensions/sql-database-projects/src/controllers/projectController.ts:665]: Looks like this was lost in the automerge.  Fixing...

File: extensions/sql-database-projects/src/test/projectController.test.ts [hunk 3]
```diff
@@ -390,18 +389,31 @@ describe('ProjectsController: import operations', function (): void {
 		await testUtils.shouldThrowSpecificError(async () => await projController.importNewDatabaseProject({ connectionProfile: mockConnectionProfile }), constants.projectLocationRequired);
 	});
 
-	it('Should show error when selected folder is not empty', async function (): Promise<void> {
```
Comment (Benjin) [inline extensions/sql-database-projects/src/test/projectController.test.ts:393]: Test case removed because checking that the folder is empty is no longer needed since we're making a brand new folder.

File: extensions/sql-database-projects/src/test/projectController.test.ts [hunk 4]
```diff
@@ -390,18 +389,31 @@ describe('ProjectsController: import operations', function (): void {
...
+		should(importPath).equal(vscode.Uri.file(path.join(folderPath, projectName, projectName + '.sql')).fsPath, 'model.filePath should be set to a specific file for ExtractTarget === file');
+
+		// reset for counter-test
+		importPath = undefined;
+		folderPath = await testUtils.generateTestFolderPath();
+		testContext.apiWrapper.setup(x => x.showQuickPick(TypeMoq.It.isAny(), TypeMoq.It.isAny(), TypeMoq.It.isAny())).returns(() => Promise.resolve({ label: constants.schemaObjectType }));
 
-		await testUtils.shouldThrowSpecificError(async () => await projController.importNewDatabaseProject({ connectionProfile: mockConnectionProfile }), constants.projectLocationNotEmpty);
+		await projController.object.importNewDatabaseProject({ connectionProfile: mockConnectionProfile });
+		should(importPath).equal(vscode.Uri.file(path.join(folderPath, projectName)).fsPath);//, 'model.filePath should be set to a folder for ExtractTarget !== file');
```
Comment (Benjin) [inline extensions/sql-database-projects/src/test/projectController.test.ts:416]: Uncomment test description
