### PR TITLE
Fix Data Explorer context menu items visibility

### LINKED ISSUE #4910: Wrong context menu actions for tree nodes
- Azure Data Studio Version: master

Steps to Reproduce:

1. Navigate to any server node on Azure or CMS.
2. Expand the server node and right click the Databases folder.
3. The context menu actions that show up are not supposed to.

Screenshot 
Untitled

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fix #4910 The when clause wasn't set up correctly - you need to use the classes like ContextKeyDefinedExpr to build up the expressions. Previously they would show up for all nodes in the tree, with this change it's scoped down to just being on the Server and Database nodes.

Note that I purposely left out Manage from DBs under Server nodes because of #4994 which means they'll always use the first connection you use to connect to the Dashboard and so you'll never be able to view the dashboards for other DBs.

### CODE REVIEW

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts [hunk 1]
```diff
@@ -15,27 +15,83 @@ MenuRegistry.appendMenuItem(MenuId.DataExplorerContext, {
...
+// For Database nodes under a Server in the SQL Servers folder
 MenuRegistry.appendMenuItem(MenuId.DataExplorerContext, {
 	group: 'connection',
 	order: 2,
 	command: {
 		id: NEW_QUERY_COMMAND_ID,
 		title: localize('newQuery', 'New Query')
 	},
-	when: NodeContextKey.IsConnectable
+	when: ContextKeyExpr.and(
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: Thoughts on adding an Or expression? Then I wouldn't need to define a new entry for each viewItem type which would be awesome...

Comment (anthonydresser) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: We do have an or expr that kevin added

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts [hunk 2]
```diff
@@ -15,27 +15,83 @@ MenuRegistry.appendMenuItem(MenuId.DataExplorerContext, {
...
+	group: 'connection',
+	command: {
+		id: NEW_QUERY_COMMAND_ID,
+		title: localize('newQuery', 'New Query')
+	},
+	when: ContextKeyExpr.and(
+		new ContextKeyDefinedExpr('isConnectable'),
+		new ContextKeyEqualsExpr('isConnectable', true),
+		new ContextKeyDefinedExpr('viewItem'),
+		new ContextKeyEqualsExpr('viewItem', 'azure.resource.itemType.databaseServer'))
```
Comment (anthonydresser) [inline src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: This should be using regular expession rather than adding menu entries twice

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts [hunk 3]
```diff
@@ -15,27 +15,83 @@ MenuRegistry.appendMenuItem(MenuId.DataExplorerContext, {
...
+	order: 2,
+	command: {
+		id: NEW_QUERY_COMMAND_ID,
+		title: localize('newQuery', 'New Query')
+	},
+	when: ContextKeyExpr.and(
+		new ContextKeyDefinedExpr('isConnectable'),
+		new ContextKeyEqualsExpr('isConnectable', true),
+		new ContextKeyDefinedExpr('viewItem'),
+		new ContextKeyEqualsExpr('viewItem', 'azure.resource.itemType.database'))
```
Comment (anthonydresser) [inline src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: We shouldn't have azure specific strings in core. this means it won't work for cms

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: Where? All I'm seeing is >= and <= @kevcunnane ?
```
export const enum ContextKeyExprType {
	Defined = 1,
	Not = 2,
	Equals = 3,
	NotEquals = 4,
	And = 5,
	Regex = 6,
	// {{SQL CARBON EDIT}}
	GreaterThanEquals = 7,
	LessThanEquals = 8
	//
}
```

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: Yeah I'll make that change - although when I was looking at how people did this for VS Code menu extensions there were lots of suggestions to do it this way instead which is why I went this route. I assume the perf difference of not having to evaluate extra items is the big reason - is there anything else you know of (like incorrect behavior/duplicate entries) that would be why we shouldn't be doing it this way?

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts (hunk 1 above)
Comment (anthonydresser) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: I must have thought he did. nvm

Comment (kevcunnane) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: VSCode folks pushed back against adding "or" to their support. Apparently it's harder to get the logic right here. Just FYI - not saying we should't, but frankly we should consider pushing this back upstream to them whatever we do.

**Comment by Charles-Gagnon** [comment]
> 
> 
> Your assumption on what the issue is is incorrect. You don't have to build a when condition using contextkeyexpr. You can just use a contextkey directly (theres plenty of examples in our source and vscode source). 

In the code? Do you have examples? I looked for any that used these and this place was the only one I found it. And VS definitely uses the ContextKey*Expr - example in [contextScopedHistoryWidget.ts](https://github.com/Microsoft/azuredatastudio/blob/87765e8673dcd00c71afbcc743af8d78c94a5b15/src/vs/platform/browser/contextScopedHistoryWidget.ts )

```
when: ContextKeyExpr.and(new ContextKeyDefinedExpr(HistoryNavigationWidgetContext), new ContextKeyEqualsExpr(HistoryNavigationEnablementContext, true)),
```

The values we were using (NodeContextKey.IsConnectable for example) are defined as RawContextKey - which itself is an extension of ContextKeyDefinedExpr. So unless I'm not understanding how this works all it was doing was checking whether that value was defined or not - not the actual value itself.

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts (hunk 2 above)
Comment (anthonydresser) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: Per my later comment, we don't have azure specific strings in core. using regex allows for the fix while not specializing for a specific extension. I.E CMS would want this behavior, but wouldn't get it unless we then hard coded another string for cms.

I'm a little confused on what you mean by perf difference. The perf of regular expression should be negligible. Do you have some link to what you are talking about with people talking about menu extensions? If you are referring to the checking if a context key is defined; I supposed doing a undefined check is faster than a reg ex, but for booleans (`isConnectable`) doing a undefined check then a true/false check is twice as slow than just doing a true/false check, since true/false check also does a undefined check at the same time.

**Comment by anthonydresser** [comment]
> 
> 
> > Your assumption on what the issue is is incorrect. You don't have to build a when condition using contextkeyexpr. You can just use a contextkey directly (theres plenty of examples in our source and vscode source).
> 
> In the code? Do you have examples? I looked for any that used these and this place was the only one I found it. And VS definitely uses the ContextKey*Expr - example in [contextScopedHistoryWidget.ts](https://github.com/Microsoft/azuredatastudio/blob/87765e8673dcd00c71afbcc743af8d78c94a5b15/src/vs/platform/browser/contextScopedHistoryWidget.ts)
> 
> ```
> when: ContextKeyExpr.and(new ContextKeyDefinedExpr(HistoryNavigationWidgetContext), new ContextKeyEqualsExpr(HistoryNavigationEnablementContext, true)),
> ```
> 
> The values we were using (NodeContextKey.IsConnectable for example) are defined as RawContextKey - which itself is an extension of ContextKeyDefinedExpr. So unless I'm not understanding how this works all it was doing was checking whether that value was defined or not - not the actual value itself.

https://github.com/Microsoft/azuredatastudio/blob/debt/layering/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L385 uses raw context keys for most of the menu entries.

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: I was talking about perf of having separate menu registrations vs doing it as a regex. Without testing my gut feeling is that having the separate menu registrations is worse overall because each item would have to be evaluated separately every time you opened a menu - vs the regex which is just a single time. 

So that's why I'm doing the change to use a regex instead - I just wanted to see if you knew of any other reasons why we'd NOT want to do separate menu registrations. Because it seemed to work just fine functionality wise - just with the probable performance hit I mentioned above.

**Comment by Charles-Gagnon** [comment]
Ah, cool. That seems to work only for simple Boolean values or single strings though. I'm not seeing support for regex's doing it that way.

And given that the methods on the RawContextKey such as isEqualTo() and toNegated() just end up using the ContextKey*Expr anyways I don't see how my way is worse/broken. Slightly less readable sure - but I'm not seeing how I can do this using the more fluent style they're using there given the limitations.

**Comment by anthonydresser** [comment]
> 
> 
> Ah, cool. That seems to work only for simple Boolean values or single strings though. I'm not seeing support for regex's doing it that way.
> 
> And given that the methods on the RawContextKey such as isEqualTo() and toNegated() just end up using the ContextKey*Expr anyways I don't see how my way is worse/broken. Slightly less readable sure - but I'm not seeing how I can do this using the more fluent style they're using there given the limitations.

Sure when you need to refer to two keys, use all those classes (in this case when added a reg ex expression. My statement was based on 
> The when clause wasn't set up correctly - you need to use the classes like ContextKeyDefinedExpr to build up the expressions
which isn't true. I'm not sure why there isn't a reg ex version, so yeah in that cause you'd need to use an and.

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: I'm less concerned about it now since we can just use regexes, if we feel this would provide other use though I'm willing to investigate doing that later on.

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts [hunk 4]
```diff
@@ -18,24 +19,31 @@ MenuRegistry.appendMenuItem(MenuId.DataExplorerContext, {
...
 	group: 'connection',
 	order: 2,
 	command: {
 		id: NEW_QUERY_COMMAND_ID,
 		title: localize('newQuery', 'New Query')
 	},
-	when: NodeContextKey.IsConnectable
+	when: ContextKeyExpr.and(
+		NodeContextKey.IsConnectable,
+		new ContextKeyRegexExpr('viewItem', /Database|azure.resource.itemType.database|azure.resource.itemType.databaseServer/))
```
Comment (anthonydresser) [inline src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: Can you just make it a regex string that searches the whole string for "server" or "database"? Something like `.+(server|database)` that way we don't need to have azure strings in our core code.

Comment (Charles-Gagnon) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: Sure - I'll do that for now. TBH though this whole thing should probably be looked at if we're really concerned about extending it to things beyond the Azure tree (such as CMS). Having some sort of nodeType on here like OE does would be a good start.

Comment (Charles-Gagnon) [reply src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: Well it isn't pretty but it at least doesn't have the azure strings in it. The main problem is that we have no consistent standard for naming these things - the root nodes have a very different naming scheme than the subnodes and some of those subnodes have database or server in their name (such as ServerLevelLogin) that we don't want to have these menu items on. 

---
In reply to: [274688271](https://github.com/Microsoft/azuredatastudio/pull/4996#discussion_r274688271) [](ancestors = 274688271)

File: src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts [hunk 5]
```diff
@@ -18,24 +19,34 @@ MenuRegistry.appendMenuItem(MenuId.DataExplorerContext, {
 	when: NodeContextKey.IsConnected
 });
 
+// The weird regex is because we want this to generically apply to Database and Server nodes but right now
```
Comment (anthonydresser) [inline src/sql/workbench/parts/dataExplorer/electron-browser/nodeActions.contribution.ts]: We control the value of viewitem for nodes coming from the "data sourcing" part of the code. So we can make it so the viewitem value for mssql nodes in extension trees avoid potentially confusing strings such as "serverlevellogin"
