### PR TITLE
Reset scheduling parameters CPU/mem request/limit to defaults

### LINKED ISSUE #14370: Need to be able to reset scheduling parameters CPU/mem request/limit to defaults (ie empty strings)
- Azure Data Studio Version:
Version: 1.26.0-rc1 (user setup)
Commit: 37727b7911f67c09ae9de526709d24788ffb6dec
Date: 2021-02-18T06:12:35.818Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Arc extension: 0.7.3

Steps to Reproduce:

1. deploy Postgres Hyperscale
2. go to Compute + storage page
3. try to remove any value from CPU limit for example. it returns an error saying the min is 0. It is inaccurate. We should be able to revert to blank string inline with CLI experience
4.

### PR DESCRIPTION
**Pull request by nasc17**
Allows for empty input boxes to send empty string for configuration settings to be reset to default. This requires no longer having current values as placeholder but values within the box. User will have to backspace and then type to update. 

To remove the requests and/or limits, specify its value as empty string:
before
spec1
spechcange
after 
spec2

This PR fixes #14370

### CODE REVIEW

**Review by Charles-Gagnon — COMMENTED** [review]
Could you include screenshots/videos of the behavior please?

File: extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts [hunk 1]
```diff
@@ -12,6 +12,18 @@ import { DashboardPage } from '../../components/dashboardPage';
 import { PostgresModel } from '../../../models/postgresModel';
 import { convertToGibibyteString } from '../../../common/utils';
 
+export type ConfigurationSpecModel = {
+	workers?: number,
+	workerCoresRequest?: string | undefined,
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts:17]: FYI - the undefined isn't needed at this point since it's already an optional property

File: extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts [hunk 2]
```diff
@@ -500,9 +532,9 @@ export class PostgresComputeAndStoragePage extends DashboardPage {
 		return flexContainer;
 	}
 
-	private handleOnTextChanged(component: azdata.InputBoxComponent): boolean {
-		if ((!component.value)) {
-			// if there is no text found in the inputbox component return false
+	private handleOnTextChanged(component: azdata.InputBoxComponent, originalValue: string): boolean {
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts:535]: Would be good to indicate in a doc comment what the return value indicates. Could also rename the function to make it clearer

**Review by Charles-Gagnon — APPROVED** [review]

**Review by bergeron — APPROVED** [review]
