### PR TITLE
Fixing a couple database reference dialog bugs

### LINKED ISSUE #15443: Database reference dialog sometimes changes value in disabled inputboxes
Changing the referenced project shouldn't populate the database name and variable text boxes when the reference location is same db.

Workaround is to change selected project before selecting location or changing location to something else and then back to same database. This problem doesn't happen if you follow the flow of the dialog from top to bottom.

Steps to Reproduce:
dbReferencesBug

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #15443. Also noticed another bug where the location dropdown wasn't getting updated when switching from the system db radio button to project radio button, so fixing that here too. 

before:
dbReferencesBug

Fixed:
dialogFix

### CODE REVIEW

File: extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts [hunk 1]
```diff
@@ -274,7 +276,6 @@ export class AddDatabaseReferenceDialog {
 		this.formBuilder!.insertFormItem(<azdata.FormComponent>this.dacpacFormComponent, 2);
 
 		this.locationDropdown!.values = constants.locationDropdownValues;
-		this.locationDropdown!.value = constants.differentDbSameServer;
```
Comment (kisantia) [inline extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts:277]: when the dacpac radio button is clicked, the location should stay the same as whatever the previously selected value was.

**Review by SakshiS-harma — APPROVED** [review]
