### PR TITLE
Fix Account Dialog with Multiple Providers

### LINKED ISSUE #11260: No enabled cloud error when using Account Dialog on startup
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open ADS and open Account Dialog immediately after startup
2. Click Add Account

Expected: Go through process to add account

Actual: Error about no clouds enabled even though public cloud is enabled.  This appears to be a race condition with something loading on startup.  Trying to add an account a little later (~10-15 seconds) works as expected.

image

### PR DESCRIPTION
**Pull request by cssuh**
Fixes a few bugs in the Account Dialog relating to having multiple providers:
Old Behavior:

1. `setSelection([0])` caused an index error on an empty list, and as a result `_providerViewsMap` was not updated.
2. After removing a provider, re-adding it caused this error:
Screenshot 2023-02-02 at 3 59 01 PM

3. When two providers (for example China & US Gov) were selected but none of them contained any accounts, only one "Add an Account" option was shown when there should be two, one for each provider.

4. There was an index out of bounds error because we weren't correctly incrementing/decrementing the index stored in providerView when we add/remove elements to the splitView  

New Behavior:

1. Check the length of firstView.view before calling `setSelection([0])
2. Check if a provider has been added already
3. Check how many providers are active before displaying the noAccountContainer.
4. Correctly increment/decrement providerView index.

Adding / removing too many providers with these unhandled errors also caused the `You have no clouds enabled` message to show up for me, this is fixed now. (although I'm not sure if that's enough to close #11260)

### CODE REVIEW

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 1]
```diff
@@ -357,13 +362,20 @@ export class AccountDialog extends Modal {
...
 
-		Registry.as<IViewsRegistry>(ViewContainerExtensions.ViewsRegistry).registerViews([{
-			id: newProvider.addedProvider.id,
-			name: newProvider.addedProvider.displayName,
-			ctorDescriptor: new SyncDescriptor(AccountPanel),
-		}], ACCOUNT_VIEW_CONTAINER);
+		// Check if view is registered, if it isn't, register the view
+		if (!Registry.as<IViewsRegistry>(ViewContainerExtensions.ViewsRegistry).getView(newProvider.addedProvider.id)) {
+			try {
+				Registry.as<IViewsRegistry>(ViewContainerExtensions.ViewsRegistry).registerViews([{
```
Comment (kburtram) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:368]: there may be a better place to put the view registration, such as one of the .contribution files, that is only loaded once so this gets added deterministically.

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 2]
```diff
@@ -357,13 +362,20 @@ export class AccountDialog extends Modal {
...
+					id: newProvider.addedProvider.id,
+					name: newProvider.addedProvider.displayName,
+					ctorDescriptor: new SyncDescriptor(AccountPanel),
+				}], ACCOUNT_VIEW_CONTAINER);
+				this.registerActions(newProvider.addedProvider.id);
+			} catch (error) {
+				this.logService.debug(error);
```
Comment (kburtram) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:375]: do we expect exceptions here?  Is it OK to swallow the exception with a log message?  i.e. would the entire experience be broken requiring a more prominent error?

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 3]
```diff
@@ -406,11 +425,21 @@ export class AccountDialog extends Modal {
...
+				provider.view.index--;
+			}
+		})
 		this._splitView!.layout(DOM.getContentHeight(this._container!));
 
 		// Remove the list view from our internal map
 		this._providerViewsMap.delete(removedProvider.id);
 		this.logService.debug(`Provider ${removedProvider.id} removed`);
+		// Update view after removing provider
+		if (this._splitViewContainer!.hidden || this._providerViewsMap.size > 1) {
```
Comment (kburtram) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:440]: so we always show the split view when removing a provider?  It seems like everywhere else there is also a check like `updatedAccounts.length > 0` or similar.  Probably fine, just checking from a UX perspective.  Also, possibly the `this._providerViewsMap.size > ` clause is redundant since the first condition seems to say "show the split view if it is hidden"?

**Review by kburtram — APPROVED** [review]
LGTM, left a few comments for consideration.

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts (hunk 2 above)
Comment (cheenamalhotra) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts:375]: This shouldn't be needed anymore since you've added the check to get registered providers first.

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 4]
```diff
@@ -406,11 +425,21 @@ export class AccountDialog extends Modal {
...
+			this.showSplitView();
+		}
 		this.layout();
```
Comment (cheenamalhotra) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:443]: Before layout, please also updateAccounts as done when adding a provider.

Comment (cssuh) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts:438]: fixed the problem this comment was referring to, it was a different issue

**Review by cheenamalhotra — APPROVED** [review]
