### PR TITLE
Fixes for sql db projects dashboard

### LINKED ISSUE #15021: Project dashboard build ids change with each new build
The build ids of builds changes with each build. Might also be confusing to users that the build ids start at zero.

Steps to repro:
1. start a build for a project and open dashboard. Refresh dashboard when build is finished
2. Start another build for the same project and refresh the dashboard.

Expected: build id for the already existing builds shouldn't change. 

Actual: Every time there is a new build (same with publish table), the newest build gets build id 0 and the other builds have their id increased by one. 

image

Next build - you can see the in progress build is now build id 0:
image

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #15021, #15089, #15185

Table names updated for Sql database projects:
image

ID column removed
Date and Target column swapped
Added target server and target database information for Publish scenario
[Tested target server and database information with publish profile (integrated and user login tested)]

image
image

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -71,13 +70,12 @@ export class ProjectsController {
 					text = constants.InProgress;
 				}
 
-				let infoRow: (string | dataworkspace.IconCellValue)[] = [count.toString(),
+				let infoRow: (string | dataworkspace.IconCellValue)[] = [infoRows.length.toString(),
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/projectController.ts:73]: should the id be something stored with the deploy info? The id isn't supposed change, so it can be set when the deployInfo is first created. It would also be good to store the id for when this dashboard data gets persisted later. Same for build info

Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/controllers/projectController.ts]: As discussed in the meeting, removed the ID column.

**Review by kisantia — APPROVED** [review]
