### PR TITLE
Fix split cell undo

### LINKED ISSUE #17820: Undo of split cell throws error
1. Create new code cell
2. Type some text such as `foobar`
3. Select `bar`
4. Split cell
5. Unselect active cell and undo, an error is thrown 

```
TypeError: Cannot read property 'source' of undefined
    at M.mergeCells (notebookModel.ts:685)
    at k.undo (cellEdit.ts:43)
    at undoRedoService.ts:1017
    at s._safeInvokeWithLocks (undoRedoService.ts:745)
    at undoRedoService.ts:1017
    at s._invokeResourcePrepare (undoRedoService.ts:788)
    at s._resourceUndo (undoRedoService.ts:1015)
    at s._undo (undoRedoService.ts:1098)
    at s.undo (undoRedoService.ts:1065)
    at M.undo (notebookModel.ts:1538)
    at notebook.component.ts:132
    at ZoneDelegate.invokeTask (C:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:421)
    at Zone.runTask (C:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:188)
    at ZoneTask.invokeTask [as invoke] (C:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:496)
    at invokeTask (C:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1540)
    at globalZoneAwareCallback (C:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1577)
```

### PR DESCRIPTION
**Pull request by barbaravaldez**
This PR is for #17820 

Keep track of how we split the cells in an array. The first entry will always have the original cell and the subsequent cells will be the newly created cells.
To merge the cells we concatenate the sources from the other cells and attached them to the original cell.

https://user-images.githubusercontent.com/34872381/145117471-0b4ee8fe-5dfd-47ff-bcd2-9c1e6a83e709.mov

### CODE REVIEW

**Comment by chlafreniere** [comment]
Please don't use `fixes` in ask mode in the description

**Comment by chlafreniere** [comment]
@barbaravaldez can you put a quick description in the PR of the problem and your solution?

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -573,6 +573,7 @@ export class NotebookModel extends Disposable implements INotebookModel {
 				let newCell = undefined, tailCell = undefined, partialSource = undefined;
 				let newCellIndex = index;
 				let tailCellIndex = index;
+				let splitCells: ICellModel[] = [];
 				let newLinesRemoved: string[] = [];
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:577]: This doesn't need to be an array, right? We know we're just removing a single string so let's do that to reduce possible confusion. And I'd also suggest updating the name to be more specific like `newlinesBeforeTailCellContent`

But also thinking about it - it would be even better to make the list of splitCells be a list of objects like this : 

```
type SplitCell {
    cell: ICellModel;
    prefix: string | undefined;
}
...
let splitCells: SplitCell[] = [];
```

So that you can then tell each cell whether it has prefix content that was stripped off or not (which would fix the issue I called out below with adding the newlines for every cell)

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 2]
```diff
@@ -679,19 +682,22 @@ export class NotebookModel extends Disposable implements INotebookModel {
...
-			cell.isEditMode = true;
-			// Set newly created cell as active cell
-			this.updateActiveCell(cell);
-			this._contentChangedEmitter.fire({
-				changeType: NotebookChangeType.CellsModified,
-				cells: [cell],
-				cellIndex: index
-			});
-			this.deleteCell(secondCell, false);
+	public mergeCells(cells: ICellModel[], newLinesRemoved: string[] | undefined): void {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:685]: I don't think newLinesRemoved can actually be undefined here so remove the `| undefined`. (and if it was possible to be undefined then your logic below would throw in that case so be careful)

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 3]
```diff
@@ -679,19 +682,22 @@ export class NotebookModel extends Disposable implements INotebookModel {
...
+		let firstCell = cells[0];
+		// Append the other cell sources to the first cell
+		for (let i = 1; i < cells.length; i++) {
+			firstCell.source = newLinesRemoved.length > 0 ? [...firstCell.source, ...newLinesRemoved, ...cells[i].source] : [...firstCell.source, ...cells[i].source];
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:689]: We don't want to add the newlines for every cell - the only one we should be adding this for is when adding on the tail cell

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 4]
```diff
@@ -573,7 +578,8 @@ export class NotebookModel extends Disposable implements INotebookModel {
 				let newCell = undefined, tailCell = undefined, partialSource = undefined;
 				let newCellIndex = index;
 				let tailCellIndex = index;
-				let newLinesRemoved: string[] = [];
+				let splitCells: SplitCell[] = [];
+				let newlinesBeforeTailCellContent: string;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:582]: This can just be defined down right before line 655 - no reason to have it all the way up here.

**Review by Charles-Gagnon — APPROVED** [review]
Please make sure to follow up with adding tests
