### PR TITLE
throw when onOk, onGenerateScript errors

### LINKED ISSUE #12836: onOk and onGenerateScript show throw on exception
While fixing #12814, it was found that onOk and onGenerateScript, which are handlers for 'Done' and 'GenerateScript' buttons, are just raising a message which continues the execution. This leads to a behavior where the wizard exits when errors have been encountered while getting the notebook ready. When the wizard exits, the user misses any errors displayed.

Similarly, in the processOptionsType field, when we are processing options sources, in the face of an error message, we are posting the error message bur returning sentinel values, which leads to the continuation of execution.

### PR DESCRIPTION
**Pull request by ranasaria**
This PR fixes #12836 
**Without this fix** 
when an error happens upon hitting 'Script to notebook' or 'Deploy' button the error flashes for a split second at the top and the whole wizard gets hidden and the notebook gets opened. The error is not displayed and the generated notebook is not guaranteed to work due to the underlying error.

**With this fix** 
when an error happens upon hitting 'Script to notebook' or 'Deploy' button the error is displayed to the user and controls are disabled.
image

The console also logs the error:
[38112:1009/162519.437240:INFO:CONSOLE(43)] "[[object Object]]Unknown error happened: failed to get options source for providerId: arc.controllers", source: file:///Users/arvranmac/git/ads/out/vs/workbench/api/browser/mainThreadExtensionService.js (43)
[38112:1009/162519.437311:INFO:CONSOLE(44)] "Error: Unknown error happened: failed to get options source for providerId: arc.controllers
	at processOptionsTypeField (/Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:348:19)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async processField (/Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:280:13)
	at async processFields (/Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:224:9)
	at async createSection (/Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:189:9)
	at async Promise.all (index 0)
	at async /Users/arvranmac/git/ads/extensions/resource-deployment/out/ui/modelViewUtils.js:154:26", source: file:///Users/arvranmac/git/ads/out/vs/workbench/api/browser/mainThreadExtensionService.js (44)

### CODE REVIEW

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts [hunk 1]
```diff
@@ -58,7 +59,9 @@ export class NotebookWizard extends WizardBase<NotebookWizard, NotebookWizardPag
 			const notebook = await this.prepareNotebookAndEnvironment();
 			await this.openNotebook(notebook);
 		} catch (error) {
-			vscode.window.showErrorMessage(error);
+			console.log(error);
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts:62]: So what's the behavior now - I see above we're setting the container message with the error message but we're also showing the error message in a toast? Please include a screenshot of what this looks like when an error occurs

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts [hunk 2]
```diff
@@ -58,7 +59,9 @@ export class NotebookWizard extends WizardBase<NotebookWizard, NotebookWizardPag
...
+			vscode.window.showErrorMessage(getErrorMessage(error));
+			throw error;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts:64]: What's catching this error?

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts:62]: Yes, we are showing both the combating message and the toast

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts (hunk 2 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts:64]: It gets caught by the onOk, onGenerateScript handlers and rethrown from there for vscode wizard code to abort the closing of the wizard.

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts:62]: Well that seems a bit redundant. Any reason why you went that way instead of just showing one?

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts:62]: Let me redo this to show just one.

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts (hunk 2 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts:64]: What I said above about vscode aborting the closing of the wizard is a conjecture from my observation that if I throw that stops the wizard from closing and if I don't that the wizard is closed. I have not actually looked into the vscode codebase for it. I will add a comment there to explain why we are re-throwing there.

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts]: I guess that's ok - but just FYI the wizard code is all ours. Not VS Code. So it'd be good to understand what's happening here if you don't have that now. The behavior matches what I'd expect in general but know exactly what's going on is usually a good idea when you're throwing errors.

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts]: You are right, found the code, here it is:
https://github.com/microsoft/azuredatastudio/blob/649f18b6f39403f6744fc7207569c2486a781fbf/src/sql/workbench/services/dialog/browser/wizardModal.ts#L85-L85
https://github.com/microsoft/azuredatastudio/blob/649f18b6f39403f6744fc7207569c2486a781fbf/src/sql/workbench/services/dialog/browser/wizardModal.ts#L259-L268
https://github.com/microsoft/azuredatastudio/blob/649f18b6f39403f6744fc7207569c2486a781fbf/src/sql/workbench/services/dialog/browser/wizardModal.ts#L179-L180



So, my conjecture was correct.

File: extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/notebookWizard/notebookWizard.ts:62]: Updated description with the screenshot.

**Review by Charles-Gagnon — APPROVED** [review]
