### PR TITLE
Fixing Slick Grid accessibility bugs. 

### LINKED ISSUE #19843: A11y_Azure Data Studio extension 'Azure SQL Migration'_Databases for assessment_Keyboard Trap: Keyboard tab focus is getting trapped inside databases grid and is not coming out of grid.
"[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### Github Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #Benchmark; #SH-AzureSQLMigration-Win32-Jun2022; #DesktopApp; #Win32; #SQL Migration Control Plane; #WCAG2.1.2; #Keyboard Trap;

### Environment and OS details:
Azure Data Studio Version 1.37.0(User Setup)
Windows Version 21H2 (OS Build 22000.675)

### Repro Steps:

1. Install Azure data studio app and install Azure SQL migration extension
2. Connect to SQL server, tab till respective server, right click and select manage
3. Tab till Azure SQL Migration in sitemap and press enter key
4. Tab till migrate to azure sql and press enter
5. Navigate to databases grid in "Databases for assessment" in step 1.
6. Verify that keyboard focus is getting trapped inside databases grid and is not coming out of grid.

### Actual Result:
Keyboard tab focus is getting trapped inside databases grid and is not coming out of grid.

### Expected Result:
Keyboard tab focus should not get trapped inside databases grid and should come out of grid. User should be able to navigate to each row using arrow keys and on clicking space/enter key database should get selected. On pressing tab key, focus should come out of grid.

### Attachment:
Keyboard trap_

### LINKED ISSUE #19864: A11y_Azure Data Studio extension 'Azure SQL Migration'_Databases for assessment_ScreenReader: Narrator/NVDA is announcing number of rows incorrectly, doesnt announce row name and row number is read incorrectly
"[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### Github Tags:
#A11yMAS; #A11yTCS; #Benchmark; #SH-AzureSQLMigration-Win32-Jun2022; #DesktopApp; #Win32; #SQL Migration Control Plane; #WCAG1.3.1; #ScreenReader; #Narrator; #NVDA; #A11ySev3; #External; #External:NVDA; #ThirdParty;

### Environment and OS details:
Azure Data Studio Version 1.37.0(User Setup)
Windows Version 21H2 (OS Build 22000.675)

### Repro Steps:

1. Turn on Narrator/NVDA
2. Install Azure data studio app and install Azure SQL migration extension
3. Connect to SQL server, tab till respective server, right click and select manage
4. Tab till Azure SQL Migration in sitemap and press enter key
5. Tab till migrate to azure sql and press enter
6. Navigate to databases grid in "Databases for assessment" step.
7. Verify that screen reader announces table summary incorrectly and doesnot announce row name

### Actual Result:
Narrator/NVDA is announcing number of rows incorrectly, doesnt announce row name and row number is read incorrectly

### Expected Result:
Narrator/NVDA should announce total number of rows correctly, should announce row name and all the table properties must be defined.

### Attachment:
Narrator_table summary_
NVDA_table summary

### PR DESCRIPTION
**Pull request by aasimkhan30**
Issues: #19864, #19843, #19831

This PR also aligns the checkbox to the center of the cell:
image
image

When select active row is true, everytime the a cell is focused the focus then goes to the entire row.
Example:
azuredatastudio-insiders_uykTv5b1e9

After disabling it, the behavior becomes normal and expected.
azuredatastudio_v59tA7R7py

Also, this PR needs to be updated to the latest version of ADS Slick to truly fix everything. The PR for that is over here. 
https://github.com/microsoft/SlickGrid.ADS/pull/7

### CODE REVIEW

**Comment by alanrenmsft** [comment]
the file name is `checkboxSelectColumn2.plugin.ts`, seriously? :) 
why not update the existing class?

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 - FYI I believe that the current expectation is that we're not supposed to close issues ourselves. The a11y team is the one that does that. So please remove the auto-close keywords from your description so they stay open.

**Comment by Charles-Gagnon** [comment]
And is this ready for review? Please set it to draft if it's still in progress

**Comment by alanrenmsft** [comment]
@aasimkhan30 please remove the auto-close tags as @Charles-Gagnon pointed out.

File: src/sql/workbench/browser/modelComponents/table.component.ts [hunk 1]
```diff
@@ -277,7 +277,7 @@ export default class TableComponent extends ComponentBase<azdata.TableComponentP
 
 			this._table = new Table<Slick.SlickData>(this._inputContainer.nativeElement, { dataProvider: this._tableData, columns: this._tableColumns }, options);
 			this._table.setData(this._tableData);
-			this._table.setSelectionModel(new RowSelectionModel({ selectActiveRow: true }));
+			this._table.setSelectionModel(new RowSelectionModel({ selectActiveRow: false }));
```
Comment (alanrenmsft) [inline src/sql/workbench/browser/modelComponents/table.component.ts:280]: what is this for?

Comment (aasimkhan30) [reply src/sql/workbench/browser/modelComponents/table.component.ts:280]: When select active row is true, everytime the a cell is focused the focus then goes to the entire row.
Example:
azuredatastudio-insiders_uykTv5b1e9

After disabling it, the behavior becomes normal and expected.

Comment (aasimkhan30) [reply src/sql/workbench/browser/modelComponents/table.component.ts:280]: azuredatastudio_v59tA7R7py

**Comment by aasimkhan30** [comment]
@alanrenmsft , updated description with gifs

File: src/sql/base/browser/ui/table/plugins/media/checkboxSelectColumn.plugin.css [hunk 2]
```diff
@@ -0,0 +1,16 @@
+/*---------------------------------------------------------------------------------------------
+ *  Copyright (c) Microsoft Corporation. All rights reserved.
+ *  Licensed under the Source EULA. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+
+.slick-plugin-checkbox-select-column {
+	text-align: center;
+	border-bottom: 0px !important;
```
Comment (alanrenmsft) [inline src/sql/base/browser/ui/table/plugins/media/checkboxSelectColumn.plugin.css:8]: can you use more specific css selectors to avoid needing to use `important` modifier?

**Review by alanrenmsft — APPROVED** [review]
