### PR TITLE
fix loop for cancelling out databases

### LINKED ISSUE #19451: SQL Binding - Can't exit out of database picker
1. Run `Create Azure Function with SQL Binding`
2. Select Create New Project
3. Go through prompts until you are prompted to choose a database (after choosing a connection)
4. Press esc to exit the dialog

The database picker quickpick shows up again, making it impossible to exit out until a database is selected.

We should be going back to the connection picker at this point.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #19451.
We should return undefined so that the azureFunctionService would then continue back to prompt the user to choose the connection profile.

### CODE REVIEW

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 1]
```diff
@@ -335,15 +335,15 @@ export async function promptForObjectName(bindingType: BindingType, connectionIn
 		// get connectionURI and selectedDatabase to be used for listing tables query request
 		connectionURI = await getConnectionURI(connectionInfo);
 		if (!connectionURI) {
-			// User cancelled or mssql connection error
+			// mssql connection error
 			// we will then prompt user to choose a connection profile again
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:339]: I'd suggest removing these comments saying what is going to happen since that's controlled by the calling code, not this. So if what we do there ever changes or we use this elsewhere this could easily be incorrect.

File: extensions/sql-bindings/src/common/azureFunctionsUtils.ts [hunk 2]
```diff
@@ -335,15 +335,15 @@ export async function promptForObjectName(bindingType: BindingType, connectionIn
...
-			continue;
+			return undefined;
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/azureFunctionsUtils.ts:340]: Since we're never continuing anymore you can get rid of the while loop completely, right?

**Review by Charles-Gagnon — APPROVED** [review]
