### PR TITLE
Fix/find context correction

### LINKED ISSUE #9551: Notebook - On switching Notebooks, the Find popup remembers previous context
Issue Type: <b>Bug</b>

Repro steps:
- Open a Notebook with markdown text in it.
- Try to find items in the Notebook by clicking Ctrl+F
- Click on "Next Match" button to go to other matches.
- Open another Notebook

The Find popup sticks around and remembers the previous context. It shows find match count from previous Notebook. The find results are not relevant on the new file.

In the image below, the results are from a previous file. Clicking on Next/Previous match does not do anything. 
image

Azure Data Studio version: azuredatastudio 1.16.0 (29031462c7de8d562a348276a27b616e14ffc103, 2020-03-11T16:51:08.075Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (20.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by MaddyDev**
Issue: When find is active on an open notebook, if user opens a new notebook, find doesn't refresh its context and shows previous active editor results.
Fix: when a new notebook editor is open, trigger the input change event that refreshes the context correctly.

This PR fixes #9551 

Will be adding tests around this in a different PR.

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/notebookEditor.ts [hunk 1]
```diff
@@ -283,58 +283,58 @@ export class NotebookEditor extends BaseEditor implements IFindNotebookControlle
 			} else {
 				this._finder.getDomNode().style.visibility = 'hidden';
 				this._findDecorations.clearDecorations();
+				return;
```
Comment (corivera) [inline src/sql/workbench/contrib/notebook/browser/notebookEditor.ts:286]: Why the returns here?

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/notebookEditor.ts:286]: no need to further check when we're already handling the reveal event here, below events needs to be checked only when isRevealed is true.

File: src/sql/workbench/contrib/notebook/browser/notebookEditor.ts [hunk 2]
```diff
@@ -283,58 +283,58 @@ export class NotebookEditor extends BaseEditor implements IFindNotebookControlle
...
-								this.notebookFindModel.getFindIndex(),
-								this._findDecorations.getCount(),
-								this._currentMatch
-							);
-							this._setCurrentFindMatch(this._currentMatch);
-						});
+			if (this._notebookModel && this._findState.searchString) {
+				let findScope = this._findDecorations.getFindScope();
+				if (this._findState.searchString === this.notebookFindModel.findExpression && findScope !== null && !e.matchCase && !e.wholeWord && !e.searchScope) {
+					if (findScope) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookEditor.ts:302]: You already check findScope !== null so this seems unnecessary (and if undefined is also a possible value then you should just have it be ` && findScope &&` above
