### PR TITLE
avoid unnecessary connections in azure view

### LINKED ISSUE #20789: Azure Tab object explorer is sending connection request on expanding databases
- Azure Data Studio Version: 1.40.0 insider
- OS Version: Windows 11

Steps to Reproduce:

1. Run mysql extension and connect to mysql server in Azure Tab. Expand 'Databases'. Check the logs a new connection request is being sent instead of object explorer expand/refresh request.

Check the below picture.
On expanding databases in object explorer, a new connection request is being sent instead of objectexplorer/expand or refresh.

Screenshot (17)

Does this issue occur when all extensions are disabled?: Yes/No Yes same behaviour for sql.

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #20789

previously we were using a hash key generated by the payload(connection info) and viewid  to determine whether a new session is needed, but since the payload changes for database nodes and their child nodes, when expanding a database node, we will end up creating a new connection/OE Session which is totally unnecessary.

I am using the session id directly and set on the node and it will be passed to its children so that no new session is created for a connectable node.

tested with azure sql server, azure sql db, mysql, pgsql. all look good.

@rishky-msft FYI.

### CODE REVIEW

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts [hunk 1]
```diff
@@ -111,42 +110,28 @@ export class OEShimService extends Disposable implements IOEShimService {
...
-		if (session) {
-			let closed = (await this.oe.closeSession(node.childProvider!, this.oe.getSession(session)!))!.success;
-			if (closed) {
-				this.sessionMap.delete(key);
-			}
+		if (node.sessionId !== undefined) {
+			const closed = (await this.oe.closeSession(node.childProvider!, this.oe.getSession(node.sessionId!)!))!.success;
 			return closed;
 		}
 		return Promise.resolve(false);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts:117]: While you're here - this is already async so you can remove the Promise.resolve.

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts [hunk 2]
```diff
@@ -221,7 +207,7 @@ export class OEShimService extends Disposable implements IOEShimService {
 	}
 
 	public isNodeConnected(viewId: string, node: ITreeItem): boolean {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts:209]: Remove viewId param?

File: src/sql/workbench/common/views.ts [hunk 3]
```diff
@@ -29,7 +29,8 @@ export interface ITreeItem extends vsITreeItem {
 	payload?: IConnectionProfile; // its possible we will want this to be more generic
 	sqlIcon?: string;
 	type?: NodeType;
-	nodeInfo?: NodeInfo
+	nodeInfo?: NodeInfo;
+	sessionId?: string;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/common/views.ts:33]: Add doc comment for what a "session" is in this context

**Review by Charles-Gagnon — COMMENTED** [review]
So does this mean that an Azure server/database node and all of its children will now use the same connection? Because that's generally not what we want to be doing for databases under a server - they need to use their own connections since many properties/views are at the DB scope. 

Although I suppose since we use SMO for OE stuff that might not be an issue (it already creates a new connection for queries at or under the database level). But let's make sure that's the case before making changes here.

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts [hunk 4]
```diff
@@ -111,42 +110,28 @@ export class OEShimService extends Disposable implements IOEShimService {
...
-		// check to make sure we have an existing connection
-		let key = generateSessionMapKey(viewId, node);
-		let session = this.sessionMap.get(key);
-		if (session) {
-			let closed = (await this.oe.closeSession(node.childProvider!, this.oe.getSession(session)!))!.success;
-			if (closed) {
-				this.sessionMap.delete(key);
-			}
+		if (node.sessionId !== undefined) {
+			const closed = (await this.oe.closeSession(node.childProvider!, this.oe.getSession(node.sessionId!)!))!.success;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts:114]: `node.sessionId!` is unnecessary - you already know it's not undefined because of the if check

**Review by Charles-Gagnon — APPROVED** [review]
I'm not an expert on this stuff so it's hard for me to say whether there's any issues with this without spending more time digging into everything so signing off with just trusting that you've looked at this enough to feel confident this isn't going to cause problems.

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts (hunk 1 above)
Comment (alanrenmsft) [reply src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts:117]: done

File: src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts (hunk 2 above)
Comment (alanrenmsft) [reply src/sql/workbench/services/objectExplorer/browser/objectExplorerViewTreeShim.ts:209]: done

File: src/sql/workbench/common/views.ts (hunk 3 above)
Comment (alanrenmsft) [reply src/sql/workbench/common/views.ts:33]: done

**Comment by alanrenmsft** [comment]
> So does this mean that an Azure server/database node and all of its children will now use the same connection? Because that's generally not what we want to be doing for databases under a server - they need to use their own connections since many properties/views are at the DB scope.
> 
> Although I suppose since we use SMO for OE stuff that might not be an issue (it already creates a new connection for queries at or under the database level). But let's make sure that's the case before making changes here.

@Charles-Gagnon, The new behavior is exactly the same as in Object Explorer when you connect to a server(Azure SQL Server, Azure MySQL Server or Azure Postgres Server), all nodes under a connection share the same connection/session. Previously, the azure view would open a new connection when the database node is expanded as if you are directly connected to an Azure SQL DB in Object Explorer. 

There were different approaches to fix the issue, one option is to not change the payload(connection info) for database node and its children, the nodes will be displayed as expected without creating more connections/sessions, but the context menu items might not work properly. e.g. `New Query` on the database node will be connected to the server not database.  there will be a lot more work to make sure all context menu items work as expected.

The approach I chose here is minimum impact since it is purely internal to this class.

**Comment by Charles-Gagnon** [comment]
Yeah, makes sense. I guess it'd be up to the provider to decide if they need to make "new" connections for certain resources so this isn't something that should be controlled at this level anyways.

**Review by cheenamalhotra — APPROVED** [review]
