### PR TITLE
fix the issue that chart axis's min/max value can't be zero

### LINKED ISSUE #3538: Chart viewer axis minimum/maximum value can't be 0
- Azure Data Studio Version: 1.3.8-rc

Steps to Reproduce:
1. Run a query that returns numeric results
2. Open chart viewer
3. Select horizontalBar or verticalBar chart types
4. Set X/Y Axis Minimum/Maximum values to 0

Expected behavior: The minimum/maximum values update like they do if you set them to any other value
Actual behavior: Entering 0 has no effect

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #3538 

noticed this today while testing the feature and found this old issue.

Root cause: we are not differentiating 0 and undefined when processing the options.
Fix: check for undefined explicitly.

With the fix: 
chartoption

### CODE REVIEW

File: src/sql/workbench/contrib/charts/browser/chartView.ts [hunk 1]
```diff
@@ -389,8 +389,9 @@ export class ChartView extends Disposable implements IPanelView {
 				numberInput.setAriaLabel(option.label);
 				numberInput.value = value || '';
 				numberInput.onDidChange(e => {
-					if (this._options[entry] !== Number(e)) {
-						(this._options[entry] as any) = Number(e);
+					if (this._options[entry] !== e) {
+						// When user clears the input box, the value we get from the input box will be empty string.
+						(this._options[entry] as any) = e === '' ? undefined : Number(e);
```
Comment (kburtram) [inline src/sql/workbench/contrib/charts/browser/chartView.ts:394]: nit: this is not the most clear statement to read, with the tertiary operator and the cast.  maybe wrapping `e === '' ? undefined : Number(e)` in `( )` would help a little.

File: src/sql/workbench/contrib/charts/browser/graphInsight.ts [hunk 2]
```diff
@@ -208,11 +208,11 @@ export class Graph implements IInsight {
 					}
 				}];
 
-				if (options.xAxisMax) {
+				if (options.xAxisMax !== undefined) {
```
Comment (kburtram) [inline src/sql/workbench/contrib/charts/browser/graphInsight.ts:211]: interesting 0 is considered false in JS.  I didn't realize this gem from C was in this language as well 😄.

**Review by kburtram — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
