### PR TITLE
Fix sql projects net6 warnings

### LINKED ISSUE #17667: SQL Database Projects is showing unsupported .NET SDK version warning even when no sqlproj is opened
1. Create new csproj (I used the Azure function project generator for this)
2. Open the folder in VS Code with the SQL Database Project extension installed

After a bit the warning will pop up

image

This is expected if there's a sqlproj in the workspace, but we shouldn't be showing this if there isn't (people may have the extension installed through the MSSQL extension but not actually use sqlproj's). And then especially with the release of .NET 6 this is could annoy a lot of people.

It doesn't seem to repro in ADS though, maybe fixed in the version being used there?

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #17667 and the double warning also mentioned in that issue. Now the .net 6 installed warning only shows when trying to build a project and it "Do Not Show Again" hasn't been selected.

before (two warnings):
image

now:
image

### CODE REVIEW

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 1]
```diff
@@ -208,7 +208,8 @@ export class NetCoreTool extends ShellExecutionHelper {
 			} else if (this.netCoreInstallState === netCoreInstallState.netCoreVersionTooHigh && vscode.workspace.getConfiguration(DBProjectConfigurationKey)[NetCoreDowngradeDoNotShowAgainKey] === true) {
 				// Assume user has used global.json to override SDK version and proceed with build as is
 			} else {
-				throw new DotNetError(NetCoreSupportedVersionInstallationConfirmation(this.netCoreSdkInstalledVersion!));
+				// don't continue building if the user hasn't selected the do not show again on the warnings shown from findOrInstallNetCore()
+				return '';
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:212]: This is a generic "run dotnet command" function so I don't think having build-specific comments here is the best. 

And do you really want to just return here and not throw an error? Returning would indicate to me that it completed successfully which isn't the case.

**Comment by Charles-Gagnon** [comment]
Also could you look into fixing the spacing here for `SDKLocation`? (should be `SDK Location` IMO)

image

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 1 above)
Comment (Benjin) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: +1 to both

Comment (kisantia) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts]: The error message was already a project build specific message, but I added it back and changed the build function that calls it to not show the error again if it's a dotnet error since it already gets shown by the netCoreHelper

File: extensions/sql-database-projects/package.json [hunk 2]
```diff
@@ -43,7 +43,7 @@
       {
         "title": "%sqlDatabaseProjects.Settings%",
         "properties": {
-          "sqlDatabaseProjects.netCoreSDKLocation": {
+          "sqlDatabaseProjects.netCoreSDK Location": {
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/package.json:46]: Did you verify this still works? I'm a little surprised that spaces in there are allowed.

At the very least don't you need to update the string in netcoreTools.ts?

Comment (kisantia) [reply extensions/sql-database-projects/package.json:46]: oops forgot to run the tests before pushing. Fixed now and also manually verified it works. Yeah I was also surprised that this worked since it looks like it uses camel case to figure out where the spaces go.

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Oh, and could you also bump the version?

File: extensions/sql-database-projects/src/tools/netcoreTool.ts [hunk 3]
```diff
@@ -17,7 +17,7 @@ import { ShellCommandOptions, ShellExecutionHelper } from './shellExecutionHelpe
 const localize = nls.loadMessageBundle();
 
 export const DBProjectConfigurationKey: string = 'sqlDatabaseProjects';
-export const NetCoreInstallLocationKey: string = 'netCoreSDKLocation';
+export const NetCoreInstallLocationKey: string = 'netCoreSDK Location';
```
Comment (zijchen) [inline extensions/sql-database-projects/src/tools/netcoreTool.ts:20]: Change intentional?

**Review by zijchen — APPROVED** [review]

File: extensions/sql-database-projects/src/tools/netcoreTool.ts (hunk 3 above)
Comment (zijchen) [reply extensions/sql-database-projects/src/tools/netcoreTool.ts:20]: Nevermind just saw Charles' comment

**Review by ssreerama — APPROVED** [review]

**Comment by ssreerama** [comment]
Want to know why the "Azure Data Studio - PR Validation" failed? Is it a transient or for any code change, I don't see any change that related to the error that is mentioned in the Error message, may be because of Console.log?? Thanks :)

**Comment by kisantia** [comment]
@Charles-Gagnon bump which version? The azdata version? I bumped the extension version after the October release.

@ssreerama PR validation failed because of a component governance error, which is an alert that either needs to get fixed by upgrading the package(s) with the vulnerabilities or dismissing it if it isn't relevant. It's the ADS DRI's job to look into these errors. You can usually tell if it's transient or not by checking if other builds in the pipeline are also failing with the same error.

**Comment by Charles-Gagnon** [comment]
Oh gotcha, yeah the version looks good then. Thanks!

Also you should merge in the latest from main so you get Alan's fix for CG.
