### PR TITLE
Fix accessibility issues with Manage Access dialog

### LINKED ISSUE #7806: A11y_AzureDataStudio_ManageAccessForFile_ScreenReader:"OWNERS ", "ALL OTHERS "and " NAMED USERS AND GROUPS" is not marked as table.
GitHubTags: #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG1.3.1;#WCAG4.2.3;#WCAG4.1.2;#WCAG4.2.1;#DesktopApp;#Win32;#NVDA;
**Environment Details: **
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit:6582debd7388b1be512fc3a9b956d3e54f6115e7
Date: 2019-10-03T08:56:27.454Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
**Additional Details:**
Tool Name : NVDA
**Steps to Reproduce:**
Install and Launch the application the azure data studio application.
2.Connet to the servers with the required credentials.
3.Navigate to the control panel and click on the “Jupyter books” icon.
4.Navigate till HDFS folder and right click on it and click on manage access.
Start NVDA and observe the announcement.
**Actual:**
Issue 1.NVDA is not announcing the "OWNERS ", "ALL OTHERS "and " NAMED USERS AND GROUPS" as table as there is no table mark up for that.
Issue 2.Table name is not announced by NVDA.
Issue 3.Header reference is  not announced with the header.
Issue 4.  Header reference is not announced along with the row content.
**Expected:**
Issue 1.NVDA is not announcing the "OWNERS ", "ALL OTHERS "and " NAMED USERS AND GROUPS" as table as there should be table mark up.
Issue 2.Table name is should announced by NVDA.
Issue 3.Header reference is  should announced with the header.
Issue 4.  Header reference should announce along with the row content.
**User Impact:**
Screen Reader user will not able to relate with the content.
**Attachment for Reference:**

[7806_A11y_AzureDataStudio_ManageAccessForFile_ScreenReader5.pptx](https://github.com/microsoft/azuredatastudio/files/3750228/7806_A11y_AzureDataStudio_ManageAccessForFile_ScreenReader5.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7806 as well as some other issues found during testing.

The bulk of the changes is converting from a manually created table from divs to using the declarative table component. While doing this I also changed it so the majority of the components aren't created until after the model has been populated since that fixes some display issues related to timing that we had before when we were updating the components after the model populated.

Made proposed API changes to clean up more of the ModelView stuff to be consistent with the other interfaces. Properties interfaces should be the ones containing just the properties and then the Component interfaces inheriting from those so that WithProperties is able to correctly identify which properties to allow. I did this here because some of the changes were ones I needed to do anyways for this and so splitting them up didn't make sense. 

New Dialog Directory :
image

Old Dialog Directory :
image

New Dialog File:
image

Old Dialog File:
image

Note that there are some cosmetic changes made to the UI - most notably the lines separating the sections in the table. Currently DeclarativeTable doesn't have support for that kind of fine-grained tuning and so in the interest of keeping this PR scoped down I'm purposely leaving it as it is for now.

### CODE REVIEW

File: extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts [hunk 1]
```diff
@@ -86,170 +83,250 @@ export class ManageAccessDialog {
...
+			this.addUserOrGroupInput.value = '';
+		});
+		const addUserOrGroupButton = this.modelBuilder.button().withProperties<azdata.ButtonProperties>({ label: loc.addLabel, width: 75 }).component();
+		addUserOrGroupButton.onDidClick(() => {
+			this.hdfsModel.createAndAddAclEntry(this.addUserOrGroupInput.value, this.addUserOrGroupSelectedType);
+			this.addUserOrGroupInput.value = '';
+		});
+		addUserOrGroupButton.enabled = false; // Init to disabled since we don't have any name entered in yet
+		this.addUserOrGroupInput.onTextChanged(() => {
+			if (this.addUserOrGroupInput.value === '') {
```
Comment (alanrenmsft) [inline extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts]: addUserOrGroupButton.enabled = this.addUserOrGroupInput.value !== ''

File: extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts [hunk 2]
```diff
@@ -86,170 +83,250 @@ export class ManageAccessDialog {
...
+		// = Sticky =
+		// ==========
+		this.stickyCheckbox = this.modelBuilder.checkBox()
+			.withProperties<azdata.CheckBoxProperties>({
+				width: checkboxSize,
+				height: checkboxSize,
+				checked: permissionStatus.stickyBit,
+				label: loc.stickyLabel
+			}).component();
+		this.stickyCheckbox.onChanged(() => {
```
Comment (alanrenmsft) [inline extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts]: I noticed we are not handling the event disposables in this dialog, can we add these to an array and dispose them when the dialog is getting closed?

Comment (Charles-Gagnon) [reply extensions/mssql/src/hdfs/ui/hdfsManageAccessDialog.ts]: I'll see about doing this as a follow up task - not going to add extra stuff to this PR at this point
