### PR TITLE
Prompt for consent when interaction is required

### LINKED ISSUE #10314: Azure AD Guest User Access (B2B) failes to Authenticate
- Azure Data Studio Version: 1.17.1 (MAC OS)

Steps to Reproduce:

**Setup:**

1. Created a guest user in alternate AD Tenant AD.
2. Invited the guest user into the primary AD.
3. Ensure the Guest user accepted the invitation and configured MFA.
4. Created a AD Group in the primary AD tenant  called `Guest_Group_Test` and added the Guest User.
5. Ensure AD Integration is on with the Azure SQL Server Azure AD by associating your AD User as owner or a group your a member of. 
6. Log into SQL Server using your user **(not the guest)**
7. The following TSQL was ran in the SQL Database successfully.
```
CREATE USER [Guest_Group_Test] FROM EXTERNAL PROVIDER;
EXEC sp_addrolemember 'db_datareader', 'Guest_Group_Test';  
```
8. Open Azure Data Studio, make a new connection to the target Azure SQL Server. 
9. Choose `Azure Active Directory - Universal with MFA Support`
10. Ensure the Account is the Guest user email who was added into the primary tenant via b2b.
11. Click Connect

**Error's:** 

`Retrieving the Azure token failed. Please Sign in again. `
`Login failed for user '<token-identified principal>'.` 

**Note:**
Tested on SSMS version 18 and the above scenario works with authenticating B2B users provided they are in a AD Group.

### PR DESCRIPTION
**Pull request by aaomidi**
This pr _should_ fix #10314 

Unfortunately since I'm unable to repro this environment I won't be able to test it personally but I have a few partners I can validate this by.

### CODE REVIEW

File: extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts [hunk 1]
```diff
@@ -56,11 +56,52 @@ export class AzureAuthCodeGrant extends AzureAuth {
...
+			expiresOn = eo;
+		} catch (ex) {
+			if (ex.msg) {
+				vscode.window.showErrorMessage(ex.msg);
+			}
+			console.log(ex);
+		}
+
+		if (!accessToken) {
+			const msg = localize('azure.tokenFail', "Failure when retreiving tokens.");
```
Comment (kburtram) [inline extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts:89]: looks like a typo in 'retrieving'

File: extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts [hunk 2]
```diff
@@ -56,11 +56,52 @@ export class AzureAuthCodeGrant extends AzureAuth {
...
+			authCompleteDeferred.reject(new Error(msg));
+			throw Error('Failure when retreiving tokens');
```
Comment (kburtram) [inline extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts:91]: same typo here.

File: extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts [hunk 3]
```diff
@@ -57,6 +57,11 @@ export class AzureDeviceCode extends AzureAuth {
 
 	}
 
+	public async promptForConsent(resourceId: string): Promise<undefined> {
```
Comment (kburtram) [inline extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts:60]: it isn't immediately clear to me when this will run.  Does this block any device code scenarios we'd like to support?  Or is this to fix the Conditional Access issue you mentioned on chat?

File: extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts (hunk 1 above)
Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureAuthCodeGrant.ts:89]: Thanks for catching this!

File: extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts (hunk 3 above)
Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts:60]: If when getting the token from AAD, the response is "interaction required", because device code is an interaction-less authentication method, they can't use it.

So this will only impact device code auth when the user is using conditional access.

File: extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts [hunk 4]
```diff
@@ -57,6 +57,11 @@ export class AzureDeviceCode extends AzureAuth {
...
+		vscode.window.showErrorMessage(localize('azure.deviceCodeDoesNotSupportConsent', "Device code authentication does not support prompting for consent. Switch the authentication method in settings to code grant."));
+		return undefined;
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts:62]: Just have return type be void and return without param

File: extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts [hunk 5]
```diff
@@ -57,6 +57,11 @@ export class AzureDeviceCode extends AzureAuth {
 
 	}
 
+	public async promptForConsent(resourceId: string): Promise<undefined> {
+		vscode.window.showErrorMessage(localize('azure.deviceCodeDoesNotSupportConsent', "Device code authentication does not support prompting for consent. Switch the authentication method in settings to code grant."));
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts:61]: Maybe explain a bit here (or link to a doc) why we need to prompt for consent here so the user doesn't blame us for it 😄

File: extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts (hunk 4 above)
Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts:62]: Won't work since it'd go against the definition on azureAuth.ts (abstract method there)

File: extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts (hunk 5 above)
Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts:61]: Yeah I actually need to do some work in making this less abrupt, right now it could literally just popup in the middle of their work and start opening a browser which can throw people off

File: extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts (hunk 4 above)
Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/azureDeviceCode.ts:62]: Ah right - guess I'm just used to always putting the same signature for overrides but this is fine

**Comment by aaomidi** [comment]
So I'm waiting for a partner to confirm this fixes their issue. Once that's done I'll add some more code that just tries to make the UX better with guidance from PM.

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 6]
```diff
@@ -368,40 +371,87 @@ export abstract class AzureAuth implements vscode.Disposable {
...
+			return refreshResponse;
 		} catch (err) {
 			const msg = localize('azure.noToken', "Retrieving the Azure token failed. Please sign in again.");
 			vscode.window.showErrorMessage(msg);
 			throw new Error(err);
 		}
 	}
 
+	private async openConsentDialog(tenantId: string, resourceId: string): Promise<boolean> {
+		return new Promise((resolve) => {
```
Comment (aaomidi) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:426]: I've been unable to test this since I never hit this condition. If anyone here knows the UI code, please check on this part of the code :)

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 7]
```diff
@@ -368,40 +371,87 @@ export abstract class AzureAuth implements vscode.Disposable {
...
+				refreshResponse = { accessToken, refreshToken, tokenClaims, expiresOn };
+			} catch (ex) {
+				if (ex?.response?.data?.error === 'interaction_required') {
+					const shouldOpenLink = await this.openConsentDialog(tenant, resourceId);
+					if (shouldOpenLink === true) {
+						const { tokenRefreshResponse, authCompleteDeferred } = await this.promptForConsent(resourceEndpoint, tenant);
+						refreshResponse = tokenRefreshResponse;
+						authCompleteDeferred.resolve();
+					} else {
+						vscode.window.showInformationMessage(localize('azure.noConsentToReauth', "The authentication failed since ADS was unable to open re-authentication page."));
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:409]: Usually we use the full product name instead of acronym

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts (hunk 6 above)
Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:426]: What if you just hardcoded the checks to go to this path for testing? That's what I usually do

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 8]
```diff
@@ -368,40 +371,87 @@ export abstract class AzureAuth implements vscode.Disposable {
...
+	private async openConsentDialog(tenantId: string, resourceId: string): Promise<boolean> {
+		return new Promise((resolve) => {
+			// 20 second timeout just in case something happens.
+			const timer = setTimeout(() => {
+				resolve(false);
+			}, 20 * 1000);
+
+			const dialogTitle = localize('azurecore.consentDialog.title', "Authentication Consent Confirmation");
+			const dialogBody = localize('azurecore.consentDialog.body', "Your tenant {0} requires you to re-authenticate again to access {1} resources. Press OK to start the authentication process.", tenantId, resourceId);
+			const dialog = azdata.window.createModelViewDialog(dialogTitle, 'azureCore.consentDialog');
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:434]: ModelViewDialog seems pretty overkill for this - why not just use showInformationMessage? 

https://github.com/microsoft/azuredatastudio/blob/master/src/vs/vscode.d.ts#L7351

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts (hunk 7 above)
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:409]: This message doesn't seem to indicate what happened here to me - isn't the real issue is that they didn't accept the consent request?

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts (hunk 8 above)
Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:434]: Is there a way to make the user have to press okay or something?

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts (hunk 7 above)
Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:409]: Essentially I don't want it to be a jarring experience of you're working with ADS and suddenly your browser opens to a sign in page .

I want to ask the user permission before opening it saying hey we're about to open a browser to sign you in, are you okay with that.

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts (hunk 8 above)
Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts]: Yes there is.

Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts]: How are you opening the web page? You could also use the opener service which would prompt for you. Granted it's not as descriptive/friendly as this but something to consider.

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts (hunk 7 above)
Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts]: Yeah so that's fine and I agree - I just don't know if the information message here really meshes with what happened. Because in this case the user specifically said "no, I don't want to open this page" right? In that case do we even need to pop up a separate error? Couldn't the consent dialog just say "if you don't do this you won't be able to authenticate"?

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts (hunk 8 above)
Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts]: Being as this is from an extension openExternalUrl should go through that IIRC

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts (hunk 7 above)
Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts]: Yeah I have no opinions on the wording of this. I'll try to get PM looped in to tell me too :)
