### PR TITLE
BDC Dashboard fixes

### LINKED ISSUE #7399: BDC status dot is not aligned
Offset slightly from text

### LINKED ISSUE #7638: BDC Dashboard Refresh button doesn't have indication refresh is occurring
After clicking refresh on the BDC Dashboard there's no indication a refresh is happening which makes it difficult to know that it worked.

### LINKED ISSUE #7725: BDC Dashboard toolbar buttons are misaligned
image

### LINKED ISSUE #7726: BDC Dashboard tab headers don't have the correct pointer
They should have the hand pointer to indicate they're clickable but currently they're just the regular mouse pointer

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7399 

image

Fixes #7726

screen

Fixes #7725

I also made the icons a little bigger since they were pretty tiny by default

image

Partial fix for #7638

refresh

### CODE REVIEW

File: extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts [hunk 1]
```diff
@@ -65,19 +65,23 @@ export class BdcDashboard {
...
-					iconPath: IconPathHelper.refresh,
-					height: '50px'
+					iconPath: IconPathHelper.refresh
 				}).component();
 
-			refreshButton.onDidClick(() => this.model.refresh());
+			refreshButton.onDidClick(async () => {
+				refreshButton.iconPath = IconPathHelper.refresh_rotate;
+				refreshButton.enabled = false;
+				await this.model.refresh();
```
Comment (kevcunnane) [inline extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts]: What if this errors? Do we need to try/catch?

Comment (kevcunnane) [reply extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboard.ts]: Also, could we put this onclick handling logic in a separate method? Would make it easier to test in the future when we focus on code coverage.

File: src/sql/workbench/browser/modelComponents/media/toolbarLayout.css [hunk 2]
```diff
@@ -50,8 +50,8 @@
 }
 
 .modelview-toolbar-container .modelview-toolbar-component modelview-button .monaco-text-button.icon {
-	padding-left: 15px;
-	background-size: 11px;
+	padding-left: 19px;
```
Comment (kevcunnane) [inline src/sql/workbench/browser/modelComponents/media/toolbarLayout.css]: Does this align with what we have in the Notebook toolbar? Long term it'd be great if these could share identical CSS at least.

File: src/sql/workbench/browser/modelComponents/media/toolbarLayout.css [hunk 3]
```diff
@@ -50,8 +50,8 @@
...
+	background-size: 15px;
```
Comment (alanrenmsft) [inline src/sql/workbench/browser/modelComponents/media/toolbarLayout.css]: which features are using now? need to make sure the feature owners are aware of this.

File: src/sql/workbench/browser/modelComponents/media/toolbarLayout.css (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/media/toolbarLayout.css]: Unfortunately it looks like no - that uses the carbon taskbar styles https://github.com/microsoft/azuredatastudio/blob/db498db0a82564fb4e813b794b16c73d5d8db0eb/src/sql/base/browser/ui/taskbar/media/taskbar.css#L47 so there isn't really anything shared there at the moment. Would be nice to align on this though in the future, I agree.

File: src/sql/workbench/browser/modelComponents/media/toolbarLayout.css (hunk 3 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/media/toolbarLayout.css]: The only other place I see this being used in our repo is schema compare and that looks fine 

image

For comparison here's how it looks right now :
image

@kisantia @udeeshagautam - FYI in case you see anything looking off or don't think the larger icons are appropriate.

**Comment by Charles-Gagnon** [comment]
FYI - per feedback from @angdesign I'm removing the animated refresh button - we want to align on refresh behavior and so I'll be working on that later on. I'm still keeping the disabling of the button while the refresh is happening though so the user gets some feedback that something is happening.
