### PR TITLE
use native win-arm64 STS builds

### LINKED ISSUE #1774: Currently there is no version (x86-32 bit or ARM64) available for ARM64 PCs
- SQL Operations Studio Version:

Steps to Reproduce:

Always connected ARM64 PCs could be useful devices for SQL admins if supported

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #1774

Previously we have added the ARM64 version of Azure Data Studio on Windows, and the backend service is still x64 binaries, with this PR, the STS is also native arm64 binaries.
image

### CODE REVIEW

File: extensions/mssql/build/postinstall.js [hunk 1]
```diff
@@ -15,15 +15,6 @@
 	async function installService() {
 		const absoluteConfigPath = require.resolve('../config.json');
 		const config = require(absoluteConfigPath);
-		let runtime = (await platform.PlatformInformation.getCurrent()).runtimeId;
```
Comment (alanrenmsft) [inline extensions/mssql/build/postinstall.js:18]: this is removed because I've added the runtime override support in the ads-service-downloader package. we just need to specify the AZDATA_RUNTIME in the yml file.

File: extensions/mssql/yarn.lock [hunk 2]
```diff
@@ -189,10 +189,10 @@
   dependencies:
     "@vscode/extension-telemetry" "0.6.1"
 
-"@microsoft/ads-service-downloader@^1.1.0":
-  version "1.1.0"
-  resolved "https://registry.yarnpkg.com/@microsoft/ads-service-downloader/-/ads-service-downloader-1.1.0.tgz#c51ba28bc17a137e92f99a2b050821965588d7d6"
-  integrity sha512-WSJ4NZvpuebg/CjlTUpqXPUYV5y5mSNJQE/dd+kuOt0nkMYzCmp5IYyFFpMFUR1CiZy/19V7DH2wGdy60+9SRg==
+"@microsoft/ads-service-downloader@^1.2.0":
```
Comment (Charles-Gagnon) [inline extensions/mssql/yarn.lock:192]: I'd suggest also updating all the other extensions that use the service downloader as well, keeping everything in sync is typically a good idea to ensure consistent behavior.

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/mssql/yarn.lock (hunk 2 above)
Comment (alanrenmsft) [reply extensions/mssql/yarn.lock:192]: sounds reasonable. I've updated other extensions using this package and updated the config file so that they will work just like before.

**Review by aasimkhan30 — APPROVED** [review]

**Review by kburtram — APPROVED** [review]
