### PR TITLE
Fix ModelView tree A11y issue

### LINKED ISSUE #6153: [Accessibility]A11y_AzureDataStudio_MapDataSrcObjects_Keyboard: On expanding tree view items with the help enter key ,keyboard focus directly shift to the fifth "Summary" screen.
[Check out Keros!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags: #A11yMAS; #A11yTCS; #MAS3.3.2; #A11y_AzureDataStudio; #Win32; #DesktopApp

**Environment Details:**
Application name: Azure Data Studio
Version: 1.9.0-insider (user setup)
Commit: 2ca39b5
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS :Windows_NT x64 10.0.18362

**Additional Details:**
Tools Name: Keyboard
MAS References: MAS3.2.2

**Steps to Reproduce:**
1. Install the app Azure Data Studio.
2. Enable SQL server2019 preview->select table from the database->Create External Table screen should open->Next button->Create Database Master Key screen should open->click on next button->fill all the required details->click on next button.
3. Select any tree view item from left panel using arrow key and press enter.
4. Observe that keyboard focus directly shift to fifth "Summary" screen. 

**Actual:**
On expanding tree view items with the help enter key ,keyboard focus directly shift to the fifth "Summary" screen. 

**Expected:**
On expanding tree view items with the help enter key ,keyboard focus remains on the same screen .

**User Impact:**
Keyboard user will get confuse with the unauthorize behaviour of the expand tree view, because when user expand any tree item and enter he will redirect to the next page and content on the first page will miss out. 

**Recommendation:**
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference :
MAS3.2.2:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={24cbfff7-374e-42e6-b9ab-d87fcd53b3e8}

**Attachment for Reference:**
[6153_[Accessibility]A11y_AzureDataStudio_MapDataSrcObjects_Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3324797/6153_.Accessibility.A11y_AzureDataStudio_MapDataSrcObjects_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #6153

This will apply to all ModelView trees, but I feel like that's the correct behavior - that if enter is pressed while a tree is focused it shouldn't go outside of the tree regardless of what it's contained in.

refresh

### CODE REVIEW

File: src/sql/workbench/browser/modelComponents/tree.component.ts [hunk 1]
```diff
@@ -160,4 +171,8 @@ export default class TreeComponent extends ComponentBase implements IComponent,
 	public set withCheckbox(newValue: boolean) {
 		this.setPropertyFromUI<azdata.TreeProperties, boolean>((properties, value) => { properties.withCheckbox = value; }, newValue);
 	}
+
+	private onkeydown(domNode: HTMLElement, listener: (e: IKeyboardEvent) => void): void {
```
Comment (alanrenmsft) [inline src/sql/workbench/browser/modelComponents/tree.component.ts]: seems not necessary to have this method. you can directly do this._regoster... there

Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/tree.component.ts]: Eh, true. Just got lazy copying from other components. TBH I think it'd be better just to have this be on the ComponentBase class instead since there's going to be a bunch of components that use it. Thoughts on that?

Comment (alanrenmsft) [reply src/sql/workbench/browser/modelComponents/tree.component.ts]: sounds like the right thing to do.

File: src/sql/workbench/browser/modelComponents/tree.component.ts [hunk 2]
```diff
@@ -119,6 +121,15 @@ export default class TreeComponent extends ComponentBase implements IComponent,
 			this._register(this._tree.onDidChangeSelection(e => {
 				this._dataProvider.onNodeSelected(e.selection);
 			}));
+			this.onkeydown(this._inputContainer.nativeElement, (e: StandardKeyboardEvent) => {
+				// Enter on a tree will select the currently selected item as the default behavior
+				// but if not stopped here then will propagate up.
+				// This might have unintended effects such as a dialog closing.
+				if (e.keyCode === KeyCode.Enter) {
+					this._tree.toggleExpansion(this._tree.getFocus());
```
Comment (udeeshagautam) [inline src/sql/workbench/browser/modelComponents/tree.component.ts]: toggleExpansion... does that mean we will close too if its already opened, I don't have any specific case against that but might be bit confusing to user. What do you say?

Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modelComponents/tree.component.ts]: Yup. That's the current behavior for OE and seems like the correct way to handle that to me. Easy change if we think just opening is the correct way - I'll run it by the accessibility team.
