### PR TITLE
Fix active cell update on tabbing 

### LINKED ISSUE #18274: Notebook keyboard navigation is broken when tab navigating into a code cell
1. Create Notebook with a couple of code cells
2. Click to select one (pressing esc if necessary to get into "browse" mode)
3. Press tab/shift+tab to keyboard navigate around the focusable elements on the Notebook until you hit a code editor

The cursor then goes into the editor and you can type like normal, but the other "active" cell is still highlighted and the up/down arrows still move the active cell (even though the cursor is active in the code cell)

We should make sure to be updating the active state correctly - if the focus leaves the cell then it seems like we should also be removing the active state (and clearing the current active cell)

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR addresses part of the issue #18274, it only fixes the tabbing forward scenario. 

tabbingInCell

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 1]
```diff
@@ -455,6 +455,7 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 		this._register(this._model.contentChanged((change) => this.handleContentChanged(change)));
 		this._register(this._model.onProviderIdChange((provider) => this.handleProviderIdChanged(provider)));
 		this._register(this._model.kernelChanged((kernelArgs) => this.handleKernelChanged(kernelArgs)));
+		this._register(this._model.onActiveCellChanged(() => this.detectChanges()));
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:458]: Are there other places where we call detectChanges in this file on active cell being changed? I'd like to avoid calling `detectChanges()` multiple times when active cell is changed.

If we're just reacting to this event coming from the model, can we remove other calls to `detectChanges()`?

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html [hunk 2]
```diff
@@ -4,7 +4,7 @@
  *  Licensed under the Source EULA. See License.txt in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
 -->
-<div style="width: 100%; height: 100%; display: flex; flex-flow: column" (mouseover)="hover=true" (mouseleave)="hover=false">
+<div tabindex="0" style="width: 100%; height: 100%; display: flex; flex-flow: column" (mouseover)="hover=true" (mouseleave)="hover=false" (focus)="updateActiveCell()">
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html:7]: This should likely have an aria-label if it's going to be tab-focusable now. Make sure you're checking with a screen reader that it's announcing something useful (like "text cell #" where number is the index in the Notebook)

File: src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts [hunk 3]
```diff
@@ -111,6 +111,9 @@ export class CodeComponent extends CellView implements OnInit, OnChanges {
 	}
 
 	ngOnInit() {
+		this._register(DOM.addDisposableListener(this.toolbarElement.nativeElement, DOM.EventType.FOCUS_IN, () => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts:114]: Why not put the listener in the component HTML instead? It'd be nice to be consistent where we can.

**Review by Charles-Gagnon — COMMENTED** [review]
Did you make sure to test tabbing backwards as well?

File: src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts (hunk 3 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts:114]: I think we might need to add the listener to the textCell.component as well right?

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts:114]: yeah I did that and it wasn't working as expected and there were no errors on the console either, so went back to adding the listener in the code.

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/cellViews/code.component.ts:114]: > I think we might need to add the listener to the textCell.component as well right?

@barbaravaldez no, since we added the focus listener on the HTML to call updateActiveCell.

**Comment by MaddyDev** [comment]
> Did you make sure to test tabbing backwards as well?

It is still wonky when tabbing backwards. It doesn't toggle backward across all the elements like it does forward, it just loops between first two elements backward. Still looking into that.

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html [hunk 4]
```diff
@@ -4,7 +4,7 @@
  *  Licensed under the Source EULA. See License.txt in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
 -->
-<div style="width: 100%; height: 100%; display: flex; flex-flow: column" (mouseover)="hover=true" (mouseleave)="hover=false">
+<div tabindex="0" style="width: 100%; height: 100%; display: flex; flex-flow: column" (mouseover)="hover=true" (mouseleave)="hover=false" (focus)="updateActiveCell()" aria-label="Markdown cell">
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html:7]: 1. Aria labels need to be localized
2. For lists of items (i.e. the cells in this case) we should also be announcing the index. For example - when navigating through a Notebook it should announce something like this

"Markdown Cell 1"
"Code Cell 2"
"Code Cell 3"
"Markdown Cell 4"

Now I'm going to guess that we aren't doing anything like that now for our cells, in which case you can talk to @chlafreniere and figure out a plan for how/when we want to fix that. It might be something that is done later as part of a round of a11y work.

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.html]: @chlafreniere  What do you think, do you want me address it as part of this PR? I agree with @Charles-Gagnon, I can create a bug to track it and we can address it as part of a round of a11y work?

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 5]
```diff
@@ -343,7 +342,16 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
...
+	}
+
+	public updateActiveCell(cell: ICellModel) {
+		if (this._model.activeCell !== cell) {
+			this._model.updateActiveCell(cell);
+		}
+	}
+
+	public getNotebookCellLabel(cell: ICellModel): string {
+		return localize('notebookCelllabel', "{0} {1}", cell.cellType === CellTypes.Code ? 'Code Cell' : 'Markdown Cell', cell.id);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:354]: You should be localizing "Code Cell" and "Markdown Cell" - just having the localize string be {0} {1} isn't actually doing anything.

But also - the cells themselves should have their labels. This shouldn't be the job of the Notebook component. This should just call cell.label or something.

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 6]
```diff
@@ -343,7 +342,16 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 
 	public unselectActiveCell() {
 		this.model.updateActiveCell(undefined);
-		this.detectChanges();
+	}
+
+	public updateActiveCell(cell: ICellModel) {
+		if (this._model.activeCell !== cell) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:348]: The model should have this check too - which means you should be able to remove this check.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
Please update the gif in the description with the latest changes. (make sure to include tabbing forward and backwards)

File: src/sql/workbench/services/notebook/browser/models/cell.ts [hunk 7]
```diff
@@ -116,6 +117,11 @@ export class CellModel extends Disposable implements ICellModel {
 		}
 		// if the fromJson() method was already called and _cellGuid was previously set, don't generate another UUID unnecessarily
 		this._cellGuid = this._cellGuid || generateUuid();
+		if (this._cellType === 'code') {
+			this.cellLabel = localize('codeCellLabel', "Code Cell {0}", this.id);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/cell.ts:121]: I don't think ID is appropriate here since that's just a random number. Generally for lists of objects like this you would announce the index and then the label (which would just be "Code Cell" or "Markdown Cell"). But getting this working correctly is likely out of scope for this PR so I guess this is fine - just putting this here for future reference. 

Although for code cells we should probably be saying the language as well.

**Comment by barbaravaldez** [comment]
Tested and looks good! I found an issue when entering a code cell editor, the cell's edit mode is not changed unless I tab again and the contents are modified.

**Comment by MaddyDev** [comment]
@barbaravaldez Could you log an issue for the code cell issue you mentioned, looks like it's a different issue than what am addressing here. Also can you check if it's regression ? Thanks!!

**Comment by Charles-Gagnon** [comment]
If it's not a regression (it's an issue with this PR) then I don't think a separate issue is necessary. That should be fixed before this goes in.

**Comment by barbaravaldez** [comment]
> @barbaravaldez Could you log an issue for the code cell issue you mentioned, looks like it's a different issue than what am addressing here. Also can you check if it's regression ? Thanks!!

@MaddyDev this is not a regression because we didn't change the cell edit mode when tabbing before

**Comment by MaddyDev** [comment]
> > @barbaravaldez Could you log an issue for the code cell issue you mentioned, looks like it's a different issue than what am addressing here. Also can you check if it's regression ? Thanks!!
> 
> @MaddyDev this is not a regression because we didn't change the cell edit mode when tabbing before

But am not doing anything with the edit mode here, am just setting the cell as active on focus. Can you explain me more whats the expected experience and what's the regression you're seeing?

**Review by Charles-Gagnon — APPROVED** [review]

**Review by barbaravaldez — APPROVED** [review]
