### PR TITLE
fix json cell handling issue

### LINKED ISSUE #17634: Clicking on results containing JSON does not open new document when some rows have NULL
```
Version: 1.33.1 (user setup)
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:45:15.872Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. I run a very simple query that does a select <JsonStringColumn> from <table>. 
2. The results have a column which contains JSON
3. If the results include rows where the JSON field is NULL, then clicking on the results that DO have JSON in them don't open a new window  with the formatted results. 
4. If you select exclusivly rows that DON'T have nulls in the JSON column, then the click works fine

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #17634

instead of relying on STS to do the JSON check only on the first row: https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/ResultSet.cs#L740, I am moving the logic to ADS, when a cell is clicked, we check whether it is a json cell and then open a new editor for it.

similarly render the cell as hyperlink if it is a json cell.

before:
json-before

after:
json-after

### CODE REVIEW

File: src/sql/workbench/contrib/query/browser/gridPanel.ts [hunk 1]
```diff
@@ -65,6 +65,8 @@ const ACTIONBAR_HEIGHT = 120;
 // this handles min size if rows is greater than the min grid visible rows
 const MIN_GRID_HEIGHT = (MIN_GRID_HEIGHT_ROWS * ROW_HEIGHT) + HEADER_HEIGHT + ESTIMATED_SCROLL_BAR_HEIGHT;
 
+const IsJsonRegex = /({.*?})/g;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/query/browser/gridPanel.ts:68]: What about text values that contain { } in them but aren't valid JSON? I feel like it'd be better to try and parse it as JSON instead to test, although we might start having perf issues if we're doing that for large blobs of data...

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:68]: And even if you keep this logic, you're removing the check for the column data type being nvarchar which could cause problems too

Comment (alanrenmsft) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:68]: The purpose of this feature is to allow user to see the json content in a separate editor, as a result:
1. it doesn't need to be very accurate, using the regex is definitely much more performant than actually parsing it. so I think a minimum check is good enough.
2. nvarchar column type check is not required, we should allow user to view  the json data regardless of the type.

this is what I think. @Charles-Gagnon  @kburtram what do you think?

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:68]: Alright, guess this is enough of an improvement and there isn't any better solution I can come up with that this seems fine for now. Please add comments explaining this though so it's clear that we're just doing a "best low-cost effort" here and not trying to be 100% accurate.

File: src/sql/workbench/contrib/query/browser/gridPanel.ts [hunk 2]
```diff
@@ -395,15 +397,15 @@ export abstract class GridTableBase<T> extends Disposable implements IView {
 		this.container.style.height = '100%';
 
 		this.columns = this.resultSet.columnInfo.map((c, i) => {
-			let isLinked = c.isXml || c.isJson;
+			let isLinked = c.isXml;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/query/browser/gridPanel.ts:400]: Might as well just remove this and use c.isXml directly below

(something to consider would be to have the queryResultTextFormatter always be used and just check in there whether the column is XML, but no big preference on my end)

File: src/sql/workbench/contrib/query/browser/gridPanel.ts [hunk 3]
```diff
@@ -693,17 +695,20 @@ export abstract class GridTableBase<T> extends Disposable implements IView {
...
 			const subset = await this.getRowData(event.cell.row, 1);
-			let value = subset[0][event.cell.cell - 1];
-			let content = value.displayValue;
-			const input = this.untitledEditorService.create({ mode: column.isXml ? 'xml' : 'json', initialValue: content });
-			await input.resolve();
-			await this.instantiationService.invokeFunction(formatDocumentWithSelectedProvider, input.textEditorModel, FormattingMode.Explicit, Progress.None, CancellationToken.None);
-			input.setDirty(false);
-			await this.editorService.openEditor(input);
+			const value = subset[0][event.cell.cell - 1];
+			const isJson = isJsonCell(value);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/query/browser/gridPanel.ts:703]: Can you instead stick a property on the cell to tell us whether it's JSON or not? Avoid having to recheck the cell every time it's clicked.

File: src/sql/workbench/contrib/query/browser/gridPanel.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:68]: I'd also definitely suggest adding appropriate documentation to the STS code making it clear that it only checks the first row currently. 

And this might be a good time to look at the extension API and try to figure out why we even have the IDbColumn and IGridResult interfaces there. They only seem to be used internally currently.

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/query/browser/gridPanel.ts (hunk 2 above)
Comment (alanrenmsft) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:400]: the isXml information is available in the columnInfo but not the slickgrid's columnDefinition, If I always use the new formatter, the isXml information needs to be retrieved from the resultSet.columnInfo again. so I am going to leave it as is.

**Comment by chlafreniere** [comment]
Does this also affect the vscode-mssql?

File: src/sql/workbench/contrib/query/browser/gridPanel.ts (hunk 3 above)
Comment (alanrenmsft) [reply src/sql/workbench/contrib/query/browser/gridPanel.ts:706]: slickgrid is not caching the value associated with a cell, so we have to retrieve it anyway.

**Comment by alanrenmsft** [comment]
> Does this also affect vscode-mssql?

@chlafreniere let me check.

**Comment by alanrenmsft** [comment]
@chlafreniere the issue also exist in vscode-mssql extension, I opened an issue there to track it: https://github.com/microsoft/vscode-mssql/issues/17334
