### PR TITLE
Remove extra filter icon from Top Operations tab

### LINKED ISSUE #23611: Top Operations Filter Icon is appearing incorrectly
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Launch ADS
2. Generate an actual execution plan for any query
3. Open the Top Operations tab
4. In the top operations tab, above the table where the query appears, the filter icon is rendering over the query.
image

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #23611

This PR removes an additional filter icon that didn't do anything and would appear over a query:
Now:
image

Before:
image

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]

**Review by kisantia — APPROVED** [review]

File: src/sql/workbench/contrib/executionPlan/browser/topOperationsTab.ts [hunk 1]
```diff
@@ -178,7 +178,6 @@ export class TopOperationsTabView extends Disposable implements IPanelView {
 
 		const headerSearchBarContainer = DOM.$('.top-operations-header-search-bar');
 		headerContainer.appendChild(headerSearchBarContainer);
-		headerContainer.classList.add('codicon', filterIconClassNames);
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/executionPlan/browser/topOperationsTab.ts:181]: what was this supposed to do? was this misplaced here?
