### PR TITLE
fix projects notification showing when it shouldn't

### LINKED ISSUE #15889: Projects notification showing when it shouldn't
This "current workspace contains not added projects" notification is showing in a couple scenarios when it shouldn't
image

1. When creating a new project that also creates a new workspace
2. Windows when any workspace is opened or project added

workaround: have this notification turned off in the settings

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #15889. 

Fixing 2 problems:
1. When creating a new project that also creates a new workspace, ADS restarts to create and enter the new workspace and the project gets added to the workspace when the extension activates. This part wasn't being awaited, so sometimes the check for not added projects was seeing that the newly added workspace folder, but it was before the project was added to the workspace. 
2. Glob returns forward slash paths, so this was notification was always showing on windows because those forward slash paths were being compared to the project paths in the workspace file which have backslashes on windows.

### CODE REVIEW

**Review by udeeshagautam — APPROVED** [review]
Thanks for fixing it so quickly!

File: extensions/data-workspace/src/services/workspaceService.ts [hunk 1]
```diff
@@ -229,7 +234,8 @@ export class WorkspaceService implements IWorkspaceService {
 		// so the filter needs to be in the format folder/**/*.sqlproj if there's only one supported projectextension
 		const projFilter = supportedProjectExtensions.length > 1 ? path.posix.join(escapedPath, '**', `*.{${supportedProjectExtensions.toString()}}`) : path.posix.join(escapedPath, '**', `*.${supportedProjectExtensions[0]}`);
 
-		return await glob(projFilter);
+		// glob will return an array of file paths with forward slashes, so they need to be converted back if on windows
+		return (await glob(projFilter)).map(p => folder.fsPath.includes('\\') ? p.split('/').join('\\') : p);
```
Comment (alanrenmsft) [inline extensions/data-workspace/src/services/workspaceService.ts:238]: is this really safe? '\' is a valid character for path on Linux.

Comment (Charles-Gagnon) [reply extensions/data-workspace/src/services/workspaceService.ts:238]: You should be able to just use path.resolve

**Review by Charles-Gagnon — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]
