### PR TITLE
Fix extension recommendations

### LINKED ISSUE #14250: Extension recommendation isn't working
Insiders/main

1. Make sure SandDance extension isn't installed
1. Run SQL query
1. Click "Chart" button on results tab

Expected : Prompt displayed asking if user wants to install Visualizer extensions

Actual : No prompt

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #14250

The VS changes are updating it to bring in the latest changes on the VS Code side. I verified that the scenario and static recommendation features still work as expected.

Do note that currently we are not respecting the `Ignore Recommendations` setting. But this is behavior that currently exists in stable so I'm not going to fix that here - opened issue for tracking that https://github.com/microsoft/azuredatastudio/issues/14274

Scenario : Showing recommendations and installing : 
Capture

Scenario : Ignoring recommendation prompt
Recommendation_NoShow

Static : Gallery shows static recommendations 

image

Static : Ignore recommendations

Static_IgnoreRecommendation

### CODE REVIEW

File: src/vs/workbench/contrib/extensions/browser/extensionRecommendations.ts [hunk 1]
```diff
@@ -1,52 +1,21 @@
 /*---------------------------------------------------------------------------------------------
  *  Copyright (c) Microsoft Corporation. All rights reserved.
- *  Licensed under the Source EULA. See License.txt in the project root for license information.
+ *  Licensed under the MIT License. See License.txt in the project root for license information.
```
Comment (kburtram) [inline src/vs/workbench/contrib/extensions/browser/extensionRecommendations.ts:3]: We should keep the old copyright header

**Review by kburtram — APPROVED** [review]

**Review by chlafreniere — APPROVED** [review]
