### PR TITLE
check for encoded components

### LINKED ISSUE #17662: Editor insert/edit link is broken for links that have % in them
- Azure Data Studio Version: 1.33.1 (user setup)
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Create a link in the editor with a percent '%' sign. E.g., https://github.com/search/advanced?q=test&r=microsoft%2Fazuredatastudio&type=Code.
image

Expectation: 
Browser opens with the url https://github.com/search/advanced?q=test&r=microsoft%2Fazuredatastudio&type=Code

Result:
Browser opens with the re-encoded '%' as '%25' https://github.com/search/advanced?q=test&r=microsoft%252Fazuredatastudio&type=Code

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #17662 

As the issue states if user enters an encoded url such as https://github.com/search/advanced?q=test&r=microsoft%2Fazuredatastudio&type=Code we re-encode it and show it as https://github.com/search/advanced?q=test&r=microsoft%252Fazuredatastudio&type=Code.

In this PR, I've added a check to see if the url has encoded components using an example method from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent .

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 1]
```diff
@@ -118,6 +118,20 @@ export class NotebookLinkHandler {
 		}
 	}
 
+	public getEncodedLinkUrl(linkUrl: string): string {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:121]: These don't need to be a part of the class - just have them be module level functions

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 2]
```diff
@@ -118,6 +118,20 @@ export class NotebookLinkHandler {
...
+		// Need to encode URI here in order for user to click the proper encoded link in WYSIWYG
+		// skip encoding it if it's already encoded
+		if (!this.containsEncodedComponents(linkUrl)) {
+			return encodeURI(linkUrl);
+		}
+		return linkUrl;
+	}
+
+	public containsEncodedComponents(url) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:130]: Please add a doc comment explaining what this is doing (for example - what is a "component" in this case)

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 3]
```diff
@@ -278,7 +278,7 @@ export class MarkdownToolbarComponent extends AngularDisposable {
 				// Otherwise, re-focus on the output element, and insert the link directly.
 				this.output?.nativeElement?.focus();
 				// Need to encode URI here in order for user to click the proper encoded link in WYSIWYG
-				let encodedLinkURL = encodeURI(linkUrl);
+				let encodedLinkURL = notebookLink.getEncodedLinkUrl(linkUrl);
 				document.execCommand('insertHTML', false, `<a href="${encodedLinkURL}" title="${encodedLinkURL}" is-encoded="true" is-absolute=${notebookLink.isAbsolutePath}>${escape(linkCalloutResult?.insertUnescapedLinkLabel)}</a>`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:282]: The title probably shouldn't be the encoded URI right? We want to show them the original link text

File: src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts [hunk 4]
```diff
@@ -103,4 +103,15 @@ suite('Noteboook Link Handler', function (): void {
...
+
+	test('Should return correctly encoded url/filePath', () => {
+		let result = new NotebookLinkHandler(notebookUri, 'https://github.com/search/advanced?q=test&r=microsoft%2Fazuredatastudio&type=Code', configurationService);
+		assert.strictEqual(result.getEncodedLinkUrl(result.getLinkUrl()), `https://github.com/search/advanced?q=test&r=microsoft%2Fazuredatastudio&type=Code`, 'HTTPS link encoding failed');
+
+		result = new NotebookLinkHandler(notebookUri, 'https://github.com/search/advanced?q=test&r=(microsoft%2Fazuredatastudio)&type=Code', configurationService);
+		assert.strictEqual(result.getEncodedLinkUrl(result.getLinkUrl()), `https://github.com/search/advanced?q=test&r=(microsoft%2Fazuredatastudio)&type=Code`, '() in HTTP link failed to resolve');
+
+		result = new NotebookLinkHandler(notebookUri, 'https://github.com/search/advanced?q=test&r=(microsoft/azuredata studio)&type=Code', configurationService);
+		assert.strictEqual(result.getEncodedLinkUrl(result.getLinkUrl()), `https://github.com/search/advanced?q=test&r=(microsoft/azuredata%20studio)&type=Code`, 'space failed to be encoded failed');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts:115]: Add tests that test passing in an already-encoded URI

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts:115]: the first test is that, passing in the already encoded '/' as %2F in the URL and checking that it's not re-encoding the % in it.

File: src/sql/workbench/contrib/notebook/browser/utils.ts [hunk 5]
```diff
@@ -44,3 +44,18 @@ export function highlightSelectedText(): void {
 	}
 }
 
+export function getEncodedLinkUrl(linkUrl: string): string {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/utils.ts:47]: I think it'd be better to keep all link encoding/decoding logic in one place - so the handler class seems like a good place to do that. 

So for now to help ensure that I'd actually suggest that we move this function into the link handler and take away the parameter, instead just using the URL that was passed into the constructor.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 6]
```diff
@@ -118,6 +118,25 @@ export class NotebookLinkHandler {
...
+				return encodeURI(this._link);
+			}
+			return this._link;
+		}
+		return undefined;
+	}
+
+	// returns true if the passed in url has encoded strings:
+	// space gets encoded as %20 and ;,/?:@&=+$ -> %3B%2C%2F%3F%3A%40%26%3D%2B%24
+	containsEncodedComponents(url): boolean {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:135]: 1. This should still be outside the class - and TBH I'd suggest make a `src/sql/base/common/network.ts` file and putting it there since it's a pretty generic thing
2. Please use valid JS doc (/** ... */) comments
3. I'm not really understanding the second part - this isn't actually encoding anything so not sure how it matters. You should be defining what an "encoded string" is and a quick description of how it detects that.

File: src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts [hunk 7]
```diff
@@ -103,4 +103,31 @@ suite('Noteboook Link Handler', function (): void {
...
+
+	test('Should return correctly encoded url/filePath', () => {
+		test('when given an already-encoded URL', () => {
+			let notebookLinkHandler = new NotebookLinkHandler(notebookUri, 'https://github.com/search/advanced?q=test&r=microsoft%2Fazuredatastudio&type=Code', configurationService);
+			assert.strictEqual(notebookLinkHandler.getEncodedLinkUrl(), `https://github.com/search/advanced?q=test&r=microsoft%2Fazuredatastudio&type=Code`, 'HTTPS link does not need encoding');
+		});
+
+		test('when given an already encoded URL with non-reserved characters', () => {
+			let notebookLinkHandler = new NotebookLinkHandler(notebookUri, 'https://github.com/search/advanced?q=test&r=(microsoft%2Fazuredatastudio)&type=Code', configurationService);
+			assert.strictEqual(notebookLinkHandler.getEncodedLinkUrl(), `https://github.com/search/advanced?q=test&r=(microsoft%2Fazuredatastudio)&type=Code`, '() in HTTP link failed to resolve');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts:115]: Not sure what "resolve" is supposed to mean here.

and in general for all of these it's probably fine just to just remove the message completely. It doesn't really add much information since the test is extremely simple and each one is now only testing 1 thing.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 8]
```diff
@@ -118,6 +118,25 @@ export class NotebookLinkHandler {
...
+	public getEncodedLinkUrl(): string | undefined {
+		// Need to encode URI here in order for user to click the proper encoded link in WYSIWYG
+		// skip encoding it if it's already encoded
+		if (typeof this._link === 'string') {
+			if (!this.containsEncodedComponents(this._link)) {
+				return encodeURI(this._link);
+			}
+			return this._link;
+		}
+		return undefined;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:130]: I'd suggest adding a comment here about why you're returning undefined (I assume it's because there's no need to implement this currently?)

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 9]
```diff
@@ -118,6 +118,25 @@ export class NotebookLinkHandler {
 		}
 	}
 
+	public getEncodedLinkUrl(): string | undefined {
```
Comment (VasuBhog) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:121]: Would be good to add JS doc for this function

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 8 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:130]: yes, we're only handling strings from the link call out dialog.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 10]
```diff
@@ -118,6 +118,34 @@ export class NotebookLinkHandler {
 		}
 	}
 
+	/**
+	* Function to get encoded url,
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:122]: `Gets the link URI-encoded link URL (https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)`

(I don't think it's necessary to call out that we check it's already encoded - that is more of an implementation detail and should be assumed since not doing so would be a bug generally)

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 8 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:136]: Please add that as a comment in the code

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 11]
```diff
@@ -118,6 +118,34 @@ export class NotebookLinkHandler {
...
+			if (!this.containsEncodedComponents(this._link)) {
+				return encodeURI(this._link);
+			}
+			return this._link;
+		}
+		return undefined;
+	}
+
+	/**
+	* Function to check if a string url has encoded characters
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:140]:
```
Checks if the specified URL is already URI-encoded by checking if there are any uncoded reserved URI component characters (such as ?, =, &, /, etc.) in the URL. See https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent for more details.
@returns true if the URL contains encoded URI component reserved characters
```

I'd also make this clearer and update the signature to : 

`containsEncodedUriComponentReservedCharacters(url: string): boolean`

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:140]: And as mentioned I'd suggest making a new file at `src/sql/base/common/network.ts` and putting this in there so others can find it more easily.

**Review by Charles-Gagnon — APPROVED** [review]
Some more comments to look at addressing, but the rest of it looks good
