### PR TITLE
Fix search for pinned notebooks

### LINKED ISSUE #12459: In-Viewlet Notebook Search does not search in pinned notebooks
Searching in pinned notebooks is not supported.

### PR DESCRIPTION
**Pull request by barbaravaldez**
Most of the fix to allow search in pinned notebooks is located in the NotebookExplorerViewlet.
I had to modified how we stored pinned notebooks in workspace config, because the parent node in the search result would be the directory name of the notebook instead of the book root. 

If we pin a standalone notebook, then we use the directory name as the parent node.

**Image before modifying the workspace config.**

Screen Shot 2020-09-28 at 8 26 53 PM

**Image after modifying the workspace config.**

Screen Shot 2020-10-02 at 11 46 23 AM

This PR fixes #12459
Note: One of the functions that I removed from the BookPinManager had a duplicate in the utils file. So I decided to move everything related to modifying the workspace to utils, since it's used in other files, too.

### CODE REVIEW

File: extensions/notebook/src/book/bookModel.ts [hunk 1]
```diff
@@ -45,7 +46,7 @@ export class BookModel {
 		if (this.isNotebook) {
 			this.readNotebook();
 		} else {
-			await this.readBookStructure(this.bookPath);
+			await this.readBookStructure(this.bookPath as string);
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookModel.ts:49]: Why are you casting to a string? It already is one

File: extensions/notebook/src/book/bookPinManager.ts [hunk 2]
```diff
@@ -33,10 +33,7 @@ export class BookPinManager implements IBookPinManager {
 	}
 
 	isNotebookPinned(notebookPath: string): boolean {
-		if (getPinnedNotebooks().findIndex(x => x === notebookPath) > -1) {
-			return true;
-		}
-		return false;
+		return (getPinnedNotebooks().filter(function (x) { return x.notebookPath === notebookPath; }).length > 0);
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookPinManager.ts:36]: Any particular reason you made this into a function object? Lamba's are generally easier to read. Any why did you change the logic anyways? The old check seemed fine if you just updated it to be x.notebookPath

File: extensions/notebook/src/book/bookTreeView.ts [hunk 3]
```diff
@@ -216,9 +217,9 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 	 * were able to successfully parse it.
 	 * @param bookPath The path to the book folder to create the model for
 	 */
-	private async createAndAddBookModel(bookPath: string, isNotebook: boolean): Promise<void> {
+	private async createAndAddBookModel(bookPath: string, isNotebook: boolean, notebookBookRoot?: string): Promise<void> {
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts:220]: Update params

File: extensions/notebook/src/common/utils.ts [hunk 4]
```diff
@@ -325,16 +325,47 @@ export async function getRandomToken(size: number = 24): Promise<string> {
...
 }
 
-export function getPinnedNotebooks(): string[] {
+export function getPinnedNotebooks(): IBookNotebook[] {
 	let config: vscode.WorkspaceConfiguration = vscode.workspace.getConfiguration(notebookConfigKey);
-	let pinnedNotebooks: string[] = config.get(pinnedBooksConfigKey) ?? [];
+	let pinnedNotebooks: [] = config.get(pinnedBooksConfigKey);
+	let pinnedBookDirectories: IBookNotebook[] = [];
+	let updateFormat: boolean = false;
+	pinnedNotebooks.map((elem, index) => {
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/common/utils.ts:340]: Either use foreach or something like
```
const pinnedBookDirectories = pinnedNotebooks.map(elem => {
if(typeof(elem) === 'string') {
   updateFormat = true;
   return { notebookPath: elem, bookPath: '' };
} else {
   return elem as IBookNotebook;
});
```

Map should only be used if you're actually using the returned array - if not then forEach is better.

File: extensions/notebook/src/common/utils.ts [hunk 5]
```diff
@@ -325,16 +325,47 @@ export async function getRandomToken(size: number = 24): Promise<string> {
...
+	return pinnedBookDirectories;
+}
 
-	return pinnedNotebooks;
+function hasWorkspaceFolders(): boolean {
+	let workspaceFolders = vscode.workspace.workspaceFolders;
+	return workspaceFolders && workspaceFolders.length > 0;
 }
+
+export function setPinnedBookPathsInConfig(bookPaths: IBookNotebook[]) {
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/common/utils.ts:360]: Param name doesn't really match what the param actually is anymore

File: extensions/notebook/src/book/bookTreeItem.ts [hunk 6]
```diff
@@ -74,6 +75,7 @@ export class BookTreeItem extends vscode.TreeItem {
 		}
 		else {
 			this.tooltip = this.book.type === BookTreeItemType.Book ? (this.book.version === BookVersion.v1 ? path.join(this.book.root, content) : this.book.root) : this.book.contentPath;
+			this.resourceUri = this.book.type === BookTreeItemType.Book && this.book.version === BookVersion.v1 ? vscode.Uri.file(path.join(this.book.root, content)) : vscode.Uri.file(book.root);
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeItem.ts:78]: this.book.root - minor but good to be consistent here in case we change the book property to be an accessor with extra logic

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/notebook/src/book/bookModel.ts (hunk 1 above)
Comment (barbaravaldez) [reply extensions/notebook/src/book/bookModel.ts:49]: Initially I was using an object of IBookNotebook or a string for the bookPath, I forgot to remove this one.
Thanks!

File: extensions/notebook/src/book/bookPinManager.ts (hunk 2 above)
Comment (barbaravaldez) [reply extensions/notebook/src/book/bookPinManager.ts:36]: I'm not sure why I did this change 😅 . But yeah I agree, I'll change it back.

**Review by lucyzhang929 — APPROVED** [review]
Looks good! Just a couple more places where bookPath is casted to a string

File: extensions/notebook/src/book/bookModel.ts [hunk 7]
```diff
@@ -167,7 +168,7 @@ export class BookModel {
 				);
 				this._bookItems.push(book);
 			} catch (e) {
-				this._errorMessage = loc.readBookError(this.bookPath, e instanceof Error ? e.message : e);
+				this._errorMessage = loc.readBookError(this.bookPath as string, e instanceof Error ? e.message : e);
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply extensions/notebook/src/book/bookModel.ts:171]: Oh that's right!! Thank you, Lucy 😄!
