### PR TITLE
table designer bug fixes

### LINKED ISSUE #18699: editor in the table designer's grid is not updating its style when theme changes
image

### LINKED ISSUE #18700: the changes made in the grid inside table designer is not reflected in the script
user has to move focus to a different cell in the table in order to commit the changes. this is confusing and not user friendly.

this also happens to the input box in the table designer, user has to move focus away from it in order to make change.

### PR DESCRIPTION
**Pull request by alanrenmsft**
**This PR fixes #18700** 
currently, user has to move the focus to a different cell in order to commit the change, this is the default slick grid behavior.
with automatic commit:
auto-commit

**This PR fixes #18699** 

root cause: the editor component is not wired to the theme change event.

Before:
image

After:
fix-theme-change

### CODE REVIEW

File: src/sql/base/browser/ui/table/tableCellEditorFactory.ts [hunk 1]
```diff
@@ -42,6 +47,7 @@ export class TableCellEditorFactory {
 			private _originalValue: string;
 			private _input: InputBox;
 			private _keyCaptureList: number[];
+			private _toDispose = new DisposableStore();
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/table/tableCellEditorFactory.ts:50]: Any reason not to just make the TextEditor disposable itself and then dispose it when it's destroyed?

File: src/sql/base/browser/ui/table/tableCellEditorFactory.ts [hunk 2]
```diff
@@ -106,9 +127,9 @@ export class TableCellEditorFactory {
 		const self = this;
 		class TextEditor {
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/table/tableCellEditorFactory.ts:128]: Just noticed this is "TextEditor" - shouldn't that be "DropdownEditor"?

File: src/sql/base/browser/ui/table/tableCellEditorFactory.ts [hunk 3]
```diff
@@ -106,9 +127,9 @@ export class TableCellEditorFactory {
...
 			private _originalValue: string;
-			private _selectBox: SelectBox;
-			private _dropdown: Dropdown;
+			private _component: SelectBox | Dropdown;
 			private _keyCaptureList: number[];
+			private _toDispose = new DisposableStore();
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/table/tableCellEditorFactory.ts:132]: Same comment about making class disposable instead

**Review by Charles-Gagnon — APPROVED** [review]

**Review by kisantia — APPROVED** [review]

**Review by caohai — APPROVED** [review]
