### PR TITLE
Show error to user

### LINKED ISSUE #9009: Azure Account signin failing silently if account has no Azure tenants
Trying to log in with an account that doesn't have any Azure tenants, nothing happens after logging in and no indication an error occurred. Console has this :

image

We should ideally surface that to the user so they know why it didn't add.

### PR DESCRIPTION
**Pull request by aaomidi**
This PR fixes #9009 

Thanks for catching this @Charles-Gagnon

### CODE REVIEW

File: extensions/azurecore/src/account-provider/azureAccountProvider2.ts [hunk 1]
```diff
@@ -305,7 +305,9 @@ export class AzureAccountProvider implements azdata.AccountProvider {
 
 		tenants = tenants.filter(t => t !== undefined);
 		if (tenants.length === 0) {
-			throw new Error(localize('azure.noTenants', "No azure tenants found. Failing..."));
+			const msg = localize('azure.noTenants', "No azure tenants found. Failing...");
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/azureAccountProvider2.ts]: I'd suggest the text be something like `Failed to add account, there were no Azure tenants found.` Bit more clear that way.

Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/azureAccountProvider2.ts]: I'd also suggest looking through the other errors and think about displaying some of them to the user as well. For example https://github.com/microsoft/azuredatastudio/blob/master/extensions/azurecore/src/account-provider/azureAccountProvider2.ts#L287 is probably something we want to show
