### PR TITLE
fix anchor links in wysiwyg

### LINKED ISSUE #14734: [WYSIWYG] Add a link to a section
Adding a link to a section works, until the code cell is modified then the link is replaced by workbench html.

Expected result:
`[Code](#code)`
Result: 
`[Code](..\AppData\Local\Programs\Azure%20Data%20Studio%20-%20RC1\resources\app\out\vs\code\electron-browser\workbench\workbench.html)`

- Azure Data Studio Version:
Version: 1.27.0-rc1 (user setup)
Commit: 3368af9371f777338a7318e3c746f3dca390396d
Date: 2021-03-15T06:07:09.474Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
Steps to Reproduce:

1. Create a code cell
2. Add a link in WYSIWYG, using the link button
3. Exit the cell
4. Re-enter the cell and update it.
5. The link has been changed for a workbench html.

### PR DESCRIPTION
**Pull request by barbaravaldez**
This PR addresses #14734

If we switch form markdown to wysiwyg and update the cell then links get converted to:
`[hello](#hello)` =>` [hello](#hello)`

`<a href="#hello">hello</a> `=>` [hello](#hello)`

Screen Shot 2021-04-06 at 4 03 55 PM

### CODE REVIEW

**Comment by chlafreniere** [comment]
@barbaravaldez Can you add some tests in htmlMarkdownConverter.test.ts? Hopefully only will take 10-15 mins to get some coverage there 😄

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts [hunk 1]
```diff
@@ -132,15 +132,21 @@ export class HTMLMarkdownConverter {
...
-				// href contains either a hyperlink or a URI-encoded absolute path. (See resolveUrls method in notebookMarkdown.ts)
-				const notebookLink = node.href ? URI.parse(node.href) : URI.file(node.title);
-				const notebookFolder = this.notebookUri ? path.join(path.dirname(this.notebookUri.fsPath), path.sep) : '';
-				let relativePath = findPathRelativeToContent(notebookFolder, notebookLink);
-				if (relativePath) {
-					return `[${node.innerText}](${relativePath})`;
+				let href = node.href;
+				const isAnchorLink = node.attributes.href.nodeValue.startsWith('#');
+				if (isAnchorLink) {
+					href = node.attributes.href.nodeValue;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:138]: What's node.href at this point? I guess I would have assume that it would still be # at this point so you could just skip this and only do the else `if(!isAnchorLink)`

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts (hunk 1 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:138]: node.href should contain the address but turndown parses the link as a file and instead of the original value it gets transform into `./Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html#hello`

**Review by lucyzhang929 — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts [hunk 2]
```diff
@@ -132,15 +132,27 @@ export class HTMLMarkdownConverter {
 		this.turndownService.addRule('a', {
 			filter: 'a',
 			replacement: (content, node) => {
-				//On Windows, if notebook is not trusted then the href attr is removed for all non-web URL links
-				// href contains either a hyperlink or a URI-encoded absolute path. (See resolveUrls method in notebookMarkdown.ts)
-				const notebookLink = node.href ? URI.parse(node.href) : URI.file(node.title);
+				let href = node.href;
+				let notebookLink: URI = undefined;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:136]: `URI | undefined`

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts [hunk 3]
```diff
@@ -295,3 +307,16 @@ export function addHighlightIfYellowBgExists(node, content: string): string {
 	}
 	return content;
 }
+
+export function getUriAnchorLink(node, notebookUri: URI): URI {
+	let notebookLink: URI;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:312]: technically this should be `URI | undefined`. I'd suggest just removing this and returning the values directly on 317 & 321 though.

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts [hunk 4]
```diff
@@ -295,3 +307,16 @@ export function addHighlightIfYellowBgExists(node, content: string): string {
 	}
 	return content;
 }
+
+export function getUriAnchorLink(node, notebookUri: URI): URI {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:311]: node should have a type

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:311]: Looks like we aren't currently importing types for turndown - it looks like DefinitelyTyped has them though so it would be great if you could look into adding these since right now it's a lot of guessing and assumptions around the properties on these things. 

https://www.npmjs.com/package/@types/turndown

(this can be done as a separate PR)

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts [hunk 5]
```diff
@@ -295,3 +307,16 @@ export function addHighlightIfYellowBgExists(node, content: string): string {
...
+	let notebookLink: URI;
+	const sectionLinkToAnotherFile = node.href.includes('#') && !node.attributes.href?.nodeValue.startsWith('#');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:313]: Stuff like this is why typings are nice - what's the difference between node.href and node.attributes.href.nodeValue?

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts [hunk 6]
```diff
@@ -295,3 +307,16 @@ export function addHighlightIfYellowBgExists(node, content: string): string {
...
+	if (sectionLinkToAnotherFile) {
+		let absolutePath = !path.isAbsolute(node.attributes.href?.nodeValue) ? path.resolve(path.dirname(notebookUri.fsPath), node.attributes.href?.nodeValue) : node.attributes.href?.nodeValue;
+		// if section link is different from the current notebook
+		notebookLink = URI.file(absolutePath);
+	} else {
+		notebookLink = URI.from({ scheme: 'file', path: notebookUri.path, fragment: node.attributes.href?.nodeValue });
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:319]: We seem to be assuming here that these are all links to other files. What about http (or other scheme) links? e.g. `https://github.com/microsoft/azuredatastudio/blob/b743d37d6cf36f2684222d723292725ce37bbf41/src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts#L5`

**Review by Charles-Gagnon — COMMENTED** [review]
It's hard for me to get a sense for this fix and how it might affect other stuff - the interaction between turndown and the various modes of display for Notebooks is pretty confusing with how the content gets converted between HTML and markdown. 

What would help is if you gave a clear description of the problem and how it happens - e.g. 

(example here is just the general format, the actual steps are likely incorrect). 

1. User creates fragment link with URL of `#content` 
2. This is converted into HTML by <something>
3. User switches to WYSIWYG mode
4. Turndown service converts that into <other content here>
....

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts (hunk 6 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:319]: I need to add a check for this. Thank you for pointing this out 👍

**Review by VasuBhog — APPROVED** [review]
Test on Windows and found that anchors do not change to full paths either (Julies issue).

**Comment by barbaravaldez** [comment]
> It's hard for me to get a sense for this fix and how it might affect other stuff - the interaction between turndown and the various modes of display for Notebooks is pretty confusing with how the content gets converted between HTML and markdown.
> 
> What would help is if you gave a clear description of the problem and how it happens - e.g.
> 
> (example here is just the general format, the actual steps are likely incorrect).
> 
> 1. User creates fragment link with URL of `#content`
> 2. This is converted into HTML by
> 3. User switches to WYSIWYG mode
> 4. Turndown service converts that into 
>    ....

1. User creates a link in markdown`#content`
2. Switches to WYSIWYG and exits cell
3. If they update the cell in WYSIWYG then the html elements gets converted to markdown using turndown. The HTML string that we send to turndown every time we [update the cell](https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts#L257) is correct, but in the inner workings of turndown it gets parsed weirdly and the href property does not match with what we sent to turndown initially if the link contains a `#`. For instance, if the initial href is `./test.md#HELLO`, then the href property is `file:///Users/bavaldez/azuredatastudio/out/vs/code/electron-browser/workbench/test.md#HELLO`, but the node.attributes.href.nodeValue is `./test.md#HELLO`. 
However for hyperlinks and URI-enconded paths the node.attributes.href?.nodeValue matches the node.href property.
