### PR TITLE
fix undefined error in dacpac extension when sending telemetry

### LINKED ISSUE #21626: Dacpac extension error reading toString of undefined
image

Happens when deploying to a new database, not existing. This doesn't affect the actual deploy as this is for the telemetry that gets sent after the operation completes. I suspect the error is in these two lines:
https://github.com/microsoft/azuredatastudio/blob/146d64435af885b06498df2c3365a72598927e55/extensions/dacpac/src/wizard/dataTierApplicationWizard.ts#L337-L338

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #21626. The error was because `potentialDataLoss` doesn't get set for deploy to new db, only for deploy to existing db.

### CODE REVIEW

File: extensions/dacpac/src/wizard/dataTierApplicationWizard.ts [hunk 1]
```diff
@@ -335,7 +335,7 @@ export class DataTierApplicationWizard {
 		additionalMeasurements.totalDurationMs = (new Date().getTime() - deployStartTime);
 		additionalMeasurements.deployDacpacFileSizeBytes = await utils.tryGetFileSize(this.model.filePath);
 		additionalProps.upgradeExistingDatabase = this.model.upgradeExisting.toString();
-		additionalProps.potentialDataLoss = this.model.potentialDataLoss.toString();
+		additionalProps.potentialDataLoss = this.model.potentialDataLoss?.toString();
```
Comment (Charles-Gagnon) [inline extensions/dacpac/src/wizard/dataTierApplicationWizard.ts:338]: You should update the interface definition too. 

(and friendly reminder that taking some committer time to add strict null checking to this extension would help avoid issues like this)

Comment (kisantia) [reply extensions/dacpac/src/wizard/dataTierApplicationWizard.ts:338]: good reminder! I'll put that on my list todo :)

[the remark this answers is not in the document]
Comment (kisantia) [reply extensions/dacpac/src/wizard/dataTierApplicationWizard.ts:338]: generateDeployScript is only for the updating an existing database scenario in the dacpac wizard, so potentialDataLoss will always be set (not undefined) in that case.

**Review by SakshiS-harma — APPROVED** [review]
