### PR TITLE
fix the dashboard toolbar not load issue

### LINKED ISSUE #14281: Failed to execute 'add' on 'DOMTokenList' error when opening dashboard
```
[22420:0212/142956.880:INFO:CONSOLE(144)] "%c  ERR color: #f33 Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.: Error: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at LabeledMenuItemActionItem._updateItemClass (file:///C:/src/AzureDataStudio/out/vs/platform/actions/browser/menuEntryActionViewItem.js:255:46)
    at LabeledMenuItemActionItem.render (file:///C:/src/AzureDataStudio/out/vs/platform/actions/browser/menuEntryActionViewItem.js:85:18)
    at file:///C:/src/AzureDataStudio/out/sql/base/browser/ui/taskbar/actionbar.js:176:22
    at Array.forEach (<anonymous>)
    at OverflowActionBar.pushAction (file:///C:/src/AzureDataStudio/out/sql/base/browser/ui/taskbar/actionbar.js:162:21)
    at OverflowActionBar.pushAction (file:///C:/src/AzureDataStudio/out/sql/base/browser/ui/taskbar/overflowActionbar.js:233:19)
    at Taskbar.setContent (file:///C:/src/AzureDataStudio/out/sql/base/browser/ui/taskbar/taskbar.js:95:36)
    at ServerDashboardPage.createToolbar (file:///C:/src/AzureDataStudio/out/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.js:142:26)
    at ServerDashboardPage.init (file:///C:/src/AzureDataStudio/out/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.js:98:18)
    at file:///C:/src/AzureDataStudio/out/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.component.js:50:22
    ```

### PR DESCRIPTION
**Pull request by alanrenmsft**
this PR fixes #14281 
I noticed in latest insider build, when you have sql-database-project extension installed, the dashboard's toolbar doesn't have all the expected items with error messages in the console.

image
image

turns out this is caused by the recent vscode merge, we added a class in the vscode's file, and in the recent vscode merge, we changed the implementation of how to add css classes to the node (the old addClass method is deprecated)
old:
https://github.com/microsoft/azuredatastudio/blob/release/1.26/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L359

new:
https://github.com/microsoft/azuredatastudio/blob/main/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L292

the new one doesn't allow empty css class names, and caused the error above.

the fix is to check whether the class is empty and only add it to the list if it is not empty.

with the fix, the toolbar is loading as expected:
image

more information on this class:
this was added here by Chris for notebook toolbar (it passes in a default class name 'notebook-button', but I couldn't find the definition of it in our code base) @chlafreniere , if the class name doesn't actually exist, could you please remove it?
https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/contrib/notebook/browser/notebook.component.ts#L512

currently only dashboard and notebook are using this class.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Thanks - looks like this fixes https://github.com/microsoft/azuredatastudio/issues/14281

**Review by Charles-Gagnon — APPROVED** [review]

File: src/vs/platform/actions/browser/menuEntryActionViewItem.ts [hunk 1]
```diff
@@ -289,10 +289,14 @@ export class LabeledMenuItemActionItem extends MenuEntryActionViewItem {
 				}
 
 				if (this.label) {
-					this.label.classList.add('codicon', this._defaultCSSClassToAdd, ...iconClass.split(' '));
+					const iconClasses = iconClass.split(' ');
```
Comment (kburtram) [inline src/vs/platform/actions/browser/menuEntryActionViewItem.ts:292]: I've noticed several exceptions in other places during code merge testing that `iconClass.split(' ')` throws, I think due to things like lead ' ' character.  I added guards to avoid, maybe not needed here, but something to be aware of.

**Review by kburtram — APPROVED** [review]
