### PR TITLE
Fix tenant Id design for Azure accounts

### LINKED ISSUE #20701: Accounts pane shows different icons for same account
- Azure Data Studio Version: 1.39.1
- OS Version: MacOs Monterey 12.6

Steps to Reproduce:

1. Add Account to Accounts pane
2. Sometimes it has the Microsoft logo, sometimes it has a different logo
Screen Shot 2022-09-30 at 2 58 03 PM
Screen Shot 2022-09-30 at 2 59 20 PM

Does this issue occur when all extensions are disabled?: N/A

### PR DESCRIPTION
**Pull request by cheenamalhotra**
This PR shall fix #20701 #20517 and many more similar issues where tenant IDs are not respected.

Current implementation contained a logic to fetch home tenant, which would look into all tenants and find the first 'Home' tenant. It is entirely possible that an Azure account contains multiple 'Home' tenants (as it is in my account), so this implementation was incorrect.

### Consequences and what changed:

* Wrong tenant identified can lead to different account Id being fetched when refreshing token. This is why when reopening ADS, we would see multiple account entries in Azure Tree for same Corp account generally observed by users also have a personal AD. https://github.com/microsoft/azuredatastudio/issues/20701#issuecomment-1301483198

The implementation is now updated to fetch the tenant Id from `token claims > tid` as fetched with the access token - is the one that user authorized from. We should be using this `tid` for future connections and refreshing, which seems to fix the issue, as the respective Azure Account will always receive token from this federation authority. Thanks @cssuh for validating the change. 

Defining tid from [MS Docs](https://learn.microsoft.com/azure/active-directory/develop/id-tokens):

**tid (String, a GUID) =** Represents the tenant that the user is signing in to. For work and school accounts, the GUID is the immutable tenant ID of the organization that the user is signing in to. For sign-ins to the personal Microsoft account tenant (services like Xbox, Teams for Life, or Outlook), the value is 9188040d-6c67-4c5b-b112-36a304b66dad.

* #20517 is also seemingly fixed when testing, we're able to see when clicking the 'Connect' icon near server/db names, correct tenant shows up relative to where Server/DB belongs to (mainly impacts multi-tenant user accounts), this was always defaulting to the same first Home tenant as saved previously., 
  * Looking at codebase [here](https://github.com/microsoft/azuredatastudio/blob/68b91089db3d1e6ee52e958ee179f360ce3eb278/src/sql/workbench/services/connection/browser/connectionWidget.ts#L796-L812) it makes sense that now the correct tenant is being loaded as associated with the connection profile.

The changes in this PR will also apply to MSAL as they apply to core design of how tenant id is used for authenticating user.

### CODE REVIEW

File: extensions/azurecore/src/azurecore.d.ts [hunk 1]
```diff
@@ -38,11 +38,17 @@ declare module 'azurecore' {
...
 		providerSettings: AzureAccountProviderMetadata;
+
 		/**
 		 * Whether or not the account is a Microsoft account
 		 */
 		isMsAccount: boolean;
 
+		/**
+		 * Represents the tenant that the user would be signing in to. For work and school accounts, the GUID is the immutable tenant ID of the organization that the user is signing in to.
+		 * For sign-ins to the personal Microsoft account tenant (services like Xbox, Teams for Life, or Outlook), the value is 9188040d-6c67-4c5b-b112-36a304b66dad.
```
Comment (cssuh) [inline extensions/azurecore/src/azurecore.d.ts:49]: Is the tenant for personal accounts not `f8cdef31-a31e-4b4a-93e4-5f571e91255a`?

**Review by cssuh — APPROVED** [review]
Made one comment about personal account tenant ID, otherwise looks good

File: extensions/azurecore/src/azurecore.d.ts (hunk 1 above)
Comment (cheenamalhotra) [reply extensions/azurecore/src/azurecore.d.ts:49]: They both are valid, the one I mentioned in comment comes for MSAL ([MS Doc](https://learn.microsoft.com/en-us/azure/active-directory/develop/accounts-overview)). Since we're soon going to be in MSAL world (as we should be ideally), we can let the comment stay as is.
