### PR TITLE
Fix anchor links in notebooks

### LINKED ISSUE #8428: Notebooks: Internal Document Links Not Functional
Azure Data Studio Version: 1.13.1

CPUs | Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.89GB (6.68GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
powershell | ms- | 2019.11.0
whoisactive | Mic | 0.1.2
sql-search | Red | 0.3.4

Steps to Reproduce:

1. Create a internal document anchor `<a name="regrets"> </a>`
2. In a different cell create a link to the anchor `[link](#regrets)`
3. clicking the created link does not navigate to the document anchor but instead opens a second tab called workbench.html with the following content:

```<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<!-- {{SQL CARBON EDIT}} @anthonydresser add 'unsafe-eval' under script src; since its required by angular -->
		<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' https: data: blob: vscode-remote-resource:; media-src 'none'; frame-src 'self' https://*.vscode-webview-test.com; object-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https:; font-src 'self' https: vscode-remote-resource:;">
	</head>
	<body class="vs-dark" aria-label="">
	</body>

	<!-- Startup via workbench.js -->
	<script src="workbench.js"></script>
</html>
```

### PR DESCRIPTION
**Pull request by barbaravaldez**
**This PR fixes #8428**

Fix issue with anchor links in notebooks.
- When selecting elements we only detected the headers, anchors are now being selected as well.
- In some cases when using anchors, the value of id is under the name attribute. Now we when getting the relativeUri we check for the name attribute in case the id is empty.
Get uri path back to fsPath due to issues on case sensitive. 

**How to Test:**
[sample.zip](https://github.com/microsoft/azuredatastudio/files/4429684/sample.zip)

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 1]
```diff
@@ -685,7 +685,10 @@ class NotebookSection implements INotebookSection {
 	}
 
 	get relativeUri(): string {
-		return this.headerEl['id'];
+		if (this.headerEl['id']) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:688]: This can be shortened to just `return this.headerEl['id'] || this.headerEl['name'];`

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:688]: That's right! I'll update the PR 😄 Thanks!

**Comment by chlafreniere** [comment]
Woohoo! So after these changes, do the 6 examples in the bug all function correctly now on your machine?

**Comment by Charles-Gagnon** [comment]
I verified it myself (thanks for the sample notebook @barbaravaldez !) and yup, looks good to me! (well - aside from the offset issue being fixed in the other PR)
