### PR TITLE
fix tab header missing issue in connection dialog

### LINKED ISSUE #17261: the recent/browse tab header sometimes disappears
image

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #17261

### CODE REVIEW

File: src/sql/workbench/services/connection/browser/connectionDialogWidget.ts [hunk 1]
```diff
@@ -218,6 +228,11 @@ export class ConnectionDialogWidget extends Modal {
 
 		this._register(this._themeService.onDidColorThemeChange(e => this.updateTheme(e)));
 		this.updateTheme(this._themeService.getColorTheme());
+		this._panelSizeObserver = new ElementSizeObserver(this._panel.element, undefined, () => {
+			this._panel.layout(new DOM.Dimension(this._panel.element.clientWidth, this._panel.element.clientHeight));
+		});
+		this._register(this._panelSizeObserver);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionDialogWidget.ts:234]: You can also call this._register in the line above

**Review by Charles-Gagnon — APPROVED** [review]
