### PR TITLE
Fetch arc dc config profile list from azdata

### LINKED ISSUE #12372: The config profile list does not match the output of azdata arc dc config list
- Azure Data Studio Version: RC1

Steps to Reproduce:

1. On the command line - Run 'azdata arc dc config list' on latest build azdata CLI
2. Open Azure Data Studio, Click on Add Azure Arc Controller
3. In Step 2 - Choose a config profile, compare the list of config profiles listed with list in (1) above

Expected Behavior

All available config profiles in azdata CLI should be shown in Azure Data Studio

[AB#3780](https://mssqltools.visualstudio.com/dea8be32-0532-4a8f-a2f4-89271d8b1cc5/_workitems/edit/3780)

### PR DESCRIPTION
**Pull request by ranasaria**
Adds a new options source to fetch dc config profile list from azdata arc dc config list command. Also did some code refactoring to simplify creation of OptionsSource object.

This PR fixes #12372

Testing: 
1. End to end testing of dc create scenario
2. Extension unit tests.

### CODE REVIEW

File: extensions/resource-deployment/src/helpers/optionSources.ts [hunk 1]
```diff
@@ -11,74 +11,112 @@ import { apiService } from '../services/apiService';
 import { throwUnless } from '../utils';
 import { CacheManager } from './cacheManager';
 
-export enum OptionsSourceType {
-	ArcControllersOptionsSource = 'ArcControllersOptionsSource'
+export const enum OptionsSourceType {
+	ArcControllersOptionsSource = 'ArcControllersOptionsSource',
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/helpers/optionSources.ts:15]: I've created an issue to not have these be hardcoded in resource deployment. That isn't maintainable long term to have to have this extension know about all the possible options

https://github.com/microsoft/azuredatastudio/issues/12682

Please work on that task when you finish up with your current stuff - it would be nice to get this done before we add too many other option types. 

(this is ok for now in this PR but  I'd like this done before we have to add another type)

File: extensions/resource-deployment/src/helpers/optionSources.ts [hunk 2]
```diff
@@ -11,74 +11,112 @@ import { apiService } from '../services/apiService';
...
+	ArcControllerConfigProfilesOptionsSource = 'ArcControllerConfigProfilesOptionsSource'
 }
 
-export abstract class OptionsSource implements IOptionsSource {
+export namespace OptionsSources {
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/helpers/optionSources.ts]: Why are you creating a new namespace? That seems unnecessary

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/helpers/optionSources.ts]: Is it just so you can do `return new OptionsSources[sourceType](variableNames, sourceType);`?

I don't know if this is a common pattern - I certainly haven't seen it before. But I really don't like doing needlessly fancy stuff like this when you could just simply do a switch statement which is clearer and easier to understand IMO.

So I'm going to ask that you just remove this whole create function and add another line to the switch I had before. There was nothing wrong with that approach and this isn't gaining us anything useful.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
The config profiles part seems ok, but I'd rather you revert the refactoring of the instance creation

File: extensions/resource-deployment/src/helpers/optionSources.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/helpers/optionSources.ts]: For a specific example of why I disagree with this being a good change - unless I'm mistaken you lose all type validation for the constructor by indexing into the namespace like that. And that very much is something we should always avoid doing.

Comment (ranasaria) [reply extensions/resource-deployment/src/helpers/optionSources.ts]: yes, it so we can do return new OptionsSources[sourceType](variableNames, sourceType);?

And there are times when we ca to any, so what you worry about is not a concern in my mind. The caller gets full type safety, and it is just this one line of code and I reckon this kind of code would be needed when tackling #12682. I do not like the massive switch statement in modelViewUtils. Switch statements add to code complexity (fewer branches in code is good for code maintainability and switch is the mother of branches.

In my view, we can handle this as appropriate when we do #12682. But I would like it if we kept the create method here as I did not invent this factory method and it not uncommon in javascript/typescript world.

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/helpers/optionSources.ts]: I don't understand your comment about casting to any. We never do that for constructors - and the times we do it for anything else are fairly rare and usually indicate a code smell.

If we update the constructor to require an additional parameter then this will just silently be broken unless we also remember to update the function call - that's bad and would never happen with the switch statement.

There are ways to get type safety for this kind of thing - see what VS Code does with the instantiation service. I haven't looked into the implementation of that to know exactly what they're doing there and regardless that's way overly complex for this one-off case.

This is not providing anything useful and is just adding extra lines of code and complexity for no real benefit.

The switch statement will go away with the linked work item - we'll just have a map of the registered callbacks instead. So none of this is long lasting anyways.

Comment (ranasaria) [reply extensions/resource-deployment/src/helpers/optionSources.ts]: reverting ...

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 3]
```diff
@@ -439,7 +439,9 @@ async function processOptionsTypeField(context: FieldContext): Promise<void> {
 				case OptionsSourceType.ArcControllersOptionsSource:
 					optionsSource = new ArcControllersOptionsSource(context.fieldInfo.options.source.variableNames, context.fieldInfo.options.source.type);
 					break;
-				default:
+				case OptionsSourceType.ArcControllerConfigProfilesOptionsSource:
+					optionsSource = new ArcControllerConfigProfilesOptionsSource(context.fieldInfo.options.source.variableNames, context.fieldInfo.options.source.type);
+					break; default:
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:444]: default should be on a new line

File: extensions/resource-deployment/src/interfaces.ts [hunk 4]
```diff
@@ -189,8 +189,8 @@ export type ComponentCSSStyles = {
 export interface IOptionsSource {
 	readonly type: OptionsSourceType,
 	readonly variableNames: { [index: string]: string; },
-	getOptions(): Promise<string[] | azdata.CategoryValue[]>,
-	getVariableValue(variableName: string, input: string): Promise<string>;
+	getOptions(): Promise<string[] | azdata.CategoryValue[]> | string[] | azdata.CategoryValue[],
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/interfaces.ts:192]: Why are you changing this? This doesn't appear to be necessary and having it sometimes return a promise makes it more annoying for callers to have to figure out what the actual return type is. If you always return a promise then you can just have the ones that don't require async stuff just resolve immediately and that's a perfectly fine option.

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/resource-deployment/src/interfaces.ts (hunk 4 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/interfaces.ts:192]: callers don't have to figure anything out as a caller can simply await. The implementers get the option of choosing either return type. See call in modelViewUtils where nothing special is being done.

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/interfaces.ts:192]: You can - but why? As far as I can tell this isn't needed currently.

Comment (ranasaria) [reply extensions/resource-deployment/src/interfaces.ts:224]: callers don't have to figure anything out as a caller can simply await. The implementers get the option of choosing either return type. Basically, you are suggesting that implementers just return a Promise.resolve of value that they wish to return then by waiting on a function that returns a simple value and not a promise, the language compiler does the wrapping of Promise.resolve for us. So, by adding that additional return time we are making the code cleaner.

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/interfaces.ts:224]: My point is that currently I don't see any implementation that needs to return a non-Promise so I don't see the point in updating this now.
