### PR TITLE
Display tables in html 

### LINKED ISSUE #18921: HTML table converted to MD table on Ctrl + S
- Azure Data Studio Version: 1.35.0
- OS Version: At least Mac and Windows

When MD has a HTML table tag, using **ADS notebook extension**, when edited using the **UI**, after saving it will try to convert it to MD table format.
Problem is, it will break formating. And for multi-line cells, MD format is a nightmare.
Hence, we need to keep HTML format eventually.

If using **MD editor**, table is preserved, but that's not easily discoverable.

Steps to Reproduce:
1. Add any HTML table using the MD editor.
2. Open it using the rich text UI editor
3. Make any change on text
4. Save it

**Actual:** It will convert the html table tag into MD table;
**Expected:** Keep HTML tables as is. Or at least allow us to set that in a given repository we do not want to convert it. 
**Reasoning:** While the MD table is desired for smaller text, it will be very hard to maintain on tables that were more sophisticated (or more complicated), e.g., when you have a specific cell in a row which is multi-lined.

E.g.,:
```html
<table style="border: 1px solid black;">
<tr style="border: 1px solid black;">
<td>This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. </td>
</tr>
<tr style="border: 1px solid black;">
<td>This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. </td>
</tr>
</table>
```

It will properly render on preview mode
image

 

But if any editing happen on Preview mode, when saving, the table will be converted to:
image

Does this issue occur when all extensions are disabled?: Yes/**No** -> This is using the Notebook Extension.

The only Extension I can file using report issue dialog is Kusto's

### PR DESCRIPTION
**Pull request by barbaravaldez**
Add setting to display tables in html format

https://user-images.githubusercontent.com/34872381/194651797-b0bb2ba7-a0a0-49fd-9561-26acbafd0f5e.mov

This PR fixes #18921

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/turndownPluginGfm.ts [hunk 1]
```diff
@@ -170,6 +170,7 @@ export function taskListItems(turndownService) {
 	});
 }
 
+
```
Comment (lucyzhang929) [inline src/sql/workbench/contrib/notebook/browser/turndownPluginGfm.ts:173]: nit: extra line

File: src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts [hunk 2]
```diff
@@ -356,6 +356,11 @@ configurationRegistry.registerConfiguration({
 			'minimum': 10,
 			'description': localize('notebook.maxRichTextUndoHistory', "The maximum number of changes stored in the undo history for the notebook Rich Text editor.")
 		},
+		'notebook.renderTablesInHtml': {
+			'type': 'boolean',
+			'default': false,
+			'description': localize('notebook.renderTablesInHtml', "Tables are displayed as HTML in text cells.")
```
Comment (lucyzhang929) [inline src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts:362]: Not sure about the exact wording but we should call out html vs markdown table. Maybe something like: `Keep HTML tables in text cells instead of converting to markdown tables.`

**Review by lucyzhang929 — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
Is this going to update any open Notebooks? Or is it going to require closing/reopening or reloading the window? If that's the case then it would be good to either prompt the user to reload the window when changing the value or have the Notebooks refresh themselves with the new setting.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 3]
```diff
@@ -155,6 +162,17 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 				this._redoStack.maxStackSize = newStackSize;
 			}
 		}));
+
+		this._register(this._configurationService.onDidChangeConfiguration(e => {
+			this.renderTablesInHtml = this._configurationService.getValue('notebook.renderTablesInHtml');
+			this._notificationService.prompt(Severity.Info, promptReloadNotebooks,
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:168]: That makes more sense. I'll reload the components, instead.

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 4]
```diff
@@ -154,6 +159,22 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 				this._undoStack.maxStackSize = newStackSize;
 				this._redoStack.maxStackSize = newStackSize;
 			}
+			if (e.affectsConfiguration('notebook.renderTablesInHtml')) {
+				this._htmlMarkdownConverter = this._instantiationService.createInstance(HTMLMarkdownConverter, this.notebookUri);
+				this.updateCellSource();
+				if (this.isEditMode) {
+					this._notificationService.prompt(Severity.Info, promptReloadNotebooks, [{
+						label: 'Reload',
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:167]: localize these

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 5]
```diff
@@ -154,6 +159,22 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
...
+						run: () => {
+							this.markdowncodeCell.map(code => code.refreshCell());
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:169]: forEach - map should generally just be used when you want to convert stuff into another form

File: src/sql/workbench/contrib/notebook/common/constants.ts [hunk 6]
```diff
@@ -0,0 +1,7 @@
+/*---------------------------------------------------------------------------------------------
+ *  Copyright (c) Microsoft Corporation. All rights reserved.
+ *  Licensed under the Source EULA. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+import { localize } from 'vs/nls';
+
+export const promptReloadNotebooks = localize('promptReloadNotebooks', "The setting for how tables are displayed in text cells has been changed. Please reload Azure Data Studio or reopen current notebooks to enable it.");
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/common/constants.ts]: Update this to match the new behavior (reload will reload the current cell - which will lose all edits in progress)

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 7]
```diff
@@ -154,6 +159,22 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 				this._undoStack.maxStackSize = newStackSize;
 				this._redoStack.maxStackSize = newStackSize;
 			}
+			if (e.affectsConfiguration('notebook.renderTablesInHtml')) {
+				this._htmlMarkdownConverter = this._instantiationService.createInstance(HTMLMarkdownConverter, this.notebookUri);
+				this.updateCellSource();
+				if (this.isEditMode) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:165]: Are you not able to refresh the edit view as well?

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:165]: what do you mean with edit view? We only need to call updateModel if the cell is already in edit mode. We call the updateModel when editing a cell.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:165]: Why do we only do this if a cell is in edit mode? We should be refreshing all cells regardless of whether they're being edited or not

**Comment by barbaravaldez** [comment]
@Charles-Gagnon I noticed that if I update the setting and the cell is in markdown mode the contents were not updated. I made some changes and it should work now, but I'm not sure if this setting should only apply for WYSIWYG and Split View mode only.

**Comment by Charles-Gagnon** [comment]
I believe it should because those are the only times that the table is rendered - and my understanding is that this functionality doesn't change anything about the code the user types into the text cell so that doesn't need to change. Is that correct?

**Comment by barbaravaldez** [comment]
> I believe it should because those are the only times that the table is rendered - and my understanding is that this functionality doesn't change anything about the code the user types into the text cell so that doesn't need to change. Is that correct?

I see,  the original issue is that the cell contents are updated when modifying the cell in wysiwyg mode, so if the user typed in a table in html format then it would get transformed to markdown. This still happens with the current fix unless the html setting is checked.

File: src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts [hunk 8]
```diff
@@ -356,6 +356,11 @@ configurationRegistry.registerConfiguration({
 			'minimum': 10,
 			'description': localize('notebook.maxRichTextUndoHistory', "The maximum number of changes stored in the undo history for the notebook Rich Text editor.")
 		},
+		'notebook.renderTablesInHtml': {
+			'type': 'boolean',
+			'default': false,
+			'description': localize('notebook.renderTablesInHtml', "Display tables in HTML format in text cells instead of converting to markdown tables.")
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts:362]: I feel like we need to be more explicit here about what's actually happening - because it's less that it's "displaying" the table in HTML format but rather converting the actual table text itself into either markdown or HTML. 

@chlafreniere Thoughts on this?

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 9]
```diff
@@ -117,6 +117,7 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 	private markdownPreviewLineHeight: number;
 	public readonly onDidClickLink = this._onDidClickLink.event;
 	public doubleClickEditEnabled: boolean;
+	public renderTablesInHtml: boolean;
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:120]: forgot to remove it

File: src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts (hunk 8 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/notebook.contribution.ts:362]: How about "Display and save" instead of just "Display"?

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 10]
```diff
@@ -128,7 +128,7 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 		@Inject(IInstantiationService) private _instantiationService: IInstantiationService,
 		@Inject(IWorkbenchThemeService) private themeService: IWorkbenchThemeService,
 		@Inject(IConfigurationService) private _configurationService: IConfigurationService,
-		@Inject(INotebookService) override notebookService: INotebookService
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:131]: nit: extra comma

**Review by chlafreniere — APPROVED** [review]
