### PR TITLE
do not crash query editor

### LINKED ISSUE #6763: unsaved tabs crashing
- Azure Data Studio Version:

Version: 1.9.0 (system setup)
Commit: 78a42e1d112ae3231777722b51eaf44f83ddbe55
Date: 2019-07-10T04:31:36.998Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. open a new sql tab
2. write some tsql code and connected to an instance
3. after some idle time, the pop with the error message shows up and the tab closes automatically

Error: Unable to open 'SQLQuery_1 - *****...grated)': Cannot read property 'slice' of undefined.

Note: the problem occurs rarely.

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #6763 

from the most recent screenshot in the issue, I can't really tell why my previous PR https://github.com/microsoft/azuredatastudio/pull/17278 didn't work for the user, so I am adding another guard (try-catch block) to make sure the query editor is not crashing when this happens again.

### CODE REVIEW

File: src/sql/workbench/contrib/query/browser/queryResultsView.ts [hunk 1]
```diff
@@ -300,43 +300,52 @@ export class QueryResultsView extends Disposable {
 		}
 	}
 
-	public set input(input: QueryResultsInput | undefined) {
-		this._input = input;
-		this.runnerDisposables.clear();
+	private showQueryEditorError(): void {
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/query/browser/queryResultsView.ts:303]: please hide the whitespaces to make it easy to tell the actual changes. image

**Review by Charles-Gagnon — APPROVED** [review]
