### PR TITLE
Register mysql, pgsql with mssql as default 'sql' kernel providers

### LINKED ISSUE #21472: Not able to attach a "Postgress DB" connection from note book.
Issue Type: <b>Bug</b>

Step to reproduce
-Install extension postgress db
-Create a note book and connect to postress db.(Works fine)
-Save notbook in local machine.
-Open saved notebook
-Try to atach connection
-Postgress saved connections is available in the list, but the connection type[driver] is Sql server

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T19:35:40.769Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

### PR DESCRIPTION
**Pull request by cheenamalhotra**
This PR fixes #21472 

Noticed that all 3 providers are registered for 'sql' kernel when creating new notebook connection, but are not available when reloading ADS with an opened notebook and trying to connect, as explained in the linked issue.

### CODE REVIEW

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -1121,7 +1121,7 @@ export class NotebookModel extends Disposable implements INotebookModel {
 			// Switching from Kusto to another kernel should set the currentKernelAlias to undefined
 			if (this._selectedKernelDisplayName !== this._currentKernelAlias && this._selectedKernelDisplayName) {
 				this._currentKernelAlias = undefined;
-			} else {
+			} else if (this._currentKernelAlias) {
```
Comment (cheenamalhotra) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:1124]: This check is added to avoid setting 'undefined' alias, as I noticed that happening while debugging.

**Review by corivera — APPROVED** [review]

File: src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts [hunk 2]
```diff
@@ -909,7 +909,11 @@ export class NotebookService extends Disposable implements INotebookService {
 			standardKernels: [{
 				name: notebookConstants.SQL,
 				displayName: notebookConstants.SQL,
-				connectionProviderIds: [notebookConstants.SQL_CONNECTION_PROVIDER],
+				connectionProviderIds: [
+					notebookConstants.SQL_CONNECTION_PROVIDER,
```
Comment (chlafreniere) [inline src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:913]: I'm a bit confused here. Shouldn't we be checking one of the connection provider registries instead of hardcoding this list?

Comment (corivera) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:913]: That's probably something we can explore in a separate PR, since it would overcomplicate the fix here.

Comment (chlafreniere) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:913]: Ok. Can we add a TODO then?

Comment (corivera) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:913]: https://github.com/microsoft/azuredatastudio/issues/22755

Comment (cheenamalhotra) [reply src/sql/workbench/services/notebook/browser/notebookServiceImpl.ts:913]: Thanks Cory!
