### PR TITLE
Books: Ensure associatedResource is Present for Untitled Notebooks that have a File Associated with them

### LINKED ISSUE #9008: TSG Notebook links aren't working
Clicking on a link in the 2019 TSG results in an error similar to this :

```
Unable to open 'sop007-get-key-version-information.ipynb': Unable to read file 'd:\src\azuredatastudio\out\vs\code\electron-browser\common\sop007-get-key-version-information.ipynb' (Error: Unable to resolve non-existing file 'd:\src\azuredatastudio\out\vs\code\electron-browser\common\sop007-get-key-version-information.ipynb').
```

Repros on both 1.15 and dev. 

Probably related to https://github.com/microsoft/azuredatastudio/issues/8534

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #9008.

2 very related issues:
- Conditionally add associatedResource (instead of untitledResource) if the file exists on disk already
- Don't use same untitled numbering logic as other untitled notebooks and use the resource as-is (either the full path uri or the untitled:Notebook-x format)

I've tested the following scenarios:
- Opening saved notebooks + rehydrating
- Untitled new notebooks + rehydrating
- Opening notebook from unsaved books viewlet + clicking relative link (note: rehydration does not work in this case, which is not a regression)
- Opening notebook from saved books viewlet + clicking relative link (rehydration succeeds)

If anyone has any spare cycles and can test, would love any help that you can provide 😄

### CODE REVIEW

File: extensions/notebook/src/book/bookTreeView.ts [hunk 1]
```diff
@@ -298,27 +297,14 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 
 	getUntitledNotebookUri(resource: string): vscode.Uri {
 		let untitledFileName: vscode.Uri;
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts]: nit: Just initialize this instead of setting on separate line
