### PR TITLE
SQL Bindings fix preview flag and constants file

### LINKED ISSUE #19337: Create AF command mentions a table even when ran directly
1. Open VS Code with empty workspace
2. Run `Create Azure Function with SQL Binding` command directly

This error appears. The error itself is fine, but it shouldn't mention a table unless it actually has a table context. 

image

### LINKED ISSUE #19347: SQL Binding: Create Function command doesn't have preview tag
Like the Add SQL Binding - this should have the preview tag until we GA

image

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #19337 and fixes #19347.

Removed constants that are not used and re-organized the file into constants, localized constants, and functions section

### CODE REVIEW

**Review by lucyzhang929 — APPROVED** [review]

File: extensions/sql-bindings/src/common/constants.ts [hunk 1]
```diff
@@ -69,22 +63,23 @@ export const enterConnectionStringSettingName = localize('enterConnectionStringS
...
 export const enterPasswordPrompt = localize('enterPasswordPrompt', 'Enter the password to be used for the connection string');
 export const enterPasswordManually = localize('enterPasswordManually', 'Enter password or press escape to cancel');
 export const userPasswordLater = localize('userPasswordLater', 'In order to user the SQL connection string later you will need to manually enter the password in your local.settings.json file.');
 export const openFile = localize('openFile', "Open File");
 export const closeButton = localize('closeButton', "Close");
-export function addSqlBinding(functionName: string): string { return localize('addSqlBinding', 'Adding SQL Binding to function "{0}"...'), functionName; }
 export const connectionProgressTitle = localize('connectionProgressTitle', "Testing SQL Server connection...");
+export const selectConnectionError = (err?: any): string => err ? localize('selectConnectionError', "Failed to set connection string app setting: {0}", utils.getErrorMessage(err)) : localize('unableToSetConnectionString', "Failed to set connection string app setting");
+
+// functions
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/common/constants.ts:80]: I'd just lump these in with the localized constants, that's really the only differences we care about in this file IMO

**Review by Charles-Gagnon — APPROVED** [review]

**Review by MaddyDev — APPROVED** [review]

**Review by barbaravaldez — APPROVED** [review]
