### PR TITLE
Fix sql project generate script

### LINKED ISSUE #10668: Project Deploy Generate Script flow calls deploy
Azure Data Studio Version: Insiders (6/1)

Steps to Reproduce:

1. Create a new project, open deploy dialog
2. Click generate script 

Two issues 
1. Looks like it call deploy flow rather than generate script
2. dialog doesn't close till user cancels which might be counter intuitive

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #10668. This fixes clicking "generate script" in the deploy dialog calling deploy and also closes the dialog before build starts instead of after. Another issue I found was that the generated script wasn't being opened, so this PR fixes that too by setting the TaskExecutionMode to script instead of execute.

### CODE REVIEW

File: extensions/sql-database-projects/src/dialogs/deployDatabaseDialog.ts [hunk 1]
```diff
@@ -161,10 +161,10 @@ export class DeployDatabaseDialog {
 			sqlCmdVariables: this.project.sqlCmdVariables
 		};
 
+		azdata.window.closeDialog(this.dialog);
 		await this.deploy!(this.project, profile);
```
Comment (alanrenmsft) [inline extensions/sql-database-projects/src/dialogs/deployDatabaseDialog.ts:165]: do we show the in-progress indicator during the deployment? maybe we should leverage the task to do the deployment without letting the dialog to wait for the operation to complete.
