### PR TITLE
use placeholder for table name in add sql bindings quickpick

### LINKED ISSUE #17248: When adding Binding to an Af project Table name input box placeholder doesnt look like placeholder [Not critical]]
- Azure Data Studio Version: Latest Project extn. (Tested in VSCode)
- OS Version:

Steps to Reproduce:

1. Use Add SQL Binding command in VSCode to add Sql Binding
2. The table name that comes in picker is a place holder but it looks like a real name and user might skip to change it.

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #17248. This is how it looks now with a placeholder:

image

### CODE REVIEW

**Review by chlafreniere — APPROVED** [review]

File: extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ export async function launchAddSqlBindingQuickpick(uri: vscode.Uri | undefined,
 	// 3. ask for object name for the binding
 	const objectName = await vscode.window.showInputBox({
 		prompt: selectedBinding.type === BindingType.input ? constants.sqlTableOrViewToQuery : constants.sqlTableToUpsert,
-		value: constants.placeHolderObject,
+		placeHolder: constants.placeHolderObject,
```
Comment (Charles-Gagnon) [inline extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts:82]: Would be good to validate it's non-empty as well.

Comment (kisantia) [reply extensions/sql-database-projects/src/dialogs/addSqlBindingQuickpick.ts:82]: added validation 
image

**Review by Charles-Gagnon — APPROVED** [review]
