### PR TITLE
Remove unusable tenants

### LINKED ISSUE #9885: Azure Account adding not working
- Azure Data Studio Version:
image

Steps to Reproduce:

1.Try to Sign in to Azure
image
2. Click Add an Account:
image

3. Supposedly account added:
image
4. No account added:

### PR DESCRIPTION
**Pull request by aaomidi**
This PR fixes #9885 

So it seems like some users have access to tenants that they can't do resource management on. Keeping these tenants in the account seems silly as no operation will work on them.

Let's log and remove these tenants from the user profile in ADS. If they ever do get access to these accounts back, a simple restart of ADS will repopulate these and try again.

### CODE REVIEW

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 1]
```diff
@@ -219,12 +219,14 @@ export abstract class AzureAuth implements vscode.Disposable {
...
 					return undefined;
 				}
+
 				try {
 					await this.refreshAccessToken(account.key, baseToken.refreshToken, tenant, resource);
 				} catch (ex) {
-					console.log(ex);
-					account.isStale = true;
-					return undefined;
+					console.log(`Could not refresh access token for ${JSON.stringify(tenant)} - silently removing the tenant from the user's account.`);
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:226]: What about other general errors that occur while trying to refresh? Is the error not something we can check for more specifically? 

It might be worth thinking about asking the user whether they want us to remove the tenant so that at least they're aware it's happening. (I'm a little worried most users won't know what that means though so not sure what the best approach is here)

Comment (aaomidi) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:226]: Synced offline

Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:226]: Talked offline - going to get this in and then if users have an issue with missing resources can look into exposing this more publically to them. But it should be enough of an edge case that this is fine to just do and log in the console.
