### PR TITLE
Fixing dashboard tabs not loading when the extension is not activated. 

### LINKED ISSUE #24294: Dashboard trying to load up before the activation of extension has completed - leads to blank white screen.
- Azure Data Studio Version: 1.44.1
- OS Version: Windows 11 (Windows_NT x64 10.0.22621)

Steps to Reproduce:

1. Install Data Migration for Oracle extension. Close the session after installing (avoid connecting to any oracle servers during this session)
2. In new session, connect to oracle server. Once connected quickly select manage and then on the extension dashboard. This should produce a blank screen.
3. The reason why this issue occurs is that dashboard is trying to render itself before the activation of extension is complete, as a result leaves a blank white screen (as shown in the picture below). This issue has also been seen with few other extensions.
 
image

Wanted to know if there any solutions to this problem?

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #24294

The tabs are now implemented with lazy loading, allowing them to wait for the owning extension to activate. While the tabs are loading, a notification has been added to inform users about the dashboard's loading status.

This example shows how the dashboard is waiting for migration extension to be activated for the first time when it downloads the service. Subsequent dashboard loadings are quick as the extension is already activated. 

New design:
BqEfryqNMV

<details>
<summary> Old design </summary>

azuredatastudio_pCa9RjYuht

</details>

### CODE REVIEW

**Review by SakshiS-harma — APPROVED** [review]

File: src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts [hunk 1]
```diff
@@ -495,14 +509,68 @@ export abstract class DashboardPage extends AngularDisposable implements IConfig
...
+				return false;
+			});
+
+			// If the tab is contributed by an extension, we'll wait for the extension to be activated before adding the tab.
+			// Not doing so causes issues with the tab UI not being rendered correctly.
+			if (owningExtension) {
+				// wait for the extension to be activated
+				await new Promise<void>((resolve, reject) => {
+					// If the extension is already activated, we can resolve immediately
+					if (this.extensionService.getExtensionsStatus()[owningExtension.id]?.activationTimes?.activateResolvedTime !== undefined) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts:532]: Is there a reason you're not using something like https://github.com/microsoft/azuredatastudio/blob/25cdb558a707b55ada24b58489b9ad387dbde42d/src/vs/workbench/services/extensions/common/extensionHostManager.ts#L48? The way you're doing it could result in a race condition if the extension status is changed between when you check here and when the event is hooked up.

That being said - we already have the [onDashboardOpen](https://github.com/microsoft/azuredatastudio/blob/25cdb558a707b55ada24b58489b9ad387dbde42d/src/sql/workbench/api/browser/mainThreadDashboard.ts#L23) event which should cover this scenario too. Was the thought here not to block the entire dashboard just because we're waiting on the extensions to load?

File: src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts [hunk 2]
```diff
@@ -495,14 +509,68 @@ export abstract class DashboardPage extends AngularDisposable implements IConfig
...
+				}
+				this.tabs.push(tab);
+				this._cd.detectChanges();
+			}
+
+		} catch (error) {
+			// If we fail to load a tab, we'll just log the error and continue
+			this.notificationService.notify({
+				severity: Severity.Error,
+				message: nls.localize('dashboard.tabLoadingError', "Error loading tab {0}", tab.title)
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts:571]: Not sure a timeout because an extension is taking a long time would count as an "error". Why do we even have a timeout anyways? Seems like it'd be fine just to not have that - and if an extension is stuck then it's stuck. But giving an error just because it's taking a while doesn't seem like the best experience.

File: src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts [hunk 3]
```diff
@@ -495,14 +509,68 @@ export abstract class DashboardPage extends AngularDisposable implements IConfig
...
+							}
+						})
+					});
+
+					/**
+					 * If the extension doesn't activate within 60 seconds, we'll reject the promise.
+					 * While this seems like a long time, it is possible for some extensions to take a
+					 * while to activate, especially if it has to download a big service file.
+					 */
+					setTimeout(() => {
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts:551]: 1. you need to cancel the timeout when the extension is loaded, the dispose and reject will be called regardless.
2. the reject should provide a reason.

File: src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts [hunk 4]
```diff
@@ -495,14 +509,68 @@ export abstract class DashboardPage extends AngularDisposable implements IConfig
...
+						disposable.dispose();
+						reject();
+					}, 60000);
+				});
 			}
-			this.tabs.push(tab);
-			this._cd.detectChanges();
+
+			const existedTab = this.tabs.find(i => i.id === tab.id);
+			if (!existedTab) {
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts:559]: while you are here, I'd also handle the duplicate tab id issue by simply logging an error message about it.

**Comment by Charles-Gagnon** [comment]
Not a huge fan of the progress notification being used here - we already get complaints about too many of these things. Did you consider other solutions like having the tab display but then show a loading spinner while we're waiting for activation to happen? I like something like that a lot better since it also then allows the user to immediately see the tabs that will be loaded vs what you have here where new ones will pop in as they load.

File: src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts (hunk 3 above)
Comment (alanrenmsft) [reply src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts:551]: I also kind of agree with @Charles-Gagnon , we probably shouldn't treat it as an error. and instead, we should try to activate the extension here.

File: src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts (hunk 1 above)
Comment (aasimkhan30) [reply src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts:532]: The extensions are already in the 'activating' state but are not done activating. This is the reason they cannot register the modelview for the dashboard tab and we see the blank screen.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts:531]: What you currently have has a race condition so probably shouldn't be the route we go with.

Activate will just be a no-op if it's already activated, so using that should be fine and avoids any similar problems (plus has the advantage of being a lot cleaner)

**Review by cheenamalhotra — APPROVED** [review]

File: src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/dashboard/browser/core/dashboardPage.component.ts]: Chatted offline - turns out there isn't anything available on any services to access this directly. So instead of modifying VS Code we're just going to fix the race condition.

It's possible there's a better way to do this, but I couldn't find a way immediately. And given the (hopefully) one-off nature of this change it should be fine.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]
