### PR TITLE
fix duplicate sqlcmd var header when loading publish profile multiple times

### LINKED ISSUE #15991: Loading a publish settings profile multiple times duplicates SQLCMD var header
1. Launch `Publish Project` dialog
2. Load a profile that contains SQLCMD vars
3. Load a profile again (can be same profile)

The `SQLCMD Variables` header is duplicated each time you load a new profile

image

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #15991. We weren't accounting for the possibility that a publish profile had previously been loaded and already added the sqlcmd table. The model view components can only get added once, but since this was adding a form component group, the title of the group was getting added again when a publish profile with sqlcmd variables is loadedmultiple times and the project didn't have sqlcmd variables.

before:
image

fixed:
fixDuplicateHeader

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts [hunk 1]
```diff
@@ -566,8 +566,15 @@ export class PublishDatabaseDialog {
 					this.targetDatabaseDropDown!.value = result.databaseName;
 				}
 
-				// save count for later to see if we need to add the SQLCMD Variables table
-				const sqlCmdVarBeforeCount = Object.keys(<Record<string, string>>this.sqlCmdVars).length;
+				if (Object.keys(result.sqlCmdVariables).length) {
+					// add SQLCMD Variables table if it wasn't there before and the profile had sqlcmd variables
```
Comment (Benjin) [inline extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts:570]: why is the table being added preemptively/before we even check if there are any sqlcmd variables in the project?

Comment (kisantia) [reply extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts:570]: if the result from reading the publish profile has any sqlcmd variables(line 569), then the table should be added if the project didn't already specify any sqlcmd variables

**Review by Benjin — APPROVED** [review]
