### PR TITLE
Postgres Compute and Storage page accessibility fixes. 

### LINKED ISSUE #15759: A11y_AzureDataStudioAAE_PG1_Compute + Storage_Keyboard: "Save" & "Discard" button are not getting the instant keyboard focus after updating the edit fields.
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudio_AAE_Jun2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#Keyboard;#WCAG2.4.3;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio - AAE
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure arc and Azure data ClI
2. Connect to Azure Arc Controller
3. Tab till Azure Arc Controller tree and tab to the node present under it
4. Tab to child node "PG1" and open manage and tab to "Compute + Storage" page
5. Edit any Spin button and tab to save button

### Actual:
"Save" & "Discard" button are not getting the instant keyboard focus after updating the edit fields.

### Expected:
"Save" & "Discard" button should get the instant keyboard focus after updating the edit fields.

### User Impact:
Keyboard users will get confused if the button do not focus in logical sequenced order.

https://user-images.githubusercontent.com/85863543/127598602-26f4264d-541c-4640-b057-b7d14f05582a.mp4

### LINKED ISSUE #15760: A11y_AzureDataStudioAAE_PG1_Compute + Storage_Keyboard: Informative tool tips present on the screen are not getting keyboard focus.
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudio_AAE_Jun2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#Keyboard;#WCAG2.4.3;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio-AAE
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure arc and Azure data ClI
2. Connect to Azure Arc Controller
3. Tab till Azure Arc Controller tree and tab to the node present under it
4. Tab to child node "PG1" and open manage and tab to "Compute + Storage" page
5. Tab to Informative tool tips

### Actual:
Informative tool tips present on the screen are not getting keyboard focus.

### Expected:
Informative tool tips present on the screen should get keyboard focus.

### User Impact:
Keyboard users will get confused if the tool tip do not focus in logical sequenced order.

### LINKED ISSUE #15769: A11y_AzureDataStudioAAE_PG1_Compute + Storage_ScreenReader: "Worker node" spin button is announced as required by the screen reader but no visual identification for required field is given on the screen
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudio_AAE_Jun2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#STP;#NVDA;#Jaws;#WCAG3.3.1;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio-AAE
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure arc and Azure data ClI
2. Connect to Azure Arc Controller
3. Tab till Azure Arc Controller tree and tab to the node present under it
4. Tab to child node "PG1" and open manage and tab to "Compute + Storage" page
5. Open NVDA
6. Tab to "Worker node" spin button and check if required field identification is given on the screen

### Actual:
"Worker node" spin button is announced as required by the screen reader but no visual identification for required field is given on the screen.

### Expected:
"Worker node" spin button is announced as required by the screen reader and also visual identification for required field should be given on the screen.

### User Impact:
Users will get confused if no visual identification is given on the screen.

https://user-images.githubusercontent.com/85863543/127597307-1a21bcd7-e24f-4c98-a847-95f6dd6342c7.mp4

### PR DESCRIPTION
**Pull request by nasc17**
Shows required indicator for worker node count.
This PR fixes #15769 

Sets aria labels for information buttons.
This PR fixes #15760

### CODE REVIEW

File: extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts [hunk 1]
```diff
@@ -547,9 +549,12 @@ export class PostgresComputeAndStoragePage extends DashboardPage {
 		if (component.value === originalValue) {
 			return false;
 		} else if ((!component.valid)) {
+			this.discardButton.enabled = true;
```
Comment (Charles-Gagnon) [inline extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts:552]: This is being called every time the text changes - which means that it could steal focus away in the middle of typing something or changing values. Is that not happening or is that the behavior you want?

It's unclear to me what the person is actually saying is wrong. Do you have better context on what the issue is there? Otherwise I'd ask for clarification because I'm not sure what they're saying should happen here. Where does the focus go currently?

Comment (nasc17) [reply extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts:552]: Your point makes sense to me. I will ask for clarification. Currently the focus does not go anywhere after an input box has been edited.

Comment (nasc17) [reply extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts:552]: Removed from this PR

**Review by bergeron — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
