### PR TITLE
Ensure we set group for both editors

### LINKED ISSUE #6012: Query editor scrolls to top when switching tabs
Issue #114 is back in ADS 1.8.0. The cursor is reset to 0,0 each time you switch tabs. This makes it difficult to edit large queries, functions and procedures.

Steps to Reproduce:

1. Open two tabs.
2. Add some SQL in the first tab. Save it to a file, and place the cursor at the end.
3. Switch to the second tab, and then back to the first.
4. Cursor position is reset to the top.

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes #6012

### CODE REVIEW

File: src/sql/workbench/parts/query/browser/queryEditor.ts [hunk 1]
```diff
@@ -294,7 +294,8 @@ export class QueryEditor extends BaseEditor {
 	 * Sets this editor and the 2 sub-editors to visible.
 	 */
 	public setEditorVisible(visible: boolean, group: IEditorGroup): void {
-		this.currentTextEditor.setVisible(visible, group);
+		this.textFileEditor.setVisible(visible, group);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/query/browser/queryEditor.ts]: So this works because despite both being "visible" we still only have one added to the DOM at a time? Seems a little odd - I suppose this is mostly because of our weird dual editor thing and so is something that the native vs code editors don't need a special case for?
