### PR TITLE
Preserve previous code cell's language when creating a new code cell from an existing context.

### LINKED ISSUE #18644: [Interactive] New cells are created using the notebook default language rather than the previously-created cell language
- Azure Data Studio Version: 
Azure Data Studio - Insiders
Version: 1.36.0-insider (user setup)
Commit: a2c39369c98916366ff7bcf9826c7cab7b8de38f
Date: 2022-03-04T06:28:43.281Z (13 hrs ago)
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

- OS Version:
Windows 11

Steps to Reproduce:

1. Create a .NET Interactive notebook, defaulting to C#
2. Create a code cell. The language is set to C#.
3. Change it to F# and run some F# code:
image
4. Create another code cell.

At this point in the VS Code experience, the new cell would default to the same language as the previous cell (F#) but instead it is creating the new cell as C#. We should consider aligning these experiences.

Does this issue occur when all extensions are disabled?: Yes/No
No

### PR DESCRIPTION
**Pull request by corivera**
This PR fixes #18644

### CODE REVIEW

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -833,13 +833,16 @@ export class NotebookModel extends Disposable implements INotebookModel {
 		}
 	}
 
-	private createCell(cellType: CellType): ICellModel {
+	private createCell(cellType: CellType, language?: string): ICellModel {
```
Comment (chlafreniere) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:836]: Please add some notebook model unit tests for this.

Comment (corivera) [reply src/sql/workbench/services/notebook/browser/models/notebookModel.ts:836]: Done.

**Review by chlafreniere — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
