### PR TITLE
restore focus

### LINKED ISSUE #9227: A11y_SQLAzureDataStudio_NewServerGroup_AddServerGroup_Keyboard:Focus is not logical after cancel button
[“Check out Accessibility Insights](https://accessibilityinsights.io/)! - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_SQLAzureDataStudioBenchmark;#A11yMAS;#A11ySev2;#A11yTCS;#SQL Azure Data Studio;#Benchmark;#DesktopApp;#Win32;#MAS2.4.3;#Keyboard;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.16.0-insider
Commit: 506c6a5e5f8423d3249670f55b1466b1980a5f03
Date: 2020-02-17T05:43:18.399Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS2.4.3

**Repro Steps:**
1. Launch Azure Data Studio.
2. Select the Connections icon (if not already selected) from left bar.
3. Hover over the 'Servers' header and select the 'New Server Group' icon.
4. Navigate to Cancel button.

**Actual:**
On navigating to the cancel button hit enter the next tab key focus is seen on the server icon in the left panel.

**Same issue is observed in the following page:**
1.Add new controller

**Expected:**
The focus should be on the button "new server group" button that opened the dialog.

**User Impact:**
Keyboard users will not receive a logical navigation sequence as well as the button that revealed the content will not be visible on the first tab.

**Attachment link for Reference :**
[A11y_SQLAzureDataStudio_NewServerGroup_AddServerGroup_Keyboard9227.zip](https://github.com/microsoft/azuredatastudio/files/4322648/A11y_SQLAzureDataStudio_NewServerGroup_AddServerGroup_Keyboard9227.zip)

### PR DESCRIPTION
**Pull request by alanrenmsft**
when we close the dialog opened by the action buttons in the view header (e.g. new connection dialog, new server group dialog, connect to BDC controller dialog and so on...), we are not able to easily set the focus back to the original button because it is no longer visible. 

It seems a proper fix for this would not be trivial and might take sometime for vscode team. This PR is a simple/low cost workaround for it.
Screen Shot 2020-03-18 at 8 59 48 PM

This PR fixes #9227

### CODE REVIEW

File: src/sql/workbench/browser/modal/modal.ts [hunk 1]
```diff
@@ -345,8 +345,6 @@ export abstract class Modal extends Disposable implements IThemable {
 			this._modalBodySection.querySelectorAll(tabbableElementsQuerySelector) :
 			this._bodyContainer.querySelectorAll(tabbableElementsQuerySelector);
 
-		this._focusedElementBeforeOpen = <HTMLElement>document.activeElement;
```
Comment (alanrenmsft) [inline src/sql/workbench/browser/modal/modal.ts]: this method might be called multiple time within the lifecycle of the dialog, i am moving it to the show method which is only called once.

**Comment by Charles-Gagnon** [comment]
Can we just have the conversation about not having these conditionally hidden? It's a common source of complaints for discoverability and I know we've discussed turning that behavior off before.

**Comment by anthonydresser** [comment]
Is it worth waiting for vscode to fix this issue for the quick open, then adopt that fix for our dialog? They will probably have better context around the best way to solve it. I'm assuming this issue is on their radar?

**Comment by alanrenmsft** [comment]
with this change, by default, the view header actions are always visible, we can use the simple element.focus() without the hacky workaround.

File: src/sql/workbench/browser/modal/modal.ts [hunk 2]
```diff
@@ -396,14 +395,19 @@ export abstract class Modal extends Disposable implements IThemable {
...
 		this._keydownListener.dispose();
 		this._resizeListener.dispose();
 		this._telemetryService.createActionEvent(TelemetryKeys.TelemetryView.Shell, TelemetryKeys.ModalDialogClosed)
 			.withAdditionalProperties({ name: this._name })
 			.send();
+		this.restoreKeyboardFocus();
+	}
+
+	private restoreKeyboardFocus() {
+		if (this._focusedElementBeforeOpen && this._focusedElementBeforeOpen.offsetParent) { // when the element is visible, we can try to set focus to it directly.
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modal/modal.ts]: Why are you checking offsetParent here?

Comment (alanrenmsft) [reply src/sql/workbench/browser/modal/modal.ts]: i guess i don't have do this check anymore since we don't have to do the workaround. in my latest commit i have removed the check.

**Comment by alanrenmsft** [comment]
ping @Charles-Gagnon
