### PR TITLE
Fixes object explorer's manage keybinding shortcut

### LINKED ISSUE #20077: Keybinding for objectexplorer.manage doesn't work
Issue Type: <b>Bug</b>

I need a quick way to initiate a database seaarch. Right-clicking the server and selecting 'Manage' gets me to the search window I want. 

I mapped a key binding to that command so I could launch it quickly with they keyboard. I set the key binding for objectExplorer.manage to Ctrl+Shift+F12. The binding displays when I right-click the server, but the key binding does not work. Nothing happens.

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (21.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0
sql-search|Red|0.4.1
vscodeintellicode|Vis|1.2.1

</details>

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #20077

### CODE REVIEW

File: src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts [hunk 1]
```diff
@@ -100,6 +104,9 @@ export class OEManageConnectionAction extends Action {
 				}
 			}
 		}
+		else if (actionContext === undefined || actionContext === null) {
+			connectionProfile = TaskUtilities.getCurrentGlobalConnection(this._objectExplorerService, this._connectionManagementService, this._editorService) as ConnectionProfile;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts:108]: You should avoid using `as` whenever possible - since that's just overriding the typing that TS provides and generally indicates an error. IConnectionProfile !== ConnectionProfile, and casting it like this is dangerous (what happens if someone tries to call a function that ConnectionProfile defines such as `matches`?).

Instead, you should be doing something like this 

```suggestion

			const globalProfile = TaskUtilities.getCurrentGlobalConnection(this._objectExplorerService, this._connectionManagementService, this._editorService);
			connectionProfile = globalProfile ? ConnectionProfile.fromIConnectionProfile(this._capabilitiesService, globalProfile) : undefined;
```

**Review by Charles-Gagnon — COMMENTED** [review]
Do note that the behavior of which connection is used isn't always going to be clear to the user - so they may not get what they expect. (focused OE nodes vs active editors)

File: src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts [hunk 2]
```diff
@@ -100,6 +104,9 @@ export class OEManageConnectionAction extends Action {
...
+		}
 
 		if (!connectionProfile) {
 			// This should never happen. There should be always a valid connection if the manage action is called for
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts:112]: Also update this comment - this could much more easily happen now if there's no "global" connection available when the user executes it via keybinding.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/dashboard/browser/dashboardActions.ts:114]:
```ts
// No valid connection (e.g. if this was triggered without an active context to get the connection from) so just return early
```

**Comment by Charles-Gagnon** [comment]
You have some compile issues currently

**Review by Charles-Gagnon — APPROVED** [review]
