### PR TITLE
Auto increment new db project name

### LINKED ISSUE #11601: Auto increment project name/folder if a project with the same name already exists
Steps to reproduce:

1. Import a sql project from a database with the default name
2. Try to import the same database project again to the same location with the default name

Actual:
Shows an error message that a project already exists at that location

Expected:
Project should be successfully created with an incremented counter appended to the folder and project name

### PR DESCRIPTION
**Pull request by anjalia**
- Adds the default save location of new projects as a workbench setting, which is initially set to the user's home directory. Prompts user to update this workbench setting whenever they create a new database project. Will continue to prompt until user either goes to settings or clicks "Don't ask me again".
- For "New Project" and "Import Project from DB", auto-increments name if project of the same name already exists in the default save location
- Adds tests with 84% coverage on newProjectTools.ts

This PR fixes #11601 

Scenario where user has workbench setting for default location:
auto_increment

Scenario where user does not have prior setting:
auto_increment_no_default

### CODE REVIEW

**Comment by anjalia** [comment]
A couple of questions for reviewers:
- The behavior here is every time after the user creates a new database project, a little window prompts them to set the "default save location" workspace setting (until they set it). Is that too pushy?
- Any tests recommended for this PR?

Thank you!

File: extensions/sql-database-projects/src/tools/newProjectTool.ts [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+import * as nls from 'vscode-nls';
+import * as path from 'path';
+import * as constants from '../common/constants';
+
+const localize = nls.loadMessageBundle();
+const MaxDefaultProjectNameCounter: number = 99;
+
+export const DBProjectConfigurationKey: string = 'sqlDatabaseProjects';
+export const ProjectSaveLocationKey: string = 'defaultProjectSaveLocation';
+export const NewDefaultProjectSaveLocation: string = localize('sqlDatabaseProjects.newDefaultProjectSaveLocation', "Would you like to set the default location to save new Database Projects?");
```
Comment (kisantia) [inline extensions/sql-database-projects/src/tools/newProjectTool.ts:18]: move localized constants to constants.ts with the other localized strings

File: extensions/sql-database-projects/src/tools/newProjectTool.ts [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+export const InvalidDefaultProjectSaveLocation: string = localize('sqlDatabaseProjects.invalidDefaultProjectSaveLocation', "Default location to save new Database Projects is invalid. Would you like to update it?");
+export const OpenWorkspaceSettings: string = localize('sqlDatabaseProjects.openWorkspaceSettings', "Yes, open Settings");
+
+export class NewProjectTool {
+	/* Returns the default location to save a new database project*/
```
Comment (kisantia) [inline extensions/sql-database-projects/src/tools/newProjectTool.ts:23]: use doc comments like 
```
/**
 * Returns the default location to save a new database project
 */
```

File: extensions/sql-database-projects/src/tools/newProjectTool.ts [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+
+	/* Returns if the default save location for new database projects workspace setting exists and is
+		a valid path*/
+	private get projectSaveLocationSettingIsValid(): boolean {
+		return this.projectSaveLocationSettingExists && fs.existsSync(this.projectSaveLocationSetting);
+	}
+
+	/* Returns if a value for the default save location for new database projects exists*/
+	private get projectSaveLocationSettingExists(): boolean {
+		return this.projectSaveLocationSetting !== null && this.projectSaveLocationSetting !== undefined
```
Comment (kisantia) [inline extensions/sql-database-projects/src/tools/newProjectTool.ts:41]: use undefined instead of null

File: extensions/sql-database-projects/src/tools/newProjectTool.ts [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+	/* Returns default project name for a fresh new project, such as 'DatabaseProject1'. Auto-increments
+		the suggestion if a project of that name already exists in the default save location */
+	public defaultProjectNameNewProj(): string {
+		return this.defaultProjectName(constants.defaultProjectNameStarter, 1);
+	}
+
+	/* Returns default project name for a new project based on given dbName. Auto-increments
+		the suggestion if a project of that name already exists in the default save location */
+	public defaultProjectNameFromDb(dbName: string): string {
+		let projectNameStarter = constants.defaultProjectNameStarter + dbName;
```
Comment (kisantia) [inline extensions/sql-database-projects/src/tools/newProjectTool.ts:54]: it's a good habit to use const instead of let if the variable isn't going to be changed

File: extensions/sql-database-projects/src/tools/newProjectTool.ts [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+
+import * as vscode from 'vscode';
+import * as fs from 'fs';
+import * as os from 'os';
+import * as nls from 'vscode-nls';
+import * as path from 'path';
+import * as constants from '../common/constants';
+
+const localize = nls.loadMessageBundle();
+const MaxDefaultProjectNameCounter: number = 99;
```
Comment (kisantia) [inline extensions/sql-database-projects/src/tools/newProjectTool.ts:14]: why is the max 99?

Comment (anjalia) [reply extensions/sql-database-projects/src/tools/newProjectTool.ts:14]: oh great point... Any recommendations on how to choose a max? I thought it'd be good _some_ max to prevent infinite looping

**Comment by dzsquared** [comment]
@kisantia  @anjalia I am concerned for users being prompted to enter a file path in a text field to set the default - it's a non-trivial task to get your file path entered correctly via keyboard.  I would suggest we either set a default when the extension installs or provide a placeholder when the user goes to set the default (not sure if this capability exists).  
Most comparative tooling (eg SSDT, SSMS) create their own folder in the user's home folder and set it as the default.

image

File: extensions/sql-database-projects/src/test/newProjectTool.test.ts [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+ *  Licensed under the Source EULA. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+
+import * as vscode from 'vscode';
+import * as should from 'should';
+import * as newProjectTool from '../tools/newProjectTool';
+import * as constants from '../common/constants';
+import { generateTestFolderPath, createTestFile } from './testUtils';
+
+describe.skip('NewProjectTool: New project tool tests', function (): void {
```
Comment (kisantia) [inline extensions/sql-database-projects/src/test/newProjectTool.test.ts:12]: Why are these tests skipped? Usually only unstable tests are skipped

File: extensions/sql-database-projects/src/test/newProjectTool.test.ts [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+		const testFolderPath = await generateTestFolderPath();
+
+		try {
+			await vscode.workspace.getConfiguration(constants.dbProjectConfigurationKey).update(constants.projectSaveLocationKey, testFolderPath, true);
+			should(newProjectTool.defaultProjectNameNewProj()).equal('DatabaseProject1');
+			should(newProjectTool.defaultProjectNameFromDb('master')).equal('DatabaseProjectmaster');
+		}
+		finally {
+			// reset configuration
+			await vscode.workspace.getConfiguration(constants.dbProjectConfigurationKey).update(constants.projectSaveLocationKey, previousSetting, true);
```
Comment (kisantia) [inline extensions/sql-database-projects/src/test/newProjectTool.test.ts:26]: reseting configuration can be done in a beforeEach() or afterEach() so that it doesn't have to be done in every test
