### PR TITLE
Fix issues due to missing notebook values (specs and cells)

### LINKED ISSUE #3844: Failed to open Notebook with saved invalid kernel.
Issue Type: <b>Bug</b>

ERR Invalid response: 403 Forbidden: Error: Invalid response: 403 Forbidden
	at __1.ServerConnection.makeRequest.then.response (C:\Users\yuronhe\.azuredatastudio-dev\extensions\microsoft.sql-vnext-0.9.3\node_modules\@jupyterlab\services\lib\kernel\default.js:1211:23)
	at <anonymous>

Azure Data Studio version: azuredatastudio 1.4.4 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

 "metadata": {
  "kernelspec": {
   "display_name": "PySpark (137.135.89.203)",
   "language": "",
   "name": "sparkmagic_pyspark"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "python",
    "version": 2
   },
   "mimetype": "text/x-python",
   "name": "pyspark",
   "pygments_lexer": "python2"
  },
  "name": "Churn Analysis Demo",
  "notebookId": 1573160917957100
 },
 "nbformat": 4,
 "nbformat_minor": 1
}

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (173.21GB free)|
|Process Argv|D:\h\azuredatastudio\.build\electron\azuredatastudio.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.3

</details>

### LINKED ISSUE #3955: Attach To: stuck at "Loading contexts...
- OE has big data connection, sql 2017 and cloud connections
- Select cloud server in OE
- Open the attach notebook
- Attach To: stuck at "loading contexts..."
image

### PR DESCRIPTION
**Pull request by kevcunnane**
- Fix #3844 Failed to open Notebook with saved invalid kernel
- Fix #3955 Attach To: stuck at "Loading contexts... 
- Specs can be null on early load of Jupyter kernels
- Cells were missing in some reference test .ipynb files. We should be resilient to malformed files if possible.

### CODE REVIEW

File: src/sql/parts/notebook/models/notebookModel.ts [hunk 1]
```diff
@@ -546,8 +546,12 @@ export class NotebookModel extends Disposable implements INotebookModel {
...
 	}
 
-	private getDisplayNameFromSpecName(kernelid: string): string {
-		let newKernel = this.notebookManager.sessionManager.specs.kernels.find(kernel => kernel.name === kernelid);
+	private getDisplayNameFromSpecName(kernel: nb.IKernel): string {
+		let specs = this.notebookManager.sessionManager.specs;
+		if (!specs || !specs.kernels) {
+			return kernel.name;
+		}
+		let newKernel = this.notebookManager.sessionManager.specs.kernels.find(kernel => kernel.name === kernel.name);
```
Comment (rajmusuku) [inline src/sql/parts/notebook/models/notebookModel.ts]: Just checking if we can use a different alias in condition checking. Both the names are accessed from kernel object.

Comment (kevcunnane) [reply src/sql/parts/notebook/models/notebookModel.ts]: Sorry Raj can you clarify? what's the suggested change?

Comment (rajmusuku) [reply src/sql/parts/notebook/models/notebookModel.ts]: kernel.name === kernel.name.. little confusing from readability.

Comment (kevcunnane) [reply src/sql/parts/notebook/models/notebookModel.ts]: I think this might be a bug, need to check
