### PR TITLE
Fix Agent tabs not switching

### LINKED ISSUE #6265: Edit Job Page Broken
Issue Type: <b>Bug</b>

Edit Job page no longer switches tabs - it only ever displays the Notifications tab.

Azure Data Studio version: azuredatastudio 1.9.0
OS version: Windows_NT x64 10.0.18362

screen

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (48.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #6265

This was broken in #6185. I don't see why the handle var was moved to be static since it doesn't seem like that should be shared, and that was breaking the agent dialog since it caused all the tabs to share the same ID which broke the tab switching logic.

Also fixing a misspelling I noticed while debugging this.

### CODE REVIEW

File: src/sql/base/browser/ui/panel/panel.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ interface IInternalPanelTab {
 	disposables: IDisposable[];
 	label: HTMLElement;
 	body?: HTMLElement;
-	destoryTabBody?: boolean;
+	destroyTabBody?: boolean;
```
Comment (kburtram) [inline src/sql/base/browser/ui/panel/panel.ts]: nice catch 😄

File: src/sql/workbench/api/node/extHostModelViewDialog.ts [hunk 2]
```diff
@@ -22,7 +22,7 @@ const PREVIOUS_LABEL = nls.localize('dialogPreviousLabel', 'Previous');
 
 class ModelViewPanelImpl implements azdata.window.ModelViewPanel {
 	private _modelView: azdata.ModelView;
-	private static _handle: number;
+	private _handle: number;
```
Comment (kburtram) [inline src/sql/workbench/api/node/extHostModelViewDialog.ts]: thanks!  this is the exact change I was planning on making this morning.

**Comment by kburtram** [comment]
@Charles-Gagnon regarding why the variable was made static, in an previous iteration of the PR there was an internal map that was getting conflicts on some component names that appended this handle, so making the variable static ensured unique ids.  In the final version this issue was resolved a different way and I forgot to go back and remove that change.  

The fact that the modelview dialog has a dependency on this handle not being static probably means that we are doing unneeded reconstruction of the an object somewhere, or caching these handles where we probably shouldn't .  Though I certainly agree that the correct change is to undo the static variable and deal with the underlying issue later if it shows up as a user facing issue (e.g. perf, etc.).
