### PR TITLE
Fixed the table width so it does not overflow from the wizard.

### LINKED ISSUE #13368: Deployment Tools and EULA page extends outside wizard space
image

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #13368 
image

### CODE REVIEW

File: extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts [hunk 1]
```diff
@@ -102,7 +102,7 @@ export class ToolsAndEulaPage extends ResourceTypePage {
 			};
 			const installedPathColumn: azdata.TableColumn = {
 				value: loc.discoverPathOrAdditionalInformationText,
-				width: 580
```
Comment (ranasaria) [inline extensions/resource-deployment/src/ui/toolsAndEulaSettingsPage.ts:105]: Can you make description a little smaller by around 10-20 px making sure the kubectl description still fits and then increase the InstallPath length?

**Review by ranasaria — APPROVED** [review]
Minor comment on adjusting widths, looks good otherwise.

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by aasimkhan30** [comment]
@ranasaria The current width fits the docker description 

image
