### PR TITLE
Fix ADS Web notebook cross linking

### LINKED ISSUE #16925: ADS Web Cross linking notebooks opens external browser
- Azure Data Studio Web 

Steps to Reproduce:

1. Have two notebook links 
2. In the notebook link create a link to the second notebook using copy path or relative path
3. It will prompt user to open in new browser

Expected: 
Should open in a new tab within same ADS web browser.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #16925.

This is a target fix for ADS Web links as we found that the file links would contain `http` scheme and therefore open up the pop dialog to open in a separate browser. The `vscode-remote` handles opening the notebook similar to how it opens using the open file command. We need to use the openerService here directly for it open in a new tab. We also only want to change file links the only condition was to look at the window.location.host and compare to the uri.authority as local file links would be the same as compared to other web links that link to a file. 

cross_linking

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 1]
```diff
@@ -60,6 +61,15 @@ export class LinkHandlerDirective {
 		} catch {
 			// ignore
 		}
+		// Web mode linking to open files
+		if (isWeb) {
+			// only change scheme for file links (file links in web mode scheme are also http)
+			// therefore we will use the authority to understand if its a local file path
+			if (window.location.host === uri.authority) {
+				uri = uri.with({ scheme: 'vscode-remote' });
+				this.openerService.open(uri);
```
Comment (lucyzhang929) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:70]: Should there be a return statement after here so that it doesn't go to the later cases?

**Review by lucyzhang929 — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 2]
```diff
@@ -60,6 +61,15 @@ export class LinkHandlerDirective {
 		} catch {
 			// ignore
 		}
+		// Web mode linking to open files
+		if (isWeb) {
+			// only change scheme for file links (file links in web mode scheme are also http)
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:66]: How/why does a local link get turned into a web link in the first place? Would we not rather find the place that's being done and put this logic there to make the link use the vscode-remote scheme instead?

Comment (VasuBhog) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:66]: The onclick target that we get back formats the href as such: `http://localhost:8000/filepath`. I have looked at where we save the links and output to the user (htmlMarkdownConverter and notebookMarkdown) but in each of these places, we are passing back the file path and not setting the uri. Since that is what we do here in linkHandler by creating the URI we get based on the href of the target. I believe it would be a better change here since it seems the target['href'] we get back is based on the window.location as well.

**Review by barbaravaldez — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:66]: Ok, so it's the web browser doing that then? Makes sense I guess.

**Review by Charles-Gagnon — APPROVED** [review]
