### PR TITLE
fix smoke test failure

### LINKED ISSUE #15268: Smoke tests are failing
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=102103&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d

```
  1) VSCode Smoke Tests (Electron)
       "before each" hook for "can open, connect and execute file":
     TypeError: Cannot read property 'logger' of undefined
```

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #15268 

Not sure how does vscode run their smoke test, that seems to be a bad merge on their side that they have nested test suite with same name, the issue is beforeEach and before have different context (this) because they are created in different suite, the parent suite's beforeEach doesn't have `app` property in its context. 

fix:

remove the unnecessary nested test suite so that all the setup are done within the same context (this object).

### CODE REVIEW

**Review by kburtram — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]

File: test/smoke/src/main.ts [hunk 1]
```diff
@@ -310,30 +310,27 @@ describe(`VSCode Smoke Tests (${opts.web ? 'Web' : 'Electron'})`, () => {
 	// 		setupDataMigrationTests(opts['stable-build'], testDataPath);
 	// 	});
 	// }
+	before(async function () {
+		const app = new Application(this.defaultOptions);
+		await app!.start(opts.web ? false : undefined);
+		this.app = app;
+	});
 
-	describe(`VSCode Smoke Tests (${opts.web ? 'Web' : 'Electron'})`, () => {
```
Comment (Charles-Gagnon) [inline test/smoke/src/main.ts:314]: Actually could you just comment out the nested suite instead and add SQL CARBON EDITs? Makes it easier to do merges later on

**Review by abist — APPROVED** [review]
