### PR TITLE
Fix the select box issue

### LINKED ISSUE #9066: Display name ignored for advanced connection property: Data value used instead
In ADS, when defining a connection option with selectable values (combo box), it is possible to have what the user sees and selects be a different value than what is put in the options object that is sent to sqltoolsservice via Json RPC call. This is evident with the Authentication type.
If a user selects "Windows Authentication"
image
Then "Integrated" is sent as the value to sqltoolsservice.
image
These category values, selectable by the user, are defined in the [package.json](https://github.com/microsoft/azuredatastudio/blob/343daf58fef1a5b08c37efb33e04ec3ef08e3875/extensions/mssql/package.json#L552-L584) and corresponding resource strings in the [package.nls.json](https://github.com/microsoft/azuredatastudio/blob/343daf58fef1a5b08c37efb33e04ec3ef08e3875/extensions/mssql/package.nls.json#L77-L81)
image
image
While this configuration works for authentication type, it does not work for those advanced connection options. An example is the advanced security setting Enclave Attestation Protocol. While a separate display name and value are defined in the same way, ADS ignores the display name and uses the data value for both display and as the value sent to sqltoolsservice back-end.
The following images show that "AAS" and "HGS" are both shown to the user and sent to the back end. The desired behavior would be for "Azure Attestation" and "Host Guardian Service" to be displayed to the user for selection and have "AAS" and "HGS", respectively, sent to the back-end.
image
image
image
image

### PR DESCRIPTION
**Pull request by aaomidi**
This PR allows us to pass in descriptions to the ADS SelectBox

Fixes #9066

### CODE REVIEW

**Comment by aaomidi** [comment]
image

**Comment by aaomidi** [comment]
hdDLua6Ku5

**Comment by aaomidi** [comment]
GByMfMg0UZ

**Comment by Xtrimmer** [comment]
Our PM, Jakub, is telling me that this fix is not what he expected. He wants to show only display names, no keyword names so the behavior is the same as how the other connection properties work. For example": Authentication Type in connection properties. Is this possible?

**Comment by aaomidi** [comment]
We tend to not stray from what VSCode's standards are. @kburtram what do you think?

**Comment by aaomidi** [comment]
image

**Comment by Charles-Gagnon** [comment]
@Xtrimmer How strongly do you prefer this? Because I think I prefer the way VS Code does it. Seeing the actual value used is helpful anyways so users are easily able to map what they would use in an actual connection string to the value they see here.

**Comment by aaomidi** [comment]
Nice I broke all the tests :D

**Comment by aaomidi** [comment]
@Charles-Gagnon a point was made that maybe the developer wants to hide some BLOBs as the actual value.

The PR in its current state doesn't get rid of the description feature.

**Comment by Charles-Gagnon** [comment]
Can you give an example?

**Comment by aaomidi** [comment]
@Charles-Gagnon I don't have a specific example. But this is a thing that HTML for example, supports:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

I think it makes sense to have a display vs "actual" value.

**Comment by aaomidi** [comment]
Although I don't like the hacky solution I have to make the display vs actual value work, so I'd prefer if we didn't diverse too much from vscode.

**Comment by Xtrimmer** [comment]
I don't have any strong feeling either way, our teams PM felt stronger about this and his thinking is that the behavior should be the same as the Sql Server Authentication type selector control. Second he thought the implementation details, such as these enum values, should probably be hidden from the user.

File: src/sql/base/browser/ui/selectBox/selectBox.ts [hunk 1]
```diff
@@ -20,6 +20,10 @@ import { SelectBoxList } from 'vs/base/browser/ui/selectBox/selectBoxCustom';
 const $ = dom.$;
 
 
+export interface SelectOptionItemSQL extends ISelectOptionItem {
+	backendValue: string; // THIS IS REQUIRED, this is the value that will actually be returned on SelectBox#values()
```
Comment (kburtram) [inline src/sql/base/browser/ui/selectBox/selectBox.ts]: In the HTML SELECT control the names of the displayValue vs. actualValue are "Text" and "Value".  Is value already taken for the purpose of Text in the standard control?  I would prefer `value` to `backendValue` if possible to be consistent with standard HTML.

File: extensions/mssql/package.json [hunk 2]
```diff
@@ -687,11 +687,11 @@
           "objectType": null,
           "categoryValues": [
             {
-              "displayName": null,
+              "displayName": "Disabled",
```
Comment (Charles-Gagnon) [inline extensions/mssql/package.json]: Localize display names

File: src/sql/workbench/test/browser/modal/optionsDialogHelper.test.ts [hunk 3]
```diff
@@ -10,9 +10,10 @@ import * as TypeMoq from 'typemoq';
 import * as assert from 'assert';
 import { ServiceOptionType } from 'sql/workbench/api/common/sqlExtHostTypes';
 import { $ } from 'vs/base/browser/dom';
+import { SelectOptionItemSQL } from 'sql/base/browser/ui/selectBox/selectBox';
```
Comment (Charles-Gagnon) [inline src/sql/workbench/test/browser/modal/optionsDialogHelper.test.ts]: Would be good to add testing for value when value and text are different

File: src/sql/base/browser/ui/selectBox/selectBox.ts [hunk 4]
```diff
@@ -60,20 +64,30 @@ export class SelectBox extends vsSelectBox {
 
 	private element?: HTMLElement;
 
-	constructor(options: string[], selectedOption: string, contextViewProvider: IContextViewProvider, container?: HTMLElement, selectBoxOptions?: ISelectBoxOptions) {
-		super(options.map(option => { return { text: option }; }), 0, contextViewProvider, undefined, selectBoxOptions);
+	constructor(options: SelectOptionItemSQL[] | string[], selectedOption: string, contextViewProvider: IContextViewProvider, container?: HTMLElement, selectBoxOptions?: ISelectBoxOptions) {
+		let optionItems: SelectOptionItemSQL[];
+		if (options.length > 0 && typeof options[0] === 'string') {
```
[the remark this answers is not in the document]
Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: I don't think you can typecheck like that on runtime.

File: src/sql/workbench/test/browser/modal/optionsDialogHelper.test.ts (hunk 3 above)
Comment (aaomidi) [reply src/sql/workbench/test/browser/modal/optionsDialogHelper.test.ts]: Done!

Comment (aaomidi) [reply src/sql/workbench/test/browser/modal/optionsDialogHelper.test.ts]: Done!

File: src/sql/base/browser/ui/selectBox/selectBox.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates

Using type predicate functions allows Typescript to do type narrowing - so it'll know that since it isn't a string[] that it must be a SelectOptionItemSQL[] so you can just do `optionItems = options;` on line 74

[the remark this answers is not in the document]
Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: Eh I guess I'm not handling the situation where the option is a non string type so it wouldn't hurt. Hmm

[the remark this answers is not in the document]
Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: I mostly meant it won't actually be doing any type checking, but what you're saying makes sense.
