### PR TITLE
Fix split cell not working with attachments

### LINKED ISSUE #19519: Regression in split cell - Content disappears
- Azure Data Studio Version: 1.36.2
- OS Version:

Steps to Reproduce:

splitnotebookissue

### PR DESCRIPTION
**Pull request by barbaravaldez**
Set attachments to the created cell after splitting a cell. We don't need to remove the attachments, because we clean the unused attachments after updating the cell source .
This PR fixes #19519

### CODE REVIEW

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -651,6 +654,7 @@ export class NotebookModel extends Disposable implements INotebookModel {
 					if (tailSource[0] === '\r\n' || tailSource[0] === '\n') {
 						newlinesBeforeTailCellContent = tailSource.splice(0, 1)[0];
 					}
+					tailCell.attachments = attachments;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:657]: So you're duplicating the attachments in both the original and the new cell? Two questions

1. What about the third cell if there is one? (if you select some text in the middle of a cell and split it'll create 3 cells)
2. We shouldn't just be duplicating the attachments if they don't exist in the cell. An attachment should only exist in the cell it's referenced in (mostly important for embedded images). Do the "extra" attachments get cleaned up when we recreate the attachments on source changing?

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts (hunk 1 above)
Comment (barbaravaldez) [reply src/sql/workbench/services/notebook/browser/models/notebookModel.ts]: I made some changes. Now, I only add the attachment if it's referenced in the cell source and it covers the scenario when the cell splits in 3 parts.

**Comment by chlafreniere** [comment]
@barbaravaldez how about tests 😄

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 2]
```diff
@@ -607,6 +608,8 @@ export class NotebookModel extends Disposable implements INotebookModel {
 						partialSource = source.slice(selection.startLineNumber - 1, selection.startLineNumber)[0].slice(0, selection.startColumn - 1);
 						headsource = headsource.concat(partialSource.toString());
 					}
+					// save attachments before updating the cell contents
+					attachments = this.cells[index].attachments;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:612]: And are you removing the attachments that no longer exist in the original cell?

Comment (barbaravaldez) [reply src/sql/workbench/services/notebook/browser/models/notebookModel.ts:612]: There's not need to remove them because we are updating the original cell source, and it removes the unused attachments here. https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/services/notebook/browser/models/cell.ts#L337

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 3]
```diff
@@ -680,10 +685,22 @@ export class NotebookModel extends Disposable implements INotebookModel {
 		return undefined;
 	}
 
+	private getCellAttachmentFromSource(source: string | string[], attachments: nb.ICellAttachments): nb.ICellAttachments {
+		let newCellAttachment = {};
+		let newSource = Array.isArray(source) ? source.join() : source;
+		for (let key of Object.keys(attachments)) {
+			if (newSource.includes(key)) {
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/services/notebook/browser/models/notebookModel.ts:692]: that makes sense. Let me update that

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/notebook/browser/models/notebookModel.ts:612]: Oh cool, a couple things : 

1. Please say that in a comment here
2. Look into re-using the logic for that cleanup function in the new "get cell attachments" function you have. At the very least this regex there should be used in both places to find the attachment keys in the source and can be shared

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 4]
```diff
@@ -680,10 +685,22 @@ export class NotebookModel extends Disposable implements INotebookModel {
 		return undefined;
 	}
 
+	private getCellAttachmentFromSource(source: string | string[], attachments: nb.ICellAttachments): nb.ICellAttachments {
+		let newCellAttachment = {};
+		let newSource = Array.isArray(source) ? source.join() : source;
+		for (let key of Object.keys(attachments)) {
+			if (newSource.includes(`![${key}](attachment:${key})`)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:692]: It would be preferable to use the same regex that https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/services/notebook/browser/models/cell.ts#L337 uses

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (MaddyDev) [reply src/sql/workbench/services/notebook/browser/models/notebookModel.ts]: No, we only have one way of specifying them through attachment:$name and referencing them from metadata.

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/notebook/browser/models/notebookModel.ts:612]: @barbaravaldez Make sure you add the comment about how we're not modifying the original cell because it already goes through the cleanup process when the source is changed.

File: src/sql/workbench/services/notebook/browser/models/cell.ts [hunk 5]
```diff
@@ -358,12 +358,8 @@ export class CellModel extends Disposable implements ICellModel {
 		return newSource;
 	}
 
-	/**
-	 * Cleans up the attachments, removing any ones that aren't being currently used in the specified source string.
-	 * @param source The new source string to check for attachments being used
-	 */
-	private cleanUnusedAttachments(source: string): void {
-		const originalAttachments = this._attachments;
+	public updateAttachmentsFromSource(source: string, attachments?: nb.ICellAttachments): void {
```
[the remark this answers is not in the document]
Comment (barbaravaldez) [reply src/sql/workbench/services/notebook/browser/models/cell.ts:361]: yup, will do :)

**Review by MaddyDev — APPROVED** [review]
+1 on tests. Looks good
