### PR TITLE
Fix/replace wrong imports

### LINKED ISSUE #7149: Wrong imports being used
Something from 'browser' is using this file, which then tries to get import('fs'). This isn't allowed.

Getting rid of 'fs', or splitting the functionality to two files would work here.

https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts#L6

### PR DESCRIPTION
**Pull request by MaddyDev**
replaced fs with IFileService.
Fixes #7149

### CODE REVIEW

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 1]
```diff
@@ -197,7 +199,7 @@ export class NotebookMarkdownRenderer {
 			// ignore
 		}
 		let originIndependentUrl = /^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;
-		if (base && !originIndependentUrl.test(href) && !fs.existsSync(href)) {
+		if (base && !originIndependentUrl.test(href) && (!URI.isUri(href) || !this.fileService.exists(URI.parse(href)))) {
```
Comment (anthonydresser) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: exists returns a promise

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 2]
```diff
@@ -13,13 +12,16 @@ import * as marked from 'vs/base/common/marked/marked';
 import { defaultGenerator } from 'vs/base/common/idGenerator';
 import { revive } from 'vs/base/common/marshalling';
 import { MarkdownRenderOptions } from 'vs/base/browser/markdownRenderer';
+import { IFileService } from 'vs/platform/files/common/files';
+import { promisify } from 'util';
```
Comment (anthonydresser) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: unused import?

File: src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts [hunk 3]
```diff
@@ -709,7 +709,9 @@ export class MainThreadNotebookDocumentsAndEditors extends Disposable implements
 				if (result) {
 					if (result.next.scheme === Schemas.untitled) {
 						let untitledNbName: URI = URI.parse(`untitled:${path.basename(result.next.path)}`);
-						this.doOpenEditor(untitledNbName, { initialContent: fs.readFileSync(result.next.path).toString(), initialDirtyState: false });
+						this.fileService.readFile(URI.parse(result.next.path)).then(content => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts]: You're in an async function - just await readFile then call doOpenEditor

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 4]
```diff
@@ -197,7 +199,7 @@ export class NotebookMarkdownRenderer {
 			// ignore
 		}
 		let originIndependentUrl = /^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;
-		if (base && !originIndependentUrl.test(href) && !fs.existsSync(href)) {
+		if (base && !originIndependentUrl.test(href) && (!URI.isUri(href) || !this.existsSync(URI.parse(href)))) {
```
Comment (anthonydresser) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: this doesn't make it sync, there is no way to make a asynchronous function synchronous

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 5]
```diff
@@ -199,7 +199,7 @@ export class NotebookMarkdownRenderer {
 			// ignore
 		}
 		let originIndependentUrl = /^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;
-		if (base && !originIndependentUrl.test(href) && (!URI.isUri(href) || !this.existsSync(URI.parse(href)))) {
+		if (base && !originIndependentUrl.test(href) && (!URI.isUri(href) || !this.exists(URI.parse(href)))) {
```
Comment (aaomidi) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: exists returns a promise that's not being awaited

File: src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts [hunk 6]
```diff
@@ -721,7 +722,8 @@ export class MainThreadNotebookDocumentsAndEditors extends Disposable implements
 				if (result) {
 					if (result.previous.scheme === Schemas.untitled) {
 						let untitledNbName: URI = URI.parse(`untitled:${path.basename(result.previous.path)}`);
-						this.doOpenEditor(untitledNbName, { initialContent: fs.readFileSync(result.previous.path).toString(), initialDirtyState: false });
+						let content = await this.fileService.readFile(URI.parse(result.previous.path));
+						this.doOpenEditor(untitledNbName, { initialContent: content.value.toString(), initialDirtyState: false });
```
Comment (aaomidi) [inline src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts]: doOpenEditor returns a promise

Comment (MaddyDev) [reply src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts]: nothing new I added here. Anyway we're not using the returned value and this is the last operation.

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 7]
```diff
@@ -199,7 +198,7 @@ export class NotebookMarkdownRenderer {
 			// ignore
 		}
 		let originIndependentUrl = /^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;
-		if (base && !originIndependentUrl.test(href) && (!URI.isUri(href) || !this.exists(URI.parse(href)))) {
+		if (base && !originIndependentUrl.test(href) && (!URI.isUri(href) || !(async () => await this.fileService.exists(URI.parse(href))))) {
```
Comment (aaomidi) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: This doesn't fix the issue, you're still going to get a Promise from this. Because your code isn't in an async block, you need to use a .then() on it.

You can't make an async function synchronous.

File: src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts (hunk 6 above)
Comment (aaomidi) [reply src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts]: It's important in this scenario, because you don't guarantee that the notebook will be open by the time this method ends. doOpenEditor will be scheduled to run on the either the next or end of current poll - rather than during the execution of this method.

It creates issues like the one in #7064 

It's either something we need to solve in this PR or create another issue for it.

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts (hunk 7 above)
Comment (MaddyDev) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: isn't await doing the same thing? awaits until the promise is returned?

Comment (aaomidi) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: Nope. You've created an anonymous async function that'll run in the next/end of current event loop. Essentially that if statement will just check if a Promise is returned (which will always be true).

Try this in the chrome console:

``` javascript
const anonymousFunction = (async () => false);

const normalFunction2 = () => {
    if((async () => await anonymousFunction())){
        console.log('boop');
    } else {
        console.log('expected outcome?');
    }
};
normalFunction();

```

Comment (Charles-Gagnon) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: Not quite. Since this returns a promise you're just checking that the promise is truthy. You need to get the value FROM the promise which as Amir said requires using .then since this is in a non-async function (you can't await)

File: src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts (hunk 6 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts]: Is that really what's causing those problems? Why does it matter if the notebook is actually opened when this function finishes?

A small potential issue is that if the switching takes a while then quickly clicking "next" or "previous" could cause issues - but that's separate I'd think.

Comment (aaomidi) [reply src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts]: I think as a general rule of thumb, if we're using functions that return a promise we should either await, .then, or return them.

I'm not saying this specific one is causing issues, but not following that rule can cause regressions down the line. 

I'm currently looking for an eslint rule to warn when you don't await these functions.

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 8]
```diff
@@ -197,9 +198,11 @@ export class NotebookMarkdownRenderer {
 			// ignore
 		}
 		let originIndependentUrl = /^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;
-		if (base && !originIndependentUrl.test(href) && !fs.existsSync(href)) {
-			href = this.resolveUrl(base, href);
-		}
+		this.fileService.exists(URI.file(href)).then(exists => {
```
Comment (anthonydresser) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: How this is written theres a chance that the code that is in the then will not actually affect href in time to affect the rest of the function. You should either use await there, or move the entire rest of the function into the then callback.

Comment (aaomidi) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: Oh didn't notice this. Yeah the entire rest of the code should be enclosed in the bracket opened in line 201. (or callbackify)

Comment (MaddyDev) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: I cannot use await since it's not async function. You mean this:
image

Comment (MaddyDev) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: I don't want to return null at the end but there isn't way to avoid that. That would still cause the same issue right?

Comment (MaddyDev) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: Thanks for catching that! Fixed it.

File: src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts [hunk 9]
```diff
@@ -329,7 +328,8 @@ export class MainThreadNotebookDocumentsAndEditors extends Disposable implements
 		@IEditorService private _editorService: IEditorService,
 		@IEditorGroupsService private _editorGroupService: IEditorGroupsService,
 		@ICapabilitiesService private _capabilitiesService: ICapabilitiesService,
-		@INotebookService private readonly _notebookService: INotebookService
+		@INotebookService private readonly _notebookService: INotebookService,
+		@IFileService private readonly fileService: IFileService
```
Comment (chlafreniere) [inline src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts]: please use an underscore before the variable name to stay consistent with other private variables here

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 10]
```diff
@@ -13,13 +12,15 @@ import * as marked from 'vs/base/common/marked/marked';
...
 import { MarkdownRenderOptions } from 'vs/base/browser/markdownRenderer';
+import { IFileService } from 'vs/platform/files/common/files';
 
 // Based off of HtmlContentRenderer
 export class NotebookMarkdownRenderer {
 	private _notebookURI: URI;
 	private _baseUrls: string[] = [];
 
-	constructor() {
+	constructor(@IFileService private readonly fileService: IFileService) {
```
Comment (chlafreniere) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: may want an _ before fileService

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 11]
```diff
@@ -59,7 +60,7 @@ export class NotebookMarkdownRenderer {
 		let signalInnerHTML: () => void;
 		const withInnerHTML = new Promise(c => signalInnerHTML = c);
 
-		let notebookFolder = path.dirname(this._notebookURI.path) + '/';
+		let notebookFolder = path.dirname(this._notebookURI.fsPath) + '/';
```
Comment (chlafreniere) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: Can we do path.join here? As I recall there's a property in path you can avoid hardcoding '/'

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 12]
```diff
@@ -197,15 +198,17 @@ export class NotebookMarkdownRenderer {
...
-			href = this.resolveUrl(base, href);
-		}
-		try {
-			href = encodeURI(href).replace(/%25/g, '%');
-		} catch (e) {
-			return null;
-		}
-		return href;
+		return this.fileService.exists(URI.file(href)).then(exists => {
+			if (base && !originIndependentUrl.test(href) && !exists) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: As discussed this needs to return the href itself. 

I'd suggest adding a return type to this method so that mistake isn't made again in the future. The return type should just be string | undefined

Comment (MaddyDev) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: I removed the file exists check and alternatively am checking if the path is absolute since we call the resolve url only for relative paths.

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts (hunk 11 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: Yes, we should be using path.sep for this. 

---
In reply to: [323447857](https://github.com/microsoft/azuredatastudio/pull/7158#discussion_r323447857) [](ancestors = 323447857)

**Comment by Charles-Gagnon** [comment]
> 				this._baseUrls[' ' + base] = base + '/';

Here's another place where we're hardcoding the path separator. You don't have to fix it in this PR but please open an issue to get this fixed

---
Refers to: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts:218 in 2676694. [](commit_id = 26766946a96b6c317aa745047e6d46dd756c991d, deletion_comment = False)

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 13]
```diff
@@ -102,7 +102,7 @@ export class NotebookMarkdownRenderer {
 			return '<img ' + attributes.join(' ') + '>';
 		};
 		renderer.link = (href: string, title: string, text: string): string => {
-			href = this.cleanUrl(!markdown.isTrusted, notebookFolder, href);
+			let returnedValue = this.cleanUrl(!markdown.isTrusted, notebookFolder, href);
 			if (href === null) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: You never use returnedValue? Why aren't you setting href = this.cleanUrl(...)?

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 14]
```diff
@@ -59,13 +59,13 @@ export class NotebookMarkdownRenderer {
...
 
-		let notebookFolder = path.dirname(this._notebookURI.path) + '/';
+		let notebookFolder = path.dirname(this._notebookURI.fsPath) + '/';
 		if (!this._baseUrls.includes(notebookFolder)) {
 			this._baseUrls.push(notebookFolder);
 		}
 		const renderer = new marked.Renderer({ baseUrl: notebookFolder });
 		renderer.image = (href: string, title: string, text: string) => {
-			href = this.cleanUrl(!markdown.isTrusted, notebookFolder, href);
+			href = this.cleanUrl(!markdown.isTrusted, notebookFolder, href).toString();
```
Comment (aaomidi) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: this.cleanUrl() has a chance to return null. Need to check that before doing a toString();

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts (hunk 13 above)
Comment (MaddyDev) [reply src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: I was testing something and forgot to change things back :(

File: src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts [hunk 15]
```diff
@@ -214,7 +215,7 @@ export class NotebookMarkdownRenderer {
 			// but we might need to add _that_
 			// https://tools.ietf.org/html/rfc3986#section-3
 			if (/^[^:]+:\/*[^/]*$/.test(base)) {
-				this._baseUrls[' ' + base] = base + '/';
+				this._baseUrls[' ' + base] = path.join(base, path.sep);
 			} else {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts]: Actually this whole method is assuming that the path separator is /. So I'd revert this change and then just create an issue and we can follow up on that later (it might not even be an actual issue - not sure if these are ever going to be encoded with platform-specific path separators)
