### PR TITLE
Fix project name validation

### LINKED ISSUE #22523: SQL Proj name validation message incorrect
In the name validation for a new SQL Project if you type in `/` or `\` alone then it shows up with this error message even though there's non-whitespace characters there.

image

### LINKED ISSUE #22524: Creating new sql project with invalid characters creates project with blank name
1. Open create new database project wizard
2. Enter in project name with invalid characters - such as `abc\/`
3. Click OK and restart ADS

Expected: It should probably stop you from entering the characters in the first place
Actual: Project is created, but it just has an empty name (`.sqlproj`) - so it doesn't even have any of the valid characters in the name

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #22523.
The underlying problem was the filename used for validation was been parsed to remove appended path, but the code was only testing the filename. Hence "/" and "\\" were been removed from validation altogether. This PR updates the code to take the filename and test it directly, instead of using the parsed base name.
The change in validation is valid for project names while creating new project and creating new project from database.

This PR also fixes #22524. Before the changes, the names with "/", "\\" characters were not throwing an error, hence the project was getting created with empty name (and within another folder). After these changes, the code throws error for these characters, hence creation of project with these filenames is suppressed.

Before (incorrect error):
image
After:
image

Before (no error):
image
After:
image

Before (no error):
image
After:
image

### CODE REVIEW

File: extensions/data-workspace/src/common/pathUtilsHelper.ts [hunk 1]
```diff
@@ -49,42 +48,41 @@ export function sanitizeStringForFilename(s: string): string {
 /**
  * Returns true if the string is a valid filename
  * Logic is copied from src\vs\base\common\extpath.ts
- * @param name filename to check
+ * @param fileName filename to check (without file path)
  */
-export function isValidBasename(name?: string): boolean {
+export function isValidBasename(fileName?: string): boolean {
```
Comment (Charles-Gagnon) [inline extensions/data-workspace/src/common/pathUtilsHelper.ts:53]: Instead of having two functions doing the same kinds of checks it would be easier to have the error message one return undefined if it's a valid basename and then this can just call that and test for if the message is undefined.

File: extensions/data-workspace/src/common/constants.ts [hunk 2]
```diff
@@ -67,7 +67,7 @@ export const whitespaceFilenameErrorMessage = localize('whitespaceFilenameErrorM
 export const invalidFileCharsErrorMessage = localize('invalidFileCharsErrorMessage', "Invalid file characters");
 export const reservedWindowsFilenameErrorMessage = localize('reservedWindowsFilenameErrorMessage', "This file name is reserved for use by Windows. Choose another name and try again");
 export const reservedValueErrorMessage = localize('reservedValueErrorMessage', "Reserved file name. Choose another name and try again");
-export const trailingWhitespaceErrorMessage = localize('trailingWhitespaceErrorMessage', "File name cannot end with a whitespace");
+export const trailingWhitespaceErrorMessage = localize('trailingWhitespaceErrorMessage', "File name cannot start or end with a whitespace");
```
Comment (Benjin) [inline extensions/data-workspace/src/common/constants.ts:70]: Nit: should be "end with whitespace" or "end with a whitespace character".  I think I like the first one better.

File: extensions/data-workspace/src/common/pathUtilsHelper.ts (hunk 1 above)
Comment (SakshiS-harma) [reply extensions/data-workspace/src/common/pathUtilsHelper.ts:53]: Completely makes sense. Updated the code appropriately.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by kisantia — APPROVED** [review]
