### PR TITLE
Fix for Edit Data grid newline on multiline strings

### LINKED ISSUE #22170: Edit Data Corrupts Multiline Varchars
Issue Type: <b>Bug</b>

1. Select "Edit Data" for a table with a multiline varchar column.
2. Edit the multiline varchar field. (I was editing a many-line JSON  column, at the very end, trying to remove a trailing comma.)
3. Observe that newlines and tabs are replaced with ASCII NUL chars.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (19.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### PR DESCRIPTION
**Pull request by smartguest**
PR adds proper regex for replacing null characters after an edit.

It adds a check to see if the unicode null character exists in a pre-edit string or not. If it does, you will not be able to edit it and the cell's text will be highlighted in yellow along with an warning explaining why you cannot edit the cell if it is selected, either automatically upon launch if it's the first cell or when a user tries to click it. (although I am not able to test this scenario in SSMS as I found it was not possible to add it via SSMS to a SQL server) 

Also removes row number in loadItem as it's not being used at all and does not exist on Slickgrid.

Initial screen with comparison to SSMS:
EditDataScreenshotDefault

Screen while editing multiline cell:
EditDataScreenshotEdit

Screen after editing multiline cell:
EditDataScreenshotPostEdit

Hypothetical (test scenario without checks) screen of a cell containing the unicode null character (message has been changed slightly to say it contains the unicode null character and that it is not supported for editing):
Invalid Cell Click Mockup

This PR fixes #22170

### CODE REVIEW

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 1]
```diff
@@ -476,6 +479,7 @@ export class EditDataGridPanel extends GridParentComponent {
 		if (newlineMatches && newlineMatches.length > 0) {
 			this.newlinePattern = newlineMatches[0];
 		}
+		// allow-any-unicode-next-line
```
Comment (aasimkhan30) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:482]: Nit: You are not just allowing but replacing unicode next line with null

**Review by aasimkhan30 — APPROVED** [review]

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 2]
```diff
@@ -1126,9 +1132,19 @@ export class EditDataGridPanel extends GridParentComponent {
...
+	onBeforeEditCell(event: Slick.OnBeforeEditCellEventArgs<any>): boolean {
+		let result = true;
 		this.logService.debug('onBeforeEditCell called with grid: ' + event.grid + ' row: ' + event.row
 			+ ' cell: ' + event.cell + ' item: ' + event.item + ' column: ' + event.column);
+
+		let itemToEdit = event.item[event.cell].displayValue;
+
+		if (Services.DBCellValue.isDBCellValue(itemToEdit) && itemToEdit.displayValue.indexOf('\u0000') !== -1) {
+			result = false;
+			this.notificationService.warn(cellWithNullMessage);
```
Comment (aasimkhan30) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1144]: Is this the best way to warn the users? I don't know if warning or error is more apt in this scenario

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 3]
```diff
@@ -37,6 +37,9 @@ import * as DOM from 'vs/base/browser/dom';
 import { onUnexpectedError } from 'vs/base/common/errors';
 import { IAccessibilityService } from 'vs/platform/accessibility/common/accessibility';
 import { IQuickInputService } from 'vs/platform/quickinput/common/quickInput';
+import { localize } from 'vs/nls';
+
+const cellWithNullMessage = localize('editData.cellWithNullMessage', "This cell contains the Unicode null character which is currently not supported for editing.");
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:42]: does SSMS also show this error?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 4]
```diff
@@ -84,7 +87,7 @@ export class EditDataGridPanel extends GridParentComponent {
 	public onCellEditEnd: (event: Slick.OnCellChangeEventArgs<any>) => void;
 	public onIsCellEditValid: (row: number, column: number, newValue: any) => boolean;
 	public onIsColumnEditable: (column: number) => boolean;
-	public overrideCellFn: (rowNumber, columnId, value?, data?) => string;
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:87]: why removing the rowNumber parameter?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:482]: This is telling the hygiene check to specifically ignore the `allow-any-unicode` rule on the next line. That rule flags any code that has unicode symbols in it 

https://github.com/Microsoft/azuredatastudio/blob/8a3d08f0dec1cdf47d7fc442f90fb2227b828375/build/hygiene.js#L44

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 4 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:87]: As I mentioned, it's only being called by loadItem, which does not have the rowNumber either, it was also not being used at all in the funciton

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 2 above)
Comment (kburtram) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1144]: Ideally this scenario never/rarely occurs, so I'm not sure a notification is too disruptive.  Ideally, showing some type of warning indicator directly on the cell would be better, but maybe overkill for rare corner-case.

File: src/sql/workbench/contrib/editData/browser/media/editData.css [hunk 5]
```diff
@@ -97,6 +97,11 @@
 	font-style: italic
 }
 
+.editDataGrid .slick-cell .grid-cell-value-container.contains-null-char-cell {
+	background-color: var(--color-cell-invalid-cell, rgb(215, 230, 16));
+	color: black
```
[the remark this answers is not in the document]
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/media/editData.css:102]: I will try to include other colors as part of the styling

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 3 above)
Comment (kburtram) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:42]: Not sure if it matters if SSMS has this check, unless we have a reason to believe it could never occur.  If there are existing null characters in the string they will be changed to newlines, which is incorrect.

**Review by kburtram — COMMENTED** [review]
Looks good but there are a few things to follow-up on before merging.

File: src/sql/workbench/contrib/editData/browser/media/editData.css (hunk 5 above)
[the remark this answers is not in the document]
Comment (kburtram) [reply src/sql/workbench/contrib/editData/browser/media/editData.css:102]: not sure we need to change the cell style if we're going to keep the notification, but if we are let's use colors from the current theme.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 2 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1144]: It is a warning as this is expected to happen and also given the current state of Edit Data, although yes an icon on the cell would be the best thing to do.

**Comment by smartguest** [comment]
@kburtram I wasn't able to repro it on SSMS as I attempted numerous times to add the null character to my SQL database without success. If there is a way of doing so, please let me know and I'll test it on both SSMS and here.

File: src/sql/workbench/contrib/editData/browser/media/editData.css (hunk 5 above)
[the remark this answers is not in the document]
Comment (alanrenmsft) [reply src/sql/workbench/contrib/editData/browser/media/editData.css:102]: yes, I guess it is ok to not have any visual difference on this type of cell.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 6]
```diff
@@ -643,7 +647,9 @@ export class EditDataGridPanel extends GridParentComponent {
 					? self.rowIdMappings[self.currentCell.row]
 					: self.currentCell.row;
 
-				return self.dataService.updateCell(sessionRowId, self.currentCell.column - 1, this.newlinePattern ? self.currentEditCellValue.replace('\u0000', this.newlinePattern) : self.currentEditCellValue);
+				// allow-any-unicode-next-line
+				let restoredValue = this.newlinePattern ? self.currentEditCellValue.replace(/\u0000/g, this.newlinePattern) : self.currentEditCellValue;
```
[the remark this answers is not in the document]
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:651]: Yes, there is no easy fix for this scenario as the index will shift around frequently if editing if we try to track where the line breaks were originally

[the remark this answers is not in the document]
Comment (alanrenmsft) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:651]: well, if we really want, we can keep the index of all the line breaks and their original value and restore them accordingly. Personally, I think it is rare to have mixed line breaks, so currently implementation should be good.

[the remark this answers is not in the document]
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: For now, I have it so each type of line break is replaced with a different character, arrows for /n and /r and null for /r/n

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 7]
```diff
@@ -474,9 +477,10 @@ export class EditDataGridPanel extends GridParentComponent {
 	private replaceLinebreaks(inputStr: string): string {
 		let newlineMatches = inputStr.match(/(\r\n|\n|\r)/g);
 		if (newlineMatches && newlineMatches.length > 0) {
-			this.newlinePattern = newlineMatches[0];
+			this.hasNewline = true
 		}
-		return inputStr.replace(/(\r\n|\n|\r)/g, '\u0000');
+		// allow-any-unicode-next-line
+		return inputStr.replace(/\r\n/g, '\u0000').replace(/\n/g, '↵').replace(/\r/g, '⏎');
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:483]: I don't think this is a good solution. I'd just keep the current behavior. if you really want to make it work, you should adopt the approach I mentioned earlier.
cons of this implementation:
1. there are more scenarios you have to raise the unsupported error, previously it is only the NULL value, now you are adding 2 more.
2. inconsistent, some line breaks are visible and some are not.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 8]
```diff
@@ -1126,9 +1136,20 @@ export class EditDataGridPanel extends GridParentComponent {
...
-	onBeforeEditCell(event: Slick.OnBeforeEditCellEventArgs<any>): void {
+	onBeforeEditCell(event: Slick.OnBeforeEditCellEventArgs<any>): boolean {
+		let result = true;
 		this.logService.debug('onBeforeEditCell called with grid: ' + event.grid + ' row: ' + event.row
 			+ ' cell: ' + event.cell + ' item: ' + event.item + ' column: ' + event.column);
+
+		let itemToEdit = event.item[event.cell].displayValue;
+
+		// allow-any-unicode-next-line
+		if (Services.DBCellValue.isDBCellValue(itemToEdit) && (itemToEdit.displayValue.indexOf('\u0000') !== -1 || itemToEdit.displayValue.indexOf('↵') !== -1 || itemToEdit.displayValue.indexOf('⏎') !== -1)) {
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1147]: we only need to block the editing if the value contains NULL and line break at the same time.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 9]
```diff
@@ -1126,9 +1130,34 @@ export class EditDataGridPanel extends GridParentComponent {
...
 
-	onBeforeEditCell(event: Slick.OnBeforeEditCellEventArgs<any>): void {
+	onBeforeEditCell(event: Slick.OnBeforeEditCellEventArgs<any>): boolean {
+		let result = true;
 		this.logService.debug('onBeforeEditCell called with grid: ' + event.grid + ' row: ' + event.row
 			+ ' cell: ' + event.cell + ' item: ' + event.item + ' column: ' + event.column);
+
+		let itemToEdit = event.item[event.cell].displayValue;
+
+		if (Services.DBCellValue.isDBCellValue(itemToEdit)) {
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1140]: I am not sure why do we have so many different cases to handle, but in line above, the `itemToEdit` is set to `event.item[event.cell].displayValue` and the next line you are calling `itemToEdit.displayValue`, which does seem to be correct, so only branch will actually be used is `typeof itemToEdit === string`.

please simplify the code if the other scenarios are not needed, otherwise, please test the other scenarios.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 10]
```diff
@@ -1161,6 +1190,7 @@ export class EditDataGridPanel extends GridParentComponent {
 		}
 		else if (Services.DBCellValue.isDBCellValue(value)) {
 			valueToDisplay = (value.displayValue + '');
+			valueToDisplay = valueToDisplay.replace(/(\r\n|\n|\r)/g, '\u0000');
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1193]: is this really needed? line breaks won't be displayed anyway, right?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 11]
```diff
@@ -1126,9 +1130,34 @@ export class EditDataGridPanel extends GridParentComponent {
...
+
+		if (!result) {
+			this.notificationService.warn(cellWithNullCharMessage);
+		}
+
+		return result;
+	}
+
+	private hasNullAndLinebreak(inputString: string): boolean {
+		let linebreakMatch = inputString.match(/(\r\n|\n|\r)/g);
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1159]: please do null check.

Comment (alanrenmsft) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1159]: also, I think you can remove the `/g` option, the match should return as soon as the first match is found, no need to find all the matches.

**Comment by smartguest** [comment]
Due to enormous complexity of keeping indexes on the newlines (accounting for different types of newlines and deletion scenarios such as determining whether a user deleted one newline or an adjacent one) and the fact that mixed multiline characters are a rare scenario, I have decided to let the current format stay as is for now

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 9 above)
Comment (alanrenmsft) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1140]: I don't think I am following. please make sure all the code path are tested, especially this PR needs to be ported to release branch.

Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1140]: What I meant to say is, after editing a cell, it would replace the DBcell value with a text value until you refresh the grid. 

If you were to edit the same cell again, it would be in the form of a string instead of a DBCell. So yes, the different paths are needed. 

Just tested them, so far, all paths work fine, although the .text one is not hit on my table. (This is meant to be consistent with the column formatter which handles this as well). It should work if the cell contains that value.

Comment (alanrenmsft) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1140]: I assume you have some local changes not pushed, I am still seeing the displayValue being called twice.

Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1140]: That is correct Alan.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 10 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1193]: They will actually, if you don't do this check, this will happen:

image

It doesn't match what is shown in SSMS, so yes it is needed.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 12]
```diff
@@ -1126,9 +1130,37 @@ export class EditDataGridPanel extends GridParentComponent {
 		});
 	}
 
-	onBeforeEditCell(event: Slick.OnBeforeEditCellEventArgs<any>): void {
+	onBeforeEditCell(event: Slick.OnBeforeEditCellEventArgs<any>): boolean {
+		let result = true;
 		this.logService.debug('onBeforeEditCell called with grid: ' + event.grid + ' row: ' + event.row
 			+ ' cell: ' + event.cell + ' item: ' + event.item + ' column: ' + event.column);
+
+		let itemToEdit = event.item[event.cell];
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1138]: please add comment explaining the scenarios when the itemToEdit could be a dbcellvalue or string or even an object with `text` property.

**Review by alanrenmsft — APPROVED** [review]
overall looks good to me, please do thorough testing to avoid needing a hotfix.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 12 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1138]: Will do so, and even in the column formatter as well.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (kburtram) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:649]: I don't suggest fixing in this PR.  Let's keep this as a known issue for now.

**Review by kburtram — APPROVED** [review]
Seems good.  If you're done testing please merge and open the port to the release branch.
