### PR TITLE
fix sorting bug

### LINKED ISSUE #17633: Inconsistent/Unexpected Results: Sorting Query Results with Nulls in SQL Notebook
Issue Type: <b>Bug</b>

When SQL notebook query results return NULLs, "Sort Ascending" and "Sort Descending" functions in the query results table yield inconsistent and unexpected results.

**Sample Query:**

```SQL
DROP TABLE IF EXISTS #Temp_A
DROP TABLE IF EXISTS #Temp_B;

CREATE TABLE #Temp_A
(
    id char(3),
    first_name VARCHAR(30)
)

CREATE TABLE #Temp_B
(
    id char(3),
    sales numeric(19,4)
)

INSERT INTO #Temp_A
VALUES 
('1', 'eric'),
('2', 'bob'),
('3', 'sally'),
('4', 'joe'),
('5', 'nancy'),
('6', 'frank'),
('7', 'alice'),
('8', 'rico')

INSERT INTO #Temp_B
VALUES
('1', '200000'),
('5', '60000'),
('7', '750000'),
('4', '250000'),
('8', '130000')

SELECT
    a.id,
    a.first_name,
    SUM(b.sales) as Sum_Sales
FROM
    #Temp_A as a
    LEFT OUTER JOIN #Temp_B as b
        ON a.id = b.id
GROUP BY
    a.id,
    a.first_name
ORDER BY
    id ASC
```
**Initial Results**
image

**Actual Results after "Sort Ascending"**
image
image

**Expected Results after "Sort Ascending"**
image

**Actual Results after "Sort Descending"**
image

**Expected Results after "Sort Descending"**
image

I should note that the results seem to be inconsistent - after alternating between "Sort Ascending" and "Sort Descending" numerous times, eventually I am able to manipulate the results to this, with all NULLS finally grouped together, at which point a subsequent "Sort Ascending" or "Sort Descending" operation finally returns the desired result (after _many_ clicks).

image

These results are unexpected, and can be difficult to catch when a query returns more than ≈ a dozen rows.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (4.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.3.0

</details>

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #17633

root cause
1. the current implementation relies on the sample data (the first row in the data set) to determine the  column type, it works well for certain scenarios, but for scenarios described in issue above, it will produce inconsistent results.
2. we are treating Null as a string (using its display value) when sorting, when sorting with strings the results will be wrong.

fix:
1. use the order: undefined -> number -> string to sort the values which will produce consistent results.
2. treat null as a special value

new results using the example provided in the issue:
image

image

results with mixed values: null, empty string, string, number

image

image

### CODE REVIEW

File: src/sql/base/browser/ui/table/tableDataView.ts [hunk 1]
```diff
@@ -24,26 +24,33 @@ function defaultCellValueGetter(data: any): any {
...
+		const value1 = cellValueGetter(a[field]);
+		const value2 = cellValueGetter(b[field]);
+		const isValue1Number = !isNaN(Number(value1));
+		const isValue2Number = !isNaN(Number(value2));
+		// Order: undefined -> number -> string
+		if (value1 === undefined || value2 === undefined) {
+			return value1 === value2 ? 0 : (value1 === undefined ? -1 : 1);
+		} else if (isValue1Number || isValue2Number) {
+			if (isValue1Number && isValue2Number) {
+				const num1 = Number(value1);
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/table/tableDataView.ts:43]: You could also just calculate this and store it above since you're already calling this on 36&37

**Review by Charles-Gagnon — APPROVED** [review]

**Review by chlafreniere — APPROVED** [review]
