### PR TITLE
fix timeout warning when exiting create function

### LINKED ISSUE #18925: SQL bindings add timed out
Version: 1.66.0 (Universal)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

Steps to Reproduce:

1. Open a folder with a subfolder where an existing Azure Functions project resides, along with the .vscode folder
> - root/
>   - api/
>     - .vscode/
>     - functions.csproj
2. connect to a server in object explorer, right click a table and select "create Azure Function with SQL binding"
3. select output binding, then "cancel" (should be no) on the prompts to initialize the folder for use with vscode and to override the SqlConnectionString setting
4. 
image

(doesn't occur when function project etc is at the root)

### LINKED ISSUE #18927: Timed out waiting for function project to be created
1. Close all folders/workspaces
2. Right click on table and select "Create Azure Function with SQL binding"
3. Choose to create a new project
4. On the "Select a language" step just wait a while - eventually this timeout message will appear

We shouldn't be starting the timeout timer if the user still has information to enter since they can take as long as they want for that.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #18925 and fixes #18927.

This will not show any error if a user exits out of a create an azure function with SQL binding quick pick or create azure function.
In order to know when a user cancels out of the prompt we would need to use the timeout error to understand that it was canceled since that would result in the promise.race rejecting with timeout error. As such we can log this using the errorType we get and still capture any other errors that may potentially happen and send telemetry for it.

### CODE REVIEW

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 1]
```diff
@@ -139,19 +139,26 @@ export async function createAzureFunction(connectionString: string, schema: stri
...
 		} catch (e) {
+			let errorType = utils.getErrorType(e);
 			propertyBag.quickPickStep = quickPickStep;
-			exitReason = 'error';
 			void vscode.window.showErrorMessage(utils.getErrorMessage(e));
 
-			TelemetryReporter.createErrorEvent(TelemetryViews.CreateAzureFunctionWithSqlBinding, TelemetryActions.exitCreateAzureFunctionQuickpick, undefined, utils.getErrorType(e))
+			if (errorType === 'TimeoutError') {
+				// timeout error will only happen if the user cancels the wizard
+				console.log('User cancelled out of the create Azure Function with SQL Binding wizard');
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:156]: This is not necessarily true - we don't know why the project may not have been found. A couple other scenarios that we should expect could happen : 

1. The project file is just taking a really long time to be made for some reason (unlikely but possible)
2. An error occurred in the createFunction call but didn't result in an actual error being thrown
3. The project was created but not added to the workspace

So unless we're able to get the AF extension to tell us specifically when the user cancelled out vs anything else happening we should just log a generic message about the search timing out.

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 2]
```diff
@@ -139,19 +139,26 @@ export async function createAzureFunction(connectionString: string, schema: stri
 			});
 
 			// check for the new function file to be created and dispose of the file system watcher
-			const timeoutForFunctionFile = utils.timeoutPromise(constants.timeoutAzureFunctionFileError);
+			const timeoutForFunctionFile = utils.timeoutPromise('');
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:142]: Why are you removing the string here?

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 3]
```diff
@@ -139,19 +139,26 @@ export async function createAzureFunction(connectionString: string, schema: stri
...
-			exitReason = 'error';
 			void vscode.window.showErrorMessage(utils.getErrorMessage(e));
 
-			TelemetryReporter.createErrorEvent(TelemetryViews.CreateAzureFunctionWithSqlBinding, TelemetryActions.exitCreateAzureFunctionQuickpick, undefined, utils.getErrorType(e))
+			if (errorType === 'TimeoutError') {
+				// timeout error will only happen if the user cancels the wizard
+				console.log('User cancelled out of the create Azure Function with SQL Binding wizard');
+			} else {
+				// else an error would occur during the createFunction
+				exitReason = 'error';
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:159]: Shouldn't you be setting exitReason to `timeout` or something in the if?

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 1 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:156]: So there is currently no way to know if a user cancels out of the createFunction API since they created it this way (https://github.com/microsoft/vscode-azurefunctions/issues/2908). 

So the issue seems of not knowing a project file takes a long time and cancels out would end in the same result of the timeoutError happening. 

So the only way to know if a user cancels is to throw during Promise.race() rejects due to the timeout. As such what would you recommend then doing to capture both errors?

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 2 above)
Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:142]: This is so the user does not get any timeout error message when they exit out of the createFunction steps.

File: extensions/sql-bindings/src/services/azureFunctionsService.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:156]: Both are going to result in a timeout so I don't think there is any way to know. I'm just saying that since we don't know we shouldn't assume it's due to the user cancelling since it could be a number of other reasons why the find timed out.

Comment (VasuBhog) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:156]: Agreed, so what should I do in this situation. Have a generic error when we get the timeout error - `Unable to Create Azure Function`?

Comment (Charles-Gagnon) [reply extensions/sql-bindings/src/services/azureFunctionsService.ts:156]: Yes, that was my suggestion 😁 

(and by error to be clear I mean log it. We shouldn't be displaying anything to the user right now since I see it being a lot more common that someone will cancel out vs something going wrong and the file not being generated, and so displaying an error would just be annoying and misleading at that point)

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 4]
```diff
@@ -147,11 +147,19 @@ export async function createAzureFunction(connectionString: string, schema: stri
 				.withAdditionalProperties(propertyBag)
 				.withConnectionInfo(connectionInfo).send();
 		} catch (e) {
+			let errorType = utils.getErrorType(e);
 			propertyBag.quickPickStep = quickPickStep;
-			exitReason = 'error';
-			void vscode.window.showErrorMessage(utils.getErrorMessage(e));
 
-			TelemetryReporter.createErrorEvent(TelemetryViews.CreateAzureFunctionWithSqlBinding, TelemetryActions.exitCreateAzureFunctionQuickpick, undefined, utils.getErrorType(e))
+			if (errorType === 'TimeoutError') {
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:153]: I'm not seeing a return here - shouldn't we be doing that since we're in an error state?

**Comment by VasuBhog** [comment]
Merged #18950 into this since it is the same error just in two different scenarios.

File: extensions/sql-bindings/src/services/azureFunctionsService.ts [hunk 5]
```diff
@@ -147,12 +159,21 @@ export async function createAzureFunction(connectionString: string, schema: stri
...
+				// this error can be cause by many different scenarios including timeout or error occurred during createFunction
+				exitReason = 'timeout';
+				console.log('Error creating azure function project');
```
Comment (Charles-Gagnon) [inline extensions/sql-bindings/src/services/azureFunctionsService.ts:168]: Same as above,

`Timed out waiting for Azure Function project to be created. This may not necessarily be an error, for example if the user canceled out of the create flow.`

**Review by Charles-Gagnon — APPROVED** [review]
One last thing about the log statement, but otherwise looks good.

You need to fix the auto-close tags in the description though. 

`This PR fixes https://github.com/microsoft/azuredatastudio/issues/18925 and https://github.com/microsoft/azuredatastudio/pull/18947.` isn't going to close 18947. You need to add the keyword before each item, e.g.

```
Fixes https://github.com/microsoft/azuredatastudio/issues/18925
Fixes https://github.com/microsoft/azuredatastudio/pull/18947
```
