### PR TITLE
Fix relative paths on anchor links 

### LINKED ISSUE #6756: Notebooks: Relative Links in HTML <a> Tags Don’t Work
In markdown (and in code cells where Display(HTML(“”)) is used), the following relative link works:
`[This works](test.ipynb)`

Using HTML syntax and <a> tags doesn’t work, though:

`<a href="test.ipynb">This doesn’t work</a>`

### PR DESCRIPTION
**Pull request by barbaravaldez**
This PR looks at #6756

Description:
Using an anchor link with a relative path to open a notebook would look for the file within the workbench directory. To fix the issue, we need to rebuild the path using the notebooks directory and the name of the notebook, and create a new uri based on the updated path.
 
How to test:
Use the relativeLinks.ipynb notebook to open another notebook using the markdown and html notation.
[relativePath.zip](https://github.com/microsoft/azuredatastudio/files/4473094/relativePath.zip)

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 1]
```diff
@@ -61,11 +62,19 @@ export class LinkHandlerDirective {
...
 			} else {
-				if (this.forceOpenExternal(uri)) {
-					this.openerService.open(uri, { openExternal: true }).catch(onUnexpectedError);
+				let newUri: URI | undefined;
+				let path = dirname(this.notebookUri.path);
+				path = 'file://' + path + '//' + basename(uri.path);
+				try {
+					newUri = URI.parse(path);
+				} catch{
+					//ignore
```
Comment (corivera) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:71]: You can use onUnexpectedError here to still log the error.

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 2]
```diff
@@ -61,11 +62,19 @@ export class LinkHandlerDirective {
...
 				this.notebookService.navigateTo(this.notebookUri, uri.fragment);
 			} else {
-				if (this.forceOpenExternal(uri)) {
-					this.openerService.open(uri, { openExternal: true }).catch(onUnexpectedError);
+				let newUri: URI | undefined;
+				let path = dirname(this.notebookUri.path);
+				path = 'file://' + path + '//' + basename(uri.path);
+				try {
+					newUri = URI.parse(path);
+				} catch{
```
Comment (corivera) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:70]: Space after catch.

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 3]
```diff
@@ -61,11 +62,19 @@ export class LinkHandlerDirective {
 			if (uri.fragment && uri.fragment.length > 0 && uri.fsPath === this.workbenchFilePath.fsPath) {
 				this.notebookService.navigateTo(this.notebookUri, uri.fragment);
 			} else {
-				if (this.forceOpenExternal(uri)) {
-					this.openerService.open(uri, { openExternal: true }).catch(onUnexpectedError);
+				let newUri: URI | undefined;
+				let path = dirname(this.notebookUri.path);
+				path = 'file://' + path + '//' + basename(uri.path);
```
Comment (corivera) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:67]: What happens here if you have a really complex path to another directory? Seems like just the basename would leave out a lot of path information. For example, say I was using a notebook in Documents, but wanted to use a relative link to a notebook in a folder that itself is in the Downloads folder.

Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:67]: If it's a relative path, could we not just append it directly, and use path.resolve to convert to an absolute path?

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 4]
```diff
@@ -62,19 +64,22 @@ export class LinkHandlerDirective {
...
-				let newUri: URI | undefined;
-				let path = dirname(this.notebookUri.path);
-				path = 'file://' + path + '//' + basename(uri.path);
-				try {
-					newUri = URI.parse(path);
-				} catch{
-					//ignore
+				let exists = await this.fileService.exists(uri);
+				if (!exists) {
+					let relPath = relative(this.workbenchFilePath.fsPath, uri.fsPath);
```
Comment (corivera) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:69]: Why the workbench file path here and not the notebook path?

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:69]: When an anchor link is used, the path from the target it's modified and instead of just showing the relative path, it uses the absolute path of the workbenchFile plus the original relative path. 
That's why I get the difference between these two paths and then I create the absolute path using the notebook path and the relative path.

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:69]: I can get the relative path from target.attributes.href.value, instead of using target['href'], but I'm not sure if this is the right way.

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 5]
```diff
@@ -41,7 +44,7 @@ export class LinkHandlerDirective {
 		try {
 			const href = target['href'];
 			if (href) {
-				this.handleLink(href);
+				Promise.resolve(this.handleLink(href));
```
Comment (corivera) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:47]: Do exceptions from handleLink still get surfaced here? The promise isn't being awaited, or handled via catch/then.

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts (hunk 4 above)
Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:69]: Ok, makes sense.

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts (hunk 5 above)
Comment (corivera) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:47]: You're also getting a hygiene build failure here due to unhandled promises.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:47]: I'd suggest making this handler async and then await on the call to this.handleLink - that will let the try/catch work properly

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 6]
```diff
@@ -41,7 +44,7 @@ export class LinkHandlerDirective {
 		try {
 			const href = target['href'];
 			if (href) {
-				this.handleLink(href);
+				this.handleLink(href).catch(e => onUnexpectedError(e));
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:47]: You can get rid of the try/catch with this

File: src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts [hunk 7]
```diff
@@ -38,19 +41,13 @@ export class LinkHandlerDirective {
...
-			if (href) {
-				this.handleLink(href);
-			}
-		} catch (err) {
-			onUnexpectedError(err);
-		} finally {
-			event.preventDefault();
+		const href = target['href'];
+		if (href) {
+			await this.handleLink(href).catch(e => onUnexpectedError(e)).finally(event.preventDefault);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts:46]: So if you're removing the try/catch and adding the .catch then this function doesn't need to be async. This will still work fine as is - it's just unnecessary though to make it async.

We generally prefer using async functions though so I'd suggest getting rid of the .catch and instead adding the try/catch/finally back

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts]: I made the method async and removed the try/catch from the promise 👍
