### PR TITLE
Corrected Keyboard Shortcut Execution Issue

### LINKED ISSUE #4704: Keyboard Shortcut to execute Stored Procedure does not work if query window has results
Issue Type: <b>Bug</b>

1) Set query shortcut 3 to `sp_columns`.

2) Bind Shortcut3 to "CTRL + Shift + 3"

3) Run a query (I ran `select top 1 * from Person.Person`  in the adventure works database)

4) Highlight the table in the text editor section

5) Run "CTRL + Shift + 3" one or more times

Actual results:
Each time you run the keyboard shortcut, the results will be placed below the existing query results. This renders the keyboard shortcut essentially unusable as you can't view the results. 

Expected results:
I expect the results window to clear and display the results of the keyboard shortcut's stored procedure only.

This seems like a regression, it only started recently.

Here is a gif demonstrating the error: 
keyboard_shortcut_error_1

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.02GB free)|
|Process Argv|-psn_0_12581887|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.7.0

</details>

### PR DESCRIPTION
**Pull request by Stevoni**
Keyboard shortcuts now fire the same events the standard query execution events are firing which corrects an issue with the results panel.

This fix will allow keyboard shortcuts to execute procedures or SQL statements without the results pane cluttering up with incomplete meta data. The previous executed results headers would not clear, the new data would fill into those columns, and the new headers would appear below the completed set.

Should fix #4704 .

### CODE REVIEW

File: src/sql/platform/query/common/queryManagement.ts [hunk 1]
```diff
@@ -210,6 +210,7 @@ export class QueryManagementService implements IQueryManagementService {
 		});
 	}
 	public runQueryString(ownerUri: string, queryString: string): Thenable<void> {
+		this.addTelemetry(TelemetryKeys.RunQueryString, ownerUri);
```
Comment (kevcunnane) [inline src/sql/platform/query/common/queryManagement.ts]: @abist can you take a look at this and decide a) if we need telemetry here, b) if there's any impact on our pipelines from this, and c) if we need a new string vs. just using the existing one? You're our telemetry expert so don't want to have any unexpected impact, thanks!

**Comment by kevcunnane** [comment]
Thanks for opening this PR. Could you give a little more info on what this fix does? E.g. what was the problem with the results that this solved? Also if you can sign the CLA that'd be much appreciated.

@anthonydresser I would be inclined to take this PR, but as the person with most experience can you take a look and make sure we don't need to send any additional events (e.g. does the onQueryEnd event always fire?)

File: src/sql/platform/query/common/queryManagement.ts (hunk 1 above)
Comment (abist) [reply src/sql/platform/query/common/queryManagement.ts]: This is fine as long as we don't include the query string itself along with it 👍

**Comment by Stevoni** [comment]
> Thanks for opening this PR. Could you give a little more info on what this fix does? E.g. what was the problem with the results that this solved? Also if you can sign the CLA that'd be much appreciated.

@kevcunnane , I elaborated in the first PR comment to expand on the rationale behind this fix. Screenshots and reproducible steps are included in the issue, #4704 . If there's something else missing, let me know.
