### PR TITLE
Remove -1 from table tab index to allow tabbing into the table

### LINKED ISSUE #9266: A11y_SQLAzureDataStudio_DeployDacpac_ReviewDeployPlan_Keyboard:The scroll bar is not accessible.
[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_SQLAzureDataStudioBenchmark;#A11yMAS;#A11ySev1;#A11yTCS;#SQL Azure Data Studio;#Benchmark;#DesktopApp;#MacOs;#MAS2.1.1;#Keyboard;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.15.0-insider
Commit: 3a8b74a
Date: 2020-02-11T05:49:41.181Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
Mac OS:10.15.3

**Additional Details:**
Mac OS:10.15.3
MAS References:MAS2.1.1

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Dacpac extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Data-tier application wizard from Context menu.
8. Select first radio button.
9. Navigate till next button & hit enter.
10. Provide all the details for Deploy Dacpac & hit next.
11. Navigate to the table using tab.

**Actual:**
On navigating on the page the tab focus after 3 is on the checkbox, the scroll bar is not accessible hence the data in the table will not be accessible to keyboard users.

**Expected:**
The scroll bar should be accessible after line 3 on the tab.

**User Impact:**
Keyboard users will be able to view the data in the table.

**Attachment link for Reference :**
[A11y_SQLAzureDataStudio_DeployDacpac_ReviewDeployPlan_Keyboard9266.zip](https://github.com/microsoft/azuredatastudio/files/4322625/A11y_SQLAzureDataStudio_DeployDacpac_ReviewDeployPlan_Keyboard9266.zip)

### PR DESCRIPTION
**Pull request by udeeshagautam**
This PR fixes #9266 

as per the older accessibility bug (#6729 ) we removed tabbing to a table - but that is now being asked for. Alan confirmed on this, hence adding it back.

### CODE REVIEW

File: extensions/dacpac/src/wizard/pages/deployPlanPage.ts [hunk 1]
```diff
@@ -99,7 +99,8 @@ export class DeployPlanPage extends DacFxConfigPage {
 			columns: this.getTableColumns(result.dataLossAlerts.size > 0),
 			width: 875,
 			height: 300,
-			ariaRole: 'alert'
+			ariaRole: 'alert',
+			moveFocusOutWithTab: true
```
Comment (udeeshagautam) [inline extensions/dacpac/src/wizard/pages/deployPlanPage.ts]: added this to follow same pattern as other tables in DacFx - @alanrenmsft et me know if we should remove this and only depend on ctrl + end

Comment (alanrenmsft) [reply extensions/dacpac/src/wizard/pages/deployPlanPage.ts]: let's remove this and rely on the common keyboard navigation.

Comment (Charles-Gagnon) [reply extensions/dacpac/src/wizard/pages/deployPlanPage.ts]: This feels like something we should just straight up remove then, right? (not even sure anywhere else uses this)

**Comment by alanrenmsft** [comment]
@udeeshagautam could you please the changes requested and merge this PR? let me know if you need any help.

File: extensions/dacpac/src/wizard/pages/deployPlanPage.ts (hunk 1 above)
Comment (udeeshagautam) [reply extensions/dacpac/src/wizard/pages/deployPlanPage.ts]: I dont want to remove the property and implementation* yet since its in azdata and also because I want to wait and see if someone from accessibility team comes back with older guidance. Will remove the usage for now.
