### PR TITLE
fix file relative path issue on mac

### LINKED ISSUE #21301: Relative file links are updated to absolute when editing in wysiwyg.
As stated in the ADS bugs section in the link below:
https://eng.ms/docs/cloud-ai-platform/azure-data/azure-data-intelligence-platform/synapse-dw/sql-dw-prod-clusters/sql-dw-tsg/getting-started/tsg-template

Rich Text View (aka What You See Is What You Get - WYSIWYG), has a bug that will break internal notebook links if you edit any character in the page. This repro's 100% of the time when there are internal links to other ADS notebook.
For example:
```
[New Synapse SQL DevOps Model](./Synapse-SQL-_aka-DW_-DevOps-Process.ipynb)
```
will become this:
```
[New Synapse SQL DevOps Model](..........\ADS%20LiveSite%20Support\Books\SQL-DW-TSG\content\Getting-Started\Synapse-SQL-_aka-DW_-DevOps-Process.ipynb)
```

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #21301

The issue still exists on mac due to the fact that HTMLAnchorElement's attributes['href']?.nodeValue is wrong on mac. Ex: For local files paths the nodeValue is as follows:
 **'/PathToParentFolder/ ./fiename.ipynb'** when it's expected to be: **'/PathToParentFolder/fiename.ipynb'**
 

Also fixes the issue #21728 where the notebook folder has a space in it's name.
While setting the relative path, we're checking the encoded file path of the link to the un-encoded notebook folder.
Ex: C:/User/**ADS Live Site**/Book1/notebook1.ipynb
and C:/User/**ADS%20Live%20Site**/Book1/notebook2.ipynb 
And the result is a malformed relative link.
Fix: Decode the path while setting the relative path with path.relative() and then encode the resulting relative path.

### CODE REVIEW

File: src/sql/workbench/services/notebook/browser/models/notebookUtils.ts [hunk 1]
```diff
@@ -72,3 +73,19 @@ export async function asyncForEach(array: any[], callback: Function): Promise<an
...
 	}
 }
+
+/**
+ * Check if a given file path is valid
+ * @param href the filepath as string
+ * @returns true if a file path is valid
+ */
+export function isFilepathValid(href: string): boolean {
+	fs.stat(href, (error, stats) => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookUtils.ts:83]: This function is always returning true. You need to either create a promise and then call resolve with true/false in the callback or (preferably) use [pfs.Promises.stat](https://github.com/Microsoft/azuredatastudio/blob/main/src/vs/base/node/pfs.ts#L257)

(you should not be using fs directly in core code. That's why you're getting the hygiene failure in the build)

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 2]
```diff
@@ -53,8 +53,17 @@ export class NotebookLinkHandler {
 			this.isMarkdown = this._link.attributes['is-markdown']?.nodeValue === 'true' ? true : false;
 			this.isEncoded = this._link.attributes['is-encoded']?.nodeValue === 'true' ? true : false;
 			this._isFile = this._link.protocol === `${Schemas.file}:` || this._link.protocol === `${Schemas.vscodeFileResource}:`;
-			// Given an anchor element for windows href link will need to use nodeValue instead as that does not encode the url
-			if (isWindows) {
+			// When editing on richtext, for local files paths use pathname to get the filepath of the link
+			// since the nodeValue results are ambiguous depending on OS ex: '/PathToParentFolder/ ./fiename.ipynb'.
+			if (this._isFile) {
+				// check if nodevalue is valid
+				if (notebookUtils.isFilepathValid(this._link.attributes['href']?.nodeValue)) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:60]: I'm a little confused by the usage of "valid" here. Because you could very well have a path that doesn't exist currently but is "valid". When wouldn't the file path be "valid" and why would you want to use the pathname directly in that case?

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 3]
```diff
@@ -53,8 +53,17 @@ export class NotebookLinkHandler {
...
+					this._href = this._link.attributes['href']?.nodeValue;
+				} else {
+					this._href = this._link.pathname;
+				}
+			} else if (isWindows) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:65]: You don't still need to do this logic for windows file paths?

**Comment by Charles-Gagnon** [comment]
What do you mean in your description by `The issue still exists on mac`?

The title implies this is fixing this for Macs, am I misreading the description?

Some more description of why this is fixing the issue would be nice too - it's not clear to me why checking whether it's a file schema or not fixes this.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 3 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:59]: so the else part is for web links not file and is still needed.

Comment (VasuBhog) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:59]: Would be good to add a comment above the else indicating that this would be for web links while the above would be for file paths just to be clear.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 4]
```diff
@@ -53,8 +52,12 @@ export class NotebookLinkHandler {
 			this.isMarkdown = this._link.attributes['is-markdown']?.nodeValue === 'true' ? true : false;
 			this.isEncoded = this._link.attributes['is-encoded']?.nodeValue === 'true' ? true : false;
 			this._isFile = this._link.protocol === `${Schemas.file}:` || this._link.protocol === `${Schemas.vscodeFileResource}:`;
-			// Given an anchor element for windows href link will need to use nodeValue instead as that does not encode the url
-			if (isWindows) {
+			// When editing on richtext, for local files paths use pathname to get the filepath of the link
+			// since the nodeValue results are ambiguous depending on OS ex: '/PathToParentFolder/ ./fiename.ipynb'.
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:56]: Do you know why nodeValue is "ambiguous"? That seems important to try and find out so we're sure we're doing the right thing here.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 3 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:59]: I would even suggest to have an outer if with the isFile check and then in the else put the previous isWindows/else logic. Makes it easier to follow that those two blocks are what should happen for web links.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 5]
```diff
@@ -53,8 +52,12 @@ export class NotebookLinkHandler {
...
+			if (this._isFile && this.isMarkdown) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:57]: Why do you only need to do this for markdown links? Make sure you add that context to the comment above

**Comment by Charles-Gagnon** [comment]
@MaddyDev It looks like you did a rebase instead of a merge, please do a merge from main to get rid of these extra changes

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 6]
```diff
@@ -173,9 +174,17 @@ export class NotebookLinkHandler {
  */
 export function findPathRelativeToContent(notebookFolder: string, contentPath: URI | undefined, isMarkdown?: boolean, isEncoded?: boolean): string {
 	if (contentPath?.scheme === 'file') {
-		let relativePath = contentPath.fragment ? path.relative(notebookFolder, contentPath.fsPath).concat('#', contentPath.fragment) : path.relative(notebookFolder, contentPath.fsPath);
+		let decodePath: boolean = contentPath.fsPath !== decodeURI(contentPath.fsPath);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:177]: Some comments here explaining why this is necessary would be helpful...especially since I'm confused with how `isEncoded` fits into the picture. Why is that not being used to tell us whether we need to decode the path?

Why are we decoding the fsPath anyways? That value generally should already be decoded - for example : 

`const testUri = vscode.Uri.file('C:/Test Path With Space/file.txt');`

results in these : 

image

Or are we doing something weird with pre-encoding the path we create the URI out of which requires it be decoded first? And are you making sure that this isn't incorrectly decoding paths that have % characters in them?

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 7]
```diff
@@ -173,9 +174,17 @@ export class NotebookLinkHandler {
...
+		let decodedContentPath = contentPath.fsPath;
+		if (decodePath) {
+			decodedContentPath = decodeURI(contentPath.fsPath);
+		}
+		// use the decodedContentPath for calculating the reative path since the notebookFolder is not encoded to get the relative path correctly.
+		let relativePath = contentPath.fragment ? path.relative(notebookFolder, decodedContentPath).concat('#', contentPath.fragment) : path.relative(notebookFolder, decodedContentPath);
 		// if relativePath contains improper directory format due to marked js parsing returning an invalid path (ex. ....\) then we need to replace it to ensure the directories are formatted properly (ex. ..\..\)
 		relativePath = isMarkdown || isEncoded ? replaceInvalidLinkPath(relativePath) : encodeURI(replaceInvalidLinkPath(relativePath)).replace(/%5C/g, '\\');
+		// encode the path if we used decoded contentPath for calculating the relativePath.
+		relativePath = decodePath ? encodeURI(relativePath) : relativePath;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:187]: If this is markdown or isEncoded is true then it's going to double-encode the value...is that what we want?

File: src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts [hunk 8]
```diff
@@ -130,4 +130,21 @@ suite('Noteboook Link Handler', function (): void {
 			assert.strictEqual(notebookLinkHandler.getEncodedLinkUrl(), `/Notebooks/Test_Paths/My%2520File.ipynb`, '% in file path failed to be encoded');
 		});
 	});
+	test('getLinkUrl should return relativePath correctly', () => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts:133]: Add tests with : 

- Non-encoded spaces
- Encoded characters in the path (for example a path with a folder named `Test%20Folder` in it)

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts [hunk 9]
```diff
@@ -53,11 +52,13 @@ export class NotebookLinkHandler {
 			this.isMarkdown = this._link.attributes['is-markdown']?.nodeValue === 'true' ? true : false;
 			this.isEncoded = this._link.attributes['is-encoded']?.nodeValue === 'true' ? true : false;
 			this._isFile = this._link.protocol === `${Schemas.file}:` || this._link.protocol === `${Schemas.vscodeFileResource}:`;
-			// Given an anchor element for windows href link will need to use nodeValue instead as that does not encode the url
+			// When editing on richtext, for local files paths the nodeValue results are ambiguous depending on OS
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:55]: Add link to any documentation or bug reports on this - it seems like a bug and we want to be sure to have as much context on why we need to do this here in case it gets fixed in a later Node.JS update or something...

File: src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts (hunk 8 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts:133]: the tests are already there for them: https://github.com/microsoft/azuredatastudio/blob/0e65f0d7eb555d6d9ae8eb5504965b7f0f65afd1/src/sql/workbench/contrib/notebook/test/browser/notebookLinkHandler.test.ts#L104

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 6 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:177]: the isEncoded is set by reading the is-encoded attribute value of the link (am not really sure when that'll be true). The contentParth passed here is nothing but the _notebookUriLink which is explicitly encoded [here](https://github.com/microsoft/azuredatastudio/blob/0e65f0d7eb555d6d9ae8eb5504965b7f0f65afd1/src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts#L63), Which is why I needed to decode it here.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 7 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:187]: you mean when it's not isMarkdown and not isEncoded ? 
Since I calculated the relativePath from decoded contentPath, I need to encode it before returning. I've had tests failing without this step.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:187]: Yeah, sorry got that mixed up. 

Are there tests covering the !isMarkdown and !isEncoded paths? Because yes, it makes sense to encode it if you decoded it before but double encoding it definitely doesn't seem like it should result in the correct behavior.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 9 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:55]: Couldn't find any issues/documentation, I'm not sure where I stumbled upon the normalize fix. Will keep looking and update it if can find it.

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 7 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:187]: Actually all the tests are for !isEncoded and !isMarkdown since we're not setting those attributes. I added a test for covering when those are set as well, thanks!

File: src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts (hunk 6 above)
Comment (VasuBhog) [reply src/sql/workbench/contrib/notebook/browser/notebookLinkHandler.ts:177]: Hey Maddy, I found this image to help understand more of the Notebook linking flow:
image

This was made a while back but hopefully can help further understand the linking process of the Notebook flow and how it was used to fix many issues.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by VasuBhog — APPROVED** [review]
