### PR TITLE
Fix schema compare not always showing diff color highlighting

### LINKED ISSUE #21368: missing diff color highlighting
Issue Type: <b>Bug</b>

A schema compare from DB to sql proj where a column is only present on the sqlproj shows the difference in the compare but it is not highlighted.

image

Extension version: 1.17.0
Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:22:25.529Z)
OS version: Darwin arm64 21.6.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #21368. Some change differences weren't getting the color decorations correctly showing. The error in the console showing that an illegal line number was trying to be used in `GetFirstNonWhitespaceColumn`, which then caused the diff color highlighting to not show up correctly for those differences. 

There's been some churn in this file since the reverse option was originally added a few years ago, so I decided to change the approach for reversing the colors rather than trying to fix the existing reverse logic. Previously, the line changes and editors were being swapped, but that seems more complicated and risky, and led to this bug happening. The new approach is to swap the line color and zone decorations after the decorations have already been determined, which will avoid the error that was happening because the color reversing is now happening after that.

Before:
Screen Shot 2022-12-13 at 5 50 36 PM

Notice the differences not getting highlighted correctly for the change difference (3rd one in the table):
colorsBefore

Fixed:
Screen Shot 2022-12-13 at 5 46 45 PM
colorsFixed

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

File: src/vs/editor/browser/widget/diffEditorWidget.ts [hunk 1]
```diff
@@ -1799,6 +1796,68 @@ const DECORATIONS = {
 
 };
 
+// {{SQL CARBON EDIT}} - helper function for reversing colors for schema compare
+/**
+	 * Reverses the decorations of the given array of decorations, so that deletes and inserts are swapped
+	 * @param decorations
+	 */
+function reverseDecorations(decorations: IModelDeltaDecoration[]): void {
```
Comment (kisantia) [inline src/vs/editor/browser/widget/diffEditorWidget.ts:1804]: I moved these helper functions into diffEditorWidget.ts because there was a cyclic dependency between sql/editor/browser/diffEditorHelper and vs/editor/browser/widget/diffEditorWidget because of DECORATIONS being needed for `reverseDecorations`. Let me know if having it in a different part of this file if will make it easier for vscode merges.

**Review by SakshiS-harma — APPROVED** [review]
