### PR TITLE
remove the alert role from the wizard page title

### LINKED ISSUE #9171: A11y_SQLAzureDataStudio_ImportBacpac_Summary Screen_ScreenReader: Alert is announced when "Summary" step is opened.
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11y_SQLAzureDataStudioBenchmark;#A11yMAS;#A11ySev2;#A11yTCS;#SQL Azure Data Studio;#Benchmark;#DesktopApp;#Win32;#MAS1.3.1;#JAWS;#NVDA;  

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.16.0-insider
OS: Windows_NT x64 10.0.18363

**Additional Details:**
Screen reader: NVDA, JAWS
MAS References:MAS1.3.1

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Dacpac extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Data-tier application wizard from Context menu.
8. Select third radio button.
9. Launch screen reader as NVDA
10. Navigate till next button & hit enter.
11. Provide all the details & hit enter.

**Actual:**
When the page "Summary" is opened the screen reader announces alert before the word summary.

**Same issue found with JAWS**.

**Same issue in the following page:**
1. Select an Operation
2. Export Bacpac-Summary screen
3. Import Bacpac Settings  
4. Export Bacpac Settings
5.SQL Server Big Data Cluster-Summary

**Expected:**
The announcement of the word "alert" should be not made.

**User Impact:**
Screen reader users will think there is a mandatory field or requirement at summary.

**Attachment link for Reference :**
[A11y_SQLAzureDataStudio_ImportBacpac_Summary Screen_ScreenReader9171.zip](https://github.com/microsoft/azuredatastudio/files/4322666/A11y_SQLAzureDataStudio_ImportBacpac_Summary.Screen_ScreenReader9171.zip)

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #9171

### CODE REVIEW

File: src/sql/workbench/services/dialog/browser/wizardModal.ts [hunk 1]
```diff
@@ -191,6 +193,8 @@ export class WizardModal extends Modal {
 				dialogPane.hide();
 			}
 		});
+
+		status(localize('wizardPageChangedMessage', "Step {0}: {1}", index + 1, pageToShow.title));
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/dialog/browser/wizardModal.ts]: So as I was mentioning - I really don't like doing this. If we ever update the text on the wizard page we're going to have to remember to update this as well. Instead I would suggest adding another property somewhere that the step text is retrieved from and then use that for both the DialogComponent and here. Where exactly that text lives I'll leave up to you - but having it on the DialogPane and then having the DialogComponent consume that seems reasonable.

File: src/sql/workbench/services/dialog/browser/dialogPane.ts [hunk 2]
```diff
@@ -47,6 +48,10 @@ export class DialogPane extends Disposable implements IThemable {
 		super();
 	}
 
+	public get pageNumberDisplayText(): string {
+		return localize('wizardPageNumberDisplayText', "Step {0}", this.pageNumber);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/dialog/browser/dialogPane.ts]: As an added bonus this is now localized as well which was something I remember thinking to myself we should fix at some point in the future 😁

File: src/sql/workbench/services/dialog/browser/wizardModal.ts [hunk 3]
```diff
@@ -186,15 +186,18 @@ export class WizardModal extends Modal {
...
 			if (page === pageToShow) {
+				dialogPaneToShow = dialogPane;
 				dialogPane.show(focus);
 			} else {
 				dialogPane.hide();
 			}
 		});
 
-		status(localize('wizardPageChangedMessage', "Step {0}: {1}", index + 1, pageToShow.title));
+		status(localize('wizardPageChangedMessage', "{0} {1}", dialogPaneToShow.pageNumberDisplayText, dialogPaneToShow.title));
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/dialog/browser/wizardModal.ts]: I guess for overall safety probably worth it to not do this if dialogPaneToShow is undefined. (would never expect that to actually happen but theoretically it could...)

Comment (Charles-Gagnon) [inline src/sql/workbench/services/dialog/browser/wizardModal.ts]: Combining already localized strings like this doesn't need to use localize. The localizers have no context and realistically this is going to already be broken for non-LTR languages so if we really wanted to make it work for those scenarios we'd want to do something different anyways.

**Comment by anthonydresser** [comment]
Why was this merged in broken?

File: src/sql/workbench/services/dialog/browser/wizardModal.ts [hunk 4]
```diff
@@ -26,6 +26,8 @@ import { IAdsTelemetryService } from 'sql/platform/telemetry/common/telemetry';
 import { onUnexpectedError } from 'vs/base/common/errors';
 import { attachModalDialogStyler } from 'sql/workbench/common/styler';
 import { ILayoutService } from 'vs/platform/layout/browser/layoutService';
+import { status } from 'vs/base/browser/ui/aria/aria';
+import { localize } from 'vs/nls';
```
Comment (aaomidi) [inline src/sql/workbench/services/dialog/browser/wizardModal.ts]: This isn't used anywhere and is now showing errors on builds
