### PR TITLE
Beginning of fix for notebook perf

### LINKED ISSUE #3843: Pasting 12,000 lines into a code cell is slow
I pasted in the 12,767 line Best Practices Check from Tiger Toolbox into a code cell in the notebook. (https://raw.githubusercontent.com/Microsoft/tigertoolbox/master/BPCheck/Check_BP_Servers.sql) 

Short story: It takes about 9 seconds for text to appear. Scrolling is very jaggy and unresponsive and CPU runs at 20%+ for over 7 minutes before I cancel the test. Syntax coloring never completes. 

00:02.43 - Paste into cell, CPU 1.27, private bytes memory 274,356K on process which shows change during this test
00:11.56 - Contents appear, CPU 23.19, memory 734,856K
00:12.37 - Syntax colorizing starts, CPU 23.19, memory 734,852K
<Scroll down to bottom to watch for end of syntax coloring, snip in time>
05:00.00 - Bottom of text still not colorized, CPU 24.38, memory 878,276K
<snip>
07:29.72 - Still not colorized, CPU 23.58, memory 861,156K
07:42.11 - Close notebook and click "Do not save", CPU 22.29, memory 865,456K
07:52.16 - Notebook closes, CPU 20.54, memory 695,364K
07:55.93 - CPU 0.64, memory 647,775K (this slowly decreases over time)

### PR DESCRIPTION
**Pull request by kevcunnane**
Fixes #3843. Now includes full fix which limits length and ensures a scrollbar is available

- Set max size for editor. 4000px gets us 200-250 lines before needing a scrollbar. 
- Adds layout updating which should also ensure accurage line highlighting to the right of the editor. What's happening is initial size is slightly off, so need to layout a 2nd time (e.g. layout once, let flex figure things out, then layout a 2nd time). This isn't optimal as there's a minor perf hit but it isn't noticeable overall.

To consider in future PRs:
- Add user configurable setting for max length?
- Handle case where we scroll to bottom but scrollbar is at the top. 
- Consider how intellisense will work on this. We may need to split into a window around the current code when sending to the kernel as it's quite likely that doing a 12K line intellisense request will be too big.

### CODE REVIEW

File: src/sql/parts/notebook/cellViews/code.component.ts [hunk 1]
```diff
@@ -166,13 +177,16 @@ export class CodeComponent extends AngularDisposable implements OnInit, OnChange
 			this._editor.setHeightToScrollHeight();
 			this.cellModel.source = this._editorModel.getValue();
 			this.onContentChanged.emit();
+			// TODO see if there's a better way to handle reassessing size.
+
```
Comment (chlafreniere) [inline src/sql/parts/notebook/cellViews/code.component.ts]: nit: extra space

File: src/sql/parts/notebook/cellViews/code.component.ts [hunk 2]
```diff
@@ -78,13 +79,15 @@ export class CodeComponent extends AngularDisposable implements OnInit, OnChange
 
 	protected _actionBar: Taskbar;
 	private readonly _minimumHeight = 30;
+	private readonly _maximumHeight = 4000;
```
Comment (chlafreniere) [inline src/sql/parts/notebook/cellViews/code.component.ts]: can we reconcile this max height and the one in queryTextEditor?

Comment (kevcunnane) [reply src/sql/parts/notebook/cellViews/code.component.ts]: Yeah 4000 can be our default.
