### PR TITLE
Fix for SQL text file for editdata upon reload.

### LINKED ISSUE #8890: Edit Data leaving a SQL text document in HotExit auto-recover list
- Azure Data Studio Version: `master`, regression from 1.14.1

Steps to Reproduce:

1. Edit Data on a table
2. Leave Edit Document open and close ADS shell window
3. Reopen ADS

Expected: Edit Data document gone and no residual UI elements

Actual: Edit Data backing SQL query is reopened in SQL query editor document

*This document was restored from an Edit Data document as part of HotExit auto-recover behavior*
image

### PR DESCRIPTION
**Pull request by smartguest**
Changes and observations:
1. Sets the Edit Data editor dirty status to always false (even if its dirty) as the status defaults to true for an untitled text editor without a set backup. 

2. If an editor is marked as dirty, it is automatically backed up, sql included (when it isn't valid for restore and causes problems). Marking it false will exclude it from reload.

This PR fixes #8890

### CODE REVIEW

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts [hunk 1]
```diff
@@ -91,6 +91,8 @@ export class QueryEditorService implements IQueryEditorService {
 		const m = await fileInput.resolve();
 		if (sqlContent) {
 			m.textEditorModel.setValue(sqlContent);
+			// prevent backup and restore of invalid sql upon restart.
+			m.setDirty(false);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: This probably isn't going to solve the issue if the user edits the query (which while sort of an edge case is something we allow).

A quick and dirty solution would be to hook into the onDidChangeDirty event and set it to false.

A better solution would probably be to create a new input for edit data that always returns false for isDirty

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts [hunk 2]
```diff
@@ -91,6 +91,8 @@ export class QueryEditorService implements IQueryEditorService {
 		const m = await fileInput.resolve();
 		if (sqlContent) {
 			m.textEditorModel.setValue(sqlContent);
+			// prevent backup and restore of invalid sql upon restart.
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: nit: But I also wouldn't use the phrase 'invalid sql' here. There's nothing invalid about this - we just don't care about preserving the query from edit data.

Maybe something like

`prevent backup and restore of backing query upon restart`

That being said - has there been discussion around re-opening the edit data editor upon restart? That seems to me to also be a reasonable solution - instead of opening a SQL editor it would open the entire editor (preserving any changes made to the query too). If you make an input type for edit data this shouldn't be too bad to do.

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts (hunk 1 above)
Comment (smartguest) [reply src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: How do you hook onto the onDidChangeDirty event? Apparently you can only access the event itself, but not set it to set isDirty to false from queryEditorService

Comment (Charles-Gagnon) [reply src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: I tried it and it worked fine for me - 
```
m.onDidChangeDirty( () => {
   m.setDirty(false);
}
```

(note this does create a bit of a feedback loop since changing the dirty state will cause the event to fire again. But that should only happen once since setting the dirty state to the same value doesn't fire the event again. May want to consider adding a guard to only do that if dirty state is true though regardless just to be safe in case the underlying implementation changes)

File: src/vs/workbench/common/editor/untitledTextEditorModel.ts [hunk 3]
```diff
@@ -63,6 +63,11 @@ export class UntitledTextEditorModel extends BaseTextEditorModel implements IUnt
 		this._register(this.configurationService.onDidChangeConfiguration(e => this.onConfigurationChange()));
 	}
 
+	public registerDirtyListener(): void {
+		// For editData
```
Comment (Charles-Gagnon) [inline src/vs/workbench/common/editor/untitledTextEditorModel.ts]: Why are you doing this here? Generally we should avoid having specific logic like this in a more general-use class.

Comment (Charles-Gagnon) [reply src/vs/workbench/common/editor/untitledTextEditorModel.ts]: And FYI - if you're ever making changes like this in VS code make sure you're adding a SQL CARBON EDIT

Comment (smartguest) [reply src/vs/workbench/common/editor/untitledTextEditorModel.ts]: I tried to do the thing you did earlier but it did not work for me, it kept on restoring the grid even when it should not, I know this isn't right.

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts (hunk 1 above)
Comment (smartguest) [reply src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: It did not fire for me at all, it kept on reopening for me even when I tried to make an edit on a table and closing ADS

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts [hunk 4]
```diff
@@ -92,6 +92,11 @@ export class QueryEditorService implements IQueryEditorService {
 		if (sqlContent) {
 			m.textEditorModel.setValue(sqlContent);
 		}
+		m.onDidChangeDirty(() => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: Actually I was looking into this further and we already have an EditDataInput that even already hooks into the onDidChangeDirty. So you should be able to just add the setDirty call to that instead which is a much better solution IMO.

Comment (smartguest) [reply src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: Add a setDirty call to the model in queryEditorService? There is no setDirty call in editDataInput.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: No, you should be able to get the model from calling 
```
const model = await this._sql.resolve();
model.setDirty(false);
```

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts [hunk 5]
```diff
@@ -92,16 +92,14 @@ export class QueryEditorService implements IQueryEditorService {
...
-			if (m.isDirty()) {
-				m.setDirty(false);
-			}
-		});
 
 		// Create an EditDataInput for editing
 		const resultsInput: EditDataResultsInput = this._instantiationService.createInstance(EditDataResultsInput, docUri.toString());
 		let editDataInput: EditDataInput = this._instantiationService.createInstance(EditDataInput, docUri, schemaName, tableName, fileInput, sqlContent, resultsInput);
 
+		editDataInput.onDidChangeDirty(() => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: I'd rather this go in the actual editDataInput file - that keeps the code together rather than spreading it across different places. This is something we want all Edit Data editors to have so no reason to tie it to this specific place (even if this is currently the only place we make this - that might change and relying on us remembering to copy this over is likely to just result in subtle bugs)

**Comment by anthonydresser** [comment]
This is a similar issue to what we had with notebooks, I would sync with @chlafreniere

**Comment by smartguest** [comment]
I have now implemented the fix from notebooks from @chlafreniere into editdata editor as well, apparently the editor must be blocked from being tracked along with using untitledResource for fileinput rather than associatedResource in order to fully close it upon rerun. Any comments on the formatting of the SQL carbon edit or is it fine?

File: src/vs/workbench/services/workingCopy/common/workingCopyService.ts [hunk 6]
```diff
@@ -139,8 +139,10 @@ export class WorkingCopyService extends Disposable implements IWorkingCopyServic
 	registerWorkingCopy(workingCopy: IWorkingCopy): IDisposable {
 		const disposables = new DisposableStore();
 
-		// {{SQL CARBON EDIT}} @chlafreniere need to block working copies of notebook editors from being tracked
-		if (workingCopy.resource.path.includes('notebook-editor-') && workingCopy.resource.scheme === Schemas.untitled) {
+		// {{SQL CARBON EDIT}} @chlafreniere need to block working copies of notebook editors from being tracked.
+		// {{SQL CARBON EDIT}} @alma1 along with editdata editors.
+		let dontRestore = (workingCopy.resource.path.includes('notebook-editor-') || workingCopy.resource.path.includes('dbo.'));
```
Comment (Charles-Gagnon) [inline src/vs/workbench/services/workingCopy/common/workingCopyService.ts]: I assume you're getting dbo because the editor title is the table name - e.g. `dbo.myTable`? That's not a usable solution though - the schema (dbo in this case) can be anything so hardcoding it like this is only going to work part of the time.

I'd suggest looking into where these working copies are being registered - is this behavior we can override when we create the editor?

Comment (smartguest) [reply src/vs/workbench/services/workingCopy/common/workingCopyService.ts]: Its being called from untitledTextEditor, to avoid this, there needs to be an optional parameter for the class that checks if working copies are needed or not

File: src/vs/workbench/common/editor/untitledTextEditorModel.ts [hunk 7]
```diff
@@ -205,4 +205,8 @@ export class UntitledTextEditorModel extends BaseTextEditorModel implements IUnt
 	isReadonly(): boolean {
 		return false;
 	}
+
+	unregisterWorkingCopy() {
```
Comment (kburtram) [inline src/vs/workbench/common/editor/untitledTextEditorModel.ts]: every change we make in the `vs` folder should be prefixed with a comment `// {{SQL CARBON EDIT}}` so we can easily identify our customizations to the upstream codebase.  Please make this update to changes under `vs`.

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts [hunk 8]
```diff
@@ -87,8 +87,9 @@ export class QueryEditorService implements IQueryEditorService {
 		let docUri: URI = URI.from({ scheme: Schemas.untitled, path: filePath });
 
 		// Create a sql document pane with accoutrements
-		const fileInput = this._untitledEditorService.create({ associatedResource: docUri, mode: 'sql' });
+		const fileInput = this._untitledEditorService.create({ untitledResource: docUri, mode: 'sql' });
 		const m = await fileInput.resolve();
+		m.unregisterWorkingCopy();
```
Comment (kburtram) [inline src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: do you know why this is now necessary and wasn't before?

Comment (smartguest) [reply src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: From what I'm seeing, when I close the editor, the function call at the end "toDisposable" does not fire when I close ADS but it does when closing the editor manually, otherwise it seems to automatically backup the editor into the backup file service for similar reasons as notebooks in #8944

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts (hunk 4 above)
Comment (smartguest) [reply src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: The sqlContent thing causes the isDirty boolean to be set true due to the change, so it must be hooked in before the textEditorModel is called.

**Comment by smartguest** [comment]
The code now has the onDidChangeDirty check moved back to EditDataInput as requested. Apparently setting the textEditorModel to SQLContent registered as a change, setting the dirty state to true. To fix this, the assignment is done after EditDataInput is created.
