### PR TITLE
Fix deploy data to be presented on dashboard

### LINKED ISSUE #15070: Project dashboard presenting incorrect information
Azure Data Studio Version: 
Version: 1.28.0-rc1 (user setup)
Commit: 1c91f7971e8d4563dca47ab113953b4ad8d59b64
Date: 2021-04-09T00:19:50.442Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create project from "VerifyContainedDBImportExport12892" db.
2. Try publishing the project. It fails but the Deployments table in dashboard shows that it was successful.
image

image

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR addresses the problem in #15070.

Originally, the code wasn't looking for the outcome of deploy functionality, hence presented passed for a successful DacFx operation, but failed scenario. Now the code checks for the outcome of the deploy task and presents information based on that.

image

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -319,7 +319,11 @@ export class ProjectsController {
 		telemetryProps.totalDuration = (actionEndTime - buildStartTime).toString();
 
 		const currentDeployIndex = this.deployInfo.findIndex(d => d.startDate === currentDeployTimeInfo);
-		this.deployInfo[currentDeployIndex].status = Status.success;
+		if (result.success === true) {
```
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/projectController.ts:322]: can be simplified to `this.deployInfo[currentDeployIndex].status = result.success ? Status.success : Status.failed`

**Review by kisantia — APPROVED** [review]

**Review by udeeshagautam — APPROVED** [review]
