### PR TITLE
Fix for dacfx wizard if user doesn't have access to master db

### LINKED ISSUE #9187: Unable to Export BacPac if user does not have access to master db
Issue Type: <b>Bug</b>

The company I work at does not allow access to the master database.  To connect to a server we need to supply a database name.  When using the Data-tier Application Wizard the step 2 dialog hangs at the Source Database entry.

image

Azure Data Studio version: azuredatastudio 1.15.0 (e57eb999fc5f1e000477da8fe0b8679ff0bfd57b, 2020-02-12T20:48:43.389Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.2.0
import|Mic|0.13.1
profiler|Mic|0.11.0

</details>

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #9187. The database dropdowns weren't populating in the dacfx wizard if the user didn't have access to the master db. This is because there was an error during the listDatabases call. For now, this will just add the database from the connection to the databases dropdown if there is an error duing the listDatabases call. Opened #9361 for the error from azdata.connection.listDatabases

### CODE REVIEW

File: extensions/dacpac/src/wizard/api/dacFxConfigPage.ts [hunk 1]
```diff
@@ -132,7 +132,13 @@ export abstract class DacFxConfigPage extends BasePage {
 			return false;
 		}
 
-		let values = await this.getDatabaseValues();
+		let values: string[];
+		try {
+			values = await this.getDatabaseValues();
+		} catch (e) {
+			// if the user doesn't have access to master, just set the database to the one the current connection is to
```
Comment (Charles-Gagnon) [inline extensions/dacpac/src/wizard/api/dacFxConfigPage.ts]: Let's add a console warn here so users can see what the error was if they want to investigate further.
