### PR TITLE
Fix missing add azure account button in accountDialog

### LINKED ISSUE #15819: add new account button is missing
now:
image

in 1.30 stable:
image

### PR DESCRIPTION
**Pull request by caohai**
This PR fixes #15819. 

`getActions()` was removed from `ViewPane` in https://github.com/microsoft/vscode/commit/585c5cc04b99ea2a9e03d25035f73c1354188fc0. We overrode this function at several places to inject our actions. Removing this function causes these overrides to not take effective, including "Add an account" action in account dialog.

This PR fixes the issue by registering "Add an account" action with `registerAction2`.

Screen Shot 2021-06-24 at 13 50 40

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
I think it would be best if we added the actions with menu contributions for the views instead. The less we drift from how VS Code does things the less likely we are to run into issues in the future.

You can see an example of how this would be done here : https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L927 - the MenuId is the ViewTitle ID and the when clause tells it what view it should display for (so in this case that would be the azure accounts view)

I'd just start with the Azure view to make sure it works there and get that reviewed before working on the others though since they're a bit more complex.

**Comment by caohai** [comment]
> I think it would be best if we added the actions with menu contributions for the views instead. The less we drift from how VS Code does things the less likely we are to run into issues in the future.
> 
> You can see an example of how this would be done here : https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L927 - the MenuId is the ViewTitle ID and the when clause tells it what view it should display for (so in this case that would be the azure accounts view)
> 
> I'd just start with the Azure view to make sure it works there and get that reviewed before working on the others though since they're a bit more complex.

Thanks for the info Charles! Yeah I'd also prefer an approach that avoids reverting VS Code changes if possible. I'll take a look at the example.

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 1]
```diff
@@ -431,4 +401,58 @@ export class AccountDialog extends Modal {
...
+		}
+
+		const v = vals.filter(v => v.view.title === pickedValue)?.[0];
+
+		if (!v) {
+			this._notificationService.error(localize('accountDialog.didNotPickAuthProvider', "You didn't select any authentication provider. Please try again."));
+			return;
+		}
+
+		v.addAccountAction.run();
```
Comment (caohai) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:456]: This section is copied from previous code directly without change.

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 2]
```diff
@@ -115,13 +116,6 @@ class AccountPanel extends ViewPane {
 	private updateTenants(account: azdata.Account) {
 		this.tenantList!.splice(0, this.tenantList!.length, account.properties?.tenants ?? []);
 	}
-
-	public getActions(): IAction[] {
-		return [this.instantiationService.createInstance(
-			AddAccountAction,
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:121]: Remove this old class if we're not using it anymore (although it looks like you have some references to it still, but those shouldn't be necessary anymore right?)

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 3]
```diff
@@ -231,33 +225,7 @@ export class AccountDialog extends Modal {
...
-
-			const v = vals.filter(v => v.view.title === pickedValue)?.[0];
-
-			if (!v) {
-				this._notificationService.error(localize('accountDialog.didNotPickAuthProvider', "You didn't select any authentication provider. Please try again."));
-				return;
-			}
-
-			v.addAccountAction.run();
+			this.runAddAccountAction();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:228]: It doesn't really matter in this specific case - but it's still good practice to always either return or await async functions (unless you have a specific reason for not wanting to wait on them)

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts [hunk 4]
```diff
@@ -431,4 +401,58 @@ export class AccountDialog extends Modal {
...
+						id: MenuId.ViewTitle,
+						group: 'navigation',
+						when: ContextKeyEqualsExpr.create('view', viewId),
+						order: 1
+					}
+				});
+			}
+
+			async run() {
+				that.runAddAccountAction();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/accountManagement/browser/accountDialog.ts:424]: Same here, suggest await

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts (hunk 2 above)
Comment (caohai) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts:121]: Are you suggesting to remove `ViewPane` from `AccountPanel` entirely? I'm not quite sure if extending `ViewPane` was solely for the purpose of injecting actions...

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts (hunk 4 above)
Comment (caohai) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts]: done

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts (hunk 3 above)
Comment (caohai) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts]: done

File: src/sql/workbench/services/accountManagement/browser/accountDialog.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts:121]: No, this is for removing the AddAccountAction (since that functionality is built into the registerAction2 calls you added)

Comment (caohai) [reply src/sql/workbench/services/accountManagement/browser/accountDialog.ts:121]: Oh that one, `registerAction2 ` will still eventually call `run()` from `AddAccountAction` with this line `v.addAccountAction.run();`

**Review by Charles-Gagnon — APPROVED** [review]
Could you create issues for the other views that were using this functionality for following up and fixing - just to make sure we don't forget about them?

**Comment by caohai** [comment]
> Could you create issues for the other views that were using this functionality for following up and fixing - just to make sure we don't forget about them?

Sure, I'll do that shortly.

**Review by kburtram — APPROVED** [review]
LGTM
