### PR TITLE
fix issue caused by execution plan provider

### LINKED ISSUE #21451: JSON field no longer open a new file
Issue Type: <b>Bug</b>

Latest update to ADS doesn't allow me to select JSON fields and open raw JSON in a new file.

I've tried restarting ADS and the issue remains.

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (4.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-mysql|Mic|0.2.4
azuredatastudio-postgresql|Mic|0.2.7

</details>

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #21451

Problem: 
The following error was logged when trying to open a JSON cell: `No valid execution plan handler is registered`

Root Cause:
When the provider is not an execution plan provider, an error will be thrown when checking whether the string is execution plan.
image

Fix:
1. Add `IsExecutionPlanProvider` to the provider metadata so that we know it without needing to activate the extension
2. Update the service so that it returns false if the provider is not an execution plan provider
3. refactor the execution plan service

With the fix:

MySQL - Json
mysql-json

MSSQL - Execution Plan
mssql-execution-plan

MSSQL - JSON
mssql-json

### CODE REVIEW

**Review by lewis-sanchez — APPROVED** [review]

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 1]
```diff
@@ -27,21 +27,59 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
+						resolve(e.provider);
+					}
+				});
+				setTimeout(() => {
+					/**
+					 * Handling a possible edge case where provider registered event
+					 * might have been called before we await for it.
+					 */
+					resolve(this._providers[providerId]);
+				}, 30000);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:69]: 30 seconds is a long time to wait...why not instead just : 

1. Always await the promise (get rid of the initial providers map check)
2. Within the promise do the check in the map first and if it exists then immediately resolve
3. Still have a timeout but just return undefined (or reject) if it gets hit

This way in the edge case it'll still return immediately instead of blocking everything waiting for 30seconds unnecessarily

File: src/sql/workbench/services/executionPlan/common/executionPlanService.ts [hunk 2]
```diff
@@ -27,21 +27,59 @@ export class ExecutionPlanService implements IExecutionPlanService {
...
+			await new Promise<void>(resolve => {
 				this._capabilitiesService.onCapabilitiesRegistered(e => {
-					resolve(Object.keys(this._capabilitiesService.providers));
+					resolve();
 				});
 			});
 		}
+	}
+
+	private async getExecutionPlanProvider(providerId: string): Promise<azdata.executionPlan.ExecutionPlanProvider> {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/executionPlan/common/executionPlanService.ts:41]: This should be returning `Promise<azdata.executionPlan.ExecutionPlanProvider | undefined>`
