### PR TITLE
Fix Notebook Connection Profile Passing Bugs

### LINKED ISSUE #8688: Connection Profile Still Passed in to Notebooks in Certain Cases
Need to cleanup another place where connection profile was still getting set from the notebook component.

In the same vein, connection profile was being defaulted to when starting a new session (instead of the active connection in a notebook), which has the potential to cause a subtle bug when changing a connection using the SQL kernel and then switching to a jupyter kernel.

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #8688.

Connection profile was getting set automatically for notebooks in the notebook component for some file->open scenarios.

In addition, a subtle bug where we were using this.connectionProfile when starting a new session instead of using this._activeConnection if it was already set.

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -449,7 +449,9 @@ export class NotebookModel extends Disposable implements INotebookModel {
 			if (!this._activeClientSession) {
 				this.updateActiveClientSession(clientSession);
 			}
-			let profile = new ConnectionProfile(this._notebookOptions.capabilitiesService, this.connectionProfile);
+
+			// If a connection profile is passed in and _activeConnection isn't yet set, use that. Otherwise, use _activeConnection
+			let profile = this._activeConnection ? this._activeConnection : new ConnectionProfile(this._notebookOptions.capabilitiesService, this.connectionProfile);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/models/notebookModel.ts]: So while looking at this I noticed something odd - on [line 683](https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/contrib/notebook/browser/models/notebookModel.ts#L683) you're setting _activeConnection to the new connection but then in the next line you're calling setActiveConnectionIfDifferent which is never going to do anything because the id's will always be the same.

Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/models/notebookModel.ts]: lemme take a look at that separately. i'd like to keep this change as minimal as possible and not introduce any other risk into this PR if at all possible.

**Comment by chlafreniere** [comment]
Yes, agreed. Will add a couple of new tests separately.
