### PR TITLE
Introduce Universal resource provider to fix ARM throttling issues

### LINKED ISSUE #22321: "..error occured while loading Azure resources"
Issue Type: <b>Bug</b>

- Log in with my Azure AD account
- Open Azure Datat Studio
- Add new connection, "Browse" the Azure AD Account
- The error says "An error occurred while loading Azure resources"
Screenshot 2023-03-14 080124
 
The underlying issue seems to be that request are throttled to the Azure back-end.

It would really be great if Azure Data Studio could be more clever in terms of caching results. I understand the API rate limit but the list of resources is not updated so often so it would make sense if Azure Data Studio could keep a local cache of this infromation to avoid hitting the rate limit API.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.58GB (16.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Major refactor to Azure core extension's ARM query design to fix #22321 
When browsing Azure resources while adding a new connection > Browse > Azure tab:

**Number of requests for 1 account before:**
- No. of Tenants X No. of Subscriptions X No. of resource types (12)
i.e. for a single account, single tenant, single subscription = **12 ARM requests**
for accounts with 100+ subscriptions this would yield to = <span style="color:red">**1200+ requests**</span>

This was a big issue as ARM requests would be easily throttled.

**Number of requests for 1 account with this change:**
- 1 per Tenant
i.e. All "supported" resources for all "filtered" subscriptions are fetched in single request, and added to result based on resource type.

As a follow up to this, I'll be cleaning up the GraphData derivates created by all providers in separate PR - which can be easily shared.

### CODE REVIEW

File: extensions/azurecore/src/azureResource/providers/universal/universalTreeDataProvider.ts [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+		return this.universalService;
+	}
+
+	public override getChildren(element: azureResource.IAzureResourceNode): Promise<azureResource.IAzureResourceNode[]> {
+		throw new Error('Method not supported for universal provider.');
+	}
+
+	public getTreeItemForResource(resource: azureResource.AzureResource, account: AzureAccount): azdata.TreeItem {
+		let service: AzureResourceUniversalService = this.universalService as AzureResourceUniversalService;
+		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/azureResource/providers/universal/universalTreeDataProvider.ts:35]: It would be great to fix these instead of just disabling the rule

Comment (cheenamalhotra) [reply extensions/azurecore/src/azureResource/providers/universal/universalTreeDataProvider.ts:35]: I'm trying.. :)

**Comment by cheenamalhotra** [comment]
Proceeding to merge to bring the fix in insiders build today! 😍
