### PR TITLE
Disable schema compare generate script and apply buttons after applying changes

### LINKED ISSUE #5727: Generate Script is not opening any file if script is empty
- Azure Data Studio Version:
Dev build

Steps to Reproduce:

1. Have no differences between two schemas (or just after apply)
2. Run generate script
3. Says generate scriptsucceded but doesnt show any script (because script is empty)

Apply/Generate script should give indication if no diff was found. Generate script is more prominent because apply anyways does nothing visible.

**Checked in SSDT : Apply/Generate Script buttons are disabled after apply only compare is allowed to handle this. Same if no differences were found.**

### PR DESCRIPTION
**Pull request by kisantia**
This disables the generate script and apply buttons after applying changes because the results are not valid anymore. The tooltip of these two buttons is then changed to "Press Compare to refresh the comparison" to explain why they are disabled.

Fixes #5727.

### CODE REVIEW

**Comment by udeeshagautam** [comment]
Haha just thinking we could have probably just done this for options change too :)

File: extensions/schema-compare/src/schemaCompareResult.ts [hunk 1]
```diff
@@ -493,6 +494,13 @@ export class SchemaCompareResult {
...
+
+					// disable apply and generate script buttons because the results are no longer valid after applying the changes
+					this.generateScriptButton.enabled = false;
+					this.generateScriptButton.title = reCompareToRefeshMessage;
+					this.applyButton.enabled = false;
+					this.applyButton.title = reCompareToRefeshMessage;
+
 					const service = await SchemaCompareResult.getService('MSSQL');
 					const result = await service.schemaComparePublishChanges(this.comparisonResult.operationId, this.targetEndpointInfo.serverName, this.targetEndpointInfo.databaseName, azdata.TaskExecutionMode.execute);
 					if (!result || !result.success) {
```
Comment (udeeshagautam) [inline extensions/schema-compare/src/schemaCompareResult.ts]: If apply failed... we should allow second apply or generate script. You can do that by either changing to recompare only after apply result comes back or by changing back if it failed...  whatever looks better on UI

File: extensions/schema-compare/src/schemaCompareResult.ts [hunk 2]
```diff
@@ -493,6 +494,13 @@ export class SchemaCompareResult {
 						'startTime': Date.now().toString(),
 						'operationId': this.comparisonResult.operationId
 					});
+
+					// disable apply and generate script buttons because the results are no longer valid after applying the changes
+					this.generateScriptButton.enabled = false;
+					this.generateScriptButton.title = reCompareToRefeshMessage;
```
[the remark this answers is not in the document]
Comment (kisantia) [reply extensions/schema-compare/src/schemaCompareResult.ts]: yup the titles get reset in startCompare()

File: extensions/schema-compare/src/schemaCompareResult.ts (hunk 1 above)
Comment (kisantia) [reply extensions/schema-compare/src/schemaCompareResult.ts]: hmm I'll add that it the buttons will be enabled again if it wasn't a success, but I think most failures would be returned from the task and not where this code is, so the buttons would still be disabled in that case.
