### PR TITLE
set ignoreOverrides false for ipynb and sql files

### LINKED ISSUE #10490: SQL/IPYNB files opened that use showTextDocument() API, are now shown a text editor.
- Azure Data Studio Version:

Steps to Reproduce:

1. Launch TSG book from command pallet: 'SQL Server 2019 Guide'
2. Open any markdown file that have relative links to ipynb files. (Ex: TroubleShooters markdown)
3. Open any notebook link

Expected:
Notebook file opens with correct kernel.
Actual:
Notebook opens up as text file with json content.

This also repros when the relative files are sql files. They just open as text files.

Following VSCode change is the cause:  https://github.com/microsoft/vscode/issues/96888

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #10490

### CODE REVIEW

File: src/vs/workbench/api/browser/mainThreadEditors.ts [hunk 1]
```diff
@@ -125,7 +125,7 @@ export class MainThreadTextEditors implements MainThreadTextEditorsShape {
 			// preserve pre 1.38 behaviour to not make group active when preserveFocus: true
 			// but make sure to restore the editor to fix https://github.com/microsoft/vscode/issues/79633
 			activation: options.preserveFocus ? EditorActivation.RESTORE : undefined,
-			ignoreOverrides: true
+			ignoreOverrides: uri.fsPath.endsWith('ipynb') || uri.fsPath.endsWith('sql') ? false : true // {{SQL CARBON EDIT}}
```
Comment (chlafreniere) [inline src/vs/workbench/api/browser/mainThreadEditors.ts:128]: do we need a toLower() here (i.e. a file is *.SQL or *.IPYNB)? Does that scenario work, or do we need a toLower() here?

File: src/vs/workbench/api/browser/mainThreadEditors.ts [hunk 2]
```diff
@@ -125,7 +125,7 @@ export class MainThreadTextEditors implements MainThreadTextEditorsShape {
 			// preserve pre 1.38 behaviour to not make group active when preserveFocus: true
 			// but make sure to restore the editor to fix https://github.com/microsoft/vscode/issues/79633
 			activation: options.preserveFocus ? EditorActivation.RESTORE : undefined,
-			ignoreOverrides: true
+			ignoreOverrides: uri.fsPath.toLowerCase().endsWith('ipynb') || uri.fsPath.toLowerCase().endsWith('sql') ? false : true // {{SQL CARBON EDIT}}
```
Comment (kburtram) [inline src/vs/workbench/api/browser/mainThreadEditors.ts:128]: do we know that uri will never be undefined here?

Comment (chlafreniere) [reply src/vs/workbench/api/browser/mainThreadEditors.ts:128]: I've been testing this myself. I haven't gotten into this case yet, but we should be defensive about this for uri and probably uri.fsPath as well.

Comment (kburtram) [reply src/vs/workbench/api/browser/mainThreadEditors.ts:128]: yeah, particularly with the change coming so close to the release.  unless, we can see a null check further up the callstack, or uri being referenced unchecked lower in the stack (in which case it will fail anyways)

Comment (chlafreniere) [reply src/vs/workbench/api/browser/mainThreadEditors.ts:128]: right, those 2 scenarios don't appear to be true.

Comment (MaddyDev) [reply src/vs/workbench/api/browser/mainThreadEditors.ts:128]: there's no null check for uri, but further up the callstack they're resolving the document uri before calling this: https://github.com/microsoft/azuredatastudio/blob/b02b41815d06ac472de81c5cafdcc6e9283fed8a/src/vs/workbench/api/common/extHost.api.impl.ts#L455
