### PR TITLE
Fix for revert on pressing escape.

### LINKED ISSUE #9083: ESC doesn't revert cell edits when Editing Data on a table
- Azure Data Studio Version: `1.15.0` - This is a regression from `1.14.1`

Steps to Reproduce:

1. Edit Data on a table
2. Start editing a cell then hit ESC character. 

Expected: Cell is reverted and focus moved out of cell.  Cell is no longer in edit mode.

Actual: Cell is not reverted and focus is not moved out of cell.  This functionality is particularly important when a cell has a validation error.  Users often hit ESC to revert the edits.  With the current experience user either has to keep editing the cell until its valid or bring up the row context menu to revert the row.  Otherwise, the user is stuck in a validation loop and can't move focus out of cell

*For example, below ESC should dismiss the notification, revert the cell edit and move focus out of edited cell*
Screen Shot 2020-02-07 at 12 36 03 AM

### PR DESCRIPTION
**Pull request by smartguest**
Added a listener for escape key, row will be reverted upon hitting escape. Also the currentEditCellValue is set to undefined in the function so that the value will not persist upon clicking another cell.

This PR fixes #9083

### CODE REVIEW

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 1]
```diff
@@ -509,6 +511,7 @@ export class EditDataGridPanel extends GridParentComponent {
 					return this.removeRow(currentNewRowIndex);
 				}).then(() => {
 					this.newRowVisible = false;
+					this.currentEditCellValue = undefined;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: It seems like this should be done inside resetCurrentCell() instead. Can you see any reason why it wouldn't be done there? There's a couple other places we're calling that method and it seems like in all those cases we should also be clearing the currentEditCellValue (such as https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts#L512)

Maybe not something to take for the 1.15 release but worth checking while we're fixing this.

Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts]: I agree, at least two other times its done like that.
