### PR TITLE
Fix column text overflow on BDC status pages

### LINKED ISSUE #7916: BDC Cluster Overview: state column text too large if "waitingforresults" status
Issue Type: <b>Bug</b>

Connected to BDC cluster and HDFS has a status "waitingforresults" that over-writes the column width:

image

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (6c5aa6b36739e45cc66757e1f4845f40d368f017, 2019-10-21T07:45:28.442Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz (40 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|127.96GB (22.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
big-data-cluster|Mic|0.0.1
resource-deployment|Mic|0.0.1
sql-vnext|Mic|0.16.0

</details>

### LINKED ISSUE #7953: HDFS Manage access UI - "Sticky"
Issue Type: <b>Bug</b>

We shoukd rename Sticjy to "Sticky bit"

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (75388cc3afd30f5d69d4e5752b62fda6351b78ca, 2019-10-15T07:33:39.693Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
scala|sca|0.3.8

</details>

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7916

- Adds a bunch of new states that were added
- Expanded cell width so we can display all existing strings nicely
- Added overflow to text so that even if we do get a really long state name back that we don't know about it'll still not overflow at least
- Added title tooltip to text so that if text is cut off users can still see full text

Also fixes #7953 - updating label from **Sticky** to **Sticky Bit**

Longest translated string we have currently :

image

image

String issue was reported with (medium length) :
image

image

Short string (normal case) :
image

image

Really long unknown state : 
image

image

### CODE REVIEW

File: extensions/big-data-cluster/src/bigDataCluster/utils.ts [hunk 1]
```diff
@@ -71,36 +71,50 @@ export function showErrorMessage(error: any, prefixText?: string): void {
...
+	'applyingmanagedupgrade': localize('state.applyingmanagedupgrade', "Applying Managed Upgrade"),
+	'managedupgrading': localize('state.managedUpgrading', "Managed Upgrading"),
+	'rollback': localize('state.rollback', "Rollback"),
+	'rollbackinprogress': localize('state.rollbackInProgress', "Rollback In Progress"),
+	'rollbackcomplete': localize('state.rollbackComplete', "Rollback Complete"),
+	'error': localize('state.error', "Error"),
+
+	// BigDataClusterStateMachine
+	'creatingsecrets': localize('state.creatingSecrets', "Creating Secrets"),
+	'waitingforsecrets': localize('state.waitingForSecrets', "Waiting Fo Secrets"),
```
Comment (kevcunnane) [inline extensions/big-data-cluster/src/bigDataCluster/utils.ts]: Typo `Waiting For Secrets`

Comment (Charles-Gagnon) [reply extensions/big-data-cluster/src/bigDataCluster/utils.ts]: Here I was just trying to be hip and cool with the lingo too
