### PR TITLE
Fix #6396 Spark link is incorrect on latest server

### LINKED ISSUE #6396: Spark link in PySpark3 kernel on 1st cell run is incorrect on latest server
From Travis:
- Noticed that the Spark link in the ADS notebooks still links to the wrong place (https://sparkhead-0.sparkhead-svc:8090/proxy/application_1563296940451_0006/). YARN URL is correct.

Note: I cannot repro, so asking for cluster that can repro this.

### PR DESCRIPTION
**Pull request by kevcunnane**
Internal Spark endpoint value changed. Updated to handle old & new URL

### CODE REVIEW

File: src/sql/workbench/parts/notebook/models/cell.ts [hunk 1]
```diff
@@ -452,7 +452,11 @@ export class CellModel implements ICellModel {
 						let host = endpoint && endpoint.ipAddress ? endpoint.ipAddress : model.activeConnection.serverName;
 						let port = endpoint && endpoint.port ? ':' + endpoint.port.toString() : defaultPort;
 						let html = result.data['text/html'];
+						// Old Spark link
```
Comment (chlafreniere) [inline src/sql/workbench/parts/notebook/models/cell.ts]: What does "old" refer to here? Can we add an issue to track removing this in the future?

Comment (kevcunnane) [reply src/sql/workbench/parts/notebook/models/cell.ts]: CTP 3.1 or older. Will fix
