### PR TITLE
Fix agent context menu to appear in correct location

### LINKED ISSUE #5637: SQL Agent context menu is showing in bottom corner of application
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open Alerts page and right-click an alert item

Expected: Context menu shows where I clicked

Actual: Context menu shows at bottom corner of screen

image

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #5637 At some point the event type changed so this broke. Updating to new type of anchor. Also minor cleanup on the getTableActions functions.

image

### CODE REVIEW

File: src/sql/workbench/parts/jobManagement/electron-browser/jobManagementView.ts [hunk 1]
```diff
@@ -72,20 +73,26 @@ export abstract class JobManagementView extends TabChild implements AfterContent
...
+			const actionContext: IJobActionInfo = {
 				ownerUri: ownerUri,
 				targetObject: targetObject,
 				component: this
 			};
 
-			let anchor = { x: event.pageX + 1, y: event.pageY };
+			let anchor: { x: number, y: number };
+			if (event.anchor instanceof HTMLElement) {
+				anchor = { x: event.anchor.getBoundingClientRect().left + 1, y: event.anchor.getBoundingClientRect().top };
```
Comment (anthonydresser) [inline src/sql/workbench/parts/jobManagement/electron-browser/jobManagementView.ts]: I don't think you need to do this conditional, the anchor type on the event is designed to be passed directly as the anchor to the contextmenuservice, which accepts a object or an htmlelement as a anchor type.

Comment (Charles-Gagnon) [reply src/sql/workbench/parts/jobManagement/electron-browser/jobManagementView.ts]: Sometimes the answer is right in front of your face, thanks!
