### PR TITLE
Fix sql proj sqlcmd table showing after loading publish profile when it shouldn't

### LINKED ISSUE #11468: SQLCMD table showing after loading profile when it shouldn't
Steps to Reproduce:

1. Open a SQL Project without any SQLCMD variables
2. Right click on Project and select publish. Dialog opens without any table for SQLCMD variables as expected
3. load a profile without SQLCMD variables
4. SQLCMD variables table shows up but it shouldn't

Screen Shot 2020-07-21 at 3 41 18 PM

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #11468. This adds a couple checks for if the loaded publish profile didn't have any sqlcmd variables: 
- table should only be added if the profile has sqlcmd variables 
- table should be removed if both the profile and project don't have sqlcmd variables

### CODE REVIEW

File: extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts [hunk 1]
```diff
@@ -418,13 +424,14 @@ export class PublishDatabaseDialog {
...
-					this.formBuilder?.insertFormItem({
-						title: constants.sqlCmdTableLabel,
-						component: <azdata.TableComponent>this.sqlCmdVariablesTable
-					},
-						6);
+				if (Object.keys(result.sqlCmdVariables).length) {
+					// add SQLCMD Variables table if it wasn't there before
+					if (Object.keys(this.project.sqlCmdVariables).length === 0) {
+						this.formBuilder?.insertFormItem(<azdata.FormComponent>this.sqlCmdVariablesFormComponent, 6);
+					}
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts:431]: 6?

Comment (kisantia) [reply extensions/sql-database-projects/src/dialogs/publishDatabaseDialog.ts:431]: it's the index that the table is being inserted at
