### PR TITLE
Fix highlight issue

### LINKED ISSUE #12268: Selecting pinned notebook will highlight notebook in Notebooks Viewlet
When selecting a pinned notebook and the book that contains the notebook is in the Notebooks Viewlet, the notebook in the Notebooks Viewlet is highlighted.

- Azure Data Studio Version:
Version: 1.22.0-rc1
Commit: cea9194595b440a6855108b4cf9b8d5dfa9be525
Date: 2020-09-14T17:39:13.623Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Open a Book in the Notebooks Viewlet
2. Pin a notebook that is in the Notebooks Viewlet
3. Select the pinned notebook
4. The notebook in the Notebooks Viewlet will be highlighted

### PR DESCRIPTION
**Pull request by barbaravaldez**
This PR addresses #12268
fixPinnedNotebook

### CODE REVIEW

File: extensions/notebook/src/book/bookTreeView.ts [hunk 1]
```diff
@@ -492,7 +491,7 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 		let notebookConfig = vscode.workspace.getConfiguration(constants.notebookConfigKey);
 		let maxDepth = notebookConfig[constants.maxBookSearchDepth];
 		// Use default value if user enters an invalid value
-		if (isNullOrUndefined(maxDepth) || maxDepth < 0) {
+		if (maxDepth === null || maxDepth === undefined || maxDepth < 0) {
```
Comment (chlafreniere) [inline extensions/notebook/src/book/bookTreeView.ts:494]: Can you provide context on this change?

File: extensions/notebook/src/book/bookTreeView.ts [hunk 2]
```diff
@@ -313,7 +312,7 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 		if (shouldReveal || this._bookViewer?.visible) {
 			bookItem = notebookPath ? await this.findAndExpandParentNode(notebookPath) : undefined;
 			// Select + focus item in viewlet if books viewlet is already open, or if we pass in variable
-			if (bookItem) {
+			if (bookItem && bookItem.contextValue !== 'pinnedNotebook') {
```
Comment (chlafreniere) [inline extensions/notebook/src/book/bookTreeView.ts:315]: I believe you should be able to do the same with

```
			if (bookItem?.contextValue !== 'pinnedNotebook') {
```

File: extensions/notebook/src/book/bookTreeView.ts (hunk 1 above)
Comment (barbaravaldez) [reply extensions/notebook/src/book/bookTreeView.ts:494]: I got a warning from IntelliSense saying that the method is deprecated since v4.0.0

File: extensions/notebook/src/book/bookTreeView.ts [hunk 3]
```diff
@@ -587,7 +586,9 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 	getNavigation(uri: vscode.Uri): Thenable<azdata.nb.NavigationResult> {
 		let result: azdata.nb.NavigationResult;
 		let notebook = this.currentBook?.getNotebook(uri.fsPath);
-		if (notebook) {
+		// checking viewId to verify that the book is opened in the Notebooks Viewlet
+		// which indicates if navigation buttons should be visible or hidden.
+		if (this.viewId === constants.BOOKS_VIEWID && notebook) {
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts:591]: What is this fixing? Don't we still want navigation buttons in the provided books too?

Comment (barbaravaldez) [reply extensions/notebook/src/book/bookTreeView.ts:591]: If the book is closed, we don't want to show the navigation buttons in the pinned notebooks. I'll modify the condition because it's not working for Provided Books.

**Review by chlafreniere — APPROVED** [review]

**Review by lucyzhang929 — APPROVED** [review]

File: extensions/notebook/src/book/bookTreeView.ts [hunk 4]
```diff
@@ -587,7 +586,9 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 	getNavigation(uri: vscode.Uri): Thenable<azdata.nb.NavigationResult> {
 		let result: azdata.nb.NavigationResult;
 		let notebook = this.currentBook?.getNotebook(uri.fsPath);
-		if (notebook) {
+		// checking viewId to verify that the book is opened in the Notebooks Viewlet
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts:589]: FYI it's "view" in this case, not "viewlet". Viewlet's are the sidebar items - each tree in a viewlet is a separate view.

**Review by Charles-Gagnon — APPROVED** [review]
