### PR TITLE
Fix/highlight correct item

### LINKED ISSUE #10938: Notebook Viewlet doesn't highlight activated / opened file from Search viewlet
- Azure Data Studio Version:
Version: 1.18.1 (user setup)
Commit: 5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa
Date: 2020-05-26T21:14:29.147Z
VS Code: 1.45.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Go to Search Viewlet.
2. Search for a keyword.
3. Open the file from the search result.
4. Navigate to the Notebook viewlet.
Here you can see that the activated / opened file is not highlighted. So if user wants to open the neighboring notebook, they won't be able to. 

Expected: Activated / opened file from Search viewlet should be highlighted in Notebook viewelet.

### PR DESCRIPTION
**Pull request by MaddyDev**
Issue: Treeitem corresponding to the active notebook is not highlighted when it is nested within a parent that's collapsed. 

Fix: TreeView does not load all the children on render. It lazy loads them only when the parent is selected. So when a element that's corresponding to the active notebook is the child of a collapsed node, getNotebook() that returns the bookTreeItem is undefined. We need to explicitly select the parentNode or call getChildren() method on the parentNode to get the elements first before calling getNotebook().

This PR fixes #10938 

fixHighlightFromSearch

### CODE REVIEW

File: extensions/notebook/src/book/bookTreeView.ts [hunk 1]
```diff
@@ -234,16 +237,40 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
...
+						await this._bookViewer.reveal(bookNode, { select: true, focus: false, expand: 3 });
+						bookItem = this.currentBook?.getNotebook(notebookPath);
+					}
+				}
 			}
 		} else if (uri.fsPath) {
+			let notebookPath = uri.fsPath;
 			bookItem = this.currentBook?.getNotebook(uri.fsPath);
+			// if the node is not expanded getNotebook returns undefined, try getChildren of the book to get the item.
+			if (!bookItem) {
```
Comment (corivera) [inline extensions/notebook/src/book/bookTreeView.ts:258]: Looks like these code sections are the same besides the initial notebookPath. You could probably move this into a separate block below, and only fill the target notebook path in these if cases.
