### PR TITLE
fix relative paths in wysiwyg

### LINKED ISSUE #14736: [WYSIWYG] Relative Link paths are changed when updating cells.
Absolute links are changed to relative links, but relative links are changed to a different path, when updating the code cell.
It's important to note that both links keep working, but it could be confusing for the user to see a different path from what they entered.
Actual result:
```
[absolute links](.\WIT-Demo\Notebook.ipynb)

[relative link](..\AppData\Local\Programs\Azure%20Data%20Studio%20-%20RC1\resources\app\out\vs\code\electron-browser\workbench\WIT-Demo\Notebook.ipynb)
```

Expected Result:
```
[absolute links](.\WIT-Demo\Notebook.ipynb)

[relative link](.\WIT-Demo\Notebook.ipynb)
```

Azure Data Studio Version:
Version: 1.27.0-rc1 (user setup)
Commit: 3368af9
Date: 2021-03-15T06:07:09.474Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
Steps to Reproduce:

1. Create a code cell
2. Add a link in WYSIWYG, using the link button
3. Exit the cell
4. Re-enter the cell and update it.
5. The relative link has been changed to a different path.

### PR DESCRIPTION
**Pull request by barbaravaldez**
Convert relative paths to absolute paths based on the notebook uri before converting to markdown
This PR fixes #14736
Screen Shot 2021-03-16 at 12 45 20 PM

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 1]
```diff
@@ -232,10 +234,24 @@ export class MarkdownToolbarComponent extends AngularDisposable {
 			if (this.cellModel.currentMode !== CellEditModes.WYSIWYG) {
 				needsTransform = false;
 			} else {
+				let result = undefined;
+				const isFile = !URI.parse(linkCalloutResult?.insertUnescapedLinkUrl).scheme.includes('http');
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:238]: There are other schemes possible too ('https' as one). Is there a reason why we can't check for 'file' directly?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 2]
```diff
@@ -232,10 +234,24 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+				if (!path.isAbsolute(linkCalloutResult?.insertUnescapedLinkUrl) && isFile) {
+					let midDirectories = (linkCalloutResult?.insertUnescapedLinkUrl.match(/..\\/g) || []).length;
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:240]: comment would be good here. it's not immediately clear what `midDirectories` refers to.

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 1 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:238]: I remember that sometimes the scheme in Windows is 'c', instead of file; but I'm not sure if that only happens when trying to parse an absolute path ex: C://Users/hello/world, so maybe we can check only for 'file'.

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 3]
```diff
@@ -232,10 +234,24 @@ export class MarkdownToolbarComponent extends AngularDisposable {
 			if (this.cellModel.currentMode !== CellEditModes.WYSIWYG) {
 				needsTransform = false;
 			} else {
+				let result = undefined;
+				const isFile = URI.parse(linkCalloutResult?.insertUnescapedLinkUrl).scheme.includes('file');
+				if (!path.isAbsolute(linkCalloutResult?.insertUnescapedLinkUrl) && isFile) {
+					// Counts the number of ..\ intermediate directories when user enters a relative path
+					let midDirectories = (linkCalloutResult?.insertUnescapedLinkUrl.match(/..\\/g) || []).length;
+					let dirName = path.dirname(this.cellModel?.notebookModel?.notebookUri.fsPath);
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:242]: notebookDirName would be more clear.

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 2 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:241]: Can we change this to include the string `num` in the variable name somewhere? For clarity 😄

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 4]
```diff
@@ -232,10 +234,24 @@ export class MarkdownToolbarComponent extends AngularDisposable {
 			if (this.cellModel.currentMode !== CellEditModes.WYSIWYG) {
 				needsTransform = false;
 			} else {
+				let result = undefined;
+				const isFile = URI.parse(linkCalloutResult?.insertUnescapedLinkUrl).scheme.includes('file');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:238]: Is there a reason you're using includes here instead of ===? Do you expect other schemes containing file to be valid?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 5]
```diff
@@ -232,10 +234,24 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+				if (!path.isAbsolute(linkCalloutResult?.insertUnescapedLinkUrl) && isFile) {
+					// Counts the number of ..\ intermediate directories when user enters a relative path
+					let midDirectories = (linkCalloutResult?.insertUnescapedLinkUrl.match(/..\\/g) || []).length;
+					let dirName = path.dirname(this.cellModel?.notebookModel?.notebookUri.fsPath);
+					const relativePath = linkCalloutResult?.insertUnescapedLinkUrl.replace(/\.\\/g, '/');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:243]: This doesn't seem like it'd handle multiple .. well...for example if I have `..\..\..\notebook.ipynb` then wouldn't relative path end up being `./././notebook.ipynb`?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 6]
```diff
@@ -232,10 +234,24 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+						midDirectories--;
+					}
+					result = path.join(dirName, relativePath);
+				}
 				// Otherwise, re-focus on the output element, and insert the link directly.
 				this.output?.nativeElement?.focus();
+				result = result ? result : linkCalloutResult?.insertUnescapedLinkUrl;
 				// Callout is responsible for returning escaped strings
-				document.execCommand('insertHTML', false, `<a href="${linkCalloutResult?.insertUnescapedLinkUrl}">${linkCalloutResult?.insertUnescapedLinkLabel}</a>`);
+				document.execCommand('insertHTML', false, `<a href="${result}">${linkCalloutResult?.insertUnescapedLinkLabel}</a>`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:254]: Shouldn't we be escaping the result and label here? Those might contain HTML characters

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 7]
```diff
@@ -232,10 +234,24 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
 				needsTransform = false;
 			} else {
+				let result = undefined;
+				const isFile = URI.parse(linkCalloutResult?.insertUnescapedLinkUrl).scheme.includes('file');
+				if (!path.isAbsolute(linkCalloutResult?.insertUnescapedLinkUrl) && isFile) {
+					// Counts the number of ..\ intermediate directories when user enters a relative path
+					let midDirectories = (linkCalloutResult?.insertUnescapedLinkUrl.match(/..\\/g) || []).length;
+					let dirName = path.dirname(this.cellModel?.notebookModel?.notebookUri.fsPath);
+					const relativePath = linkCalloutResult?.insertUnescapedLinkUrl.replace(/\.\\/g, '/');
+					while (midDirectories > 1) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:244]: Is there something preventing you from using `fs.resolve` instead of manually calculating all this path stuff out?

**Comment by VasuBhog** [comment]
Just tested this on Windows. 
The markdown preview shows the relative path like below.

image
image

'Guides\Release-Testing\Notebooks\WYSIWYG\WYSIWYG-test.ipynb' - relative path used

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 4 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts]: For now, we only expect file schemes

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 2 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts]: using fs.resolve instead

**Comment by barbaravaldez** [comment]
> Just tested this on Windows.
> The markdown preview shows the relative path like below.
> 
> image
> image
> 
> 'Guides\Release-Testing\Notebooks\WYSIWYG\WYSIWYG-test.ipynb' - relative path used

This should work now. @VasuBhog  can you double check that it works on your end?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 8]
```diff
@@ -232,10 +234,18 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+				let result = undefined;
+				const isFile = URI.parse(linkCalloutResult?.insertUnescapedLinkUrl).scheme === 'file';
+				if (!path.isAbsolute(linkCalloutResult?.insertUnescapedLinkUrl) && isFile) {
+					const notebookDirName = path.dirname(this.cellModel?.notebookModel?.notebookUri.fsPath);
+					const relativePath = linkCalloutResult?.insertUnescapedLinkUrl.replace(/(\.\\ | \.\/)/g, '/');
+					result = path.resolve(notebookDirName, relativePath);
+				}
 				// Otherwise, re-focus on the output element, and insert the link directly.
 				this.output?.nativeElement?.focus();
+				result = result ? result : linkCalloutResult?.insertUnescapedLinkUrl;
```
Comment (corivera) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:246]: You can replace this with a null-coalescing operator: "result ?? linkCalloutResult?.insertUnescapedLinkUrl". The operator returns the left value if it's not undefined/null, and the right value otherwise.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 9]
```diff
@@ -232,10 +234,18 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+					const notebookDirName = path.dirname(this.cellModel?.notebookModel?.notebookUri.fsPath);
+					const relativePath = linkCalloutResult?.insertUnescapedLinkUrl.replace(/(\.\\ | \.\/)/g, '/');
+					result = path.resolve(notebookDirName, relativePath);
+				}
 				// Otherwise, re-focus on the output element, and insert the link directly.
 				this.output?.nativeElement?.focus();
+				result = result ?? linkCalloutResult?.insertUnescapedLinkUrl;
 				// Callout is responsible for returning escaped strings
-				document.execCommand('insertHTML', false, `<a href="${linkCalloutResult?.insertUnescapedLinkUrl}">${linkCalloutResult?.insertUnescapedLinkLabel}</a>`);
+				document.execCommand('insertHTML', false, `<a href="${escape(result)}">${escape(linkCalloutResult?.insertUnescapedLinkLabel).replace(/%20/g, ' ')}</a>`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:248]: Why are you replacing %20 with spaces? Would suggest adding a comment about that

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 10]
```diff
@@ -232,10 +234,18 @@ export class MarkdownToolbarComponent extends AngularDisposable {
 			if (this.cellModel.currentMode !== CellEditModes.WYSIWYG) {
 				needsTransform = false;
 			} else {
+				let result = undefined;
+				const isFile = URI.parse(linkCalloutResult?.insertUnescapedLinkUrl).scheme === 'file';
+				if (!path.isAbsolute(linkCalloutResult?.insertUnescapedLinkUrl) && isFile) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:239]: I'd put the isFile check first so it can skip evaluating isAbsolute if it's not a file

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 11]
```diff
@@ -232,10 +234,18 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+					const notebookDirName = path.dirname(this.cellModel?.notebookModel?.notebookUri.fsPath);
+					const relativePath = linkCalloutResult?.insertUnescapedLinkUrl.replace(/(\.\\ | \.\/)/g, '/');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:241]: Could you explain what this is supposed to be doing?

And also what about my previous comment : 

> This doesn't seem like it'd handle multiple .. well...for example if I have ..\..\..\notebook.ipynb then wouldn't relative path end up being ./././notebook.ipynb?

Is there something making it so that users can't enter in ..\ manually in the URL?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 9 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:248]: I replace the %20 for whitespaces because the label is anything the users define as the text to display. 

Screen Shot 2021-03-16 at 11 07 55 AM

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 11 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:241]: The reason I replace the `..\` is because even if we have these two paths that should work. The second one doesn't work when we make the transformation to markdown. 
`../../../EmptyBook/readme.md`

`..\..\..\EmptyBook\readme.md`

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:241]: I'll just replace the backlashes for slashes instead of that regular expression

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 6 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts]: Can I use `encodeURI` instead of escape in the result? If I use escape then urls are identified as files.

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 12]
```diff
@@ -236,16 +237,16 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+					const relativePath = (linkCalloutResult?.insertUnescapedLinkUrl).replace(/\\/g, path.posix.sep);
 					result = path.resolve(notebookDirName, relativePath);
 				}
 				// Otherwise, re-focus on the output element, and insert the link directly.
 				this.output?.nativeElement?.focus();
 				result = result ?? linkCalloutResult?.insertUnescapedLinkUrl;
-				// Callout is responsible for returning escaped strings
-				document.execCommand('insertHTML', false, `<a href="${escape(result)}">${escape(linkCalloutResult?.insertUnescapedLinkLabel).replace(/%20/g, ' ')}</a>`);
+				// Callout is responsible for returning escaped strings. We replace %20 for whitespaces to allow spaces in the link's display text
+				document.execCommand('insertHTML', false, `<a href="${encodeURI(result)}">${escape(linkCalloutResult?.insertUnescapedLinkLabel).replace(/%20/g, ' ')}</a>`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:248]: For these I think you should just use https://github.com/microsoft/azuredatastudio/blob/main/src/vs/base/common/strings.ts#L40 instead - this isn't a URI and so we shouldn't be using a function to encode URIs here

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:248]: Let me try using that instead

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 13]
```diff
@@ -232,10 +235,18 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+					const notebookDirName = path.dirname(this.cellModel?.notebookModel?.notebookUri.fsPath);
+					const relativePath = (linkCalloutResult?.insertUnescapedLinkUrl).replace(/\\/g, path.posix.sep);
+					result = path.resolve(notebookDirName, relativePath);
+				}
 				// Otherwise, re-focus on the output element, and insert the link directly.
 				this.output?.nativeElement?.focus();
-				// Callout is responsible for returning escaped strings
-				document.execCommand('insertHTML', false, `<a href="${linkCalloutResult?.insertUnescapedLinkUrl}">${linkCalloutResult?.insertUnescapedLinkLabel}</a>`);
+				result = result ?? linkCalloutResult?.insertUnescapedLinkUrl;
+				// Callout is responsible for returning escaped strings.
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:248]: This comment doesn't seem to make sense anymore

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 14]
```diff
@@ -232,10 +235,18 @@ export class MarkdownToolbarComponent extends AngularDisposable {
 			if (this.cellModel.currentMode !== CellEditModes.WYSIWYG) {
 				needsTransform = false;
 			} else {
+				let result = undefined;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:238]: result is pretty generic - maybe use something clearer like `linkUrl` and default it to `linkCalloutResult.insertUnescapedLinkUrl`?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 13 above)
Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:248]: mm but we are scaping the strings, right?

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:248]: That's what I'm saying - this comment implies that the callout is the one doing the escaping. But that's not correct - the caller is the one responsible for doing that

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 15]
```diff
@@ -232,10 +235,16 @@ export class MarkdownToolbarComponent extends AngularDisposable {
 			if (this.cellModel.currentMode !== CellEditModes.WYSIWYG) {
 				needsTransform = false;
 			} else {
+				let linkUrl = linkCalloutResult?.insertUnescapedLinkUrl;
+				const isFile = URI.parse(linkUrl).scheme === 'file';
+				if (isFile && !path.isAbsolute(linkUrl)) {
+					const notebookDirName = path.dirname(this.cellModel?.notebookModel?.notebookUri.fsPath);
+					const relativePath = (linkCalloutResult?.insertUnescapedLinkUrl).replace(/\\/g, path.posix.sep);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:242]: linkCalloutResult is possibly undefined here yet you call replace without checking - which would throw. Is having an undefined result actually valid anyways?

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:242]: I think we check that it's not undefined before getting here

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:242]: https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts#L228

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:242]: If you're ever in this file again it would be nice to clean up that ? then since it's not doing anything

Comment (barbaravaldez) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:242]: you're right let me do that

**Review by lucyzhang929 — APPROVED** [review]
Tested on mac:
- add relative link, click out of cell, edit cell again, make sure markdown is not changed
- save, re-open notebook, make sure markdown is not changed
- paths with spaces

Looks good!

**Comment by barbaravaldez** [comment]
> Tested on mac:
> 
> * add relative link, click out of cell, edit cell again, make sure markdown is not changed
> * save, re-open notebook, make sure markdown is not changed
> * paths with spaces
> 
> Looks good!

Thank you, Lucy!!! 😄

**Review by Charles-Gagnon — APPROVED** [review]
Do you not have the issue with spaces being turned into %20 anymore?

And please look into adding some tests for this!

**Comment by barbaravaldez** [comment]
> Do you not have the issue with spaces being turned into %20 anymore?
> 
> And please look into adding some tests for this!

The escape library that we use only replaces `<, >, and &`.
