### PR TITLE
fix account dropdown list issue

### LINKED ISSUE #11251: azure account list not getting populated
the subscription list is populated properly but the account list is empty, if i press Refresh, then it will be correctly populated.

Screen Shot 2020-07-08 at 11 32 29 AM

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #11251

### CODE REVIEW

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 1]
```diff
@@ -806,7 +806,11 @@ async function processAzureAccountField(context: AzureAccountFieldContext): Prom
 		await vscode.commands.executeCommand('workbench.actions.modal.linkedAccount');
 		await populateAzureAccounts();
 	}));
-	await populateAzureAccounts();
+
+	// populate the values in a different batch as the initialization to avoid the issue that the account list is empty even though the values are correctly.
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:810]: But why is this happening? Is this that annoying race condition issue with the ModelView components again?

Comment (alanrenmsft) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts:810]: yes, request of setting actual dropdown values got executed first and then the request of setting the values to empty list because the all came in the same batch.

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts:810]: Odd that it's still having this issue - normally it happens if the data is set immediately after creation. And given that this is already in an async functionWhat if instead you fetched the accounts before creating the dropdown - and then just initialized the dropdown with those accounts? I just don't know if we can safely assume this is always going to fix the issue as it is. 

(realistically we need to fix that race condition bug - but that's a lot larger task so I guess doing something temporary like this in the short term is ok)

**Comment by alanrenmsft** [comment]
yeah, that is a much larger task.
more information here, this is what is being sent to the dropdown component in sequence:
Screen Shot 2020-07-09 at 1 52 57 PM

Screen Shot 2020-07-09 at 1 53 34 PM
