### PR TITLE
ML- Fixed a bug with loading model list

### LINKED ISSUE #16638: Machine Learning - View models dialog is broken
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Open ML dashboard
2. Select View/Import models

Expected: Should see the list of models or empty list
Actual: View is not loaded. Page is empty

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by llali**
Fixed the issue when loading model list UI.

### CODE REVIEW

File: extensions/machine-learning/src/views/models/manageModels/currentModelsComponent.ts [hunk 1]
```diff
@@ -200,7 +202,6 @@ export class CurrentModelsComponent extends ModelViewBase implements IPageView {
 
 	private refreshComponents(): void {
 		if (this._formBuilder) {
```
Comment (udeeshagautam) [inline extensions/machine-learning/src/views/models/manageModels/currentModelsComponent.ts:204]: wont we have to still remove in the this._dataTable.isEmpty = true flow?

**Review by udeeshagautam — APPROVED** [review]

**Comment by udeeshagautam** [comment]
> This PR fixes #16638

... it will close the bug even before port

File: extensions/machine-learning/src/views/models/manageModels/currentModelsComponent.ts (hunk 1 above)
Comment (llali) [reply extensions/machine-learning/src/views/models/manageModels/currentModelsComponent.ts:204]: remove is for cleaning up everything. no condition is needd
