### PR TITLE
Fix for edit data grid not showing

### LINKED ISSUE #10730: edit data editor is not showing any data
Screen Shot 2020-06-04 at 10 41 16 AM

### PR DESCRIPTION
**Pull request by smartguest**
Since the dimension is not set initially for flexibleSash, there must be a null check done to return a result for getHorizontalSashWidth when the Sash for it is being created.

This PR fixes #10730

### CODE REVIEW

File: src/sql/workbench/contrib/query/browser/flexibleSash.ts [hunk 1]
```diff
@@ -95,7 +95,10 @@ export class HorizontalFlexibleSash extends Disposable implements IHorizontalSas
 	}
 
 	public getHorizontalSashWidth?(): number {
-		return this.dimension.width;
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/query/browser/flexibleSash.ts:98]: maybe this? : this.dimension> this.dimension.width : 0;

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/query/browser/flexibleSash.ts:98]: Or just `return this.dimension?.width ?? 0`

Comment (smartguest) [reply src/sql/workbench/contrib/query/browser/flexibleSash.ts:98]: Seems easier that way
