### PR TITLE
Hide Open in Editor for notebook search

### LINKED ISSUE #12423: Open search results in editor not showing results
Steps to Reproduce:

1. Search a term in Notebooks View
2. When results load on the side bar, click on Open in Editor
3. Results are not loaded in the editor
Screen Shot 2020-09-17 at 3 55 02 PM

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #12423. Hiding search editor link from notebooks viewlet; users have given us feedback that it's confusing that the link doesn't do anything currently, and would rather not see it here.

image

image

### CODE REVIEW

File: src/vs/workbench/contrib/search/browser/searchView.ts [hunk 1]
```diff
@@ -1641,7 +1641,7 @@ export class SearchView extends ViewPane {
 		this.openerService.open(URI.parse('https://go.microsoft.com/fwlink/?linkid=853977'));
 	};
 
-	protected updateSearchResultCount(disregardExcludesAndIgnores?: boolean): void { // {{SQL CARBON EDIT}}
+	protected updateSearchResultCount(disregardExcludesAndIgnores?: boolean, showOpenInEditor = true): void { // {{SQL CARBON EDIT}} - Hide Open in Editor in Notebooks viewlet
```
Comment (kburtram) [inline src/vs/workbench/contrib/search/browser/searchView.ts:1644]: nit: maybe add a type for `showOpenInEditor` parameter.

**Review by kburtram — APPROVED** [review]
LGTM

**Review by alanrenmsft — APPROVED** [review]

**Review by MaddyDev — APPROVED** [review]
