### PR TITLE
Fix test script overwriting grep option

### LINKED ISSUE #8199: -g flag no longer works for tests
passing -g to the test shell script no longer works. Looks like the shell script is over writing the grep option.

I use -g all the time to limit what tests I run. We should handle this better.

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #8199

### CODE REVIEW

File: test/electron/index.js [hunk 1]
```diff
@@ -29,6 +29,14 @@ const optimist = require('optimist')
 
 const argv = optimist.argv;
 
+// {{SQL CARBON EDIT}}
+// Set test run options. These are NOT used if grep is specified manually - that implies the user has a specific desire to
+// filter the tests beyond the defaults set for ADS_TEST_GREP in the calling scripts.
+if (!argv.grep) {
```
Comment (anthonydresser) [inline test/electron/index.js]: I generally use -g instead of --grep.

Comment (anthonydresser) [reply test/electron/index.js]: Nvm i see its decribed above as both

Comment (Charles-Gagnon) [reply test/electron/index.js]: Yeah I tested this with -g so this should be working as intended with both 😄
