### PR TITLE
Fix Icon foreground to allow setting color from theme

### LINKED ISSUE #21279: Encrypt/Trust Server Certificate labels different colors than other labels
The labels for Encrypt and Trust Server Certificate are slightly different colors than the other modes

image

(the colors are different for light mode too, although it's not as obvious)

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes #21279 

image
_captured theme "Dark Azure Data Studio (default dark)"_

### CODE REVIEW

File: src/vs/platform/theme/common/colorRegistry.ts [hunk 1]
```diff
@@ -215,7 +215,9 @@ export const foreground = registerColor('foreground', { dark: '#CCCCCC', light:
...
 export const errorForeground = registerColor('errorForeground', { dark: '#F48771', light: '#A1260D', hcDark: '#F48771', hcLight: '#B5200D' }, nls.localize('errorForeground', "Overall foreground color for error messages. This color is only used if not overridden by a component."));
 export const descriptionForeground = registerColor('descriptionForeground', { light: '#717171', dark: transparent(foreground, 0.7), hcDark: transparent(foreground, 0.7), hcLight: transparent(foreground, 0.7) }, nls.localize('descriptionForeground', "Foreground color for description text providing additional information, for example for a label."));
-export const iconForeground = registerColor('icon.foreground', { dark: '#C5C5C5', light: '#424242', hcDark: '#FFFFFF', hcLight: '#292929' }, nls.localize('iconForeground', "The default color for icons in the workbench."));
+
+// {{SQL CARBON EDIT}} -- Update icon foreground color and let it be set by theme
+export const iconForeground = registerColor('icon.foreground', { dark: null, light: null, hcDark: null, hcLight: null }, nls.localize('iconForeground', "The default color for icons in the workbench."));
```
Comment (Charles-Gagnon) [inline src/vs/platform/theme/common/colorRegistry.ts:220]: Why are we using the icon foreground color for text? Shouldn't we be using the same color text as the rest of the dialog regardless of what the icon colors are like?

Comment (cheenamalhotra) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: This modifies the style 'color' on label as 'codicon' class is applied on the label. I checked almost all themes, and these hard-coded colors don't look too different than the theme defaults, so we shouldn't need to set them here.

Comment (Charles-Gagnon) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: We probably shouldn't be using codicon for the entire row (label + icon). The label isn't an icon after all. I would suggest looking into fixing that first. Generally, the label and icon would be separate elements in the DOM (usually as siblings in a div together).

If we're using the icon color for these labels then if someone goes and changes the color of icons to something completely different the labels will also show up with that different color (but not the other labels on the dialog)

Comment (cheenamalhotra) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: I couldn't make it work to get desired alignment without using background image, and couldn't find any other example for reference. If you have a solution for reference, please let me know.

Comment (Charles-Gagnon) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: The modelview dialogs have a text tooltip that can be set - e.g. from the deploy BDC wizard : 

image

This is done in code in src\sql\workbench\browser\modelComponents\text.component.ts - look at the modelview-text-tooltip.

Although you'll still need to be using background-image regardless, it's just that it'll be on its own element (that's a sibling of the text label element) instead of being a class directly on the label element itself.

image

Comment (cheenamalhotra) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: It seems like the 'codicon' class is not applied here, if that's what we are okay with, I can remove this class itself from the component. We don't need to change the whole design.

Comment (cheenamalhotra) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: Also to mention, icon colors don't change with CSS, its defined in svg files, so this infocon color is a myth.

Comment (cheenamalhotra) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: Apparently, I cannot remove codicon css, as it's needed for this design, I this the change is fine as-is as the icon-foreground color applies only to text on foreground and not the icon itself. And because all our text should be of same color, this change is probably necessary for proper theming.

Comment (cheenamalhotra) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: Apparently, removing 'codicon' breaks css consistency in common-icons.css, so I wouldn't recommend we go for it.

> If we're using the icon color for these labels then if someone goes and changes the color of icons to something completely different the labels will also show up with that different color (but not the other labels on the dialog)

And as mentioned above, this is not the case with codicons, I don't think we should have any concern.

Comment (Charles-Gagnon) [reply src/vs/platform/theme/common/colorRegistry.ts:220]: That's for our icons - codicons are a VS Code core concept and are done with fonts so they inherit the colors. (we've just hacked in our mostly-SVG based icons to use the same class for consistency and ease of use but with the downside that they don't get affected by settings such as the icon color) 

See https://code.visualstudio.com/api/references/theme-color#base-colors

For example, if you put this in your settings.json then it will color the icons red : 

```json
	"workbench.colorCustomizations": {
		"icon.foreground": "#ff0000"
	}
```

image

which then results in this for the labels

image


(doesn't really matter here, but FYI you can also change the colors of SVGs with CSS - see https://qawithexperts.com/article/html/how-to-change-color-of-svg-various-ways-using-css/414 for some examples)

File: src/sql/workbench/browser/modal/dialogHelper.ts [hunk 2]
```diff
@@ -23,7 +23,6 @@ export function appendRow(container: HTMLElement, label: string, labelClass: str
 	labelContainer.style.display = 'flex';
 
 	if (title) {
-		labelContainer.classList.add("codicon");
```
[the remark this answers is not in the document]
Comment (cheenamalhotra) [reply src/sql/workbench/browser/modal/dialogHelper.ts:26]: I thought about that, but it would become a very generic class, and it may contradict any other component classes unless it went into standard classes of codicon or something.

**Review by alanrenmsft — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/browser/modal/dialogHelper.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/workbench/browser/modal/dialogHelper.ts:26]: Curious what you mean by it "changes the entire design". What design is that? And what hacks are you talking about for the tooltip?

[the remark this answers is not in the document]
Comment (cheenamalhotra) [reply src/sql/workbench/browser/modal/dialogHelper.ts:26]: I meant the Custom Options tooltip current design would need rework, making sure descriptions can align well in connection dialog limited width. Currently we're using 'title' attribute, which provides in-built tooltip that is much lighter on UI, but with the other design tooltip is a component that is controlled on hover, it's not HTML's tooltip/title. 

If you want to spend time on that and think it's worth the effort, feel free to go for it, but as far it meets requirements, we shouldn't need to spend time on redoing it.
