### PR TITLE
3707 Kusto Icon Fix

### LINKED ISSUE #11495: Non-Kusto icons show for connections added through TSGWorkspace
- Azure Data Studio Version: 1.21

Steps to Reproduce:

1. Have Kusto connection added to TSGWorkspace.code-workspace
2. Open ADS and see connection in connection explorer
3. Notice the icon associated with the connection does not have a kusto icon

### PR DESCRIPTION
**Pull request by JustinMDotNet**
Changed getIconpath in serverTreeRenderer to always set iconPath if iconId is undefined. Changed renderConnection to always renderServerIcon

This PR fixes #11495

### CODE REVIEW

**Review by Charles-Gagnon — COMMENTED** [review]
What issue is this fixing?

And please include screenshots showing the fixed nodes + default server nodes to show there aren't regressions there.

**Comment by JustinMDotNet** [comment]
Adding screenshots showing the new icons.

### Connection Explorer
image
### Recent Connections
image

**Comment by Charles-Gagnon** [comment]
So what was the issue here? Not clear to me how this was broken in the first place - shouldn't the provider have had the correct icon ID?

**Comment by JustinMDotNet** [comment]
> So what was the issue here? Not clear to me how this was broken in the first place - shouldn't the provider have had the correct icon ID?

The issue we were seeing were the icons getting rendered (see screenshot below) before the providers were registered and never getting updated.

image

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
Your logic is defaulting to the first icon in the list but that isn't the current behavior - note that this is the current default icon :

image

But with your change now it's using the Azure SQL icon since it's first in the list :

image

I think we should do a couple things here to really fix this :

1. Add a new field to the iconPath objects called `default` - then if there isn't a valid connection you go through the provided icons and select the first one that is set as the default
1. Then in mssql go add a new iconPath value that uses the current default server icon and set it as default for MSSQL so that the behavior there doesn't change.

File: src/sql/platform/capabilities/common/capabilitiesService.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export const clientCapabilities = {
 
 export interface ConnectionProviderProperties {
 	providerId: string;
-	iconPath?: URI | IconPath | { id: string, path: IconPath }[]
+	iconPath?: URI | IconPath | { id: string, path: IconPath, default: boolean }[]
```
Comment (Charles-Gagnon) [inline src/sql/platform/capabilities/common/capabilitiesService.ts:25]: default should be optional

File: src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts [hunk 2]
```diff
@@ -171,16 +171,14 @@ export class ServerTreeRenderer implements IRenderer {
...
 
 		let iconId = this._connectionManagementService.getConnectionIconId(connection.id);
-		if (!iconId) { return undefined; }
-
 		let providerProperties = this._connectionManagementService.getProviderProperties(connection.providerName);
 		if (!providerProperties) { return undefined; }
 
 		let iconPath: IconPath | undefined = undefined;
-		let pathConfig: URI | IconPath | { id: string, path: IconPath }[] | undefined = providerProperties.iconPath;
+		let pathConfig: URI | IconPath | { id: string, path: IconPath, default: boolean }[] | undefined = providerProperties.iconPath;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts:178]: default should be optional

(I would also suggest making this into a defined type so we don't have it duplicated between the two trees)

File: src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts [hunk 3]
```diff
@@ -259,16 +260,14 @@ function getIconPath(connection: ConnectionProfile, connectionManagementService:
...
-
 	let providerProperties = connectionManagementService.getProviderProperties(connection.providerName);
 	if (!providerProperties) { return undefined; }
 
 	let iconPath: IconPath | undefined = undefined;
 	let pathConfig: URI | IconPath | { id: string, path: IconPath }[] | undefined = providerProperties['iconPath'];
 	if (Array.isArray(pathConfig)) {
 		for (const e of pathConfig) {
-			if (!e.id || e.id === iconId) {
+			if (!e.id || e.id === iconId || iconId === undefined) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/asyncServerTreeRenderer.ts:270]: Update the logic here to check for default as well

File: src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts [hunk 4]
```diff
@@ -171,16 +171,14 @@ export class ServerTreeRenderer implements IRenderer {
...
 		let providerProperties = this._connectionManagementService.getProviderProperties(connection.providerName);
 		if (!providerProperties) { return undefined; }
 
 		let iconPath: IconPath | undefined = undefined;
-		let pathConfig: URI | IconPath | { id: string, path: IconPath }[] | undefined = providerProperties.iconPath;
+		let pathConfig: URI | IconPath | { id: string, path: IconPath, default?: boolean }[] | undefined = providerProperties.iconPath;
 		if (Array.isArray(pathConfig)) {
 			for (const e of pathConfig) {
-				if (!e.id || e.id === iconId) {
+				if (!e.id || e.id === iconId || e.default) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/objectExplorer/browser/serverTreeRenderer.ts:181]: Actually the logic here needs to be 

`if (!e.id || e.id === iconId || (!iconId && e.default)) {`

otherwise if the default icon is before the actual icon we'll use the default instead.

File: src/sql/platform/capabilities/common/capabilitiesService.ts [hunk 5]
```diff
@@ -22,7 +22,7 @@ export const clientCapabilities = {
 
 export interface ConnectionProviderProperties {
 	providerId: string;
-	iconPath?: URI | IconPath | { id: string, path: IconPath }[]
+	iconPath?: URI | IconPath | { id: string, path: IconPath, default?: boolean }[]
```
Comment (Charles-Gagnon) [inline src/sql/platform/capabilities/common/capabilitiesService.ts:25]: Would suggest moving this out into its own type (ProviderIcon or something similar) and then update the pathConfigs to use that type as well.

**Review by Charles-Gagnon — APPROVED** [review]
Looks good once you fix the issue (and take a look at my suggestion too)
