### PR TITLE
Save Kusto Notebook with proper language notebook info

### LINKED ISSUE #14545: [Notebook] Kusto Notebook Language Info Metadata is only updated after connecting to a Kusto connection
- Azure Data Studio Version: 1.26.1
- Windows and Mac

**Not a Regression.**

Steps to Reproduce:

1. Created new notebook
2. Changed kernel to Kusto
3. Saved notebook
4. Reopened notebook

Change Kernel and Save:
StableSaveKusto

Change connection to Kusto cluster and save:
SaveKustoConnection

The language_info only gets updated after a user connects to a Kusto cluster.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #14545. Which now saves the language_info upon changing the kernel to Kusto and then saving the notebook.

Aliases such as Kusto in this example still use SQL as the kernel in the backed but we can set the language info to be set to kusto here before the user saves the new kusto notebook therefore the metadata will contain the proper kusto name and be opened with the Kusto kernel.

### CODE REVIEW

**Review by barbaravaldez — APPROVED** [review]

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -963,12 +963,20 @@ export class NotebookModel extends Disposable implements INotebookModel {
...
 		await this.updateKernelInfo(kernel);
+		let aliasLanguageInfo: nb.ILanguageInfo;
 		this.kernelAliases.forEach(kernel => {
 			if (this._defaultLanguageInfo?.name === kernel.toLowerCase()) {
 				kernelAlias = kernel;
 			}
 		});
-		if (kernel.info) {
+		if (kernelAlias) {
+			aliasLanguageInfo = {
```
Comment (lucyzhang929) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:973]: Since aliasLanguageInfo isn't used anywhere else, can we just declare it here:
`let aliasLanguageInfo: nb.ILanguageInfo = {`

**Review by lucyzhang929 — APPROVED** [review]

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 2]
```diff
@@ -963,12 +963,20 @@ export class NotebookModel extends Disposable implements INotebookModel {
 
 	private async updateKernelInfoOnKernelChange(kernel: nb.IKernel, kernelAlias?: string) {
 		await this.updateKernelInfo(kernel);
+		let aliasLanguageInfo: nb.ILanguageInfo;
 		this.kernelAliases.forEach(kernel => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:967]: While you're here - this could be refactored a bit to be clearer and shortcut execution when it finds an item : 

kernelAlias = this.kernelAliases.find(kernel => this._defaultLanguageInfo?.name === kernel.toLowerCase()) ?? kernelAlias`

**Review by Charles-Gagnon — APPROVED** [review]

**Review by corivera — APPROVED** [review]
