### PR TITLE
fix query plan doc failed to load issue

### LINKED ISSUE #14632: Cannot open query plan
- Azure Data Studio Version:
Version: 1.26.1
Commit: 796abbdf5fdd341e3528e30a6b777c93e115eb02
Date: 2021-02-24T23:37:01.966Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

- Steps to Reproduce:

1. Open any Sql Query plan exported by SSMS 18
2. Query plan doesn't open

Error in notification
Unable to open 'Query Plan': Cannot read property 'getBoundingClientRect' of null.

Devtools output:

  | onDidChangeNotification | @ | notificationsAlerts.ts:36
-- | -- | -- | --
  | (anonymous) | @ | breadcrumbsModel.ts:294
  | fire | @ | event.ts:570
  | addNotification | @ | notifications.ts:204
  | notify | @ | notificationService.ts:94
  | doHandleOpenEditorError | @ | editorGroupView.ts:1024
  | (anonymous) | @ | editorGroupView.ts:931
  | async function (async) |   |  
  | (anonymous) | @ | editorGroupView.ts:931
  | doShowEditor | @ | editorGroupView.ts:931
  | doOpenEditor | @ | editorGroupView.ts:931
  | openEditor | @ | editorGroupView.ts:888
  | openEditor | @ | editorService.ts:516
  | onEditorOpening | @ | editorReplacerContribution.ts:74
  | open | @ | untitledTextEditorInput.ts:21
  | onGroupWillOpenEditor | @ | editorService.ts:516
  | (anonymous) | @ | editorService.ts:109
  | fire | @ | event.ts:570
  | openEditor | @ | editorGroupView.ts:888
  | openEditor | @ | editorService.ts:516
  | openResources | @ | window.ts:570
  | async function (async) |   |  
  | openResources | @ | window.ts:570
  | onOpenFiles | @ | window.ts:506
  | async function (async) |   |  
  | onOpenFiles | @ | window.ts:506
  | (anonymous) | @ | window.ts:162
  | emit | @ | events.js:228
  | onMessage | @ | electron/js2c/renderer_init.js:115

image

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #14632 

turns out this feature never worked, I went all the way back to 0.33 release of sqlops studio :)

root cause:
if we use fileservice to read the text file, it is returned as binary and we use the toString method of it, the text is not the same as if we read it using textfileservice.

image

html-query-plan packages uses XSLT to transform the xml to html, and during rendering, it will look for the node with css class 'qp-root', but due to the malformed xml string, the html was not created successfully, and result in the error of can not read property getBoundingClientRect of null.

fix:

use textfileservice to read the file content.

with the fix:
image

### CODE REVIEW

File: src/sql/workbench/contrib/queryPlan/common/queryPlanInput.ts [hunk 1]
```diff
@@ -3,13 +3,13 @@
  *  Licensed under the Source EULA. See License.txt in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
 
-import { EditorInput, EditorModel, IEditorInput } from 'vs/workbench/common/editor';
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/queryPlan/common/queryPlanInput.ts:6]: organized imports, the only actual change is removed IFileService and added ITextFileService

**Review by abist — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
