### PR TITLE
highlight correct notebook on navigation.

### LINKED ISSUE #10780: Notebooks Viewlet Highlight Does Not Update when Navigating to Items in Book
Notebooks viewlet on PC does not update when navigating to different pages in a Jupyter book. The current item should be highlighted in the tree view.

Regression from May release.

### PR DESCRIPTION
**Pull request by MaddyDev**
PR to address the following in June milestone #10780 

Ported just the highlight fix part from #10523 : Previously we're trying to find the notebook to highlight in the current book which can be different when using the navigation links. (Current book is the book that's opened last on the viewlet.) Fix is to get the correct book first and then highlight the notebook in it.

### CODE REVIEW

**Comment by chlafreniere** [comment]
@MaddyDev can you provide a brief summary for what was broken?

File: extensions/notebook/src/extension.ts [hunk 1]
```diff
@@ -129,6 +129,14 @@ export async function activate(extensionContext: vscode.ExtensionContext): Promi
 	const providedBookTreeViewProvider = new BookTreeViewProvider(appContext.apiWrapper, [], extensionContext, true, PROVIDED_BOOKS_VIEWID);
 	await providedBookTreeViewProvider.initialized;
 
+	azdata.nb.onDidChangeActiveNotebookEditor(e => {
```
Comment (chlafreniere) [inline extensions/notebook/src/extension.ts:132]: This will steal focus whenever any other viewlet is already open, right?

(i.e. say the connections viewlet is open and a user uses the previous/next buttons to navigate between notebooks. Wouldn't this always focus on the notebooks viewlet again?)

Comment (chlafreniere) [reply extensions/notebook/src/extension.ts:132]: Another scenario to test is the following:
- If a user navigates from one viewlet to the notebooks viewlet and a notebook that exists in the viewlet is opened, that notebook should be highlighted.

Comment (MaddyDev) [reply extensions/notebook/src/extension.ts:132]: yes, reveal will open the viewlet irrespective if the viewlet is not currently active.

Comment (chlafreniere) [reply extensions/notebook/src/extension.ts:132]: ok. how do we prevent that behavior?

Comment (chlafreniere) [reply extensions/notebook/src/extension.ts:132]: I believe passing in 'false' as the second parameter would stop this. Please correct me if I'm wrong.

File: extensions/notebook/src/book/bookTreeView.ts [hunk 2]
```diff
@@ -178,14 +178,6 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 			this.currentBook = book;
 		}
 		this._bookViewer = this._apiWrapper.createTreeView(this.viewId, { showCollapseAll: true, treeDataProvider: this });
-		this._bookViewer.onDidChangeVisibility(e => {
```
Comment (chlafreniere) [inline extensions/notebook/src/book/bookTreeView.ts:181]: Do we have to delete this code? This is the code that will set the highlight when the notebooks viewlet is visible.

File: extensions/notebook/src/extension.ts (hunk 1 above)
Comment (MaddyDev) [reply extensions/notebook/src/extension.ts:132]: We don't need to focus the viewlet each time a notebook in the viewlet is active on the editor?

File: extensions/notebook/src/book/bookTreeView.ts (hunk 2 above)
Comment (MaddyDev) [reply extensions/notebook/src/book/bookTreeView.ts:181]: added it back (sorry I totally missed why it was added in the first place)
