### PR TITLE
Show book's notebook TOC title in pinned notebooks view

### LINKED ISSUE #15576: Pinned Notebook should display friendly name (based on TOC)
- Azure Data Studio Version:
Version: 1.30.0-insider (user setup)
Commit: f691701c1c720a1a7662a1028a4b92a3baa1c2bd
Date: 2021-05-25T05:43:43.864Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Pin a notebook from a Jupyter Book
2. The notebook under the Pinned Notebooks section should show the friendly name as displayed in Jupyter Book. 
Currently it shows the file name instead. 

Note: not notebooks are part of a Jupyter Book. Need to think about what the experience should be for this as well.

### PR DESCRIPTION
**Pull request by barbaravaldez**
Screen Shot 2021-05-26 at 1 51 31 PM

This PR fixes #15576

### CODE REVIEW

**Review by lucyzhang929 — APPROVED** [review]

File: extensions/notebook/src/common/utils.ts [hunk 1]
```diff
@@ -475,16 +475,17 @@ function hasWorkspaceFolders(): boolean {
...
+export async function setPinnedBookPathsInConfig(pinnedNotebookPaths: INotebook[]): Promise<void> {
 	let config: vscode.WorkspaceConfiguration = vscode.workspace.getConfiguration(notebookConfigKey);
 	let storeInWorspace: boolean = hasWorkspaceFolders();
 
 	await config.update(pinnedBooksConfigKey, pinnedNotebookPaths, storeInWorspace ? false : vscode.ConfigurationTarget.Global);
 }
 
 
-export interface IBookNotebook {
+export interface INotebook {
```
Comment (MaddyDev) [inline extensions/notebook/src/common/utils.ts:486]: INotebook is very generic, if this is specific to pinned notebooks, would suggest to name it as INotebookPin

**Review by MaddyDev — APPROVED** [review]
