### PR TITLE
Callout Dialog Fixes + WYSIWYG Improvements for Insert Link

### LINKED ISSUE #12859: WYSIWYG does not provide an option for creating a link
WYSIWYG edit mode does not provide an option for inserting a link, need to switch to Split View. 
Screen Shot 2020-10-09 at 11 13 10 AM

- Azure Data Studio Version:
Version: 1.23.0-rc1
Commit: 7429407029af2e08d17a8928825815cffad94f17
Date: 2020-10-09T00:40:51.445Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Create a text cell and the toolbar does not provide a link option.

### LINKED ISSUE #14406: not able to do keyboard navigation within ADS because of the callout dialog
once we have the callout dialog opened once, the keyboard navigation within ADS is broken, unless the notebook is closed.

image

### PR DESCRIPTION
**Pull request by chlafreniere**
https://user-images.githubusercontent.com/40371649/109606492-9b7cb580-7adb-11eb-94d8-b44bf6dbe5c4.mp4

I apologize for fixing a few different things in this PR, but they were all related.

Fixes #12859.
Fixes #14406.

- Added Insert Link Callout functionality to WYSIWYG
- Link text in callout is set by default in both WYSIWYG + non-WYSIWYG editor modes if text is selected
- Keyboard navigation now works as expected in Link callout
- Fixed markdown generated in callout to be consistent with previous md link generation in non-WYSIWYG modes

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 1]
```diff
@@ -231,4 +264,49 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+			calloutOptions = await this._linkCallout.open();
+		}
+		return calloutOptions;
+	}
+
+	private getCurrentSelectionText(): string {
+		if (this.cellModel.currentMode === CellEditModes.WYSIWYG) {
+			return document.getSelection()?.toString() || '';
+		} else {
+			const nbEditor = this._notebookService.findNotebookEditor(this.cellModel?.notebookModel?.notebookUri);
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:298]: I don't like having this code live in the toolbar component. I thought about adding the ability to query for a cell's backing editor, but that only saves a couple of lines of code.

Having the cellModel handle the "text of what's currently selected" was another thing I thought about, but I'm not convinced that makes sense to live there either (and it's a bit niche). Any thoughts for where I can put this? Maybe a utility method or something?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 2]
```diff
@@ -231,4 +264,49 @@ export class MarkdownToolbarComponent extends AngularDisposable {
 			}
 		}
 	}
+
+	/**
+	 * Instantiate modal for use as callout when inserting Link or Image into markdown.
+	 * @param calloutStyle Style of callout passed in to determine which callout is rendered.
+	 * Returns markup created after user enters values and submits the callout.
+	 */
+	private async createCallout(type: MarkdownButtonType, triggerElement: HTMLElement): Promise<ILinkCalloutDialogOptions> {
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:273]: I didn't want the text transformer itself to have to know anything about callouts, so that's why I refactored it out.

**Review by lucyzhang929 — APPROVED** [review]
Tested linking and looks good! Theres still that issue of ESC key closing the dialog and exiting edit mode though.

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 3]
```diff
@@ -205,13 +213,38 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+			if (!calloutResult.insertLinkUrl) {
+				return;
+			}
+			// If cell edit mode isn't WYSIWYG, use result from callout. No need for further transformation.
+			if (this.cellModel.currentMode !== CellEditModes.WYSIWYG) {
+				needsTransform = false;
+			} else {
+				// Otherwise, re-focus on the output element, and insert the link directly.
+				this.output?.nativeElement?.focus();
+				// Callout is responsible for returning escaped strings
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:234]: Hm, if you're going to make this responsibility on the callout then I'd definitely explicitly call it `escapedLinkUrl` and `escapedLinkLabel`.

But in general I think you should leave it up to the caller to do that - because who knows what kind of escaping the caller actually wants? Sure in this case it's probably ok since this is only going to be used in one place mostly likely but it's still a better practice I think

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 4]
```diff
@@ -205,13 +213,38 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+				document.execCommand('insertHTML', false, `<a href="${calloutResult?.insertLinkUrl}">${calloutResult?.insertLinkLabel}</a>`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:235]: Are these commands documented anywhere? And what makes it so that the text is going to be inserted in the correct position - does the output element remember the cursor position it was at?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 2 above)
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:273]: `createLinkCallout`? Although I'm a little confused since it seems like it's supposed to handle images too but doesn't do anything about them

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 1 above)
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:298]: Do you really have to re-do this lookup every time? I would think that when the toolbar is created it should know what editor it's on so no need to find it again every time you need to get the selected text

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 5]
```diff
@@ -61,7 +61,7 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 
 	@HostListener('document:keydown', ['$event'])
 	onkeydown(e: KeyboardEvent) {
-		if (this.isActive() && this.cellModel?.currentMode === CellEditModes.WYSIWYG) {
+		if (document.activeElement.className === this.output?.nativeElement?.className && this.isActive() && this.cellModel?.currentMode === CellEditModes.WYSIWYG) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:64]: Why are you changing this logic?

File: src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts [hunk 6]
```diff
@@ -179,14 +161,32 @@ export class MarkdownTextTransformer {
...
-			if (editorModel) {
-				let markdownLineType = getMarkdownLineType(type);
-				// Paragraph (empty string) is just used for replacing any existing headers so will never be an undo operation
-				isUndo = beginInsertedText && this.isUndoOperation(selection, type, markdownLineType, editorModel);
-				if (isUndo) {
-					this.handleUndoOperation(markdownLineType, startRange, endRange, editorModel, beginInsertedText, endInsertedText, selections, selection);
-				} else {
-					this.handleTransformOperation(markdownLineType, type, startRange, endRange, editorModel, beginInsertedText, endInsertedText, selections, selection);
+
+			// If markdown has been previously transformed (e.g. through a callout), insert it "as is"
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts:165]: I'm a little confused why you're using something called `MarkdownTextTransformer` if you're not even transforming the text. All you're doing is just inserting the text right? Seems like that could just be done in a separate standalone function or something - no reason to overload the meaning of this class.

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:273]: Or are you going to be coming back to this later to add the image functionality?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 7]
```diff
@@ -231,4 +264,49 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+		const triggerPosX = triggerElement.getBoundingClientRect().left;
+		const triggerPosY = triggerElement.getBoundingClientRect().top;
+		const triggerHeight = triggerElement.offsetHeight;
+		const triggerWidth = triggerElement.offsetWidth;
+		const dialogProperties = { xPos: triggerPosX, yPos: triggerPosY, width: triggerWidth, height: triggerHeight };
+		let calloutOptions;
+		/**
+		 * Width value here reflects designs for Notebook callouts.
+		 */
+		const width: DialogWidth = 452;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:283]: This should be defined in a more common location - and given a name like

`const CALLOUT_WIDTH: DialogWidth = 452;`

**Review by Charles-Gagnon — COMMENTED** [review]
Some callout tests would be a good idea

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 7 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:283]: Sure. I just moved this class to a new location, but happy to move it into `calloutDialog.ts`

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts (hunk 5 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:64]: When the text cell isn't active (e.g. in callout, or even in a dialog -- connection dialog tabbing is broken if you open it while editing a text cell in WYSIWYG mode), keyboard events are still getting handled here. Is there a better way to handle the "only handle keyboard events when editing markdown in WYSIWYG mode"?

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 2 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:273]: I'm coming back later to add image functionality

File: src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts [hunk 8]
```diff
@@ -186,7 +186,7 @@ export class ImageCalloutDialog extends CalloutDialog<IImageCalloutDialogOptions
 	public insert(): void {
 		this.hide();
 		this._selectionComplete.resolve({
-			insertMarkup: `<img src="${strings.escape(this._imageUrlInputBox.value)}">`,
+			insertMarkdown: `<img src="${strings.escape(this._imageUrlInputBox.value)}">`,
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts:189]: It's really suspposed to have markdown, so it will look like ``. I just haven't changed the imageCallout dialog yet. Just went ahead and changed Markup->Markdown in the notebook codebase

File: src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts [hunk 9]
```diff
@@ -121,18 +129,41 @@ export class LinkCalloutDialog extends CalloutDialog<ILinkCalloutDialogOptions>
 		this._register(styler.attachInputBoxStyler(this._linkUrlInputBox, this._themeService));
 	}
 
+	protected onAccept(e?: StandardKeyboardEvent) {
+		e.stopPropagation();
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts:133]: Love it, thanks!

File: src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts [hunk 10]
```diff
@@ -121,18 +129,41 @@ export class LinkCalloutDialog extends CalloutDialog<ILinkCalloutDialogOptions>
...
+	}
+
+	protected onClose(e?: StandardKeyboardEvent) {
+		e.stopPropagation();
+		e.preventDefault();
+		this.cancel();
+	}
 	public insert(): void {
 		this.hide();
+		let label = strings.escape(this._linkTextInputBox.value);
```
[the remark this answers is not in the document]
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts:146]: I don't understand this comment. Can you explain?

[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts:146]: If you have a label such as `My_]_label` then this will break the markdown (it'll be something like `[My_]_label](...)`. Similarly with ) in the URL portion.

Right now strings.escape is just escaping a few specific characters - not those ones

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 4 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:235]: https://www.w3schools.com/jsref/met_document_execcommand.asp

File: src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts (hunk 6 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts:165]: > Tested linking and looks good! Theres still that issue of ESC key closing the dialog and exiting edit mode though.

Yeah that'll be tackled separately in a different PR.

**Comment by chlafreniere** [comment]
> Tested linking and looks good! Theres still that issue of ESC key closing the dialog and exiting edit mode though.

@lucyzhang929 Yeah that'll be tackled separately in a different PR. Tracked by #14434

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 4 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts]: Why did we choose to use these functions instead of functions on the VS wrappers over this stuff? Was there some functionality that you couldn't get through VS Editors alone or something?

For example for this - we add text to editors all the time. Why are we calling this special command to do that for us here?

Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts]: Output components aren't editors, and aren't webviews. They're just div's.

Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts]: We can talk about whether that's the right long term design but notebook outputs were previously webviews, which caused some pretty extreme bad perf. In vscode, they have a solution where only webview is created for a notebook, and it's shared between outputs (but has some builtin isolation)

**Review by VasuBhog — APPROVED** [review]
Looks good! Will do further testing with it as well for URI Parameterization scenarios.

File: src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts (hunk 6 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts]: Thanks. The logic is now in its own standalone function.

File: src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts [hunk 11]
```diff
@@ -186,7 +186,7 @@ export class ImageCalloutDialog extends CalloutDialog<IImageCalloutDialogOptions
 	public insert(): void {
 		this.hide();
 		this._selectionComplete.resolve({
-			insertMarkup: `<img src="${strings.escape(this._imageUrlInputBox.value)}">`,
+			insertMarkdown: `![](${strings.escape(this._imageUrlInputBox.value)})`,
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/calloutDialog/imageCalloutDialog.ts:189]: This should also be using escapeUrl right?

File: src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts [hunk 12]
```diff
@@ -121,18 +132,67 @@ export class LinkCalloutDialog extends CalloutDialog<ILinkCalloutDialogOptions>
...
 	public cancel(): void {
 		super.cancel();
 		this._selectionComplete.resolve({
-			insertMarkup: ''
+			insertMarkdown: '',
+			insertEscapedLinkLabel: escapeLabel(this._linkTextInputBox.value)
 		});
 	}
+
+	public setUrl(val: string): void {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/calloutDialog/linkCalloutDialog.ts:173]: Could just make this a property setter too `public set url(val: string)`

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 13]
```diff
@@ -203,15 +213,41 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
 		}
+		this._notebookEditor = this._notebookService.findNotebookEditor(this.cellModel?.notebookModel?.notebookUri);
 	}
 
-	public onInsertButtonClick(event: MouseEvent, type: MarkdownButtonType): void {
-		let go = new MarkdownTextTransformer(this._notebookService, this.cellModel, this._instantiationService);
-		let trigger = event.target as HTMLElement;
-		go.transformText(type, trigger);
+	public async onInsertButtonClick(event: MouseEvent, type: MarkdownButtonType): Promise<void> {
+		event.preventDefault();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:220]: Could use EventHelper here too

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts [hunk 14]
```diff
@@ -203,15 +213,41 @@ export class MarkdownToolbarComponent extends AngularDisposable {
...
+				return;
+			}
+			// If cell edit mode isn't WYSIWYG, use result from callout. No need for further transformation.
+			if (this.cellModel.currentMode !== CellEditModes.WYSIWYG) {
+				needsTransform = false;
+			} else {
+				// Otherwise, re-focus on the output element, and insert the link directly.
+				this.output?.nativeElement?.focus();
+				// Callout is responsible for returning escaped strings
+				document.execCommand('insertHTML', false, `<a href="${calloutResult?.insertEscapedLinkUrl}">${calloutResult?.insertEscapedLinkLabel}</a>`);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts:238]: Now you're using the markdown-escaped URl and label here which probably isn't correct for inserting into an anchor tag.

This is the kind of thing I was referring to when I suggested letting the callers handle the escaping.

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts (hunk 5 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:64]: I guess my question is more of "why do you need to check the class names as well"? Isn't checking whether it's active and is in WYSIWYG mode enough?

File: src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts [hunk 15]
```diff
@@ -616,6 +564,36 @@ function getColumnOffsetForSelection(type: MarkdownButtonType, nothingSelected:
 	}
 }
 
+/**
+ * When markdown is already formatted correctly and doesn't need transformed, insert markdown based on current editor selection
+ * @param markdownToInsert formatted markdown
+ * @param editorControl editor control for cell
+ */
+export async function insertFormattedMarkdown(markdownToInsert: string, editorControl: IEditor): Promise<void> {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts:572]: Should be `editorControl` since you handle empty editor controls (is that actually a valid scenario though?)

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts (hunk 5 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:64]: `this.active()` only checks that a current cell is active:

https://github.com/microsoft/azuredatastudio/blob/c375e8d17a23428705d1427cf04206fe7a9289bb/src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts#L345

It has nothing to do with what the actual active element on the DOM is. A cell can be active but a dialog/callout can be opened as well. Is there a better way to check that the active element is actually the text cell component?

File: src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts (hunk 15 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts:572]: I don't understand this comment. Are you missing a `?`? 

And no, that's not a valid scenario; to insert markdown, we need a valid editor control.

File: src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts (hunk 14 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/markdownToolbar.component.ts]: Thanks. I thought about this a bit more. I would like the markdown to be used as-is, so I think that it makes sense to return escaped markdown. For the other strings, can return unescaped and leave up to callers to handle as they wish. I've changed the variable names to reflect this.

File: src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts (hunk 15 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts:572]: Oops, yeah that's supposed to be `editorControl?`

Seems like you could get rid of the if check then? (oh how I wish we had strict typing in all the core...)

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts (hunk 5 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:71]: Why aren't you checking the actual element in that case? It just seems a little odd to check the className since those tend not to be necessarily unique.

(I'd suggest using getActiveElement from DOM.ts as well since that handles the shadow root stuff as well (probably not necessary in this scenario but hey you never know what we'll change in the future)

File: src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts (hunk 15 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/markdownToolbarActions.ts:572]: Ok actually looked at the code - it seems like you do actually expect to occasionally get an undefined editor. So in that case you should make the parameter `editorControl?`

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts (hunk 5 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:71]: Sounds good thanks 😄

**Review by alanrenmsft — APPROVED** [review]
