### PR TITLE
Fix parentheses for firewall ip address

### LINKED ISSUE #12230: Create Firewall Rule IP address is missing closing ')'
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. The IP address in the Create Firewall Rule dialog is missing a closing a ')'

image

### PR DESCRIPTION
**Pull request by cssuh**
Fixed the end parentheses for adding a firewall rule. 
Screen Shot 2021-01-04 at 2 04 39 PM

This PR fixes #12230

### CODE REVIEW

**Review by abist — APPROVED** [review]

File: src/sql/workbench/services/resourceProvider/browser/firewallRuleDialog.ts [hunk 1]
```diff
@@ -304,7 +304,7 @@ export class FirewallRuleDialog extends Modal {
 		this.onAccountSelectionChange(this._accountPickerService.selectedAccount);
 		this._fromRangeinputBox!.setPlaceHolder(this.viewModel!.defaultFromSubnetIPRange ?? '');
 		this._toRangeinputBox!.setPlaceHolder(this.viewModel!.defaultToSubnetIPRange ?? '');
-		this._IPAddressElement!.innerText = '(' + this.viewModel.defaultIPAddress ?? '' + ')';
+		this._IPAddressElement!.innerText = '(' + (this.viewModel.defaultIPAddress ?? '') + ')';
```
Comment (alanrenmsft) [inline src/sql/workbench/services/resourceProvider/browser/firewallRuleDialog.ts:307]: interesting, this is very hard to spot during code review. I'd recommend to use template string here.

**Review by alanrenmsft — APPROVED** [review]
