### PR TITLE
set mode explicitly to notebook

### LINKED ISSUE #18088: New notebook prompted to save as json file while saving
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a new notebook and edit
2. Close the notebook and choose 'Save' option from the prompt. Notebook's suggested to save as json file instead of ipynb.

image

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #18088 

VSCode added autodetectLanguage step whenever file content changes. And unless the file mode (language) is explicitly set, it tries to pick a language for the file.

Added setMode in notebookInput to explicitly set the language.

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts [hunk 1]
```diff
@@ -248,6 +248,9 @@ export abstract class NotebookInput extends EditorInput implements INotebookInpu
 		this._providersLoaded = this.assignProviders();
 		this._notebookEditorOpenedTimestamp = Date.now();
 		if (this._textInput) {
+			if (this._textInput instanceof UntitledTextEditorInput) {
+				this._textInput.setMode('notebook');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts:252]: Is there any reason why we wouldn't just always set the mode to Notebook? It's probably unnecessary for non-untitled files but it shouldn't harm anything and will make this more robust.

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts:252]: I agree and I was trying to do that but setMode is not implemented by one of the editor inputs - TextResourceEditorModel. So I was not able to do it directly.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts:252]: Ah, then you should just put this in https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts:252]: You're sure this works for you? I wanted to test if this fixed something else but : 

1. In the constructor the mode is already set to 'notebook' for the text input
2. Regardless of that, even with the code to set the mode I'm not seeing any difference. The save dialog still prompts to save as JSON

image

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/models/notebookInput.ts:252]: @Charles-Gagnon It's the same in the release version as well, so I guess we always save as type JSON but in the name the extension is ipynb.

File: src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts [hunk 2]
```diff
@@ -26,6 +26,7 @@ export class UntitledNotebookInput extends NotebookInput {
 		@IExtensionService extensionService: IExtensionService
 	) {
 		super(title, resource, textInput, true, textModelService, instantiationService, notebookService, extensionService);
+		this.setMode('notebook');
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts:29]: Ok, tested fix and seems good (the issue I was still seeing is what you mentioned has been around for a while where the save dialog file lists the JSON file types).

Just one small change though - do this instead : 

```
// Set the mode explicitly so that the auto language detection doesn't run and mark the model as being JSON
this.textInput.resolve().then(() => this.setMode('notebook'));
```

I noticed while debugging into this that setting the mode immediately like this meant it wasn't actually setting the mode on the underlying model due to this check here : https://github.com/microsoft/azuredatastudio/blob/2bc6a0cd012de69504061a876070cfa43533fedc/src/vs/workbench/common/editor/textEditorModel.ts#L91

Now this didn't really affect your fix because it was still setting the `_hasModeSetExplicitly` property correctly - but I want to avoid potential other issues of having the mode be 'plaintext' (the default).

**Comment by Charles-Gagnon** [comment]
Please also make sure we have a test in the signoff plan for this scenario

**Comment by MaddyDev** [comment]
> Please also make sure we have a test in the signoff plan for this scenario

https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_workitems/edit/9622

File: src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts [hunk 3]
```diff
@@ -26,6 +26,8 @@ export class UntitledNotebookInput extends NotebookInput {
 		@IExtensionService extensionService: IExtensionService
 	) {
 		super(title, resource, textInput, true, textModelService, instantiationService, notebookService, extensionService);
+		// Set the mode explicitly so that the auto language detection doesn't run and mark the model as being JSON
+		this.textInput?.resolve().then(() => this.setMode('notebook'));
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts:30]: Don't fix test errors like this - you should fix the test to pass in a dummy (test) input instead.

Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts:30]: why would I fix the test and not the root cause? What if there's a scenario where textInput isn't defined and resolve would fail ?

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/models/untitledNotebookInput.ts:30]: Because it's not a valid scenario - if a Notebook doesn't have a text input then something has gone horribly wrong (every input needs to have a backing model or it doesn't make sense)

**Review by Charles-Gagnon — APPROVED** [review]
