### PR TITLE
Fix menu entry for tasks

### LINKED ISSUE #5243: Tasks Panel view menu shows an error notifcation
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Execute the `View` > `Tasks` menu item

Expected: Tasks view is shown
Actual: Error message is shown

> Note: The Tasks menu item should probably have a keyboard shortcut assigned similar to other View items

image

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes #5243

### CODE REVIEW

File: src/sql/workbench/parts/tasks/browser/tasks.contribution.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ registry.registerWorkbenchAction(
 		ToggleTasksAction.ID,
 		ToggleTasksAction.LABEL,
 		{ primary: KeyMod.CtrlCmd | KeyCode.KEY_T }),
-	'View: Show Task History',
+	'View: Toggle Views',
```
Comment (kburtram) [inline src/sql/workbench/parts/tasks/browser/tasks.contribution.ts]: Should the text be `Toggle Tasks`?
