### PR TITLE
Editable dropdown component improvement

### LINKED ISSUE #12977: A11y_SQL Azure Data Studio_Import Extension - Import ExtensionModify Columns_ScreenReader: There are more than 6 list items present in the drop down of column 2 yet they all are announced as 6 of 7.
“[Check out Accessibility Insights](https://accessibilityinsights.io/)! – Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags**: #A11yMAS;#A11yTCS;#A11ySev2;#BM_SQLAzureDataStudio_Oct2020;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG1.3.1;#Benchmark;#NVDA;#AILimited;#AINotInScope;

**Environment Details:**
Application Name: SQL Azure Data Studio
Version 1.22.1 User Setup
Windows Version: Windows10
Screen reader: NVDA2020.3

**Repro Steps:**

1. Launch Azure Data Studio Insiders application.
2. Tab to server drop down and tab again to button new connection press enter key and add the server details.
3. Tab to the connected server and press enter key, use down key and select any database keep_MDW Right click on/ open the context menu for a database and select Data-tier application wizard from the context menu
4. Add data in specify input file screen and tab to "next" button and press enter.
5. Press enter on next button.
6. Launch screen reader as NVDA and tab to drop down in column 2 and press enter on it , navigate to each item using down key arrow. 

**Actual:**
On navigating to the first item in the list it is announced as 1 of 6 the 6th item is announced as 6 of 7 and the 7th and rest of the items are announced as 6 of 7.

**Issue not observed with JAWS**

**Expected:**
On navigating to the first item the 1st item should be announced as 1 of (total number of items in the list) and thus the rest should follow.

**User Impact:**
The screen reader users will get the incorrect list numbers.

**Attachment:**

[#12977_A11y_SQL Azure Data Studio_Import ExtensionModify Columns_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/5401656/12977_A11y_SQL.Azure.Data.Studio_Import.ExtensionModify.Columns_ScreenReader.zip)

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #12977

1. the editable dropdown component is using  the vscode Tree component, it is a virtual tree but doesn't have proper aria properties to indicate the actual index of the item, as a result, screen readers will only read the items that is visible. since the Tree component is obsolete, I am replacing it with the List component which is accessible and meanwhile fit our needs best. there is no change to the appearance or behavior of the dropdown.

1. did some clean up to remove the toggle action related stuff I removed a couple days ago.

1. slide in a small fix, i noticed when using narrator with connection dialog, it is always reading table xxx, column xxx, when I navigate between the input boxes and dropdowns, the table here is only used for layout purpose, so set its role to presentation.

Connection Dialog

**before**
image

**after**
image

Query Editor

**before**
image

**after**
image

Import Wizard

**before**

image

**after**
image

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Screenshot of new vs old please just to confirm it looks the same (gif of it in action wouldn't hurt either)

**Comment by alanrenmsft** [comment]
added some screenshots to PR description.

File: src/sql/base/parts/editableDropdown/browser/dropdown.ts [hunk 1]
```diff
@@ -70,21 +65,17 @@ const defaults: IDropdownOptions = {
 	strictSelection: true,
 	maxHeight: 300,
 	errorMessage: errorMessage,
-	contextBorder: Color.fromHex('#696969'),
-	actionLabel: nls.localize('dropdownAction.toggle', "Toggle dropdown")
+	contextBorder: Color.fromHex('#696969')
```
Comment (Charles-Gagnon) [inline src/sql/base/parts/editableDropdown/browser/dropdown.ts:68]: It would be great to use the color registry for this instead.

File: src/sql/base/parts/editableDropdown/browser/dropdown.ts [hunk 2]
```diff
@@ -166,53 +157,76 @@ export class Dropdown extends Disposable {
...
+				default:
+					return;
+			}
+			if (handled) {
+				e.preventDefault();
+				e.stopPropagation();
+			}
+		}));
+		this._register(this._selectList.onMouseClick((e) => {
+			if (e.element) {
```
Comment (Charles-Gagnon) [inline src/sql/base/parts/editableDropdown/browser/dropdown.ts:219]: Is this also closing the list too?

File: src/sql/base/parts/editableDropdown/browser/dropdownList.ts [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+export interface ISelectListTemplateData {
+	root: HTMLElement;
+	text: HTMLElement;
+}
+
+export interface IDropDownListItem {
+	text: string;
+}
+
+export class SelectListRenderer implements IListRenderer<IDropDownListItem, ISelectListTemplateData> {
```
Comment (Charles-Gagnon) [inline src/sql/base/parts/editableDropdown/browser/dropdownList.ts:22]: DropdownListRenderer?

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/base/parts/editableDropdown/browser/dropdown.ts [hunk 4]
```diff
@@ -166,53 +157,76 @@ export class Dropdown extends Disposable {
 					e.stopPropagation();
 					break;
 				case KeyCode.DownArrow:
-					if (!this._treeContainer.parentElement) {
+					if (!this._isDropDownVisible) {
 						this._showList();
 					}
-					this._tree.domFocus();
-					this._tree.focusFirst();
+					setTimeout(() => {
```
Comment (aasimkhan30) [inline src/sql/base/parts/editableDropdown/browser/dropdown.ts:163]: Why do we need a setTimeout here?

**Review by aasimkhan30 — APPROVED** [review]

**Review by kisantia — APPROVED** [review]

File: src/sql/base/parts/editableDropdown/browser/dropdown.ts (hunk 2 above)
Comment (alanrenmsft) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:219]: yes, after you select an element, the list should be closed.

File: src/sql/base/parts/editableDropdown/browser/dropdown.ts (hunk 1 above)
Comment (alanrenmsft) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:68]: this is a fallback color, and we don't actually need this, I am removing it.

File: src/sql/base/parts/editableDropdown/browser/dropdown.ts (hunk 4 above)
Comment (alanrenmsft) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:163]: same as the one I showed you previously, to make sure it can successfully set focus to the expected element
