### PR TITLE
Save db project information when saved in scmp file

### LINKED ISSUE #19228: Schema Compare file not reusable for Database Projects
Issue Type: <b>Bug</b>

Schema Compare file (.SCMP) not reusable when Database Projects is either source or target.  When starting from Database Projects (icon on left-bar) > right-click project, choose Manage > click Schema Compare > click Open .scmp file > choose .scmp file from location: the Schema Compare window opens properly, however the .sqlproj file that was previously saved as a reference in the .SCMP file is no longer recognized (the source or target side, whichever the .sqlproj was on, is blank).  When you click the ellipse and try to choose your .sqlproj file, it allows you to choose one, but you then receive `"Schema Compare failed: Object reference not set to an instance of an object."` message.

At this point, the .SCMP file seems to produce the same error even if you to switch a .DACPAC file and then try to compare.  If I close out of the Schema Compare tab, go back to Manage page for the Database Project and try to start the process again, even using an .SCMP file which was save with a db & .DACPAC as it's comparison, results in the same error.

It seems like this error is coming from the database side of the comparison.  Once I change the connection & re-connect to the database, the `"Schema Compare failed: Object reference not set to an instance of an object."` error goes away.  Only after that step can I go back and point the schema compare at the .sqlproj file I was originally working with.

Extension version: 1.13.0
Azure Data Studio version: azuredatastudio-insiders 1.37.0-insider (4e849f0d601f9e5210f3612458d8f1effae9d527, 2022-04-27T05:28:05.548Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (15.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #19228.

After the changes that went in for publishing changes to database projects from remote database, a small functionality was missed where schema compare file when opened didn't understand how to read and use database projects information stored in the scmp file. This PR fixes that scenario.
While working on this, this issue was found: https://github.com/microsoft/azuredatastudio/issues/20332 . For better testing: https://github.com/microsoft/azuredatastudio/issues/20334

### CODE REVIEW

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 1]
```diff
@@ -1135,7 +1149,11 @@ export class SchemaCompareMainWindow {
 				databaseName: '',
 				ownerUri: '',
 				packageFilePath: endpoint.packageFilePath,
-				connectionDetails: undefined
+				connectionDetails: undefined,
+				projectFilePath: '',
+				targetScripts: [],
```
Comment (kisantia) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts:1154]: why are these being added when they aren't getting set since it isn't a sql project endpoint in this case?

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 2]
```diff
@@ -1126,6 +1126,20 @@ export class SchemaCompareMainWindow {
...
+				packageFilePath: '',
+				serverDisplayName: '',
+				serverName: '',
+				databaseName: '',
+				ownerUri: '',
+				connectionDetails: undefined,
+				projectFilePath: endpoint.projectFilePath,
+				targetScripts: [],
+				dataSchemaProvider: '',
+				folderStructure: 'Schema/Object Type'			// TODO: Pick this automatically from the scmp file, after issue #20332 is resolved (check dsp as well)
```
Comment (kisantia) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts:1141]: use the `schemaObjectType` const

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 3]
```diff
@@ -1126,6 +1126,20 @@ export class SchemaCompareMainWindow {
...
+			endpointInfo = {
+				endpointType: endpoint.endpointType,
+				packageFilePath: '',
+				serverDisplayName: '',
+				serverName: '',
+				databaseName: '',
+				ownerUri: '',
+				connectionDetails: undefined,
+				projectFilePath: endpoint.projectFilePath,
+				targetScripts: [],
```
Comment (kisantia) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts:1139]: do the scripts get added after?

Comment (SakshiS-harma) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts:1139]: Yes, just before the schema compare API is called (https://github.com/microsoft/azuredatastudio/blob/main/extensions/schema-compare/src/schemaCompareMainWindow.ts#L379) .

File: extensions/schema-compare/src/schemaCompareMainWindow.ts (hunk 1 above)
Comment (SakshiS-harma) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts:1154]: This isn't necessary, I will remove it in next iteration.

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 4]
```diff
@@ -1126,6 +1126,20 @@ export class SchemaCompareMainWindow {
...
+				dataSchemaProvider: '',
+				folderStructure: loc.schemaObjectType			// TODO: Pick this automatically from the scmp file, after issue #20332 is resolved (check dsp as well)
```
Comment (kisantia) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts:1141]: not for this PR, but I just noticed that the localized strings of  schemaObjectType and the the other folder structure strings are getting sent to DacFx. This might cause problems for non-English languages. Can you create a follow up task to check this? It would really be better to be sending an enum instead of a string anyway.

**Review by kisantia — APPROVED** [review]
looks good to me! Please make sure the checks (besides the 2 smoke test validation ones since those are flaky) are passing before merging.

File: extensions/schema-compare/src/schemaCompareMainWindow.ts (hunk 4 above)
Comment (SakshiS-harma) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts:1141]: Sure, I will create a task for it.

Comment (SakshiS-harma) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts:1141]: Created this: https://github.com/microsoft/azuredatastudio/issues/20344
