### PR TITLE
Fix modal event propagation

### LINKED ISSUE #5741: [Accessibility]A11y_ Azure Data Studio_CreateExternalTable_Keyboard:Radio button Sql server or Oracle is moving on next page by pressing enter/space Bar
Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.
 GitHubTags: #A11yMAS; #A11yTCS; #MAS3.2.2; #A11y_AzureDataStudio; #Win32; #DesktopApp
**Environment Details:**
Application name: Azure Data Studio (Agent, Create External Data, Notebooks)
Version: 1.8.0-insider (user setup)
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS:Windows_NT x64 10.0.17134
**Additional Details:**
Tool name: keyboard
MAS reference:3.2.2
**Repro Steps:**
1.Install the app Azure Data Studio.
2.Connect to Database-> Enable SQL server2019 preview->click on external table.
3.press tab and select Sql server or Oracle Radio button.
**Actual:**
when we hit enter or space bar on the Sql server or Oracle Radio button we find that next page is open without hitting next button.
**Expected:**
Until and unless we select/click the"Next"button focus should not move on next page.
**User Impact:**
User will get confuse with the unauthorize behaviour of the radio button.
**Recommendation:**
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx
**MAS Reference:3.2.2**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={24cbfff7-374e-42e6-b9ab-d87fcd53b3e8}
**Attachment for Reference:**
[5741_AccessibilityA11y_ Azure Data Studio_CreateExternalTable_Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3235940/5741_AccessibilityA11y_.Azure.Data.Studio_CreateExternalTable_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #5968: [Accessibility]A11y_AzureDataStudio_CSVModifyColumn_Keyboard: As soon as we select any list item from “Data Type” expanded list through keyboard it navigates to the next page “Summary.”
[Check out Keros!](https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags: #A11yMAS; #A11yTCS; #MAS3.3.2; #A11y_AzureDataStudio; #MacOs; #DesktopApp

**Environment Details:**
Application name: Azure Data Studio 
Version: 1.8.0-insider (user setup)
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: : MacOS Mojave 10.14.5

**Additional Details:**
Tool name: Voice Over
MAS reference: MAS3.2.2

**Repro Steps:**
1.Install the app Azure Data Studio.
2.Connect to database->navigate to the Data services folder->HDFS Folder-> navigate to CSV files folder->Right click on the files->Select option Create external table from CSV->Click on the "Next" button->Click on next button.
3.Navigate to the table.
4.Select any list item from “Data Type” expand list and press enter key.
5.Observed that next page is open without hitting next button.

**Actual:**
When we hit enter after selecting list item from “Data Type” expand list we find that next page is open without hitting next button.

**Expected:**
Until and unless we select and click the next button focus should not go on next page.

**User Impact:**
Keyboard user will get confuse with the unauthorize behaviour of the expand list.

**Recommendation:**
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference:**
**MAS3.2.2**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={24cbfff7-374e-42e6-b9ab-d87fcd53b3e8}

**Attachment for Reference:**
[5968_[Accessibility]A11y_AzureDataStudio_CSVModifyColumn _Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3275106/5968_.Accessibility.A11y_AzureDataStudio_CSVModifyColumn._Keyboard.pptx)

Does this issue occur when all extensions are disabled?  : Yes

### LINKED ISSUE #5976: [Accessibility]A11y_AzureDataStudio_CSVSelectDestinationDatbse_Keyboard:After selecting any list item from "Schema for new external table” combo box through keyboard focus navigates to the next screen “Preview Data”.
[Check out Keros! ](https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx)- Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags: #A11yMAS; #A11yTCS; #MAS3.3.2; #MAS2.4.3; #A11y_AzureDataStudio; #MacOs; #DesktopApp

**Environment Details:**
Application name: Azure Data Studio
Version: 1.8.0-insider (user setup)
Commit: 2ca39b5
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS : MacOS Mojave 10.14.5

**Additional Details:**
Tools Name: Keyboard
MAS References: MAS3.2.2,MAS2.4.3

**Steps to Reproduce:**
1.Install the app Azure Data Studio.
2.Connect to database->navigate to the Data services folder->HDFS Folder-> navigate to CSV files folder->Right click on the files->Select option Create external table from CSV files.
3.Navigate till for “Schema for new external table” combo box .
4.Observe that after selecting any list item from "Schema for new external table” combo box through keyboard focus navigates to the next screen “Preview Data”.

**Actual:**
After selecting any list item from the "Schema for new external table” combo box  through keyboard , it navigates to the next screen “Preview Data”.

**Expected:**
After selecting any list item from the "Schema for new external table” combo box  through keyboard , it should navigates to next interactive control of the same screen.

**User Impact:**
Keyboard user will get confuse with the unauthorize behaviour of the expand list.

**Recommendation:**
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference :
MAS3.2.2:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={24cbfff7-374e-42e6-b9ab-d87fcd53b3e8}

**Attachment for Reference:**
[5976_[Accessibility]A11y_AzureDataStudio_CSVSelectDestinationDatbse_Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3275945/5976_.Accessibility.A11y_AzureDataStudio_CSVSelectDestinationDatbse_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #5976
Fixes #5968
Fixes #5741

Fixes some more cases where keyboard events for enter were being propagated up after a control was handling them, causing any parent controls (such as wizard) to get them and possibly have unintended side effects such as moving to the next page.

### CODE REVIEW

File: src/sql/base/parts/editableDropdown/browser/dropdownTree.ts [hunk 1]
```diff
@@ -124,10 +125,24 @@ export class DropdownController extends TreeDefaults.DefaultController {
 		return response;
 	}
 
+	public onKeyDown(tree: tree.ITree, event: IKeyboardEvent): boolean {
+		// The enter key press is handled on key up by our base class (DefaultController) but
+		// we want to stop it here because we know we're going to handle it (by selecting the item)
+		// and letting it propagate up means that other controls may incorrectly handle it first
+		// if they're listening to onKeyDown
+		const response = super.onKeyDown(tree, event);
+		if (event.keyCode === KeyCode.Enter) {
```
Comment (anthonydresser) [inline src/sql/base/parts/editableDropdown/browser/dropdownTree.ts]: Seems like you are stopping twice? do we need this  one if you stop it later.

Comment (Charles-Gagnon) [reply src/sql/base/parts/editableDropdown/browser/dropdownTree.ts]: What do you mean we stop it later? Are you talking about in the onEnter? That one is triggered on key up so is a separate event. The comment explains that I do this here because everywhere else we've been using key down and so if I just do it there then the key down is still handled in those other places (like the dialog) and we want to specifically stop that.

---
In reply to: [339764920](https://github.com/microsoft/azuredatastudio/pull/8050#discussion_r339764920) [](ancestors = 339764920)

File: src/sql/base/browser/ui/selectBox/selectBox.ts [hunk 2]
```diff
@@ -91,6 +94,23 @@ export class SelectBox extends vsSelectBox {
 		this._register(focusTracker);
 		this._register(focusTracker.onDidBlur(() => this._hideMessage()));
 		this._register(focusTracker.onDidFocus(() => this._showMessage()));
+		// Stop propagation - we've handled the event already and letting it bubble up causes issues with parent
+		// controls handling it (such as dialog pages)
+		this.onkeydown(this.selectElement, (e: IKeyboardEvent) => {
```
Comment (udeeshagautam) [inline src/sql/base/browser/ui/selectBox/selectBox.ts]: This should be fine but to be sure, can you please validate once that the dialogs/wizards that are working now don't start behaving weird. These two should be able to cover this,
1. Restore wizard directly using select box 
2. DacFx wizard (ex. extract flow) using it through .component

Please let me know if you need help validating those.

Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: Verified that things seem to be working fine there.
