### PR TITLE
Reload ADS when data-workspace extension opens a workspace

### LINKED ISSUE #14537: Projects open/create workspace causes many things to not work anymore
When a workspace is created or opened by the data workspace extension, the extension host restarts. However, this causes problems since there is state maintained in the core that relies on ext host that gets lost when the ext host gets restarted. 

Examples of things that don't work anymore:
- can't connect
- trying to refresh a connection gives the error "TypeError: Cannot read property 'toLowerCase' of undefined"
- azdata.connection.listDatabases() doesn't work

The fix for this will be to restart the app when opening or creating a workspace

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #14537. Before, only the extension host was restarting when a workspace was opened/created for projects. While the projects were working, many things were broken after the extension host restarted, like connecting. This is because there is state maintained in the core that relies on ext host that gets lost when the ext host gets restarted. The fix is to restart the app when a workspace is entered. 

example of workspace reloading when another workspace is opened through the open existing dialog and connection working:
https://user-images.githubusercontent.com/31145923/109890246-d3027380-7c3b-11eb-9fa2-cd4491824501.mp4

### CODE REVIEW

**Comment by udeeshagautam** [comment]
+ @dzsquared FYI

File: src/sql/workbench/api/browser/mainThreadWorkspace.ts [hunk 1]
```diff
@@ -18,24 +19,27 @@ export class MainThreadWorkspace extends Disposable implements MainThreadWorkspa
...
 		super();
 	}
 
-	$createAndEnterWorkspace(folder: URI, workspaceFile?: URI): Promise<void> {
+	async $createAndEnterWorkspace(folder: URI, workspaceFile?: URI): Promise<void> {
 		folder = URI.revive(folder);
 		workspaceFile = URI.revive(workspaceFile);
-		return this.workspaceEditingService.createAndEnterWorkspace([{ uri: folder }], workspaceFile);
+		await this.workspaceEditingService.createAndEnterWorkspace([{ uri: folder }], workspaceFile);
+		this.hostService.reload();
```
Comment (udeeshagautam) [inline src/sql/workbench/api/browser/mainThreadWorkspace.ts:31]: does it affect any tests

Comment (kisantia) [reply src/sql/workbench/api/browser/mainThreadWorkspace.ts:31]: it doesn't affect any of the data workspace or sql database projects tests since these are stubbed

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
In my testing it looks like this is broken even for users that open/save a workspace through other ways like the File commands. So I don't think this is the correct fix - we should probably be doing the reload in the functions themselves. 

Although it's not great in general that we just break when the extension host is restarted. Did you find out what "state" is lost that breaks us?

**Review by alanrenmsft — APPROVED** [review]

**Comment by kisantia** [comment]
@Charles-Gagnon which file commands also do this? File->Open workspace reloads ADS.

@alanrenmsft can you share what state maintained in core relies on the extension host since you have more context?

**Comment by Charles-Gagnon** [comment]
I guess open workspace does but saving a new workspace doesn't - that just restarts the extension host

**Review by Charles-Gagnon — APPROVED** [review]
