### PR TITLE
Fix/save defaults to txt

### LINKED ISSUE #11564: Saving Text Editors defaults to txt
Insiders/main

image

### PR DESCRIPTION
**Pull request by MaddyDev**
Fix: getExtensions method expects language name but the textFileService is passing the mode. Get language by calling  getLanguageName with.mode and then pass it in for getExtensions.

This PR addresses #11564

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Please submit this to VS Code and link this issue : https://github.com/microsoft/vscode/issues/103704

**Comment by MaddyDev** [comment]
> Please submit this to VS Code and link this issue : [microsoft/vscode#103704](https://github.com/microsoft/vscode/issues/103704)

https://github.com/microsoft/vscode/pull/103882

File: src/vs/workbench/services/textfile/browser/textFileService.ts [hunk 1]
```diff
@@ -462,7 +462,9 @@ export abstract class AbstractTextFileService extends Disposable implements ITex
 	}
 
 	suggestFilename(mode: string, untitledName: string) {
-		const extension = this.modeService.getExtensions(mode)[0];
+		// {{SQL Carbon Edit}} - pass language not mode for getting the extension.
```
Comment (kburtram) [inline src/vs/workbench/services/textfile/browser/textFileService.ts:465]: could you please update the tag to `// {{SQL CARBON EDIT}}` so Find in Files will work correctly with case-sensitive matching?

File: src/vs/workbench/services/textfile/browser/textFileService.ts [hunk 2]
```diff
@@ -462,7 +462,9 @@ export abstract class AbstractTextFileService extends Disposable implements ITex
...
+		const langName = this.modeService.getLanguageName(mode);
+		const extension = langName ? this.modeService.getExtensions(langName)[0] : undefined;
```
Comment (kburtram) [inline src/vs/workbench/services/textfile/browser/textFileService.ts:467]: do we know that `this.modeService.getExtensions` always returns an array with at least 1 element?  Or should we null check before accessing?

Comment (MaddyDev) [reply src/vs/workbench/services/textfile/browser/textFileService.ts:467]: it can return an empty array but it's the same with the previous call (const extension = this.modeService.getExtensions(mode)[0]) and I am trying to stick to the pattern they followed. If you think it's good to add the null check, I can add it but do I need to update the other statements in this method that have the same issue?
