### PR TITLE
Fix for table name not showing up on the header.

### LINKED ISSUE #9006: Edit Data: On edit data the table name isn't shown anywhere
- Azure Data Studio Version:

Steps to Reproduce:

1. Open any table and right click to launch edit data.

Expected: 
It should open table in edit mode and show the table name on the title-header.
Current behavior:
It opens the table in edit mode but doesn't show the table name info anywhere. It shows the query instead of the table-name now.

### PR DESCRIPTION
**Pull request by smartguest**
An EditData editor created with an untitledResource will not have the name of the table on the top of the head. However, if we use an associatedResource which displays the title, the editor is initialized as dirty by default, and changes to the dirty state will not be detected at all for the editor. To fix this, the dirty state must be manually set to false upon creating the editor, so to detect when the editor has changed.

This PR fixes #9006

### CODE REVIEW

File: src/sql/workbench/services/queryEditor/browser/queryEditorService.ts [hunk 1]
```diff
@@ -87,8 +87,10 @@ export class QueryEditorService implements IQueryEditorService {
 		let docUri: URI = URI.from({ scheme: Schemas.untitled, path: filePath });
 
 		// Create a sql document pane with accoutrements
-		const fileInput = this._untitledEditorService.create({ untitledResource: docUri, mode: 'sql' });
+		const fileInput = this._untitledEditorService.create({ associatedResource: docUri, mode: 'sql' });
```
Comment (MaddyDev) [inline src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: >associatedResource [](start = 57, length = 18)

Is there a reason you changed it to untitledResource from associatedResource? Just wanted to know why you changed it in the first place.

Comment (smartguest) [reply src/sql/workbench/services/queryEditor/browser/queryEditorService.ts]: It was changed to that because it was used to fix the issue of the edit data editor opening up upon reload even when no changes were made. I was told take a similar approach to how it was fixed for notebooks, which used untitledResource to fix the problem, which worked since the dirty state for an untitledResource editor is false. However, I did not realize there was a side effect as you pointed out.

but as you can see, it introduced a side effect even
