### PR TITLE
Notebooks: Potential Fix for "Notebook Provider does not Exist" Error

### LINKED ISSUE #4580: Notebook provider does not exist
Issue Type: <b>Bug</b>

Reopening Azure Data Studio with a couple of notebooks open, I occasionally get this error: Notebook provider does not exist.

It eventually clears the error but the contents of the notebook never reappear. I have to close and then reopen the notebook.

Console:

image

Extension Host
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger attached.

C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388 Could not display contents: Notebook provider does not exist
ZoneDelegate.invoke @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388 ERROR Error: Uncaught (in promise): Error: Notebook provider does not exist
Error: Notebook provider does not exist
    at NotebookService.<anonymous> (workbench.main.js:325092)
    at step (workbench.main.js:6487)
    at Object.next (workbench.main.js:6468)
    at fulfilled (workbench.main.js:6459)
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388)
    at Object.onInvoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4156)
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:387)
    at Zone.run (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Object.onInvokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147)
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:420)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595)
    at NotebookService.<anonymous> (workbench.main.js:325092)
    at step (workbench.main.js:6487)
    at Object.next (workbench.main.js:6468)
    at fulfilled (workbench.main.js:6459)
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388)
    at Object.onInvoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4156)
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:387)
    at Zone.run (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Object.onInvokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147)
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:420)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595)
    at resolvePromise (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:814)
    at resolvePromise (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:771)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:873
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Object.onInvokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147)
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:420)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595)
ZoneDelegate.invoke @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388
workbench.main.js:223646 Extension Host
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger listening on ws://127.0.0.1:29524/b311a990-e4ec-4b2b-b83c-163e97ca7293
For help, see: https://nodejs.org/en/docs/inspector

C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280  WARN UNRESPONSIVE extension host, 'Microsoft.notebook' took 51% of 5493.361ms, saved PROFILE here: 'C:\Users\viharp\AppData\Local\Temp\exthost-7bbcbc.cpuprofile' Array(4)
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for MicrosoftSqlToolsServiceLayer.exe is C:\Users\viharp\AppData\Roaming\azuredatastudio\mssql\sqltools_2108.log (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:90:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 2108 (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:91:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {} (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:94:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for SqlToolsResourceProviderService.exe is C:\Users\viharp\AppData\Roaming\azuredatastudio\mssql\resourceprovider_2108.log (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:90:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 2108 (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:91:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {} (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:94:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for MicrosoftSqlToolsCredentials.exe is C:\Users\viharp\AppData\Roaming\azuredatastudio\mssql\credentialstore_2108.log (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:90:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 2108 (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:91:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {} (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:94:13))

Azure Data Studio version: azuredatastudio 1.5.1-insider (25b1d4b6731a00e9dfdfcad0a91749f78d48e7e8, 2019-03-18T07:42:56.190Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|15.84GB (4.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
azuredatastudio-postgresql|Mic|0.1.0
PowerShell|ms-|1.11.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

### PR DESCRIPTION
**Pull request by chlafreniere**
I believe this fixes #4580, but I would like more testing if at all possible. I kicked off a Windows build here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=29974.

This issue was hard to repro for me, but I could repro it once (and only once) consistently by using the .zip install... The first time that I launched ADS from a particular folder, it sometimes took > 20 seconds until the service was started and other extensions were activated. I suspect that this was due to a change in VS Code, but maybe @anthonydresser can help us with any details. On subsequent launches, the service and other extensions were activated much more quickly, so this issue went away. So, if I needed to repro this a second time, I just copied ADS to another folder, and voila... After this change, I didn't see this particular error message occur any longer, but that doesn't mean that we're 100% home-free here.

Two issues here:
- 10 seconds to wait is not long enough to wait on notebook providers being available; from my testing, on first launch, it can take up to 23 seconds on my machine until extensions are activated
- In our super failback "this should never be hit"-type code, we were falling back to a provider that no longer exists. Better to at least fallback to SQL (something that at least has a chance to exist) instead of something that has 0 chance of existing.

As for testing, we need an integration test that tests notebook editor rehydration (which would catch issues like this one). I took a look at this and couldn't figure out how to close and reopen ADS from within a test, so I need to work with @alanrenmsft on how we can accomplish this.

### CODE REVIEW

**Comment by anthonydresser** [comment]
Do you know which line is causing the error to throw? This should really be done asynchronously waiting on a provider similarly to how we do connections.

File: src/sql/workbench/services/notebook/common/notebookServiceImpl.ts [hunk 1]
```diff
@@ -424,8 +424,8 @@ export class NotebookService extends Disposable implements INotebookService {
 	}
 
 	private waitOnProviderAvailability(providerDescriptor: ProviderDescriptor, timeout?: number): Promise<INotebookProvider> {
-		// Wait up to 10 seconds for the provider to be registered
-		timeout = timeout || 10000;
+		// Wait up to 30 seconds for the provider to be registered
+		timeout = timeout || 30000;
```
Comment (corivera) [inline src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: Should we use a timeout this high? Seems like a long time to wait for a failure, especially since all this stuff happens locally.

Comment (corivera) [reply src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: Disregard this, saw the description write-up.

**Comment by corivera** [comment]
In general, should we just remove all reference to DEFAULT_NOTEBOOK_PROVIDER?

File: src/sql/workbench/services/notebook/common/notebookServiceImpl.ts (hunk 1 above)
Comment (kevcunnane) [inline src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: Let's modify this slightly (or we could put this in the `getProviderInstance`):
- First await `extensionService.whenInstalledExtensionsRegistered`. You'll need to make this a private field instead of it only existing in the constructor. This ensures we wait at least until the extension host is loaded (which could be a long time).
- Then your new timeout still seems reasonable just in case (e.g. if someone is debugging extension startup, or in the future case where we do "no restart needed" extension installs and it then has to take a few seconds to register things

File: src/sql/workbench/services/notebook/common/notebookServiceImpl.ts [hunk 2]
```diff
@@ -401,6 +401,13 @@ export class NotebookService extends Disposable implements INotebookService {
 		let providerDescriptor = this._providers.get(providerId);
 		let instance: INotebookProvider;
 
+		// Await extension registration before awaiting provider registration
+		try {
+			await this._extensionService.whenInstalledExtensionsRegistered;
+		} catch (error) {
+			throw typeof(error) === 'string' ? new Error(error) : error;
```
Comment (kevcunnane) [inline src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: Question: do we care? Why re-throw here when it's handled in a different place, and in particular how would an upstream caller understand what an error in this path means?

Instead, should we cleanly exit here or just try to get the provider and fail with standard error if that occurs? While this isn't likely to come up, I think we should just assume that if this fails we go on with our process and see if we can succeed anyhow.

File: src/sql/workbench/services/notebook/common/notebookServiceImpl.ts [hunk 3]
```diff
@@ -401,6 +401,13 @@ export class NotebookService extends Disposable implements INotebookService {
 		let providerDescriptor = this._providers.get(providerId);
 		let instance: INotebookProvider;
 
+		// Await extension registration before awaiting provider registration
+		try {
+			await this._extensionService.whenInstalledExtensionsRegistered;
```
Comment (kevcunnane) [inline src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: So... putting this here likely means SQL notebooks will be help up unnecessarily. I would suggest moving this inside the 
```
			if (!providerDescriptor.instance) {
```
block or inside the waitOnProviderAvailability method. Either one means we only await if the required object doesn't exist. For internal providers this speeds things up, for anything else it shouldn't cause any harm.
