### PR TITLE
Fix missing password in Connection pane for Server connections with remembered passwords

### LINKED ISSUE #21812: Previously connected Azure SQL Server connections with saved passwords have blank password field.
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:
1. In Object Explorer, expand the Azure section
2. Locate a previously connected instance of SQL Server where the "Remember password" checkbox was checked.
3. Click on the connection button (plug icon)
4. Change the authentication type to SQL Login
5. The password that was entered previously and supposed to be remembered doesn't appear in the "Password" field, but the user name appears. 
image

6. In the "Connection" blade, click on the "Cancel" button
7. Under "Servers" in the Object Explorer, right click on the server with the saved password and click on "Edit Connection".
8. The password that was entered previously and remembered appears in the "Password" field along with the user name. 
image

EXPECTATION:
The password field should be filled in along with the "User name" since the option to "Remember password" was selected.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #21812

This PR fixes a bug around remembered passwords for connections not appearing in the connection blade. Clicking on the "Connect" button for a server that has previously been connected to and set to have the password remembered will now appear in the connection pane.

1. Click on the "Connect" button (plug icon) on a server node that has previously been connected to.
image

   1.1. Switch the authentication type to SQL Login (May not need to do this if default auth type is SQL Login).

2. The user name and password for the connection will be filled in.
image

### CODE REVIEW

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 1]
```diff
@@ -598,6 +598,16 @@ export class ConnectionWidget extends lifecycle.Disposable {
 			this._userNameInputBox.enable();
 			this._passwordInputBox.enable();
 			this._rememberPasswordCheckBox.enabled = true;
+
+			const recentConnections = this._connectionManagementService.getRecentConnections();
+			if (recentConnections && recentConnections.length > 0) {
+				const self = this;
+				const connectionProfile = recentConnections.find(c => c.serverName === self._serverNameInputBox.value && c.userName === self._userNameInputBox.value);
```
Comment (kburtram) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:605]: I don't think this is the correct way to check identity of a connection?

**Review by kburtram — COMMENTED** [review]
I'm not sure this is the correct place to load this password.  Are we able to actually remember the password somewhere if the user checks "Remember Password" (such as in the connection profiles in Settings) and then load it from their when showing the connection dialog?

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 2]
```diff
@@ -598,6 +598,16 @@ export class ConnectionWidget extends lifecycle.Disposable {
 			this._userNameInputBox.enable();
 			this._passwordInputBox.enable();
 			this._rememberPasswordCheckBox.enabled = true;
+
+			const recentConnections = this._connectionManagementService.getRecentConnections();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:602]: Is recent connections the right one to use here? Recent connections are temporary and can be cleared at any time, shouldn't we be using saved connections instead? I suppose using both is an option too in case they didn't save the connection when previously connected...

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 3]
```diff
@@ -598,6 +598,16 @@ export class ConnectionWidget extends lifecycle.Disposable {
...
+			if (recentConnections && recentConnections.length > 0) {
+				const self = this;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:604]: nit: You shouldn't need this - as long as you use a lambda capture below it'll capture the this context correctly.

File: src/sql/workbench/services/connection/browser/connectionWidget.ts (hunk 2 above)
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:602]: Is this actually where we want the logic to be? It'll affect everything opening the connection dialog - which may be problematic for example if it was opened with a different password pre-populated for some reason which would then be overwritten by this. 

Could you just move this logic to where the azure pane is making the connection to instead do the lookup and population of the password field there which is then passed into here?

File: src/sql/workbench/services/connection/browser/connectionWidget.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:605]: getConnectionInfoId is likely what you should be using here, although I believe that has the group name as well which probably isn't what you want.

**Comment by cheenamalhotra** [comment]
Hi Lewis,

Regarding the issue, there are 2 things to note:
1. When user is changing the auth type and selecting 'SqlLogin' - we don't expect saved password to load, that also applies to Server tree connections.
2. If you want to pre-populate password for Azure Tree connections, you need to first set your default authentication mode to 'SqlLogin' with this setting: 


However, setting this mode does not load password, and to fix that, we can pre-populate password either on path of ADS Connection core API `MainThreadConnectionManagement.$openConnectionDialog` or from the AzureCore extension where this call is triggered.

It does come with a complexity since Azure Core extension sets blank 'authenticationMode', so we need to consider the default auth mode setting in that case and accordingly load saved password.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts [hunk 4]
```diff
@@ -364,11 +365,11 @@ export class ConnectionDialogService implements IConnectionDialogService {
 	}
 
 	private handleFillInConnectionInputs(connectionInfo: IConnectionProfile): void {
-		this._connectionManagementService.addSavedPassword(connectionInfo).then(connectionWithPassword => {
+		this._connectionManagementService.addSavedPassword(connectionInfo).then(async connectionWithPassword => {
```
Comment (cheenamalhotra) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:368]: Nit: This call to addSavedPassword can be avoided since createModel will take care of it. But even if this exists, it should be skipped second time as password will be populated.. so functionally we're fine. 

For readability, I'd suggest cleaning it up to handle password addition only in 1 place.

**Review by cheenamalhotra — APPROVED** [review]
Other than a small feedback, looks good to me!

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts [hunk 5]
```diff
@@ -412,6 +412,14 @@ export class ConnectionDialogService implements IConnectionDialogService {
 		}
 
 		let newProfile = new ConnectionProfile(this._capabilitiesService, model || providerName);
+		if (!model.password && defaultAuthenticationType === AuthenticationType.SqlLogin && authenticationTypeName === AuthenticationType.SqlLogin) {
+			try {
+				await this._connectionManagementService.addSavedPassword(newProfile);
+			}
+			catch (err) {
+				onUnexpectedError(err);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:420]: Would be good to create another error wrapping this to clearly indicate what failed (something like `Error filling in password for connection dialog model`)

File: src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts [hunk 6]
```diff
@@ -307,11 +307,17 @@ suite('ConnectionDialogService tests', () => {
...
 			called = true;
 		});
+
 		await connectionDialogService.showDialog(mockConnectionManagementService.object, testConnectionParams, connectionProfile);
 		await (connectionDialogService as any).handleFillInConnectionInputs(connectionProfile);
-		let returnedModel = ((connectionDialogService as any)._connectionControllerMap['MSSQL'] as any)._model;
-		assert.strictEqual(returnedModel._groupName, 'testGroup');
-		assert(called);
+
+		setTimeout(() => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts:314]: You aren't waiting for this callback to be called so it will finish the test before any of the code inside is ran. You should use the `done` callback to tell the test to wait until that happens so you're sure that happens.

But also is there a reason you couldn't have handleFillInConnectionInputs return a promise? Doing waits like this generally leads to unstable tests since there's nothing guaranteeing that it will complete before the 200ms is up.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts [hunk 7]
```diff
@@ -363,15 +364,20 @@ export class ConnectionDialogService implements IConnectionDialogService {
...
 				this._model.dispose();
 			}
-			this._model = this.createModel(connectionWithPassword);
-
+			this._model = connectionWithPassword;
 			this.uiController.fillInConnectionInputs(this._model);
-		}).catch(err => onUnexpectedError(err));
+		}
+		catch (err) {
+			onUnexpectedError(err);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:378]: I would also suggest adding additional context to the message for where this happened.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts [hunk 8]
```diff
@@ -412,6 +418,14 @@ export class ConnectionDialogService implements IConnectionDialogService {
 		}
 
 		let newProfile = new ConnectionProfile(this._capabilitiesService, model || providerName);
+		if (!model.password && defaultAuthenticationType === AuthenticationType.SqlLogin && authenticationTypeName === AuthenticationType.SqlLogin) {
+			try {
+				await this._connectionManagementService.addSavedPassword(newProfile);
+			}
+			catch (err) {
+				onUnexpectedError(new Error('Error filling in password for connection dialog model.'));
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:426]: You should keep the original error in the message as well

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts [hunk 9]
```diff
@@ -412,6 +418,14 @@ export class ConnectionDialogService implements IConnectionDialogService {
 		}
 
 		let newProfile = new ConnectionProfile(this._capabilitiesService, model || providerName);
+		if (!model.password && defaultAuthenticationType === AuthenticationType.SqlLogin && authenticationTypeName === AuthenticationType.SqlLogin) {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: Is there a reason you're checking the default auth type here? If the auth type passed in was sql then I would think we'd want to fill in the password regardless of what the default type is for that provider.

Comment (lewis-sanchez) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: According to @cheenamalhotra, we only want to fill in the password when the default connection is SQL Login since there isn't an expectation to load the password when the auth type is switched to SQL Login.

She outlined the two things for me to take note of in this comment: https://github.com/microsoft/azuredatastudio/pull/21813#issuecomment-1414266066

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts [hunk 10]
```diff
@@ -363,15 +364,20 @@ export class ConnectionDialogService implements IConnectionDialogService {
...
 				this._model.dispose();
 			}
-			this._model = this.createModel(connectionWithPassword);
-
+			this._model = connectionWithPassword;
 			this.uiController.fillInConnectionInputs(this._model);
-		}).catch(err => onUnexpectedError(err));
+		}
+		catch (err) {
+			onUnexpectedError(new Error(`Error filling in connection inputs with password. Original error message: ${err.message}`));
```
Comment (alanrenmsft) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:378]: does it log the error to console?

**Comment by lewis-sanchez** [comment]
> @lewis-sanchez what was the actual issue that caused the problem?

We weren't retrieving the password from the credential store when the edit connection pane was opened, so the password field would appear blank instead of with the saved password.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts (hunk 10 above)
Comment (lewis-sanchez) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:378]: Yes, it logs the error to the console.

**Comment by alanrenmsft** [comment]
as per our offline chat, user shouldn't have to change the default auth type setting in order to make this work, instead, we should check whether a username password is saved for the target server and populate it automatically. also it should populate the username password when auth type is changed to SQL Auth in the dialog.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts (hunk 10 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:378]: I generally would say we should prefer to use the logger service instead of this function for caught errors.

Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:378]: We aren't guaranteed that this is an Error object, so using the message property is unsafe. Better to just get the string version directly (or use a helper function)

```suggestion
			onUnexpectedError(new Error(`Error filling in connection inputs with password. Original error message: ${err}`));
```

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts (hunk 9 above)
Comment (cheenamalhotra) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: @lewis-sanchez  just above on line 413, default authenticationType is being considered so additional check is not needed.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts [hunk 11]
```diff
@@ -412,6 +418,14 @@ export class ConnectionDialogService implements IConnectionDialogService {
 		}
 
 		let newProfile = new ConnectionProfile(this._capabilitiesService, model || providerName);
+		if (!model.password) {
```
Comment (alanrenmsft) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: this should only be performed for sql login auth type, right?

File: src/sql/workbench/services/connection/browser/connectionWidget.ts [hunk 12]
```diff
@@ -598,6 +599,16 @@ export class ConnectionWidget extends lifecycle.Disposable {
...
 			this._rememberPasswordCheckBox.enabled = true;
+
+			this._initialConnectionInfo.authenticationType = AuthenticationType.SqlLogin;
+			if (this._initialConnectionInfo && this._initialConnectionInfo.userName) {
+				const loadProfileIntoPasswordInputBox = (profile: IConnectionProfile) => {
+					this._passwordInputBox.value = profile.password;
+				};
+
+				this._rememberPasswordCheckBox.checked = this._initialConnectionInfo.savePassword;
+				this._connectionManagementService.addSavedPassword(this._initialConnectionInfo, true).then(loadProfileIntoPasswordInputBox);
```
Comment (alanrenmsft) [inline src/sql/workbench/services/connection/browser/connectionWidget.ts:610]: let's use `await` instead.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts (hunk 11 above)
Comment (lewis-sanchez) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: It isn't able to retrieve anything if the auth type isn't SQL. login.

Comment (lewis-sanchez) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: The authentication type is also being checked on line 413 - 414, so it seemed redundant to check here too.

Comment (alanrenmsft) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: fine by me.

Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: What checks are you talking about? I only see it getting the default value and using that if the model doesn't have one itself. But that doesn't affect this line so it'll try to fill in the password regardless of the auth type.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts [hunk 13]
```diff
@@ -487,7 +501,7 @@ export class ConnectionDialogService implements IConnectionDialogService {
 			});
 			this._connectionDialog.onShowUiComponent((input) => this.handleShowUiComponent(input));
 			this._connectionDialog.onInitDialog(() => this.handleInitDialog());
-			this._connectionDialog.onFillinConnectionInputs((input) => this.handleFillInConnectionInputs(input as IConnectionProfile));
+			this._connectionDialog.onFillinConnectionInputs(async (input) => this.handleFillInConnectionInputs(input as IConnectionProfile));
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionDialogService.ts:504]: nit: This doesn't need to be async if you aren't awaiting anything.

File: src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts [hunk 14]
```diff
@@ -307,9 +307,13 @@ suite('ConnectionDialogService tests', () => {
 		mockWidget.setup(x => x.fillInConnectionInputs(TypeMoq.It.isAny())).returns(() => {
 			called = true;
 		});
+
 		await connectionDialogService.showDialog(mockConnectionManagementService.object, testConnectionParams, connectionProfile);
 		await (connectionDialogService as any).handleFillInConnectionInputs(connectionProfile);
-		let returnedModel = ((connectionDialogService as any)._connectionControllerMap['MSSQL'] as any)._model;
+
+		let connectionControllerMap = (connectionDialogService as any)._connectionControllerMap;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/test/browser/connectionDialogService.test.ts:314]: Would be good to add tests for this functionality.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts (hunk 13 above)
Comment (lewis-sanchez) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:504]: I thought the rule was that you need to declare something as async if it's calling another async function, but awaiting it was optional if you wanted the promise to bubble up the call hierarchy.

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts (hunk 11 above)
Comment (lewis-sanchez) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: The checks in the `addSavedPassword` function. If the auth type is SqlLogin then it will set `isPasswordRequired` to `true`, and go to the credential service to read the password.
image

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts (hunk 13 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:504]: Async does nothing if there isn't an await and it isn't returning anything. And even then you only need async if the return value isn't a promise already itself - in this case for example you could just return the call to handleFillInConnectionInputs directly and it would then properly bubble up the promise to the caller.

So in this case async isn't going to do anything useful - and you also aren't even passing up the promise. (but events don't do anything with rejected promises anyways so that isn't something we generally put much effort into doing anything about - better to do like you do and have the called function handle any errors itself)

File: src/sql/workbench/services/connection/browser/connectionDialogService.ts (hunk 11 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/services/connection/browser/connectionDialogService.ts:421]: Ok good, was confused with the line numbers you gave earlier. That seems fine then.

File: src/sql/workbench/services/connection/browser/connectionWidget.ts (hunk 12 above)
Comment (lewis-sanchez) [reply src/sql/workbench/services/connection/browser/connectionWidget.ts:610]: This seems like it's more trouble than it's worth since the call chain isn't small and not awaiting something correctly could cause issues, IMO.

**Review by alanrenmsft — APPROVED** [review]
