### PR TITLE
Refresh cell toolbar when changing cell type.

### LINKED ISSUE #18461: Cell toolbar not updated when converting text cell to code cell.
[Not a regression]

Cell toolbar not updated when converting text cell to code cell.

Version: 1.34.0
Commit: 83a4316cf89cbf961a0f09a72c861379cfd01fa9
Date: 2021-12-15T20:50:08.229Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 21.3.0

Repro:
1. Create text cell
2. Convert cell 
3. The text cell is converted into a code cell but the cell toolbar is still a Text Cell toolbar. 

Screen Shot 2022-02-17 at 4 25 10 PM

### PR DESCRIPTION
**Pull request by corivera**
This PR fixes #18461

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts [hunk 1]
```diff
@@ -71,14 +82,14 @@ export class CellToolbarComponent {
 		let moveCellUpButton = this.instantiationService.createInstance(MoveCellAction, 'notebook.MoveCellUp', 'masked-icon move-up', this.buttonMoveUp);
 
 		let splitCellButton = this.instantiationService.createInstance(SplitCellAction, 'notebook.SplitCellAtCursor', this.buttonSplitCell, 'masked-icon icon-split-cell');
-		splitCellButton.setListener(context);
+		splitCellButton.setListener(this._cellContext);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts:85]: Are the old actions disposed of when you set the content? If not we're going to be leaking listeners here.

File: src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts [hunk 2]
```diff
@@ -51,14 +52,24 @@ export class CellToolbarComponent {
 
 	ngOnInit() {
 		this.initActionBar();
+		this.model.onCellTypeChanged(cell => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts:55]: Make sure you dispose this on `ngOnDestroy`

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/cellViews/cellToolbar.component.ts:57]: `onCellTypeChanged` returns a disposable for unregistering the event handler (the arrow function)
