### PR TITLE
Fixes select box issue

### LINKED ISSUE #9797: dropdown elements in connection advanced dialog is not populated correctly
today's insider build:
Screen Shot 2020-03-30 at 9 39 01 PM

i am using mac.

very likely caused by this pr: https://github.com/microsoft/azuredatastudio/pull/9508/

### PR DESCRIPTION
**Pull request by aaomidi**
This PR fixes #9797

### CODE REVIEW

**Comment by alanrenmsft** [comment]
is this issue specific to macOS?

**Comment by Charles-Gagnon** [comment]
No, I was seeing it on Windows too

**Comment by aaomidi** [comment]
Nope, just a mistake when doing feedback changes and I guess I didn't have yarn watch running when testing it.

File: src/sql/base/browser/ui/selectBox/selectBox.ts [hunk 1]
```diff
@@ -66,12 +66,12 @@ export class SelectBox extends vsSelectBox {
 
 	constructor(options: SelectOptionItemSQL[] | string[], selectedOption: string, contextViewProvider: IContextViewProvider, container?: HTMLElement, selectBoxOptions?: ISelectBoxOptions) {
 		let optionItems: SelectOptionItemSQL[];
-		if (Array.isArray<string>(options)) {
-			optionItems = (options as string[]).map(o => {
+		if (typeof (options[0]) === 'string' && Array.isArray<string>(options)) {
```
Comment (alanrenmsft) [inline src/sql/base/browser/ui/selectBox/selectBox.ts]: apparently the Array.isArray<string>(options) did not work as expected, we probably don't need it. also we need to check the array length.

Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/selectBox/selectBox.ts]: Huh, so isArray<string> isn't actually checking that it's an array of strings? That seems like a bug there?

Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/selectBox/selectBox.ts]: Just to be safe should check options.length > 0 too

Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: No it's not a bug. Remember that the type is only there during compile time, not run time.

Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: I can probably just flip the conditions.

Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: It does do type coercion, so it's still useful.

Comment (alanrenmsft) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: [] is an array, but your check will throw exception here.

Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: That's true, although I'm going to end up just throwing another error to the user here.

Comment (Charles-Gagnon) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: If that was the case then typeof(options[0]) wouldn't do anything 😄 Interfaces are dropped (so yeah we lose the typing for SelectOptionItemSQL) but the string type is still there so theoretically we should be able to actually make a generic version of isArray unless I'm missing something that at least is able to handle classes and built in types correctly.

I think the problem here is that we define the functions but they're never actually implemented anywhere so it just falls back to using the built-in isArray. Looking at VS Code it's likely they added these purely for the type coercion and didn't actually care about differentiating different types of arrays (since all their uses are like `string | string[]`

File: src/sql/base/browser/ui/selectBox/selectBox.ts [hunk 2]
```diff
@@ -65,6 +67,10 @@ export class SelectBox extends vsSelectBox {
 	private element?: HTMLElement;
 
 	constructor(options: SelectOptionItemSQL[] | string[], selectedOption: string, contextViewProvider: IContextViewProvider, container?: HTMLElement, selectBoxOptions?: ISelectBoxOptions) {
+		if (options.length === 0) {
```
Comment (alanrenmsft) [inline src/sql/base/browser/ui/selectBox/selectBox.ts]: this is a behavior change, i think sometimes we do initialize the selectbox with no options and then add options to it. I could be wrong, but if you are making this change, should definitely do some testing.

File: src/sql/base/browser/ui/selectBox/selectBox.ts [hunk 3]
```diff
@@ -66,12 +68,15 @@ export class SelectBox extends vsSelectBox {
 
 	constructor(options: SelectOptionItemSQL[] | string[], selectedOption: string, contextViewProvider: IContextViewProvider, container?: HTMLElement, selectBoxOptions?: ISelectBoxOptions) {
 		let optionItems: SelectOptionItemSQL[];
-		if (Array.isArray<string>(options)) {
-			optionItems = (options as string[]).map(o => {
+
+		if (options.length === 0) {
+			optionItems = [];
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/selectBox/selectBox.ts]: Do you need this check? I would imagine the else if would handle this fine since it's an empty array anyways.

**Comment by aaomidi** [comment]
Alright so it looks like I forgot how JS works. 

```
let options = [];
options[10] === undefined
```

No need for length checking

File: src/sql/base/browser/ui/selectBox/selectBox.ts (hunk 2 above)
Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: Not an issue anymore

File: src/sql/base/browser/ui/selectBox/selectBox.ts (hunk 3 above)
Comment (aaomidi) [reply src/sql/base/browser/ui/selectBox/selectBox.ts]: Not an issue anymore

**Comment by Charles-Gagnon** [comment]
*sigh* Javascript...
