### PR TITLE
Fix for modify column structure bug in import wizard. 

### LINKED ISSUE #11949: SQL Server Import: Modify Columns step is ignoring my edits on Azure Data Studio for macOS.
My issue is explained well with this old comment:

> Modify Columns step is ignoring my edits on Azure Data Studio for macOS. After I choose to continue, the table is created with the suggested types instead my edits. That's causing an "Error inserting data into table" because of one of my columns is VARCHAR(72), and PROSE is setting VARCHAR(50)

_Originally posted by @williamthiago in https://github.com/microsoft/azuredatastudio/issues/2090#issuecomment-509819216_

A few details about my environment:
- Version: 1.21.0
- Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
- Date: 2020-08-11T20:51:42.148Z (1 wk ago)
- VS Code: 1.48.0
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.4.0 (MacOS 10.15.4 Catalina)

Steps to Reproduce:

1. Install SQL Server Import extension.
2. Connect to db server (I am connecting to an AzureSql database)
3. Run Flat File Import: Import Wizard from command palette
4. Fill in necessary fields in Step 1
5. Preview Data in Step 2
6. Modify data types for 1 or more columns (for example: `tinyint` -> `int`, `nvarchar(50)` -> `nvarchar(200)`) in Step 3
7. Receive an error that complains about data truncation. In my example, I've changed the data type of the `Winner` column from `bit` to `nvarchar(20)`, but the error says that a string cannot be converted to a boolean; one can infer that the importer ignored my manual correction. See example below.

Screen Shot 2020-08-24 at 10 28 15 PM

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #11949

### CODE REVIEW

**Review by abist — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
You were able to repro the issue and verify that this fixed it? It would be good to know why this broke it since I don't see anything inherently wrong with the code you had.

**Review by Charles-Gagnon — APPROVED** [review]

File: extensions/import/src/wizard/pages/summaryPage.ts [hunk 1]
```diff
@@ -106,16 +106,19 @@ export class SummaryPage extends ImportPage {
...
+				index: i++,
 				newName: val.columnName,
 				newDataType: val.dataType,
 				newNullable: val.nullable,
 				newInPrimaryKey: val.primaryKey
 			};
-			changeColumnResults.push(this.provider.sendChangeColumnSettingsRequest(columnChangeParams));
-		});
+			const changeColumnResult = await this.provider.sendChangeColumnSettingsRequest(columnChangeParams);
+			changeColumnResults.push(changeColumnResult);
```
Comment (Charles-Gagnon) [inline extensions/import/src/wizard/pages/summaryPage.ts:120]: Putting a note here - should most likely error out if any of these fail instead of just continuing on.
