### PR TITLE
Fix schema comparison failure for Azure synapse dedicated pool

### LINKED ISSUE #22923: "Update project from database" doesn't work anymore since ADS version 1.43
- Azure Data Studio Version: 1.43
- OS Version: Windows 11

Steps to Reproduce:

1. create project from database (in my case a synapse dedicated sql pool) (create project from database extracts the wrong platform version)
2. update that project (via 'update project from database') with the same database
3. error received of "target platform isn't matching", even if I change target platform it doesn't work. 

Does this issue occur when all extensions are disabled?: Yes/No
I need to use the extensions SQL DB project & schema compare for this to work

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #22923  (and #20363).
Two problems fixed in this PR:
1. In a prior PR (https://github.com/microsoft/azuredatastudio/pull/20607), target platform was getting incorrectly set (just considers the vscode version, and doesn't read the ADS version of the enum values used). Updated assignment in this one.
2. Target platform wasn't getting set in the Schema Compare object that was been sent from Update database from projects codeflow. Because of this, the code was using the default target platform of 160 (Sql Server 2022), hence the comparison failed. Assignment added in this PR.

Tested scenarios:
- Create project from database sets correct target platform for Azure and DW databases.
- Update project from database and Schema comparison workflows complete successfully for Azure Synapse dedicated SQL pool.
- Schema comparison fails when Azure database and DW platform project are compared (expected behavior) [and the other way round].

### CODE REVIEW

File: extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts [hunk 1]
```diff
@@ -572,7 +572,7 @@ export class UpdateProjectFromDatabaseDialog {
 			projectFilePath: this.projectFileDropdown!.value! as string,
 			extractTarget: mapExtractTargetEnum(<string>this.folderStructureDropDown!.value),
 			targetScripts: [],
-			dataSchemaProvider: '',
+			dataSchemaProvider: this.project!.getProjectTargetVersion(),
```
Comment (kisantia) [inline extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts:575]: does the schema compare extension already do this or does a similar fix need to happen there as well?

**Review by kisantia — APPROVED** [review]

File: extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts (hunk 1 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts:575]: not sure if the `dataSchemaProvider` gets set later, but this place in schema compare might also need to be updated: https://github.com/microsoft/azuredatastudio/blob/d69e5b97df19ec32dc41fd186c83b819e2ed72af/extensions/schema-compare/src/schemaCompareMainWindow.ts#L150-L163

Comment (SakshiS-harma) [reply extensions/sql-database-projects/src/dialogs/updateProjectFromDatabaseDialog.ts:575]: So, in the above spot, we don't have any context about dataSchemaProvider. We just have the projectFilePath.
The data schema provider gets appropriately set when SchemaCompareDialog opens and "Ok" button is clicked. So, this scenario (schema compare started from project context) works as expected.

**Review by Benjin — APPROVED** [review]
