### PR TITLE
Machine Learning - Bug fixes

### LINKED ISSUE #10369: ML - Make predictions Display Name issue
- Azure Data Studio Version:
Version: 1.17.1 (user setup)
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-30T00:16:35.943Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Click on the the **_Make predictions_** button from ML Extension.
2. Choose the **_File upload_** method. Then, follow the instructions until **Step 3**.
Specify `mpdev` as **_Display Name_**. 
image
3. When you click Predict, you'll get a new SQL file that looks like this:
image
If you click run, it will show an error like below: 
_Msg 1038, Level 15, State 4, Line 16
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name._

The expected outcome of **_Make predictions_** is to display the following line
`    [p].[variable1] AS mpdev`
(instead of `[p].[mpdev] AS [variable1]`) 

I can repro using the **_File upload_** method, but not the **_Imported Model_**. I haven't tested the Azure ML one. 

Thanks.

### PR DESCRIPTION
**Pull request by llali**
This PR fixes 
#10369
#10353

Added a message when imported models table is empty

### CODE REVIEW

File: extensions/machine-learning/src/packageManagement/packageManager.ts [hunk 1]
```diff
@@ -196,23 +199,25 @@ export class PackageManager {
...
+		let rExecutable = await this.getRExecutable();
 		if (model.downloadUrl) {
 			const packageFile = utils.getPackageFilePath(this._rootFolder, model.fileName || model.name);
 			const packageExist = await utils.exists(packageFile);
 			if (!packageExist) {
 				await this._httpClient.download(model.downloadUrl, packageFile, this._outputChannel);
 			}
-			cmd = `"${this._rExecutable}" CMD INSTALL ${packageFile}`;
+			cmd = `"${rExecutable}" CMD INSTALL ${packageFile}`;
 			output = await this._processService.executeBufferedCommand(cmd, this._outputChannel);
```
Comment (udeeshagautam) [inline extensions/machine-learning/src/packageManagement/packageManager.ts:218]: Long term  - I think the execute command code is something needed by so many extensions (I know 3 for sure ML/Proj) we should work with Alan to see if we can have some common utils for this hat extns can share.

File: extensions/machine-learning/src/common/utils.ts [hunk 2]
```diff
@@ -44,6 +44,15 @@ export async function exists(path: string): Promise<boolean> {
 	return promisify(fs.exists)(path);
 }
 
+export async function isDirectory(path: string): Promise<boolean> {
+	try {
+		const stat = await fs.promises.lstat(path);
```
[the remark this answers is not in the document]
Comment (llali) [reply extensions/machine-learning/src/common/utils.ts:49]: I use fs itself too so I wanted to make it clear. otherwise it'll look like promises.promises 

---
In reply to: [425278988](https://github.com/microsoft/azuredatastudio/pull/10377#discussion_r425278988) [](ancestors = 425278988)

File: extensions/machine-learning/src/packageManagement/packageManager.ts (hunk 1 above)
Comment (llali) [reply extensions/machine-learning/src/packageManagement/packageManager.ts:218]: sure, there are so many modules added here which will be useful to move to share location

---
In reply to: [425310850](https://github.com/microsoft/azuredatastudio/pull/10377#discussion_r425310850) [](ancestors = 425310850)
