### PR TITLE
Fix #5765 Trusted state handling

### LINKED ISSUE #5765: Notebooks: Can be Improperly Trusted After Save + Reopen
Repro:

Save a notebook
Rename the notebook (i.e. from file explorer)
Open the (now renamed) file [notebook will be untrusted]
Make an edit to the notebook, and save [notebook will still show untrusted]
Close the file
Reopen the file

Now, notebook will incorrectly show as trusted.

### PR DESCRIPTION
**Pull request by kevcunnane**
- Notebooks Can be Improperly Trusted After Save + Reopen
Fix was to only save if actually trusted.
Also fixed condition where it wasn't correctly skipping if in the queue

### CODE REVIEW

File: src/sql/workbench/services/notebook/common/notebookServiceImpl.ts [hunk 1]
```diff
@@ -553,16 +553,21 @@ export class NotebookService extends Disposable implements INotebookService {
...
+			// 4. Notebook is trusted. Don't need to save state of untrusted notebooks
 			let notebookUriString = notebookUri.toString();
-			if (updateTrustState && this._trustedCacheQueue.findIndex(uri => uri.toString() === notebookUriString)) {
-				this._trustedCacheQueue.push(notebookUri);
-				this._updateTrustCacheScheduler.schedule();
+			if (changeType === SerializationStateChangeType.Saved && this._trustedCacheQueue.findIndex(uri => uri.toString() === notebookUriString) < 0) {
+				// Only save if it's trusted
+				let notebook = this.listNotebookEditors().find(n => n.id === notebookUriString);
+				if (notebook && notebook.model.trustedMode) {
+					this._trustedCacheQueue.push(notebookUri);
```
Comment (anthonydresser) [inline src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: Does this have a borderline "resource" leak, where we constantly add to this cache but never clear it?

Comment (kevcunnane) [reply src/sql/workbench/services/notebook/common/notebookServiceImpl.ts]: In `updateTrustedCache` we clear it out:
```
				this._trustedCacheQueue = [];
```
