### PR TITLE
Fix account and tenant selection behavior

### LINKED ISSUE #21643: Selecting server/database from Azure tree does not pick up correct account
- Azure Data Studio Version: RC1
- OS Version: Windows 11

Steps to Reproduce:

1. In Azure tree, connect to multiple accounts using ADAL
2. Migrate accounts to MSAL (update auth library and reload)
3. Reauthenticate to accounts as prompted.
4. Connect to any resource from second+ account in list.
5. The account loaded in dropdown is the first one in the list and not the one associated with the resource.

This is a new issue, and root cause is likely related to MSAL <> ADAL account id comparison when loading associated account in dropdown, as account id is different for ADAL live# accounts, and is not matched with MSAL live# accounts, but needs further investigation.

The issue does not apply to newly added MSAL accounts, and only applies to migrated accounts.

### LINKED ISSUE #21743: Azure settings in Connection Dialog not disabled during connect
The Azure dropdowns aren't disabled during a connection like the other ones which is confusing and could result in unexpected behavior if changed in the middle of a connection. 

image

### PR DESCRIPTION
**Pull request by cheenamalhotra**
This PR fixes #21643 and tenant selection issues as well.

I had been intermittently facing this issue and was able to finally debug and root cause it. The issue had been present due to selectBox defaulting to 'first' item by default in `fillInAzureAccountOptions()` which when called without any data always ends up selecting first account in the list. This fires event that populates tenant and we start getting console errors as under:

image
_(captured in v1.41.0)_

Which should not be the case as the subscription ID "72f988bf-***" is not applicable to live account. This PR makes sure the correct account is selected after this call completes only in `fillInConnectionInputs(connectionInfo)` when connection Info is available.

Also removed unwanted `_azureTenantId` assignments that were causing incorrect tenant to be selected (started failing since https://github.com/microsoft/azuredatastudio/commit/ec7e754009ef126e60f51fd1c983c16fb974849a#diff-6cbed09935af5348af95a7fe0c504191ac5e2ee347e0325d5d89d6237dd90698R692). This part wasn't necessary in the PR as the fallback to default owning tenant takes care of tenant being available.

Also fixed #21743 with minor changes.

**I would propose we take this change in hotfix as well, to prevent these issues from surfacing.**
cc @kburtram

### CODE REVIEW

File: src/sql/base/browser/ui/selectBox/selectBox.ts [hunk 1]
```diff
@@ -193,15 +193,17 @@ export class SelectBox extends vsSelectBox {
...
+	public selectWithOptionName(optionName?: string, selectFirstByDefault: boolean = true): void {
 		let option: number | undefined;
 		if (optionName !== undefined) {
 			option = this._optionsDictionary.get(optionName);
 		}
 		if (option !== undefined) {
 			this.select(option);
 		} else {
-			this.select(0);
+			if (selectFirstByDefault) {
```
Comment (alanrenmsft) [inline src/sql/base/browser/ui/selectBox/selectBox.ts:204]: you can merge the new if statement with else.

**Review by alanrenmsft — APPROVED** [review]

**Review by cssuh — APPROVED** [review]
