### PR TITLE
fix notebook serialization issue for non-mssql providers

### LINKED ISSUE #22441: Cannot Export Query Results with Postgres connection on Apple M1
Issue Type: <b>Bug</b>

1. On Apple M1 Max Chip, open Azure Data Studio using Rosetta
2. Install PostgreSQL extension for Azure Data Studio
3. Create Jupyter Book and add a sql query to run
4. Run the sql query with a Postgres connection
5. Try to export results in json, markdown, xml, excel, etc

Outcome:
Failed to save results. Could not find a serialization provider with the specified ID 'PGSQL'

Azure Data Studio version: azuredatastudio 1.42.0 (Universal) (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T18:04:34.407Z)
OS version: Darwin x64 22.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 4|
|Memory (System)|64.00GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

[vscode-app-1679671057776.log](https://github.com/microsoft/azuredatastudio/files/11063943/vscode-app-1679671057776.log)

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #22441

I am using a MySQL test server to demonstrate the fix below.

Before:
image

After:

nb-save-as

### CODE REVIEW

**Review by corivera — APPROVED** [review]
Looks good. The default ipynb serializer is under the SQL provider, so this works fine as a default

File: src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts [hunk 1]
```diff
@@ -482,14 +482,9 @@ export class DataResourceDataProvider implements IGridDataProvider {
...
-			// If there's still no provider, then fallback to the default MSSQL one.
-			let connProviders = this.cellModel.notebookModel.getApplicableConnectionProviderIds(this.cellModel.notebookModel.selectedKernelDisplayName);
-			if (connProviders?.length > 0) {
-				provider = connProviders[0];
-			} else {
-				provider = mssqlProviderName;
-			}
+			// Serizalize notebook query results to file is agnostic of database engine since the data is already in the notebook.
+			// We can let the mssql provider handle it so that other providers don't have to implement it.
+			provider = mssqlProviderName;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:487]: I feel like we should first check if the current provider supports serialization, and if it does use that. Then only fall back to MSSQL if it doesn't. There may be cases where certain providers want to serialize data in a specific way for some reason.

Comment (alanrenmsft) [reply src/sql/workbench/contrib/notebook/browser/outputs/gridOutput.component.ts:495]: that sounds good to me. implemented in most recent commit.
