### PR TITLE
fix for stop session error and session selection lost issue

### LINKED ISSUE #3123: Failed to stop sessions
- Azure Data Studio Version:

Steps to Reproduce:
don't have a consistent repro
image

### PR DESCRIPTION
**Pull request by alanrenmsft**
1. fix #3123 - this is the UI side of fix, there is another fix at the sqltoolsservice side. basically regardless the error, we will set the UI to allow user to start another session instead of the unrecoverable state. with the service side fix, this should not happen, but just in case.

2. fix the issue that the session selection in the dropdown is lost when switch 2 running profiler editors. previously the code is resetting the collection but not restoring the selection, I refactored the code a bit.

### CODE REVIEW

File: src/sql/parts/profiler/service/profilerService.ts [hunk 1]
```diff
@@ -141,7 +141,11 @@ export class ProfilerService implements IProfilerService {
 			this._sessionMap.get(this._idMap.reverseGet(id)).onSessionStateChanged({ isStopped: true, isPaused: false, isRunning: false });
 			return true;
 		}, (reason) => {
-			this._notificationService.error(reason.message);
+			// The error won't be actionable to the user, so only log it to console.
+			// In case of error, the state of the UI is not usable, makes more sense to
+			// set it to stopped so that user can restart it or pick a different session
+			console.error(reason.message);
```
Comment (abist) [inline src/sql/parts/profiler/service/profilerService.ts]: we should remove console calls
