### PR TITLE
Nasc/Compute and Storage Loading Page Bug Fix

### LINKED ISSUE #13134: Modifying components in ModelViewDashboard only works after the tab has been selected
In the Arc extension we use a ModelViewDashboard with multiple tabs.  When opening a dashboard, the model may not have data yet.  If so, we initialize certain UI components with loading text/icons.  Then when the model is loaded, each tab modifies its components with the real values.

We're seeing that modifying these components only works after the tab has been selected.  It doesn't have to currently be selected.  Just has to have been selected at some point.  Modifications made while the tab has never been selected don't appear in the UI when you do eventually visit the tab.

We've seen similar behavior in the past where we can't use LoadingComponents on anything other than the default tab.  Even though we set loading to false, the spinner keeps spinning unless you visited the tab while it was loading.

What's interesting is that adding components seems to work fine, even without visiting the tab.  It's just removing or modifying components that doesn't take effect.

The current repro is the Compute + Storage page of the Arc Postgres dashboard.  The text boxes keep the 'loading' placeholder even when the debugger shows we've changed it.  And it only unsticks once you visit the tab then refresh the model.  To repro this, the model must not have data on initial load.  So this only happens the first time you open a dashboard for each resource. (Though it could cause stale data in other situations)

Let me know if it's useful and I can create a minimal repro.

### PR DESCRIPTION
**Pull request by nasc17**
This PR fixes #13134 
The compute and storage page previously was getting stuck loading while waiting for the model to have data. This fix makes it so that certain UI components are not initialized until after the data is present. It takes about 5-10s for the page to populate. 

Csloadingfixpage1
Cspageloadingpage2

### CODE REVIEW

File: extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts [hunk 1]
```diff
@@ -483,8 +461,30 @@ export class PostgresComputeAndStoragePage extends DashboardPage {
...
-		this.editMemory();
+		if (this._postgresModel.configLastUpdated) {
+			this.editWorkerNodeCount();
+			this.editCores();
+			this.editMemory();
+
+			// Workaround https://github.com/microsoft/azuredatastudio/issues/13134
+			// by only adding these once the model has data. After the bug is fixed,
+			// use loading indicators instead of keeping the page blank.
+			if (this.workerContainer?.items.length === 0) {
```
Comment (bergeron) [inline extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts:472]: My only concern is duplicated UI components if there are concurrent refreshes that cause a race here.  Doing one refresh as a time in the model is the best fix I know.  But there's a race there too between checking and setting the promise.  @Charles-Gagnon do you know of any better locking strategy in JS?

Comment (Charles-Gagnon) [reply extensions/arc/src/ui/dashboards/postgres/postgresComputeAndStoragePage.ts:472]: The javascript engine is single threaded - so as long as you don't have anything that'll cause the thread to suspend/switch context (such as awaits) then this should be fine.

**Review by Charles-Gagnon — APPROVED** [review]
