### PR TITLE
emit error for kube file not found

### LINKED ISSUE #11035: screen to display kube config info is stuck in spinning mode when config file is not present - Arc data controller extension
- Azure Data Studio Version:

Steps to Reproduce:

1. Deploy the Azure Arc data controller extension onto the latest insiders build
2. Launch the data controller wizard
3. In the screen where the wizard attemps to read the config file from the default path to display the cluster contexts, if the config file is not present, it seems to be stuck with a spinning wheel.

It should drop an error message "File not found. Please select a kube config file" ..

### PR DESCRIPTION
**Pull request by ranasaria**
This PR fixes #11035

### CODE REVIEW

File: extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts [hunk 1]
```diff
@@ -30,14 +30,15 @@ export class RadioGroupLoadingComponentBuilder implements azdata.ComponentBuilde
...
 	async loadOptions(optionsInfo: OptionsInfo | (() => Promise<OptionsInfo>)): Promise<void> {
-		if (typeof optionsInfo !== 'object') {
-			optionsInfo = await optionsInfo();
-		}
 		this.component().loading = true;
 		this._optionsDivContainer.clearItems();
-		let options: (string[] | azdata.CategoryValue[]) = optionsInfo.values!;
-		let defaultValue: string = optionsInfo.defaultValue!;
 		try {
+			if (typeof optionsInfo !== 'object') {
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts:36]: What's this change for?

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts:36]: So that when an exception is thrown while calling optionsInfo() the catch block handles displaying it correctly in the divContainer.

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts:36]: Please include a screenshot/gif of what this looks like now

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 2]
```diff
@@ -677,6 +679,23 @@ function getClusterContexts(file: string): (() => Promise<OptionsInfo>) {
 	};
 }
 
+async function throwIfNotExistsOrNotAFile(file: string, fileDescription: string = 'kube config') {
+	try {
+		const stats = await fs.promises.stat(file); // this throws if the file does not exist with error.code = ENOENT
+		if (!stats.isFile()) {
+			throw Error(localize('getClusterContexts.NotFile', "Path:{0} is not a file, please select a valid {1} file ...", file, fileDescription));
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:686]: Missing space after `Path:`?

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 3]
```diff
@@ -677,6 +679,23 @@ function getClusterContexts(file: string): (() => Promise<OptionsInfo>) {
 	};
 }
 
+async function throwIfNotExistsOrNotAFile(file: string, fileDescription: string = 'kube config') {
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:682]: `kube config` should be localized (the config part at least I would expect to be different in other languages)

File: extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts:36]: This is what it looks like after the fix: 
image

This is what it did before the fix. The spinner next to the 'Cluster Context:' label would just keep spinning forever indicating load which would never complete because there is no file.
image

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts:36]: And I assume you've tested it that it clears the error message correctly when you then select a valid kube config?

File: extensions/resource-deployment/src/ui/modelViewUtils.ts [hunk 4]
```diff
@@ -677,6 +679,23 @@ function getClusterContexts(file: string): (() => Promise<OptionsInfo>) {
...
+	try {
+		const stats = await fs.promises.stat(file); // this throws if the file does not exist with error.code = ENOENT
+		if (!stats.isFile()) {
+			throw Error(localize('getClusterContexts.NotFile', "Path:{0} is not a file, please select a valid {1} file ...", file, fileDescription));
+		}
+	}
+	catch (e) {
+		if (e.code === 'ENOENT') {
+			throw Error(localize('getClusterContexts.FileNotFound', "File:{0} not found. Please select a {1} file ...", file, fileDescription));
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/modelViewUtils.ts:691]: I'd get rid of the `...` too, I'm not a fan of the "dangling" sentences like that for UI elements.

File: extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts (hunk 1 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts:36]: yup. With valid kube config file, the new radio buttons get shown. That reminds me to test with a an invalid file that is picked from file picker that exists but is not parseable as a kube config file. Will test with that before check-in as well.

File: extensions/resource-deployment/src/ui/modelViewUtils.ts (hunk 3 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts:682]: done

File: extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts (hunk 1 above)
Comment (alanrenmsft) [reply extensions/resource-deployment/src/ui/radioGroupLoadingComponentBuilder.ts:36]: @ranasaria I do see an accessibility issue here, we should leverage the wizard error banner to show errors, otherwise it won't get announced unless you make this a live region.

File: extensions/resource-deployment/src/ui/modelViewUtils.ts (hunk 2 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts]: fixed

File: extensions/resource-deployment/src/ui/modelViewUtils.ts (hunk 4 above)
Comment (ranasaria) [reply extensions/resource-deployment/src/ui/modelViewUtils.ts]: fixed

**Comment by alanrenmsft** [comment]
@ranasaria There is still an open comment you haven't addressed, could you please take a look?
