### PR TITLE
Fix node update in bdc dashboard on reconnect

### LINKED ISSUE #8102: BDC connections doesn't save new password...
Issue Type: <b>Bug</b>

1. Create bdc with specific admin credentials
2. Add controller endpoint from #1 to BDC connections
3. Delete bdc
4. Create bdc with same username as #1 but different password
5. Connect to endpoint from #2 & click Manage
6. It will show the connections dialog again since password is different. Type new password and hit ok
7. Close bdc dashboard
8. do #5 again, you will be prompted again!!

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (a7f597c9431c2ee82e6175eb744c328e8c680019, 2019-10-28T07:38:19.274Z)
OS version: Windows_NT x64 10.0.19008

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (14.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

(1 theme extensions excluded)

</details>

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
For #8102

We weren't calling saveControllers after updating the info in the dashboard model so while the info was updated for the current session if you closed ADS and tried to connect again we'd prompt for the password again. 

Also fixed it to use the actual value of the remember password option for the node so that we don't overwrite it to false each time. #8136 opened up to cover us not having remember password being an option in the connect controller dialog. 

And finally fixed issue where we weren't saving the controller node when opening from the SQL dashboard if the connection information was right. (If it was wrong then we'd prompt for connection and save it correctly there)

### CODE REVIEW

File: extensions/mssql/src/main.ts [hunk 1]
```diff
@@ -216,7 +216,8 @@ async function handleOpenClusterDashboardTask(profile: azdata.IConnectionProfile
 			url: controller.endpoint,
 			auth: profile.authenticationType === 'Integrated' ? AuthType.Integrated : AuthType.Basic,
 			username: 'admin', // Default to admin as a best-guess, we'll prompt for re-entering credentials if that fails
-			password: profile.password
+			password: profile.password,
+			rememberPassword: true
```
Comment (Charles-Gagnon) [inline extensions/mssql/src/main.ts]: We don't currently have a way for the user to set this from the SQL dashboard. Maybe have a setting to say which to use?
