### PR TITLE
Fix bug minimizing a maximized result grid

### LINKED ISSUE #3993: Resultset magnify button doesn't unmagnify
- Azure Data Studio Version: `master`
 
Steps to Reproduce:

1. Run a query with multiple resultsets
2. Click the Magnify button
3. Click the Un-Magnify button

Expected: Resultset grid return to original state

Actual: Resultset grid stays in magnified state and clicking button has no effect

### PR DESCRIPTION
**Pull request by MattIrv**
Fixes #3993. `ScrollableSplitView`'s `addViews` method expected views in reverse order (the last one in the array passed in would end up at the top), but the views were not being passed in reverse order when minimizing a maximized result set. I've changed `addViews` to expect them in a normal order and updated code where needed.

### CODE REVIEW

**Comment by kburtram** [comment]
@MattIrv I'll merge now for tonight's build.

File: src/sql/base/browser/ui/scrollableSplitview/scrollableSplitview.ts [hunk 1]
```diff
@@ -314,6 +316,14 @@ export class ScrollableSplitView extends HeightMap implements IDisposable {
 		if (!types.isArray(sizes) && sizes.type === 'distribute') {
 			this.distributeViewSizes();
 		}
+
+		// Re-render the views. Set lastRenderTop and lastRenderHeight to undefined since
+		// this isn't actually scrolling up or down
+		let scrollTop = this.lastRenderTop;
```
Comment (anthonydresser) [inline src/sql/base/browser/ui/scrollableSplitview/scrollableSplitview.ts]: You shouldn't need this code. this is handled later in the lifecycle of laying out the view
