### PR TITLE
accessibility fix: swaps header tags for label tags on most recent list

### LINKED ISSUE #10623: A11y_AzureDataStudioStayHealthy_Welcome_Resources_ScreenReader: Non header element is announced with heading level.
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#NonBenchmark;#DesktopApp;#MAS1.3.1;#SQL Azure Data Studio;#FTP;#NVDA;#JAWS;#STP;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS1.3.1
Screen reader : NVDA2020.1, JAWS

**Repro Steps:**
1 . Launch Azure Data Studio Insiders application.
2 . If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3 . Navigate till Resources section on Welcome screen.
4 . Launch screen reader as NVDA.
5 . Navigate to Name last opened line in browse mode

**Actual:**
On navigating to "Name and  last opened " line using insert+numpad key (6) it is announced as heading level 4

**Same issue with JAWS**

**Expected:**
The line "Name and last opened" should not be announced as heading level 4. 

**User Impact:**
Screen reader users will get the wrong structure information.

**Attachment link for Reference:**
[A11y_AzureDataStudioStayHealthy_Welcome_Resources_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/4701072/A11y_AzureDataStudioStayHealthy_Welcome_Resources_ScreenReader.zip)

### PR DESCRIPTION
**Pull request by v-bbrady**
Accessibility issue: #10623. Non header element is announced with heading level. This PR fixes the issues by replacing them with label tags.

This PR fixes #10623

### CODE REVIEW

File: src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts [hunk 1]
```diff
@@ -111,14 +111,14 @@ export default () => `
...
-						<input class="input" name="tabs" type="radio" id="tab-1" checked="checked" />
+						<input tabindex="-1" class="input" name="tabs" type="radio" id="tab-1" checked="checked" />
 						<label class="label" for="tab-1" tabIndex="0">${escape(localize('welcomePage.history', "History"))}</label>
 						<div class="panel">
 							<div class="recent history">
 								<div class="flex list-header-container">
 									<i class="icon-document themed-icon"></i>
-									<h4 class="list-header">${escape(localize('welcomePage.name', "Name"))}</h4>
-									<h4 class="list-header-last-opened">${escape(localize('welcomePage.lastOpened', "Last Opened"))}</h4>
+									<label tabindex="0" class="list-header"><b>${escape(localize('welcomePage.name', "Name"))}</b></label>
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts:120]: Is there a reason you're using label instead of something like span? Label is usually used when you're labeling a specific element such as a checkbox right?

File: src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts [hunk 2]
```diff
@@ -111,14 +111,14 @@ export default () => `
 				<div class="resources-container">
 					<h2>${escape(localize('welcomePage.resources', "Resources"))}</h2>
 					<div class="tabs">
-						<input class="input" name="tabs" type="radio" id="tab-1" checked="checked" />
+						<input tabindex="-1" class="input" name="tabs" type="radio" id="tab-1" checked="checked" />
```
Comment (alanrenmsft) [inline src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts:114]: why are we setting the tab index to -1? this will cause the radio button to be inaccessible

File: src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts (hunk 1 above)
Comment (alanrenmsft) [inline src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts:120]: why do we need to make a label keyboard focusable?

Comment (v-bbrady) [reply src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts:120]: This was addressed in one of the accessibility issues, that when you press enter on "deploy a server" it should then focus the History label.

Comment (v-bbrady) [reply src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts:120]: I have it skipping the checkbox for now because it is an unused feature that hasnt been built in yet. The future feature is to allow users to tab between history and pinned files. The checkbox provides no use for the user right now. But the styling and markup are built around what the new feature will be utilizing.

File: src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts (hunk 2 above)
Comment (v-bbrady) [reply src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts:114]: I have the checkbox inaccessible for now because it is an unused feature that hasnt been built in yet. The future feature is to allow users to tab between history and pinned files. The checkbox provides no use for the user right now. But the styling and markup are built around what the new feature will be utilizing.

File: src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts (hunk 1 above)
Comment (alanrenmsft) [reply src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts]: @v-bbrady IIUC, this is the fix for another issue, right? if so, please let me know which issue it is. it doesn't seem to be a reasonable behavior, i will probably resolve it as won't fix.

Comment (alanrenmsft) [reply src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts]: https://www.w3schools.com/tags/tag_label.asp, i agree with Charles here. @v-bbrady could you please make it span?

File: src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts (hunk 2 above)
Comment (alanrenmsft) [reply src/sql/workbench/contrib/welcome/page/browser/az_data_welcome_page.ts]: i see, I would definitely encourage you to add comment here to state that.
