### PR TITLE
unescape the encoded chars in tablename uri

### LINKED ISSUE #7947: Can't "edit Data" when tablename contains '$'
- Azure Data Studio Version: 1.12.2

Steps to Reproduce:

1. Create a table that contains $ in the tablename
2. right click on table -> Edit Data
3. Get an error massage

### PR DESCRIPTION
**Pull request by MaddyDev**
Decode the encoded special characters in table name when passing the table name as a uri during connections.
I'm not sure if there's a better place to unescape the uri since am not too familiar with the code around connections. As far as I debugged, these are the two places where the encoded table name is passed in and they couldn't map to a connection in connections (which have the names decoded). Suggestions welcome!
I have tested this creating a table dbo.Persons$1 and editing the content using edit data. And it works as expected. 

This PR fixes #7947

### CODE REVIEW

File: src/sql/workbench/contrib/editData/browser/editDataResultsEditor.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class EditDataResultsEditor extends BaseEditor {
 	 */
 	private _bootstrapAngular(): void {
 		let input = <EditDataResultsInput>this.input;
-		let uri = input.uri;
+		let uri = unescape(input.uri);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataResultsEditor.ts]: Why aren't you unescaping it in the EditDataResultsInput like you did for EditDataInput?

File: src/sql/workbench/contrib/editData/browser/editDataInput.ts [hunk 2]
```diff
@@ -93,7 +93,7 @@ export class EditDataInput extends EditorInput implements IConnectableInput {
 	// Getters/Setters
 	public get tableName(): string { return this._tableName; }
 	public get schemaName(): string { return this._schemaName; }
-	public get uri(): string { return this._uri.toString(); }
+	public get uri(): string { return unescape(this._uri.toString()); }
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataInput.ts]: Make sure you check that this URI isn't used anywhere else that expects the escaped URI
