### PR TITLE
Adjust modals for title bar

### LINKED ISSUE #5642: Dialog back button broken by custom menu bar
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open Connection Dialog and the Advanced Options Dialog
2. Click the "Back" button arrow

Expected: Advanced dialog is dismissed

Actual: Advanced dialog is not dismissed.  It appears the click is being captured by the custom menu bar.

image

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes #5642

### CODE REVIEW

File: src/sql/workbench/browser/modal/modal.ts [hunk 1]
```diff
@@ -172,6 +172,8 @@ export abstract class Modal extends Disposable implements IThemable {
 		}
 
 		this._bodyContainer = DOM.$(`.${builderClass}`, { role: 'dialog', 'aria-label': this._title });
+		const top = this.layoutService.getTitleBarOffset();
```
Comment (anthonydresser) [inline src/sql/workbench/browser/modal/modal.ts]: This is the real change, we need to adjust the top based on the title bar. The rest of the changes are converting layoutservice to workbenchlayoutservice to gain access to this method.

File: src/sql/workbench/parts/connection/browser/advancedPropertiesController.ts [hunk 2]
```diff
@@ -23,7 +23,7 @@ export class AdvancedPropertiesController {
 		this._options = this._advancedDialog.optionValues;
 	}
 
-	public showDialog(providerOptions: azdata.ConnectionOption[], container: HTMLElement, options: { [name: string]: any }): void {
```
Comment (anthonydresser) [inline src/sql/workbench/parts/connection/browser/advancedPropertiesController.ts]: I found this debt during my investigation, the container wasn't being used, (nor should it).

File: src/sql/workbench/services/connection/browser/connectionDialogWidget.ts [hunk 3]
```diff
@@ -91,13 +91,13 @@ export class ConnectionDialogWidget extends Modal {
...
 		@IThemeService themeService: IThemeService,
-		@ILayoutService layoutService: ILayoutService,
+		@IWorkbenchLayoutService layoutService: IWorkbenchLayoutService,
 		@ITelemetryService telemetryService: ITelemetryService,
 		@IContextKeyService contextKeyService: IContextKeyService,
 		@IContextMenuService private _contextMenuService: IContextMenuService,
 		@IContextViewService private _contextViewService: IContextViewService,
 		@IClipboardService clipboardService: IClipboardService,
-		@ILayoutService logService: ILogService
+		@ILogService logService: ILogService
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/connection/browser/connectionDialogWidget.ts]: haha interesting...guess this wasn't actually being used if this wasn't noticed until now?
