### PR TITLE
Fix telemetry opt out message

### LINKED ISSUE #7890: Telemetry opt in/out dialog mentions VS Code
Issue Type: <b>Bug</b>

image

Telemetry opt in/out dialog mentions VS Code

Azure Data Studio version: azuredatastudio Dev 1.13.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (1.95GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-es|Mic|1.9.0
vscodeintellicode|Vis|1.1.9

</details>

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7890

### CODE REVIEW

File: src/vs/workbench/contrib/welcome/telemetryOptOut/browser/telemetryOptOut.ts [hunk 1]
```diff
@@ -62,8 +62,8 @@ export abstract class AbstractTelemetryOptOut implements IWorkbenchContribution
 	}
 
 	private showTelemetryOptOut(telemetryOptOutUrl: string): void {
-		const optOutNotice = localize('telemetryOptOut.optOutNotice', "Help improve VS Code by allowing Microsoft to collect usage data. Read our [privacy statement]({0}) and learn how to [opt out]({1}).", this.privacyUrl, this.productService.telemetryOptOutUrl);
-		const optInNotice = localize('telemetryOptOut.optInNotice', "Help improve VS Code by allowing Microsoft to collect usage data. Read our [privacy statement]({0}) and learn how to [opt in]({1}).", this.privacyUrl, this.productService.telemetryOptOutUrl);
+		const optOutNotice = localize('telemetryOptOut.optOutNotice', "Help improve Azure Data Studio by allowing Microsoft to collect usage data. Read our [privacy statement]({0}) and learn how to [opt out]({1}).", this.privacyUrl, this.productService.telemetryOptOutUrl);
```
Comment (abist) [inline src/vs/workbench/contrib/welcome/telemetryOptOut/browser/telemetryOptOut.ts]: Probably adding a SQL CARBON EDIT tag would be a good idea to avoid this in future.
