### PR TITLE
Add fix to enter press on last row of Edit Data.

### LINKED ISSUE #19126: Pressing enter on the new row of Edit Data doesn't lead to a new row being created.
Previously you simply pressed enter to commit the row changes but after some recent changes, this is no longer the case.

Workaround: you need to click on another cell after pressing enter in order to update the table.

### PR DESCRIPTION
**Pull request by smartguest**
Since SlickGrid cannot move to the non existent new row when enter is pressed and therefore cannot trigger the cell submission process, this code will manually call the cell submission process if we press enter on the null row, then move to the newly created row below if successful. Invalid edits have been tested to work. Additionally, empty cells with a blank display value that aren't null are now properly treated as empty null cells (previously they weren't, causing blank spaces to appear after a new row has been added)

Valid edit and refresh afterwards:
ValidEditWithEnterPress

Invalid edit and correct one afterwards:
InvalidEditWithEnterPress

Fixes #19126

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
please test all the scenarios thoroughly and add the new scenario to the test plan.

**Comment by smartguest** [comment]
The test scenario was already added to the test plan, just that they were marked as not applicable.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 1]
```diff
@@ -193,6 +196,19 @@ export class EditDataGridPanel extends GridParentComponent {
...
+			// In case the last row is entered in, we need to wait to get the cell value after edit end
+			// so that we can add a row, submit the value and move down. (SlickGrid tries to go down immediately
+			// which fails, as we haven't added the new row yet).
+			if (self.isLastRowEnter) {
+				self.isLastRowEnter = false;
+				self.submitCurrentCellChange((result: EditUpdateCellResult) => {
+					self.table.grid.navigateDown();
+				},
+					(error: any) => {
+						this.notificationService.error(error);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:209]: You shouldn't ever mix this and self - doing so at best is confusing and at worst is a bug. In this it should be capturing the this context so it's probably fine - but you should still use self to at least be consistent here.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 2]
```diff
@@ -82,6 +82,9 @@ export class EditDataGridPanel extends GridParentComponent {
 	// Prevent the cell submission function from being called multiple times.
 	private cellSubmitInProgress: boolean;
 
+	// Manually submit the cell after edit end if it's the null row.
+	private isLastRowEnter: boolean;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:86]: Consider naming this `isInNullRowEnter` 

1. `isIn` is usually used to indicate state (which this is)
2. We call it the null row everywhere else so good to keep it consistent

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 3]
```diff
@@ -1131,6 +1151,11 @@ export class EditDataGridPanel extends GridParentComponent {
 			// Since we need to return a string here, we are using calling a function instead of event emitter like other events handlers
 			return this.onBeforeAppendCell ? this.onBeforeAppendCell(args.row, args.cell) : undefined;
 		});
+		this.table.grid.onKeyDown.subscribe((e, args) => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1154]: We already hook up the key listener on line 134 - why do you need to add another one here?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 4]
```diff
@@ -1189,7 +1214,7 @@ export class EditDataGridPanel extends GridParentComponent {
 		let valueToDisplay = '';
 		let cellClasses = 'grid-cell-value-container';
 		/* tslint:disable:no-null-keyword */
-		let valueMissing = value === undefined || value === null || (Services.DBCellValue.isDBCellValue(value) && value.isNull) || value === 'NULL';
+		let valueMissing = value === undefined || value === null || (Services.DBCellValue.isDBCellValue(value) && (value.isNull || value.displayValue.length === 0)) || value === 'NULL';
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1217]: An empty value isn't necessarily a null value though - what about an empty string?

**Comment by Charles-Gagnon** [comment]
Looking at the gif it seems like there's a noticeable delay between when you press enter and when the new row actually appears. That doesn't seem very user friendly - do you know why that's happening?

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 4 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1217]: Well currently, whatever is returned by the service does not distinguish between null or empty when the row is added, so in order to compensate for this, we will need to check if a new row is being added or not during the refresh.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 3 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1154]: For some reason, pressing enter does not work with the key listener there, it is not captured at all. My guess is that SlickGrid's native OnKeyDown swallowed the event and moved the focus down (since the enter key has a known use for base slickgrid), so you have to wire the event in the grid itself rather than the container.

**Comment by smartguest** [comment]
@Charles-Gagnon That is the behavior that happens during any refresh or when a new row is added, I think it's primarily caused by the way the data is loaded and refreshed. This has been happening since release 1.18.1, although the delay is slightly less than it is now (though back then we did not use slickgrid, and this has been the case for a while now)

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 3 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1154]: Not necessary, I'm removing it.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 4 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:1217]: Just added logic in the load data function to determine if a newly added row contains null values or not.

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts [hunk 5]
```diff
@@ -234,19 +247,30 @@ export class EditDataGridPanel extends GridParentComponent {
...
+						// Since it is currently impossible to add empty strings via edit data
+						// this must mean the empty strings on the newly added row are null values.
+						let isNewlyAddedRow = false;
+						if (this.isInNullRow && (counter === (count - 2))) {
+							isNewlyAddedRow = true;
+						}
 						let dataWithSchema = {};
 						// skip the first column since its a number column
 						for (let i = 1; i < this.dataSet.columnDefinitions.length; i++) {
+							let isNewAddedNullCell = isNewlyAddedRow && r.cells[i - 1].displayValue === '';
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:266]: Why can you not use isNull here?

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts (hunk 5 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:266]: We have to make sure that we are on the right row (one before the null row) first before we can replace the value, having the check done once for the whole row will optimize it a bit.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:266]: I was referring to checking whether the cell has a null value. Cell objects have isNull on them - why are you checking for an empty string here instead of using that?

Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editDataGridPanel.ts:266]: Because the newly added row will have the null values be marked as non-null (returned from the dataservice), and their display values will be empty strings, I'm not exactly sure where this comes from, but it's definitely not from anywhere in Edit Data. This is to handle this edge case.
