### PR TITLE
Save sql plan no longer uses the exact same name as the default

### LINKED ISSUE #18385: Save sqlplan always uses the same file name 'plan.sqlplan'
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Run a query execution plan using Explain
2. Save the sqlplan using the toolbar button

Expected: Filenames do not conflict with files in the save target directory by default

Actual: Filenames are always 'plan.sqlplan' regardless whether there is already a file with that name there.  Most apps would do something like 'plan_1.sqlplan', 'plan_2.sqlplan', etc.

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #18385

Previously when you clicked on the "Save Plan File" button. The save file dialog would appear recommending "plan.sqlplan" as the file name, even if there was already a file with that same name in the save folder location. This PR appends a number to the default file name, so any new files being saved with the default name will appear as "plan1.sqlplan", "plan2.sqlplan", and so on.

### CODE REVIEW

File: src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts [hunk 1]
```diff
@@ -446,24 +446,31 @@ export class SavePlanFile extends Action {
 	public override async run(context: ExecutionPlanView): Promise<void> {
 		const workspaceFolders = context.workspaceContextService.getWorkspace().folders;
 		const defaultFileName = 'plan';
+		const fileExtension = 'sqlplan'; //TODO: Get this extension from provider
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/executionPlan/browser/executionPlanView.ts:449]: It would be good to take the opportunity and replace all hardcoded instances of sqlplan in the code with a single constant defined somewhere - possibly src\sql\platform\connection\common\constants.ts

**Review by Charles-Gagnon — APPROVED** [review]

**Review by kburtram — APPROVED** [review]

**Review by aasimkhan30 — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]
