### PR TITLE
fix how failed/errored installation workflow

### LINKED ISSUE #8584: When installation of tool has failed/errorered the informational message is wrong
- Azure Data Studio Version:
Version: 1.14.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
Steps to Reproduce:

1. start 'Deploy SQL Server ...' dialogue by clicking on ... to the right of connections.
image
1. Change the following setting to point to an invalid location:
image
1. Make sure azdata is not already installed on the box. 
1. Select the 'SQL Server Big Data Cluster' card.  Then click on 'Install Tools'

Actual: The warning 'Some required tools are not installed, you can click the "Install tools" button to install them.' shows up.

image

Expected. Actual failure message shows pointing user to the 'Deployment' channel for more information

### PR DESCRIPTION
**Pull request by ranasaria**
Here is a list of changes in this bug fix:
1. Wrap download and insall of azdata.msl in a try/catch block to ensure exit code is non-zero when a failure happens.
2. Make sure the controls of UI stay disabled when an error/failure happens so that user is unable to continue the workflow.
3. Made the status field of the iTool object publicly readable.
4. Minor method renames for code redability.

This PR fixes #8584

### CODE REVIEW

File: extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts [hunk 1]
```diff
@@ -340,14 +343,14 @@ export class ResourceTypePickerDialog extends DialogBase {
...
-		this.enableUiControlsWhenNotInstalling(!tool.isInstalling); // if installing the disableContainers else enable them
+		this.toggleUiControls(tool.status !== ToolStatus.Installing); // if installing then disable ui controls else enable them
 	}
 
-	private enableUiControlsWhenNotInstalling(enabled: boolean): void {
-		this._cardGroup.enabled = enabled;
-		this._agreementContainer.enabled = enabled;
-		this._optionsContainer.enabled = enabled;
-		this._dialogObject.cancelButton.enabled = enabled;
+	private toggleUiControls(enable: boolean): void {
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: nit: But toggle usually means flipping between values. This is more of a setUiControlsEnabled

Comment (ranasaria) [reply extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: or disabled depending on the parameter value. How about enableDisableUiControls?

Comment (Charles-Gagnon) [reply extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: I prefer prefixing with set since it's setting a value. The enabled part is referring to the name of the property so I see no reason to change it.
