### PR TITLE
Fixing duplicate connections in Async sever tree

### LINKED ISSUE #22668: Duplicate connections can be added via AsyncServerTree.
It appears that it is now possible to add duplicate connections in ADS when AsyncServerTree is enabled. This introduces a number of issues related to deleting and connecting which is troubling. 

To reproduce:

1. Create a connection on ADS, or pick an individual one on the Object Explorer.

2. Open recent connections, and click the entry that matches the first connection.

3. It is observed that two entries for the connection appear on the server tree, and this introduces minor to serious issues with disconnecting and deleting (at one point I was unable to delete the entries until switching to a stable version of ADS). 

It appears that when adding a connection to the server tree, there is no duplicate check done at all. This will affect my current progress on the new connection URI as it depends on the server tree being able to not accept exact duplicates being added instead of overriding the existing profile.

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #22668 
In case of new connections, I am checking if the connection already exists in the group and then replace the connection instead of appending it to the end.

@smartguest can you please verify if the fix works.

### CODE REVIEW

File: src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts [hunk 1]
```diff
@@ -228,7 +228,12 @@ export class ServerTreeView extends Disposable implements IServerTreeView {
 			if (this._tree instanceof AsyncServerTree) {
 				const connectionParentGroup = this._tree.getElementById(newConnection.groupId) as ConnectionProfileGroup;
 				if (connectionParentGroup) {
-					connectionParentGroup.connections.push(newConnection);
+					const matchingConnectionIndex = connectionParentGroup.connections.findIndex((connection) => connection.matches(newConnection));
+					if (matchingConnectionIndex !== -1) {
+						connectionParentGroup.connections[matchingConnectionIndex] = newConnection;
+					} else {
+						connectionParentGroup.connections.push(newConnection);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts:235]: You should probably be using [ConnectionProfileGroup.addConnections](https://github.com/microsoft/azuredatastudio/blob/main/src/sql/platform/connection/common/connectionProfileGroup.ts#L145)

Make sure you go through the other places that you're directly adding the connections like here and verifying whether they should also be using addConnections as well.

Comment (aasimkhan30) [reply src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts:235]: I will have to modify to replace in case of matching connections. The current logic doesn't work in case of this bug as the new connection we get has a completely different id from the existing connections.

Comment (smartguest) [reply src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts:235]: Yeah, it's randomly generated each time you create a new connection from the connection maker

**Review by smartguest — APPROVED** [review]
It works with fixing the check, both for selecting recent connections as well as creating brand new connections with the same details. However there is an additional bug that I noticed that should be fixed as well along with this. I will create a new issue for it right now.

File: src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts:235]: And even updating the connection if we found a match here isn't great, we should be disposing the original connection. That also seems like something that the connection group should be providing functions to do.
