### PR TITLE
Fix #5566 DacFx extract/export pages not loading from command palette 

### LINKED ISSUE #5566: DacFx extract/export pages not loading from command palette
Steps to Reproduce:

1. Launch DacFx wizard from command palette
2. Select Extract or Export page
3. Page doesn't load

image

### PR DESCRIPTION
**Pull request by kisantia**
The DacFx wizard extract and export pages were failing to load when launched from the command palette or if the database name was unset in a the deploy page before going to the extract or export pages. The problem was that it was trying to sanitize the database name to generate a default filename, but it was failing when the database was not set.

Fixes #5566.

### CODE REVIEW

File: extensions/dacpac/src/wizard/api/dacFxConfigPage.ts [hunk 1]
```diff
@@ -148,7 +148,7 @@ export abstract class DacFxConfigPage extends BasePage {
 	}
 
 	protected generateFilePathFromDatabaseAndTimestamp(): string {
-		return path.join(this.getRootPath(), sanitizeStringForFilename(this.model.database) + '-' + this.getDateTime() + this.fileExtension);
+		return this.model.database ? path.join(this.getRootPath(), sanitizeStringForFilename(this.model.database) + '-' + this.getDateTime() + this.fileExtension) : '';
```
Comment (udeeshagautam) [inline extensions/dacpac/src/wizard/api/dacFxConfigPage.ts]: this is assuming this.model is not null - does the assumption stand always?

Comment (kisantia) [reply extensions/dacpac/src/wizard/api/dacFxConfigPage.ts]: yes it gets initialized when the wizard is started. There isn't anything that sets the model to null

Comment (udeeshagautam) [reply extensions/dacpac/src/wizard/api/dacFxConfigPage.ts]: The constructor checks for null? or its never created with null?
