### PR TITLE
Fix WYWIWYG Table cell adding new line in table cell

### LINKED ISSUE #15552: Notebook: WYSIWYG Table editing: Adding newline messes up table formating
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a table in WYSIWYG mode
2. Go to any text and press Enter in the middle of the test so as to introduce new line in the cell
3. Click outside the cell to get out of editing mode

**Observed**
A new row forms when the text should be in new line  

Possible Fix:
It seems WYSIWYG editor should add <br> Instead of new line character while editing tables in WYSIWYG mode

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #15552. 
Fixes when a user presses enter within the table cell to use <br> to create a new line within the cell. This makes sure the new line is inside the table cell.
 
Before Fix:
image

With Fix: 
image

### CODE REVIEW

**Review by lucyzhang929 — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts [hunk 1]
```diff
@@ -176,6 +176,10 @@ export class HTMLMarkdownConverter {
 			replacement: function (content, node, options) {
 				// For elements that aren't lists, convert <br> into its markdown equivalent
 				if (node.parentElement?.nodeName !== 'LI') {
+					// Keeps <br> in table cell to create new line in the table cell
+					if (node.parentElement?.nodeName === 'TD') {
```
Comment (chlafreniere) [inline src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:180]: Does this work with all table headers?

Comment (VasuBhog) [reply src/sql/workbench/contrib/notebook/browser/htmlMarkdownConverter.ts:180]: will have to add another condition for table headers as well, this condition was for table cells.

**Review by corivera — APPROVED** [review]
