### PR TITLE
declarative table fix

### LINKED ISSUE #14841: Switching focus between declarative tables
- Azure Data Studio Version:

When selecting rows from two different tables, we should be able to change the focus
ads-focus

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #14841

also fixes:
1. allow row selection when user click anywhere on the row
2. allow select row using keyboard
3. differentiate active & selected vs selected styles.
4. rename the selectEffect property to enableRowSelection
5. reset the selectedRow when clearContainer()

dark:
image

light:
image

### CODE REVIEW

**Review by aasimkhan30 — APPROVED** [review]

**Review by cssuh — APPROVED** [review]

File: src/sql/workbench/browser/modelComponents/declarativeTable.component.ts [hunk 1]
```diff
@@ -316,6 +321,15 @@ export default class DeclarativeTableComponent extends ContainerBase<any, azdata
 		}
 	}
 
+	public onKey(e: KeyboardEvent, row: number) {
+		const event = new StandardKeyboardEvent(e);
+		if (event.equals(KeyCode.Enter) || event.equals(KeyCode.Space)) {
+			this.onRowSelected(row);
+			e.preventDefault();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/browser/modelComponents/declarativeTable.component.ts:328]: FYI there's `EventHelper.stop` that lets you do preventDefault and stopPropagation in one line

**Review by Charles-Gagnon — APPROVED** [review]
