### PR TITLE
Fix resource endpoints to end with slash

### LINKED ISSUE #21536: Azure AAD is not working for MySQL extension in Insiders latest release.
- Azure Data Studio Version: Insiders 1.41.0-insider (January 5 release)
- OS Version: Windows

Steps to Reproduce:

1.  Select Azure Active Directory Authentication type.
2.  Select Account and connect

Error:

image

Our package.json file with azureAuth option specified:

image
 
Our extension repo: https://github.com/microsoft/azuredatastudio-mysql

Note:

1. Azure AAD is working in stable release 1.40.2
 

Does this issue occur when all extensions are disabled?: Yes only MySQL extension is enabled

### PR DESCRIPTION
**Pull request by cheenamalhotra**
This PR fixes #21536

Resource endpoints are appended to scope when request is made to MSAL, therefore they need to end with slash (`/`)
This change is backwards compatible with ADAL.

### CODE REVIEW

File: extensions/azurecore/src/account-provider/providerSettings.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ const publicAzureSettings: ProviderSettings = {
 			},
 			graphResource: {
 				id: SettingIds.graph,
-				endpoint: 'https://graph.windows.net',
+				endpoint: 'https://graph.windows.net/',
```
Comment (alanrenmsft) [inline extensions/azurecore/src/account-provider/providerSettings.ts:42]: where do we build the URL, is it in the library that we don't have control over? if so, this looks good to me, otherwise I think we should just check and append the slash if necessary when building the url.

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 2]
```diff
@@ -323,16 +321,17 @@ export abstract class AzureAuth implements vscode.Disposable {
...
+		const endpoint = resource.endpoint;
 		let account: AccountInfo | null = await this.getAccountFromMsalCache(accountId);
 		if (!account) {
 			Logger.error('Error: Could not fetch account when acquiring token');
 			return null;
 		}
 		let newScope;
 		if (resource.azureResourceId === azdata.AzureResource.ResourceManagement) {
-			newScope = [`${resource?.endpoint}user_impersonation`];
+			newScope = [`${endpoint.endsWith('/') ? endpoint : endpoint + '/'}user_impersonation`];
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:332]: You could just do this on line 324 to save having to duplicate the call (and adding a comment about why this is necessary wouldn't hurt either)

**Review by alanrenmsft — APPROVED** [review]

File: extensions/azurecore/src/account-provider/auths/azureAuth.ts [hunk 3]
```diff
@@ -323,16 +321,19 @@ export abstract class AzureAuth implements vscode.Disposable {
...
 			Logger.error('Error: Could not fetch account when acquiring token');
 			return null;
 		}
 		let newScope;
 		if (resource.azureResourceId === azdata.AzureResource.ResourceManagement) {
-			newScope = [`${resource?.endpoint}user_impersonation`];
+			newScope = [`${endpoint}user_impersonation`];
 		} else {
-			newScope = [`${resource?.endpoint}.default`];
+			newScope = [`${endpoint}.default`];
```
Comment (Charles-Gagnon) [inline extensions/azurecore/src/account-provider/auths/azureAuth.ts:336]: So was looking at this thing and noticed that it says in some situations it needs to have a double slash - https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-acquire-token?tabs=dotnet#azure-ad-v10-resources

Is that not something we have to worry about for our stuff?

Comment (cheenamalhotra) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:336]: I'm not sure what would be a "resource that accepts a version 1.0 access token" since we fetch 2.0 access tokens with MSAL.

Comment (cheenamalhotra) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:336]: Understanding from [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/747#issuecomment-451047774), leads me to think this should not apply to us, since we fetch 2.0 access tokens. 
Also referenced: https://nicolgit.github.io/AzureAD-Endopoint-V1-vs-V2-comparison/

Comment (Charles-Gagnon) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:336]: Ah ok, so does MSAL always get v2.0 tokens? Or is that a configuration we have on our side to guarantee that?

Comment (cheenamalhotra) [reply extensions/azurecore/src/account-provider/auths/azureAuth.ts:336]: Yes, MSAL fetches from v2.0 endpoints only. Quoting from [Documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-overview#migrate-apps-that-use-adal-to-msal):

> Active Directory Authentication Library (ADAL) integrates with the Azure AD for developers (v1.0) endpoint, where MSAL integrates with the Microsoft identity platform. The v1.0 endpoint supports work accounts, but not personal accounts. The v2.0 endpoint is the unification of Microsoft personal accounts and work accounts into a single authentication system. Additionally, with MSAL you can also get authentications for Azure AD B2C.
