### PR TITLE
Show git status in projects tree

### LINKED ISSUE #13670: Projects in workspace should show relative path (relative to workspace file) as hover over text
Steps to Reproduce:

1. Open a workspace with multiple projects.
2. For hover text of each project, the information could be made more meaningful that just the name of the project.
image

Suggestion: Add relative path of project to the workspace file. It will be helpful in case same name projects are opened in a workspace.

### PR DESCRIPTION
**Pull request by kisantia**
This adds the git status of the files in the project to show in the project tree:
image

This PR also fixes #13670.
image

Right now, I have the project tree item showing the git status of the sqlproj file, but it can be changed to show the status of the folder. Depending on which one we decide to use, the tree node will show as modified in different scenarios:

Project tree node as sqlproj git status would change when:
- anything in the sqlproj file changes
-  db references are added/modified
-  a new file is added or deleted
- doesn't show when a file is in the project is modified

Project tree node as folder containing the project git status would change when:
- any file in the folder is changed
- a new file is added or deleted
- doesn't show when db references are updated
- doesn't show if something in the sqlproj file changes

Any preference on which one to go with?

### CODE REVIEW

**Comment by dzsquared** [comment]
> Any preference on which one to go with?

Project tree node as sqlproj git status - as the source control pane notification counter/icon will also serve as an overall notification for changes in the workspace as a whole, whereas the sqlproj file may have very specific changes.

**Review by alanrenmsft — APPROVED** [review]
so the magic here is to use full path? and git status will be automatically added?
regarding to your question, I would leave it to Drew to decide.

**Review by dzsquared — APPROVED** [review]

File: extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ export class FolderNode extends BaseProjectTreeItem {
 	}
 
 	public get treeItem(): vscode.TreeItem {
-		const folderItem = new vscode.TreeItem(this.uri, vscode.TreeItemCollapsibleState.Collapsed);
+		const folderItem = new vscode.TreeItem(this.fileSystemUri, vscode.TreeItemCollapsibleState.Collapsed);
```
Comment (SakshiS-harma) [inline extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts:32]: Just a question here: just updating the uri to fileSystemUri updates the git status. How?

**Review by SakshiS-harma — APPROVED** [review]

**Comment by kisantia** [comment]
@alanrenmsft yup the git status shows if the resourceUri of the vscode.TreeItem is set to the full path

File: extensions/sql-database-projects/src/test/projectTree.test.ts [hunk 2]
```diff
@@ -68,24 +68,24 @@ describe('Project Tree tests', function (): void {
 
 		const tree = new ProjectRootTreeItem(proj);
 		should(tree.children.map(x => x.uri.path)).deepEqual([
-			'/TestProj/Database References',
-			'/TestProj/duplicateFolder',
-			'/TestProj/someFolder',
-			'/TestProj/duplicate.sql']);
+			'/TestProj.sqlproj/Database References',
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/test/projectTree.test.ts:71]: This is not affecting the display name for projects right?

Comment (kisantia) [reply extensions/sql-database-projects/src/test/projectTree.test.ts:71]: nope, I added a line to set the label of the project node to the project name without the .sqlproj extension
https://github.com/microsoft/azuredatastudio/blob/67b2505b48681b8314e65ebbc817a8c5ec2914c8/extensions/sql-database-projects/src/models/tree/projectTreeItem.ts#L51

**Review by udeeshagautam — APPROVED** [review]

File: extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts (hunk 1 above)
Comment (Benjin) [reply extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts:32]: +1 to this question.  I'm guessing VS Code automatically checks git status for tree entries that have filesystem URIs (rather than just arbitrary paths), which would be some unexpected but welcome magic.

**Review by Benjin — APPROVED** [review]

File: extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts (hunk 1 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/models/tree/fileFolderTreeItem.ts:32]: yup the git status shows if the resourceUri of the vscode.TreeItem is set to the full path
