### PR TITLE
Fix find highlight on cell edits

### LINKED ISSUE #21637: The Find feature is returning text that have been deleted from the text cell
I have a text cell in my notebook, trying to remove the text `Preview` from it, 
image

after removing the `Preview` text, I am still able to find it using the Find feature.

image

This is not a regression, I tried on 1.40.2, the issue also exists there.

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #21637 

Issue: When ever cell source is edited, the find is triggered. In the wysiwyg mode, we use rendered text as source and the rendered text isn't updated on edits and still has the original source before edit. 
Fix: created a onCellPreviewUpdated event and every time the preview is updated the event is fired. On the event we trigger the find again.

### CODE REVIEW

**Comment by lucyzhang929** [comment]
@MaddyDev It seems like the issue still exists in split/markdown mode:
### Searching for "find"
Screenshot 2023-03-01 at 2 33 08 PM


### After deleting "find":
Screenshot 2023-03-01 at 2 33 21 PM


### Exit edit mode:
Screenshot 2023-03-01 at 2 33 27 PM

File: src/sql/workbench/contrib/notebook/browser/notebookEditor.ts [hunk 1]
```diff
@@ -374,15 +371,11 @@ export class NotebookEditor extends EditorPane implements IFindNotebookControlle
...
-					this._onFindStateChange(changeEvent).catch(onUnexpectedError);
-				}
-			}));
 			this._register(cell.onCurrentEditModeChanged(editMode => {
-				if (editMode !== CellEditModes.WYSIWYG) {
-					this._onFindStateChange(changeEvent).catch(onUnexpectedError);
-				}
+				this._onFindStateChange(changeEvent).catch(onUnexpectedError);
+			}));
+			this._register(cell.onCellPreviewUpdated(previewUpdated => {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebookEditor.ts:377]: Do one of these end up being fired when cell edit mode is changed as well? (just trying to figure out why the onCellEditModeChanged handler was removed)

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 2]
```diff
@@ -337,6 +337,7 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 				if (this.isFindActive) {
 					this.addDecoration();
 				}
+				this.cellModel.cellPreviewUpdated.fire(true);
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:340]: If we're only ever returning true then just make the Event an `Event<void>` - the boolean doesn't provide anything useful.

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 3]
```diff
@@ -232,7 +232,9 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 				let cells = [...new Set(oldDecorationsRange.map(item => item.cell))].filter(c => c.cellType === 'markdown');
 				cells.forEach(cell => {
 					let cellOldDecorations = oldDecorationsRange.filter(r => r.cell === cell);
-					let cellEditor = this.cellEditors.find(c => c.cellGuid() === cell.cellGuid);
+					// In split mode we have code and text cells with the same Guid,
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:235]: Is there not a way to use the cellType? `hasEditor` is kind of a weird way to go about checking if it's a text cell.

File: src/sql/workbench/contrib/notebook/browser/notebookEditor.ts (hunk 1 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/notebookEditor.ts:377]: Yes edit mode sets the mode and in turn fires the onCellEditModeChanged so it find is being called twice. And when we're coming out of edit mode, updatePreview is called which fires the onCellPreviewUpdated that I added.

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts (hunk 3 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/notebook/browser/notebook.component.ts:235]: Sounds good, thanks.

**Review by lucyzhang929 — APPROVED** [review]

**Comment by VasuBhog** [comment]
Do we have an updated ADO task or new tasks for our release notebook testing in regards to find in a notebook? @MaddyDev can you please update when you get a chance?

**Review by VasuBhog — APPROVED** [review]

**Comment by MaddyDev** [comment]
> Do we have an updated ADO task or new tasks for our release notebook testing in regards to find in a notebook? @MaddyDev can you please update when you get a chance?

We do have one task for [Find in a notebook](https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_workitems/edit/10171) I'll update that for testing more scenarios.

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 4]
```diff
@@ -232,7 +232,9 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
...
+					// we need to find the text component editor => c.hasEditor() filters that.
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:236]: Update comment - and it would be good for all these checks to have a comment explaining why you're even doing the `getEditor()` check

File: src/sql/workbench/contrib/notebook/browser/notebook.component.ts [hunk 5]
```diff
@@ -254,7 +256,9 @@ export class NotebookComponent extends AngularDisposable implements OnInit, OnDe
 				let cells = [...new Set(newDecorationsRange.map(item => item.cell))].filter(c => c.cellType === 'markdown');
 				cells.forEach(cell => {
 					let cellNewDecorations = newDecorationsRange.filter(r => r.cell === cell);
-					let cellEditor = this.cellEditors.find(c => c.cellGuid() === cell.cellGuid);
+					// In split mode we have code and text cells with the same Guid,
+					// we need to find the text component editor => c.hasEditor() filters that.
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/notebook.component.ts:260]: Same as above, update/fix comment

**Review by Charles-Gagnon — APPROVED** [review]
