### PR TITLE
Fixing smattering of issues regarding updating projects for cross-plat

### LINKED ISSUE #22567: Prompt to update .sqlproj for ADS compatibility goes away after ~15 seconds
Split from #22528

When you open a project created in SSDT that hasn't been updated for ADS compatibility yet, the user is asked if they want to update their references and targets.  If the user selects nothing, the toast notification excuses itself to the alert button in the tray.  This is kinda hidden, and confusing to the user.

### LINKED ISSUE #22569: Not selecting a response when prompted to update .sqlproj for ADS compat blocks loading of projects/tree
Split from #22528

This is especially confusing if you hit #22567.

### LINKED ISSUE #22570: ADS should check for cross-plat compatibility before building/publish/schema compare
Split from #22528

When a user opens a project that isn't compatible with ADS/NetCore, they're prompted to update it.  If they reject this prompt, they can still proceed with editing their project.  However, when they go to use any action that involves building (publish, schema compare, update from existing), this compat state needs to be checked again.

### PR DESCRIPTION
**Pull request by Benjin**
Fixes #22569
Fixes #22570
Fixes #22567

### CODE REVIEW

File: extensions/sql-database-projects/src/models/project.ts [hunk 1]
```diff
@@ -158,15 +158,39 @@ export class Project implements ISqlProject {
...
+	 * @param project
+	 * @param blockingPrompt whether to block the thread until the user updates, or to fire and forget
+	 * @returns true if the project is updated after return, false if the user rejected the prompt
+	 */
+	public static async checkPromptCrossPlatStatus(project: Project, blockingPrompt: boolean): Promise<boolean> {
+		if (project.isCrossPlatformCompatible) {
+			return true;
+		}
+
+		if (blockingPrompt) {
```
Comment (kisantia) [inline extensions/sql-database-projects/src/models/project.ts:179]: if it's a blocking prompt, should it be a modal dialog so people don't miss it?

**Review by kisantia — APPROVED** [review]

File: extensions/sql-database-projects/src/models/project.ts (hunk 1 above)
Comment (Benjin) [reply extensions/sql-database-projects/src/models/project.ts:179]: Yeah, good call

Comment (Benjin) [reply extensions/sql-database-projects/src/models/project.ts:179]: I'm going to check in with the modal, but I figured I'd show what both look like in case we decide to change it later.
