### PR TITLE
Make connectionProfileGroup support undefined values

### LINKED ISSUE #9081: Show Active Connections is Non-Functional when > 0 Active Connections Exist
- Connect to a server in OE
- Click "Show Active Connections" action in the servers viewlet
- No connections will show up in the servers viewlet; action still says "Show Active Connections":

image

User is now stuck in this state until restarting ADS

### LINKED ISSUE #9086: Show Active Connections hides Server Groups
- Azure Data Studio Version: `1.15.0` - This is a regression from `1.14.1`

Steps to Reproduce:

1. Add a connection into a Server Group and connect to it
2. Click the "Show Active Connections" button

Expected: The connection is shown 

Actual: The connection is not shown

*In 1.14.1 the filtered view correctly looks like this*
Screen Shot 2020-02-07 at 1 13 21 AM

*In 1.15.0 the server group is missing from the filtered view*
Screen Shot 2020-02-07 at 1 13 27 AM

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #9086 and fixes #9081

Same basic fix as #9099 but I prefer fixing it this way (plus added tests)

Tests should really be added for the filtering methods as well but that isn't set up to be easily testable so I went with the minimum for now and will look into beefing the other testing up later.

### CODE REVIEW

File: src/sql/platform/connection/common/connectionProfileGroup.ts [hunk 1]
```diff
@@ -75,8 +75,24 @@ export class ConnectionProfileGroup extends Disposable implements IConnectionPro
 		this._isRenamed = val;
 	}
 
+	public get children(): ConnectionProfileGroup[] {
```
Comment (Charles-Gagnon) [inline src/sql/platform/connection/common/connectionProfileGroup.ts]: As a side note - I also plan on coming back and looking into changing this name. It has two meanings for this class - children in this context are just the child groups but hasChildren/getChildren also includes the connections. So really this property should be called childGroups or something (like I named the private vars).

But as I'm thinking this is a candidate for porting to 1.15 release I wanted to minimize changes here so kept it as-is.
