### PR TITLE
Fix toolbar overflow focus not always going to first element in overflow

### LINKED ISSUE #10244: overflow focus isn't always the first element
The focus of the toolbar overflow should be the first item when opened. Right now the focus is only getting set to the correct element when there aren't any separators left in the toolbar

image

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #10244. When the overflow menu opens, the focus should be set to the first item in the overflow. This wasn't happening correctly because the separators were being counted when calculating the index, but when focus is being set, only focusable items are considered. 

old:
overflowFocus

fixed:
overflowFocusFix

### CODE REVIEW

**Comment by chlafreniere** [comment]
How can we write tests for this 😄

File: src/sql/base/browser/ui/taskbar/overflowActionbar.ts [hunk 1]
```diff
@@ -188,12 +194,25 @@ export class OverflowActionBar extends ActionBar {
...
+			// separators aren't focusable so we don't want to include them when calculating the focused item index
+			this._focusedItem = this._actionsList.childElementCount - this.getActionListSeparatorCount();
 			this.updateFocus();
 		}
 		DOM.EventHelper.stop(event, true);
 	}
 
+	private getActionListSeparatorCount(): number {
+		let count = 0;
+		for (let i = 0; i < this._actionsList.children.length; i++) {
```
Comment (Charles-Gagnon) [inline src/sql/base/browser/ui/taskbar/overflowActionbar.ts:207]: This could be simplified 

`return this._actionsList.children.filter(c => c.className.includes('taskbarSeparator')).length;`
