### PR TITLE
fix search action

### LINKED ISSUE #14630: Book search action doesn't work
Stable 1.26 & main

1. Open book in Notebook view
2. Click on magnifying glass next to book item
3. Enter search term in search box

Expected : Search completes successfully
Actual : Get error about a missing path

image

The issue seems to be the search path isn't constructed correctly - it's searching `c:\Users\chgagnon\Desktop\sqlserver2019\troubleshooters\**\*.md,c:\Users\chgagnon\Desktop\sqlserver2019\troubleshooters\**\*.ipynb` but the `troubleshooters` folder is nested in the `content` folder. If I change the search path to `c:\Users\chgagnon\Desktop\sqlserver2019\content\troubleshooters\**\*.md,c:\Users\chgagnon\Desktop\sqlserver2019\content\troubleshooters\**\*.ipynb` then it works as expected

### PR DESCRIPTION
**Pull request by barbaravaldez**
This PR fixes #14630

### CODE REVIEW

File: extensions/notebook/src/book/bookTreeView.ts [hunk 1]
```diff
@@ -498,7 +498,7 @@ export class BookTreeViewProvider implements vscode.TreeDataProvider<BookTreeIte
 	public async searchJupyterBooks(treeItem?: BookTreeItem): Promise<void> {
 		let folderToSearch: string;
 		if (treeItem && treeItem.sections !== undefined) {
-			folderToSearch = treeItem.uri ? getContentPath(treeItem.version, treeItem.book.root, path.dirname(treeItem.uri)) : getContentPath(treeItem.version, treeItem.book.root, '');
+			folderToSearch = treeItem.uri ? getContentPath(treeItem.book.version, treeItem.book.root, path.dirname(treeItem.uri)) : getContentPath(treeItem.book.version, treeItem.book.root, '');
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTreeView.ts:501]: So it seems like we have an issue here then - since BookTreeItem sets its version to book.version when it's created if it's a book. 

https://github.com/microsoft/azuredatastudio/blob/main/extensions/notebook/src/book/bookTreeItem.ts#L55

So is the issue then that this is broke for any non-book items? (since it looks like we never set the version there)

Does it even make sense for each BookTreeItem to have its own version vs just always using the book.version?

**Review by lucyzhang929 — APPROVED** [review]
Tested searching in books, sections, and nested sections - looks good! But I agree with @Charles-Gagnon, might be a good idea to always use book.version since BookTreeItem can also be a standalone notebook without a version.

File: extensions/notebook/src/book/bookTocManager.ts [hunk 2]
```diff
@@ -349,9 +349,9 @@ export class BookTocManager implements IBookTocManager {
 			this.cleanUp(path.dirname(section.book.contentPath));
 		}
 
-		if (book.version === BookVersion.v1) {
+		if (book.book.version === BookVersion.v1) {
```
Comment (Charles-Gagnon) [inline extensions/notebook/src/book/bookTocManager.ts:352]: Would suggest renaming the book param to `bookItem` to make it clearer what it is - book.book doesn't initially seem to make a lot of sense

**Review by Charles-Gagnon — APPROVED** [review]
