### PR TITLE
Messages panel wordwrap

### LINKED ISSUE #10956: Cannot see long error message because horizontal scroll is missing
- Azure Data Studio Version: 1.19.0

I have executed some SQL query that has longer error message. In the **Messages**  tab is shown error message but since it is long I cannot see the end of the message. There is no horizontal scroll.

I need to copy entire error message and paste it in some editor to see what is the issue.

Steps to Reproduce:

1. Execute some statement that will cause long error message (see example below). 

image

### PR DESCRIPTION
**Pull request by anthonydresser**
This PR fixes #10956

This PR implements a custom setting for adding word wrap or horizontal scrolling for the messages panel.

### CODE REVIEW

File: src/sql/workbench/contrib/query/browser/query.contribution.ts [hunk 1]
```diff
@@ -305,228 +305,104 @@ KeybindingsRegistry.registerCommandAndKeybindingRule({
...
-		'type': 'boolean',
-		'description': localize('showConnectionInfoInTitle', "Controls whether to show the connection info for a tab in the title."),
-		'default': true
-	},
-	'sql.promptToSaveGeneratedFiles': {
-		'type': 'boolean',
-		'default': false,
-		'description': localize('sql.promptToSaveGeneratedFiles', "Prompt to save generated SQL files")
-	},
-	'mssql.intelliSense.enableIntelliSense': {
```
Comment (anthonydresser) [inline src/sql/workbench/contrib/query/browser/query.contribution.ts:391]: I moved these settings to the mssql extension, since it makes more sense for it to be there. There shouldn't be any functional changes.

File: src/sql/workbench/contrib/query/browser/query.contribution.ts [hunk 2]
```diff
@@ -305,228 +305,104 @@ KeybindingsRegistry.registerCommandAndKeybindingRule({
...
+			'type': 'string',
+			'description': localize('queryEditor.results.saveAsCsv.encoding', "File encoding used when saving results as CSV"),
+			'default': 'utf-8'
+		},
+		'queryEditor.results.saveAsXml.formatted': {
+			'type': 'string',
+			'description': localize('queryEditor.results.saveAsXml.formatted', "When true, XML output will be formatted when saving results as XML"),
+			'default': true
+		},
+		'queryEditor.results.saveAsXml.encoding': {
```
Comment (anthonydresser) [inline src/sql/workbench/contrib/query/browser/query.contribution.ts:349]: I changes the id of these settings. This does have a functional change in if a user has already set this setting manually, it won't pick up those settings and the user will have to reset the setting. I think we can get around this by documenting these changes. but I think its good in the long run to standardize these settings and make the naming more generic.

File: extensions/mssql/package.json [hunk 3]
```diff
@@ -198,9 +198,157 @@
...
+          "type": "boolean",
+          "default": true,
+          "description": "%mssql.query.ansiNulls%"
+        },
+        "mssql.query.alwaysEncryptedParameterization": {
+          "type": "boolean",
+          "default": false,
+          "description": "%mssql.query.alwaysEncryptedParameterization%"
+        },
+        "mssql.ignorePlatformWarning": {
```
Comment (anthonydresser) [inline extensions/mssql/package.json:349]: I changed the name of this setting to make it fall in line with the rest of the settings.

File: src/sql/workbench/contrib/query/browser/query.contribution.ts (hunk 2 above)
Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/query/browser/query.contribution.ts:348]: What if we had a check happen at startup that looked for the old values and if they exist updated them to the new ones? We've done a similar thing in SSMS before with breaking config changes and that seems to work pretty well.

Comment (anthonydresser) [reply src/sql/workbench/contrib/query/browser/query.contribution.ts:348]: Certainly an option.

**Comment by anthonydresser** [comment]
I can make a simpler fix for a hotfix.

**Comment by anthonydresser** [comment]
@Charles-Gagnon @kburtram I added a initial configuration upgrader implementation https://github.com/microsoft/azuredatastudio/pull/10970/files#diff-1e8d55d2c8a5a77fd983347ccfb30ba1R29 I'm working on writing tests for it, but figured I'd get some eyes on it while I do that.

File: src/sql/workbench/contrib/configuration/common/configurationUpgrader.ts [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+	private readonly globalStorage: { [key: string]: boolean };
+	private readonly workspaceStorage: { [key: string]: boolean };
+
+	constructor(
+		@IStorageService storageService: IStorageService,
+		@IConfigurationService private readonly configurationService: IConfigurationService
+	) {
+		this.globalStorage = JSON.parse(storageService.get(ConfigurationUpgraderContribution.STORAGE_KEY, StorageScope.GLOBAL, '{}'));
+		this.workspaceStorage = JSON.parse(storageService.get(ConfigurationUpgraderContribution.STORAGE_KEY, StorageScope.WORKSPACE, '{}'));
+		this.processSettings();
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/configuration/common/configurationUpgrader.ts:41]: Don't you need the store calls in a .then?

**Comment by anthonydresser** [comment]
How long would we want to keep these overrides in place? I supposed we could add telemetry to see how often these are being upgrading and determine when to remove them based on that. @Charles-Gagnon

**Comment by Charles-Gagnon** [comment]
We definitely could - but is there a problem with just leaving these checks there indefinitely? I imagine we're not going to be utilizing this very often so it shouldn't be adding tons of overhead or anything.

File: src/sql/workbench/contrib/configuration/common/configurationUpgrader.ts [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+	'sql.copyIncludeHeaders': 'queryEditor.results.copyIncludeHeaders', // June 19, 2020
+	'sql.copyRemoveNewLine': 'queryEditor.results.copyRemoveNewLine', // June 19, 2020
+	'sql.showBatchTime': 'queryEditor.messages.showBatchTime', // June 19, 2020
+	'sql.chart.defaultChartType': 'queryEditor.chart.defaultChartType', // June 19, 2020
+	'sql.tabColorMode': 'queryEditor.tabColorMode', // June 19, 2020
+	'sql.showConnectionInfoInTitle': 'queryEditor.showConnectionInfoInTitle', // June 19, 2020
+	'sql.promptToSaveGeneratedFiles': 'queryEditor.promptToSaveGeneratedFiles', // June 19, 2020
+});
+
+export class ConfigurationUpgraderContribution implements IWorkbenchContribution {
```
Comment (aaomidi) [inline src/sql/workbench/contrib/configuration/common/configurationUpgrader.ts:29]: I'd maybe allow a way to convert configuration values as well. Like if we know something has changed to a known second value.
