### PR TITLE
Fix #5809: Data-tier wizard "Source Server" shouldn't show database name

### LINKED ISSUE #5809: Data-tier wizard "Source Server" shouldn't show database name
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run Data-Tier Application Wizard

Expected: "Source Server" should show server name without database since there is already a separate "Source Database" field.

On another note, it looks like "Source Database" isn't a required field, but there isn't any way not to specify a "Source Database" as far as I can tell.

image

### PR DESCRIPTION
**Pull request by kisantia**
Fixes #5809. Removes database name from server dropdowns and adds the required asterisk to the database dropdown titles.

image

### CODE REVIEW

File: extensions/dacpac/src/wizard/api/basePage.ts [hunk 1]
```diff
@@ -67,19 +67,14 @@ export abstract class BasePage {
...
-			if (!db) {
-				db = localize('basePage.defaultDb', '<default>');
-			}
-
 			if (!usr) {
 				usr = localize('basePage.defaultUser', 'default');
 			}
 
-			let finalName = `${srv}, ${db} (${usr})`;
+			let finalName = `${srv} (${usr})`;
```
Comment (kburtram) [inline extensions/dacpac/src/wizard/api/basePage.ts]: I think we have the same bug in the flat file import wizards.  it might be a quick-win to resolve this same bug in there as well.

Comment (kisantia) [reply extensions/dacpac/src/wizard/api/basePage.ts]: sure I removed it there too. @kenvanhyning just fyi I removed the database name in the server dropdown in the flat file import wizard
image
