### PR TITLE
Don't show links for BDC logs if none available

### LINKED ISSUE #7285: [ADS] ADS LOGS url (Kibana) not working for Metrics and Logs Pods
Issue Type: <b>Bug</b>

· In ADS under Big data cluster overview -> Cluster Details-> Control, the LOGS url for metricsdc, metricsui, metricsdb, logsui, logsdb and mgmtproxy takes us to "file:///C:/Program%20Files/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/code/electron-browser/workbench/workbench.html".
· The Kibana logs are not available for these PODS which I assume is expected considering we do not have fluentbit running in those PODs. But it would be better to either disable this option for these PODs or give a message stating the logs for these PODS are not collected by design. Or is there a plan to include any logs for this PODs?
		
	
image
	 
· I am using latest ADS version:
		
image

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (a584aca96997a18ecedee73a575536332e542718, 2019-09-19T07:58:50.448Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (18.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #7285

We won't always have logs available for instances so show N/A if none are available.

Also did some clean up of the CSS Styles - I need to go through and do a full pass since we still have a lot of duplicated styles around but I wanted to keep this PR focused.

I also will be going through and adding more null/undefined checks for the values returned for the instance status. We shouldn't be assuming the status is going to always come back with the expected values. Again - going to do that in a separate PR to keep this one focused.

### CODE REVIEW

File: extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts [hunk 1]
```diff
@@ -197,10 +198,23 @@ function createMetricsAndLogsRow(modelBuilder: azdata.ModelBuilder, instanceStat
...
-	metricsAndLogsRow.addItem(metricsCell, { CSSStyles: { 'width': `${metricsAndLogsMetricsColumnWidth}px`, 'min-width': `${metricsAndLogsMetricsColumnWidth}px` } });
-	const logsCell = modelBuilder.hyperlink().withProperties({ label: localize('bdc.dashboard.viewHyperlink', "View"), url: instanceStatus.dashboards.logsUrl, CSSStyles: { 'margin-block-start': '0px', 'margin-block-end': '0px', 'user-select': 'text', 'color': '#0078d4', 'text-decoration': 'underline' } }).component();
-	metricsAndLogsRow.addItem(logsCell, { CSSStyles: { 'width': `${metricsAndLogsLogsColumnWidth}px`, 'min-width': `${metricsAndLogsLogsColumnWidth}px` } });
+
+	// Not all instances have all logs available - in that case just display N/A instead of a link
+	if (isNullOrUndefined(instanceStatus.dashboards) || isNullOrUndefined(instanceStatus.dashboards.nodeMetricsUrl)) {
+		const metricsCell = modelBuilder.text().withProperties({ value: localize('bdc.dashboard.notAvailable', "N/A"), CSSStyles: { 'margin-block-start': '0px', 'margin-block-end': '0px' } }).component();
```
Comment (kevcunnane) [inline extensions/big-data-cluster/src/bigDataCluster/dialog/bdcDashboardResourceStatusPage.ts]: We're meant to only define the localized string once. Seems like we share it in these cases. Might be easiest just to put in its own function and pass in the property to check (`instanceStatus.dashboards.nodeMetricsUrl` or `instanceStatus.dashboards.logsUrl`) since all the rest is identical.
