### PR TITLE
set aria label for agreement checkbox

### LINKED ISSUE #7597: A11y_AzureDataStudio_Selectthedeploymentoption_AI4D:Name property does not exist for "I accept"check box
GitHubTags: #SQL Azure Data Studio;#A11y_AzureDataStudio;#A11yMAS;#A11yTCS;#WCAG1.3.1,#WCAG4.1.2;#WCAG4.2.1;#DesktopApp;#NVDA;#AI4D#Win32;
**Environment Details:**
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 32df727ff9fe68421b004bf270cd509e4c5de165
Date: 2019-10-08T19:18:43.743Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
**Additional Details:**
AI4D

**Steps to Reproduce :**
1.Install /Launch the application Azure data studio.
2.Navigate to connections and click on more action button.
3.Select “Deploy SQL Server big data cluster” from more action drop down.
4.Click on “Deploy SQL Server big data cluster” .
5.Open AI4D and hover on the I accept check box.
**Actual:**
When we hover on the check box we found name property does not exist for the check box and also it is not announced by the NVDA.
**Expected**:
Name property should exist for the check box.
**User Impact:**
Screen reader User will not able to understand for what purpose the check box is there.
**Attachment for Reference:**
[A11y_AsureDataStudio_Selectthedeploymentoption_AI4D.pptx](https://github.com/microsoft/azuredatastudio/files/3707366/A11y_AsureDataStudio_Selectthedeploymentoption_AI4D.pptx)
Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by alanrenmsft**
set aria label for the agreement check
This PR fixes #7597
Screen Shot 2019-11-22 at 11 31 23 AM

### CODE REVIEW

File: extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts [hunk 1]
```diff
@@ -297,6 +299,16 @@ export class ResourceTypePickerDialog extends DialogBase {
 		return createFlexContainer(this._view, [checkbox, text]);
 	}
 
+	private getAgreementDisplayText(agreementInfo: AgreementInfo): string {
+		// the agreement template will have {index} as placeholder for hyperlinks
+		// this method will get the display text after replacing the placeholders
+		let text = agreementInfo.template;
```
Comment (Charles-Gagnon) [inline extensions/resource-deployment/src/ui/resourceTypePickerDialog.ts]: This is fine - but in general for this kind of thing you could also use the aria-labeledby attribute to reduce the amount of duplication of logic
