### PR TITLE
Fix driverlog uri in output

### LINKED ISSUE #4813: Spark Notebook : Driver link click does not work
Issue Type: <b>Bug</b>

run 1st cell of the spark notebook. It provide diagnostics links. One of the links is a driver link that ideally should take you to the spark driver logs. The link is non clickable. Does not work

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (3.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.11.0

</details>

### PR DESCRIPTION
**Pull request by YurongHe**
Fixed #4813
There are two issues:
1) getKnoxEndpoint provider match fails because it was lower case before, so it wouldn't get the correct endpoint.
2) driverLog uri match patter is changed.

### CODE REVIEW

File: src/sql/workbench/parts/notebook/models/cell.ts [hunk 1]
```diff
@@ -393,9 +396,10 @@ export class CellModel implements ICellModel {
 					if (model.activeConnection) {
 						let endpoint = this.getKnoxEndpoint(model.activeConnection);
 						let host = endpoint && endpoint.ipAddress ? endpoint.ipAddress : model.activeConnection.serverName;
+						let port = endpoint && endpoint.port ? ':' + endpoint.port.toString() : defaultPort;
 						let html = result.data['text/html'];
-						html = this.rewriteUrlUsingRegex(/(https?:\/\/mssql-master.*\/proxy)(.*)/g, html, host);
-						html = this.rewriteUrlUsingRegex(/(https?:\/\/master.*master-svc.*\/proxy)(.*)/g, html, host);
```
Comment (chlafreniere) [inline src/sql/workbench/parts/notebook/models/cell.ts]: please be careful here. we had 2 for backwards compatibility (CTP 2.4 and older). Would rather add to this list instead of replace here.
