### PR TITLE
Fixing the height of the query plan

### LINKED ISSUE #18382: the query plan pane is resizable even though there is only one plan.
image

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #18382 
Before:
image
After:
image
image
image

### CODE REVIEW

File: src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts [hunk 1]
```diff
@@ -116,6 +116,14 @@ export class QueryPlan2View implements IPanelView {
 				this._qps.push(qp2);
 				this._graphs.push(g);
 				this.updateRelativeCosts();
+
+				// If there is only one query plan, set the height of the query plan to 100%
+				// Later on, if other plans are added we decrease the height to 500px
+				if (this._qps.length === 1) {
+					this._qps[0].container.style.height = '100%';
+				} else if (this._qps.length > 1) {
+					this._qps[0].container.style.height = '500px';
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:125]: Where is the 500px value coming from? And why are you only setting the height of the first to 500px when there's more than one?

I'm not sure that this will look nice in all situations too - what happens if the user expands the panel to be >1000px high and has two plans? Will you end up with a gap again? What might be better is to look into making each plan take up an equal % of the total height, with a minimum height of 500px or whatever seems reasonable so that they can expand to fill the space as needed.

File: src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts [hunk 2]
```diff
@@ -194,7 +191,12 @@ export class QueryPlan2 implements ISashLayoutProvider {
 			if (newHeight < 200) {
 				return;
 			}
-			this._container.style.height = `${newHeight}px`;
+			/**
+			 * Since the parent container is flex, we will have
+			 * to change the flex-basis property to change the height.
+			 */
+			this._container.style.minHeight = '200px';
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:198]: This seems like it should belong in the css

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts (hunk 2 above)
Comment (aasimkhan30) [reply src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:198]: This overrides CSS's min-width. Intially, the min-width is set to 500px. After resizing, the min-width is updated to 200px.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:198]: I'm not really understanding what this is doing then - why 200px? And why only do this after resizing?

Comment (aasimkhan30) [reply src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:198]: Since we are trying to equally divide the tab container into query plans, we must set the min-height so that query plans do not become too short. It prevents situations like this. (when there are many query plans, they become too short)
image

We fix this issue by changing the min-height to 500px
image


Now, if the user wants to manually drag and resize the queryplans, the min-height of 500px will prevent them from doing so. Therefore, as soon as the user drags the sash, we change the min-height from 500px to 200px. 
image

Comment (aasimkhan30) [reply src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:198]: 200px is an arbitrary number. There is no good reason behind it other than the query plan starts looking bad when we go below that.

Comment (Charles-Gagnon) [reply src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:198]: But why not just have a min-height of 200px to start with then? Or just set the initial height to 500px if you want to start off with it being bigger but allow them to make it smaller.

Comment (aasimkhan30) [reply src/sql/workbench/contrib/queryplan2/browser/queryPlan.ts:198]: The problem I was there was setting the initial height to 500px will prevent it from taking up the entire space.
