### PR TITLE
fix json cell handling in query editor

### LINKED ISSUE #313: Support for large field viewing, E. g. JSON
- SQL Operations Studio Version:
0.23
Steps to Reproduce:
Query any large field

We started taking advantage of the new JSON support in SQL server 2016. Problem is that in one field there could be a lot of data and there is no good way to view it aside for saving it to a file or copy and paste to a text editor. It would be nice if there would be a built in viewer for JSON. thanks.

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #313

1. handle line breaks in the json string
2. use pointer cursor for link cells
3. inherit the whitespace setting from parent cell for link cell to avoid showing things in multiple lines.

Before
image

After
image

### CODE REVIEW

**Review by aasimkhan30 — APPROVED** [review]

File: src/sql/workbench/contrib/query/browser/gridPanel.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ const MIN_GRID_HEIGHT = (MIN_GRID_HEIGHT_ROWS * ROW_HEIGHT) + HEADER_HEIGHT + ES
 // performant than trying to parse the string to object.
 // Regex explaination: after removing the trailing whitespaces, the string must start with '[' (to support arrays)
 // or '{'. And there must be a '}' to match the '{'.
```
Comment (caohai) [inline src/sql/workbench/contrib/query/browser/gridPanel.ts:79]: update the regex explanation in comment as well?

**Review by caohai — APPROVED** [review]
