### PR TITLE
Keybinding for Show SQL Pane

### LINKED ISSUE #3763: Create a Keybinding for "Show SQL Pane" when Editing Data
- Azure Data Studio Version:  1.3.9

Steps to Reproduce:

I can't find a way to create a Keybinding to show or hide the "SQL Pane" when editing data.
In SSMS this is Crtl + " but can't seem to find it for Data Studio.

Kind Regards,

Tim

### PR DESCRIPTION
**Pull request by smartguest**
Added a keybinding in the edit data contribution file that toggles show SQL pane.
This PR fixes #3763

### CODE REVIEW

**Comment by smartguest** [comment]
Option to always show SQL Pane added as requested by gregveres in #3763

File: src/sql/workbench/contrib/editData/browser/editData.contribution.ts [hunk 1]
```diff
@@ -18,6 +24,20 @@ const editDataEditorDescriptor = new EditorDescriptor(
 	'EditData'
 );
 
+const configurationRegistry = <IConfigurationRegistry>Registry.as(ConfigExtensions.Configuration);
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editData.contribution.ts:27]: why are we adding this setting?  i.e. has this been requested by a customer?

File: src/sql/workbench/contrib/editData/browser/editData.contribution.ts [hunk 2]
```diff
@@ -18,6 +24,20 @@ const editDataEditorDescriptor = new EditorDescriptor(
...
+configurationRegistry.registerConfiguration({
+	'id': 'showEditDataSqlPaneOnStartup',
+	'title': nls.localize('showEditDataSqlPaneOnStartup', 'Show Edit Data SQL pane on startup'),
+	'type': 'object',
+	'properties': {
+		'editor.showEditDataSqlPaneOnStartup': {
+			'type': 'boolean',
+			'default': true,
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editData.contribution.ts:35]: should the default be `false` to main compatibility with current behavior?

File: src/sql/workbench/contrib/editData/browser/editData.contribution.ts [hunk 3]
```diff
@@ -30,3 +50,17 @@ const editDataResultsEditorDescriptor = new EditorDescriptor(
 
 Registry.as<IEditorRegistry>(Extensions.Editors)
 	.registerEditor(editDataResultsEditorDescriptor, [new SyncDescriptor(EditDataResultsInput)]);
+
+// Keybinding for toggling the query pane
+KeybindingsRegistry.registerCommandAndKeybindingRule({
+	id: editDataActions.ShowQueryPaneAction.ID,
+	weight: KeybindingWeight.EditorContrib,
+	when: undefined,
+	primary: KeyMod.CtrlCmd | KeyCode.US_QUOTE,
```
Comment (kburtram) [inline src/sql/workbench/contrib/editData/browser/editData.contribution.ts:59]: is this the keybinding currently used to show the terminal?  I suggest we leave the keybinding unassigned by default and let user configure it themselves since we are running out of available keyboard shortcuts.

File: src/sql/workbench/contrib/editData/browser/editData.contribution.ts (hunk 1 above)
Comment (smartguest) [reply src/sql/workbench/contrib/editData/browser/editData.contribution.ts:27]: Yes, a customer requested this feature should be added
