### PR TITLE
Fix #4976 AAD Login will not work from Azure

### LINKED ISSUE #4976: AAD Login will not work from Azure section
- Sign into Azure and browse to a server where you're added as an AAD admin
- Expand and choose AAD auth in the connection dialog
- Click to connect.

Expected:
- Connection is successful
Actual:
- Get `Login failed for user '.'`.

image

Note: If I do the same thing fro the servers view (manually entering server name) it works fine so long as firewall is opened up.

### PR DESCRIPTION
**Pull request by kevcunnane**
- Azure token wasn't being copied into profile so expand didn't work, it spun forever
- Fixed this by saving in password/token after the connection profile copy, & refactored to be cleaner
- We should ideally ensure session notifies resolves even on fail so if there's a different error it'll break, not spin forever. Punting this part of the fix for now
- Also doesn't solve issue where we always try to connect even if user + password combo isn't saved. Will investigate / work in a separate PR on this.

### CODE REVIEW

File: src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts [hunk 1]
```diff
@@ -44,45 +45,56 @@ export class OEShimService extends Disposable implements IOEShimService {
...
+		return sessionId;
+	}
+
+	private async connectOrPrompt(connProfile: ConnectionProfile): Promise<ConnectionProfile> {
+		connProfile = await new Promise(async (resolve, reject) => {
+			await this.cm.connect(connProfile, undefined, { showConnectionDialogOnError: true, showFirewallRuleOnError: true, saveTheConnection: false, showDashboard: false, params: undefined }, {
+				onConnectSuccess: async (e, profile) => {
+					let existingConnection = this.cm.findExistingConnection(profile);
+					connProfile = new ConnectionProfile(this.capabilities, existingConnection);
+					connProfile = <ConnectionProfile>await this.cm.addSavedPassword(connProfile);
```
Comment (anthonydresser) [inline src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts]: Is this the only actual change? (Looks like a bunch of code moving around).

Comment (Charles-Gagnon) [reply src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts]: How is this actually fixing the issue? We were calling addSavedPassword before, just directly as a param to the ConnectionProfile constructor, so I'm not sure how this is actually changing anything

---
In reply to: [289190793](https://github.com/microsoft/azuredatastudio/pull/5768#discussion_r289190793) [](ancestors = 289190793)

Comment (kevcunnane) [reply src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts]: You called addSavedPassword on the existing connection, then copied it to connProfile which caused it to be lost. Instead we copy to connProfile and addSavedPassword on that which adds back in the data needed.

Comment (kevcunnane) [reply src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts]: And yes - this is the primary fix. I think that moving to a consistent model of just using promises instead of having multiple different methods (Deferred) which aren't needed is a helpful improvement. It's strange to have a deferred in an async method

Comment (Charles-Gagnon) [reply src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts]: Ah, so yeah ConnectionProfile isn't copying over the password (or honestly most stuff like server, db, etc). Not what I'd expect from how it was called but yeah your fix makes sense.

**Comment by kburtram** [comment]
@kevcunnane @anthonydresser if this is targeted for June let's try to merge soon to include in today's testing.
