### PR TITLE
ML- Fixed the issue with wrong title in predict page

### LINKED ISSUE #10369: ML - Make predictions Display Name issue
- Azure Data Studio Version:
Version: 1.17.1 (user setup)
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-30T00:16:35.943Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Click on the the **_Make predictions_** button from ML Extension.
2. Choose the **_File upload_** method. Then, follow the instructions until **Step 3**.
Specify `mpdev` as **_Display Name_**. 
image
3. When you click Predict, you'll get a new SQL file that looks like this:
image
If you click run, it will show an error like below: 
_Msg 1038, Level 15, State 4, Line 16
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name._

The expected outcome of **_Make predictions_** is to display the following line
`    [p].[variable1] AS mpdev`
(instead of `[p].[mpdev] AS [variable1]`) 

I can repro using the **_File upload_** method, but not the **_Imported Model_**. I haven't tested the Azure ML one. 

Thanks.

### LINKED ISSUE #10466: ML - Make Predictions Step 2 title
- Azure Data Studio Version:
ML Extension 0.1.0

Steps to Reproduce:

1. Click on Make Predictions in ML Extension. Choose Imported model in Step 1.
image

2. Step 2 says "Upload model file".
image
3. This should say "Select imported model" instead of "Upload model file">

### PR DESCRIPTION
**Pull request by llali**
This PR fixes #10466

### CODE REVIEW

File: extensions/machine-learning/src/views/models/prediction/predictWizard.ts [hunk 1]
```diff
@@ -40,6 +40,7 @@ export class PredictWizard extends ModelViewBase {
 	 * Opens a dialog to manage packages used by notebooks.
 	 */
 	public async open(): Promise<void> {
+		this.modelSourceType = ModelSourceType.RegisteredModels;
```
Comment (udeeshagautam) [inline extensions/machine-learning/src/views/models/prediction/predictWizard.ts:43]: looks good but not sure how this fixes the script issue? was that because of missing t use registered models?

Comment (llali) [reply extensions/machine-learning/src/views/models/prediction/predictWizard.ts:43]: ah sorry wrong issue mapped.
