### PR TITLE
Fix for query select command text in manage tab for Kusto tables

### LINKED ISSUE #13295: Kusto Database Dashboard: Mismatch between "select top <n>" label and resulting query
Right click on a table that's listed in the database dashboard of a Kusto cluster, and you'll see an item labeled as "Select Top 1000":

image

- Select this item from the menu. The resulting query looks like the following:

image

Note the "take 10". These numbers should match (1000 vs. 10).

### PR DESCRIPTION
**Pull request by gupta1**
This PR fixes #13295

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

File: src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts [hunk 1]
```diff
@@ -256,7 +256,27 @@ MenuRegistry.appendMenuItem(MenuId.ExplorerWidgetContext, {
...
+				ItemContextKey.ItemType.isEqualTo('table')
+			)
+		),
+	order: 2
+});
+
+MenuRegistry.appendMenuItem(MenuId.ExplorerWidgetContext, {
+	command: {
+		id: commands.ExplorerScriptSelectAction.ID,
+		title: 'Take 10'
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts:273]: This should be localized (and like the above the action class itself should have a LABEL property with this value)

Comment (alanrenmsft) [reply src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts:273]: good catch, I was too focused on the when clause syntax. 🤣

Comment (gupta1) [reply src/sql/workbench/contrib/scripting/browser/scripting.contribution.ts]: Sure, made the change
