### PR TITLE
fix the find highlight issues

### LINKED ISSUE #15094: Highlighting of search text is off by 3 characters in some notebooks.
- Azure Data Studio Version:

Steps to Reproduce:

1. Search in a notebook for a string and sometimes the selection is off by 3 characters. On clicking next  the characters shift by 3 more characters an  so no.

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #15094 and #14455 

We had cleanMarkdownLinks to clean up markdown links back when we didn't use the renderedOutput of the markdown cell, to remove the link syntax with just the link. But we have come a long way with wysiwyg and the old logic doesn't make sense anymore. So removed it.
Added the mode change events to trigger findStateChange -> Previously on edit mode we have a code cell with markdown code and the rendered html text cell but now even in edit mode we can still be on rich text mode only and have only rendered output so updated the logic to check if the markdown is actually visible (which can happen in split view and markdown only mode) and search accordingly.
Also fixed the scroll issue to scroll to the current highlighted node.

### CODE REVIEW

**Review by lucyzhang929 — COMMENTED** [review]
Tested and it seems like the highlight being blocked by the cell toolbar issue is still happening.

Cell is not in edit mode:
Screen Shot 2021-04-15 at 11 42 42 AM

Cell is in edit mode:
Screen Shot 2021-04-15 at 11 43 04 AM

**Comment by MaddyDev** [comment]
> Tested and it seems like the highlight being blocked by the cell toolbar issue is still happening.
> 
> Cell is not in edit mode:
> Screen Shot 2021-04-15 at 11 42 42 AM
> 
> Cell is in edit mode:
> Screen Shot 2021-04-15 at 11 43 04 AM

Thanks @lucyzhang929 Fixed it now.

**Review by lucyzhang929 — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/find/notebookFindModel.ts [hunk 1]
```diff
@@ -535,7 +535,7 @@ export class NotebookFindModel extends Disposable implements INotebookFindModel
 
 	private searchFn(cell: ICellModel, exp: string, matchCase: boolean = false, wholeWord: boolean = false, maxMatches?: number): NotebookRange[] {
 		let findResults: NotebookRange[] = [];
-		if (cell.cellType === 'markdown' && cell.isEditMode && typeof cell.source !== 'string') {
+		if (cell.cellType === 'markdown' && (cell.showMarkdown || cell.currentMode === CellEditModes.SPLIT) && typeof cell.source !== 'string') {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/find/notebookFindModel.ts:538]: Would suggest adding a comment here explaining that this is for searching the markdown portion of the cell.

Although in general I think this logic could use some cleaning up to make it clearer what the different types of content you're searching could be : 

1. markdown cell & markdown pane visible -> search cell.source
2. markdown cell & WYSIWYG pane visible -> search cell.renderedOutputTextContent
2. non-markdown cell -> search source content directly

The first two and the last one are exclusive (cellType can only be one or the other)

So the logic would look something like 

```
if(cellType === 'markdown') {
   if(<markdown pane visible>) { 
        // search cell.source
   } 
   if(<rich text pane visible>) {
       // search cell.rederedOutputTextContent
   }
} else { 
    // search cell.source
}
```

This would be a lot easier to follow and understand. (you can make helper functions to combine the search logic for stuff like searching cell.source since those would likely be the same).

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/workbench/contrib/notebook/browser/find/notebookFindModel.ts (hunk 1 above)
Comment (MaddyDev) [reply src/sql/workbench/contrib/notebook/browser/find/notebookFindModel.ts:538]: Yep, I'll do that refactor in my next PR of Find (highlight all terms).
