### PR TITLE
fix DW sql project build failing

### LINKED ISSUE #15248: Error running command sqlDatabaseProjects.build: Invalid DSP in .sqlproj file.
I'm getting this error when I try to build the project in Az Data Studio. I built it successfully on visual studio 2019.

Error running command sqlDatabaseProjects.build: Invalid DSP in .sqlproj file. This is likely caused by the extension that contributes sqlDatabaseProjects.build.

Steps to Reproduce:

1. Bulid project. 

Here my `DSP` tag in `.sqlproj` file   `<DSP>Microsoft.Data.Tools.Schema.Sql.SqlDwDatabaseSchemaProvider</DSP>`

Wondering what changed. I haven't installed any other software or even an Az Data Studio update in a while.

- Azure Data Studio Version:
Version: 1.28.0 (user setup)
Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
Date: 2021-04-15T00:24:15.710Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #15248. This was exposed by the project dashboard changes, since the project's target version information was retrieved every build.
https://github.com/microsoft/azuredatastudio/blob/c58b7d35d781e0e9b8c2e18a299cd66e79cad2d9/extensions/sql-database-projects/src/controllers/projectController.ts#L183

### CODE REVIEW

File: extensions/sql-database-projects/src/common/constants.ts [hunk 1]
```diff
@@ -347,7 +348,8 @@ export const targetPlatformToVersion: Map<string, string> = new Map<string, stri
 	[sqlServer2016, '130'],
 	[sqlServer2017, '140'],
 	[sqlServer2019, '150'],
-	[sqlAzure, 'AzureV12']
+	[sqlAzure, 'AzureV12'],
+	[sqlDW, 'Dw']
```
Comment (udeeshagautam) [inline extensions/sql-database-projects/src/common/constants.ts:352]: small case w expected?

**Review by udeeshagautam — APPROVED** [review]

File: extensions/sql-database-projects/src/common/constants.ts (hunk 1 above)
Comment (kisantia) [reply extensions/sql-database-projects/src/common/constants.ts:352]: Yup. SSDT is strict on the casing of the version. Only Dw is allowed - DW, dW, and dw aren't allowed

**Review by SakshiS-harma — APPROVED** [review]
