### PR TITLE
Notebooks: Ensure WYSIWYG Mode for Keyboard Shortcuts

### LINKED ISSUE #14404: Text cell editor doesn't respect the 'Tab Moves Focus' setting
Steps to Reproduce:

1. Open a notebook and create a text cell
2. Run the 'Toggle Tab key Moves Focus ' command
image
3. Set the focus in the text editor and then press tab

Expected:
Just like in other editors, I should be able to move the keyboard focus out from the text cell

Actual:
focus stays in the text cell

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #14404.

We were incorrectly capturing keyboard shortcuts even outside of WYSIWYG mode, causing some functionality to not work (such as tab moves focus).

### CODE REVIEW

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 
 	@HostListener('document:keydown', ['$event'])
 	onkeydown(e: KeyboardEvent) {
-		if (this.isActive()) {
+		if (this.isActive() && this.isWYSIWYGMode()) {
```
Comment (barbaravaldez) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:64]: Is this listener only for WYSIWYG? Why we don't check if it's in Markdown mode as well?

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts [hunk 2]
```diff
@@ -461,6 +461,10 @@ export class TextCellComponent extends CellView implements OnInit, OnChanges {
 			this._model.updateActiveCell(undefined);
 		}
 	}
+
+	private isWYSIWYGMode(): boolean {
+		return this.cellModel && this.cellModel.showPreview && !this.cellModel.showMarkdown && this.cellModel.isEditMode;
```
Comment (Charles-Gagnon) [inline src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts:466]: Seems like something that should probably go into cellModel - having something like `currentMode` would be pretty useful I think and being explicit about mode changes makes sense to me instead of relying on the combination of a bunch of different states.

File: src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts (hunk 1 above)
Comment (chlafreniere) [reply src/sql/workbench/contrib/notebook/browser/cellViews/textCell.component.ts]: @barbaravaldez looking at the code I believe it is; we shouldn't override any keyboard shortcuts that already exist for editors (i.e. they already have undo/redo defined)

**Review by alanrenmsft — APPROVED** [review]

**Review by MaddyDev — APPROVED** [review]

**Review by halerankin — APPROVED** [review]

**Review by barbaravaldez — APPROVED** [review]
