### PR TITLE
Benjind/schema compare add aria label

### LINKED ISSUE #6730: A11y_AzureDataStudio(Schema,Dacpac,Backup)_SelectSource-Target_SchemaCompare_AI4D: Name property must not contain special characters as '...' for more commands button.
[“Check out Accessibility Insights! !](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS; #A11yTCS; #A11y_ADS_Schema_Dacpac_Backup; #Azure Data Studio; #DesktopApp; #Win10; #AI4D; #MAS4.1.2; 

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.10.0-insider (user setup)
Commit: 975e45061b073ecce2398d00c12f525d90e07b02
Date: 2019-08-08T19:22:13.572Z
VS Code 1.37.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
Nvda Version: 2019.2rc2

**Additional Details:**
Tools Name: Nvda
MAS References: MAS4.1.2

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Launch Accessibility Insights tool and hover the mouse over More commands button represented as '...'

**Actual:**
**Issue 1:** Name property must not contain special characters as '...' for 'Select Source' and 'Select Target' buttons.
**Issue 2:** Tooltip not displayed on keyboard navigation to 'Select Source' and 'Select Target' buttons.

**Expected:**
**Issue 1:** Name for 'Select Source' and 'Select Target' buttons should be available.
**Issue 2:** Tooltip should be displayed on keyboard navigation to 'Select Source' and 'Select Target' buttons.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: (https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx)

**User Impact:**
Screen reader users will not get to know the context of the button if it got announced as special characters.

**MAS Reference:**
MAS 4.1.2-
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}

**Attachment for Reference:**
image

image

### PR DESCRIPTION
**Pull request by Benjin**
Adds the ability to explicitly set the `aria-label` property of a button, which is used by screen-readers.
Sets `aria-label` for the ellipsis buttons in the SchemaCompare pane, as "..." is not accessible.

Addresses #6730 (not linking so that Accessibility testing team can be the ones to validate and close)

### CODE REVIEW

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 1]
```diff
@@ -814,7 +814,8 @@ export class SchemaCompareMainWindow {
 	private createSourceAndTargetButtons(view: azdata.ModelView): void {
 		this.selectSourceButton = view.modelBuilder.button().withProperties({
 			label: '•••',
-			title: localize('schemaCompare.sourceButtonTitle', 'Select Source')
+			title: localize('schemaCompare.sourceButtonTitle', 'Select Source'),
```
Comment (chlafreniere) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts]: localized strings should be double quoted.

**Comment by udeeshagautam** [comment]
I re-ran the PR build

**Comment by alanrenmsft** [comment]
@Benjin , please don't merge the changes, there is a build error: src/sql/base/browser/ui/button/button.ts(51,3): error TS2322: Type 'string | null' is not assignable to type 'string'.

please fix this one first.
