### PR TITLE
restore focus on escape

### LINKED ISSUE #12980: A11y_SQL Azure Data Studio_Import ExtensionModify Columns_Keyboard: The focus after using escape key on the list of items in column 2 row 2 drop down button is seen on the edit field beside it.
“[Check out Accessibility Insights! ](https://accessibilityinsights.io/)– Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#BM_SQLAzureDataStudio_Oct2020;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG2.4.3;#Benchmark;#Keyboard;#AINotInScope;

**Environment Details:**
Application Name: SQL Azure Data Studio
Version 1.22.1 User Setup
Windows Version: Windows10

**Repro Steps:**

1. Launch Azure Data Studio Insiders application.
2. Tab to server drop down and tab again to button new connection press enter key and add the server details.
3. Tab to the connected server and press enter key, use down key and select any database keep_MDW Right click on/ open the context menu for a database and select Data-tier application wizard from the context menu
4. Add data in specify input file screen and tab to "next" button and press enter.
5. Press enter on next button.
6. Tab to drop down button in cell column 2 row2 and press enter key.
7. Once the items have been expanded use the escape key to close the list.

**Actual:**
On using the escape key to close the list for the drop-down button in column 2 row2 the focus in on the edit field in column 2 row2 .

**Expected:**
The focus on using escape key on the list should be on the drop down button that opened the list.

**User Impact:**
The keyboard users will have to use an extra tab to move to the next column and this would disrupt the focus order.

**Attachment:**

[#12980_A11y_SQL Azure Data Studio_Import ExtensionModify Columns_Keyboard.zip](https://github.com/microsoft/azuredatastudio/files/5401664/12980_A11y_SQL.Azure.Data.Studio_Import.ExtensionModify.Columns_Keyboard.zip)

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #12980

there are 4 ways to invoke the dropdown list and the expected focus behavior when escape is pressed to close the dropdown list

click inside the textbox -> focus should go back to textbox
press down arrow key when textbox is being focused -> focus should go back to text box
click on the dropdown arrow when focus is not within the control: -> focus should go back to textbox (similar to native select control)
focus on the dropdown arrow and invoke it -> focus should go back to the dropdown arrow
the fix is to capture the focused element before showing the list and restore focus to it when escape is pressed.

### CODE REVIEW

**Review by aasimkhan30 — APPROVED** [review]

File: src/sql/base/parts/editableDropdown/browser/dropdown.ts [hunk 1]
```diff
@@ -209,8 +214,11 @@ export class Dropdown extends Disposable {
 		});
 
 		this._controller.onDropdownEscape(() => {
```
Comment (Charles-Gagnon) [inline src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: Is this also triggered when the dropdown is closed via other means such as selecting a value?

**Review by Charles-Gagnon — APPROVED** [review]

File: src/sql/base/parts/editableDropdown/browser/dropdown.ts (hunk 1 above)
Comment (aasimkhan30) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: No, it is only triggered when pressing the escape button.

Comment (Charles-Gagnon) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: That doesn't seem right then to me - shouldn't the behavior be the same?

Comment (aasimkhan30) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: I guess, we can add the same code to onSelectionChange()

Comment (alanrenmsft) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: the requirement of restoring keyboard focus is only required for escape key, when a value is selected, the focus should go to the textbox

Comment (Charles-Gagnon) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: When you say "the requirement" what are you referring to? Because I don't think we should take that issue as being the full description of correct behavior, it was calling out behavior that was specifically wrong but I wouldn't necessarily assume they'd list all the different scenarios and their expected results. And having it behave differently when selecting an item vs escaping out of the dropdown seems odd to me.

Comment (Charles-Gagnon) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: Where do you get the requirement of "when a value is selected, the focus should go to the textbox"?

Comment (alanrenmsft) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: the "requirement" of restoring keyboard focus is for escape key press scenario, there isn't a requirement of restoring keyboard focus when selection done, so probably I should say it makes more sense for the focus to go to the input box. I took a look at the SSMS one, the arrow is not a focusable element, I think that is probably the desired behavior, when you click on it, it will bring up the list, and when you use keyboard, you can already bring up the list by using ALT+Down key, what do you guys think? @Charles-Gagnon  @aasimkhan30

Comment (Charles-Gagnon) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: In the input box you're saying? That seems fine as long as we can make it clear through the screen reader that this is an expandable element.

Comment (aasimkhan30) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: Are you referring to something like this? https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-none.html

Comment (alanrenmsft) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: yes, this one, or the .NET editable combobox, they both are not exposing the dropdown arrow as a focusable element, but since we are using actionbar here, I am not sure how easy it is to make it not keyboard focusable.

Comment (Charles-Gagnon) [reply src/sql/base/parts/editableDropdown/browser/dropdown.ts:216]: You should be able to just override it with styles to set the tab index on the anchor element.

**Comment by alanrenmsft** [comment]
while looking into the issue, i noticed vscode already has a class to show an dropdown icon, same is used for the regular dropdown.

look at the database field in the screenshots below. it looks the same on macOS.

before:
image

after:

image

**Comment by alanrenmsft** [comment]
I am still working on this PR following the requirements here: https://www.w3.org/TR/wai-aria-1.1/#combobox

**Comment by alanrenmsft** [comment]
@Charles-Gagnon @aasimkhan30 , please take another look.

**Review by Charles-Gagnon — APPROVED** [review]
Nice, the arrow being different was one of those little things that's bugged me for a while!
