### PR TITLE
Fix issues with loading aliased kernels in notebooks

### LINKED ISSUE #20995: Kusto Notebook defaults to SQL kernel when opened
Version: 1.40.0-insider (Universal)
Commit: d5cf088ba7b794859438fd2c1902249fd1e6a947
Date: 2022-10-26T05:49:36.314Z (15 hrs ago)
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.6.0

Steps to Reproduce:

1. Open a Saved Kusto Notebook (that had just the kernel and save - then close the notebook and reopen it)
2. The Kernel should be Kusto but it is defaulted to SQL
image

Metadata of Notebook (shows Kusto as the kernel alias through the language_info):
```
{
    "metadata": {
        "kernelspec": {
            "name": "SQL",
            "display_name": "SQL",
            "language": "sql"
        },
        "language_info": {
            "name": "kusto",
            "version": ""
        }
    },
    "nbformat_minor": 2,
    "nbformat": 4,
    "cells": [
        {
            "cell_type": "markdown",
            "source": [
                "test"
            ],
            "metadata": {
                "azdata_cell_guid": "c646cedd-57d5-4f6f-a841-8b17f8248f8c"
            },
            "attachments": {}
        }
    ]
}
```
Expected: Should show Kusto kernel

### PR DESCRIPTION
**Pull request by corivera**
This PR address 2 issues related to using aliased kernels in notebooks e.g. Kusto and LogAnalytics.
1. Fixes a problem where the Kusto kernel was being reset to SQL when first opening a Kusto kernel notebook. When I added the new event for handle kernel additions, I re-used an existing "kernelChanged" event to notify the KernelDropdown, but that event was actually meant to notify when a client session had been initialized instead. Thus we were overwriting the saved kernel with the SQL default as soon as the session started. I'll removed that client session event in a subsequent PR, since it isn't actually used anywhere that I could tell.

2. Fixes a problem where trying to change between aliased kernels would fail, like changing to LogAnalytics from Kusto and vice versa. We were overwriting the new kernel alias when changing the kernel, which actually caused the kernelAlias to be cleared entirely and subsequently revert to SQL.

This PR fixes #20995

### CODE REVIEW

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 1]
```diff
@@ -1279,7 +1284,9 @@ export class NotebookModel extends Disposable implements INotebookModel {
 
 	private async updateKernelInfoOnKernelChange(kernel: nb.IKernel, kernelAlias?: string) {
 		await this.updateKernelInfo(kernel);
-		kernelAlias = this.kernelAliases.find(kernel => this._defaultLanguageInfo?.name === kernel.toLowerCase()) ?? kernelAlias;
+		if (!kernelAlias) {
+			kernelAlias = this.kernelAliases.find(k => this._defaultLanguageInfo?.name === k.toLowerCase());
```
Comment (corivera) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:1288]: This defaultLanguageInfo gets updated further down, so when changing from Kusto to LogAnalytics we would see the old kusto language state and overwrite kernelAlias to be Kusto, since Kusto is also in the aliases list here. Then we'd have a different alias to the kernel display name LogAnalytics right after this, causing the kernelAlias to be set to undefined, which causes the notebook kernel to be set to the underlying SQL kernel as a fallback.

File: src/sql/workbench/services/notebook/browser/models/notebookModel.ts [hunk 2]
```diff
@@ -264,6 +265,10 @@ export class NotebookModel extends Disposable implements INotebookModel {
 		return this._kernelsChangedEmitter.event;
 	}
 
+	public get kernelsAdded(): Event<nb.IKernel> {
```
Comment (Charles-Gagnon) [inline src/sql/workbench/services/notebook/browser/models/notebookModel.ts:268]: Please add a doc comment explaining when this event is fired (and it'd be great to do that for the other events as well since clearly there's some confusion with the naming)

**Review by Charles-Gagnon — APPROVED** [review]

**Review by lucyzhang929 — APPROVED** [review]

**Review by chlafreniere — APPROVED** [review]
