### PR TITLE
Fixed #4384 add await on disconnect

### LINKED ISSUE #4384: notebook disconnect should wait
- Azure Data Studio Version:

Steps to Reproduce:
1. open a new NB
2. make a sql connection from attachTo
3. close NB.
4. open a new NB immediately
5. the connection made in step 2 will show up in the attachTo list.

Expected:
The connection created from step 2 shouldn't be listed in attachTo

The issue is: 
Right now notebook disconnect doesn't wait.

### PR DESCRIPTION
**Pull request by YurongHe**
Added await on disconnect to make sure it is disconnected.

### CODE REVIEW

File: src/sql/parts/notebook/models/notebookModel.ts [hunk 1]
```diff
@@ -630,11 +630,11 @@ export class NotebookModel extends Disposable implements INotebookModel {
 			if (this.notebookOptions && this.notebookOptions.connectionService) {
 				let connectionService = this.notebookOptions.connectionService;
 				if (this._otherConnections) {
-					this._otherConnections.forEach(conn => connectionService.disconnect(conn).catch(e => console.log(e)));
+					notebookUtils.asyncForEach(this._otherConnections, async (conn) => await connectionService.disconnect(conn).catch(e => console.log(e)));
```
Comment (MattIrv) [inline src/sql/parts/notebook/models/notebookModel.ts]: Why this change? From reading the code I don't see much of a functional difference. Did you mean to await the call to `notebookUtils.asyncForEach` here?

File: src/sql/parts/notebook/notebookUtils.ts [hunk 2]
```diff
@@ -116,4 +116,10 @@ export function tryMatchCellMagic(input: string): string {
 	let match = magicRegex.exec(firstLine);
 	let magicName = match && match[1];
 	return magicName;
+}
+
+export async function asyncForEach(array, callback) {
```
Comment (MattIrv) [inline src/sql/parts/notebook/notebookUtils.ts]: this needs a return type

File: src/sql/parts/notebook/models/notebookModel.ts (hunk 1 above)
Comment (YurongHe) [reply src/sql/parts/notebook/models/notebookModel.ts]: Yes. otherwise array.forEach wouldn't wait.

File: src/sql/parts/notebook/notebookUtils.ts (hunk 2 above)
Comment (YurongHe) [reply src/sql/parts/notebook/notebookUtils.ts]: is it a coding standard?

Comment (kevcunnane) [reply src/sql/parts/notebook/notebookUtils.ts]: Yes it is, please add return type for all methods. is it a promise? I wouldn't know immediately. Similarly please type the inputs as it really isn't clear how all this works.

Comment (MattIrv) [reply src/sql/parts/notebook/notebookUtils.ts]: We need to update our TS Lint rules to enforce more stuff like this but it's helpful for people calling the function or modifying this code in the future because otherwise the types will show up as `any` and it'll be harder to figure out what this code is doing
