### PR TITLE
Benjin/project update bug

### LINKED ISSUE #18078: Project update says success but build and schema compare failed
image

### PR DESCRIPTION
**Pull request by Benjin**
Fixes #18078.  My investigation found an underlying problem that I haven't been able to address yet, but this PR fixes some extension-level logic and adds a work-around for the base issue.

The underlying issue is:
* The `schemaComparePublishProjectChanges` task in Tools Service sends a task result with the `success` boolean set to false (correct)
* The ADS task displays that the task failed (correct)
* The `result` object returned by `service.schemaComparePublishProjectChanges` has its success boolean set to true (_incorrect_)

How ADS gets two different success statuses for the same task... I don't know.

### CODE REVIEW

File: extensions/sql-database-projects/src/controllers/projectController.ts [hunk 1]
```diff
@@ -534,21 +534,25 @@ export class ProjectsController {
 
 		const result: mssql.SchemaComparePublishProjectResult = await service.schemaComparePublishProjectChanges(operationId, projectPath, fs, utils.getAzdataApi()!.TaskExecutionMode.execute);
 
-		const project = await Project.openProject(projectFilePath);
+		result.success = result.success && result.errorMessage === '';
```
Comment (Benjin) [inline extensions/sql-database-projects/src/controllers/projectController.ts:537]: This line is the patch for the unfixed underlying issue.  Even if that were fixed, the other changes in this PR would still be bugs.

File: extensions/schema-compare/src/schemaCompareMainWindow.ts [hunk 2]
```diff
@@ -913,20 +912,19 @@ export class SchemaCompareMainWindow {
 					this.applyButton.enabled = true;
 					this.applyButton.title = loc.applyEnabledMessage;
 				}
+				else if (this.targetEndpointInfo.endpointType === mssql.SchemaCompareEndpointType.Project) {
```
Comment (kisantia) [inline extensions/schema-compare/src/schemaCompareMainWindow.ts:915]: nit: else if should be on the same line as the } on the line above

File: extensions/sql-database-projects/src/controllers/projectController.ts (hunk 1 above)
Comment (kisantia) [inline extensions/sql-database-projects/src/controllers/projectController.ts:537]: it seems a little strange to be reseting the value of result.success instead of having a new variable or having the if condition be checking result success and no error message

**Review by kisantia — APPROVED** [review]

File: extensions/sql-database-projects/src/controllers/projectController.ts (hunk 1 above)
Comment (Benjin) [reply extensions/sql-database-projects/src/controllers/projectController.ts:537]: Given the spot of code you found, it seems that `result.success` being true is by design, I'll key off of the error message.  I redefined the success bool because I was hedging my bets that that was wrong.

File: extensions/schema-compare/src/schemaCompareMainWindow.ts (hunk 2 above)
Comment (Benjin) [reply extensions/schema-compare/src/schemaCompareMainWindow.ts:915]: whoops; been working in DacFx for too long
