### PR TITLE
Fix #6576 Spark job submit fails from command palette

### LINKED ISSUE #6576: Spark job submit fails from command palette
Broken in 2 ways:
- If already connected to 1 SQL server, fails with error accessing label of undefined.
- If not connected, we should prompt for connection

### PR DESCRIPTION
**Pull request by kevcunnane**
- Fix spark job failing when 1 or more servers are connected
and listed in getActiveConnections
- If nothing is connected, prompts to choose a server
- Added option to dropdown when 1 or more server is connected
to support picking a different connection

Root bug was trying to access "host" not "server" in options bag, which no longer exists.

**Screenshot - new option in prompt**
image

### CODE REVIEW

File: extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts [hunk 1]
```diff
@@ -49,31 +55,61 @@ export class OpenSparkJobSubmissionDialogCommand extends Command {
...
+		let errorMsg = localize('sparkJobSubmission_NoSqlSelected', 'No SQL Server is selected.');
 		if (!selectedHost) { throw new Error(errorMsg); }
 
 		let sqlConnection = connectionMap.get(selectedHost);
 		if (!sqlConnection) { throw new Error(errorMsg); }
 
 		let sqlClusterConnection = await SqlClusterLookUp.getSqlClusterConnection(sqlConnection);
 		if (!sqlClusterConnection) {
-			throw new Error(LocalizedConstants.sparkJobSubmissionNoSqlBigDataClusterFound);
+			throw new Error(localize('errorNotSqlBigDataCluster', 'The selected server is not a SQL Server big data cluster'));
```
Comment (alanrenmsft) [inline extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts]: maybe: The selected server does not belong to a SQL Server big data cluster ?

File: extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts [hunk 2]
```diff
@@ -49,31 +55,61 @@ export class OpenSparkJobSubmissionDialogCommand extends Command {
...
+			connectionList = connectionList.filter(conn => conn.providerName === constants.sqlProviderName && (<MssqlOptions><any>conn.options).server);
+		}
+		// Prompt choice if we have active connections
 		if (connectionList && connectionList.length > 0) {
-			connectionList.forEach(conn => {
-				if (conn.providerName === constants.sqlProviderName) {
-					displayList.push(conn.options.host);
-					connectionMap.set(conn.options.host, conn);
-				}
+			let selectConnectionMsg = localize('selectOtherServer', 'Select other SQL Server');
```
Comment (alanrenmsft) [inline extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts]: double quote the actual string

File: extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts [hunk 3]
```diff
@@ -49,31 +55,61 @@ export class OpenSparkJobSubmissionDialogCommand extends Command {
...
+			let displayList: string[] = [];
+			if (connectionList && connectionList.length > 0) {
```
Comment (alanrenmsft) [inline extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts]: this is already true, we are in this condition scope already.

File: extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts [hunk 4]
```diff
@@ -49,31 +55,61 @@ export class OpenSparkJobSubmissionDialogCommand extends Command {
...
+
+		// Show connection dialog if still don't have a server
+		if (showConnectionDialog) {
+			let connection = await azdata.connection.openConnectionDialog([constants.sqlProviderName]);
+			if (connection) {
+				let options: MssqlOptions = <any>connection.options;
+				connectionMap.set(options.server, connection);
+				selectedHost = options.server;
+				// Wait an appropriate timeout so that the serverInfo object can populate...
+				await timeout(150);
```
Comment (alanrenmsft) [inline extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts]: do we really need this? is the openConnectionDialog returning before the connection.options are set?

File: extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts (hunk 3 above)
Comment (kevcunnane) [reply extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts]: Thanks - missed in a refactor

File: extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts (hunk 4 above)
Comment (kevcunnane) [reply extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts]: We do - `SqlClusterLookUp.getSqlClusterConnection` queries the `getServerInfo` function. If I don't do a timeout, it will be null and connect will fail. If I timeout, the call has time to set the connection in the `connectionManagementService._connectionStatusManager` object and works. Otherwise it isn't set yet, and I cannot figure out how to cleanly wait on / ensure that this is available.

File: extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts (hunk 1 above)
Comment (kevcunnane) [reply extensions/mssql/src/sparkFeature/dialog/dialogCommands.ts]: nice, will update
