### PR TITLE
Column/Table Drag & Drop

### LINKED ISSUE #3630: Support drag-n-drop columns and tables into Query Editor
- Azure Data Studio Version:1.2.4

Steps to Reproduce:
when writing the query I can not drag tables or columns from server navigation pane. This feature is available in SSMS
annotation 2018-12-17 090330

### PR DESCRIPTION
**Pull request by cssuh**
This PR introduces the base functionality for drag/drop in ADS.  The purpose of this PR is to get some technical feedback on the implementation of this feature and suggestions on how I can improve it (I wanted to do this before I got too far along in the development).

Here is my current TODO list:
- ~~add parsing for the column label so it is correctly formatted~~
- Some fixes in dnd.ts (parameterize)
- ~~Add SQL Carbon Edit tags in the VS Code changes~~

Future enhancements (not meant to be included in this PR):
- Fix the table collapsing/expanding when clicked & dragged
- Be able to drag the table/column over any part of the text (will only be dropped where your typing cursor is currently)
- Remove the large blue box highlighting
- Add more components to be dragged/dropped (also folders)

DragDropDev

This PR fixes #3630

### CODE REVIEW

File: src/vs/base/parts/tree/browser/treeView.ts [hunk 1]
```diff
@@ -1431,7 +1433,7 @@ export class TreeView extends HeightMap {
 
 		// can be null
 		let currentDropTarget = item.id === this.inputItem.id ? this.inputItem : this.items[item.id];
-
+		console.log(currentDropTarget);
```
Comment (aaomidi) [inline src/vs/base/parts/tree/browser/treeView.ts:1436]: console.log remaining here

File: src/vs/base/parts/tree/browser/treeView.ts [hunk 2]
```diff
@@ -1556,6 +1558,23 @@ export class TreeView extends HeightMap {
...
+			if (i.substring(0, 1) === '(') {
+				break;
+			}
+			else {
+				columnArr.push(i);
+			}
+		}
+		let columnStr = columnArr.join(' ');
+
+		return columnStr;
```
Comment (abist) [inline src/vs/base/parts/tree/browser/treeView.ts:1574]: I'm assuming this is to handle cases like objects which have `(System-Versioned)` in them. However, this would also get rid of labels that actually have parentheses in them.

Comment (aaomidi) [reply src/vs/base/parts/tree/browser/treeView.ts:1574]: Are these table fields populated on SQLToolsServer? might be something we can pass in directly.

Also whoever is using parentheses in field/table name really hates their developers 😄

File: src/vs/base/browser/dnd.ts [hunk 3]
```diff
@@ -57,6 +57,12 @@ export const DataTransfers = {
 	 */
 	RESOURCES: 'ResourceURLs',
 
+	/**
```
Comment (aaomidi) [inline src/vs/base/browser/dnd.ts:60]: sql carbon edit

File: src/vs/base/parts/tree/browser/treeView.ts [hunk 4]
```diff
@@ -1556,6 +1558,23 @@ export class TreeView extends HeightMap {
 		return item.top < this.lastRenderTop + this.lastRenderHeight && item.top + item.height > this.lastRenderTop;
 	}
 
+	private parseLabel(label) {
```
Comment (aaomidi) [inline src/vs/base/parts/tree/browser/treeView.ts:1561]: Move this method to somewhere in the sql path

File: src/vs/base/parts/tree/browser/treeView.ts [hunk 5]
```diff
@@ -1279,7 +1279,11 @@ export class TreeView extends HeightMap {
 		}
 
 		e.dataTransfer.effectAllowed = 'copyMove';
-		e.dataTransfer.setData(DataTransfers.RESOURCES, JSON.stringify([item.uri]));
+
+		// {{SQL CARBON EDIT}}
+		e.dataTransfer.setData(DataTransfers.RESOURCES, JSON.stringify([`${element.nodeTypeId}:${item.uri}?${element.metadata.schema ? element.metadata.schema + '.' + element.metadata.name : element.metadata.name}`]));
```
Comment (abist) [inline src/vs/base/parts/tree/browser/treeView.ts:1284]: I think instead of making changes in the `vs` side of code and then adding the `SQL Carbon Edit` tag, we should change these files instead - 

src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts
src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts

These files control the server tree. Changing the `treeview` in `vs` would change the behavior of all the trees

File: src/vs/workbench/browser/dnd.ts [hunk 6]
```diff
@@ -176,14 +178,25 @@ export class ResourcesDropHandler {
 	}
 
 	async handleDrop(event: DragEvent, resolveTargetGroup: () => IEditorGroup | undefined, afterDrop: (targetGroup: IEditorGroup | undefined) => void, targetIndex?: number): Promise<void> {
-		const untitledOrFileResources = extractResources(event).filter(r => this.fileService.canHandleResource(r.resource) || r.resource.scheme === Schemas.untitled);
+
```
Comment (abist) [inline src/vs/workbench/browser/dnd.ts:181]: Please put this logic in the `drop` function of `dragAndDropController.ts` instead. The controller class has a good API for any tree that needs custom implementation, and you should be able to do this without changing the underlying logic of the drag and drop.

File: src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts [hunk 7]
```diff
@@ -29,9 +31,11 @@ export class ServerTreeDragAndDrop implements IDragAndDrop {
 	public getDragURI(tree: ITree, element: any): string {
 		if (element instanceof ConnectionProfile) {
 			return (<ConnectionProfile>element).id;
-		}
-		else if (element instanceof ConnectionProfileGroup) {
+		} else if (element instanceof ConnectionProfileGroup) {
 			return (<ConnectionProfileGroup>element).id;
+
```
Comment (abist) [inline src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts:36]: What I would suggest here is to have all the changes in the `sql` side. You can get rid of the changes on the `vs` side by actually sending in the data by changing the `DragAndDrop` class right here. Since you are already sending the URI, you can perhaps have a dictionary that maps URI's to elements here. So, without changing the inner implementation, you can get the data directly by changing the `drop` function here to retrieve the data from the dictionary based on the URI. 
A good way to realize that this wasn't the correct way to do this is by observing that you had to change the interface in order for it to work. Usually, you'd never have to change an interface, especially on the `vs` side 😄

File: src/sql/workbench/services/objectExplorer/browser/treeCreationUtils.ts [hunk 8]
```diff
@@ -46,7 +46,7 @@ export class TreeCreationUtils {
 		const actionProvider = instantiationService.createInstance(ServerTreeActionProvider);
 		const renderer = instantiationService.createInstance(ServerTreeRenderer, false);
 		const controller = instantiationService.createInstance(ServerTreeController, actionProvider);
-		const dnd = instantiationService.createInstance(ServerTreeDragAndDrop);
+		const dnd = instantiationService.createInstance(TreeDragAndDrop);
```
Comment (abist) [inline src/sql/workbench/services/objectExplorer/browser/treeCreationUtils.ts:49]: You can let the name be what it was because it was more specific. This drag and drop controller is specific to servers.

File: src/vs/base/parts/tree/browser/tree.ts [hunk 9]
```diff
@@ -500,7 +502,8 @@ export interface IDragAndDrop {
 	/**
 	 * Sent when the drag operation is starting.
 	 */
-	onDragStart(tree: ITree, data: IDragAndDropData, originalEvent: Mouse.DragMouseEvent): void;
+	// {{SQL CARBON EDIT}}
+	onDragStart(tree: ITree, data: IDragAndDropData, originalEvent: Mouse.DragMouseEvent, element: any, item: ViewItem): void;
```
Comment (abist) [inline src/vs/base/parts/tree/browser/tree.ts:506]: You don't need to change the interface here. You can get the `element` from `data`, as it's always going to be the first element in the array if you're support drag and drop of only a single element at once. You can also get rid of `item` since you can retrieve `item.uri` as `data.elements[0].id`

File: src/vs/base/parts/tree/browser/treeView.ts [hunk 10]
```diff
@@ -1300,7 +1302,7 @@ export class TreeView extends HeightMap {
 		this.currentDragAndDropData = new dnd.ElementsDragAndDropData(elements);
 		StaticDND.CurrentDragAndDropData = new dnd.ExternalElementsDragAndDropData(elements);
 
-		this.context.dnd!.onDragStart(this.context.tree, this.currentDragAndDropData, new Mouse.DragMouseEvent(e));
+		this.context.dnd!.onDragStart(this.context.tree, this.currentDragAndDropData, new Mouse.DragMouseEvent(e), element, item);
```
Comment (abist) [inline src/vs/base/parts/tree/browser/treeView.ts:1305]: Please revert the changes in this file

File: src/vs/workbench/browser/dnd.ts [hunk 11]
```diff
@@ -172,14 +174,25 @@ export class ResourcesDropHandler {
...
+		// {{SQL CARBON EDIT}}
```
Comment (abist) [inline src/vs/workbench/browser/dnd.ts:178]: This logic should go in `src/vs/workbench/browser/parts/editor/editorDropTarget.ts` instead of `src/vs/workbench/browser/dnd.ts` since we only want to change the behavior of drag and drop in the editor. Put this logic in the `handleDrop` function of `src/vs/workbench/browser/parts/editor/editorDropTarget.ts`

File: src/vs/base/parts/tree/browser/tree.ts (hunk 9 above)
Comment (cssuh) [reply src/vs/base/parts/tree/browser/tree.ts:506]: Screen Shot 2020-06-12 at 1 27 26 PM
When I try to use `data.elements[0].id` it gives me an error saying `Property 'elements' does not exist on type 'IDragAndDropData'.` even though it seems like the code works when I run through with the debugger

Comment (abist) [reply src/vs/base/parts/tree/browser/tree.ts:506]: From your screenshot, I can see that `data`'s type is `ElementsDragAndDropData`, which exists in `src/vs/base/browser/ui/list/listView.ts`, which just implements `IDragAndDropData`. You could either change the function parameter type to be `ElementsDragAndDropData` or you could do something like `(data as ElementsDragAndDropData).elements`

**Comment by cssuh** [comment]
agreed, although it looks like I may need to add a test so the code coverage doesn't decrease
thank you for the review it was extremely helpful

File: src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts [hunk 12]
```diff
@@ -44,16 +47,24 @@ export class ServerTreeDragAndDrop implements IDragAndDrop {
...
 	/**
 	 * Called when the drag operation starts.
 	 */
-	public onDragStart(tree: ITree, data: IDragAndDropData, originalEvent: DragMouseEvent): void {
+	public onDragStart(tree: ITree, dragAndDropData: IDragAndDropData, originalEvent: DragMouseEvent): void {
 		TreeUpdateUtils.isInDragAndDrop = true;
+		const data = dragAndDropData.getData();
+		const element = data.elements[0];
+		if (element.nodeTypeId === 'Column' || element.nodeTypeId === 'Table') {
+			originalEvent.dataTransfer.setData(DataTransfers.RESOURCES, JSON.stringify([`${element.nodeTypeId}:${element.id}?${element.metadata.schema ? element.metadata.schema + '.' + element.metadata.name : element.metadata.name}`]));
```
Comment (abist) [inline src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts:66]: You could change this too 
```
const schema = element.metadata.schema;
const name = element.metadata.name;
originalEvent.dataTransfer.setData(DataTransfers.RESOURCES, JSON.stringify([`${element.nodeTypeId}:${element.id}?${schema ? schema + '.' + name : name}`]));
```

File: src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts [hunk 13]
```diff
@@ -27,33 +28,56 @@ export class ServerTreeDragAndDrop implements IDragAndDrop {
...
 
 	/**
 	 * Called when the drag operation starts.
 	 */
-	public onDragStart(tree: ITree, data: IDragAndDropData, originalEvent: DragMouseEvent): void {
+	public onDragStart(tree: ITree, dragAndDropData: IDragAndDropData, originalEvent: DragMouseEvent): void {
 		TreeUpdateUtils.isInDragAndDrop = true;
+		const data = dragAndDropData.getData();
+		const element = data[0];
+		if (element.nodeTypeId === 'Column' || element.nodeTypeId === 'Table') {
```
Comment (aaomidi) [inline src/sql/workbench/services/objectExplorer/browser/dragAndDropController.ts:76]: i see you're referencing this in two parts of the code, would it make sense for this to be an enum? Or some sort of helper method
