### PR TITLE
Fixes #9397 Launch onenote links

### LINKED ISSUE #9397: Links which launch OneNote do not work from Azure Data Studio
Issue Type: <b>Bug</b>

Links which launch OneNote start with "onenote:". These do not work from markdown or Notebooks. Azure Data Studio silently fails on this. Clicking on such a link is no-op.

Azure Data Studio version: azuredatastudio 1.15.0 (e57eb999fc5f1e000477da8fe0b8679ff0bfd57b, 2020-02-12T20:48:43.389Z)
OS version: Windows_NT x64 10.0.18363

### PR DESCRIPTION
**Pull request by qifahs**
This PR fixes #9397 

For the livesite TSG scenario, it is common place to have "onenote:" links. These links launch OneNote and open the page. This PR adds support to allow "onenote:" links.

### CODE REVIEW

File: src/vs/editor/browser/services/openerService.ts [hunk 1]
```diff
@@ -116,7 +116,9 @@ export class OpenerService implements IOpenerService {
 		// Default opener: maito, http(s), command, and catch-all-editors
 		this._openers.push({
 			open: async (target: URI | string, options?: OpenOptions) => {
-				if (options?.openExternal || matchesScheme(target, Schemas.mailto) || matchesScheme(target, Schemas.http) || matchesScheme(target, Schemas.https)) {
+				// {{SQL CARBON EDIT}} - Begin
```
Comment (chlafreniere) [inline src/vs/editor/browser/services/openerService.ts:119]: can we just pass in the openExternal option from the caller side where we need this? Would there be anywhere else besides notebooks where this is applicable?

Comment (anthonydresser) [reply src/vs/editor/browser/services/openerService.ts:119]: You shouldn't need these edits, it checks for the openExternal field first. just call the function with openExternal options as true.

Comment (qifahs) [reply src/vs/editor/browser/services/openerService.ts]: Thanks for the tip. Sent an update which limits the change to the linkHandler directive, and affects the Onenote links only.
