### PR TITLE
Fix dashboard icons

### LINKED ISSUE #15394: "Create Project from Database" Action has No Icon on Server Dashboard Toolbar
This is what I see from the toolbar (maybe just needs an extension refresh?)

image

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #15394

With the VS Code merge they changed how menu items were getting their background-image set and now use a couple of new rules that reference a var set by the code. https://github.com/microsoft/azuredatastudio/blob/main/src/vs/platform/actions/browser/menuEntryActionViewItem.css

These rules take precedence over the ones we add inline though (since they're more specific) and as a result that icon is overwritten and since the new var is never set in our code the icon is blank.

This fix isn't ideal - using !important isn't great here. But I was worried that trying to change anything else with the VS stuff would lead to more problems with their icons. If we wanted to fix this in a better way I think it would be best to look at getting rid of this custom logic since I can't really see any reason for using what we have over what they're doing. But I didn't want to try and make bigger changes like that this late in the release so I opted for the "safer" approach. 

After fix : 

image

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

File: src/vs/platform/actions/browser/menuEntryActionViewItem.ts [hunk 1]
```diff
@@ -304,8 +304,8 @@ export class LabeledMenuItemActionItem extends MenuEntryActionViewItem {
 					iconClass = ICON_PATH_TO_CSS_RULES.get(iconPathMapKey)!;
 				} else {
 					iconClass = ids.nextId();
-					createCSSRule(`.codicon.${iconClass}`, `background-image: ${asCSSUrl(item.icon.light || item.icon.dark)}`);
-					createCSSRule(`.vs-dark .codicon.${iconClass}, .hc-black .codicon.${iconClass}`, `background-image: ${asCSSUrl(item.icon.dark)}`);
+					createCSSRule(`.codicon.${iconClass}`, `background-image: ${asCSSUrl(item.icon.light || item.icon.dark)} !important`);
```
Comment (kburtram) [inline src/vs/platform/actions/browser/menuEntryActionViewItem.ts:307]: could you add the // {{SQL CARBON EDIT}} tags?  They are still useful during the code merge process to understand why there are merge conflicts.

**Review by kburtram — APPROVED** [review]

File: src/vs/platform/actions/browser/menuEntryActionViewItem.ts (hunk 1 above)
Comment (Charles-Gagnon) [reply src/vs/platform/actions/browser/menuEntryActionViewItem.ts]: Alright, cleaned it up. No logic changed - just moved the two custom classes into our own code.
