### PR TITLE
Fix New Notebook issues

### LINKED ISSUE #4936: Add a shortcut to create a notebook in the document well. (aduxr)
Add the command and shortcut for creating a new notebook to the ADS document well (aka watermark).

image

### LINKED ISSUE #5338: New Notebook menu item should be next to New Query
- Azure Data Studio Version: `master`

It seems like `New Notebook` item should be next to `New Query` since these are somewhat related commands.

image

### PR DESCRIPTION
**Pull request by kevcunnane**
- Fix #5338 New Notebook menu item should be next to New Query
- Fix #4936 Add a shortcut to create a notebook in the document well

Created a built-in New Notebook command
that routes to the existing extension-based command.
This avoided a rearchitecture that was more complex that seemed worth it.
Per VSCode patterns, used a _ modifier for the existing command so it's "private"

**Watermark**
image

** Right-click menu**
image

### CODE REVIEW

File: src/vs/workbench/contrib/watermark/browser/watermark.ts [hunk 1]
```diff
@@ -50,6 +51,10 @@ const newSqlFile: WatermarkEntry = {
 	text: nls.localize('watermark.newSqlFile', 'New SQL File'),
 	id: GlobalNewUntitledFileAction.ID
 };
+const newNotebook: WatermarkEntry = {
+	text: nls.localize('watermark.newNotebook', 'New Notebook'),
```
Comment (chlafreniere) [inline src/vs/workbench/contrib/watermark/browser/watermark.ts]: double quotes 😄
